### ISSUE TITLE
suggestion: use a vector-db like pinecone to overcome the token limits?

### ISSUE THREAD

**Issue by teamgroove** [paul-gauthier/aider#1]

**Comment by paul-gauthier** [comment]
FYI,I just released some improvements to how aider manages the context window 

https://github.com/paul-gauthier/aider/blob/main/docs/ctags.md

**Comment by teamgroove** [comment]
Wow! That's an impressive solution and very "compressed". It amazes me, that ctags is totally sufficient. Great idea + great, that it works.! Contratulations! I like your blog-post about it, too!
