### ISSUE TITLE
Add files with wildcards

### ISSUE THREAD

**Issue by tiagoefreitas** [paul-gauthier/aider#10]
For small projects it would be nice to be able to add all files and/or using wildcards.
Its annoying having to do it every time unless I missed something.

**Comment by paul-gauthier** [comment]
Sure, I'm happy to add ease of use features. Help me understand your goal... What exactly are you trying to do?

If your code is in a git repo, then aider should automatically notice all the files in the repo. As you type a filename inside the chat, it should auto-complete the filename for you. And just mentioning a file by name will cause aider to prompt for permission to add it to the chat context. Same thing if GPT mentions one of your filenames.

Are your files in a git repo? I really recommend that when working with aider.

You can also invoke aider with wildcards on the command line. So run `aider *.py` to add all your python files to the chat context.

**Comment by tiagoefreitas** [comment]
Yes its in a repo and the autocomplete is working, but since its a small project I need a few files always in the context, and its cumbersome to have to add them every time I launch it. Good to know about the command line, that is enough for my purposes.
Now it would also be very useful to automatically or easily add library files that are in the files imports, even if they are not in the same repo. It should only add the interfaces if available as the full code is usually not needed.
The workaround I will try for now is to link the main libs to my repo so aider at least finds the files.

I was working with typescript and GPT gets the types wrong sometimes for lack of context, this may solve it, but for now I will switch to vanilla js as typecript is not really needed for non-production code.

**Comment by paul-gauthier** [comment]
Glad to hear the command line wildcarding is working for you.

And absolutely, I am working towards solutions where aider will automagically get access to the call signatures of libraries/packages that it is referencing. This is a common problem with GPT. It knows the right package/lib/function to call, but it doesn't quite remember the args/types/api/etc.
