### ISSUE TITLE
aider hang forever

### ISSUE THREAD

**Issue by jzhang-brex** [paul-gauthier/aider#100]
![CleanShot 2023-07-13 at 21 26 45](https://github.com/paul-gauthier/aider/assets/1160963/1f0c87b0-475c-4942-8a47-c9be514f3565)

It just stoped at this step forever. I don't know how I can get you more information to replicate it. I tried run it with `--verbose` but it just print out all the configuration value.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

Do you get a traceback or any additional information when you hit ^C to force aider to exit?

Is it a *very* large repository?

Is the repo dirty, with a large number of uncommitted changes?

**Comment by w3bdesign** [comment]
@jzhang-brex 

I have experienced the same issue and wonder if it can be connected to streaming responses.

Can you try adding `--no-stream` to the command-line before running aider and see if it fixes or improves anything?

**Comment by paul-gauthier** [comment]
Also, can you tell me what version you're running? The latest version will display it when you run the program. Or you can run with `--version` to print it out. 

You should make sure you've upgraded to 0.8.3 because there was a bug like this in 0.8.1. That was the default version on pypi for about a day before the bug fix was released.

**Comment by jzhang-brex** [comment]
> Is it a very large repository?

Yes, it's a huge repo. However, the issue is intermittent and I got it working most of the time. 

My version is fairly behind. I was on `0.7.1`. Let me upgrade and observe if the issue continue. If I didn't reply within 2 weeks, you can consider I can no longer reproduce the issue.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by linusjf** [comment]
I'm having a similar problem with aider. I enter my prompt and then it hangs in both single-line and multi-line mode. Ctrl C and trying it again with the same prompt works. This is irrespective of which provider I select. It has caused problems with both OpenRouter and DeepMind.
