### ISSUE TITLE
Change the AI ​​model in Aider browser

### ISSUE THREAD

**Issue by testappform** [paul-gauthier/aider#1000]
### Issue

![image](https://github.com/user-attachments/assets/237745fc-a540-43af-972b-be63a9ce5c58)
Hello
I tried a lot to change the model in aider browser
But I couldn't
I want to know how to change it to groq

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

With the browser version, you need to set the model when you launch aider:

```
aider --browser --model <model-name>
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
