### ISSUE TITLE
Add third party git repo information to chat

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#1002]
### Issue

When working with a less well known codebase, LLMs can be inaccurate or have out-of-date information.
It would be good to be able to add a map of that repo to the current chat, so that coding suggestions from the LLM are improved.

My current solution is to add some information using the /web scraper, but the git repo mapping seems pretty good and it would be nice to extend this.

### Version and model info

Aider version: Latest
LLM: Claude Sonnet 3.5

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can make a repo map of one repo with:

```
aider --show-repo-map > repomap.md
```

And then add that file to the other repo.

**Comment by lockmeister** [comment]
handy, thanks!
