### ISSUE TITLE
Remove dev dependencies from the final build

### ISSUE THREAD

**Issue by chapayevdauren** [paul-gauthier/aider#1006]
### Issue

When I try to install the aider package locally with other packages like flake8 or pycodestyle, it is conflicting with them.
```
Because packageA depends on aider-chat (0.42.0) which depends on flake8 (7.1.0), flake8 is required.
So, because packageA depends on flake8 (7.1.1), version solving failed.
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Those are not "dev" dependencies. Aider ships with built in linters for popular language, and uses flake8 for python. The aider dev deps are installed with the `[dev]` extra, like:

```
pip install aider-chat[dev]
# or
pip install -e .[dev]
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/install/pipx.html
