### ISSUE TITLE
Check for keywords which suggest parts of the original code have been left out (Claude 3.5 Sonnet)

### ISSUE THREAD

**Issue by arjanspeelman** [paul-gauthier/aider#1007]
### Issue

Claude 3.5 Sonnet has the habit of sometimes not showing parts of the code which have no changes to them. Those will be marked with things like '// Existing fields...' or '// ... (rest of the fields)' (exact text varies). I just noticed that part of my code now contains these placeholder and I've lost my original code. Would it be possible to detect these keywords and instead of processing that output, ask Claude for the full output so we don't lose code?

### Version and model info

Aider v0.47.0
claude-3.5-sonnet

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

FYI, you can always do `/undo` if you don't like the changes to your code.

Claude is already strongly prompted to deliver full code. But LLMs don't always follow instructions, unfortunately.

This doc may be helpful:
https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
