### ISSUE TITLE
The benchmark test encountered a problem

### ISSUE THREAD

**Issue by WentaoTan** [paul-gauthier/aider#1008]
### Issue

dirname: 2024-08-05-18-58-25--test2
  test_cases: 27
  model: ourModel
  edit_format: whole
  commit_hash: c45688c-dirty
  pass_rate_1: 25.9
  pass_rate_2: 33.3
  percent_cases_well_formed: 100.0
  **error_outputs: 10**
  num_malformed_responses: 0
  num_with_malformed_responses: 0
  **user_asks: 9**
  lazy_comments: 0
  syntax_errors: 0
  indentation_errors: 0
  exhausted_context_windows: 0
  **test_timeouts: 2**
  command: aider --model ourModel
  date: 2024-08-05
  versions: 0.47.2-dev
  seconds_per_case: 173.1
  total_cost: 0.9951

The status will be printed all the time during the test. I found that sometimes the values ​​**error_outputs: 10** **user_asks: 9** will increase. The model I use is my own local model, which is written in the form of API in imitation of the format of OpenAI GPT. Under what circumstances will these two values ​​increase? What does it mean?

Thank you for your help, looking forward to your answer!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You would have to check the logs for your benchmark, and the source code for the benchmarking tool to really figure out what triggered those counters to increment. They go up if aider outputs error messages (in red) or asks the "user" a question.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
