### ISSUE TITLE
some commits still created in `--no-auto-commits` mode

### ISSUE THREAD

**Issue by tmm1** [paul-gauthier/aider#101]
i prefer to create all git commits myself, so i use aider with `--no-auto-commits`

however i've encountered certain scenarios were commits are still made unexpectedly

- when adding a new file there's a prompt asking to "create and add to git"

   i wish this would only create and not commit the empty file.

- i've randomly had commits created with the exact message `Refactor code to improve performance and readability./ls` and no chat history attached

    i do use `/ls` but i'm not sure how that ended up at the end of the commit message

**Comment by tmm1** [comment]
> * randomly had commits created

ah, so this is coming from the welcome message:

```
Git repo has uncommitted changes.
Commit before the chat proceeds [y/n/commit message]?
```

where a commit message is filled in. i guess i typed `/ls<enter>` and unexpectedly created a commit. i would prefer if that prompt was omitted in `--no-auto-commits` mode.

**Comment by tmm1** [comment]
> * i wish this would only create and not commit the empty file.

another variant of this is when i've already created a file and added it to my git index, but since it isn't in the commit history yet, aider doesn't recognize it or even show it in `/ls`

when i `/add` to bring it in, it will force commit whatevers in my index:

```
> /add lib/common.sh                                                                                                       

Added lib/common.sh to the chat
Commit 6d486a4 aider: Added lib/common.sh
```

**Comment by tmm1** [comment]
additionally, `/undo` doesn't work immediately after `/add` to undo that commit

```
> /undo                                                                                                                    

The last commit was not made by aider in this chat session.
```

**Comment by paul-gauthier** [comment]
Thanks for the feedback on aider's use of git. I added a FAQ entry that explains a bit more clearly how aider uses git. Please let me know if this info is helpful.

https://aider.chat/docs/faq.html#how-does-aider-use-git

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by tmm1** [comment]
Thanks, `--no-git` does what I want
