### ISSUE TITLE
Webversion: GIT-stuff

### ISSUE THREAD

**Issue by ophoria** [paul-gauthier/aider#1010]
### Issue

The following is shown in the console, but it is never mentioend int he web GUI: On the contrary it reports all changes were done there.

**
Committing config.py before applying edits.
**Cmd('git') failed due to: exit code(128)
  cmdline: git add /Users/S/config.py
  stderr: 'fatal: Unable to create '/Users/S/.git/index.lock': File exists.**

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.'

### Version and model info

aider 0.47.1, OSX
git version 2.39.3 (Apple Git-145)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It looks like your git repo may be corrupted. Or maybe you were using aider to edit your repo at the same time as some other git tool?

**Comment by ophoria** [comment]
You're right - it was VSCode :)  What I'd wish for however is for the message _that it happened_ would appear in the webversion also and not only in the console window. (Or is that text actually output by GIT and not aider?)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
