### ISSUE TITLE
having a lot of these issues deepseek/coder

### ISSUE THREAD

**Issue by sprappcom** [paul-gauthier/aider#1016]
### Issue

deepseek coder issue:

```
Tokens: 43,288 sent, 531 received. Cost: $0.0062 request, $0.10 session.
The LLM did not conform to the edit format.
https://aider.chat/docs/troubleshooting/edit-errors.html

# 1 SEARCH/REPLACE block failed to match!

```

it seemed to match but the problem persists.
rustlang

### Version and model info

1. latest aider doing rust code.
2. sonnet and openai works

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can try `--edit-format whole` to see if it's more reliable.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by andr0s** [comment]
@paul-gauthier I have the latest aider version from pip, and I confirm it has tons of issues when it comes to DeepSeek models. Now, it's just unusable at all. Claude works ok, as well as open ai.

I'm constantly getting errors 

```
The LLM did not conform to the edit format.
https://aider.chat/docs/troubleshooting/edit-errors.html

# 2 SEARCH/REPLACE blocks failed to match!
```

Even on a simple script (~150 lines of code). Python.

I've just realized that `--edit-format whole` seems to help, thank you. But it feels like things are working slower with it... Also, does it consume more tokens? If no, I'm ok with it :)
