### ISSUE TITLE
Retry Error

### ISSUE THREAD

**Issue by djo534** [paul-gauthier/aider#102]
It's not working on my end. Every time I try a prompt it keep saying retry..
![olo](https://github.com/paul-gauthier/aider/assets/135929024/53dc243a-5e55-4c88-bcee-275f881a7246)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

These retries occur when the OpenAI API is returning errors. Do these errors continue to occur for you?

Is your API key valid and in good standing with OpenAI?

**Comment by circbuf255** [comment]
Same issue here.  New install.  Created multiple API keys on paid account. Revoked them and aider errors out as expected.  Created new API key and it gets to prompt (and openAI says API key was accessed).  When you enter the prompt, that’s when the retry error occurs.  Reinstalled multiple times, no joy.

Anaconda (latest), used pip to install aider-chat.

**Comment by paul-gauthier** [comment]
Thanks for looking into this and trying to debug.

The latest version on github prints the underlying exception on retries. If you have a chance to try it might help us understand what's going on.

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

**Comment by circbuf255** [comment]
Done.  Now that I have an error message work from it makes a lot more sense: "You exceeded your current quota, please check your plan and billing details."

Apparently ChatGPT API is billed separately from ChatGPT Plus ($20).  Thanks for the help.

**Comment by circbuf255** [comment]
Done.  The error message says it all:  "You exceeded your current quota, please check your plan and billing details."

It wasn't immediately clear that ChatGPT API is billed separately from ChatGPT Plus ($20).  I would confirm, but one account has $0 in credits and the other is expired (I don't really want to give them my address).  Thanks for the help.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by funkytaco** [comment]
FYI, I set a limit of $8, and I've reach $12 in 2 days of requests for a small app. It might be a good idea to capture Error Code 429: https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details
