### ISSUE TITLE
Adding support for F#

### ISSUE THREAD

**Issue by NatElkins** [paul-gauthier/aider#1020]
### Issue

Hi,

What is required to add support for a new language (F#, in this case)?  Is it just a tree-sitter grammar?  Or is there more beyond that?  If the former, there is an implementation here: https://github.com/ionide/tree-sitter-fsharp

Thank you!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider will probably work well with F# already. Have you tried it?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/languages.html#how-to-add-support-for-another-language

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
