### ISSUE TITLE
Do files need to be /drop then /add after a big change in git?

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#1024]
### Issue

When I checkout a commit in git and there is a significant change to a file, does it need to be /drop then /add back in, or is it automatically updated to the latest code?

### Version and model info

Aider: latest
LLM: Sonnet 3.5

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

No, aider always uses the latest versions of files.

**Comment by lockmeister** [comment]
great, thanks!
