### ISSUE TITLE
Question re: /add-clipboard-image

### ISSUE THREAD

**Issue by glinkot** [paul-gauthier/aider#1025]
### Issue

This feature will be great.  It would go a long way toward iterating quickly with the model having automatic visibility of the latest change.  Could I ask, does this keep adding more and more screenshots, or replace the same one?  The latter would be preferable so it doesn't bloat the context.

If the answer is that they cumulate, could we have a /replace-clipboard-image command which keeps just a single image that updates?

Second, how best to refer to the screenshot in requests, just say "in the attached image" or similar?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Each `/add-clip` adds a new image. You can see them in `/tokens` and use`/drop` to drop old ones.

**Comment by lockmeister** [comment]
Note that this works on WSL too. I had to 
apt install wl-clipboard
And after that /add-clipboard-image adds snip screenshots that I take in Windows using Win-Shift-S
This is very useful functionality, thanks @paul-gauthier 

Dropping the old image is pretty fast due to the tab autocompletion of aider commands. You only have to type a few characters of the image filename to drop it.

Eventually it would perhaps be useful to be able to name the images, but this MVP is very useful as it is.

**Comment by lockmeister** [comment]
It would be good to have one change, @paul-gauthier  - when an image is added, aider makes assumptions and starts coding before receiving instructions. It would be nice if the addition of an image (or other file) muted aider's output in the same way that /ask does.

**Comment by glinkot** [comment]
Yes, I logged a bug for that just recently @lockmeister https://github.com/paul-gauthier/aider/issues/1032

**Comment by glinkot** [comment]
I think the main usage of this function is to keep updating the input to the model, as you refine your visuals or whatever.  Right now, the name of the file is quite a mouthful when you look at /tokens.  Would be great if it was just called 'clipimage' in there, so you could go /drop clipimage then readd the new one.  Using /drop by itself. will take all my project files out of context.

![image](https://github.com/user-attachments/assets/ef49ea93-aff4-4105-877d-264cd61730a3)

**Comment by paul-gauthier** [comment]
Good point. I had aider make a few improvements:

1. Renamed the `/add-clipboard-image` to just `/clipboard`.
2. Doing `/clip something` will name the image file `something.png`, making it easier to know which image is which.
3. If you then do `/clip something` again, it will replace that image with the new clipboard image.
4. You can do `/clip` to also add text from the clipboard to the chat. It'll add whatever it finds in the clipboard.

**Comment by glinkot** [comment]
Great!  Thanks Paul!  So, if I were to go:

(copy image to clipboard)
/clip currentImage
(copy some log text to clipboard)
/clip latestLog

... I'd see both listed under that name in /tokens

Then on my next run I could, if I wanted, go
/clip latestLog 
and it would replace that text, and currentImage would remain untouched?

I imagine then /drop latestLog could work just on that object also.

That sounds like a fantastic approach if so!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by glinkot** [comment]
Hi Paul, here are the outcomes.  The test was done by creating a new vite project with "npm create vite@latest" then choosing vanilla, typescript.  Then I copied in my .env (containing only the passwords and setting sonnet as the model)

Test 1 - Text with /clipboard (Fail): 

Steps: 
/clipboard

Result:
It adds the text, but it immediately echoes the clipboard contents and  calls the LLM (see this pic, showing its the new dev version)

![image](https://github.com/user-attachments/assets/ce42256a-0be8-4cc0-9e95-2fc029522271)

**Comment by glinkot** [comment]
Test 2 - Image with /clipboard (Pass)

Steps:
(Copy image to clipboard)
/clipboard

Result: 
Places it in context.

**Comment by glinkot** [comment]
Test 3 - Text with /clipboard {clipName} (Fail)

Steps:
(copy text to clipboard)
/clip latestLogText

OR
/clipboard latestLogText

Result:
(doesn't add the item to the context, calls LLM anyway)

![image](https://github.com/user-attachments/assets/f551ca3f-bc4d-4b62-9f82-c4a736bcfe30)
![image](https://github.com/user-attachments/assets/6bec8949-45f2-46f8-bc53-5b205a7730fa)

**Comment by glinkot** [comment]
Test 4 - Add image with /clipboard {clipName} (Pass)

Steps:
(copy image to clipboard)
/clip myImage

Result:
Adds image to the context, doesn't call LLM.

![image](https://github.com/user-attachments/assets/87c37cd7-7038-48db-9060-fb3a44d1ecb3)

**Comment by glinkot** [comment]
(PASS but one issue)
Test 5 - Replace image with /clipboard {clipName}

Steps:
(continues from test 4, with myImage in context)
(copy new larger image so we can see it in /tokens)
/clip myImage

Result:
States that it's replacing the existing image.
Puts a new image, same name, new temp folder
Confirmed both images are the correct 1st and 2nd ones
(Minor issue: reports 1105 tokens for each, even though the 2nd image was at least 10x bigger.  Perhaps this doesn't recalc on replacement?)

![image](https://github.com/user-attachments/assets/2c0c318d-a9d3-47c6-bf11-64351a86871b)

**Comment by glinkot** [comment]
So in summary:
- Adding or replacing text **doesn't currently work**, being named or just with /clipboard
- Adding and replacing images **works well** (except not updating token estimate when replacing)

**Comment by glinkot** [comment]
So in summary:

Adding and replacing images works well (except not updating token estimate when replacing, and dropping by name)
Adding or replacing text doesn't currently work, being named or just with /clipboard

Thanks Paul!

**Comment by paul-gauthier** [comment]
For text, it just pastes it into the conversation as a message from the user. Images are "added to the chat" like a file.

**Comment by glinkot** [comment]
I see, that makes it clear.  Thanks Paul!
