### ISSUE TITLE
Adding support for Perl repo maps

### ISSUE THREAD

**Issue by recursionbane** [paul-gauthier/aider#1027]
### Issue

Hi, what would be needed to add Perl5 support (repo maps, not just linting) to Aider?

Is it a matter of updating the tree-sitter grammar for Perl?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/languages.html#how-to-add-support-for-another-language

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by casimirloeber** [comment]
I am not really sure where to start as I have no experience with Tree Sitter anything but there might be something to start with here:

https://github.com/tree-sitter-perl/tree-sitter-perl
https://github.com/nvim-treesitter/nvim-treesitter/tree/0e21ee8df6235511c02bab4a5b391d18e165a58d/queries/perl

Do you have any resources on how to go about generating a tags.scm file? I have tried researching it but the information is sparse.
