### ISSUE TITLE
Split aider repo into client and server parts

### ISSUE THREAD

**Issue by Alexxosipov** [paul-gauthier/aider#1028]
### Issue

Hey guys. I guess it would be a great idea to split repository into backend and frontend side, where backend would be a manager process as a small http/socket server handling everything for prompts, LLM conversations, git interactions and so on. Basically it would be a server for 2 main reasons: streaming outputs and receiving inputs. 
Client will be the same CLI, but it will work via local stream instead of in-process conversations between functions.
 
We can open the way to create plugins and additions on top of aider making it possible to work with from browser and even telegram bots/mobile apps (sounds very futuristic but anyway)

**Comment by Alexxosipov** [comment]
The simplest usecase: I would like to build laravel error page integration with aider that will send laravel error to aider that is working in laravel repository

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You may be able to make a small cli script that prints out the laravel errors. Then you can `/run show-laravel-errors` to include it into the aider chat.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
