### ISSUE TITLE
error on opening  aider 

### ISSUE THREAD

**Issue by vahid788** [paul-gauthier/aider#103]
aider
aider : The term 'aider' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ aider
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (aider:String) [], CommandNotFoundExce 
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by paul-gauthier** [comment]
Thanks for trying to use aider and reporting this issue.

It looks like aider is not installed on your system or not available on the default shell path.

You could try checking the [installation](https://aider.chat/docs/install.html) and [usage](https://aider.chat/#usage) instructions and see if they're helpful.

**Comment by vahid788** [comment]
i installed i can use from  this location "C:\Users\fUJITSU\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\aider.exe"

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
