### ISSUE TITLE
Bug: Tokens sent reporting appears incorrect

### ISSUE THREAD

**Issue by glinkot** [paul-gauthier/aider#1031]
### Issue

As shown below, I'm seeing it reporting usage of a very large amount of tokens, but the /tokens command suggests it's not doing so.  See highlighted box in the attached screenshot.

![image](https://github.com/user-attachments/assets/7ebf1aa6-f6d4-4def-9bd9-18f162531126)

**Comment by Qubhis** [comment]
Hi, I've been looking for something else but bumped into this related issue https://github.com/paul-gauthier/aider/issues/1023

**Comment by paul-gauthier** [comment]
This issue should be fixed in the latest version.
