### ISSUE TITLE
Bug: Adding file triggers LLM response

### ISSUE THREAD

**Issue by glinkot** [paul-gauthier/aider#1032]
### Issue

When using /add-clipboard-image, the LLM is immediately invoked rather than this being a local operation and it then waiting for the next user prompt.  See highlighted rectangle.

![image](https://github.com/user-attachments/assets/7dffcc2b-a4fe-42fe-9f88-003b9ad84329)

**Comment by glinkot** [comment]
Just to note the second point above is now resolved by Paul's recent changes to /clipboard commands.

Very important still that this just add it locally though, without asking the LLM to guess what the addition of the image is asking it to do.

**Comment by paul-gauthier** [comment]
Doing `/add` or `/clipboard` no longer triggers an LLM response. 

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by glinkot** [comment]
Tested and works nicely!  Thanks so much paul.  

![image](https://github.com/user-attachments/assets/3edc4acb-37f0-4750-b793-9e98d353c42c)
