### ISSUE TITLE
Sonnet Not Working

### ISSUE THREAD

**Issue by RhydianDowning** [paul-gauthier/aider#1035]
### Issue

I am not sure if this is due to sonnet api, however sonnet is working through Cody/Sourcegraph for me at the same time:

Getting this error:
Unexpected error: litellm.APIConnectionError: b'{"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}'
Traceback (most recent call last):
  File "/home/MyLinuxUsername/.local/lib/python3.10/site-packages/litellm/utils.py", line 10080, in __next__
    self.fetch_sync_stream()
  File "/home/MyLinuxUsername/.local/lib/python3.10/site-packages/litellm/utils.py", line 10175, in fetch_sync_stream
    self.completion_stream = self.make_call(client=litellm.module_level_client)
  File "/home/MyLinuxUsername/.local/lib/python3.10/site-packages/litellm/llms/anthropic.py", line 577, in make_sync_call
    raise AnthropicError(status_code=response.status_code, message=response.read())
litellm.llms.anthropic.AnthropicError: b'{"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}'

However if i pass in the --opus tag it works great. This has been happening all morning

### Version and model info

Aider v0.48.2 (also tried with the three previous versions
Model: claude sonnet

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

These errors are because Anthropic's API servers are overloaded/down. Aider is simply reporting that the server is broken. 

Anthropic has been having serious issues since yesterday. You can directly check their server status here:

https://status.anthropic.com/
