### ISSUE TITLE
I still cant use vertex ai same issue as #993

### ISSUE THREAD

**Issue by kanishkave** [paul-gauthier/aider#1039]
### Issue

When i tried to use vertex ai with sonnet with the following command: 
`aider --model vertex_ai/claude-3-5-sonnet@20240620` 
I am getting this error 
```BadRequestError: litellm.BadRequestError: VertexAIException BadRequestError - 
vertexai import failed please run `pip install -U google-cloud-aiplatform 
"anthropic[vertex]"```

### Version and model info

_No response_

I have already ran that specific pip install command

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you originally install aider? What command did you use?

That may affect how to install the google cloud packages.

**Comment by kanishkaverma** [comment]
I used pip install aider-chat

**Comment by paul-gauthier** [comment]
This appears to be a problem with your local python environment. The best thing might be to start with a clean python virtual environment and try installing both again:

```
pip install aider-chat
pip install -U google-cloud-aiplatform "anthropic[vertex]"
```

**Comment by shane-graham** [comment]
For anyone utilizing using Google Vertex AI to access the Anthropic models, note that only two GCP regions are supported:  us-east5 and europe-west1.  I missed that detail and it took some time to figure out the issue.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
