### ISSUE TITLE
Gpt-4 is adding "// ... existing code ..." which Aider writes to file and commits

### ISSUE THREAD

**Issue by Patrik88** [paul-gauthier/aider#104]
Example:
<img width="832" alt="Skärmavbild 2023-07-15 kl  15 39 23" src="https://github.com/paul-gauthier/aider/assets/10167164/afe9cdc5-eb4a-4ebb-b2d0-05d33b70c1d0">
⬇️
<img width="691" alt="Skärmavbild 2023-07-15 kl  15 56 21" src="https://github.com/paul-gauthier/aider/assets/10167164/39ae1880-0b31-4fc5-bdda-cdd3da605a39">

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

I just added a FAQ entry that you might find helpful:
https://aider.chat/docs/faq.html#aider-isnt-editing-my-files

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by Patrik88** [comment]
Thank you Paul,
It's my pleasure!

Cool. I wrote kinda exact the same prompt as you mentioned in the FAQ to solve this. 

What do you think of adding the prompt to the system messages? Or will the system messages get to large by including this kind of stuff there?
