### ISSUE TITLE
Question: how to  get repomap from python?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [paul-gauthier/aider#1043]
### Issue

Hi,

For my [personnal RAG project](https://github.com/thiswillbeyourgithub/WDoc/tree/dev) I was thinking I might add a code parser and wanted to play with aider's repomap as strings by adding a Langchain document loader using aider.

But I couldn't find in the docs or intuitively how to get a repomap directly in python, can anyone shed some light here?

Thanks!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

`coder.get_repo_map()`

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
