### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by tom-doerr** [paul-gauthier/aider#1045]
### Issue

I updated aider in hope to fix my issue in https://github.com/paul-gauthier/aider/issues/995
However after updating Aider I can't start it anymore at all:
```
❯ aider --sonnet --vim
Traceback (most recent call last):
  File "/home/tom/.local/bin/aider", line 5, in <module>
    from aider.main import main
  File "/home/tom/.local/lib/python3.10/site-packages/aider/main.py", line 12, in <module>
    from aider import __version__, models, utils
ImportError: cannot import name '__version__' from 'aider' (/home/tom/.local/lib/python3.10/site-packages/aider/__init__.py)
```
Likely an issue on my side, just wanted to have it documented 

### Version and model info

❯ pip freeze | grep aider
aider==0.2.4
aider-chat==0.47.1

**Comment by paul-gauthier** [comment]
Looks like you accidentally did `pip install aider` not `aider-chat`.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
