### ISSUE TITLE
[Question] Generate repo map

### ISSUE THREAD

**Issue by Mushoz** [paul-gauthier/aider#1047]
### Issue

When I am sending questions in ask mode, why does each question need to do the "Generate repo map". Shouldn't the repo map be made once, and then cached? For large repo's this can take quite a while (10+ seconds) and it's really slowing down the flow of the conversation. I know about .aiderignore, but there aren't any folders/files left that I should ignore.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider customizes the repo map based on the state of the chat, so it updates before every new message sent to the LLM.

What version of aider are you running. There have been some perf improvements in recent releases, including the unreleased code in the main branch.

You can get that by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
