### ISSUE TITLE
[Defect] Aider sets language to French by mistake during /ask command and continues with it. 

### ISSUE THREAD

**Issue by sholub89** [paul-gauthier/aider#1048]
### Issue

```
> /ask hello, how are you                                                                                                                                                     

Bonjour ! Je vais bien, merci. Comment puis-je vous aider aujourd'hui avec le code que vous m'avez montré ? Y a-t-il des questions spécifiques sur l'un des fichiers ou des   
fonctionnalités que vous aimeriez discuter ?         
```

Here is my setup
```
Aider v0.48.1
Model: vertex_ai/claude-3-5-sonnet@20240620 with diff edit format
Git repo: .git with 14 files
Repo-map: using 1024 tokens
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sonnet just likes to speak French. Aider specifically tells it your language as reported by the operating system. But sonnet sometimes ignores it, especially for small, casual non-coding messages like your example.

**Comment by sholub89** [comment]
Got it.
I found it nearly impossible to make it switch to English for subsequent messages :) 
Restarting the Aider helps. 
Since it is a known issue and is on the LLM level - please consider closing this ticket.
