### ISSUE TITLE
Support multiple-line prompts

### ISSUE THREAD

**Issue by jzhang-brex** [paul-gauthier/aider#105]
Sometimes I need to write multi-line prompt. My current workaround is to write the prompt in a text editor and copy them into aider. 

The ideal solution is that when I hit `ctrl+enter` or `cmd+enter`, I can continue the edit the prompt.

**Comment by paul-gauthier** [comment]
Aider supports this using `{}` characters. See the [tips](https://github.com/paul-gauthier/aider#tips) section, which says:

Enter a multiline chat message by entering `{` alone on the first line. End the multiline message with `}` alone on the last line.

**Comment by paul-gauthier** [comment]
Also, in many terminal environments if you paste text with multiple lines into aider they will be received as a multi-line input. But this may not work in all terminal environments.

**Comment by tmm1** [comment]
I also tried to use ctrl+enter. If that could be supported it would be nice.

**Comment by paul-gauthier** [comment]
Good idea. I asked [aider to make that change](https://github.com/paul-gauthier/aider/commit/6244df835257f448c9fda37c02ba090ad651b40b) though I had to manually switch the keybinding from ControlJ to the correct ControlM.

**Comment by paul-gauthier** [comment]
Actually, apparently prompt toolkit has no way to express "control+enter". So I switched it to esc-enter instead.

**Comment by jzhang-brex** [comment]
> So I switched it to esc-enter instead.

Thanks for making the change! I upgrade to 0.9.0 but `esc-enter` doesn't work for me. 

I think `{` and `{` will work for most case except if I need to paste some code snippet which should contains `{` at a single line. I can probably workaround it by put a leading space.

**Comment by joshuavial** [comment]
It wasn't working for me either, then I realised it isn't in the 0.9.0 build and only in main
`pip install --upgrade git+https://github.com/paul-gauthier/aider.git#egg=aider-chat` will get you the version from the main branch

just remember to switch back to the last stable version if there are any issues
`pip install --upgrade aider-chat==0.9.0`

**Comment by kripper** [comment]
https://github.com/paul-gauthier/aider/issues/502
