### ISSUE TITLE
[Feature Request] Output of /git commands added to the chat context

### ISSUE THREAD

**Issue by zxkxyz** [paul-gauthier/aider#1051]
### Issue

As far as I can tell the output of Aider `/git` commands is not added to the chat context. My use case is using the `/git` command to print a diff of a number of commits so I can ask Aider to make a Pull Request description for me based on the changes in my branch (whether I made those changes or Aider did). I tried my command first `/git diff main...branch` and then `/ask`ed Aider (Claude 3.5 Sonnet) to generate a PR based on the provided git diff but it told me I need to provide a diff first (hence my conclusion that /git output is not added to the chat context). My workaround has been running that command outside of aider and pasting it into the Aider CLI.

Adding the /git output would be useful for multiple scenarios outside of PR description generation but hey if there was a nice Aider shortcut for generating PRs from my branch that would be nice too :) 

### Version and model info

Latest (v0.48.1) and Claude 3.5 Sonnet via Vertex AI.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can do `/run git ...`
