### ISSUE TITLE
Working with Images - VertexAI (Different Problems)

### ISSUE THREAD

**Issue by xavitg** [paul-gauthier/aider#1055]
### Issue

Hello,

Today I am reporting several problems I am experiencing related to Images and trying to add them to the chat, which is super useful  to interact with claude via Vertex.

1st Problem:
<img width="602" alt="image" src="https://github.com/user-attachments/assets/3410ed74-d7df-4aad-ba58-842672fa6b21">
I am not able to paste an image via Cloud Shell :(

2nd Problem: /add <image-filename>

<img width="1227" alt="image" src="https://github.com/user-attachments/assets/b8511fc9-9795-4ade-946c-59f460c661e8">
This is a normal .png image. I have tried with different ones and the same problem.

I have no way to send Images to Aider and work with Claude 3.5.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

1. Sorry, you probably can't paste images into aider running in a Cloud Shell. The Cloud Shell terminal almost certainly does not support image paste from the user's OS.
2. It appears that you told aider to make an empty file named `image.png`. Aider then correctly reported that it's not a valid image file.

**Comment by xavitg** [comment]
@paul-gauthier  Hello, Now I am using vscode on my macbook. SHould it work?

**Comment by paul-gauthier** [comment]
The clipboard command may work yes. The terminal built into VSCode is not fully functional compared to a native terminal.

**Comment by xavitg** [comment]
I get this error:

<img width="662" alt="image" src="https://github.com/user-attachments/assets/59491ae1-dee0-4b64-b512-5d10ae963f61">

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
