### ISSUE TITLE
Feedback. Aider no longer works for me. It’s too aggressive. Always wants to edit. I don’t want to use it like that. 

### ISSUE THREAD

**Issue by atljoseph** [paul-gauthier/aider#1058]
### Issue

Long time aider user here. I can’t use it anymore as it is. Here is my feedback. Happy to answer questions, should there be any. I now prefer coding without aider, sadly. 

I used to use this tool to answer questions about my code in the command line. A few months ago, it started always wanting to make edits instead of just answer my questions. I like using it the way I like to use it, and I don’t think I should be asked to change that usage. I continually have to type out prompts that tell the models to not edit anything, but it’s so painful to keep having to repeat myself (isn’t that what AI products are supposed to fix?!).  I don’t want the dry run mode. I don’t want it to edit my files. I don’t want it to give me a diff. I don’t want it to lint the output and fail and then reinterpret a new request I never made and go edit my files. It used to answer a question if you asked a question, but now (I’m not sure what system prompts changed) aider always seems to intuit an edit request from a question. Heck, I don’t want it to make commits either (I use the flag to prevent it). But nonetheless, it always tries to edit things after adding them to the chat. Please allow me to use aider in a less obtrusive, in my face, and aggressive fashion. I don’t work to satisfy the ai things. They exist to satisfy human requests. Can you find a way to make it work for me? Or tell me about options to make it do so?  I’d like to be in control of making the edits, and to turn the insights from the model into changes in my code, and not be led around by an AI carrot on a stick making me think it is saving time when it is really just burning up my time with anthropic and OpenAI credits. I’d like to run the ai around with a carrot on a stick instead. Feel me? I sure hope so. I can’t be the only one who feels this way. Thank you for your product, and I look forward to being able to continue to use it in a way that is free of triggering cognitive dissonance. 

This is where it breaks down for me: 
If something is supposed to help, and it makes things harder or doesn’t help in a way that is meaningful to the one being helped, then that can’t be classified as being helpful. 

### Version and model info

Anthropic sonnet 3.5 and ChatGPT 4o/3.5. 

Always latest version. Updated every time I use it. Used it yesterday. What version was it yesterday? Idk. Y’all know better than me. This issue has spanned many versions.

**Comment by atljoseph** [comment]
Basically, I don’t want to have to tell it explicitly on every question I ask to not edit anything. And over half the time it doesn’t respect what I asked it to do anyway.

**Comment by BarfingLemurs** [comment]
I suggest picking from the release list for that "few months ago" date. Make sure you install in a fresh environment (Python venv) for easy testinh

- https://pypi.org/project/aider-chat/#history

**Comment by atljoseph** [comment]
No.

**Comment by atljoseph** [comment]
No thank you

**Comment by atljoseph** [comment]
Sorry. Why would I do that? For instance, doesn’t even support sonnet 3.5.
That’s a no go.

**Comment by BarfingLemurs** [comment]
hmm? just testing what was worked for you before?

**Comment by atljoseph** [comment]
Aider is supposed to emulate a paired programmer, right? But it’s not
actually that.

It’s possible to ask a programmer pairing with us a question, and get an
answer without editing code.

Why not aider?

**Comment by atljoseph** [comment]
Oh sorry, I didn’t get that from the context, or an idea of which helpful
information you need from me. Are you looking for a version number where
behavior changed??

**Comment by BarfingLemurs** [comment]
(PS. Im not the author, just a random person trying to help )

 Dates from when it was last working out helps to narrow down what's changed, for example, the prompt changing and such.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You should try using /ask and see if that meets your needs. 

https://aider.chat/docs/usage/modes.html

**Comment by atljoseph** [comment]
Thank you. As a developer, I def get the ask, and understand the purpose of
providing a point in time where it changed. But I’m not convinced that
doing so would help much. Being that the working state was months ago, it’s
possible that the feature where behavior changed doesn’t work the same way
as before anyways, and that the resolution might be to move forward instead
of looking back at diffs. Plus, am pretty sure the author has an idea of
the what/where/how is going on. I’d think it’s mainly a matter of tweaking
the prompts that aider provides to the model being used so that it is aware
of question being asked instead of allowing it to assume a question is an
imperative statement. It’s about telling the model more explicitly how to
interact with (and respect) the human user, and most importantly their
intent.

**Comment by atljoseph** [comment]
Thanks. Wasn’t even aware that was a command to be honest. Is there a
command that says /edit, too?

**Comment by paul-gauthier** [comment]
Please see the docs link I shared that describes all the related features.

**Comment by atljoseph** [comment]
What flag on the cli changes the chat mode? Didn’t see that in the doc. Thanks for the link. That’s almost exactly what was looking for.

**Comment by atljoseph** [comment]
Nothing here for chat mode https://aider.chat/docs/config/options.html

**Comment by paul-gauthier** [comment]
I just pushed a few improvements, so please re-check the docs:

https://aider.chat/docs/usage/modes.html

The docs now describe the new `/code` and `--chat-mode <mode>` command line switch. These changes are available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by atljoseph** [comment]
Thank you so much. It’s good to know all the options lol. I just don’t use
the non cli ones. :)

**Comment by mr-september** [comment]
Hi @paul-gauthier, are these command lines applicable in the `--browser` gui? 

I actually have the opposite problem as the OP - I like to start out with chat/ask/help-like prompts to formulate a strategy. Then, when I try to get the AI to start executing the strategy, it stays stuck in that mode and would just suggest little lazy snippets (full of functions with only `placeholder code for function` to me instead of editing/committing actual code.

**Comment by paul-gauthier** [comment]
Unfortunately the browser UI is experimental and doesn't have these features yet.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
