### ISSUE TITLE
Clear command doesn’t clear anything

### ISSUE THREAD

**Issue by atljoseph** [paul-gauthier/aider#1060]
### Issue

With aider open, if I type /clear, nothing is cleared until the cli is closed and restarted. Can just run /clear and then ask something with a clean slate. Based on the reaction of the model, there are some context dingleberries there somewhere. Works better after clearing and closing. Curious what the clear command is intended for if one has to exit and come back in anyways. 

### Version and model info

Latest.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

What makes you think `/clear` isn't working? You can run `aider --verbose` to see exactly what aider is sending to the LLM, to check that /clear is (or isn't) working.

**Comment by atljoseph** [comment]
Because after using clear command the model+aider’s behavior doesn’t change
until AFTER the cli is restarted with ctrl-C. Can ask same question and get
wildly different answers (answers that seem to imply availability of the
conversational context that had presumably been cleared). Haven’t tried the
debugging yet. Might tonight or next weekend.

**Comment by paul-gauthier** [comment]
Sorry, I'm not sure I can conclude that `/clear` isn't working based on that description.



You can see in this log with `--verbose` that the first chat message is not sent to the LLM after the `/clear` command:

```
$ aider --no-git --verbose --mini

...

Aider v0.49.2-dev
Model: gpt-4o-mini with whole edit format
Git repo: none
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args
──────────────────────────────────────────────────────────────────────────────────────────────
> hello, this is my first chat message


SYSTEM Act as an expert software developer.
...


USER hello, this is my first chat message

...

Hello! How can I assist you today? If you have any code or requests for changes, feel free to
share!


Tokens: 645 sent, 24 received. Cost: $0.00011 request, $0.00011 session.
──────────────────────────────────────────────────────────────────────────────────────────────
> /clear

──────────────────────────────────────────────────────────────────────────────────────────────
> this is my second chat message


SYSTEM Act as an expert software developer.

...

USER this is my second chat message

SYSTEM
Understood! Please let me know if you have any specific requests or changes you'd like to make
to your code, and I'll be ready to assist you
```

**Comment by atljoseph** [comment]
Sure. That’s why I’m asking you about it, And providing a clarification
that was requested. Thank you for the next steps.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by bnn1** [comment]
@paul-gauthier could you please explain what does the `/clear` command actually do? i'm a bit confused because after running the command, the `.aider.input.history` and `.aider.chat.history.md` files are not cleared

**Comment by maliayas** [comment]
I don't know if the same issue but... In my case, after running `/clear` and then `/ask A new message`, Aider -unwantedly- would load previous history if the restore-chat-history feature was in use. That was because when the new coder was being created, previous coder's args were used as base.

I've created a PR as a fix to this: https://github.com/Aider-AI/aider/pull/4668
