### ISSUE TITLE
Aider reads and edit the code SUPER slow

### ISSUE THREAD

**Issue by xavitg** [paul-gauthier/aider#1066]
### Issue

Hello,

I installed aider on a server with 2 virtual cpus and 2 threads per core.
As you can see in this image, Aider is at almost 100% of cpu usage:
<img width="784" alt="image" src="https://github.com/user-attachments/assets/ffa34f42-99ea-4403-ad66-78c29119b009">

I just asked aider to read all the code and fix/clean it. It starts very fast but after few minutes, it starts going VERY slow. It literally doesn't go forward and can keep hours reading/editing a single file of code. I guess its because of the cpu problem u see on the image.

How can I resolve this? I want aider to run fast as always. This makes me waste a lottt of time in these scenarios.

Thank you

**Comment by paul-gauthier** [comment]
When reporting problems, it is very helpful if you can provide the “announcement” lines that aider prints at startup is an easy way to share some helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```

**Comment by xavitg** [comment]
Aider v0.49.1
Models: ***@***.*** with diff edit format, weak model ***@***.***
Git repo: .git with 4 files
Repo-map: using 1024 tokens
VSCode terminal detected, pretty output has been disabled.
Use /help <question> for help, run "aider --help" to see cmd line args

**Comment by paul-gauthier** [comment]
It's very unusual that a repo with 4 files would be slow. One thing you could try is running aider with `--no-pretty` if you are asking it to do massive large edits all in one go. You said "read all the code and fix/clean it", which sounds like something which should be broken down into a few smaller requests to work better.

**Comment by xavitg** [comment]
Hello, this is the video of how slow it is. 

https://github.com/user-attachments/assets/c1678761-6e62-4dff-9c62-399f5a9caf34


I usually run the promt: read all the code, clean the code, fix possible bugs and so. Do u recommend me to usee --no pretty when I start Aider? What does that command do? Because normally I use Aider to develope from 0 but before finishing my daily tasks with Aider, I ask the promt I mentioned, and it has to read pages with 1000 lines of code.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by MrCanan** [comment]
Hi @xavitg 
I have exactly sale result as you,
Small project to test, and always incredible slow as your video, even if with a simple request (fast load, calc, etc. but not for answer)
Hope you find a solution?
Best regards
