### ISSUE TITLE
[Question] is there any way aider would create files or even folder structure automaticly after user confirmation

### ISSUE THREAD

**Issue by Palkers76** [paul-gauthier/aider#1067]
### Issue

I'm new to aider, but I can't find option where aider create files for me when I ask him to create entire project.
I know it's assistant and can't relay only on what assistent propose, but would be nice to ask assistant to provide all or initial requirements and it create files and folders for you :)

**Comment by Palkers76** [comment]
found the solution

**Comment by lapochka8** [comment]
> found the solution

Im dumb, help me out here.
