### ISSUE TITLE
[Bug] "/add" command fails with "--subtree-only" option when searching for files

### ISSUE THREAD

**Issue by go-run-jump** [paul-gauthier/aider#1068]
### Issue

When using Aider with the `--subtree-only` command line option, the `/add` command fails to add files when only the file name is provided, even though it correctly identifies matching files.

## Steps to reproduce:
1. Start Aider with the `--subtree-only` option
2. Try to add a file using only its name with the `/add` command

## Expected behavior:
Aider should search for the file within the allowed subtree and ask if I want to add it if found.

## Actual behavior:
Aider identifies matching files but skips them, citing that they match an "aiderignore spec".

## Example interaction:
```
> /add example_file.dart

Skipping /path/to/project/subtree/example_file.dart that matches aiderignore spec.
```

## Additional information:
- This behavior only occurs when the `--subtree-only` option is used.
- The error message mentions an "aiderignore spec", which seems unrelated to the `--subtree-only` option.

### Version and model info

Aider v.0.49.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. The `/add` command will you you matches BEFORE you press enter. Use TAB to autocomplete from them.
