### ISSUE TITLE
instructions on how to add the file + more instructions on what to do next.

### ISSUE THREAD

**Issue by sprappcom** [paul-gauthier/aider#1070]
### Issue

1. is there a possible to say "yes" + more instructions?
2. how to force yes on everything so i dont have to be prompted while i take a break?

### Version and model info

latest aider

**Comment by sholub89** [comment]
@sprappcom , please see the documentation for your use case: 
https://aider.chat/docs/config/options.html#--yes

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
