### ISSUE TITLE
possible to open a discussion tab in github?

### ISSUE THREAD

**Issue by sprappcom** [paul-gauthier/aider#1071]
### Issue

1. need discussion tab

2. how do i limit what shld be in the repo map?
it's always "preparing repo-map" and sometimes the files are not found. actually these files from vim *.sw* are deleted so actually i dont want it to be inside the repo map at all

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Next time you restart aider it should stop mentioning files which have disappeared. You should probably not add vim files to your git repo?
