### ISSUE TITLE
large repo, processing cpu uses 1 core. possible to make it multicore?

### ISSUE THREAD

**Issue by sprappcom** [paul-gauthier/aider#1072]
### Issue

as titled

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Unfortunately no. There are more large/mono repo performance improvements for repo maps coming in the next release.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
