### ISSUE TITLE
Invalid command: /add-clipboard-image

### ISSUE THREAD

**Issue by tom-doerr** [paul-gauthier/aider#1077]
### Issue

![image](https://github.com/user-attachments/assets/71501877-2122-453b-92d6-4b32d45618ea)

Here is the docu referencing it:
https://aider.chat/docs/usage/images-urls.html

However `/clipboard` works.

### Version and model info

❯ pip freeze | grep aider-chat
aider-chat==0.49.1

**Comment by paul-gauthier** [comment]
Ya, sorry. It's been renamed to `/clipboard`. I'll update the docs. Thanks.
