### ISSUE TITLE
Claude 2.0 Integration?

### ISSUE THREAD

**Issue by antoan** [paul-gauthier/aider#108]
Would it be possible to make aider work with the [Claude 2.0](https://www.anthropic.com/index/claude-2) model from Anthropic, I just wondered if it has been attempted.

Apologies if this is not the sort of question to post here.

Thank you for your work on aider.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

Yes, I would like to support Claude! See the discussion in existing issue  #7 .
