### ISSUE TITLE
Bug GUI

### ISSUE THREAD

**Issue by djfaizp** [paul-gauthier/aider#1083]
### Issue

while using GUI if i lost data connection on browser it stop working, it should not dependent on user client browser.

**Comment by djfaizp** [comment]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tornado/websocket.py",
line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError

**Comment by djfaizp** [comment]
can you please provide contex how to log errors ?

**Comment by paul-gauthier** [comment]
A screenshot would be fine. But I think you need to use aider in an environment where you can reliably connect the browser to the server.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
