### ISSUE TITLE
Add /document <filename> as another quick option

### ISSUE THREAD

**Issue by chhudson** [paul-gauthier/aider#1084]
### Issue

Context:
I'm watching a WatsonX webinar and they have a `/document @(filename)` function. This would be awesome to add as a new feature to Aider.

Story:
As a user, I want to easily document/provide a summary of what this file does at the top of a file so that I can understand this file's intent later or bring colleagues up to speed quickly on a given codebase/project.

* If this is the wrong place for feature requests just LMK

### Version and model info

Aider 0.50 Model sonnet

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You should just be able to ask aider "Please add documentation at the top of filename".

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
