### ISSUE TITLE
Claude Prompt Caching!

### ISSUE THREAD

**Issue by bitdeep** [paul-gauthier/aider#1086]
### Issue

More info here:
https://x.com/alexalbert__/status/1823751966893465630
hope you guys implement it fast.

**Comment by dolan** [comment]
Came here to ask about this same feature, but I'm 2 hours late.

**Comment by rawwerks** [comment]
and i am 3 hours late!

**Comment by technoplato** [comment]
I was thinking we could have an /add-docs or /add-static or some other way to add information that would work for being cacheable (that would have no effect on models that don't support caching).

@paul-gauthier do you want any help building this? I'm interested in contributing but unsure about how you like to go about "feature" contribs vs bug fixes.

**Comment by luke3butler** [comment]
So it looks like the prompt caching implementation is done by adding a `cache_control` parameter.

> Prompt Caching references the entire prompt - `tools`, `system`, and `messages` up to and including the block designated with `cache_control`.

It would be really useful if Aider had the concept of "forking" or creating a "checkpoint" in the conversation, so the conversation could be restored to that point in time, with the same exact context. There's plenty of reasons why this is useful, but now with prompt caching it seems like a no-brainer. I think this would even be useful for models that don't have prompt caching.

Maybe you could tag a checkpoint to enable prompt caching on it. Something along the lines of (being extra verbose for clarity) `/cache-from-next-message` or `/create-checkpoint {regular message}`.

Prompt caching is 25% more expensive on the first call, but 90% cheaper for followup calls, so being able to reuse different "checkpoints" would be very valuable.

**Comment by therealtimex** [comment]
Aider leverages litellm, which has support for Prompt Caching in the newest update https://github.com/BerriAI/litellm/releases/tag/v1.43.13-stable

Hope this makes Aider support prompt caching easier

**Comment by bitdeep** [comment]
How we are going with this? Spending like $10/day is getting expansive.

https://x.com/mckaywrigley/status/1824148683711189033

**Comment by johnknott** [comment]
Also, Gemini has Context Caching too - https://ai.google.dev/gemini-api/docs/caching

**Comment by paul-gauthier** [comment]
The main branch has experimental support for prompt caching with Claude and DeepSeek models. It has not yet been well tested, so try it at your own risk!

You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

To try prompt caching, run:

```
aider --cache-prompts
```

Currently, it will only print out cache hit statistics if you also do `--no-stream`. It should be caching even during streaming, but without showing you stats.

```
Tokens: 755 sent, 2,103 cached, 460 received. Cost: $0.0092 message, $0.01 session.
```

Look for the lightning bolt to know that caching is enabled:

<img width="800" alt="2024-08-19_12-09-15" src="https://github.com/user-attachments/assets/9311bd54-a81d-4477-9db7-05adf55a5196">

**Comment by technoplato** [comment]
@paul-gauthier How do you decide what pieces of the message to cache?

AFAICT, if we just naively send updated queries to to llm, we'll bust the cache every time the query changes.

Am I missing something? I see there are some arguments passed to the [Coder](https://github.com/paul-gauthier/aider/commit/8e43911a636d8170d59926bda5cb59a45515c5d1) constructor but was wondering if we could be a little more specific with caching things intentionally like docs, etc.

**Comment by paul-gauthier** [comment]
Aider orders the chat that gets sent to the LLM to try and maximize caching. Read only files from `/read` and the repo-map will be cached along with the system prompt.

**Comment by llamaha** [comment]
This is really amazing thanks so much!

**Comment by lockmeister** [comment]
I recommend installing with
``` pipx install --suffix=@dev git+https://github.com/paul-gauthier/aider.git ```

then you can run this dev version with 

``` aider@dev ```

but still have access to the regular aider in case of any problems.

**Comment by bitdeep** [comment]
This is hot, we can use a dev now, going to auto setup it on my daily pull
now. 😁

Enviado do Gmail para celular

**Comment by lockmeister** [comment]
what does the 5 minute timer for the cache mean for users? Do we need some kind of "mouse jiggler" keep-alive to ensure that we don't pay more after a coffee break?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by rbutera** [comment]
> what does the 5 minute timer for the cache mean for users? Do we need some kind of "mouse jiggler" keep-alive to ensure that we don't pay more after a coffee break?

i'm too dumb to do the calculations but i think you'd end up eating up all the savings you get from prompt caching by forcing a dummy request automatically after 4 minutes of inactivity... right?

**Comment by paul-gauthier** [comment]
This doc may be helpful:

https://aider.chat/docs/usage/caching.html

**Comment by zerocorebeta** [comment]
How to reset cache? Is it just me or some files which were edited and committed when i do "/undo", the model has no idea i reverted back to previous commit?
