### ISSUE TITLE
just upgraded and everything seemed messed up.

### ISSUE THREAD

**Issue by sprappcom** [paul-gauthier/aider#1087]
### Issue

1. seemed to get stuck a lot time
2. lint issues a lot.
3. 1 and 2 makes the code doesnt work anymore.

i cant verify if it's upgraded issue. how to downgrade to previous upgrade?

### Version and model info

latest aider

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```
