### ISSUE TITLE
Repo - Codespace Error is "Terminated"

### ISSUE THREAD

**Issue by teknightstick** [paul-gauthier/aider#109]
I have a large repo and I was able to open it in codespaces.   I got ctags installed and tagged it.  

I asked aider what is the repo it started to heavily review the repo and it seemed like it was going great.   then i got 
"Terminated" 

```
@teknightstick ➜ /workspaces/Camogame2023 (master) $ aider
Aider v0.9.0
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /help                                                                                                                                                                                             

/add Add matching files to the chat session using glob patterns
/clear Clear the chat history
/commit Commit edits to the repo made outside the chat (commit message optional)
/diff Display the diff of the last aider commit
/drop Remove matching files from the chat session
/exit Exit the application
/help Show help about all commands
/ls List all known files and those included in the chat session
/run Run a shell command and optionally add the output to the chat
/tokens Report on the number of tokens used by the current chat context
/undo Undo the last git commit if it was done by aider
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /tokens                                                                                                                                                                                           

Terminated
@teknightstick ➜ /workspaces/Camogame2023 (master) $ aider
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

It looks to me like the OS has terminated aider because it ran out of resources, probably memory? What are the resource limits of the codespaces environment you are using? You might want to try increasing the available memory.

**Comment by teknightstick** [comment]
You nailed it.   I had the basic codespaces on and a pretty large repo.  

So quick side question.  I used ctags and generated the ctag files.   What is the best way to get aider to see the ctags first to get context.

**Comment by paul-gauthier** [comment]
Glad to hear you resolved that issue.

You don't need to "generate the ctags file". Aider does all that automatically once you've installed universal ctags. Based on the output you showed above it looks like aider is already using ctags:

```
@teknightstick ➜ /workspaces/Camogame2023 (master) $ aider
Aider v0.9.0
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
```
That last line means aider has found and is using universal ctags.

Here's some more info about aider and ctags that you might find helpful:
https://aider.chat/docs/install.html#install-universal-ctags-optional

**Comment by teknightstick** [comment]
Ok awesome so ctags is more like a bonus feature that utilizes an optional dependancy but  once the dependancy is installed it just automatically can do more for itself. 

I simply asked it what is this repo and now i see all the files aider made for itself and its able to give me a little brief on it. 


Sidequest question. 
So I have a repo where I have had 2 different developers work on it over time.   

If i wanted to utilize aider to do an extensive code review and make a list of suggestions How exactly would i go about that.  

FYI i just cranked the codespaces up to the largest one and its working fully now.
