### ISSUE TITLE
If aider is unable to fix lint error, it will loop forever without adding or changing code.

### ISSUE THREAD

**Issue by onigetoc** [paul-gauthier/aider#1090]
### Issue

Aider ask me that: Attempt to fix lint errors? y
if i say Y it will try and is unable to fix it then il will loop forever (It will eat token like Pacman will eat dot).
If i said no, it will not process with the code change, fix or else and will do absolutly nothing.
I'm trap for the whole time in my Vite, React project without any help from Aider.

### Version and model info

Latest version today.
gpt-4o-mini

**Comment by alexandj90** [comment]
When I've faced this i have resorted to delete the '.aider.tags.cache.v3' folder, the '.aider.llm.history', '.aider.input.history' and '.aider.chat.history.md' files in the working directory. I'm sure there are other ways, but this works for me.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
