### ISSUE TITLE
What is the syntax to add multiple lint-cmd for different languages?

### ISSUE THREAD

**Issue by dangnhdev** [paul-gauthier/aider#1091]
### Issue

--lint-cmd doc:
> Specify lint commands to run for different languages, eg: "python: flake8 --select=..." (can be used multiple times)  

How can I specify lint-cmd for multiple languages? Which separator should be used?
Thank you for this awesome tool!

### Version and model info

aider v0.50.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/config/options.html#--lint-cmd

You can specify multiple `--lint-cmd "python:pylinter" --lint-cmd "c:myfavclinter"` etc.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
