### ISSUE TITLE
How do I map to local folder structure rather than github?

### ISSUE THREAD

**Issue by piovis2023** [paul-gauthier/aider#1092]
### Issue

[Windows 11 OS, Conda envrionment, No Docker]

How How do I map to local folder structure rather than github?

I keep everything local and offline.

Thank you

**Comment by lockmeister** [comment]
have you tried using git locally, you don't need to push to github at all. Seems to me aider is heavily structured around git, with the way the repo map works etc. Git works well locally and offline.

**Comment by piovis2023** [comment]
thanks @lockmeister . Giving it a go now!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
