### ISSUE TITLE
Deepseek doesn't want to use search and replace blocks?

### ISSUE THREAD

**Issue by samnymr** [paul-gauthier/aider#1094]
### Issue

as the tin says, I have edit on whole format.

Whenever I ask it to do anything its giving me "here's the updated file" and proceeds to write the file rather than put it into the file.

I've tried adding the file to the chat. And telling it which file to edit but it still writes the code to chat.

### Version and model info

Aider v0.50.1
Model: deepseek/deepseek-coder with ♾️ whole edit format
Git repo: .git with 4,369 files
Warning: For large repos, consider using --subtree-only and .aiderignore
See: https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo
Repo-map: using 1024 tokens

**Comment by samnymr** [comment]
correction, it sometimes does, but the search and replace is terrible, it seems to remove parts of code that it shouldn't touch at all..

**Comment by djfaizp** [comment]
your prompt style should be like you are instructing 
this will solve issue or may be it's issue from deepseek sometimes i also do get same errors

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by tdobson** [comment]
The thing about deepseek is that it's quite good at writing new code, but quite bad at editing it.

See the top leaderboard on this page.... and then the bottom leaderboard:
https://aider.chat/docs/leaderboards/

**Comment by djfaizp** [comment]
> The thing about deepseek is that it's quite good at writing new code, but quite bad at editing it.
> 
> See the top leaderboard on this page.... and then the bottom leaderboard: https://aider.chat/docs/leaderboards/

yes pretty bad 
and sonnet is very expensive 🫰
it burns my $5 in just 5-6 editings 
because i made mistake by putting large code in single file

**Comment by tdobson** [comment]
I agree it is expensive. One of my greatest hopes for the next 12 months is that the price of sonnet-like-performance drops a lot. 

If you can split your code out into several files, 

Paul just added a new sonnet feature (and deepseek!) called prompt caching that might help. It's slightly experimental, but try adding --cache-prompts. If you're editing a large set of files, and only say 2 change, it'll cache those.

To be clear though: I'm 100% with you - I want deepseek to work better at refactoring and code editing. It's so close to be amazing.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
