### ISSUE TITLE
openai compatible apis not workign for nvidia since it has meta/model_name so openai/meta/model_name and openai/model_name both doent work

### ISSUE THREAD

**Issue by Uddhav07** [paul-gauthier/aider#1095]
### Issue

![image](https://github.com/user-attachments/assets/69322a76-0511-4cd7-b749-ebd6dd707b18)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/llms/openai-compat.html

**Comment by Uddhav07** [comment]
> Thanks for trying aider and filing this issue. This doc may be helpful:
> 
> https://aider.chat/docs/llms/openai-compat.html

i did follow the doc but still the same issue

**Comment by Uddhav07** [comment]
also what is expected of me even though niether method works but 
openai/meta/model or meta/model is to be used

**Comment by paul-gauthier** [comment]
Probably `openai/model`.

**Comment by Uddhav07** [comment]
> Probably `openai/model`.

Yeah that's what I did with all other stuff
Still didn't work

What can I share to help you help me

**Comment by paul-gauthier** [comment]
Sorry, I am not able to help debug configurations to a custom model like this. The issues are likely to be problems in your local environment or with the model provider.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
