### ISSUE TITLE
It is fine to pay Anthropic but in return for the money spent users should not get back obscure AnthropicException - InternalServerError

### ISSUE THREAD

**Issue by distributev** [paul-gauthier/aider#1097]
### Issue

I would argue that the user should never have to pay to AI providers when receiving  InternalServerError doen't matter that tokens were sent (consumed) as long as no response was provided back (and this happened because of the AI's vendor fault) then the user should not pay for such requests.

(If this is out of what aider can do at least provide more details about the exception) Currently we get like this, we can see that we 
were charged for the obscure litellm.InternalServerError

![image](https://github.com/user-attachments/assets/809a991d-c73b-4526-a2fb-59bcbbec166f)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, if Anthropic is charging you when there server crashes that is something you will need to speak with them about.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by distributev** [comment]
aider is really good and I feel it gets even better while I use (understand) more about it. I anticipated you cannot change what Anthropic charges and what not but at least is it possible in Aider to display to the user a more useful message about which specific error Anthropic/OpenAI gave instead of showing the generic/opaque InternalServerError ?

Thank you again for this software.
