### ISSUE TITLE
aider always starts with antropic claude even after I specify --openai-api-key

### ISSUE THREAD

**Issue by distributev** [paul-gauthier/aider#1099]
### Issue

Hello - aider is a very good package - there is a lot of hype around AI but aider is an exception and actually delivers on its promises.

Usually I use anthropic but sometime I want to switch to openai.

![image](https://github.com/user-attachments/assets/9626d95e-19a8-4683-9859-81a1258e527f)

**Comment by upperpalaeolithic** [comment]
possibly anthropic api key set in your environment which takes priority. use '--model 4o' parameter to override?

**Comment by distributev** [comment]
Yes this is what I did and it works.
This can be closed, maybe the docs can state it with more clarity.
