### ISSUE TITLE
Feature: optionally enhance /ask with the option to redirect the LLM output (answer) to a file on disk

### ISSUE THREAD

**Issue by distributev** [paul-gauthier/aider#1103]
### Issue

It is easier to read and manipulate large chunks of text/code inside files vs. to the terminal

I use aider exclusively with the /ask and reading (or copy pasting) code from a file is easier compared with the terminal.

Further more a file called **_ask.txt_** or **_scratchpad.txt_** could be designated like this.

_User's query comes above the separator (keep an empty line between the query and the separator)_

--------------------------------------------------------------

_LLM answer comes below the separator  (keep an empty line between the separator and the LLM answer)_

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

All the chat is logged to `.aider.chat.history.md`.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
