### ISSUE TITLE
Feature request: Advanced Context Control and Branching Conversations

### ISSUE THREAD

**Issue by randoentity** [paul-gauthier/aider#1104]
### Issue

Occasionally, especially with the new "ask" mode, I'd like the ability to clear only the last few messages (e.g. /clear "last three messages"). Additionally, I'd like to retry (/regenerate) a prompt. Interfaces like text-generation-webui and SillyTavern support this kind of functionality. It would be fantastic to have more control over the conversation history, enabling the user to manually fix errors that the LLM cannot resolve on its own (/edit). An even more advanced feature would be supporting branching conversations.

I'm torn between thinking that this goes beyond the intended purpose of Aider and believing that this is a powerful and useful feature that would significantly enhance Aider's usability, potentially making it the only LLM UI I'd need.

**Comment by grrowl** [comment]
+1, i find myself only wanting to preserve the last 2-3 turns of conversation. Otherwise I get the LLM to summarise and copy + clear + paste + continue, but it's cumbersome and the LLM loses fidelity of recent diffs.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider already automatically summarizes the longer past history. You don't need to manage that manually.

If aider gets stuck on a coding problem, the most pragmatic things to try are:

1. `/clear` the conversation and just try again.
2. `/drop` extra files from the chat to reduce distractions.
3. Try a stronger LLM.
4. Just code that part yourself and move on with aider for the next bit of work.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
