### ISSUE TITLE
Have you thought of using LSPs? 

### ISSUE THREAD

**Issue by idvorkin** [paul-gauthier/aider#1107]
### Issue

**Aider is fantastic, thank you for building it**

*In case you haven't considered it, bringing it up*

I wonder if Aider could use an LSP as a tool. Being able to do things like rename safely, and find all references could make changes much safer.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Please see the discussion in #527.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
