### ISSUE TITLE
Idea: Upload chat history to gist

### ISSUE THREAD

**Issue by idvorkin** [paul-gauthier/aider#1108]
### Issue

I'm not sure the best way to implement this feature request/workflow, but I thought I'd share what I'm doing today, in case it inspires others/gives me a better approach :) 

I like to have the chat history that created the changes, as a result I upload the aider conversation to a gist, then link it to the diff. 

My workflow is normally: 

- create a branch
- use aider to make a bunch of changes
- upload the history
- Do a rebase to squash a bunch of the commits 
- Link the chat gist to the file. 

For reference here's the gist upload code

```zsh
function ghg-aider()
{
    trim_file_after_marker_to_new_file '.aider.chat.history.md' '# aider chat started at' '.aider.last.chat.md'
    gh gist create -w .aider.last.chat.md
}
```

Here's an example of such a diff/gist: 
* Link to the "feature": https://github.com/idvorkin/Settings/commit/4b1bf128a4c137dc4823d1ab00890bf257d4e0d8
* Aider Chat History: https://tinyurl.com/2bwbpncz

**Comment by paul-gauthier** [comment]
Sorry about that incorrect reply.

Aider support making those shared chat histories look pretty:

https://aider.chat/docs/faq.html#can-i-share-my-aider-chat-transcript

**Comment by idvorkin** [comment]
Oh sweet. Thanks!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
