### ISSUE TITLE
/web requires hitting enter for every line of scraped content

### ISSUE THREAD

**Issue by glinkot** [paul-gauthier/aider#1109]
### Issue

In VS Code and a cmd window, if I go:

/web https://www.postman.com/api-platform/api-documentation/#:~:text=API%20documentation%20is%20a%20set,of%20common%20requests%20and%20responses.

It says 'more' once it reaches a page of output, and then you have to hold down enter as it dumps it line by line into the console.  For longer pages, this can take a while!

![image](https://github.com/user-attachments/assets/12ede87f-51f9-4471-afad-29f3a77a3354)

**Comment by bitdeep** [comment]
Bruh... just hit Q, wtf bro.

**Comment by glinkot** [comment]
That isn't self evident.  Next time I suggest being helpful but using more than the two actual English words in that message.
