### ISSUE TITLE
Feature Request: Instruction suggestion. 

### ISSUE THREAD

**Issue by teknightstick** [paul-gauthier/aider#111]
`sudo apt update`
`sudo apt install -y universal-ctags`
`pip install aider-chat`

Typing in all that into Codespaces is the easiest way to have aider and ctags running in order to see this. 

Aider v0.9.0
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args

**Comment by paul-gauthier** [comment]
Thanks for the suggestion!

I think most of that info is available in the [installation instructions](https://aider.chat/docs/install.html) right now?

I am reluctant to try and provide detailed instructions for every possible situation that a user might encounter. There are so many different environments they might be working in.

**Comment by teknightstick** [comment]
You need to update before the ctag install can occur.  At first it just says something like "cant find that extension."  which is probably intuitively handles by smarter people than me.

**Comment by paul-gauthier** [comment]
Fair enough. I added the update to the docs. Thanks for the suggestion.

https://github.com/paul-gauthier/aider/commit/e7692fc9d130acfbb2c4a3d9cb63a78fa5b47483

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
