### ISSUE TITLE
Installing using pip or pipx aider-chat[help] only installs the previous version

### ISSUE THREAD

**Issue by lawong888** [paul-gauthier/aider#1111]
### Issue

Tried installing aider-chat with the help components

pip install aider-chat[help]
or
pipx install aider-chat[help]

only installs Aider v0.49.1 and not the latest v0.50.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You need to add the `--upgrade` switch to pip/pipx.

**Comment by lawong888** [comment]
I tried it and it didn't work, still installed the older verison:

pipx install aider-chat[help]  --force --pip-args "--extra-index-url https://download.pytorch.org/whl/cu118"--upgrade
  installed package aider-chat 0.49.1, installed using Python 3.11.9
  These apps are now globally available
    - aider.exe
done! ✨ 🌟 ✨

if I removed the [help], it works:

pipx install aider-chat  --force --pip-args "--extra-index-url https://download.pytorch.org/whl/cu118"--u
pgrade
  installed package aider-chat 0.50.1, installed using Python 3.11.9
  These apps are now globally available
    - aider.exe
done! ✨ 🌟 ✨

**Comment by fry69** [comment]
I think you need to install `aider-chat[help]` in the same pipx virtual Python environment as the main `aider`, like this:
```shell
pipx runpip aider-chat install aider-chat[help]
```
But I can confirm that doing this will downgrade an existing aider `0.50.1` to `0.49.1` for some reason.

**Comment by fry69** [comment]
Update: aider version `0.51.0` was released and now installing the support files for `/help` via
```
pipx runpip aider-chat install aider-chat[help]
```
works as expected. No more downgrade! Thank you!

**Comment by lawong888** [comment]
pipx list shows nothing has been installed with pipx

pipx runpip aider-chat install aider-chat[help]
venv for 'aider-chat' was not found. Was 'aider-chat' installed with pipx

**Comment by fry69** [comment]
>  venv for 'aider-chat' was not found. Was 'aider-chat' installed with pipx

This was meant if you first installed aider and then wanted to install the help package in the same pipx virtual environment. If aider was never installed, you can go directly to
```shell
pipx install aider-chat[help]
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
