### ISSUE TITLE
/web invokes LLM, causing it to repeat prior request

### ISSUE THREAD

**Issue by glinkot** [paul-gauthier/aider#1115]
### Issue

/web appears to add the page content to the context and then hit the LLM, which looks at the text and the previous request, thinking the previous request must be a new one.

/web should hold that content locally prepend it to the following request instead.  

![image](https://github.com/user-attachments/assets/95c34d6e-1aa9-47cf-b02b-e55060ee0e6d)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can always just include a URL in a chat message, so you can explain what you want to do with the URL. Aider will ask if you want to include it.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
