### ISSUE TITLE
Bug inside browser 

### ISSUE THREAD

**Issue by djfaizp** [paul-gauthier/aider#1121]
### Issue

We can only undo last commit using browser and if we accidentally sent anything we can't undo from browser have to do it manually from terminal using commit id

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The browser UI is experimental and doesn't support all the features of the CLI version.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
