### ISSUE TITLE
Don't change Author line

### ISSUE THREAD

**Issue by myurko** [paul-gauthier/aider#1124]
### Issue

Aider currently adds "(aider)" in the author field of  its commits after the current user name. This breaks strict author checking. Can we by default, or at least with a startup argument not change the Author string?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/git.html

**Comment by myurko** [comment]
Thanks for this info!
