### ISSUE TITLE
How to use ollama make main_model to create or init Coder in aider python api ？

### ISSUE THREAD

**Issue by RebornXiao** [paul-gauthier/aider#1127]
### Issue

@classmethod
    def create(
        self,
        main_model=None,
        edit_format=None,
        io=None,
        from_coder=None,
        summarize_from_coder=True,
        **kwargs,
    ):
    
    Ask：above mothed 。How to introduce the local model of the ollama service, instantiate it as a parameter of main_model, and introduce it into the create method?
    Thank you！

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/llms/ollama.html

**Comment by RebornXiao** [comment]
I have found the method. Use the following method:

    model = Model("ollama/codegemma")

    # Create a coder object
    coder = Coder.create(main_model=model, fnames=fnames)

    # This will execute one instruction on those files and then return
    coder.run("make a script that prints hello world")

The local ollama model can be used based on the aider's api interface.

**Comment by RebornXiao** [comment]
> Thanks for trying aider and filing this issue. This doc may be helpful:
> 
> https://aider.chat/docs/llms/ollama.html

Thank you and I find the right way！

model = Model("ollama/codegemma")
