### ISSUE TITLE
🪲 BUG During reflector 

### ISSUE THREAD

**Issue by djfaizp** [paul-gauthier/aider#1129]
### Issue

I'm error that Only 3 reflector are allowed ? why and how to solve it ? is anyone facing this issue ?

### Version and model info

AIDER V.50.1
MODEL : DEEPSEEK

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can just ask it to try again. But if it get stuck for 3 retries, you may want to run `/clear` before asking again for the change. The model may have gotten itself confused.

**Comment by djfaizp** [comment]
i will try and share experiences thanks for your kind reply 😊 you are doing great work this project have helped me alot i have zero knowledge of programming and i have successfully built a good program. now I'm just about to finish it but due to large volume of codes it is maybe confusing

**Comment by djfaizp** [comment]
it's works now after /clear and my file had 1000+ line codes that's why model was confusing . now i have split them in 4 i will update if i still found that error thanks @paul-gauthier for this awesome project.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
