### ISSUE TITLE
Error/Bug using deepseek-coder-v2 and Ollama latest update

### ISSUE THREAD

**Issue by U0M0Z** [paul-gauthier/aider#1130]
### Issue

Hi, 
opening this issue because I am having some problems in developing a script using a local LLM served by Ollama on my machine. The error is in the connection between aider and the local version of deepseek-coder-v2. I haven't had any issue for the past week but suddenly the error started to pop up today after updating to the newer version of Ollama on my machine.

Here's the code:

```
import os

from aider.coders import Coder
from aider.models import Model
from aider.io import InputOutput

From prompts import coder_prompt

folder_name = os.path.join(‘results_dir’)

# Define folder and 
exp_file = os.path.join(folder_name, "experiment.py")
vis_file = os.path.join(folder_name, "plot.py")
notes = os.path.join(folder_name, "notes.txt")

fnames = [exp_file, vis_file, notes]

# Define I/O for model 
io = InputOutput(yes=True, chat_history_file=f"{folder_name}/{project_name}_aider.txt")

# Define main model to leverage
main_model = Model("ollama/deepseek-coder-v2:16b")

# Instantiate coder model
coder = Coder.create(main_model=main_model, fnames=fnames, io=io, stream=False, use_git=False, edit_format="diff”)

coder_out = coder.run(coder_prompt)
print(coder_out)
```

And here is the error it generates:

```
————————————————————————————————————————————————————————————

litellm.APIConnectionError: {"error":"an unknown error was encountered while running the model "}
Traceback (most recent call last):
  File "/Users/<username>/miniconda3/envs/arc/lib/python3.11/site-packages/litellm/main.py", line 2424, in completion
    generator = ollama.get_ollama_response(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/miniconda3/envs/arc/lib/python3.11/site-packages/litellm/llms/ollama.py", line 268, in get_ollama_response
    raise OllamaError(status_code=response.status_code, message=response.text)
litellm.llms.ollama.OllamaError: {"error":"an unknown error was encountered while running the model "}
```

Some Environment specs:

```
Package                      Version
--------------------- --------
aider-chat                   0.49.1
litellm                           1.43.4
requests                      2.32.3
```

**Comment by dsedivec** [comment]
I was getting this, and I think the problem is actually that llama.cpp is crashing on this model.  See the discussion at ggerganov/llama.cpp#8862, and a potential workaround [here](https://github.com/ollama/ollama/issues/5975#issuecomment-2306851184).  After using that workaround locally, Aider was able to service at least my first couple prompts to successful completion.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Yes, this looks like an error coming from Ollama, not to do with aider.

**Comment by dsedivec** [comment]
I will say that, when Aider gets this error, it seems like the terminal gets very... confused, and Aider seems to go into some kind of loop where it just keeps repeating the same thing over and over.  I'm guessing this is because the server closes the connection, so maybe Aider re-opens it and re-sends the context, which ollama submits as a wholly new request, which repeats a bit and then trips the bug again.  Round and round we go in a crash loop.  I'm not sure if Aider can discern this fatal error from a "just try again" kind of error in the API.

Just a note, in case you're interested in changing error handling/reporting.  I'm excited to try Aider, thank you for writing this. :)

**Comment by U0M0Z** [comment]
Thanks @dsedivec for the information! In my scenario aider keeps trying to reconnect to ollama and the error handling/recognition is missing. It would be great to have a sort of error handling message for the situation.

**Comment by mik3lang3lo** [comment]
Same problem as described. 

> litellm.APIConnectionError: Ollama Error - {'error': 'error reading llm response: read tcp
127.0.0.1:61549->127.0.0.1:59108: wsarecv: An existing connection was forcibly closed by the remote host.'}
Traceback (most recent call last):
  File "C:\Users\mathe\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 9936, in
chunk_creator
    response_obj = self.handle_ollama_stream(chunk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 9359, in
handle_ollama_stream
    raise e
  File "C:\Users\mathe\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 9334, in
handle_ollama_stream

`litellm.APIConnectionError: Ollama Error - {'error': 'error reading llm response: read tcp
127.0.0.1:63309->127.0.0.1:63295: wsarecv: An existing connection was forcibly closed by the remote host.'}
Traceback (most recent call last):
  File "C:\Users\mathe\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 9936, in
chunk_creator
    response_obj = self.handle_ollama_stream(chunk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 9359, in
handle_ollama_stream
    raise e
  File "C:\Users\mathe\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 9334, in
handle_ollama_stream
    raise Exception(f"Ollama Error - {json_chunk}")
Exception: Ollama Error - {'error': 'error reading llm response: read tcp 127.0.0.1:63309->127.0.0.1:63295: wsarecv: An
existing connection was forcibly closed by the remote host.'}`

**Comment by paul-gauthier** [comment]
That error means something is wrong with your Ollama server.

**Comment by vishnunuk** [comment]
@paul-gauthier 
When generating a response, `deepseek-coder-v2` randomly stops or quits with the following error:

````Error: An unknown error was encountered while running the model.````


I have tested different versions of `deepseek-coder-v2` and the Ollama server, including both the Docker and desktop versions on Windows, macOS, and Linux. On all three platforms, I can reproduce this issue. No other models have shown this behavior.

ss when  `deepseek-coder-v2` randomly stops or quits when responding... 
<img width="899" alt="Screenshot 2024-09-17 at 9 17 30 PM" src="https://github.com/user-attachments/assets/072ab47a-28f5-471f-80d2-bbae6f1181a1">

**Comment by regs01** [comment]
Same here. Deepseek-coder-v2 halts answering. Often even after one word.


![Image](https://github.com/user-attachments/assets/23ddb2cf-f77e-42ca-8b61-1296edbd0d1f)
