### ISSUE TITLE
Aider streaming the whole file!

### ISSUE THREAD

**Issue by hadi-nayebi** [paul-gauthier/aider#1131]
### Issue

When using aider, it keeps writing the whole file in the response (stream, <source>) even if it changes a single word. How one can stop this behavior? is this the default behavior? I have a relatively large file and every time it makes a small edit, I have to sit and wait for aider to stream the whole updated file for minutes.

**Comment by hadi-nayebi** [comment]
I get this, aider: error: unrecognized arguments: --diff
and when using --show-diffs, still get the same behavior. 

the other clue is that, it streams the whole file after 

path/to/idea.md
<source> 
content of the file
</source>

**Comment by hadi-nayebi** [comment]
I just realized what you mean. There are all these options for the /chat-mode 

Chat mode should be one of these:

- help        : Get help about using aider (usage, config, troubleshoot).
- ask         : Ask questions about your code without making any changes.
- code        : Ask for changes to your code (using the best edit format).

Or a valid edit format:

- diff        : A coder that uses search/replace blocks for code modifications.
- diff-fenced : A coder that uses fenced search/replace blocks for code modifications.
- udiff       : A coder that uses unified diff format for code modifications.
- whole       : A coder that operates on entire files for code modifications.

I can understand the top three options. First question: which one is the default?
what is the practical difference between these? is there any article or tutorial to go through these and when to choose each?!
Some times, i like to work on the idea.md which is not a code source, sometimes I work on the cookbook.md, and some times the src code. Is research behind having all these options?

**Comment by hadi-nayebi** [comment]
Another related question I have is whether the continuous edit are possible. When I prompt aider to continue identifying edits, and commit and repeat, it never makes an intermediate commits. It seems that it does propose many changes but until it is done responding, the commits never happen. The behavior I am looking is to follow my prompt, identify items to edit, commit and continue to the next item without stopping. I intend to use this behavior for expanding ideas not the source code directly. I have an idea.md file which I have a seed on an idea and my current partial implementation, I want aider to only focus on the idea.md and expand this file step by step and take the seed into a well thought out idea. Later I will use the idea.md file as a core file that will guide the code implementation workflow. I hope the behavior I am describing is clear.

**Comment by paul-gauthier** [comment]
This doc may be helpful:

https://aider.chat/docs/scripting.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
