### ISSUE TITLE
Struggles to find errors. 

### ISSUE THREAD

**Issue by Jedward23** [paul-gauthier/aider#1132]
### Issue

The way it shares errors with the AI looks like this:

# Fix any errors below, if possible.

## See relevant lines below marked with █.

src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:
  1█import React, { useState, useEffect, useCallback, useMemo } from 'react';
  2│import { MonthlyConfig, GlobalAgencyData, Expense, MonthlyExpense, GlobalCategory, HealthMetrics } from
'../../../types/types';
  3│import { PieChart, Pie, Cell, ResponsiveContainer, Legend, Tooltip, LineChart, Line, XAxis, YAxis, CartesianGrid }
from 'recharts';
  4│import { useAgencyCalculations } from '../../../hooks/useAgencyCalculations';
...⋮...
279│  const renderMetric = useCallback((label: string, value: number, previousValue?: number) => {
280│    const change = calculateChange(value, previousValue);
281│    return (
282█      <div className="flex justify-between items-center">
283█        <span>{label}:</span>
284█        <div className="text-right">
285█          <div>{formatCurrency(value)}</div>
286│          {showComparison && change !== null && previousValue !== undefined && (
287█            <div className={`text-sm ${getColorClass(value - previousValue)}`}>
288│              {change}
289│            </div>
290│          )}
291│        </div>
292│      </div>
293│    );
294│  }, [showComparison, formatCurrency, calculateChange, getColorClass]);

--------------

It's better to show it the errors in this format (same as REACT shows in terminal):

webpack compiled with 12 warnings
ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:124:42
TS2304: Cannot find name 'previousFinancials'. <----- ==Note: This is especially helpful, which it doesn't see==
    122 |   const handleOverrideToggle = useCallback((checked: boolean) => {
    123 |     setIsWorkingCapitalOverridden(checked);
  > 124 |     if (!checked && currentFinancials && previousFinancials) {
        |                                          ^^^^^^^^^^^^^^^^^^
    125 |       const calculatedValue = previousFinancials.workingCapital ?? 0;
    126 |       setDisplayedWorkingCapital(calculatedValue);
    127 |       onUpdate({

ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:125:31
TS2304: Cannot find name 'previousFinancials'.
    123 |     setIsWorkingCapitalOverridden(checked);
    124 |     if (!checked && currentFinancials && previousFinancials) {
  > 125 |       const calculatedValue = previousFinancials.workingCapital ?? 0;
        |                               ^^^^^^^^^^^^^^^^^^
    126 |       setDisplayedWorkingCapital(calculatedValue);
    127 |       onUpdate({
    128 |         startingWorkingCapital: calculatedValue,

ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:137:26
TS2304: Cannot find name 'previousFinancials'.
    135 |       });
    136 |     }
  > 137 |   }, [currentFinancials, previousFinancials, displayedWorkingCapital, onUpdate]);
        |                          ^^^^^^^^^^^^^^^^^^
    138 |
    139 |   const handleWorkingCapitalChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    140 |     const newValue = Number(e.target.value);

ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:391:91
TS2304: Cannot find name 'previousFinancials'.
    389 |               <h3 className="font-semibold mb-2">Expenses</h3>
    390 |               <div className="space-y-2">
  > 391 |                 {renderMetric('Team Costs', currentFinancials.teamCosts, showComparison ? previousFinancials?.teamCosts : undefined)}
        |                                                                                           ^^^^^^^^^^^^^^^^^^
    392 |                 <div className="flex items-center justify-between">
    393 |                   <span>Other Expenses:</span>
    394 |                   <div className="mt-4">

ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:406:93
TS2304: Cannot find name 'previousFinancials'.
    404 |                   </div>
    405 |                 </div>
  > 406 |                 {renderMetric('Total Costs', currentFinancials.totalCosts, showComparison ? previousFinancials?.totalCosts : undefined)}
        |                                                                                             ^^^^^^^^^^^^^^^^^^
    407 |               </div>
    408 |             </div>
    409 |

ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:438:95
TS2304: Cannot find name 'previousFinancials'.
    436 |               <h3 className="font-semibold mb-2">Profit</h3>
    437 |               <div className="space-y-2">
  > 438 |                 {renderMetric('Gross Profit', currentFinancials.grossProfit, showComparison ? previousFinancials?.grossProfit : undefined)}
        |                                                                                               ^^^^^^^^^^^^^^^^^^
    439 |                 {renderMetric('Tax Amount', currentFinancials.tax, showComparison ? previousFinancials?.tax : undefined)}
    440 |                 {renderMetric('Net Profit', currentFinancials.netProfit, showComparison ? previousFinancials?.netProfit : undefined)}
    441 |                 <div className="flex justify-between items-center">

ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:439:85
TS2304: Cannot find name 'previousFinancials'.
    437 |               <div className="space-y-2">
    438 |                 {renderMetric('Gross Profit', currentFinancials.grossProfit, showComparison ? previousFinancials?.grossProfit : undefined)}
  > 439 |                 {renderMetric('Tax Amount', currentFinancials.tax, showComparison ? previousFinancials?.tax : undefined)}
        |                                                                                     ^^^^^^^^^^^^^^^^^^
    440 |                 {renderMetric('Net Profit', currentFinancials.netProfit, showComparison ? previousFinancials?.netProfit : undefined)}
    441 |                 <div className="flex justify-between items-center">
    442 |                   <span>Profit Margin:</span>

ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:440:91
TS2304: Cannot find name 'previousFinancials'.
    438 |                 {renderMetric('Gross Profit', currentFinancials.grossProfit, showComparison ? previousFinancials?.grossProfit : undefined)}
    439 |                 {renderMetric('Tax Amount', currentFinancials.tax, showComparison ? previousFinancials?.tax : undefined)}
  > 440 |                 {renderMetric('Net Profit', currentFinancials.netProfit, showComparison ? previousFinancials?.netProfit : undefined)}
        |                                                                                           ^^^^^^^^^^^^^^^^^^
    441 |                 <div className="flex justify-between items-center">
    442 |                   <span>Profit Margin:</span>
    443 |                   <div className="text-right">

**Comment by tdobson** [comment]
I'm writing React, and I've had the linter utterly fail me in usefulness in this same way.

when I provide the lines and the linting errors, the llm's generally have quite a good approach to resolving it.

I think it'd even do quite a good job if the linters provided the liste of errors at the top of the file - but that's not what happens - the LLM's just are told to guess what's wrong on specific lines, and fail... hard. :(

**Comment by Jedward23** [comment]
Agreed, I think if Aider could just find a way to provide the errors from
REACT in a clearer way that the LLM can understand. It could accomplish far
more without any supervision.

--

Thank you,


Jason Edward Nicoll
Director of Marketing & Operations

**Comment by tdobson** [comment]
A thought @Jedward23 : do we have any idea where/how React's linter thing works?

Eg is it possible to call it and get a list of these errors?

eg 

$ findMyErrors.exe.sh src/*ts*
ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:440:91
TS2304: Cannot find name 'previousFinancials'.
438 | {renderMetric('Gross Profit', currentFinancials.grossProfit, showComparison ? previousFinancials?.grossProfit : undefined)}
439 | {renderMetric('Tax Amount', currentFinancials.tax, showComparison ? previousFinancials?.tax : undefined)}
ERROR in src/components/Dashboard/MonthlyConfig/FinancialOverview.tsx:439:85
TS2304: Cannot find name 'previousFinancials'.
437 |
438 | {renderMetric('Gross Profit', currentFinancials.grossProfit, showComparison ? previousFinancials?.grossProfit : undefined)}

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can specify your preferred linter with `--lind-cmd`.

This doc may be helpful:
https://aider.chat/docs/usage/lint-test.html

**Comment by tdobson** [comment]
@Jedward23  try something like 

$ aider  --lint-cmd "typescript:npx tsc --noEmit --skipLibCheck --skipDefaultLibCheck " 

It's not perfect, but I suspect with a bit of tweaking we can find something that works well for typescript projects like React often is. :)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by paul-gauthier** [comment]
FYI, aider will no longer attempt to use the built in linter for typescript. It appears to not be useful.

The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```
