### ISSUE TITLE
Feature request: Implement prompt caching with Claude

### ISSUE THREAD

**Issue by liviuolos** [paul-gauthier/aider#1133]
I think Aider would greatly benefit from prompt caching leading to development cost reduction, faster answers, better quality for lengthily development. 

https://www.anthropic.com/news/prompt-caching

"Writing to the cache costs 25% more than our base input token price for any given model, while using cached content is significantly cheaper, costing only 10% of the base input token price."

**Comment by maledorak** [comment]
There is already a discussion about that feature: https://github.com/paul-gauthier/aider/issues/1086

**Comment by fry69** [comment]
Even better: Prompt caching is already in the main branch, see here -> https://github.com/paul-gauthier/aider/issues/1086#issuecomment-2297256228
