### ISSUE TITLE
Ability to set various models for various tasks

### ISSUE THREAD

**Issue by Lash-L** [paul-gauthier/aider#1134]
### Issue

It would be nice if I could specify what llm to use for various different tasks that aider performs. I do not have the full knowledge of all of the prompts aider sends, but I assume that are split up into a lot of smaller steps. There's some parts that I assume could be run on cheaper models. Basically a model for generating code and a model for everything else?

Again, I'm not sure all of the prompts that are being used under the hood, but I think this would be a helpful feature

**Comment by fry69** [comment]
FYI: aider already uses a "strong" model for coding tasks and a "weak" model for commit messages and summarizing.

**Comment by lvalics** [comment]
Could be an idea to setup (like in CrewAI) a small team, like a DevOps, Documenter, Tester, Fronten Programmer, Backend Programmer and on a debate something like /debate to discuss an implementation from different point of view. Then let the user to decide on best implementation, after the debate.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
