### ISSUE TITLE
Unexpected behavior with --map-tokens parameter

### ISSUE THREAD

**Issue by Daoctor** [paul-gauthier/aider#1136]
### Issue

Hi, 
I've discovered that the `--map-tokens` parameter is not behaving as expected. The intended functionality is to specify the maximum number of tokens that the repo map will use. However, when a value is set for `--map-tokens`, the actual token usage far exceeds the specified limit.

Test Environment:
- Git repository: `.git` with 104 files
- Aider v0.51.0 
- `--map-tokens 2000`

Expected Behavior:
The `--map-tokens` parameter should limit the number of tokens used for creating the repo map to the specified value.

Actual Behavior:
When a value is set for `--map-tokens`, the token usage significantly exceeds the specified limit.

### Screenshot
![image](https://github.com/user-attachments/assets/505997dd-ff6e-4554-809c-d6d47cbf6e7c)

### Enable verbose output
![image](https://github.com/user-attachments/assets/2966d93c-f676-452e-8dba-54b67631dedd)

### Version and model info

Test on Aider v0.51.0, Aider v0.50.1, Aider v0.50.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, `--map-tokens` is a suggestion not a max. I've updated the docs to reflect this.

If you haven't added any editable files to the chat, aider uses a larger repo-map in order to help identify relevant content since there's nothing else to go on.

**Comment by Daoctor** [comment]
> Thanks for trying aider and filing this issue.
> 
> Sorry, `--map-tokens` is a suggestion not a max. I've updated the docs to reflect this.
> 
> If you haven't added any editable files to the chat, aider uses a larger repo-map in order to help identify relevant content since there's nothing else to go on.

Thank you. You've solved my doubt. I just tried adding the file and everything works fine.
