### ISSUE TITLE
Model is not mapped - Warnings make mess of output

### ISSUE THREAD

**Issue by nktice** [paul-gauthier/aider#1140]
### Issue

In running aider with the following command
```bash
aider --model ollama/llama3.1:70b 
```
I'm getting warnings, cutting into the output and making a mess. 
Here's an example, of the text that's cutting in to the aider output.  
```bash
00:51:26 - LiteLLM:WARNING: litellm_logging.py:2323 - Model is not mapped in model cost map. Defaulting to None model_cost_information for standard_logging_payload
00:51:26 - LiteLLM:WARNING: litellm_logging.py:1318 - Model=llama3.1:70b not found in completion cost map. Setting 'response_cost' to None
00:51:26 - LiteLLM:WARNING: litellm_logging.py:2323 - Model is not mapped in model cost ma
```
I have tried running this with the warnings turned off ( with the following ) 
```bash
aider --model ollama/llama3.1:70b --no-show-model-warnings
```
Alas that doesn't help resolving this issue... so I thought I'd write.
It'd be really great if it was clear as to where to adjust settings 
to configure this, such as disabling output, or specifying...
It'd be really great to configure prefixes such as ollama.
By definition it is a local model and will have no charge - 
so other models, will default to have no costs, unless specified. - 
so that new models loaded on local loaders won't have such issues. 

For comparison loading with the following seems to work just fine.
```bash
aider --model ollama/llama3.1
```
And it's clear to me that ollama is working, with either model.  

### Version and model info

aider-chat                               0.51.0
model ollama/llama3.1:70b

**Comment by nktice** [comment]
I have managed to find what I think works around the issue I had... I've documented my installation process in full detail here :  
https://github.com/nktice/AMD-AI/blob/main/ollama-litellm-aider.md

**Comment by paul-gauthier** [comment]
Please upgrade to the latest version of aider. This warning was a bug in litellm, which is now fixed.

**Comment by nktice** [comment]
Excellent, thank you... that issue appears resolved after the update.

**Comment by maleadt** [comment]
I'm still seeing a warning using `ollama/llama3.1:70b` using aider 0.54.12; is this expected?

```
$ aider --model ollama/llama3.1:70b
Model ollama/llama3.1:70b: Unknown context window size and costs, using sane defaults
```

**Comment by paul-gauthier** [comment]
That is expected, unless you have created a model settings file for your Ollama model.

https://aider.chat/docs/config/adv-model-settings.html
