### ISSUE TITLE
Share configuration which used for writing `aider` itself

### ISSUE THREAD

**Issue by dantetemplar** [paul-gauthier/aider#1141]
### Issue

I've noticed that you wrote "Aider wrote 56% of the code in this release." in releases. I wonder what models and prompts do you use.

I guess It will be very helpful if you share sample of your message history and configs with community!

Thanks :heart:

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Closest you can probably do is check the commit history in github. Commits by "Paul Gauthier (aider)" were done by aider.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
