### ISSUE TITLE
Missing model chatgpt-4o-latest

### ISSUE THREAD

**Issue by david-strejc** [paul-gauthier/aider#1142]
### Issue

There is new model - due to community it is the "best one" https://platform.openai.com/docs/models chatgpt-4o-latest

**Comment by fry69** [comment]
The best model - due to aider community and benchmarks - is `Sonnet-3.5`. `chagpt-4o-latest` is optimized for the ChatGPT website, not coding tasks via the API.

See also the leaderboard -> https://aider.chat/docs/leaderboards/

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use it like this:

```
aider --model chatgpt-4o-latest
```

But the default 4o that aider uses seems to work better.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
