### ISSUE TITLE
How can I point to specific framework's docs or examples?

### ISSUE THREAD

**Issue by djl0** [paul-gauthier/aider#1146]
### Issue

If I want to build something using a relatively new framework which may have changes in syntax or design patterns since the model was trained (eg LlamaIndex or Polars), is there a way to point to that repo locally where docs or the code live?

**Comment by tdobson** [comment]
There's not a sort of regular way of doing that easily within standard operations. I have sympathy for this, as I personally use a framework called Mantine and it's fairly new and rapidly changing (and I love it), but it means the models are frequently wrong unless I supply the docs.

There's no super standard way (at present) of saying "yo aider, the docs are here" other than perhaps scraping them all into a file and including them in the repo(?) or one off searching for the docs needed and adding them with /web or copy/pasting the relevant docs into the request you send aider.

I have a sense that as caching requests in some models becomes cheaper and more prevelant, we'll provide the docs to the models alongside the code, eg /add frameworkManual.md

**Comment by tdobson** [comment]
related: https://github.com/paul-gauthier/aider/issues/1005

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use `/read` to load in documentation.

**Comment by djl0** [comment]
hi @paul-gauthier thanks for your reply! Is this a new feature? I don't see the command here: https://aider.chat/docs/usage/commands.html

Do you have any examples for this?

**Comment by tdobson** [comment]
/read is an alias for /read-only

/read big-documentation-manual.html
/add frameworkfile.tsx
Please change this framework file following the documentation!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
