### ISSUE TITLE
it can't update the code file if /add multi files

### ISSUE THREAD

**Issue by tocer** [paul-gauthier/aider#1147]
### Issue

If I only /add one file, then the chat can update the code of that file, if I add more files, it outputs the entire code of that file and lets me update it manually, even if I ask it to update the specified file.

How to get it to follow my instructions to continue updating files?

### Version and model info

aider v0.51.1
model: deepseek-coder

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html
