### ISSUE TITLE
Question: Enter in terminal should produce new line, not submit.

### ISSUE THREAD

**Issue by bdmorin** [paul-gauthier/aider#1150]
### Question

When using Aider in the terminal, sometimes I need to break up answers or want to bullet point something, only every time I hit enter, I submit everything. 

The question: Is there a way to submit it with ctl-enter or something? If this is documented, I couldn't find it. 

### Version and model info

n/a

**Comment by Noctree** [comment]
I second this, makes it impossible to send stacktraces to let the AI fix them

**Comment by sholub89** [comment]
+1

**Comment by tdobson** [comment]
I hear what you're saying, and I empathise - I work around this by doing ---- every time I really want to press enter - the model understands and aider is happy. It isn't elegant though, and I certainly empathise. It's worth noting that there is a documented answer to this https://aider.chat/docs/usage/tips.html

**Comment by bdmorin** [comment]
Paste... 📄
Why the hell didn't I think of that.
Also thanks for the link, I completely missed that.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Unfortunately there is no portable way to accept control-enter or shift-enter as input. META-Enter works, but in some environments that means doing ESC+Enter.

See also these docs:
https://aider.chat/docs/usage/commands.html#entering-multi-line-chat-messages

Also, you can do `/clipboard` to paste arbitrary text in from the clipboard.

**Comment by bdmorin** [comment]
> Thanks for trying aider and filing this issue.

Thank you for this amazing tool!
