### ISSUE TITLE
/read-only automatically adds back ticks around file name, causing it not to be found

### ISSUE THREAD

**Issue by gkford** [paul-gauthier/aider#1151]
### Issue

Example:

If I starting typing the file name after read-only, back ticks are added automatically like so:
```
> /read-only `api/database_info_for_aider.md`                                                                                                                                             

File not found: /root/walkit/`api/database_info_for_aider.md`
```

If I then delete the back ticks, it works:
```
> /read-only api/database_info_for_aider.md                                                                                                                                               

Added /root/walkit/api/database_info_for_aider.md to read-only files.
api/database_info_for_aider.md                                                                                                                                                            
```

### Version and model info

Aider v0.51.1
Main model: claude-3-5-sonnet-20240620 with diff edit format, prompt cache, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 68 files
Repo-map: using 1024 tokens, files refresh
VSCode terminal detected, pretty output has been disabled.

**Comment by gkford** [comment]
Also, it doesn't seem to be possible to add a list of files with /read-only in the same way as with /add

eg:

```
> /read-only api/src/messages/message.model.ts api/src/messages/messages.service.ts                                                                                                       

File not found: /root/walkit/api/src/messages/message.model.ts api/src/messages/messages.service.ts
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Both of those issues should be fixed in the main branch now, with some new test coverage.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
