### ISSUE TITLE
Keep-alive for prompt caching

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#1152]
### Issue

Would it be possible for aider to automatically send some minimal prompt to Claude to prevent the 5 minute cache timeout, if the user hasn't done anything for the last 4.5 minutes?
I assume this would prevent tokens from being re-sent.
This would need a sensible stop time, e.g. 1 hour, in case the user has stopped.

**Comment by DamianB-BitFlipper** [comment]
Cool idea!

**Comment by lockmeister** [comment]
@paul-gauthier , thanks for your great work, I see you've implemented this https://aider.chat/docs/usage/caching.html#preventing-cache-expiration
