### ISSUE TITLE
Discussion: Would it be valuable to be able to tell aider to remember certain thigns as part of the prompt?

### ISSUE THREAD

**Issue by brooksc** [paul-gauthier/aider#1153]
### Issue

I've been using aider for the last week with deepseek's hosted model and the smaller one on ollama.  The former works well, the latter not so much.

I've found aider at times will do things I don't want to.  and it does these across multiple scripts.  I'd love to force it to remember some instructions like:

1. Just do a simple import.  Don't wrap imports in functions that execute pip install.  I'll do that thanks.  
2. Don't delete any functionality I do not ask you to delete.  
3. ...

I'm hoping prepending this to the prompt would prevent the problematic behavior.  Particularly on the locally hosted models.

### Version and model info

aider 0.51.1

**Comment by lockmeister** [comment]
Have you tried creating a file with those instructions and add them to the context with /add ?
I think with the new prompt caching, you would pay for the tokens for that file once and it would be cached after that.

**Comment by brooksc** [comment]
What a wonderful idea, I never thought of that.  Thank you, I'll do that!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/usage/conventions.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by brooksc** [comment]
Thanks Paul I should have closed it. 

I've added a conventions.md file to my project and that's working fine, but a few observations.

1. For me I wanted to have one conventions.md for all my python projects across multiple git repos.  I tried to store it at ~/.conventions.md and create a symlink in the project, but aider complained about it spanning git repos.
2. I'd find it valuable if this was a per-language config I could just set once -- and only override it in the rare case.

I'm a hobbyist so I get this may be different for company software repos.

Also for anyone else finding this in the future -- this is what my conventions.md reads (of course I used AI to expand it with common python conventions)

Please follow these instructions in everything you do:
1. DO NOT REMOVE FUNCTIONALITY UNLESS EXPLICITLY REQUESTED.
2. Do not install Python packages via code; just inform me to run pip.
3. DO NOT REMOVE COMMENTS unless explicitly requested.
4. Always add a #!/usr/bin/env python3 at the top of the file.
5. Include import statements at the top of the file.

Conventions:
------------
1. Use snake_case for variable and function names.
2. Use UPPERCASE for constants.
3. Use PascalCase for class names.
4. Use spaces around operators and after commas.
5. Use 4 spaces for indentation (no tabs).
6. Keep lines to a maximum of 79 characters.
7. Use descriptive variable names.
8. Add docstrings to all functions, classes, and modules.
9. Use type hints for function arguments and return values.
10. Use 'is' or 'is not' for comparisons to None, True, or False.
11. Use context managers (with statements) when dealing with resources.
12. Follow PEP 8 style guide for Python code.
13. Organize imports into three groups: standard library imports, third-party imports, and local application imports, separated by a blank line.
14. Avoid wildcard imports (e.g., from module_name import *).
15. Use list comprehensions and generator expressions where appropriate for readability and efficiency.
16. Use f-strings for formatting strings (Python 3.6+).
17. Handle exceptions using try/except blocks and avoid using bare except clauses (always specify the exception type).
18. Avoid mutable default arguments in function definitions (e.g., use None and check inside the function).
19. Ensure that each Python file ends with a newline.
20. Use the built-in logging module for logging rather than print statements for debugging.
21. Avoid deep nesting of code blocks to maintain readability (e.g., by returning early from a function).
22. Use the __name__ == '__main__' guard to ensure that code only runs when the script is executed directly, not when it is imported as a module.
23. Comment your code where necessary to explain the why behind non-obvious decisions or algorithms.
24. Regularly refactor your code to improve readability, maintainability, and performance.
25. Write unit tests to verify the correctness of your code and follow Test-Driven Development (TDD) principles where applicable.

**Comment by paul-gauthier** [comment]
You should be able to use `/read` or `--read` to point to a conventions file anywhere in your filesystem.

Also see these recently updated docs:
https://aider.chat/docs/usage/conventions.html#always-load-conventions
