### ISSUE TITLE
[Question] How to add context in the chat window without triggering a model response?

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [paul-gauthier/aider#1154]
### Issue

Hi all!

I know it is possible to create a file, add it and have that be my "extra" context. But sometimes I just want to add a bit of context without going through the hassle of the file stuff. 

I currently do /ask for this, but this seems 1) wasteful 2) the model response may confuse the context I am trying to add.

Is there a way to add context to the chat history without triggering any model response?

**Comment by razhangwei** [comment]
How about /clipboard?

**Comment by DamianB-BitFlipper** [comment]
Interesting hack. I'll give it a look.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Type in your context. Then just don't press enter until you are ready to type in an actual instruction?

**Comment by DamianB-BitFlipper** [comment]
That works and it's what I am currently doing. I'm making an aider plugin for Emacs.

I wanted to add "context" to aider from Emacs's IDE functionality (ie: with a keybinding, make the focus a specific variable, and then your coding command can be "Make this more modular") and it know what you're referring to. Right now I'm making a prompt prefix that gets prepended to all /code, /ask requests.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
