### ISSUE TITLE
~ in path does not become user directory

### ISSUE THREAD

**Issue by larryhudson** [paul-gauthier/aider#1155]
### Issue

If I try to add a file with a path starting with the ~ alias for my home directory, the path does not work correctly. I get an error like this:

```
> /read-only ~/README_CONVENTIONS.md

File not found:
/Users/larryhudson/my-current-directory/~/README_CONVENTIONS.md
```

I would like to be able to use the ~ alias so that I can store useful files outside of the current repo - eg. global code conventions etc. At the moment, it means I need to write out the absolute path (e.g. /Users/larryhudson/).

### Version and model info

Aider v0.51.0
Model: Claude 3.5 Sonnet
macOS Sonoma 14.3.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Great idea! Aider just added this feature.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by larryhudson** [comment]
Great, thank you so much! I'm loving Aider, it's been a huge productivity boost. Thanks for all your work on it!
