### ISSUE TITLE
Question: What makes Aider work so well in comparison to others?

### ISSUE THREAD

**Issue by ariel-frischer** [paul-gauthier/aider#1157]
### Issue

I'm curious why `aider` is working so well, for editing files specifically. I understand there is a repo map feature which does seem novel, but what else is going on under the hood? I've tried GptEngineer, Amazon Q, AutoGPT, and open-interpreter, this repo seems to be the most useful and effective by far. I may need to retry these alternatives and make sure I'm using Claude 3.5 Sonnet but the `aider` workflow does seem more productive.

As a follow-up, I'm curious what could we do to improve it further? Outside of improving the actual LLM model? I noticed this website has some benchmarking rankings: https://www.swebench.com/ so perhaps one of the other repositories is also doing something novel that `aider` is not.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The aider blog has a number of articles that describe some of the things that help aider work well.

https://aider.chat/blog/

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
