### ISSUE TITLE
Fuzzy create/edit file detection?

### ISSUE THREAD

**Issue by tmm1** [paul-gauthier/aider#1159]
### Issue

Sometimes models will use basename for filenames in edits. Maybe the "create new file" detection could short-circuit if a fuzzy match is found?

```
Client.kt
Create new file? [Y/n] n
Skipping edits to Client.kt

HDHR.kt
Create new file? [Y/n] n
Skipping edits to HDHR.kt
──────────────────────────────────────────────────────────────────────────────────────────────────────
app/src/main/java/com/getchannels/android/dvr/Client.kt app/src/main/java/com/getchannels/android/hdhr/HDHR.kt
> 
```

### Version and model info

aider 0.52.1

**Comment by paul-gauthier** [comment]
Thanks for letting me know about this.

Others are reporting similar in discord:

https://discord.com/channels/1131200896827654144/1131200896827654149/1277637343423234160

I will work on it.

**Comment by paul-gauthier** [comment]
I just added a strong prompt asking for the full file path. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
