### ISSUE TITLE
feature request: let context consist of changes, not only files

### ISSUE THREAD

**Issue by alexanderkjeldaas** [paul-gauthier/aider#116]
Sometimes large PRs should be broken into smaller pieces, and in those cases, being able to operate on a set or range of commits in addition to the source code could be useful.

One way to do this could be that the `/add` command could add *changes*, in the form of a range of commits, a branch, a commit or similar.  This can be designed in various ways, but to get an idea of what this could enable we can look at an example

Example 1:

Let's say there is a PR that contains 5 commits.  We want to isolate the "configuration changes", the "refactoring changes (no semantic change)", and "the core change" into 3 parts.

```
> /add-branch PR-big-change
> /tokens
Approximate context window usage, in tokens:

     271 system messages
     835 chat history                            use /clear to clear
   3,941 branch PR-big-change  
      34 mod.rs    use /drop to drop from chat
     650 config.rs use /drop to drop from chat
   9,831 shuffler.rs     use /drop to drop from chat
========
  16,099 tokens total
     285 tokens remaining in context window
  16,384 tokens max context window size
> extract configuration changes from PR-big-change
... feeding diff HEAD..PR-big-change to gpt... with rest of context
....
NOTE: Updated context, PR-big-change diff is now 112 lines smaller
>  /diff
...
> /diff PR-big-change
... diff HEAD..PR-big-change
> extract refactorings from PR-big-change that do not change semantics.
...
```

**Comment by joshuavial** [comment]
I've been doing things like `/run diff main` on feature branches to get context into the chat (particularly useful for documentation). Are you wanting something with more granular control where a user can easily add or drop particular commit diffs from the context window?

I'd be curious to hear more about the ideal user experience as it isn't clear to me what this should look like.

i.e. if we go with an /add-diff command
`/add-diff [branch]` would be the same as `/run diff [branch]`
`/add-diff [branch] [commit]` where the commit is an autocomplete off the title or hash?
`/drop-diff` drops all diffs
`/drop-diff [commit]` drops a particular one and autocompletes off ones in context

**Comment by alexanderkjeldaas** [comment]
@joshuavial I didn't know about the `/run diff [branch]` command - I will have to test it before commenting, maybe it already does what I want!

**Comment by alexanderkjeldaas** [comment]
I think `/run` looks excellent, but my testing shows a big drawback. Adding to the chat means also processing gpt output as potential updates to the systems.  This is a disaster when you only want to add it to the context. The "disaster" involves getting a large number of bad edits, and answering "n" to all of these edits.  Can't even press Ctrl-C as then you don't get it into the context.

I think what you suggested elsewhere - putting snippets into files and `/add`-ing them as files is a workaround that would actually work, but then why not have a `/run-add` command which does exactly this, adding the output from a command to the context, but not involving gpt?

**Comment by joshuavial** [comment]
That makes sense, I was often working on small changes and it was easy to unwind the actions (with ctrl c or n) when I did the diff. I also would usually do it with no files added to the context. 

Makes me wonder if it would be useful to have the run output moved to a different part of the prompt, or maybe have a way to intentionally steer it to context vs instruction.

**Comment by paul-gauthier** [comment]
> Can't even press Ctrl-C as then you don't get it into the context.

Pressing CTRL-C should not prevent any of the conversation from staying in the chat history. If you are seeing otherwise, please let me know because that's a bug. 

The idea is that you can use CTRL-C to stop GPT when you see it doing something wrong, and then you can discuss the partial output it already generated when you're giving it corrections or new directions.

**Comment by paul-gauthier** [comment]
I think this feature request is probably out of scope for aider at this time.

I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
