### ISSUE TITLE
How to suppress code diff output from the screen?

### ISSUE THREAD

**Issue by greendrake** [paul-gauthier/aider#1160]
### Issue

Whenever I ask it to do something with my codebase, it outputs all the file diffs on the screen. I don't need that. I just want it to do the job quietly, commit and tell me when done. How to instruct it to behave that way?

For example, I have a small Golang codebase (13 files). I issue this command:

> Rewrite this codebase in JavaScript to be run in web browsers. Do it quietly, do not tell me what you are doing. Just do the job and tell me when done.

— and everything it does gets shown on the screen.

### Version and model info

Aider v0.52.1
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 13 files
Repo-map: using 1024 tokens, auto refresh

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The diff you see is the model specifying how to edit the code. There's no way to suppress showing it.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
