### ISSUE TITLE
Feature Request: Option to Skip All URLs in Input

### ISSUE THREAD

**Issue by ryanfreckleton** [paul-gauthier/aider#1163]
### Issue

**Problem:**
When pasting data into Aider chat that contains multiple URLs (e.g., in a JSON format), Aider currently asks individually whether to add each URL. This can be cumbersome when dealing with a large number of URLs.

**Proposed Solution:**
Introduce an option to skip all URLs in the input with a single character input, similar to the current approach for adding URLs. For example, using "N" could skip all URLs.

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
