### ISSUE TITLE
BUG: Using 0.52.1 and prompt caching to hold a large data file for reference, edits are no longer applying

### ISSUE THREAD

**Issue by 5ocworkshop** [paul-gauthier/aider#1164]
### Issue

I have a 5000 line data file that contains organization names and id strings.  I have loaded it in to the cache via /read and I then want to query it with dirty data strings.  I have that working fine.

However I now have aider helping me write a small client/server setup so I can send the queries to the server and have it return the desired match result or error.  But I noticed something really strange.  Sonnet is giving me nice code and explanations, as always, but it doesn't seem to be triggering the actual diffs and updates. 

I have to prompt it explicitly to provide the updates.  Here is how I am starting aider 0.52.1:

--sonnet \
--cache-prompts \
--no-stream \
--dark-mode \
--edit-format udiff

This is on Debian on WSL2.  Very small repo, <10 files.  Just a sandbox trying to make this script.

**Comment by alexandj90** [comment]
Try —edit-format diff

**Comment by 5ocworkshop** [comment]
> Try —edit-format diff

Will do, but  is there a reason udiff wouldn't work due to a recent change?

**Comment by 5ocworkshop** [comment]
I think this is being addressed here: https://github.com/paul-gauthier/aider/issues/1169
