### ISSUE TITLE
QUESTION: Why do the model developers not ensure that the models are fully aware of the latest version of their APIs?

### ISSUE THREAD

**Issue by 5ocworkshop** [paul-gauthier/aider#1166]
### Issue

 Why do the model developers not ensure that the models are fully aware of the latest version of their APIs?  And failing that why do they not provide a plain text link on their website that would allow an LLM to quickly ingest the information about the API so that they can write compliant code?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, this isn't something can help with. Maybe talk to Anthropic or OpenAI?

**Comment by andrewsgeller** [comment]
> ### Issue
> Why do the model developers not ensure that the models are fully aware of the latest version of their APIs? And failing that why do they not provide a plain text link on their website that would allow an LLM to quickly ingest the information about the API so that they can write compliant code?
> 
> ### Version and model info
> _No response_

it’s definitely annoying, but not all models have context up through the date their API or libraries have changed. I find it most frustrating with OpenAI, but it applies to llama-index and some other toolboxes as well.
