### ISSUE TITLE
Why i do not use Aider but i would like too

### ISSUE THREAD

**Issue by onigetoc** [paul-gauthier/aider#1171]
Here's the translation:

"I would like to use 'aider', but what repels me the most is being unable to work in the folder I want without having an associated GitHub project. I have many projects that I won't put on GitHub, but I can't use 'aider' because I can't work in a specific folder of my choice. I don't understand this insistence on always associating it with a GitHub project."
And if we can, then it's not really well exlained anywhere.

### Version and model info
@atest

_No response_

**Comment by wbazant** [comment]
You can skip the git integration.

**Comment by richarda23** [comment]
I've started using it today for a brand new project. You don't have to have a project on Github. You can just use git locally and not publish your project at all.

**Comment by paul-gauthier** [comment]
Thanks for your interest in aider and filing this issue.

You don't need to do anything with GitHub to use git. Git runs purely locally on your machine.

So you can certainly use aider with git without using GitHub. Or you can use aider without even using git at all with the `--no-git` switch.

This doc may be helpful:

https://aider.chat/docs/git.html#disabling-git-integration

**Comment by onigetoc** [comment]
It just always go to base Windows /USERNAME
if i open Aider in a project folder in Cursor or VS Code terminal, I cannot add files because it's always returning back to the base Windows path /USERNAME folder.

```
Note: in-chat filenames are always relative to the git working dir, not the current working dir.
Cur working dir: C:\Users\LENOVO\APPS\0-Node\1-project-starter\terminal-pstarter
Git working dir: C:\Users\LENOVO
```

**Comment by onigetoc** [comment]
I do not know if the last updated fixed it, but now i can easily add files from a VS Code / Cursor project.
It asked me if i wanted to add or create a repo and i write no 'n'
and finally did not create a map and i can now add files from the path i'm at.
GREAT. (Its now simpler, fast and easy)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by onigetoc** [comment]
@paul-gauthier 
I Just wanted to know if you confirm or not that you did the modification? 
But it seems that is the case, but let me know to be sure because i tell everyone you did fix it or make it easier to add files. :)
