### ISSUE TITLE
Disable suggest running commands

### ISSUE THREAD

**Issue by zenturacp** [paul-gauthier/aider#1173]
### Issue

The new feature is very frustrating - especially when running platform io or other projectes, nice for some areas but here it suggests on every commit to run monitor and build etc.

Can i somehow disable the feature?

### Version and model info

Aider v0.52.1
Main model: claude-3-5-sonnet-20240620 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 7 files
Repo-map: using 1024 tokens, auto refresh
VSCode terminal detected, pretty output has been disabled.
Use /help <question> for help, run "aider --help" to see cmd line args

**Comment by banahogg** [comment]
One related issue that I've seen is that the model will give a command to run but will also give a variant with a path to be filled in, which definitely shouldn't be run:

`> Remove the empty python file

Certainly! To remove the empty python file, we don't need to make any changes to the existing files. Instead, we can use a shell command to delete the file. Here's the command you can run:

```bash
rm python
```

This command will remove the empty file named "python" from your current directory.

If you want to ensure you're removing the correct file or if you're not in the directory containing the file, you might want to use the full path. For example:

```bash
rm /path/to/your/project/python
```

Replace "/path/to/your/project/" with the actual path to the directory containing the empty python file.

After running this command, the empty python file will be deleted from your file system.
Tokens: 4.3k sent, 154 received. Cost: $0.02 message, $0.05 session.

rm python
Run shell command? [Y/n]

Running rm python

rm /path/to/your/project/python
Run shell command? [Y/n] n`

**Comment by zenturacp** [comment]
Now i got this - then it suggest running git to commit and it also does it it self :-) It really makes sense to have this feature but it would be nice to have a white list of what to suggest  - this is very buggy indeed

```
To simulate adding this new file to the repository and committing it, you could run the following commands:

 git add PROJEKT.md
 git commit -m "feat: Tilføj projektbeskrivelse i PROJEKT.md"
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The main branch has stronger prompting around these issues.

**Comment by zenturacp** [comment]
> The change is available in the main branch. You can get it by installing the latest version from github:
> 
> 
> 
> ```
> 
> python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
> 
> ```
> 
> 
> 
> If you have a chance to try it, let me know if it works better for you.

I will try later - what about the ability to disable the feature? It should be an option - I actually use aider a lot for writing and making project descriptions, technical project plans, it should never run a command in these kinds of situations

**Comment by zenturacp** [comment]
> If you have a chance to try it, let me know if it works better for you.

Still a big issue - i upgraded and i asked it to make a MD file and then it suggests to type it but i have it open in my editor.. 

```
This command will display the contents of the newly created SVAR_REVIEW.md file in the console.


Tokens: 10k sent, 1.6k received. Cost: $0.06 message, $0.06 session.

SVAR_REVIEW.md
Create new file? (Y)es/(N)o [Yes]:
Applied edit to SVAR_REVIEW.md
Commit cd9ae8f docs: restructure and clean up SVAR.md content

type SVAR_REVIEW.md
Run shell command? (Y)es/(N)o [Yes]: n
You can use /undo to undo and discard each aider commit.
```

Would really love to disable the feature - at least until its more stable, or add a whitelist of what it should do?

**Comment by quocdat-le-insacvl** [comment]
IMO, most of the time it's counterproductive. It should be disabled by default, or at least have a disable option as suggested above 👍

**Comment by aelaguiz** [comment]
thanks paul, this was sorely needed for my use cases

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
