### ISSUE TITLE
Some drive-by easy-to-fix code smells

### ISSUE THREAD

**Issue by akaihola** [paul-gauthier/aider#1174]
### Issue

This is a collection of things I noticed in the Aider code base while working on it. These should all be trivial to clean up without changing behavior or breaking anything. I'm happy to make a PR or PRs for these if needed.

### Variable `added_fnames` in [`cmd_add`](/paul-gauthier/aider/blob/483b7ec41fcbf43d37c6319dac7690c6be2e4cb8/aider/commands.py#L555-L633) is only modified, never read

```python
555:     def cmd_add(self, args):
...
558:         added_fnames = []
...
613:                     added_fnames.append(matched_file)
...
633:                     added_fnames.append(matched_file)
```

### [`expand_subdir()`](/paul-gauthier/aider/blob/483b7ec41fcbf43d37c6319dac7690c6be2e4cb8/aider/commands.py#L1081-L1090) yields both `Path`s and `str`s

```python
def expand_subdir(file_path):
    file_path = Path(file_path)
    if file_path.is_file():
        yield file_path          # <-- this is a `Path`
        return

    if file_path.is_dir():
        for file in file_path.rglob("*"):
            if file.is_file():
                yield str(file)  # <-- this is a `str`
```

### Version and model info

Aider 0.52.2-dev 483b7ec41fcbf43d37c6319dac7690c6be2e4cb8

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

A PR would be welcome.
