### ISSUE TITLE
Read my project folder to create the script.

### ISSUE THREAD

**Issue by cloudgprabhu** [paul-gauthier/aider#1178]
### Issue

Is there a way to add / review the project folder to create a script ? The "Claude Dev" VSCode does that which is missing in aider... e.g, If I ask for create something, the plugin will review the project folder and provide necessary scripts.

Attached image for reference is the feature I'm looking for in Aider.

![Screenshot 2024-08-25 at 7 12 23 PM](https://github.com/user-attachments/assets/9aad95de-d756-4e83-b48d-342b60a51ae8)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/repomap.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
