### ISSUE TITLE
Resume previous chat context after restarting aider in the same repo

### ISSUE THREAD

**Issue by techguysimon** [paul-gauthier/aider#118]
Is there anyway to resume a previous context? I see .aider.chat.history.md & .aider.input.history but I don't see any signs that this is being used in any way. 

I'm experimenting using aider for pretty complex app and I have done a good amount of prompting to get the process going and then I entered a typo when adding a file that caused aider to crash. I open aider back up and it has no clue what I was doing and why. Nothing more than what it can gather from existing code

**Comment by joshuavial** [comment]
As a work around you could read through your chat history file and save snippets you want to reuse into ai specific documentation folder. Then you can just add and drop those snippets as you like and it should help you recreate chat context reasonably well.

**Comment by MohHeader** [comment]
> file and save snippets you want to reuse into ai specific documentation folder.

I really liked this idea, I was always thinking about something like README.md but for aider to give it a more context about the project it is working in.

Never thought to do that manually through a file then just simply /add it to the conversation, Perhaps I have a tendency to over-engineer things. 😨
Still, it could serve as a good starting point for establishing best practices.

Thanks @joshuavial for the insight!

**Comment by paul-gauthier** [comment]
Aider saves all the messages you type and makes them available in the input history. These persist across sessions. 

You can use the up arrow to scroll back through history. Or control-r to search. 

By default the input history is stored in a file local to the git repo. You can use a command line option or config setting to store it in your home directory, if you want history to be shared across all projects.

**Comment by paul-gauthier** [comment]
I'm going to close this, and continue further discussion in #166 since there's already a bit more detail in that discussion.

**Comment by fishony** [comment]
test
