### ISSUE TITLE
Playwright is not supported on non-Ubuntu Linux distros -- perhaps can be replaced?

### ISSUE THREAD

**Issue by atemerev** [paul-gauthier/aider#1180]
### Issue

Playwright is heavyweight and not supported on Fedora and other non-Ubuntu linux distros. Therefore, /web functionality mostly doesn't work. Perhaps it can be replaced with a more lightweight solution like Trafilatura?

### Version and model info

Aider 0.52.1, Fedora 40

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider falls back to httpx if playwright is not available.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
