### ISSUE TITLE
Feat: Ability to set the Anthropic API base URL

### ISSUE THREAD

**Issue by sammcj** [paul-gauthier/aider#1182]
### Issue

It would be great if you could set the anthropic API base (similar to the openai api base).

This would allow you to use Anthropic models hosted on Bedrock via an API key rather than having to have an AWS login, logging in and getting AWS access keys.

### Version and model info

- Aider 0.52.1
- Model Claude 3.5 on bedrock

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I think you can use `ANTHROPIC_API_BASE`.

**Comment by szad670401** [comment]
same issue.

We are using an internal proxy for Claude 3.5 set up within the company, and the invocation format follows OpenAI’s format. (Claude 3.5 is called through OpenAI’s API interface.) It seems that Aider does not yet support this invocation method.
I tried the following:
```
aider --openai-api-base=https://ai.model.server:8000/v1 --openai-api-key=xxxx
  --model claude-3-5-sonnet-20240620 --weak-model gpt-4o-mini
  ```
  This command automatically recognizes the Claude name and redirects to the Anthropic API, but I expect the OpenAI API.
```
aider --openai-api-base=https://ai.model.server:8000/v1 --anthropic-api-key=xxxx 
  --model claude-3-5-sonnet-20240620 --weak-model gpt-4o-mini
  ```
  Neither of these commands works properly.

**Comment by paul-gauthier** [comment]
This doc may be helpful:

https://aider.chat/docs/llms/openai-compat.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by paul-gauthier** [comment]
Unfortunately it doesn't appear that litellm supports `ANTHROPIC_API_BASE`. You could open an issue with them.

**Comment by paul-gauthier** [comment]
Yes, but I can't get litellm to honor it. So again, maybe open an issue with them.

**Comment by paul-gauthier** [comment]
If you think litellm is honoring the `ANTHROPIC_API_BASE` environment variable, then please go ahead and use it. If you find that it is not honoring that environment variable, you need to open an issue with litellm. Aider doesn't need to do anything.
