### ISSUE TITLE
Missing Azure ENV Variables Error Message Clarity

### ISSUE THREAD

**Issue by Hoekz** [paul-gauthier/aider#1186]
### Issue

![Screenshot 2024-08-26 at 12 35 47 PM](https://github.com/user-attachments/assets/a1bb657e-493c-46e2-8eff-2b2b0d00e18e)

Currently if you are missing _any_ of the AZURE variables, this error message is printed:

```
Model azure/gpt-4o-deployment: Missing these environment variables:
- AZURE_API_BASE
- AZURE_API_VERSION
- AZURE_API_KEY
```

In reality, I had both the API Version and Key correctly listed and has written `AZURE_API_URL` instead of `AZURE_API_BASE`. It would be helpful to update the messaging to either say that "at least one of the following environment variables is missing" or to only list the specific variable(s) missing as I spent a little while trying to figure out how I could `echo` the variables but `aider` could not see them.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I've made that change. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
