### ISSUE TITLE
How to change the directory where Aider saves\creates files

### ISSUE THREAD

**Issue by Ltbltbltbltb** [paul-gauthier/aider#1187]
### Issue

I'm looking for a way to configure Aider to save files in a specific directory rather than the default one. I've checked the documentation and existing issues but couldn't find a clear solution. Could you please guide me on how to achieve this?

The files are currently being created and saved in: "C:\Users\lucas\". I want to change this to "C:\Users\lucas\miniconda3\envs\aideeerrr\Scripts" in order to use Cursor together with Aider.

### Version and model info

Windows 11

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You probably created a git repo in your home directory. You should create a git repo in the dir where you want aider to work with `git init`.

**Comment by Ltbltbltbltb** [comment]
Thank you, Man!
