### ISSUE TITLE
OpenAI forwarding API configuration

### ISSUE THREAD

**Issue by LiGenYu2007** [paul-gauthier/aider#1188]
OpenAI forwarding API configuration error, use the official website tutorial to configure 
(
setx OPENAI_API_KEY "sk-xxx"
setx OPENAI_API_BASE "https://api.wlai.vip"
aider --model openai/gpt-4o
)
![7d71e946f34f03e02c27f6c01721292](https://github.com/user-attachments/assets/e80a2eac-0cdf-4aeb-a536-5e9564801d20)
There is no output

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This is most likely a problem with your api server. It's not responding, or not responding in an OpenAI compatible way.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
