### ISSUE TITLE
Generating testcases for QA engineers

### ISSUE THREAD

**Issue by atomicsyed-99** [paul-gauthier/aider#120]
Hi Paul , this is an amazing tool , love the expansive range of use-cases this can be employed for!. I wanted to know , how can we use aider to generate testcases for the QA engineers of a team to test each and every time a change is made to some code file in the repo/codebase. Lets say a project has 1000+ files and I need aider to understand the codebase structure in such a way that every time a developer makes some change and creates a PR for the QA/tester to deploy and check the relevant impact areas in the product , he doesnt need to sit and ideate the possible impact areas in the product due to this change that he needs to test. Can aider be used to identify these possible impact areas and generate the relevant test-cases for the same (the testcase should be used to validate the possible impact areas basically) . Please let me know your thoughts on the same , thanks!

**Comment by paul-gauthier** [comment]
I'm not sure this is a use case that is currently within the scope of this project. I could imagine there might be creative ways to use aider for this purpose. If you do come up with an approach, I would be curious to hear about it. But it's not really central to the functionality that aider is currently trying to provide.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to reopen it or file another issue if there's more you would like to discuss.
