### ISSUE TITLE
Inquiry: Code Scanning & Code Quality Tools for Security Practices

### ISSUE THREAD

**Issue by diopresi** [paul-gauthier/aider#1201]
Hi,

First of all, thank you for developing and maintaining "aider." It's an impressive tool, and I'm excited about its potential in AI-assisted pair programming.

I have a few questions regarding the current and future capabilities of "aider":

### Questions:
1. **Current Features:**
   - Does "aider" currently include any tools or plugins for code scanning to detect potential security vulnerabilities in the AI-generated code?
   - Are there any existing features that enforce code quality standards, such as linters or static analysis tools?

2. **Roadmap:**
   - If such features are not currently available, are there any plans to integrate code scanning and code quality tools to ensure that the generated code adheres to security best practices?
   - Is there a public roadmap available where users can track the planned features and enhancements for "aider"?

### Additional Context:
Ensuring that AI-generated code is secure and adheres to best practices is crucial for many developers and organizations. Integrating code scanning and quality tools would significantly enhance the reliability and safety of the code produced using "aider."

Thank you for considering my questions. I'm looking forward to your response.

**Comment by tdobson** [comment]
I can have a go for you:

1)
a) Nope.
b) yes. See https://aider.chat/docs/usage/lint-test.html - you could run security testing suites you like via the --test-cmd option

2)
a) I suspect not
b) Here on github and on discord.

**Comment by diopresi** [comment]
Thanks for reply @tdobson ,

Wondering how can we leverage the `--test-cmd`, i'm thinking of integrating snyk into the workflow, can anyone point right direction, an example would be greatly appreciated.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You could try `--test-cmd "snyk test"` to have it scan the repo whenever you run `/test`.

**Comment by fdietze** [comment]
Any shell command which gives feedback on what is wrong and where success can be determined by the exit code should work. If you want to use multiple tools at the same time, use a shell script.

**Comment by diopresi** [comment]
Thanks much!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
