### ISSUE TITLE
The LLM did not conform to the edit format - DeepSeek-Coder-V2

### ISSUE THREAD

**Issue by ptrac3** [paul-gauthier/aider#1208]
When running local Ollama model DeepSeek-Coder-V2 I am receiving the following error message, it should be noted that this does not happen with LLAMA 3.1 8 or online models such as Claude or ChatGPT.

After having initiated a git repo and given the first instruction, aider will complaint about the LLM not conforming to the edit format:

```
The LLM did not conform to the edit format.
https://aider.chat/docs/troubleshooting/edit-errors.html

No filename provided before ``` in file listing
```

After that, it will then print a final error message before stopping:

```
litellm.APIConnectionError: Ollama Error - {'error': 'an unknown error was encountered while running the model '}
Traceback (most recent call last):
  File "/Users/user/anaconda3/lib/python3.11/site-packages/litellm/utils.py", line 10042, in chunk_creator
    response_obj = self.handle_ollama_stream(chunk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/anaconda3/lib/python3.11/site-packages/litellm/utils.py", line 9465, in handle_ollama_stream
    raise e
Understood. Here's a Python script without a specific filename but with proper formatting:
```

This results in aider not being able to produce any code with the result. It is weird that his happens with DeepSeek-Coder-V2 which was supposed to be one of the best model to work with.
I am including below additional details regarding my current aider and model versions/configuration (if there is something else to share please let me know):

`aider --version`

`aider 0.54.3`

From Ollama, after running ollama run ollama/deepseek-coder-v2:
```
>>> /show system
No system message was specified for this model.
>>> /show template
{{ if .System }}{{ .System }}

{{ end }}{{ if .Prompt }}User: {{ .Prompt }}

{{ end }}Assistant:{{ .Response }}

```

```
>>> /show info
  Model
  	arch            	deepseek2	
  	parameters      	15.7B    	
  	quantization    	Q4_0     	
  	context length  	163840   	
  	embedding length	2048     	
  	
  Parameters
  	stop	"User:"     	
  	stop	"Assistant:"	
  	
  License
  	DEEPSEEK LICENSE AGREEMENT  	
  	Version 1.0, 23 October 2023	
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by ptrac3** [comment]
> Thanks for trying aider and filing this issue. This doc may be helpful:
> 
> https://aider.chat/docs/troubleshooting/edit-errors.html

Hi there and thanks for the reply! I did already have a look at that but, as deepseek-coder-v2 should be compatible with aider https://aider.chat/docs/llms/deepseek.html is there any more guidance on this? To me it seems to be a bug or an issue preventing the LLM from working, or does aider only officially support DeepSeekCoder-V2 APIs?

**Comment by paul-gauthier** [comment]
You appear to be using a quantized version of deepseek coder, which isn't as capable as the real, full version.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by remmen-io** [comment]
I have the same with a on-prem provided DeepSeek-Coder-V2-Lite-Instruct (using vllm)

https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct

Is this due to the Instruct version?

**Comment by remmen-io** [comment]
I was able to fix this  by adding the correct model information
```
➜ cat ~/.aider.model.metadata.json
{
 "openai/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct": {
        "max_tokens": 20000,
        "max_input_tokens": 20000,
        "max_output_tokens": 8192,
        "input_cost_per_token": 0.0,
        "output_cost_per_token": 0.0,
        "litellm_provider": "openai",
        "mode": "chat",
        "supports_function_calling": true
 }
}
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html
