### ISSUE TITLE
View aider settings

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#1211]
### Issue

It would be useful to be able to see what Aider options are set. Eg. with a /settings command.
I tried /help but it was not able to tell me what is set.

### Version and model info

aider 0.54.4

**Comment by lockmeister** [comment]
I found this out because I've set my aider.conf.yml to include these lines:

```
# my personal preferences
no-auto-commits: true
vim: true
cache-prompts: true
cache-keepalive-pings: 5
no-stream: true
sonnet: true
auto-lint: true
```
however, when I run aider it _does_ auto-commit, this makes me assume it is ignoring my .aider.conf.yaml in my ~ directory, or perhaps I've incorrectly specified the settings in the yaml.

It would be useful to have a /settings command to check this.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

That's a great idea. I added `/settings`.

The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --upgrade

# or try this...
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by lockmeister** [comment]
That worked, thanks so much!
@paul-gauthier , I can't believe how quickly you do these fixes. Aider is a fantastic project and you are doing a great job.

I've installed the latest version, for the record I prefer to install it using pipx as you recommend in your documentation. To install the latest version I use

pipx install --suffix=@dev --force git+https://github.com/paul-gauthier/aider.git

and then I can run it using

aider@dev

As you know, `pipx` allows you to install Python packages in isolated virtual environments, ensuring no conflicts while making them globally accessible. It's ideal for managing command-line tools, providing clean uninstalls, security, and compatibility with multiple Python versions without cluttering your global environment.

**Comment by vsvito420** [comment]
ah great. i woundered today how i bricked my aider after updating. i did reinstall with --force worked fine.
heres what i still got from the logs before i fixed aider by reinstall

c:\Users\vitos\Documents\GitHub\aider2>aider
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in runmodule_as_main
  File "<frozen runpy>", line 88, in runcode
  File "c:\users\vitos\.local\bin\aider.exe\main.py", line 4, in <module>
ModuleNotFoundError: No module named 'aider'
