### ISSUE TITLE
"Warmed cached tokens" message interferes with prompt

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#1212]
### Issue

While typing a prompt, the "warmed cache tokens" message gets printed on top of the prompt as I'm typing

### Version and model info

aider 0.54.4
sonnet

**Comment by paul-gauthier** [comment]
Good point. I've changed that message to only show with `--verbose`.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by lockmeister** [comment]
@paul-gauthier, your workrate is phenomenal! You addressed this issue so fast. Thanks for your work on this project.

I've installed the latest version, for the record I prefer to install it using pipx as you recommend in your documentation. For the latest version I use

````
pipx install --suffix=@dev --force git+https://github.com/paul-gauthier/aider.git
```
and then I can run it using 

```
aider@dev
```

I'll close this after I test it for a while and make sure the issue is fixed

**Comment by lockmeister** [comment]
I tested @paul-gauthier 's fix above, it seems to have worked. Thanks Paul!
