### ISSUE TITLE
Possiblity of using preauthorised GPT4 API access on plaforms like Steamship with aider?

### ISSUE THREAD

**Issue by antoan** [paul-gauthier/aider#122]
I'd like to figure out if it would be possible in principle to make aider work with 3rd pary GPT4 API access provided by platforms like Steamship, to avoid having to wait for general API accessibility from OpenAI.

https://www.steamship.com/plugins/gpt-4

With Steamship you can 'create' a private GPT4 instance and get a Starship API key, I'm in the process of trying to clarify with them if this is a valid OpenAPI key I can use with aider, which I doubt. Here is what they have mentioned to me so far: 

_Are the underlying OpenAI keys available for 3rd party tools code which require them, under a starship account?

Yes, you can write a tool which uses the pre-authenticated LLMs. All the tools [in this folder](https://github.com/steamship-core/python-client/tree/main/src/steamship/agents/tools/text_generation) do exactly that._

Failng that, would be grateful for any suggestions on how I could go about integrating aider with the pre-authenticated models provided, by their [SDK](https://github.com/steamship-core/python-client), my self. 

Any thoughts/suggestions/starting point would be much appreciated.

**Comment by paul-gauthier** [comment]
Do they provide an OpenAI compatible API? Aider has some support for experimenting with models which do. This FAQ might be helpful:

https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc

**Comment by antoan** [comment]
@paul-gauthier Thank you for your input, much appreciated Paul.

Cheers
