### ISSUE TITLE
AttributeError in scrape_with_playwright when response is None

### ISSUE THREAD

**Issue by hoeoek** [paul-gauthier/aider#1224]
### Bug Description
The `scrape_with_playwright` method in the `Scraper` class raises an `AttributeError` when the `response` object is `None`. This occurs when a page fails to load, causing the code to attempt to access `header_value` on a `NoneType` object.

### Steps to Reproduce
1. Use the `Scraper` class to scrape a URL that results in a failed or empty response.
2. Observe that an `AttributeError` is raised in the `scrape_with_playwright` method.

### Expected Behavior
The method should handle the case where the `response` object is `None` gracefully, without raising an `AttributeError`.

### Actual Behavior
When the `response` object is `None`, the following error is thrown:

`AttributeError: 'NoneType' object has no attribute 'split'`

### Code Reference
The issue occurs in this section of the code:
```python
response.header_value("content-type").split(";")[0] if response else None
```

### Version and model info

Aider v0.54.6
Playwright v1.46.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
