### ISSUE TITLE
claude>deepseek (aider) but why

### ISSUE THREAD

**Issue by vsvito420** [paul-gauthier/aider#1227]
### Issue

hi i reached my claude limit so i got a new ai bot deepseek. however i think claude is muuuch better. the point is i feel like some aider features are missing in deepseek. /map for example (i dont know what it realy does but it doesnt work) 2. **i would like to be able to select the strong and weak ai. for example claude for power deepseek for weak**

**Comment by lockmeister** [comment]
have you tried https://openrouter.ai/
It allows you (effectively) infinite use of Claude, at quite a reasonable cost

**Comment by Alexxosipov** [comment]
Agree with @lockmeister. I'm using openrouter's claude model, using aider 3-4 hours a day and didn't reach the limit even once.

But the feature request is great, selecting weak model might be useful

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can pick the main model with `--model xxx` and the weak model with `--weak-model xxx`. You can force the repomap to be on with `--map-tokens 1024`, but that will often confuse models which aren't strong enough to understand it.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
