### ISSUE TITLE
Aider[Browser] isnt able to /run anything

### ISSUE THREAD

**Issue by vsvito420** [paul-gauthier/aider#1228]
### Issue

in terminal aider i can for example do /run wrangler deploy but the web version of aider cant RUN things.

### Version and model info

aider 0.54.7-dev

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
