### ISSUE TITLE
ignoring git repository

### ISSUE THREAD

**Issue by dhdevdk** [paul-gauthier/aider#123]
Is it possible to run aider without git, even if a git repository is present? I understand that git is integrated into aider, but I've noticed that I keep making small changes, and it's quite obstructive when everything is instantly committed. Ideally, I'd like to keep a chat with aider open all the time, ask something, check its changes in my IDE, possibly make small modifications, and then commit.

Is this kind of workflow possible?

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

This FAQ entry may provide helpful info:
https://aider.chat/docs/faq.html#how-does-aider-use-git

**Comment by dhdevdk** [comment]
Ahh I haven't seen the `--no-git` option. Thanks!
