### ISSUE TITLE
sonnet via litellm proxy

### ISSUE THREAD

**Issue by paul-gauthier** [paul-gauthier/aider#1249]
Thanks. I have installed it and will try it out.

I think I have an issue, though. I launch it like this:

```
aider --model-metadata-file ~/claude_3_5_sonnet.json --model openai/claude-3-5-sonnet 
```

It uses a Sonnet 3.5 model, hosted on AWS, running through a LiteLLM proxy. So this gives it an OpenAI API, but the model is Anthropic. We have a metadata file (below) that controls how it behaves. However now, I don't think this is working anymore.

Metadata file:

```json
{
    "claude-3-5-sonnet": {
        "max_tokens": 4096,
        "max_input_tokens": 200000,
        "max_output_tokens": 4096,
        "input_cost_per_token": 0.000003,
        "output_cost_per_token": 0.000015,
        "litellm_provider": "anthropic",
        "mode": "chat",
        "supports_function_calling": true,
        "supports_vision": true,
        "tool_use_system_prompt_tokens": 159,
        "supports_assistant_prefill": true
    }
}
```

And the warning on startup:

```
Model openai/claude-3-5-sonnet: Unknown context window size and costs, using sane 
defaults.
Did you mean one of these?
- anthropic/claude-3-5-sonnet
- claude-3-5-sonnet
For more info, see: https://aider.chat/docs/llms/warnings.html
```

Has something changed in this area?

_Originally posted by @efunneko in https://github.com/paul-gauthier/aider/issues/1223#issuecomment-2322157670_

**Comment by paul-gauthier** [comment]
@efunneko 

I *think* you may want to do change your metadata file to be like this. The key should match the model, so `openai/claude-3-5-sonnet`. And *maybe* you want `"litellm_provider": "openai"` not `anthropic`.

Hard for me to know for sure, given this is a custom setup.

```
{
    "openai/claude-3-5-sonnet": {
        "max_tokens": 4096,
        "max_input_tokens": 200000,
        "max_output_tokens": 4096,
        "input_cost_per_token": 0.000003,
        "output_cost_per_token": 0.000015,
        "litellm_provider": "openai",
        "mode": "chat",
        "supports_function_calling": true,
        "supports_vision": true,
        "tool_use_system_prompt_tokens": 159,
        "supports_assistant_prefill": true
    }
}
```

**Comment by efunneko** [comment]
Thanks for your suggestions. It turns out that the key in the file seems to work with and without the "openai/" prefix, but the litellm_provider needs to be set to openai. 

One question I still have is whether I am missing out on any Sonnet specific optimizations in aider if it thinks I am using openai but really am using sonnet?

**Comment by paul-gauthier** [comment]
You will need to make sure your model settings and model metadata reflect the values for Sonnet. See aider/models.py for details on how Sonnet's settings are configured.

https://aider.chat/docs/config/adv-model-settings.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
