### ISSUE TITLE
2 potential issues

### ISSUE THREAD

**Issue by knowcell** [paul-gauthier/aider#125]
I used aider on Mac and PC.  Amazing tool, thanks @paul-gauthier.  Couple of things I observed with VS code.

1) 'Failed to apply edit to file_name.py' response after processing a prompt.  I noticed that on a Mac, this came up if the python script was the active window.  It went away if I selected some other file as the active window before aider ended its response.  That did not help on a PC.

2) seems to be unaware of file contents.  I get responses like 'Please provide the relevant sections of your code so I can show you exactly how to implement these changes.'.  Giving a comment line from the code was not sufficient context and I had to copy the whole code into the terminal to get aider to recognize the context and provide a response.  Is that expected behavior? (It is a small script, about 100 lines long.)

**Comment by joshuavial** [comment]
I don't know about number 1, but number 2 surprises me - did you use the `/add [filename]` command to get the file into Aider before instructing it in the changes you wanted? You shouldn't have to copy and paste files into the chat window.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

It might be helpful if you can share some logs of the chats that weren't working the way you expect. Either screenshots, or even better by getting the logs from `.aider.chat.history.md`.

Also, you may want to review this FAQ entry:
https://aider.chat/docs/faq.html#aider-isnt-editing-my-files

**Comment by knowcell** [comment]
Here an example of the chat transcript:

# aider chat started at 2023-07-19 09:33:43

> Aider v0.9.0  
> C:\Users\bhad0\anaconda3\envs\aider\Scripts\aider plot_random.py  
> Model: gpt-4  
> Creating empty file plot_random.py  
> Files not tracked in .git:  
> - plot_random.py  
> Add them? y  
> Added plot_random.py to the git repo  
> Commit 8138ecf Added new files to the git repo: plot_random.py  
> Git repo: .git  
> Repo-map: basic using 1024 tokens (ctags executable not found)  
> Added plot_random.py to the chat.  
> Use /help to see in-chat commands, run with --help to see cmd line args  

#### what does the script do?  

I'm sorry, but I can't provide the information you're looking for. The script content for 'plot_random.py' is not provided. Could you please provide the content of the script or describe what it does?


# aider chat started at 2023-07-19 09:36:04

> Aider v0.9.0  
> C:\Users\bhad0\anaconda3\envs\aider\Scripts\aider /add plot_random.py  
> Model: gpt-4  
> Creating empty file \add  
> Files not tracked in .git:  
> - ..\..\..\add  
> Add them? y  

# aider chat started at 2023-07-19 09:36:42

> Aider v0.9.0  
> C:\Users\bhad0\anaconda3\envs\aider\Scripts\aider  
> Model: gpt-4  
> Git repo: .git  
> Repo-map: basic using 1024 tokens (ctags executable not found)  
> Use /help to see in-chat commands, run with --help to see cmd line args  

#### what does the script do?  

I'm sorry, but without access to the content of the scripts, I can't provide an accurate description of what they do. Could you please share the content of the scripts or describe their functionality?


#### What does the script below do? import numpy as np  
#### import matplotlib.pyplot as plt  
####   
#### # Generate 1000 random numbers between 0 and 1  
#### random_numbers = np.random.rand(1000)  
####   
#### # Plot a histogram with 10 bins  
#### plt.hist(random_numbers, bins=10)  
####   
#### # Set the title and labels  
#### plt.title('Histogram of 1000 random numbers')  
#### plt.xlabel('Value')  
#### plt.ylabel('Frequency')  
####   
#### # Show the plot  
#### plt.show()  

The script generates a histogram of 1000 random numbers between 0 and 1.

Here's a step-by-step breakdown:

1. It imports the necessary libraries: numpy for generating random numbers and matplotlib for plotting.

2. It generates 1000 random numbers between 0 and 1 using numpy's `rand` function and stores them in the `random_numbers` variable.

3. It creates a histogram of these random numbers using matplotlib's `hist` function. The histogram has 10 bins, meaning the range of values (0 to 1) is divided into 10 equal parts and the number of random numbers falling into each part is counted.

4. It sets the title of the plot to 'Histogram of 1000 random numbers' and labels the x-axis as 'Value' and the y-axis as 'Frequency'.

5. Finally, it displays the plot using matplotlib's `show` function. The plot shows the distribution of the 1000 random numbers.

**Comment by paul-gauthier** [comment]
It looks like you are trying to use aider with an existing script called `plot_random.py`? But when you launch aider with `aider plot_random.py`, that file is not in the current directory. So aider *creates an empty file* named `plot_random.py` for you. See this snippet of the output you provided above:

```
Aider v0.9.0
C:\Users\bhad0\anaconda3\envs\aider\Scripts\aider plot_random.py
Model: gpt-4
Creating empty file plot_random.py <=====
```

You need to provide aider with the actual `plot_random.py` file that you want it to work on. Either by changing to the directory that contains it before you launch aider. Or by giving aider a full path to the file.

**Comment by knowcell** [comment]
Thank you, that was it!  I was one folder out when starting aider.  Thanks again for creating such a useful program.
