### ISSUE TITLE
Add support for GitHub models

### ISSUE THREAD

**Issue by stochmal** [paul-gauthier/aider#1250]
### Issue

https://github.com/marketplace/models

You get daily free credits when using this service so great to experiment with aider

**Comment by fry69** [comment]
aider uses [LiteLLM](https://github.com/BerriAI/litellm) to communicate with LLMs, you need to ask there if you want support for this API.

If the API is compatible to OpenAI, have a look here -> https://aider.chat/docs/llms/openai-compat.html

**Comment by stochmal** [comment]
cool will try it out as Github models use OpenAI API standard

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
