### ISSUE TITLE
0.54.8 release does not take `OPENAI_API_KEY` env var

### ISSUE THREAD

**Issue by chenrui333** [paul-gauthier/aider#1274]
👋 looks like something got changed in 0.54.8 release, and it does not consume the env var anymore. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/183091

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, what do you. mean it "doesn't take the OPENAI_API_KEY" variable? The link you provided shows aider stopping because the OPENAI_API_KEY env var is not set.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by chenrui333** [comment]
seems resolved now, thanks!
