### ISSUE TITLE
REQ: When rate limit message is returned from LLM, report the amount of usage in the UI

### ISSUE THREAD

**Issue by 5ocworkshop** [paul-gauthier/aider#1285]
### Issue

Is it possible when you hit the rate limit with your LLM provider, for example I am hitting it with Anthropic today, to display the actual amount of usage which is reported to be in the response header?

litellm.RateLimitError: AnthropicException - {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your daily rate limit (https://docs.anthropic.com/en/api/rate-limits); see
the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options 
for a rate limit increase."}}

I am using caching, so that may be why thinks don't line up, but I am on tier 3 and should have 5M tokens.  The UI says I have used around 4M at the moment, but starting at about 3M today it started hitting me with these rate limit messages (I wait a while and submit my prompt and get 1 or 2 in and it comes back again).  It would be good to be able to see within aider what it says the usage has been for the day when it response, if possible.

aider 0.54.8
Model: --sonnet

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Unfortunately, it's not possible for aider to know how much of Anthropic's rate limits you have been consuming. They operate on multiple time scales and count all usage in your organization.
