### ISSUE TITLE
REQ: Add a /version command that outputs the Version and model info used to report bugs here

### ISSUE THREAD

**Issue by 5ocworkshop** [paul-gauthier/aider#1286]
### Issue

It would be great if there was a /version command that could be run from within aider to generate the aider version, model info, git repo, repo map and switches set in a standard way so the output could be cut and pasted here during bug reports or feature requests.  Would encourage consistency and also reduce the time and overhead of collecting information when reporting bugs, as most of the information is only reported on launch and if you are a few hours in to a session when a bug or idea arises, it makes it easier to gather the info.

**Comment by 5ocworkshop** [comment]
Looks like the bottom of the output of /model gives some of the info although oddly the model I'm currently using (--sonnet) didn't appear?  Err, it says repo map is disabled but I don't think that is correct.  Will restart and confirm.

Aider v0.54.10
Model:  with udiff edit format
Git repo: .git with 26 files
Repo-map: disabled

Ahh, of course, I tried to set the /model and didn't provide one so it set it to null I guess?  Is that the desired behaviour or if no model is specified and one is already set, should it keep the existing model?

Ahh I see virtually all of the info is available in /settings but not in a compact way with just the key items in a single spot they can be cut and paste to add to tickets so perhaps /version is still a good idea?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I have been thinking about something like this, yes. I hope to add it soon.
