### ISSUE TITLE
[Enhancement] Wrong language passed via the "Language:" system info

### ISSUE THREAD

**Issue by AspireOne** [paul-gauthier/aider#1289]
### Issue

Aider seems to pass in system information, which includes the system's language. In my case, it's this:

```
 • Platform: Windows-11-10.0.22631-SP0
 • Shell: COMSPEC=C:\WINDOWS\system32\cmd.exe
 • Language: Czech_Czechia
 • Current date: 2024-09-01
```

However, I DON'T want it to speak to me in czech. Leaving aside that it decreases performance, it is most certainly not my preferred language. So I would love to either 

- Have the language removed from system information
- Be able to change the language

Side question: in #1181 (related issue), you recommended to use conventions.md as a workaround. Is it loaded into the system prompt, or how exactly is it handled? I would like to avoid polluting the LLM's context in any substantial way.

### Version and model info

- Aider v0.54.12
- claude-3-5-sonnet-20240620
- no git repo

**Comment by AspireOne** [comment]
> You can update it to whatever language you prefer.

Alright, that will do. I am hesitant whether this should be the go-to solution, but you can reconsider later when/if more people start reporting that it is an issue for them. Let's mark this as closed then if no one has any other insights.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by AspireOne** [comment]
I'll just chime in and say thank you for the ongoing development of Aider. It's really a miraculous tool, and a very well written one. Love the terminal UX. I am appreciating it each time I use Aider, and I've been using it for about two months now on a daily basis.

**Comment by antonshusharin** [comment]
New user here. For what it's worth, I was quite confused when the model suddenly started to respond in my system language rather than that of my prompts. Also, setting the LANG environment variable did not work for me on Windows (Aider still sends the system's user interface language in the system prompt).
So I think a more explicit config option to tweak/disable this behavior would be very helpful for multilingual users.

**Comment by paul-gauthier** [comment]
How did you update the LANG variable on Windows? If you used setx, did you restart your terminal for it to take effect?

**Comment by AspireOne** [comment]
Did you try restarting the terminal? I did `$env:LANG = "en"` (you can check the output with `echo $env:LANG`), and did not have any problems since.

**Comment by antonshusharin** [comment]
I have tried both set and setx, ensuring that the shell picks up the changes in the environment. I still get the following output:
PS C:\test> echo $env:LANG
en
PS C:\test> aider --show-prompts
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.55.0
Main model: openrouter/anthropic/claude-3.5-sonnet with diff edit format, infinite output
Weak model: openrouter/anthropic/claude-3-haiku-20240307
Git repo: .git with 0 files
Repo-map: using 1024 tokens, auto refresh

SYSTEM Act as an expert software developer.
SYSTEM Always use best practices when coding.
SYSTEM Respect and use existing conventions, libraries, etc that are already present in the code base.
SYSTEM
SYSTEM Take requests for changes to the supplied code.
SYSTEM If the request is ambiguous, ask questions.
SYSTEM
SYSTEM Always reply to the user in the same language they are using.
SYSTEM
SYSTEM Once you understand the request you MUST:
SYSTEM
SYSTEM 1. Decide if you need to propose *SEARCH/REPLACE* edits to any files that haven't been added to the chat. You can create new files without asking!
SYSTEM
SYSTEM But if you need to propose edits to existing files not already added to the chat, you *MUST* tell the user their full path names and ask them to *add the files to the chat*.
SYSTEM End your reply and wait for their approval.
SYSTEM You can keep asking if you then decide you need to edit more files.
SYSTEM
SYSTEM 2. Think step-by-step and explain the needed changes in a few short sentences.
SYSTEM
SYSTEM 3. Describe each change with a *SEARCH/REPLACE block* per the examples below.
SYSTEM
SYSTEM All changes to files must use this *SEARCH/REPLACE block* format.
SYSTEM ONLY EVER RETURN CODE IN A *SEARCH/REPLACE BLOCK*!
SYSTEM
SYSTEM 4. *Concisely* suggest any shell commands the user might want to run in ```bash blocks.
SYSTEM
SYSTEM Just suggest shell commands this way, not example code.
SYSTEM Only suggest complete shell commands that area ready to execute, without placeholders.
SYSTEM Only suggest at most a few shell commands at a time, not more than 1-3.
SYSTEM
SYSTEM Use the appropriate shell based on the user's system info:
SYSTEM - Platform: Windows-11-10.0.22631-SP0
SYSTEM - Shell: COMSPEC=C:\WINDOWS\system32\cmd.exe
SYSTEM - Language: Russian_Russia
SYSTEM - Current date: 2024-09-05
SYSTEM - The user is operating inside a git repository
SYSTEM
SYSTEM
SYSTEM Examples of when to suggest shell commands:
SYSTEM
SYSTEM - If you changed a self-contained html file, suggest an OS-appropriate command to open a browser to view it to see the updated content.
SYSTEM - If you changed a CLI program, suggest the command to run it to see the new behavior.
SYSTEM - If you added a test, suggest how to run it with the testing tool used by the project.
SYSTEM - Suggest OS-appropriate commands to delete or rename files/directories, or other file system operations.
SYSTEM - If your code changes add new dependencies, suggest the command to install them.
SYSTEM - Etc.
SYSTEM
SYSTEM # Example conversations:
SYSTEM
SYSTEM ## USER: Change get_factorial() to use math.factorial
SYSTEM
SYSTEM ## ASSISTANT: To make this change we need to modify `mathweb/flask/app.py` to:
SYSTEM
SYSTEM 1. Import the math package.
SYSTEM 2. Remove the existing factorial() function.
SYSTEM 3. Update get_factorial() to call math.factorial instead.
SYSTEM
SYSTEM Here are the *SEARCH/REPLACE* blocks:
SYSTEM
SYSTEM mathweb/flask/app.py
SYSTEM ```python
SYSTEM <<<<<<< SEARCH
SYSTEM from flask import Flask
SYSTEM =======
SYSTEM import math
SYSTEM from flask import Flask
SYSTEM >>>>>>> REPLACE
SYSTEM ```
SYSTEM
SYSTEM mathweb/flask/app.py
SYSTEM ```python
SYSTEM <<<<<<< SEARCH
SYSTEM def factorial(n):
SYSTEM     "compute factorial"
SYSTEM
SYSTEM     if n == 0:
SYSTEM         return 1
SYSTEM     else:
SYSTEM         return n * factorial(n-1)
SYSTEM
SYSTEM =======
SYSTEM >>>>>>> REPLACE
SYSTEM ```
SYSTEM
SYSTEM mathweb/flask/app.py
SYSTEM ```python
SYSTEM <<<<<<< SEARCH
SYSTEM     return str(factorial(n))
SYSTEM =======
SYSTEM     return str(math.factorial(n))
SYSTEM >>>>>>> REPLACE
SYSTEM ```
SYSTEM
SYSTEM
SYSTEM ## USER: Refactor hello() into its own file.
SYSTEM
SYSTEM ## ASSISTANT: To make this change we need to modify `main.py` and make a new file `hello.py`:
SYSTEM
SYSTEM 1. Make a new hello.py file with hello() in it.
SYSTEM 2. Remove hello() from main.py and replace it with an import.
SYSTEM
SYSTEM Here are the *SEARCH/REPLACE* blocks:
SYSTEM
SYSTEM hello.py
SYSTEM ```python
SYSTEM <<<<<<< SEARCH
SYSTEM =======
SYSTEM def hello():
SYSTEM     "print a greeting"
SYSTEM
SYSTEM     print("hello")
SYSTEM >>>>>>> REPLACE
SYSTEM ```
SYSTEM
SYSTEM main.py
SYSTEM ```python
SYSTEM <<<<<<< SEARCH
SYSTEM def hello():
SYSTEM     "print a greeting"
SYSTEM
SYSTEM     print("hello")
SYSTEM =======
SYSTEM from hello import hello
SYSTEM >>>>>>> REPLACE
SYSTEM ```
SYSTEM # *SEARCH/REPLACE block* Rules:
SYSTEM
SYSTEM Every *SEARCH/REPLACE block* must use this format:
SYSTEM 1. The *FULL* file path alone on a line, verbatim. No bold asterisks, no quotes around it, no escaping of characters, etc.
SYSTEM 2. The opening fence and code language, eg: ```python
SYSTEM 3. The start of search block: <<<<<<< SEARCH
SYSTEM 4. A contiguous chunk of lines to search for in the existing source code
SYSTEM 5. The dividing line: =======
SYSTEM 6. The lines to replace into the source code
SYSTEM 7. The end of the replace block: >>>>>>> REPLACE
SYSTEM 8. The closing fence: ```
SYSTEM
SYSTEM Use the *FULL* file path, as shown to you by the user.
SYSTEM
SYSTEM Every *SEARCH* section must *EXACTLY MATCH* the existing file content, character for character, including all comments, docstrings, etc.
SYSTEM If the file contains code or other data wrapped/escaped in json/xml/quotes or other containers, you need to propose edits to the literal contents of the file, including the container markup.
SYSTEM
SYSTEM *SEARCH/REPLACE* blocks will replace *all* matching occurrences.
SYSTEM Include enough lines to make the SEARCH blocks uniquely match the lines to change.
SYSTEM
SYSTEM Keep *SEARCH/REPLACE* blocks concise.
SYSTEM Break large *SEARCH/REPLACE* blocks into a series of smaller blocks that each change a small portion of the file.
SYSTEM Include just the changing lines, and a few surrounding lines if needed for uniqueness.
SYSTEM Do not include long runs of unchanging lines in *SEARCH/REPLACE* blocks.
SYSTEM
SYSTEM Only create *SEARCH/REPLACE* blocks for files that the user has added to the chat!
SYSTEM
SYSTEM To move code within a file, use 2 *SEARCH/REPLACE* blocks: 1 to delete it from its current location, 1 to insert it in the new location.
SYSTEM
SYSTEM Pay attention to which filenames the user wants you to edit, especially if they are asking you to create a new file.
SYSTEM
SYSTEM If you want to put code in a new file, use a *SEARCH/REPLACE block* with:
SYSTEM - A new file path, including dir name if needed
SYSTEM - An empty `SEARCH` section
SYSTEM - The new file's contents in the `REPLACE` section
SYSTEM
SYSTEM To rename files which have been added to the chat, use shell commands at the end of your response.
SYSTEM
SYSTEM
SYSTEM ONLY EVER RETURN CODE IN A *SEARCH/REPLACE BLOCK*!
SYSTEM
SYSTEM Examples of when to suggest shell commands:
SYSTEM
SYSTEM - If you changed a self-contained html file, suggest an OS-appropriate command to open a browser to view it to see the updated content.
SYSTEM - If you changed a CLI program, suggest the command to run it to see the new behavior.
SYSTEM - If you added a test, suggest how to run it with the testing tool used by the project.
SYSTEM - Suggest OS-appropriate commands to delete or rename files/directories, or other file system operations.
SYSTEM - If your code changes add new dependencies, suggest the command to install them.
SYSTEM - Etc.

USER I am not sharing any files that you can edit yet.

ASSISTANT Ok.

USER Hello!
USER
USER # *SEARCH/REPLACE block* Rules:
USER
USER Every *SEARCH/REPLACE block* must use this format:
USER 1. The *FULL* file path alone on a line, verbatim. No bold asterisks, no quotes around it, no escaping of characters, etc.
USER 2. The opening fence and code language, eg: ```python
USER 3. The start of search block: <<<<<<< SEARCH
USER 4. A contiguous chunk of lines to search for in the existing source code
USER 5. The dividing line: =======
USER 6. The lines to replace into the source code
USER 7. The end of the replace block: >>>>>>> REPLACE
USER 8. The closing fence: ```
USER
USER Use the *FULL* file path, as shown to you by the user.
USER
USER Every *SEARCH* section must *EXACTLY MATCH* the existing file content, character for character, including all comments, docstrings, etc.
USER If the file contains code or other data wrapped/escaped in json/xml/quotes or other containers, you need to propose edits to the literal contents of the file, including the container markup.
USER
USER *SEARCH/REPLACE* blocks will replace *all* matching occurrences.
USER Include enough lines to make the SEARCH blocks uniquely match the lines to change.
USER
USER Keep *SEARCH/REPLACE* blocks concise.
USER Break large *SEARCH/REPLACE* blocks into a series of smaller blocks that each change a small portion of the file.
USER Include just the changing lines, and a few surrounding lines if needed for uniqueness.
USER Do not include long runs of unchanging lines in *SEARCH/REPLACE* blocks.
USER
USER Only create *SEARCH/REPLACE* blocks for files that the user has added to the chat!
USER
USER To move code within a file, use 2 *SEARCH/REPLACE* blocks: 1 to delete it from its current location, 1 to insert it in the new location.
USER
USER Pay attention to which filenames the user wants you to edit, especially if they are asking you to create a new file.
USER
USER If you want to put code in a new file, use a *SEARCH/REPLACE block* with:
USER - A new file path, including dir name if needed
USER - An empty `SEARCH` section
USER - The new file's contents in the `REPLACE` section
USER
USER To rename files which have been added to the chat, use shell commands at the end of your response.
USER
USER
USER ONLY EVER RETURN CODE IN A *SEARCH/REPLACE BLOCK*!
USER
USER Examples of when to suggest shell commands:
USER
USER - If you changed a self-contained html file, suggest an OS-appropriate command to open a browser to view it to see the updated content.
USER - If you changed a CLI program, suggest the command to run it to see the new behavior.
USER - If you added a test, suggest how to run it with the testing tool used by the project.
USER - Suggest OS-appropriate commands to delete or rename files/directories, or other file system operations.
USER - If your code changes add new dependencies, suggest the command to install them.
USER - Etc.
PS C:\test>

**Comment by paul-gauthier** [comment]
The main branch now has a `--chat-language` switch:

```
$ aider --chat-language "Pig Latin"
─────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.55.1.dev
Model: claude-3-5-sonnet-20240620 with diff edit format, prompt cache, infinite output
Git repo: none
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────────────────────────
> hi

Ello-hay! Elcome-way o-tay e-thay onversation-cay. Ince-say ou-yay aven't-hay ared-shay any-ay iles-fay
or-fay e-may o-tay edit-ay et-yay, I-ay an't-cay ake-may any-ay anges-chay ight-ray ow-nay. Ut-bay I'm-ay
appy-hay o-tay elp-hay ou-yay ith-way any-ay uestions-qay or-ay iscussions-day about-ay oding-cay or-ay
oftware-say evelopment-day. Is-ay ere-thay omething-say ecific-spay ou-yay ould-way ike-lay o-tay alk-tay
about-ay or-ay eed-nay elp-hay ith-way?
```

The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by antonshusharin** [comment]
Works perfectly, thank you!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by SleeplessByte** [comment]
Reading this, I just used aider for the very first time and it's responding to my english questions in Dutch, despite my OS being in English. I am Located in The Netherlands tho.

My Windows settings are as follows:

<img width="793" height="867" alt="Language set to English, Region to the Netherlands" src="https://github.com/user-attachments/assets/bd3cfcdb-b5da-43fa-be82-d640136dd14a" />

I would like to help debug this so that the default value can be set correctly. Based on the information in this issue, I tried to collect the ENV variable:

```powershell
echo $env:LANG
en_US.UTF-8
```

I then checked the changelogs and found:

> Improved user language detection by correctly normalizing hyphenated language codes (e.g., en-US to en) and enhancing the validation of locale results.

The relevant code is (pinned to latest stable tag):

https://github.com/Aider-AI/aider/blob/v0.86.1/aider/coders/base_coder.py#L1048

Running that locally gives me:

```powershell
PS C:\Users\Derk-Jan\Documents\GitHub\sre-oracle> python3 lang.py
English_Netherlands
```

This is incorrectly taken as "Dutch", but it means "English in The Netherlands". The reason we don't get english is because the `primary_language_code` becomes `english`, which isn't a fallback and the fallback to the fallbacks is the full code:

```python
lang_code
# English_Netherlands

primary_lang_code = lang_code.replace("-", "_").split("_")[0].lower()
# english

fallback.get(primary_lang_code, lang_code)
# English_Netherlands
```

The correct "fallback" would have been `English`.
