### ISSUE TITLE
Extending aider to use GPT-4-0613 for more tokens/context window (16K and 32K)

### ISSUE THREAD

**Issue by rappster** [paul-gauthier/aider#129]
Hi Paul,

please excuse if this is not the right place to ask such type of questions that are somewhere between "asking", "feature request" and "could I try to modify aider to this on my own eventually". Let me know if you'd prefer to discuss things like this rather via e-mail, a discord/slack server or similar

The actual question: would it be possible to extend `aider` to make use of the new `0613` model family that offer more context window and explicitly support [function calling](https://openai.com/blog/function-calling-and-other-api-updates)?

I searched the existing issues for "gpt-4 0613" and [this](https://github.com/paul-gauthier/aider/issues/110) is the closest that I got?

Would love to help out if that's something were you could see "community support", just need to dive into the code base deeper. But with `aider` that's something that actually became fun now ;-)

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

Aider uses `gpt-4` by default which OpenAI currently maps to `gpt-4-0613`. You can specify any model with the `--model` command line arg.

This FAQ entry may be helpful:
https://aider.chat/docs/faq.html#gpt-4-vs-gpt-35

**Comment by paul-gauthier** [comment]
Regarding the function calling API, it turns out to harm code editing performance. See the benchmark results for more details:

https://aider.chat/docs/benchmarks.html

**Comment by rappster** [comment]
Very interesting! Got some reading to do tonight ;-)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
