### ISSUE TITLE
Is Aider able to talk about specifc git commit?

### ISSUE THREAD

**Issue by mikeon** [paul-gauthier/aider#1299]
### Issue

Hi, I would like to ask, if there is an option to talk about specifc commit content and also about commit diff with prev, so quicky understand the changes. If no, I would like to participate to create such a functionallity. Thanks

**Comment by ozapinq** [comment]
simple solution that i use currently is `/run git log -p <commit_sha>`. you can even talk about diffs (useful during code reviews) using `/run git diff main` or similar

**Comment by mikeon** [comment]
thanks mate, lov this
