### ISSUE TITLE
Feature Request / implement Backoff

### ISSUE THREAD

**Issue by WillTryToDoItRight** [paul-gauthier/aider#13]
Hello there, 

thanks for making this open source!
I have a request: due to being still on the free credits of OpenAI API, I  run into timeouts.

```
fetch_starred_repos.py
Add these files to the chat? y
RateLimitError: You exceeded your current quota, please check your plan and billing details.
Retry in 1 seconds.
RateLimitError: You exceeded your current quota, please check your plan and billing details.
Retry in 1 seconds.
RateLimitError: You exceeded your current quota, please check your plan and billing details.
Retry in 1 seconds.
RateLimitError: You exceeded your current quota, please check your plan and billing details.
Retry in 1 seconds.
RateLimitError: You exceeded your current quota, please check your plan and billing details.
Retry in 1 seconds.
RateLimitError: You exceeded your current quota, please check your plan and billing details.
Retry in 1 seconds.
RateLimitError: You exceeded your current quota, please check your plan and billing details.
Retry in 1 seconds.
RateLimitError: You exceeded your current quota, please check your plan and billing details.
```
Is it possible for you to implement this library to omit that?
https://pypi.org/project/backoff/

Thanks in advance.
Greetings from Germany

**Comment by paul-gauthier** [comment]
Hi, thanks for trying aider and for filing this issue. I've been meaning to switch to exponential backoff.

I pasted your issue into aider, and it updated itself:
https://github.com/paul-gauthier/aider/commit/df91e9ab1ca2ba256b1e933de793db10dcec1c9f

Hopefully this helps you manage your rate limiting issues better.
