### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by tobiasmuehl** [paul-gauthier/aider#130]
Hi,

really cool work, very useful AI tool. Is there a Discord channel for the users of `aider`? If not, should we make one?

**Comment by paul-gauthier** [comment]
Great idea!

Here's a link:

https://discord.gg/SqzfE6bw

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by 0xAxy** [comment]
discord link is expired. Please make a permenent link somewhere.

**Comment by paul-gauthier** [comment]
Sorry, the link in this issue was old. I just updated it. There's a good discord link on the homepage.

Here's the permanent link:

https://discord.gg/Tv2uQnR88V

**Comment by JWPapi** [comment]
Link is invalid again.
