### ISSUE TITLE
How to add support for a new language to repo map?

### ISSUE THREAD

**Issue by ozapinq** [paul-gauthier/aider#1301]
### Issue

Hey! 

I'm willing to add support for additional languages, but I don't get where to start. I found *.scm files under aider/queries, but still don't get how the whole machinery of repo mapping works. Could someone please point me to docs on how to do that?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/languages.html#how-to-add-support-for-another-language

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
