### ISSUE TITLE
Chat Mode Configuration Option

### ISSUE THREAD

**Issue by Ga68** [paul-gauthier/aider#1310]
### Issue

I'd love a chat-mode option for the command line options or, better yet for me, the YAML file, so that I can set aider to boot up into ask mode instead of code mode.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You should be able to add `chat-mode: ask‘ to your yaml config file.

**Comment by fry69** [comment]
You can set the default chat format with [YAML](https://aider.chat/docs/config/aider_conf.html) ->
```
## Specify what edit format the LLM should use (default depends on model)
#edit-format:
```

It `chat-mode` is an alias for `edit-format` on the command line, see here -> https://aider.chat/docs/config/options.html#--edit-format-edit_format
```
--edit-format EDIT_FORMAT

Specify what edit format the LLM should use (default depends on model)
Environment variable: AIDER_EDIT_FORMAT
Aliases:

    --edit-format EDIT_FORMAT
    --chat-mode EDIT_FORMAT
```

So this should work in `.aider.conf.yml` ->
```
edit-format: ask
```

**Comment by Ga68** [comment]
Fantastic! You're ahead of me as normal :)
It would be great to add that alias/note onto [the website](https://aider.chat/docs/config/aider_conf.html)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
