### ISSUE TITLE
Uncaught PermissionError in pathlib.py line 1232

### ISSUE THREAD

**Issue by vranjit27** [paul-gauthier/aider#1317]
i have a weird bug... there's some random file in one of my directories that is supposed to be docker exec-ed inside a container... this file contains some file paths like /root/<subdir>.... now for whatever reason, aider is looking at this line and trying to open it... getting a "PermissionError: [Errno 13] Permission denied: '/root/<subdir>'" within aider... 

the specific filepath aider is complaining about exists only in one file (it's a shell script), and only in one line: ln -s /root/<subdir>/... <link>

this is the aider output:

Aider version: 0.54.12
Python version: 3.9.18
Platform: Linux-5.13.0-52-generic-x86_64-with-glibc2.31
Python implementation: CPython
Virtual environment: No
OS: Linux 5.13.0-52-generic (64bit)
Git version: git version 2.25.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 623, in main
    repo_map = coder.get_repo_map()
  File "base_coder.py", line 599, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
  File "repomap.py", line 124, in get_repo_map
    files_listing = self.get_ranked_tags_map(
  File "repomap.py", line 466, in get_ranked_tags_map
    result = self.get_ranked_tags_map_uncached(
  File "repomap.py", line 497, in get_ranked_tags_map_uncached
    ranked_tags = self.get_ranked_tags(
  File "repomap.py", line 309, in get_ranked_tags
    if not Path(fname).is_file():
  File "pathlib.py", line 1456, in is_file
    return S_ISREG(self.stat().st_mode)
  File "pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/<path_to_file>'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
