### ISSUE TITLE
Fuzzy matching issue in find_filename

### ISSUE THREAD

**Issue by ImAmirreza** [paul-gauthier/aider#1321]
### Issue

The find_filename function in the editblock coder has a **fuzzy matching** issue that causes it to consider files with similar names but different extensions as the same file. Specifically, when searching for a filename, the function considers app.controller.ts and app.controller.spec.ts as the same file.
This issue causes problems when trying to write unit tests, as the function will not create a separate spec file and instead add the test to the end of the controller file.

### Version and model info

Model: llama3.1-70B diff

**Comment by ImAmirreza** [comment]
I understand the current workaround, but I was hoping that Aider could automatically create a new file when I ask it to write to a non-existent file. This would be more in line with the model's capabilities and would make the interaction more user-friendly.

**Comment by paul-gauthier** [comment]
As mentioned in the doc, LLMs are prone to overly focusing on the info in their context. If you don't make the blank file for them, they will often ignore your explicit request to make a new file.

**Comment by ImAmirreza** [comment]
But the llm side is ok as i said the problem is from fuzzy marching with some minor changes to find filename function i did fix it but my solution is not general so i did decide to not send pull request

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
