### ISSUE TITLE
Sonnet started impersonating me

### ISSUE THREAD

**Issue by mikehearn** [paul-gauthier/aider#1322]
### Issue

I don't think this is _really_ an Aider bug, but I'm not sure and I wonder if other people have seen it. At any rate, aider could potentially detect this has started happening and abort the inferencing.

<img width="1524" alt="image" src="https://github.com/user-attachments/assets/6e1f8b5c-af4b-479f-8ac6-b97e2d53ede9">

This happened after a pretty long session ($2.10 overall). This particular request sent 10k tokens. Also I noticed that just before this happened the output of `/voice` changed to be much lower quality, with no capital letters or punctuation being used. Also earlier in the session I was getting overload errors and backoff/retries. Is it possible Anthropic lowers the model quality significantly when under heavy load?

### Version and model info

Aider v0.54.12
Main model: claude-3-5-sonnet-20240620 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 14 files
Repo-map: using 1024 tokens, auto refresh

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This does happen occasionally to Sonnet, if the context gets long it can confuse the LLM.

This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by mikehearn** [comment]
How do I tell how long the context is? It seems like every interaction always sent about 10k-12k tokens so presumably aider was clipping the context for quite a while before this happened.

Thanks for the link. If it happens again I'll try /clear

**Comment by paul-gauthier** [comment]
You can use `/tokens` to see how many tokens you are using for each message.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
