### ISSUE TITLE
Aider recommended grep command results flooded by chat history

### ISSUE THREAD

**Issue by TzviCons** [paul-gauthier/aider#1323]
### Issue

Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 1,828 files
Repo-map: using 1024 tokens, auto refresh

I asked aider to search for usages of a method I'm in middle of refactoring. It recommended to grep the function name and upon approval, proceeded. As this function name had been mentioned quite a number of times, the grep returned countless results from the aider history files. 

Is here a way to have grep commands always exclude files in .gitignore or .aiderignore? 
![image](https://github.com/user-attachments/assets/38bbf8ee-e03d-4f4c-bd13-a92000ccc56f)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Looks like it was giving you some sensible advice. You can use `grep --exclude=.aider*` to exclude all of aider's files.

**Comment by TzviCons** [comment]
Thanks! 

I was kind of hoping that aider would do it on its own. The command it was recommending with ---exclude='.aider.history' didn't help. Does it pay to add something to the prompt so that it would exclude it without needing to be told explicitly?

Also I don't know much about how aider handles the repo map internally but can I get aider to check the repo map for usages of a certain function?

**Comment by paul-gauthier** [comment]
There's not really a direct way for aider to check for all usages of a function. You were on the right track with the grep command. Aider won't always be able to suggest the perfect shell commands to run unfortunately.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
