### ISSUE TITLE
Adding / Indexing docs

### ISSUE THREAD

**Issue by alreadyarrived** [paul-gauthier/aider#1325]
### Issue

Hi I'm wondering if it's possible to add / index documentations, especially for newer versions that sonnet may not be up to date with

### Version and model info

Latest aider with sonnet 3.5

**Comment by paul-gauthier** [comment]
This looks like a duplicate of #1005, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.
