### ISSUE TITLE
Feature Request: --on-save and --on-save-cmd

### ISSUE THREAD

**Issue by GeoffMillerAZ** [paul-gauthier/aider#1328]
### Summary

In many coding environments like VSCode, on-save actions such as auto-formatting, import sorting, and linting are common workflows. Currently, `aider` lacks support for these automatic on-save behaviors. This results in an extra manual step if users want their style preferences to apply before committing, which can be tedious and prone to missed formatting/linting issues.

### Proposed Enhancement

Introduce a new flag `--on-save` to automatically apply user-defined on-save commands (e.g., formatters, linters, import sorters) before committing any changes. This would allow `aider` to align with common workflows seen in IDEs like VSCode.

#### 1. **`--on-save` Flag**

```bash
--on-save
```

This flag would enable or disable all on-save behaviors that the user has configured, replicating the common on-save functionality seen in IDEs.

#### 2. **`--on-save-cmd` for Custom Commands**

```bash
--on-save-cmd "python: black --config pyproject.toml"
```

This flag would allow users to specify one or more on-save commands. These commands should be able to chain multiple actions for the same language, such as using `black` for auto-formatting and `isort` for sorting Python imports.

Example for Python:

```bash
--on-save-cmd "python: black --config pyproject.toml"
--on-save-cmd "python: isort --profile black ."
```

In this example:
- **`black`** is used to autoformat the Python files, and it points to the project's configuration via `--config pyproject.toml`.
- **`isort`** is used to sort imports.

This approach allows for multiple on-save actions to be defined for the same language, which helps ensure that all required formatting and sorting is completed before a commit.

#### 3. **Pre-Commit Application**

The on-save commands should be applied **before** committing any changes made by `aider`. This ensures that the final code state adheres to the user’s formatting and linting preferences.

A possible enhancement to this could involve using **two commits**:
- The first commit contains changes made by `aider`.
- The second commit contains changes made by on-save commands (e.g., formatting or sorting imports).

This separation would allow users to distinguish between `aider`’s modifications and changes made by automated tools like `black` or `isort`. Additionally, any linting or testing should be postponed until the last on-save command finishes to avoid unnecessary errors during the process.

### Use Case Example

When using a linter like `pyright` with Python, common linting errors can arise from unused imports or improperly formatted code. For example:
- **Unused imports** often cause unnecessary lint warnings, which can be automatically resolved by sorting imports using `isort`.
- **Code style violations** can be caught and automatically fixed with `black`.

Without an `--on-save` feature, users currently need to manually save the file in their IDE to apply these fixes, or run these tools manually before each commit. The proposed `--on-save` feature would streamline this process, improving workflow efficiency and reducing linting issues before they even occur.

### Benefits

- **Increased Productivity**: Users can automate formatting and sorting, reducing the need for manual intervention before commits.
- **Less Linting Noise**: Automatically fixing linting issues (like unused imports) through an on-save setup reduces false positives during code analysis.
- **Improved Code Consistency**: Ensures that files are consistently formatted and validated before any commits, leading to cleaner, more maintainable code.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/usage/lint-test.html

You can use the lint command for this. It is run whenever aider edits a file.

**Comment by GeoffMillerAZ** [comment]
> Thanks for trying aider and filing this issue. This doc may be helpful:
> 
> 
> 
> https://aider.chat/docs/usage/lint-test.html
> 
> 
> 
> You can use the lint command for this. It is run whenever aider edits a file.

Oh I guess you could just use that to solve this. Thanks!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
