### ISSUE TITLE
Support triggers

### ISSUE THREAD

**Issue by alifanov** [paul-gauthier/aider#134]
Does aider support different triggers to query LLM?
For example slack messages, task management tool, logs from server or issues from sentry

**Comment by paul-gauthier** [comment]
You could possibly script aider as part of a webhook, etc. But that is not a core use case for aider. It is really intended as an interactive tool for coding with GPT.

**Comment by alifanov** [comment]
Yes, aider offers better workflow for developing in comparison with other code assistance tools (like copilot, code whisper and etc). At least for me
Regarding triggers I was tlaking about with fixing issues after deploying (for cases that tests don't cover) so it's like enhancement for /run command

**Comment by paul-gauthier** [comment]
I think this feature request is out of scope for aider in the near future. 

I'm going to close this issue for now, but feel free to reopen it or file another issue if there's more you would like to discuss.
