### ISSUE TITLE
BUG: When running unit tests that are auto prompted to run after they are created, the output is not passed back to the LLM

### ISSUE THREAD

**Issue by 5ocworkshop** [paul-gauthier/aider#1342]
### Issue

I am added a new feature to a project.  After it added the feature, the unit test was created and then Aider asked me if I wanted to run the test command.  I said yes and the command ran (in this case it was successful).  When prompted if I want to add the output of the test to the conversation if I hit enter or say Yes, nothing happens.  I just get returned to the aider prompt.

If I /run the same command myself the output does get sent to the conversation correctly.

aider 0.54.12
--sonnet

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The output will be sent along with your next chat message.

**Comment by 5ocworkshop** [comment]
Ah sot here is a subtle difference in the almost identical prompt to what happens when you receive output using /run versus when the prompt itself sets you up to run?  Using run, when prompted, will submit the results as the next prompt when you say Yes.  If you accept the running of the command triggered from the previous prompt, and you say Yes, it will append the output to your next message but you still have the interactive opportunity to add things to the message?

**Comment by paul-gauthier** [comment]
Yes, that's correct. I agree, it's currently a bit confusing.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
