### ISSUE TITLE
Is it possible to use Llama-2

### ISSUE THREAD

**Issue by funkytaco** [paul-gauthier/aider#135]
Meta just released Llama-2, I'd like to see support for it if possible

**Comment by paul-gauthier** [comment]
@tmm1 recently shared a recipe for this: https://github.com/paul-gauthier/aider/issues/110#issuecomment-1643000033

You can also check the FAQ entry for more general info about using aider with other model:
https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc

**Comment by apcameron** [comment]
Have a look at my post on this
https://github.com/paul-gauthier/aider/issues/138
