### ISSUE TITLE
Possible Time-&-Token-Saving Search & Replace Idea...

### ISSUE THREAD

**Issue by Captain-Bacon** [paul-gauthier/aider#1354]
### Issue

Hi there,

I love Aider (with Sonnet - OpenAI was always such a moody grouch), and thought I'd see if this floats your boat:

Aider uses a lot of tokens on search and replace.  And if/when it gets it wrong then you can just watch the token count (and the $ count!) go up and up, and it takes a fair amount of time.

I was thinking of this as a potential alternative to the current S&R:  1st line of text in block, last line of text in block, and a checksum.
I was thinking that the checksum could be the character count, or the sum of the ascii character codes (!!) or something (the world could be your oyster there I guess), but the problem we all know is that the AI isn't great as an LLM at counting.  The checksum only really needs to be there if there is more than one section of code that it could refer to (hopefully anyways), but in those cases, and with the LLM being bad at numbers, then there could be a background API call that essentially asks it 'is this the code you're looking for, or this one?'.  Being able to programmatically 'copy/paste' that in a call, and get a yes/no answer should be far faster than the LLM writing out big chunks of code, sometimes multiple times before it gets it right. Ingested tokens are also a lot cheaper than output.

I expect that you've already tried or thought about something similar, and the current S&R is the most bullet-proof, but perhaps there's a flag I could tick to select fast S&R or slow S&R, and deal with the consequences.

FWIW I did try to get Aider to help me do an mvp of that in the source-code, but while we could make the flag work (/fast), we couldn't figure out how the S&R integrated into the whole.  I'd be happy to have a play around and see what works if only I knew that....FWIW

Anyway, it's not much, but hopefully it's _something_

Love 'n' lard
The Captain

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I've tried things like this and unfortunately they don't work well with most models.

**Comment by Captain-Bacon** [comment]
Thanks so much for the reply - I thought you might have already gone there a million times, but it was an itch I had to scratch, so I appreciate it.
