### ISSUE TITLE
Feature Request: Support for Structured Questions and Responses in Scripted Aider Using Pydantic Models

### ISSUE THREAD

**Issue by GeoffMillerAZ** [paul-gauthier/aider#1355]
### Summary

When using `aider` as part of a scripted or agentic workflow, it becomes important to have structured, reliable responses from the model to allow for programmatic flow control. This feature request suggests the addition of structured questions and guaranteed structured responses, leveraging models like GPT-4o that support Pydantic or Zod models. By exposing hooks for this within `aider`, it would allow scripts to interact with `aider` in a more deterministic and structured manner, driving automated processes with minimal human intervention.

### Proposed Enhancement

1. **Structured Questions Using Pydantic/Zod Models**:
   - Allow `aider` to accept structured questions, where the response is guaranteed to follow a specific schema (e.g., JSON format using Pydantic or Zod models).
   - This would enable `aider` to ask detailed questions about the code, workspace, or progress of the session and provide responses that can be consumed by the script controlling `aider`.
   - Example: 
     ```python
     {
       "response": "yes",
       "confidence": 0.97
     }
     ```

2. **Scripted Aider Flow Control**:
   - A script could ask a detailed question (e.g., about the state of the code, linting results, or following conventions) and get a structured response back.
   - This structured response could then determine the next action, such as:
     - Terminate the script if an error is found.
     - Undo the last action.
     - Pause and notify for human input.
     - Attempt a backup prompt to address issues.

3. **Configurable Model for Structured Questions**:
   - Since only certain models like GPT-4o support structured responses with Pydantic/Zod models, there should be a configuration option for specifying the model to use when asking structured questions.
   - This would allow users to ensure the correct model is used for reliable, structured output.

### Use Case Example

When dealing with large codebases, package upgrades often lead to breaking changes that require significant refactoring. One common scenario is the deprecation of methods from third-party libraries. For example, when a method is deprecated, developers need to replace every instance of it with a new method. This is further complicated when the new method requires additional arguments that were not needed in the deprecated version.

Manually identifying and refactoring code across hundreds of files can be tedious and error-prone. Automating this process allows developers to focus on higher-level tasks while ensuring consistency and correctness.

#### How This Example Code Helps:

The provided script automates the process of identifying and fixing deprecated methods across all `.py` files in a directory. It uses `aider`'s `query_with_response_model` to scan each file for library imports and deprecated method usages. If found, it replaces the old method with the new one, adding any additional required arguments. Finally, it runs a linting step to ensure the code is correctly formatted and follows the required coding standards.

This approach can save significant time in large refactorings, minimize human error, and ensure that all instances of the deprecated method are updated consistently.

#### Simple Explanation of the Logic:

1. **Loop through all Python files**: The script scans each `.py` file in the directory.
2. **Check for library import**: If the file imports the library in question, continue. Otherwise, skip to the next file.
3. **Find deprecated method usages**: If the library is imported, the script identifies every usage of the deprecated method.
4. **Fix the deprecated method**: For each finding, the script instructs `aider` to replace the deprecated method with the new method and add the necessary argument.
5. **Lint the code**: After processing all files, the script runs a lint check to ensure that the changes adhere to the project’s style guide.

#### Pseudocode:

```text
For each .py file in the directory:
  Add the file to aider's session
  Ask aider: Does this file import the required library?
  If no:
    Drop the file and continue to the next one
  If yes:
    Ask aider: Find all instances of the deprecated method
    For each usage found:
      Ask aider to replace the deprecated method with the new one
      Add the necessary arguments to the new method
    Drop the file after processing
Run a lint check to verify the code quality
```

#### Example of how the aider script could look

```
from aider.coders import Coder
from aider.models import Model
from pydantic import BaseModel, Field
from typing import List
import glob

# Pydantic model for yes/no response with confidence score
class BinaryResponse(BaseModel):
  response: str  # Either "yes" or "no"
  confidence: float = Field(..., ge=0.0, le=1.0)  # Confidence score between 0 and 1

# Pydantic model for findings in the code
class CodeFinding(BaseModel):
  finding: str  # The deprecated method name
  line_number: int  # The line number where it was found
  context: str  # A snippet or brief context of the finding

class CodeFindings(BaseModel):
  findings: List[CodeFinding]

# Initialize aider with a model and the files to work on
model = Model("gpt-4-turbo")
fnames = glob.glob("*.py")  # Find all .py files in the directory

coder = Coder.create(main_model=model, fnames=fnames)

# Define the deprecated method and the new method name
deprecated_method = "old_method"
new_method = "new_method"
new_argument = "'required_arg'"

# Loop over all Python files in the directory
for fname in fnames:
  # Add the file to the coding session
  coder.run(f"/add {fname}")

  # Check if the file imports the library in question
  query_import = f"Does the file {fname} import the library 'library_name'?"
  import_response = coder.query_with_response_model(query=query_import, response_model=BinaryResponse)

  # If the file doesn't import the library, drop it from the session and continue
  if import_response.response == "no":
    coder.run(f"/drop {fname}")
    continue

  # If the file imports the library, check for uses of the deprecated method
  query_deprecated = f"Find all instances of '{deprecated_method}' being used in the file {fname}."
  findings_response = coder.query_with_response_model(query=query_deprecated, response_model=CodeFindings)

  # Loop over all findings and instruct aider to fix each instance
  for finding in findings_response.findings:
    line_number = finding.line_number
    context = finding.context

    # Instruct aider to replace the deprecated method with the new method, adding the new argument
    prompt = (f"On line {line_number}, replace the usage of '{deprecated_method}' "
              f"with '{new_method}', and add the required argument {new_argument}. "
              f"Here is the context: {context}")
    
    coder.run(prompt)

  # Drop the file from the coding session after processing
  coder.run(f"/drop {fname}")

# After processing all files, run linting
coder.run("/lint")
```

4. **Natural Language as Unit Test**:
   - This structured question/response model could also serve as the basis for natural language-driven unit tests.
   - Example: Auto-test by prompting `aider` to check if code follows naming conventions, and receiving structured JSON feedback on test results.
   
   For instance:
```json
{
  "unit_tests": [
    {
      "test_name": "Variable Naming Clarity",
      "input_code": "int tmp = 5;",
      "expected_result": "fail",
      "actual_result": "fail",
      "metadata": {
        "issue": "Variable name 'tmp' is not clear",
        "suggestions": [
          "Use a more descriptive name, e.g., 'tempValue' or 'temporaryCounter'."
        ],
        "severity": "medium"
      }
    },
    {
      "test_name": "Casing Convention - Camel Case",
      "input_code": "int TempValue = 10;",
      "expected_result": "fail",
      "actual_result": "fail",
      "metadata": {
        "issue": "Variable 'TempValue' does not follow camelCase convention.",
        "suggestions": [
          "Rename the variable to 'tempValue' to match the camelCase convention."
        ],
        "severity": "low"
      }
    }
  ]
}
```

5. **Pre-Built Pydantic Models for Common Queries**:
   - Include pre-built models for common structured queries such as simple yes/no responses or error reports.
   - Example: A Pydantic model for yes/no questions that also returns a confidence score.
   
   Example:
```python
from pydantic import BaseModel

class ResponseModel(BaseModel):
    response: str
    confidence: float
```

   This allows for rapid integration of `aider` into larger workflows where decisions can be made based on the model's structured responses, improving automation.

### Benefits

- **Enhanced Automation**: Allowing `aider` to interact programmatically with a script by providing structured responses ensures greater automation without human intervention.
- **Flow Control**: Enables detailed control of the program’s flow based on reliable, structured data, e.g., undo actions, retry prompts, or awaiting human intervention based on the returned result.
- **Structured Unit Tests**: Enables natural language-driven unit testing, where results are returned in a structured format that `aider` can then use to drive subsequent actions.
- **Reduced Duplication of Effort**: Instead of building a separate agent to manage this functionality, this enhancement would leverage `aider`'s existing understanding of the codebase and workspace for more effective integration into workflows.

### Conclusion

This feature would greatly enhance `aider`'s usability in automated workflows, agentic processes, and scripting, by providing structured responses that can guide the flow of execution based on the content and feedback received.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This seems out of scope for aider.

**Comment by GeoffMillerAZ** [comment]
I understand. Aider lets you chat with your code, and it lets you script Aider. This feature would be needed to let your scripting chat with your code. You need predictable, machine-readable responses to do that, and Aider is already great at chatting with your code -- just not in a scripted manner.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
