### ISSUE TITLE
feature request: /undoall 

### ISSUE THREAD

**Issue by glinkot** [paul-gauthier/aider#1356]
### Issue

Would be nice to have this feature, which would rewind back all changes made in the current chat session.  I sometimes find myself 15 prompts in, realising I won't be able to get the desired result, and I run undo many times to rewind it.

**Comment by fry69** [comment]
You can achieve a similar outcome by leveraging git branches and switching between them.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Yes, for complex management of your git history aider expects you to do those changes yourself with git. I don't want users to be surprised by aider making large changes to their git history.
