### ISSUE TITLE
How to give aider permission to read-write...

### ISSUE THREAD

**Issue by PtradeLLC** [paul-gauthier/aider#136]
Hello, I am trying to debug a feature, and gave aider instructions on how to. However, I got a response back as follows:

```
The files you've mentioned are currently read-only. Could you please  
make the following files read-write so that I can propose the necessary        
changes. Once you've made these files read-write, I can provide the necessary steps to  
implement the feature 
```
I guess what I was asking is if there's any special way of doing it with aider. If not I can just `chmod +rw` like I would any other file

Please advice?
Thanks in advance

**Comment by paul-gauthier** [comment]
Thanks for trying aider, and for filing this issue.

When GPT is asking for a file to be marked read-write, it's trying to get you to add it to the chat session. It's only allowed to modify files that have been added to the session. You can do that with the `/add` command.

**Comment by paul-gauthier** [comment]
The next release of aider asks GPT to use less confusing language when it wants you to add a file to the chat. 

I'm going to close this issue for now, but feel free to reopen it or file another issue if there's more you would like to discuss.
