### ISSUE TITLE
Failing to detect some files .

### ISSUE THREAD

**Issue by hemangjoshi37a** [paul-gauthier/aider#1365]
### Issue

It is failing to detect the files in a folder and in the working directory that i want to add to aider chat but it is not detecting in the auto suggest in the chat interface . please help solve this issue .

**Comment by fry69** [comment]
For aider the git repository is the source of truth, you can't add files to the context that are not part of the current repository. See also here -> https://aider.chat/docs/git.html

**Comment by hemangjoshi37a** [comment]
then how to add ?

**Comment by hemangjoshi37a** [comment]
ok thanks for helping out .

**Comment by andrewsgeller** [comment]
Also, just as a tip. If you are using aider and add a file to your repo manually (touch /path/to/new/file), you need to manually commit that change (git add . And git commit).

Then, go back to aider and refresh the repo map /map-refresh) to allow aider to see this new file.

Then you can use /add and aider should be able to auto-find the new find and add it.

If you use the shell commands you can do all this directly from aider-chat already.

Sent from my iPhone
________________________________

**Comment by o-glethorpe** [comment]
So I just created a file and I dont want to add to git yet. Aider cant work with it?
