### ISSUE TITLE
CONVETIONS.md works?

### ISSUE THREAD

**Issue by FrankBevr** [paul-gauthier/aider#1366]
### Issue

**Hola** :wave:,

Thanks for the heavy work that you are doing. 

This is my issue. I catgegorised it in Goal, Currrent Solution, Problem, Question. 

### Goal:

Make a commit in a predefined style.

### Current Solution

```md
- Write git commit messages as Franks  Commit Style.
- Franks Commit Style looks as the following:
    ```
    :GITHUB_EMOJI: (FILE) SHORT DESCRIPTION
    
    DETAILS
    - A
    - B
    - C
    ```
 ```

### Problem
It will not work. I tried it more expressive and I tried it less expressive. It doesn't work with emojis and with doing the details.

### Question

Does someone has a nice CONVENTIONS.md file which takes influence over commit messages? If yes Can you post it, here?

</br> 

**Best regards**  
Frank :beers:

**Comment by fry69** [comment]
`CONVENTIONS.md` does not apply to commit message generation, it is happening in a different code path (and also possibly with a different LLM, see `--weak-model`) with different prompts.

See here how to customize the commit message generation -> https://aider.chat/docs/git.html#commit-messages

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
