### ISSUE TITLE
Why is aider not a command line app?

### ISSUE THREAD

**Issue by SDBlackwood** [paul-gauthier/aider#1368]
### Issue

Hey

Firstly, great work; I am really impressed with what you have done with this.  

I just wondered if there was a reason why aider needs to enter a chat session rather than just running like a normal command line app? e.g

`aider ask blah blah blah`

I ask because my command line is customised and doing things like finding files in aider seemed more difficult.  It seems like you would be able to forgo any code relating to autocomplete etc. with a command line application

**Comment by fry69** [comment]
See here -> https://aider.chat/docs/scripting.html

Your example
```shell
aider ask blah blah blah
```
works with just a little change:
```shell
aider --message "/ask What is the purpose of this code base?"
```
which will not change code, but
```shell
aider --message "Please update README.md to the current state of the code base" *.py
```
will change files.

**Comment by p-wegner** [comment]
@fry69 Currently calling a slash command this way may also trigger a folder creation prompt, which will cause the process to fail if not run with --yes and even then when it can't create C:/web like in my case. See https://github.com/paul-gauthier/aider/issues/1244

**Comment by SDBlackwood** [comment]
Great, thanks for the info
