### ISSUE TITLE
Uncaught TypeError in main.py line 170

### ISSUE THREAD

**Issue by ccc0168** [paul-gauthier/aider#1379]
Aider version: <module 'aider.__version__' from 'F:\\myenv\\aider-env\\Lib\\site-packages\\aider\\__version__.py'>
Python version: 3.12.4
Platform: Windows-11-10.0.26257-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.45.2.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 416, in main
    launch_gui(argv)
  File "main.py", line 170, in launch_gui
    if "-dev" in __version__:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'module' is not iterable

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
