### ISSUE TITLE
Unknown context window size and costs can be determined at runtime (enhancement)

### ISSUE THREAD

**Issue by iplayfast** [paul-gauthier/aider#1380]
### Issue

When using ollama I ran the following:
```
aider --model=ollama/yi-coder:latest
Model ollama/yi-coder:latest: Unknown context window size and costs, using sane defaults.
For more info, see: https://aider.chat/docs/llms/warnings.html
```
However if in another terminal I run the following:
```
 ollama run yi-coder
>>> /show
Available Commands:
  /show info         Show details for this model
  /show license      Show model license
  /show modelfile    Show Modelfile for this model
  /show parameters   Show parameters for this model
  /show system       Show system message
  /show template     Show prompt template

>>> /show info
  Model                      
  	arch            	llama 	     
  	parameters      	8.8B  	     
  	quantization    	Q4_0  	     
  	context length  	131072	     
  	embedding length	4096  	     
  	                           
  Parameters                 
  	stop	"<|endoftext|>"	        
  	stop	"<|im_end|>"   	        
  	stop	"<fim_prefix>" 	        
  	stop	"<fim_suffix>" 	        
  	stop	"<fim_middle>" 	        
  	                           
  License                    
  	Apache License           	  
  	Version 2.0, January 2004	  
```
You can see that context length is actually given. This particular model prides itself on it's large context length. 
This information can be retrieved using the ollama api
https://github.com/ollama/ollama/blob/main/docs/api.md#show-model-information

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider relies on litellm for this information. You could open a PR there to see if they would like to pull it from ollama.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by krrishdholakia** [comment]
hi @paul-gauthier what litellm function are you calling for this information? is it `get_model_info`?

**Comment by paul-gauthier** [comment]
Aider fetches and caches https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json and checks to find the model there first. If that fails, it calls `get_model_info`, yes.

**Comment by krrishdholakia** [comment]
got it - would it work if we just added the ollama check to `get_model_info`? similar to how we do it for huggingface

**Comment by paul-gauthier** [comment]
Yes, it should. Aider won't find a match in the json so it will call that method.

**Comment by automenta** [comment]
Is this why the context length seems stuck at 2048, even if the model supports larger? 
https://github.com/ollama/ollama/issues/2204#issuecomment-2103671083
https://github.com/ollama/ollama/blob/main/docs/api.md

**Comment by automenta** [comment]
![image](https://github.com/user-attachments/assets/1287888f-d45e-4a6f-b511-265313f137f8)
:lab_coat:

**Comment by paul-gauthier** [comment]
This is all outside the scope of aider, so I am going to close this issue.
