### ISSUE TITLE
Questions regarding long context, and context caching

### ISSUE THREAD

**Issue by Astlaan** [paul-gauthier/aider#1386]
### Issue

1) When selecting Sonnet as model, which is the context window size we are using? Is it the 200k window that it can use, or is aider using a different context size? I suppose that working with the full 200k window will more easily enable to have full codebase context?

2) Deepseek has caught my attention, due to it's performance, combined with it's low prices, especially when using context caching. https://platform.deepseek.com/api-docs/news/news0802/ Does Aider structure the input in such a way that enables itself to take full advantage of Deepseek's context caching? This seems interesting, because the very low cost por cache hits would probably enable whole codebase context for a lot cheaper (since the codebase doesn't have to be constantly fully processed). 

Here are the two caching scenarios that DeepSeek presents:
![image](https://github.com/user-attachments/assets/4f5cf781-63b4-4216-aa55-262bae6e904a)

**Comment by Astlaan** [comment]
Ok, I didn't know, but actually Claude Sonnet 3.5 also has the context caching feature now.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider uses whatever size context window the model offers. And yes, aider does structure the conversation to maximize caching of system prompts and read only files. Aider does support caching for Anthropic and Deepseek.

**Comment by Astlaan** [comment]
@paul-gauthier Thank you Paul :)
Clear answer and fully addresses my questions, so I think the issue can almost be closed. :)

I would just suggest perhaps to state this more clearly in the docs? In case it wasn't just me that missed those parts ;)
Something along the lines of:
- "By default, Aider uses the maximum context length provided by the models, and specify which one is use when the maximum length can be automatically determined by Aider", in https://aider.chat/docs/config/adv-model-settings.html
- A subsection about context caching in the same page, saying that Aider already structures queries in order to take full advantage of the context caching features offered by models such as Claude and DeepSeek

**Comment by paul-gauthier** [comment]
This doc may be helpful:

https://aider.chat/docs/usage/caching.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
