### ISSUE TITLE
/drop not working with subdirs on windows

### ISSUE THREAD

**Issue by paul-gauthier** [paul-gauthier/aider#139]
Hello again, I just retested the new version and thank for fixing the issue with /add. From my laymans perspective the commit issues seems to be much better now when you have the option of no commit and now that it rarely if ever does the "your existing code" commit. 
My only concern (and i dont even know if this is the case) is that when it writes the "ORIGINAL" it wastes tokens, especially if its a particularly long function or class.

Perhaps, an alternative solution, which I am sure you've thought of already, but just in case, could be to just create copies of the files, if possible, then make as many commits there as you want, this way you can get the best of both worlds.

Concerning the new 0.10.1 version currently i am encountering the following problems, which might be similar to the current ticket, so I felt like it would be better to post them here, rather than open a new one. 

1. When trying to  /drop files it gives me this error, even though they have been added in the chat successfully. I have to do /drop without specifying the file and then readd it:
 ----
![aider](https://github.com/paul-gauthier/aider/assets/128929586/b41875f2-516b-4cf4-99e4-741a3417227d)

----
Is there something wrong I am doing here?

2. This is almost certainly a me issue here - but in windows cmd/powershell i can no longer copy/paste inside once I've run aider and have to manually rewrite errors if they occur.  

3. This is more of a newbie question than an issue - I've managed to get c-tags going by adding the path to env, but i dont really understand how to use it correctly, and all i see is it taking up 1024 tokens, and still not being able to figure out if lets say i add 2 files to the chat, and exclude a 3rd (main.py), it still doesnt exactly know what functions are carried out in the main.py. I am pretty certain this is just due to my lack of understanding of the process, so any guide/info here would be greatly appreciated, as my current project is waaaaay over the 8k limit so any option to manage that would be of huge value. 

Again, thank you for this product, I cannot express enough how freaking amazing it is, especially to a total beginner such as myself. 

_Originally posted by @cranyy in https://github.com/paul-gauthier/aider/issues/90#issuecomment-1646605798_

**Comment by paul-gauthier** [comment]
Thanks for reporting this issue. There is definitely something unusual going on in your screenshot. I can not reproduce that behavior, on Mac or Windows. And it appears that there are [good test cases that should cover this situation](https://github.com/paul-gauthier/aider/blob/0e9dbddfde253b02393289b45568b9f51ed178d7/tests/test_commands.py#L85).

Can you look in `.aider.chat.history.md` and show me the startup output that appeared when you launched aider that time? I'm interested in the lines that look like this:

```
# aider chat started at 2023-07-22 12:13:32

> Aider v0.10.1-dev
> /Users/gauthier/Projects/aider/.venv/bin/aider
> Model: gpt-4
> Git repo: .git
> Repo-map: universal-ctags using 1024 tokens
> Use /help to see in-chat commands, run with --help to see cmd line args
```

**Comment by cranyy** [comment]
I just redid it - heres the log from chat.history:

# aider chat started at 2023-07-22 23:22:31

> Aider v0.10.1-dev  
> C:\Projects\aider\aider\main.py C:\Projects\aider\ChristmasStar  
> Model: gpt-4  
> Git repo: ChristmasStar\.git  
> Repo-map: universal-ctags using 1024 tokens  
> Use /help to see in-chat commands, run with --help to see cmd line args  

#### /ls  
> Repo files not in the chat:  
> config.json  
> hyperfeatey.py  
> main.py  
> mls.py  
> plotey.py  
> requirements.txt  
> stoceky.py  
> test\config.json  
> test\hyperfeatey.py  
> test\main.py  
> test\mls.py  
> test\plotey.py  
> test\stoceky.py  

#### /add test\main.py  
> No files matched 'test\main.py'. Do you want to create the file? y  
> Added test\main.py to the chat  

#### /drop test\main.py  
> No files matched 'test\main.py'

**Comment by paul-gauthier** [comment]
Thanks for providing those logs. That helped me reproduce the problem. It's related to issue #95.

The root cause was inconsistent handling of paths when aider is launched from a directory which is not the the git working directory (root). I made things consistent.

Now, when you are using in-chat commands insider aider you are always working with paths that are relative to the git working directory, even if you launch aider from elsewhere in your filesystem (inside or outside of the git repo). I think this the simplest and clearest way to handle things. It's worth noting that it handles the case where you run `aider /path/to/a/git/repo` from a place completely outside that repo. That was the situation in your logs above.

Thanks again for the help debugging this.

**Comment by cranyy** [comment]
Thank you, I retested again, and the drop seems to work now, but now it seems that the issue from #90 is back again, and I can no longer /add folders or files that werent part of the original repo, they cant be discovered with /ls and have to manually add them:

# aider chat started at 2023-07-23 17:11:02

> Aider v0.10.1-dev  
> C:\Projects\aider\aider\main.py C:\Projects\aider\1234  
> Model: gpt-4  
> Git repo: .git  
> Repo-map: universal-ctags using 1024 tokens  
> Use /help to see in-chat commands, run with --help to see cmd line args  

#### /ls  
> Repo files not in the chat:  
> .dockerignore  
> .flake8  
> .github\workflows\release.yml  
> .github\workflows\ubuntu-tests.yml  
> .github\workflows\windows-tests.yml  
> .pre-commit-config.yaml  
> 2g1.py  
> CNAME  
> HISTORY.md  
> LICENSE.txt  
> MANIFEST.in  
> README.md  
> _config.yml  
> _layouts\default.html  
> aider\__init__.py  
> aider\coders\__init__.py  
> aider\coders\base_coder.py  
> aider\coders\base_prompts.py  
> aider\coders\editblock_coder.py  
> aider\coders\editblock_func_coder.py  
> aider\coders\editblock_func_prompts.py  
> aider\coders\editblock_prompts.py  
> aider\coders\single_wholefile_func_coder.py  
> aider\coders\single_wholefile_func_prompts.py  
> aider\coders\wholefile_coder.py  
> aider\coders\wholefile_func_coder.py  
> aider\coders\wholefile_func_prompts.py  
> aider\coders\wholefile_prompts.py  
> aider\commands.py  
> aider\diffs.py  
> aider\dump.py  
> aider\io.py  
> aider\main.py  
> aider\models.py  
> aider\prompts.py  
> aider\repomap.py  
> aider\utils.py  
> aider\versioncheck.py  
> assets\benchmarks.svg  
> assets\css\style.scss  
> assets\figure.png  
> assets\robot-flowchart.png  
> assets\screencast.svg  
> assets\screenshot.png  
> benchmark\Dockerfile  
> benchmark\__init__.py  
> benchmark\benchmark.py  
> benchmark\docker.sh  
> benchmark\docker_build.sh  
> benchmark\plot.sh  
> benchmark\prompts.py  
> benchmark\rungrid.py  
> benchmark\test_benchmark.py  
> docs\benchmarks.md  
> docs\commands.md  
> docs\ctags.md  
> docs\faq.md  
> docs\install.md  
> examples\2048-game.md  
> examples\README.md  
> examples\add-test.md  
> examples\asciinema.md  
> examples\census.md  
> examples\chat-transcript-css.md  
> examples\complex-change.md  
> examples\css-exercises.md  
> examples\hello-world-flask.md  
> examples\hello.md  
> examples\no-color.md  
> examples\pong.md  
> examples\semantic-search-replace.md  
> examples\update-docs.md  
> pytest.ini  
> requirements.txt  
> scripts\versionbump.py  
> setup.py  
> tests\__init__.py  
> tests\test_coder.py  
> tests\test_commands.py  
> tests\test_editblock.py  
> tests\test_io.py  
> tests\test_main.py  
> tests\test_models.py  
> tests\test_repomap.py  
> tests\test_wholefile.py  
> tests\utils.py

**Comment by paul-gauthier** [comment]
Sorry, I am not able to reproduce the problem. Can you try and describe the steps I need to take more clearly? Also happy to try and work with you live if you want to ping me on discord: https://discord.gg/rsemBGUt

**Comment by paul-gauthier** [comment]
Just checking back to see if you can help me reproduce the problem you're describing?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
