### ISSUE TITLE
Uncaught TypeError in main.py line 170

### ISSUE THREAD

**Issue by ispyridis** [paul-gauthier/aider#1395]
Aider version: <module 'aider.__version__' from 'C:\\Users\\ISPYR\\anaconda3\\Lib\\site-packages\\aider\\__version__.py'>
Python version: 3.11.5
Platform: Windows-10-10.0.19045-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.45.2.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 404, in main
    launch_gui(argv)
  File "main.py", line 170, in launch_gui
    if "-dev" in __version__:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'module' is not iterable

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

You may want to read the docs on installing aider with pipx. Particularly if you are trying to use aider on replit.

https://aider.chat/docs/install/pipx.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
