### ISSUE TITLE
aider: error: unrecognized arguments: --list-models

### ISSUE THREAD

**Issue by spidy0x0** [paul-gauthier/aider#1396]
### Issue

└──╼ $aider --list-models gemini/
usage: aider [-h] [--openai-api-key OPENAI_API_KEY]
             [--anthropic-api-key ANTHROPIC_API_KEY] [--model MODEL] [--opus]
             [--sonnet] [--4] [--4o] [--mini] [--4-turbo] [--35turbo]
             [--deepseek] [--models MODEL] [--openai-api-base OPENAI_API_BASE]
             [--openai-api-type OPENAI_API_TYPE]
             [--openai-api-version OPENAI_API_VERSION]
             [--openai-api-deployment-id OPENAI_API_DEPLOYMENT_ID]
             [--openai-organization-id OPENAI_ORGANIZATION_ID]
             [--model-settings-file MODEL_SETTINGS_FILE]
             [--model-metadata-file MODEL_METADATA_FILE]
             [--verify-ssl | --no-verify-ssl] [--edit-format EDIT_FORMAT]
             [--weak-model WEAK_MODEL]
             [--show-model-warnings | --no-show-model-warnings]
             [--map-tokens MAP_TOKENS]
             [--map-refresh {auto,always,files,manual}]
             [--cache-prompts | --no-cache-prompts]
             [--cache-keepalive-pings CACHE_KEEPALIVE_PINGS]
             [--map-multiplier-no-files MAP_MULTIPLIER_NO_FILES]
             [--max-chat-history-tokens MAX_CHAT_HISTORY_TOKENS]
             [--env-file ENV_FILE] [--input-history-file INPUT_HISTORY_FILE]
             [--chat-history-file CHAT_HISTORY_FILE]
             [--restore-chat-history | --no-restore-chat-history]
             [--llm-history-file LLM_HISTORY_FILE] [--dark-mode]
             [--light-mode] [--pretty | --no-pretty] [--stream | --no-stream]
             [--user-input-color USER_INPUT_COLOR]
             [--tool-output-color TOOL_OUTPUT_COLOR]
             [--tool-error-color TOOL_ERROR_COLOR]
             [--tool-warning-color TOOL_WARNING_COLOR]
             [--assistant-output-color ASSISTANT_OUTPUT_COLOR]
             [--code-theme CODE_THEME] [--show-diffs] [--git | --no-git]
             [--gitignore | --no-gitignore] [--aiderignore AIDERIGNORE]
             [--subtree-only] [--auto-commits | --no-auto-commits]
             [--dirty-commits | --no-dirty-commits]
             [--attribute-author | --no-attribute-author]
             [--attribute-committer | --no-attribute-committer]
             [--attribute-commit-message-author | --no-attribute-commit-message-author]
             [--attribute-commit-message-committer | --no-attribute-commit-message-committer]
             [--commit] [--commit-prompt PROMPT] [--dry-run | --no-dry-run]
             [--lint] [--lint-cmd LINT_CMD] [--auto-lint | --no-auto-lint]
             [--test-cmd TEST_CMD] [--auto-test | --no-auto-test] [--test]
             [--file FILE] [--read FILE] [--vim]
             [--voice-language VOICE_LANGUAGE] [--version]
             [--just-check-update] [--check-update | --no-check-update]
             [--install-main-branch] [--upgrade] [--apply FILE] [--yes] [-v]
             [--show-repo-map] [--show-prompts] [--exit] [--message COMMAND]
             [--message-file MESSAGE_FILE] [--encoding ENCODING]
             [-c CONFIG_FILE] [--gui]
             [--suggest-shell-commands | --no-suggest-shell-commands]
             [FILE ...]
aider: error: unrecognized arguments: --list-models

### Version and model info

Aider v0.55.0
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: none
Repo-map: disabled

**Comment by fry69** [comment]
Use the deprecated `--models` instead of `--list-models` or use the main branch:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

**Comment by spidy0x0** [comment]
Thanks
