### ISSUE TITLE
use aider to make quick throwaway scripts

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#1398]
### Issue

It would be useful to be able to quickly generate simple scripts, e.g. for basic file manipulation tasks, renaming etc. Aider's scripting functionality is perfect for this.
But it's time consuming to create a new folder, cd in, git init and then start aider. And I often don't want to run aider in my current dir as the .git might relate to my main project of the time.

Is there any convenient way to use aider for quick simple tasks like this?
I am considering writing a script that creates a temp folder, git init then run aider and then delete it all after aider successfully produces a script.

### Version and model info

aider 0.55.0
sonnet 3.5

**Comment by fry69** [comment]
I do not want to diminish aider's general usefulness but for a really quick LLM task consider using either
- [llm](https://llm.datasette.io/)
- [aichat](https://github.com/sigoden/aichat)

These can be used e.g. for automatically generating commit messages without aider, see [here](https://gist.github.com/fry69/4e86172691a30cfb9fb77047026a0d61).

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can run aider with --no-git.

**Comment by lockmeister** [comment]
I appreciate your suggestions. But I want the power of aider, and the convenience of git. And I don't want to create a temp folder, git, python env each time.

So I've written a wrapper for Aider which does all this for you: https://gist.github.com/lockmeister/367bbe24c7b69e258bf3cd5cb8d13517

This makes it super easy to quickly whip up a script from any location without messing with the environment you are using. My wrapper sets up a /tmp folder, python env, git repo and then offers to delete them once you accept the script. My wrapper drops you into an aider session so you get the full power of Aider

@fry69 , I'd be interested to hear more about how you use those other tools and when you use them instead of aider.
@paul-gauthier  thanks again for making the best coding assistant I've found to date.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
