### ISSUE TITLE
Feature Request: Easier CTAGS execution on specific file extension

### ISSUE THREAD

**Issue by lightningRalf** [paul-gauthier/aider#14]
Hey there, 
So I want to become a product manager, and want to understand codebases better with the help of aider.

For this I would like to do things less manual and more automated.
Here is what I thought about - and asked GPT-4 based on your README:
```
I want to run aider with the ctags on all .py files in a different repo, how do I do this?

```
And the answer was:
```
To run Aider with ctags on all .py files in a different repo, follow these steps:

Open your terminal and navigate to the root directory of the target repository.
cd /path/to/your/repo
Install the universal ctags if you haven’t already:
# For Ubuntu/Debian-based systems
sudo apt-get install universal-ctags

# For macOS (using Homebrew)
brew install --HEAD universal-ctags/universal-ctags/universal-ctags
Generate the tags file for your repo using ctags:
ctags -R *.py
This command will recursively search for all .py files and generate a tags file in the repository root.

Run Aider with the --ctags flag and specify all .py files you want to work on:
aider --ctags file1.py file2.py ...
Replace file1.py, file2.py, etc., with the paths to the source code files you want to work on.

Now, Aider will launch using ctags for better understanding and modification of your codebase while working on specified .py files. If you don’t want to specify each individual .py file, you can use wildcards or other tools like [find](https://man7.org/linux/man-pages/man1/find.1.html) to pass all desired .py files as arguments.
```

And then I asked further - and received this:
```
You can accomplish this using the find command along with a wildcard to specify all .py files. Here’s an example of how you can do this:

Open your terminal or command prompt.
Navigate to the directory containing the .py files you want to work with.
Use the following command to pass all .py files as arguments to a script called your_script.py:
python your_script.py $(find . -name "*.py")
In this example, find . -name "*.py" will search for all .py files in the current directory and its subdirectories. The $( ... ) syntax will pass the output of the find command (i.e., the list of found .py files) as arguments
```
This works out quite nicely. BUT includes all files, also the 'hidden files' within .venv for example.
So to make it work without these folders - GPT-4 answer was the following: 
```
python3 .venv/bin/aider --ctags $(find . -name "*.py" ! -path "./. venv/*") -c .venv/bin/. aider.conf .yml
```

How about putting this inside the README?

---
So after executing the command above: 

## RESULT: I get the following:
``` 
Added generate_repo_info.py to the chat
Added main.py to the chat
Using git repo: . git
Use /help to see in-chat commands.
generate_repo_info.py main. py
>
``` 
In the [repo](https://github.com/lightningRalf/CrawlGitHub) I am trying to analyse are three .py files.
So this does exclude the "fetch_starred_repos.py" (dont know why)
## Steps I took:
1. git clone CrawlGitHub
2. cd into directory
3. python3 -m venv .venv
4. python3 source .venv/bin/activate
5. pip install git+https://github.com/paul-gauthier/aider.git
6. create new file .aider.conf.yml with openai-api-key:{mykey}
7. sudo apt-get install universal-ctags
8. ctags -R *.py
9. python3 .venv/bin/aider --ctags $(find . -name "*.py" ! -path "./. venv/*") -c .venv/bin/. aider.conf .yml
10. see result: "fetch_starred_repos.py" is missing

**Comment by paul-gauthier** [comment]
Thanks for trying aider! I'm not sure I fully understand what you are trying to do, but let me offer some suggestions.

The README for aider explains how to enable ctags. You just install the `universal ctags` tool and then run `aider --ctags`. That's all you need to do. It will automatically use ctags to scan **every file** in your git repository.

I gave this a try against the repo you mentioned:

> $ git clone https://github.com/lightningRalf/CrawlGitHub.git  
> $ cd CrawlGitHub  
> $ aider  --ctags  
> Using git repo: .git  

#### eplain the general structure of this project  

The project consists of three files:

1. `.gitignore`: This file is used to specify files and directories that should be ignored by Git when tracking changes in the repository.

2. `fetch_starred_repos.py`: This script fetches the starred repositories of a GitHub user. It contains several variables such as `api_url`, `github_pat`, `headers`, `json_data`, `page`, `response`, `starred_repos`, and `working_directory`. The script likely makes API calls to GitHub to retrieve the starred repositories and stores the information in the `starred_repos` variable.

3. `generate_repo_info.py`: This script generates information about a specific repository. It contains a function `get_readme_url(github_url, default_branch)` and several variables such as `api_url`, `contributors`, `contributors_data`, `contributors_response`, `contributors_url`, `default_branch`, `existing_files`, `existing_numbers`, `forks`, `github_pat`, `headers`, `latest_release`, `markdown_file`, `next_number`, `readme_url`, `releases_data`, `releases_response`, `releases_url`, `repo_data`, `repo_description`, `repo_name`, `response`, `stars`, `urls`, `watching`, and `working_directory`. The script likely makes API calls to GitHub to retrieve various information about the repository, such as contributors, forks, stars, and watchers, and generates a markdown file with this information.

4. `main.py`: This file is not described in the summaries provided. It is likely the main entry point of the project, which calls the functions from the other two scripts to fetch starred repositories and generate repository information.

The general structure of the project is to fetch information about starred repositories and generate detailed information about each repository, possibly for documentation or reporting purposes.

**Comment by lightningRalf** [comment]
Well, it seems I could not trust GPT4 to explain it to me well enough.

Thanks for taking the time.

Didnt know that aider --ctags takes the content of the .git files

## One question remains:
is there an easy way to exclude folders? For example if I dont want GPT-4 to go through all the documentation? And just ask questions to the code?

**Comment by paul-gauthier** [comment]
One thing that may not be obvious is that GPT only sees a high level "map" of the repo until you explicitly give it permission to load the content of specific files. The map is built using ctags, and just shows GPT the functions and variables which are defined in each file in the git repo.

But aider doesn't sent GPT the *full content* of any* files, until you explicitly "add them to the chat". You can add files by naming them on the command line or by adding them using `/add` in the chat.

So unless you explicitly add the doc files to the chat, GPT will only see some high level info about them in the repo map.

**Comment by lightningRalf** [comment]
Thank you for the clarification!
