### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by LaBiXiaoChen** [paul-gauthier/aider#143]
> ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 2.8.3. See: https:github.com/urllib3/urllib3/issues/2168

**I don't know why this error occurred, and I don't know what to do next**

**Can the developer help me?**

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

This looks like there is a problem in your python environment. What version of python are you running? How did you install aider?

**Comment by paul-gauthier** [comment]
Also, feel free to join us on the Discord where we may be able to help debug your issue.

https://discord.com/channels/1131200896827654144/1133060264825208942

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by LaBiXiaoChen** [comment]
Do you have a Telegram group? I used to use Telegram.
