### ISSUE TITLE
Timeout while loading pages (/web command)

### ISSUE THREAD

**Issue by gxgl** [paul-gauthier/aider#1430]
### Issue

Hello,

First of all: Nice work! Thank you for this!

I am using Aider for some months now and I didn't have any problem, but today I have updated to v0.55.0 and I have started to get this kind of messages:

Scraping https://developer.atlassian.com/server/jira/platform/administration-ui-locations/...
Timeout while loading 
https://developer.atlassian.com/server/jira/platform/administration-ui-locations/

I am not sure if is indeed a timeout or a false positive because, somehow, some data from the pages arrives.

A complete mister!

### Version and model info

Aider: v0.55.0
Using: GPT 4o (--4o)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The timeout just means that the page didn't go idle in the 5 seconds aider will wait. But it sounds like the content you wanted was loaded and available, so that's good.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by gxgl** [comment]
Hello Paul,

sure. 
Thank you for the info and sorry for this late reply.

Too busy on last days...

Thanks a lot,
George
