### ISSUE TITLE
[Deepseek] --yes | Ask for creation of new file 

### ISSUE THREAD

**Issue by quocdat-le-insacvl** [paul-gauthier/aider#1431]
### Issue

I really enjoy Aider AI. Thank you very much!

I'm using DeepSeek with the --yes option. The model tried to ask for the file (which doesn't exist), but after that, the conversation stopped. I'm not sure whether the bug is in the --yes option or if the model doesn't make a good request.

![image](https://github.com/user-attachments/assets/ff53fda1-0c34-4de0-a3ce-10918b2805e5)

### Version and model info

Aider v0.55.0
Model: deepseek/deepseek-coder with diff edit format, prompt cache, infinite output
Git repo: .git with 46 files
Repo-map: using 1024 tokens, auto refresh

**Comment by fry69** [comment]
See this tip for creating new files -> https://aider.chat/docs/usage/tips.html#creating-new-files

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Unfortunately Deepseek isn't always smart enough to try and create a new file.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by quocdat-le-insacvl** [comment]
@paul-gauthier I checked but is there any option to disable crawling suggestion ? I'm using `--yes`
![image](https://github.com/user-attachments/assets/94b07140-ab9e-469f-968b-3ee9c52b35e5)

Thank you very for your support !

**Comment by paul-gauthier** [comment]
No, if you've used `--yes` that will answer yes to everything.
