### ISSUE TITLE
Feature request: Callback functionality

### ISSUE THREAD

**Issue by maledorak** [paul-gauthier/aider#1438]
### Feature request

The aider could invoke a callback script provided by the user for every LLM response.

Thanks to that, we can run many helpful automation like notifications on discord/slack/email, or even chaining aider based on previous generation. 

It can be especially useful when aider will run on headless mode like CI/CD or vps

Proposed flag
```
aider --calback "python callback.py"
aider --calback "./callback.sh"
```

For debugging purposes to run callback without calling LLM we can use:
```
aider --callback "python callback.py" --callback-debug
```

**Comment by maledorak** [comment]
I've already created my proposition for this feature. - #1439 

Code and unit tests are done. The only documentation is left.

You can already test this callback feature on my branch using
`python -m aider --callback 'scripts/callbacks/example_callback.py'`
or 
`python -m aider --callback 'scripts/callbacks/example_callback.py' --callback-debug`
callback debug will run callback right away from `aider/main.py` without running base coder

**Comment by paul-gauthier** [comment]
As I mentioned on discord, I'm not sure I understand the use case for this versus using the existing lint and test hooks?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
