### ISSUE TITLE
Uncaught TypeError in core.pyx line 14

### ISSUE THREAD

**Issue by f0-x** [paul-gauthier/aider#1452]
Aider version: 0.55.0
Python version: 3.12.5
Platform: Linux-6.10.8-arch1-1-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: No
OS: Linux 6.10.8-arch1-1 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 694, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1194, in send_message
    lint_errors = self.lint_edited(edited)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1288, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 93, in lint
    lintres = cmd(fname, rel_fname, code)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 110, in py_lint
    basic_res = basic_lint(rel_fname, code)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 205, in basic_lint
    parser = get_parser(lang)
             ^^^^^^^^^^^^^^^^
  File "core.pyx", line 19, in tree_sitter_languages.core.get_parser
  File "core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How did you install aider? What environment are you using?

It looks like you don't have the correct set of dependencies installed.

You may want to read the docs on installing aider with pipx. Particularly if you are trying to use aider on replit.

https://aider.chat/docs/install/pipx.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by f0-x** [comment]
Hi @paul-gauthier, thank you for taking time to reply to the issue. I installed `aider-chat` on my Arch Linux laptop using this [AUR Package](https://aur.archlinux.org/packages/aider-chat?all_deps=1#pkgdeps).

![image](https://github.com/user-attachments/assets/c948b70a-96ff-4d7a-9ef1-0c76ed3dba80)

Could you please point me which specific packages and their versions is required by aider-chat to function properly, then I could downgrade to appropriate versions ?

**Comment by paul-gauthier** [comment]
See #610. 

Like all python packages, aider expects its dependencies to be installed as described in requirements.txt. 

The AUR packaged version of aider does not seem to do this. 

Can you just install aider via pip or pipx?

**Comment by paul-gauthier** [comment]
https://github.com/paul-gauthier/aider/blob/main/requirements.txt

**Comment by paul-gauthier** [comment]
This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
