### ISSUE TITLE
Use of RepoPack?

### ISSUE THREAD

**Issue by aronchick** [paul-gauthier/aider#1460]
### Issue

What do you think about use of RepoPack (or similar) to upload the entire codebase to an artifact, as an artifact? We'll run into caching issues, of course, but could be really interesting.

https://github.com/yamadashy/repopack

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/faq.html#how-can-i-add-all-the-files-to-the-chat

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
