### ISSUE TITLE
Yi coder cycles

### ISSUE THREAD

**Issue by kv-gits** [paul-gauthier/aider#1462]
### Issue

New model yi_coder has unusual bos eos tokens (<|startoftext|> <|endoftext|> ), so it cant stop generating and moves to inifinity cycle.
Would be nice to have an option to change this tokens.

### Version and model info

Aider 0.55.0, [Yi-Coder-9B-Chat](https://huggingface.co/01-ai/Yi-Coder-9B-Chat)

**Comment by fry69** [comment]
I have given this a shot, but I have not tested if it actually works. Please try and report ->
```
pip install git+https://github.com/fry69/aider.git@eos-bos
```
The new command line arguments are `--bos-token <token>` and `--eos-token <token>`.

**Comment by fry69** [comment]
@kv-gits

Can you please try again? I fixed my branch to actually send the BOS/EOS tokens to LiteLLM, it involved a bit more than I initially thought. Here is how it now looks in the Ollama debug log:

--- snip ---
time=2024-09-11T11:12:24.672+02:00 level=DEBUG source=routes.go:211 msg="generate request" prompt="<|im_start|>user\n\n<|startoftext|>### System:\nAct as an expert code analyst.\nAnswer questions about the supplied code.\n\nAlways reply to the user in the same language they are using.\n<|endoftext|><|startoftext|>### User:\nI am not sharing the full contents of any files with you yet.<|endoftext|><|startoftext|>### Assistant:\nOk.<|endoftext|><|startoftext|>### User:\nHello, this is a test.<|endoftext|>\n<|im_end|>\n<|im_start|>assistant\n" images=[]
--- snap --

**Comment by fry69** [comment]
As I am digging deeper into this topic, I think that BOS/EOS tokens should best be left alone. It seems to be the responsibility of the inference software to apply those correctly, and Ollama has access to the `special_tokens_map.json` file for Yi Coder to read from.

If I understand this correctly the client (aider+LiteLLM in this case) just has to supply the correct format (ChatML) to Ollama and the inference software (Ollama/llama.cpp) has to translate this to the format for the actual model (token wise). But please correct me if I am wrong.

**Comment by kv-gits** [comment]
@fry69 Most probably you right. I use llama.cpp, not ollama. Also aider-benchmarks work fine with yi-coder. I will try ollama and give feedback.

**Comment by fry69** [comment]
Maybe also relevant -> https://huggingface.co/01-ai/Yi-Coder-9B-Chat/discussions/4

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
