### ISSUE TITLE
Module to use Anthropic's Claude

### ISSUE THREAD

**Issue by Bakobiibizo** [paul-gauthier/aider#147]
Hello,

After using your tool I dove into the code base to figure out how you structured the cognitive architecture. My only issue was running out of context window. I have a key for Anthropic's API so I went ahead and [built a module that lets me run Claude.](https://github.com/Bakobiibizo/aider/tree/dev) Its not working fully yet since there are a lot of interactions I am unaware of. I was hoping you'd be willing to check it out. I worked on it for too long today and I cant see my mistakes from exhaustion lol. 

I used a fairly inelegant approach and just highjacked the base coder after I confirmed it was Claude. If you want me to refactor it into a more civilized way before I make a pull that would be fine. Mostly I wanted to get it running on my side.

let me know what you think.

**Comment by petebytes** [comment]
Aider is an amazing project - freaking love it - but I too run into context length issues often.
Would love to see Anthropic's API integrated, although I am still waiting for access.

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc
