### ISSUE TITLE
circle error in area of compatibility issue that dont seem to get sorted even though i have tried lots 

### ISSUE THREAD

**Issue by DMTarmey** [paul-gauthier/aider#1489]
### Issue

(myenv) dmtarmey  …/aider-chat   main !?⇡   v22.8.0  13:49  pytest 
=========================== test session starts ===========================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/dmtarmey/Projects/aider-chat
configfile: pytest.ini
plugins: anyio-4.4.0
collected 3 items / 8 errors                                              

================================= ERRORS ==================================
__________________ ERROR collecting tests/test_coder.py ___________________
ImportError while importing test module '/home/dmtarmey/Projects/aider-chat/tests/test_coder.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_coder.py:10: in <module>
    from aider.coders import Coder
aider/coders/__init__.py:1: in <module>
    from .base_coder import Coder
aider/coders/base_coder.py:14: in <module>
    from jsonschema import Draft7Validator
E   ModuleNotFoundError: No module named 'jsonschema'
_________________ ERROR collecting tests/test_commands.py _________________
ImportError while importing test module '/home/dmtarmey/Projects/aider-chat/tests/test_commands.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_commands.py:13: in <module>
    from aider.coders import Coder
aider/coders/__init__.py:1: in <module>
    from .base_coder import Coder
aider/coders/base_coder.py:14: in <module>
    from jsonschema import Draft7Validator
E   ModuleNotFoundError: No module named 'jsonschema'
________________ ERROR collecting tests/test_editblock.py _________________
ImportError while importing test module '/home/dmtarmey/Projects/aider-chat/tests/test_editblock.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_editblock.py:9: in <module>
    from aider.coders import Coder
aider/coders/__init__.py:1: in <module>
    from .base_coder import Coder
aider/coders/base_coder.py:14: in <module>
    from jsonschema import Draft7Validator
E   ModuleNotFoundError: No module named 'jsonschema'
___________________ ERROR collecting tests/test_main.py ___________________
ImportError while importing test module '/home/dmtarmey/Projects/aider-chat/tests/test_main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_main.py:15: in <module>
    from aider.main import check_gitignore, main, setup_git
aider/main.py:5: in <module>
    import configargparse
E   ModuleNotFoundError: No module named 'configargparse'
___________________ ERROR collecting tests/test_repo.py ___________________
ImportError while importing test module '/home/dmtarmey/Projects/aider-chat/tests/test_repo.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_repo.py:11: in <module>
    from aider.repo import GitRepo
aider/repo.py:7: in <module>
    from aider.sendchat import simple_send_with_retries
aider/sendchat.py:7: in <module>
    from openai.error import (
E   ModuleNotFoundError: No module named 'openai.error'
_________________ ERROR collecting tests/test_repomap.py __________________
ImportError while importing test module '/home/dmtarmey/Projects/aider-chat/tests/test_repomap.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_repomap.py:9: in <module>
    from aider.repomap import RepoMap
aider/repomap.py:11: in <module>
    import networkx as nx
E   ModuleNotFoundError: No module named 'networkx'
_________________ ERROR collecting tests/test_sendchat.py _________________
ImportError while importing test module '/home/dmtarmey/Projects/aider-chat/tests/test_sendchat.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_sendchat.py:7: in <module>
    from aider.sendchat import send_with_retries
aider/sendchat.py:7: in <module>
    from openai.error import (
E   ModuleNotFoundError: No module named 'openai.error'
________________ ERROR collecting tests/test_wholefile.py _________________
ImportError while importing test module '/home/dmtarmey/Projects/aider-chat/tests/test_wholefile.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_wholefile.py:9: in <module>
    from aider.coders import Coder
aider/coders/__init__.py:1: in <module>
    from .base_coder import Coder
aider/coders/base_coder.py:14: in <module>
    from jsonschema import Draft7Validator
E   ModuleNotFoundError: No module named 'jsonschema'
========================= short test summary info =========================
ERROR tests/test_coder.py
ERROR tests/test_commands.py
ERROR tests/test_editblock.py
ERROR tests/test_main.py
ERROR tests/test_repo.py
ERROR tests/test_repomap.py
ERROR tests/test_sendchat.py
ERROR tests/test_wholefile.py
!!!!!!!!!!!!!!!!! Interrupted: 8 errors during collection !!!!!!!!!!!!!!!!!
=========================== 8 errors in 16.20s ============================

(myenv) dmtarmey  …/aider-chat   main !?⇡   v22.8.0  13:49  

### Version and model info

lattest of of today 11 09 2024

**Comment by fry69** [comment]
Have you read -> https://github.com/paul-gauthier/aider/blob/main/CONTRIBUTING.md and set up your environment correctly?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
