### ISSUE TITLE
Uncaught TypeError in repo.py line 299

### ISSUE THREAD

**Issue by petrusali** [paul-gauthier/aider#1497]
Aider version: 0.56.0
Python version: 3.12.5
Platform: macOS-14.6.1-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.23.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 778, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1202, in send_message
    saved_message = self.auto_commit(edited)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1885, in auto_commit
    res = self.repo.commit(fnames=edited, context=context, aider_edits=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 95, in commit
    diffs = self.get_diffs(fnames)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 222, in get_diffs
    if not self.path_in_repo(fname):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 359, in path_in_repo
    return self.normalize_path(path) in tracked_files
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 299, in normalize_path
    path = str(Path(PurePosixPath((Path(self.root) / path).relative_to(self.root))))
                                   ~~~~~~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by MESTIKAMAZAYA** [comment]
> Thanks for trying aider and filing this issue.
> 
> The fix is available in the main branch. You can get it by installing the latest version from github:
> 
> ```
> aider --install-main-branch
> 
> # or...
> 
> python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
> ```
> 
> If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

I've updated to 0.57.1 now and hoping the problem fixed. Thank you.
