### ISSUE TITLE
Feature request: limit chat history

### ISSUE THREAD

**Issue by BrianAndersen78** [paul-gauthier/aider#150]
Thanks for great program!

Try Aider with Streamlit and it will make you cry 😄  
Building Admin dashboards is 50 times faster then manually 👯‍♀️

But if you have the time, it would be amazing if we could limit the chat history sent to GPT-4. 
It looks like tokens used by the chat history, sums up to about 4/5 of the actual cost of building with Aider. That is stupid :)

I only really need 2-3 previous chats to be included in request...  
An adjustable limit would be much appreciated 😄 ( sorry I don't have the time for a PR at the moment )

Paul - You are the best!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

There's a PR #144 pending that should help with this. I hope to merge it soon.

**Comment by paul-gauthier** [comment]
The chat history PR merged and is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by BrianAndersen78** [comment]
Thx a lot... I'll install and get beck to you in a day or two, when i have testet...

**Comment by BrianAndersen78** [comment]
Thanks for the update, and sorry for the late reply. I have testet for 5-10 hours now, wanted to be sure of any findings...

It seems that the chat history is still building up, and it still gets very large. I still have situations where it ends up crashing, because it's reached the limit. 

It's not the crash it self that matters, but the chat history seems to often confuse GPT-4 when it gets to large. I have multiple times tried situations where GPT-4 makes wrong replys, and if i manually clears the chat history, it successful makes the correct changes.

Also the chat history still makes up about 4/5 of the total cost of GPT-4. When spending $10 - 20 pr day, this is not a small amount ( still worth it though :) )

**Comment by paul-gauthier** [comment]
Can you confirm which version of aider you are running? It announces the version when you launch it.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open if you are still having a problem.
