### ISSUE TITLE
Uncaught TypeError in main.py line 172

### ISSUE THREAD

**Issue by wxfan** [paul-gauthier/aider#1502]
Aider version: <module 'aider.__version__' from 'D:\\Services\\.pyenv\\pyenv-win\\versions\\3.10.9\\lib\\site-packages\\aider\\__version__.py'>
Python version: 3.10.9
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 4, in <module>
    main()
  File "main.py", line 422, in main
    launch_gui(argv)
  File "main.py", line 172, in launch_gui
    if "-dev" in __version__:
TypeError: argument of type 'module' is not iterable

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Looks like aider has trouble getting its version information from `version.py` for some reason, which produces this crash:
```
Aider version: <module 'aider.version' from 'D:\Services\.pyenv\pyenv-win\versions\3.10.9\lib\site-packages\aider\version.py'>
```
This looks very odd. Can you please try a fresh install?

**Comment by wxfan** [comment]
Thanks for your reply, I just uninstall and install the aider-chat again, It works correctly.

Igot the above error when I launched the browser version of aider, I used the following command:
python -m aider --browser.

**Comment by paul-gauthier** [comment]
This should be fixed in the latest version of aider, please upgrade with:

```
aider --upgrade
```
