### ISSUE TITLE
Estimate OpenAI Costs

### ISSUE THREAD

**Issue by dgallo-igloo** [paul-gauthier/aider#151]
Loving aider so far. Is there a way to get an idea of how much using aider in a project is costing with GPT?

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

You can use `/tokens` to see how many tokens each request is going to send. If you run aider with `--no-stream` it will print out actual costs in dollars, but you won't see the live responses streaming back from GPT. Unfortunately, OpenAI doesn't provide definite token counts when using streaming.

There's more info on the in-chat commands here:

https://aider.chat/docs/commands.html

**Comment by dgallo-igloo** [comment]
I am getting the same output whether I use the `--no-stream` option or not.
```
Approximate context window usage, in tokens:

     438 system messages 
     151 repository map  use --map-tokens to resize
   2,423 readme.md       use /drop to drop from chat
========
   3,012 tokens total
   5,180 tokens remaining in context window
   8,192 tokens max context window size
```
I'm not 100% sure how to interpret those token counts into $.  I could multiply 3,012 by the $0.03/1K price for input tokens on GPT-4 and that would tell me roughly how much it will cost to run the next query in `aider`.

This would not be the total cost though correct?  That would be the cost only for sending the added files and current chat history to OpenAI I assume.  Then there would be extra costs for
* the actual prompt I run in `aider`
* all of the output from GPT for the above prompt.

Am I on the right track here?

**Comment by paul-gauthier** [comment]
```
$ aider --no-stream -3
Aider v0.10.2-dev
Model: gpt-3.5-turbo-16k
Git repo: .git
Repo-map: disabled
Use /help to see in-chat commands, run with --help to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────
> hi

Hello! How can I assist you today?
265 prompt tokens, 9 completion tokens, $0.000831 cost
```

See the final line, that prints after each message comes back from GPT.

**Comment by dgallo-igloo** [comment]
Ah, I see.  I was thinking it affected the output of `/token`.  This is very helpful!  Thank you

**Comment by dgallo-igloo** [comment]
I thought of a follow up question. Is the cost output stored anywhere in a format that I could parse out and sum up the costs for all of the history in a project?

**Comment by paul-gauthier** [comment]
I made a couple of improvements related to costs. They aren't a full solution to your needs, but they're steps in the right direction.

The `/tokens` command now includes dollar costs:

```
> /tokens

Approximate context window usage, in tokens:

$ 0.01      438 system messages
$ 0.03    1,052 repository map  use --map-tokens to resize
$ 0.07    2,209 aider/io.py     use /drop to drop from chat
================
$ 0.11    3,699 tokens total
          4,493 tokens remaining in context window
          8,192 tokens max context window size
```

And the cost info that is printed when `--no-stream` is enable is included in `.aider.chat.history.md`.

```
$ tail .aider.chat.history.md
> Repo-map: disabled
> Use /help to see in-chat commands, run with --help to see cmd line args

#### hi
> 265 prompt tokens, 9 completion tokens, $0.000831 cost

Hello! How can I assist you today?
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
