### ISSUE TITLE
New Modal from OpenAI openai-o1-preview and mini Is out 

### ISSUE THREAD

**Issue by Yona544** [paul-gauthier/aider#1511]
### Issue

https://openai.com/index/introducing-openai-o1-preview/

**Comment by lucasbmiguel** [comment]
Just opened a PR for introducing basic support ^

**Comment by paul-gauthier** [comment]
Please see the blog post, which explains how to use them with aider:

https://aider.chat/2024/09/12/o1.html

**Comment by lucasbmiguel** [comment]
Oh, I missed that. Got tricked because they were not listed in the OPENAI_MODELS var within models.py. Just saw the code now, thanks.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
