### ISSUE TITLE
Aider browser support for o1-preview / o1-mini models

### ISSUE THREAD

**Issue by JereKaplas** [paul-gauthier/aider#1516]
### Issue

aider --model o1-preview works with something like /ask <question>

But aider --model o1-preview --browser sends requests with stream: true, which is not supported with the o1 models:

BadRequestError: litellm.BadRequestError: OpenAIException - Error code: 400 - {'error': {'message': "Unsupported value: 'stream' does not support true with this model. Only the default (false) value is
supported.", 'type': 'invalid_request_error', 'param': 'stream', 'code': 'unsupported_value'}}

### Version and model info

aider 0.56.1.dev111+ge6037140
aider --model o1-preview --browser

**Comment by JereKaplas** [comment]
Neither stream: false in aider.conf.yml or `aider --browser --model o1-preview --no-stream` fixes this.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Currently o1 is only supported in the development version of aider:

```
aider --install-main-branch
```
