### ISSUE TITLE
Uncaught IsADirectoryError in pathlib.py line 1117

### ISSUE THREAD

**Issue by artimath** [paul-gauthier/aider#1518]
Aider version: 0.56.0
Python version: 3.10.1
Platform: macOS-14.5-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 23.5.0 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 735, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 778, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1213, in send_message
    lint_errors = self.lint_edited(edited)
  File "base_coder.py", line 1307, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
  File "linter.py", line 86, in lint
    code = Path(fname).read_text(encoding=self.encoding, errors="replace")
  File "pathlib.py", line 1132, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
IsADirectoryError: [Errno 21] Is a directory: '/Users/ryanhunter/new_era/veils-hub/src/features/universalInbox/FEATURE+USECASES.md'

```

**Comment by fry69** [comment]
Thank you for filing this issue.

The error seems to come from the OS and it tries to tell you that `FEATURE+USECASES.md` file is not a file but a directory. Can you confirm that please? Or is something else going on here?

**Comment by paul-gauthier** [comment]
The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
