### ISSUE TITLE
/undo not working without --auto-commits == true

### ISSUE THREAD

**Issue by quocdat-le-insacvl** [paul-gauthier/aider#1528]
### Issue

I understand that `/undo` performs `git reset HEAD^`, but returning to the previous chat status would be more useful.

This is particularly helpful in buggy situations when the code isn't working well enough for a commit.

Moreover, `aider` can make multiple commits in a single run, which may complicate returning to a previous status (e.g., to refine the prompt, add more details to the prompt).

### Version and model info

Aider v0.56.0
Main model: claude-3-5-sonnet-20240620 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 63 files
Repo-map: using 1024 tokens, auto refresh

**Comment by quocdat-le-insacvl** [comment]
![image](https://github.com/user-attachments/assets/2fe67bdd-73fb-41f4-bfef-3ae36de4ee6d)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider uses auto-commits to implement /undo, so you need to leave them on if you want the safety of undo.

You can always squash the many aider commits afterwards if you want a tidy git history.
