### ISSUE TITLE
Is there a way to exclude the .env file from cTag?

### ISSUE THREAD

**Issue by GitIgnoreMaybe** [paul-gauthier/aider#153]
Hey, maybe this is already done, but I couldn't find anything related to that. What I actually want: I don't want the .env file being mapped and send to OpenAI.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

If the `.env` is checked into git, then it will be part of the ctags repo map. Did you intend to commit it to git?

**Comment by GitIgnoreMaybe** [comment]
This actually answers the question already. So it respects the gitignore. Thanks for the clarification 🙏
