### ISSUE TITLE
ZeroDivisionError in PageRank calculation due to non-existent node in personalization vector #1535

### ISSUE THREAD

**Issue by kbagi** [paul-gauthier/aider#1536]
### Issue

Issue
The personalization vector includes a node (e.g., 'README.md') that doesn't exist in the graph. This happens when a user specifies a file with the --read option that isn't referenced from other places in the codebase. The PageRank algorithm then attempts to allocate all probability mass to this non-existent node, resulting in a division by zero.

Steps to reproduce:

Use the --read option with a file that isn't referenced from other places in the codebase (e.g., --read README.md)
Run the PageRank calculation on the resulting graph

The above results in an empty repo map.

### Version and model info

Version and model info
Aider v0.56.1.dev111+ge6037140
Main model: claude-3-5-sonnet-20240620 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 208 files
Repo-map: using 1024 tokens, auto refresh

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by karol-excelpoint** [comment]
Great! My test are passing - thanks @paul-gauthier :)

**Comment by kbagi** [comment]
Great! My test are passing - thanks @paul-gauthier  :)

**Comment by pootow** [comment]
why not just remove the file in personalization? @paul-gauthier 

```python
        # remove personalization for files that not in the graph
        personalization = {k: v for k, v in personalization.items() if k in G.nodes}
        if personalization:
            pers_args = dict(personalization=personalization, dangling=personalization)
        else:
            pers_args = dict()
```
