### ISSUE TITLE
The Join Discord link on the website doesn't work

### ISSUE THREAD

**Issue by GitIgnoreMaybe** [paul-gauthier/aider#154]
https://discord.com/invite/SqzfE6bw

![SCR-20230726-sd3](https://github.com/paul-gauthier/aider/assets/37028024/17f87420-920d-4678-bc68-fad6b7b99a92)
![SCR-20230726-sdi](https://github.com/paul-gauthier/aider/assets/37028024/79f21245-9cb4-4b43-a03d-85269a35ac94)

**Comment by paul-gauthier** [comment]
Thanks for the heads up. I fixed it.
