### ISSUE TITLE
Asking aider to split up code leads to "your existing code here"

### ISSUE THREAD

**Issue by cranyy** [paul-gauthier/aider#155]
If you ask aider to split up a file into smaller files, it will almost always create a new file without actually adding the function inside, but just writing the imports, a function then -  "your existing code here". 

To recreate just give it a 2000-3000 token file, and tell it to split the file into helper files, it will almost certainly write some version of "your existing code" after adding the imports into the new file. Even if you reprompt and try to explain it keeps on doing it.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

This is just unfortunately a limitation of the GPT models. Sometimes they get confused and stop following instructions. GPT-3.5 especially. Which model are you using?

I did recently add stronger prompting for GPT-3.5 to not elide code like this:

https://github.com/paul-gauthier/aider/commit/fcdd640a0970e4216057fa8fb8433c7e2271ca05

This is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
