### ISSUE TITLE
Add Knowledge / Guidelines for aider

### ISSUE THREAD

**Issue by Palkers76** [paul-gauthier/aider#1552]
### Issue

I want to add some additional guidelines to aider, so it will understand some specific code syntax, methods based on local documention in md or pdf.
for instance I'm using d2lang for diagramming, unfortunatly openai or other models do not understand how to use it, they usualy knows plantuml or marmaid.
I tried adding guideline to docs/d2lang.md in repo but still aider makes mistakes
I also used /add but not better.
is it possible that my guidline is too long?

**Comment by Palkers76** [comment]
found option /read

**Comment by turian** [comment]
@Palkers76 So /read is like knowledge and prompts used in every query?
