### ISSUE TITLE
REQ: A live stream of Paul using aider so we can shoulder surf and observe workflow and best practices

### ISSUE THREAD

**Issue by 5ocworkshop** [paul-gauthier/aider#1568]
### Issue

Paul, I wanted to ask if you would consider the idea of doing a live stream of some of your update work on aider.  Nothing that needs to be scripted, just something stream of consciousness as you select and resolve issues or add enhancements using aider.

It could be really helpful to see and hear how you decide on what files to include or remove from the chat, when you clear the chat, how you build your prompts and how you iterate through bugs.  I always find it fascinating to "shoulder surf" with experts and invariably pick up things the presenter intended and also catch some "wait a second, how/why did he just do that?" things that are beneficial as well.

For example, understanding your thinking on when the right time to clear the chat history is when iterating through a multi-faceted update or enhancement workflow would be really useful.

### Version and model info

Aider v0.56.0
Main model: claude-3-5-sonnet-20240620 with diff edit format, prompt cache, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 6 files
Repo-map: using 1024 tokens, files refresh
VSCode terminal detected, pretty output has been disabled.

**Comment by paul-gauthier** [comment]
Thanks for your interest in aider. Not sure I'm set up to live stream my coding though.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
