### ISSUE TITLE
O1-Preview Error

### ISSUE THREAD

**Issue by wsalem117** [paul-gauthier/aider#1581]
Please find that when I run o1 preview I get the following error. 

waelsalem@192 erp-v2-1 % aider --model o1-preview
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.56.0
Model: o1-preview with whole edit format
Git repo: .git with 181 files
Repo-map: disabled
VSCode terminal detected, pretty output has been disabled.
Use /help <question> for help, run "aider --help" to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> hi                                                                                                                                                                        

BadRequestError: litellm.BadRequestError: OpenAIException - Error code: 400 - {'error': {'message': "Unsupported value: 'messages[0].role' does not support 'system' with 
this model.", 'type': 'invalid_request_error', 'param': 'messages[0].role', 'code': 'unsupported_value'}}

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  

I tested the same model through API and also on claude dev and both are working as expected with the same api key. I also tested aider with 4o model and is working fine as expected. 

can you please let me know what am I doing incorrectly here? 

Thanks in advance.
WS

**Comment by wsalem117** [comment]
The fix in ticket 1521 works for me. please close this ticket. thanks again.

**Comment by fry69** [comment]
> please close this ticket.

You should have the option to close this issue yourself.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
