### ISSUE TITLE
Stuck on initial repo scan

### ISSUE THREAD

**Issue by danloomer** [paul-gauthier/aider#1587]
### Issue

I am having trouble running aider on a very large repo. 

It gets stuck on the initial repo scan. I've tried deleting the symbol cache and `.aider` files in the project directory and trying again but no luck.

Not sure if there's some file that it gets stuck on that could be ignored (maybe the code can detect these scenarios and skip certain files or warn about them though?).

Python process is stuck at 100% CPU utilization and the file being checked does not change.

### Version and model info

```
Aider v0.56.0
Main model: openai/anthropic:claude-3-5-sonnet with diff edit format
Weak model: openai/anthropic:claude-3-haiku
Git repo: .git with 165,715 files
Warning: For large repos, consider using --subtree-only and .aiderignore
See: https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo
Repo-map: using 1024 tokens, files refresh
Use /help <question> for help, run "aider --help" to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /ask hey whats up?

Initial repo scan can be slow in larger repos, but only happens once.
Scanning repo:  18%|████████████████████████████▌                                                                                                                                   | 29586/165715 [04:41<02:51, 791.50it/s]
```

**Comment by fry69** [comment]
Thank you for filing this issue.

This document may be helpful ->  https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo

**Comment by danloomer** [comment]
Thanks! I did read that entry in the FAQ, and I tried the `--subtree-only` flag. It's also nicely linked in the command output since it detects the repo size.

The `--subtree-only` doesn't seem to help since it still tries to build a tag cache for the full repo though.

The advice around `.aiderignore` might be good, but I have no way to know what I should be ignoring.. It kind of feels like the scanning process is getting stuck on some weird files that cause it to hang, but I don't have insight into what those files may be.

**Comment by fry69** [comment]
> The advice around `.aiderignore` might be good, but I have no way to know what I should be ignoring.

With a 160k files repo I'd ignore everything and unignore the folder/package you are working on, like this ->
```gitignore
*
!folder
!folder/**
```

**Comment by danloomer** [comment]
Thanks I'll give that a shot! 

I can achieve the ignore file updates easily enough with some scripting, but might be cool to have a way to tell aider to generate the repo map based on the subtree, or to specify ignore files/folders as a command line flag. I guess repos this big are quite an outlier though so maybe a user side solution is good enough.

**Comment by danloomer** [comment]
Before resorting to the ignore file idea, I tried letting the command run in the background for about an hour, even though it seemed stuck.

It does eventually seem to get past the files it's stuck on. 

I'm up to 93% scanned now.. Maybe there's nothing that's worth looking into, but it does seem like some sort of skip or timeout, or warning about files that it gets stuck on could be useful.

If it completes the scan I might try using it like that for a bit and see how well it performs (particularly when I need to change branches or when I pull in new changes).

**Comment by fry69** [comment]
This giant tag cache / repo map will probably as useful as searching in GitHub always against all repositories.

**Comment by danloomer** [comment]
You're probably right, and it seems like it hangs forever on the "Updating repo map" step and eventually failing out.

I just tried the ignore approach and it works! 👍 

Not sure if we want to keep this issue open to add more safety around this logic to either timeout or warn the user of why it's stuck, but otherwise I'm satisfied from my end.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by hedges333** [comment]
It seems like if I run it in a directory with no repo map, and decline to create one, that it shouldn't try to scan all the files, but should only work with the files that I give it.

For instance, if I run `aider` in / to analyze some system config files, and add those files manually, why would I want it to scan my entire file tree?
