### ISSUE TITLE
Uncaught AttributeError in sendchat.py line 30

### ISSUE THREAD

**Issue by hammerandtongs** [paul-gauthier/aider#1623]
Aider version: 0.56.0
Python version: 3.12.5
Platform: Linux-6.10.6-amd64-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.10.6-amd64 (64bit)
Git version: git version 2.45.2

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 698, in main
    return 1
  File "base_coder.py", line 735, in run
    return self.io.get_input(
                ^^^^^^^^^^^^^^
  File "base_coder.py", line 772, in run_one
    self.io.tool_warning(f"Only {self.max_reflections} reflections allowed, stopping.")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 761, in preproc_user_input
    else:
          
  File "commands.py", line 221, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "commands.py", line 196, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "commands.py", line 235, in cmd_commit
    self.raw_cmd_commit(args)
  File "commands.py", line 249, in raw_cmd_commit
    self.coder.repo.commit(message=commit_message)
  File "repo.py", line 102, in commit
    commit_message = self.get_commit_message(diffs, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 187, in get_commit_message
    commit_message = simple_send_with_retries(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 38, in wrapper
    retry_exceptions(),
    ^^^^^^^^^^^^^^^^^^
  File "sendchat.py", line 30, in retry_exceptions
    litellm.llms.anthropic.chat.AnthropicError,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'litellm.llms.anthropic' has no attribute 'AnthropicError'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by hammerandtongs** [comment]
Fwiw this was a long established install that's been working fine for weeks but did have an upgrade? that day.

That day and for a few days there were quite a few sporadic failures in the summarizer lookups? It seems like some difficult polish in failure paths around timeouts might be needed given the multiple possible failure steps from some models being unavailable.

**Comment by paul-gauthier** [comment]
When a model API is down/slow/flakey, aider retries patiently using exponential backoff. But after 1min it gives up.

**Comment by paul-gauthier** [comment]
Per the linked doc, how did you install aider? What version of aider and litellm are installed?

**Comment by hammerandtongs** [comment]
Ok, this is a 6+ week install thats been upgrading along the way. 

I'll work on reinstalling. 

Any thoughts on https://github.com/astral-sh/uv ?
