### ISSUE TITLE
Uncaught UnicodeEncodeError in io.py line 584

### ISSUE THREAD

**Issue by jamsturg** [paul-gauthier/aider#1636]
Aider version: 0.56.0
Python version: 3.11.5
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: Yes
OS: Windows 10 (64bit)
Git version: git version 2.46.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 698, in main
    coder.run()
  File "base_coder.py", line 734, in run
    user_message = self.get_input()
                   ^^^^^^^^^^^^^^^^
  File "base_coder.py", line 747, in get_input
    return self.io.get_input(
           ^^^^^^^^^^^^^^^^^^
  File "io.py", line 368, in get_input
    self.user_input(inp)
  File "io.py", line 413, in user_input
    self.append_chat_history(hist, linebreak=True)
  File "io.py", line 584, in append_chat_history
    f.write(text)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 19539-19540: surrogates not allowed

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Surrogate Unicode characters seem to be a rabbit hole to handle. For further notice, here are two StackOverflow answers which look like they might be related:

https://stackoverflow.com/a/27367173/2955999

https://stackoverflow.com/a/38147966/2955999

@paul-gauthier 
Maybe it is best to open the chat history file and write to it not as UTF-8, just as binary data somehow?
-> https://github.com/paul-gauthier/aider/blob/main/aider/io.py#L624

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
