### ISSUE TITLE
Incomplete OpenAI URL used

### ISSUE THREAD

**Issue by edoloughlin** [paul-gauthier/aider#1638]
### Issue

I installed aider on Ubuntu 24.02 in a virtual env (Python 3.12.3). Trying any prompts or using /help showed a repeated error message:

`litellm.APIError: APIError: OpenAIException - Connection error.
`

I changed a few lines in `llm.py` to turn on `litellm` verbose logging and I see this repeated before the requests:

```
POST Request Sent from LiteLLM:
curl -X POST \
https://api.openai.com/v1/ \
-H 'Authorization: *****' \
-d '{'model': 'gpt-4o', 'messages': [{'role': 'system', 'content': "Act as an expert software developer.\nAlways use best practices when
[...]
```

`https://api.openai.com/v1/` is clearly wrong, but I can't see how I can fix it.

I tried changing the model (I was using the default before trying 4o) but it gives the same result.

### Version and model info

Aider v0.57.1
Main model: openai/gpt-4o with diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 28 files
Repo-map: using 1024 tokens, auto refresh

**Comment by fry69** [comment]
Thank you for filing this issue.

This works for me with OpenAI API without problems.

Please check if you have set the `OPENAI_API_BASE` environment variable by accident. LiteLLM will use it if set.

Otherwise start aider with `--verbose` and check where it gets its configuration, maybe something is wrongly set there.

**Comment by edoloughlin** [comment]
Thanks - it's working now. It was a combination of using a Python venv for the first time, wrapping the aider command in a shell script and not sourcing a .env file correctly.

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
