### ISSUE TITLE
Use recent chat history from prior sessions when you launch a new session

### ISSUE THREAD

**Issue by steven-reyes** [paul-gauthier/aider#166]

**Comment by sriramr98** [comment]
Clearing the chat when reaching maximum tokens is absolutely necessary and can be opt-in based. I would love to pick this up and raise a PR

**Comment by joshuavial** [comment]
Paul has merged in a 'auto summarize chat when token limit hit' feature in #144 

I like the idea of being able to restore your last context with a command, and it should be feasible by reading the history files - it also makes me think about things like /stash xyz which lets you store a context and /restore xyz which brings it back. 

I think the long term vision is to make Aider is smart enough to know what files (or fractions of a file) to bring in to context based on the task being given so one day we don't have to think about it anywhere near as much. In that world I could imagine /stash and /restore commands being feature bloat or temporary band aid solutions. Or maybe they would be good editions.

**Comment by paul-gauthier** [comment]
Yes, everything @joshuavial said is 100% correct!

In fact, in the main branch you can already run `python -m aider.history .aider.chat.history.md` and it will print out a summarized version of the recent conversation. Keep in mind that this command line invocation is purely for debugging purposes at this time!

It's likely that in the future aider will do this on startup.

**Comment by paul-gauthier** [comment]
I just put up PR #591 for this.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by cad0p** [comment]
Funnily enough, aider provided an example implementation:

---

> /help how do I restore previously added files as well?

To restore previously added files along with the chat history when restarting aider, you can use the
--restore-chat-history flag in combination with the --file option. Here's how you can do it:

 1 First, exit your current aider session if you haven't already.
 2 When restarting aider, use both the --restore-chat-history flag and the --file option with a wildcard to
   include all previously added files. For example:

    aider --restore-chat-history --file "*" --model bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0

   The --file "*" option will attempt to add all files that were previously part of the chat session.
 3 If you know specific files or directories you want to include, you can list them explicitly:

    aider --restore-chat-history --file file1.py file2.java src/* --model
    bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0


This approach will restore both your chat history and the files that were part of your previous session.

Keep in mind that the --file option with wildcards might add more files than were originally in your chat,
so you may need to use the /drop command to remove any extra files that were unintentionally added.

If you frequently work with the same set of files, you might consider creating a shell script or alias that
includes both the --restore-chat-history flag and the --file options with your commonly used files.

Remember, you can always use the /add and /drop commands within the aider chat to fine-tune which files are
included in your session after starting up.
