### ISSUE TITLE
Uncaught AttributeError in main.py line 117

### ISSUE THREAD

**Issue by shihabdider** [paul-gauthier/aider#1677]
### Issue

# Uncaught AttributeError in main.py line 117

Aider version: 0.57.1
Python version: 3.10.6
Platform: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
Python implementation: CPython
Virtual environment: No
OS: Linux 4.18.0-372.9.1.el8.x86_64 (64bit)
Git version: git version 2.31.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 490, in main
    check_gitignore(git_root, io)
  File "main.py", line 117, in check_gitignore
    if repo.ignored(".aider"):
AttributeError: 'Repo' object has no attribute 'ignored'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
