### ISSUE TITLE
Uncaught PermissionError in pathlib.py line 1044

### ISSUE THREAD

**Issue by tomwg123** [paul-gauthier/aider#1678]
Aider version: 0.57.1
Python version: 3.11.8
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.44.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 709, in main
    coder.run()
  File "base_coder.py", line 723, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 766, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1204, in send_message
    lint_errors = self.lint_edited(edited)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1298, in lint_edited
    errors = self.linter.lint(self.abs_root_path(fname))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "linter.py", line 86, in lint
    code = Path(fname).read_text(encoding=self.encoding, errors="replace")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Projects\\my-chrome-ext\\src'

```

This seems likely having to do with some of the files Aider wanted to create failing because when it should have created a src directory, it just created an empty file named src.  Here is some of the console output before the crash:

                                                                                                                                                                               
src/                                                                                                                                                                           
Create new file? (Y)es/(N)o [Yes]:

src/manifest.json
Create new file? (Y)es/(N)o [Yes]:
Unable to create src/manifest.json, skipping edits.

src/background/background.ts
Create new file? (Y)es/(N)o [Yes]:
Unable to create src/background/background.ts, skipping edits.

src/popup/popup.html
Create new file? (Y)es/(N)o [Yes]:
Unable to create src/popup/popup.html, skipping edits.

src/popup/popup.ts
Create new file? (Y)es/(N)o [Yes]:

src/options/options.html
Create new file? (Y)es/(N)o [Yes]:

src/options/options.ts
Create new file? (Y)es/(N)o [Yes]:
C:\Projects\my-chrome-ext\src: unable to read: [Errno 13] Permission denied: 'C:\\Projects\\my-chrome-ext\\src'

src/content/content.ts
Create new file? (Y)es/(N)o [Yes]:
C:\Projects\my-chrome-ext\src: unable to read: [Errno 13] Permission denied: 'C:\\Projects\\my-chrome-ext\\src'

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
