### ISSUE TITLE
I am having an issue where aider is not able to make files or update the code that i give it on previous files that i was working on.

### ISSUE THREAD

**Issue by stevenviz** [paul-gauthier/aider#168]
I am in the latest aider update before updating to day i was in 8.0.3 i think and something like this happened but was resolved after creating a new file.  If this could be fixed without always creating a new file and if it is necessary to create a new file in order to fix this then lets try to implement it.

here is an example with a project that i am working on:

Allow creation of new file **src/screens/HomeScreen1.js**? y
[WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\steve\\OneDrive\\Desktop\\aider\\Projects\\Apps\\Finance Focus\\**src\\screens'

Traceback (most recent call last):
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aider\coders\base_coder.py", line 1035, in apply_updates
    edited = self.update_files()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aider\coders\wholefile_coder.py", line 126, in update_files
    if self.allowed_to_edit(fname, new_lines):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\aider\coders\base_coder.py", line 985, in allowed_to_edit
    Path(full_path).parent.mkdir(parents=True, exist_ok=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\steve\\OneDrive\\Desktop\\aider\\Projects\\Apps\\Finance Focus\\**src\\screens'
Update exception #5, aborting

After every attempt the system aborts and stays in the aider chat while the code or new file is not implemented into the project.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

Can you show me the first few lines that are printed when you run aider? This will contain the version number and the information about which GPT model aider is using, etc.

It looks like the LLM has proposed a filename `**src/screens/HomeScreen.js` that starts with `**`. This makes me think you may be working with GPT-3.5? If so, you would almost certainly have more success with GPT-4 if you have access.

A simple workaround is to add the file to aider yourself, and then ask GPT to put the code there. You can do that by running `aider src/screens/HomeScreen.js` or by doing `/add src/screens/HomeScreen.js` while in the chat.

**Comment by paul-gauthier** [comment]
This seems similar to issue #157 and may be improved if we explicitly strip asterisks from filenames proposed by GPT.

**Comment by stevenviz** [comment]
Hey Paul I am using gpt3.5 since I currently don't have access to gpt4.


Regarding the solution below that you suggested I usually add all the files or review them in the beginning of the chat and they are added to aider which let’s aider have access to the files and make edits and changes. But it didn’t want to further edit or add new files when it came to some components of the project.

(A simple workaround is to add the file to aider yourself, and then ask GPT to put the code there. You can do that by running aider src/screens/HomeScreen.js or by doing /add src/screens/HomeScreen.js while in the chat.)

**Comment by stevenviz** [comment]
Ok thanks I'll try that later and let you know what happens.

**Comment by stevenviz** [comment]
After following your suggestion I didn't have the issue.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by ssillah10** [comment]
Hi Paul, I am having the same issue but with Gemini. It can't create or edit files. Any suggestions?

**Comment by coolaydalena** [comment]
Im experiencing thi

> Claude has stopped being able to create files today. Is anyone else experiencing the issue?

Im experiencing the same issue. I can see in the logs the it is trying to create a new file, however in reality it didn't. Instead, it appends the code content to an existing file.

**Comment by kadavilrahul** [comment]
I think that aider need to incorporate shell commands for writing files rather than python commands which are unreliable.

**Comment by schoettler** [comment]
> Claude has stopped being able to create files today. Is anyone else experiencing the issue?

nearly a year later but yes, in macos
