### ISSUE TITLE
Integration of base url

### ISSUE THREAD

**Issue by lightningRalf** [paul-gauthier/aider#17]
Hello Paul,
is it possible to add OPEN_AI_BASE or openai.api_base endpoint

default:
openai.api_base = "https://api.openai.com/v1/chat/completions"

https://platform.openai.com/docs/models/default-usage-policies-by-endpoint

In this way I am possible to try to use local modals with it / with this method for example.
https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md

Model I want to try to use: https://huggingface.co/bigcode/starcoderplus
And also Orca once it is released.

Thanks in advance.
Greetings from Germany

**Comment by paul-gauthier** [comment]
Sure thing. Just merged PR #18 with this change.

Note that the base url should just be `https://api.openai.com/v1` without the `/chat/completions`.
