### ISSUE TITLE
Does aider work with Bard, Claude or local LLM like gpt4all? Thanks!

### ISSUE THREAD

**Issue by linvest21** [paul-gauthier/aider#171]

**Comment by paul-gauthier** [comment]
Thanks for trying aider! There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc

**Comment by linvest21** [comment]
Perfect!

Outstanding work Paul!

Look fwd to more support of private models..

Best David
