### ISSUE TITLE
litellm.RateLimitError:

### ISSUE THREAD

**Issue by efe13dev** [paul-gauthier/aider#1715]
### Issue
hi,
I am trying to use it on a file with a few lines, yesterday it worked very well but since last night it takes forever to respond to any request and most of the time it returns this error:

![Captura de pantalla 2024-09-25 090628](https://github.com/user-attachments/assets/f42ccc15-be45-4c40-92b5-64b725c593cf)

### Version and model info

Aider v0.57.1
Model: gemini/gemini-1.5-pro-latest with diff-fenced edit format
Git repo: .git with 2 files
Repo-map: using 1024 tokens, auto refresh
Use /help <question> for help, run "aider --help" to see cmd line args

**Comment by fry69** [comment]
Thank you for filing this issue.

This is an error directly from Google Vertex API, aider has no influence over rate limits. Check your account/quotas and/or contact Google.

**Comment by efe13dev** [comment]
I will try to change the Gemini api key, but I don't understand that yesterday all day it was working well and fast, and now any request takes several minutes to be resolved and many times returns an error

**Comment by fry69** [comment]
You can start aider with `--verbose` to see what is going or log the LLM messages to a file with `--llm-history-file <filename>` if you want to investigate further.

But remember that these messages come from the API endpoints, where aider has no control over.
