### ISSUE TITLE
option to always add a file to the context when asked

### ISSUE THREAD

**Issue by dwiel** [paul-gauthier/aider#1735]
### Issue

When using aider it often asks if it can read a file. I never say no. I'd like a way to set a config option so that it doesn't bother me with this question. It looks like this should be a config option and or a command line option?

**Comment by fry69** [comment]
Thank you for filing this issue.

You can start aider with the command line option `--yes` to automatically accept these requests from aider (aider will still require you to accept possibly destructive actions explicitly like running commands).

-> https://aider.chat/docs/config/options.html#--yes

**Comment by dwiel** [comment]
awesome, thanks

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
