### ISSUE TITLE
add progress UI to aid the long startup time for cli

### ISSUE THREAD

**Issue by wasdee** [paul-gauthier/aider#175]
aider startup time is long for my tried on 2 real repo, user might think it is freezing.
consider add progress bar or sth. to let user know it is working on sth not freezing

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

This is a great idea! I just added it in 3ef16827fc9794888123494268dc55f6782d6d34.

It is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
