### ISSUE TITLE
Context - Access commit history

### ISSUE THREAD

**Issue by titouandk** [paul-gauthier/aider#1758]
### Issue

It would be nice to be able to ask something based on previous commit:

> do the same changes as the last commit, but for euros instead of dollars

**Comment by fry69** [comment]
Thank you for filing this issue.

The last changes should be part of the chat history and get send to the LLM again, so you do not need last diffs while the chat history is available.

If you start aider fresh and want to have the last diff in the chat history, you can try ->
```
/run git diff HEAD~1
```
That should produce the last commit diff and it should get included in the chat history, so the LLM sees it. Increase the number after the tilde get include more past commits.

**Comment by titouandk** [comment]
This is a very handy trick, thank you!

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.

**Comment by titouandk** [comment]
The `/help` command does not know this `/run` trick apparently.

Maybe the aider doc online could also benefit of this example as a way to add context?

**Comment by fry69** [comment]
PR with new tips section is out

**Comment by titouandk** [comment]
Thank you! 🙏
