### ISSUE TITLE
Is there a way to keep existing code local?

### ISSUE THREAD

**Issue by levelground** [paul-gauthier/aider#176]
With Aider, is there a way to have it work on existing code files and also prevent it from uploading these code files or their source code to ChatGPT? This would be to ensure that in an enterprise environment, proprietary source files would not be made available elsewhere or potentially used in a manner where source code is accessible outside of the organization.

**Comment by joshuavial** [comment]
Kind of. There is an ongoing conversation in #172 about using Aider with other LLMs that you can run locally. Unfortunately none of them are really comparible to GPT 3.5 (let alone 4) in performance so they aren't much use. 

But there are a lot of people who want this so feel free to jump into discord and join the llm-integrations channel if you want to stay tuned to the conversation.

This section of the docs might also be useful https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc

**Comment by paul-gauthier** [comment]
We get a lot of questions about using aider with models other than OpenAI's GPT-3.5 and GPT-4. The short answer is that we haven't *yet* found any other models capable of *editing code* well enough to support aider's "pair programming" style workflow.

There are a few places that you can look for more information on this topic:

- Issue #172 is a "catch all" issue for discussions about this topic. I'm going to close this issue so we can keep all the discussion in that one place. Please feel free to reopen this issue if that seems more appropriate.
- There are ongoing discussions about [LLM integrations in the aider discord](https://discord.com/channels/1131200896827654144/1133060780649087048).
- The [FAQ](https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc) has some more info.
