### ISSUE TITLE
Relative paths outside root incorrectly added

### ISSUE THREAD

**Issue by BlairCurrey** [paul-gauthier/aider#178]
Found a couple bugs on main when doing `/add` with a relative paths outside of the root. 

1. In non-git repos, relative paths outside the coder root can (incorrectly) be added. 
2. In git repos, adding relative paths outside coder root causes an unhandled exception.

Instead, I would expect both of these cases to fail gracefully. Probably flow into the "Unable to add" error message. My pr for #156 happens to fix **2.** but **1.** will still be an issue.

Steps to reproduce **1.**:

- start aider in a non-git repo (and deny prompt to start git repo)
- do `/add ../somepathoutsidecoderroot`
- see that it gets added

and **2.**

- start aider in a git repo
- do `/add ../somepathoutsidecoderroot`
- see unhandled error and program crash. Stack trace points to line `self.coder.repo.repo.git.add(abs_file_path)` of `commands.py`

**Comment by paul-gauthier** [comment]
I fixed both cases, thanks for reporting.
