### ISSUE TITLE
issue with deepseek model. can't add file while using aider --deepseek --no-auto-commits

### ISSUE THREAD

**Issue by sbh-pra** [paul-gauthier/aider#1786]
### Issue

I can't add files while using with deepseek
<img width="1681" alt="Screenshot 2024-09-27 at 11 00 34 PM" src="https://github.com/user-attachments/assets/18f47b0e-55c9-42ea-84c6-f7b010e40d81">

### Version and model info

aider 0.57.1
Deepseek coder 2.5

**Comment by fry69** [comment]
Thank you for filing this issue.

This document may be helpful -> https://aider.chat/docs/usage/tips.html#creating-new-files

**Comment by sbh-pra** [comment]
@fry69 thx for doc reference

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
