### ISSUE TITLE
Need support for llama2 70B or wizardCode

### ISSUE THREAD

**Issue by Maverick7** [paul-gauthier/aider#179]

**Comment by paul-gauthier** [comment]
We get a lot of questions about using aider with models other than OpenAI's GPT-3.5 and GPT-4. The short answer is that we haven't *yet* found any other models capable of *editing code* well enough to support aider's "pair programming" style workflow.

There are a few places that you can look for more information on this topic:

- Issue #172 is a "catch all" issue for discussions about this topic. I'm going to close this issue so we can keep all the discussion in that one place. Please feel free to reopen this issue if that seems more appropriate.
- There are ongoing discussions about [LLM integrations in the aider discord](https://discord.com/channels/1131200896827654144/1133060780649087048).
- The [FAQ](https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc) has some more info.
- There are some [GitHub issues which may contain relevant information](https://github.com/paul-gauthier/aider/issues?q=is%3Aissue+%23172).
