### ISSUE TITLE
[bug] the output layout got messed up after upgrading to 0.57.1

### ISSUE THREAD

**Issue by litanlitudan** [paul-gauthier/aider#1795]
### Issue

Hi there,

Seems the terminal output's layout got messed up after upgrading to 0.57.1. Just wanna confirm whether this is a bug or a misconfiguration. The layout got messed up both in the VSCode terminal and normal Terminal. If it's a bug, I am more than happy to help debugging this issue :)
![CleanShot 2024-09-27 at 23 12 59@2x](https://github.com/user-attachments/assets/58cfd86d-691d-4b4b-b34d-961d071764b5)

### Version and model info

Aider: V0.57.1
Model: anthropic/claude-3-5-sonnet-20240620

**Comment by fry69** [comment]
Thank you for filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from GitHub:
```
aider --install-main-branch

# or

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```
If you have a chance to try it, please report if it works better for you.
