### ISSUE TITLE
o1-preview verbosity fail fix

### ISSUE THREAD

**Issue by deus777** [paul-gauthier/aider#1809]
### Issue

o1-preview seems to suffer from verbal diarrhea and often repeatedly fails to create proper SEARCH and REPLACE blocks adding unnecessary comments that were explicitly asked not to provide and hence failing to update code. 

I am thinking it might yield a higher success rate  to use the structure output feature of openai and output JSON blocks instead for the o1 series of models. Openai guarantees this format to be correct (supposedly).

**Comment by fry69** [comment]
The `o1` models do not allow structure output.

This document may be helpful -> https://aider.chat/2024/08/14/code-in-json.html
