### ISSUE TITLE
Thoughts on internal architecture

### ISSUE THREAD

**Issue by joshuavial** [paul-gauthier/aider#181]
I've been looking at at some of the aider tickets like #170 and #172 and thought it was worth a conversation before trying to tackle them. I figure a little internal refactoring might make it a bunch easier to implement but didn't want to spend time on significant changes without discussion first.

It seems to me there might be some benefit of building up some internal concepts of 
- transport : how aider talks to the LLM (e.g. openai, text-generation-interface)
- model : which model you're talking to
- coder : which coder is driving the model (editblock, wholefile etc.)

It would then be straightforward to reference a setup as `openai.gpt-4-8k.editblock` and have a lot of information about what is going on.

For example for #170 we can keep using the openai transport layer as openrouter supports the interface but as we play with the claude (and other) models it would be nice to be able to easily switch out editblock vs wholefile coders to measure the performance.

For #172 I would be keen to experiment with a [text-generation-interface](https://github.com/huggingface/text-generation-inference) transport as we can have more control (and maybe less complexity?) than using an openAI api wrapper like fastchat or text-generation-webui. I'm also thinking we would likely need to write some specific coders to get any useful work out of the smaller open models.

I think this would also get us a long way to a simple plugin architecture where if we document what a transport or coder need to implement it becomes possible to incorporate 3rd party code with flags like --transport or --coder pointing to stand alone directories. I don't know if we would need or want a full blown plugin system but giving people the ability to easily implement their own transports, coders, (and maybe even commands?) might go a long way to keeping the core of aider lean and focused on the essentials.

Thoughts?

**Comment by paul-gauthier** [comment]
I think a bunch of this is already supported? Aider has `Model` and `Coder` objects. I think they only need to be gently extended to support the vision you are describing.

The Model is providing defaults for which coder backend to use, context window size, whether a repo map should be used and a couple of other details. It also attempts to validate sane model names (currently only from the OpenAI naming scheme).

The Coders implement different code editing prompts and backends.

You can choose the Model with `--model` and you can override the default editing backend with `--edit-format` to select any of the Coders. There's some support for overriding other defaults of a given Model, and I was expecting to add switches for that.

The concept of a Transport sounds interesting. I am a bit concerned about trying to support a large number of different APIs/wrappers/abstractions that all lead to the same bag of models. But I haven't thought deeply about this yet.

**Comment by joshuavial** [comment]
Cool, I wasn't thinking of dramatic changes and it might be transport is overkill and we can get all we need with the cloned openAI interfaces - I'll start with getting the openrouter models registered happily and see what flags need to be exposed to make that easy.
