### ISSUE TITLE
Confused about the convention configuration

### ISSUE THREAD

**Issue by moltar** [paul-gauthier/aider#1821]
### Issue

The [example docs](https://aider.chat/docs/usage/conventions.html) show:

```
# alone
read: CONVENTIONS.md

# multiple files
read: [CONVENTIONS.md, anotherfile.txt]
```

But the [configuration docs](https://aider.chat/docs/config/aider_conf.html) state:

```
## specify a read-only file (can be used multiple times)
#read: xxx
## Specify multiple values like this:
#read: [xxx,yyyy,zzz]
```

How do these two concepts relate?

### Version and model info

aider 0.57.1

**Comment by fry69** [comment]
Thank you for filing this issue.

The "(can be used multiple times)" is a bit confusing, it refers to the command line arguments, where this is true. But since the documentation for aider gets auto-generated from the source code, this spills into the pseudo-YAML file, where it is not true.

Use the the second syntax for configuration files.

**Comment by fry69** [comment]
`read-only` and `read` are synonymous in aider, I tried to fix this confusion a bit,  but so far no luck -> https://github.com/paul-gauthier/aider/pull/1743

**Comment by moltar** [comment]
So what's the correct way to set:

1) a list of read-only files
2) a list of convention files

?

**Comment by fry69** [comment]
They are the same. A convention file is just a name for a read-only file, it is in no way special.

**Comment by moltar** [comment]
So how does Aider know which files to consider convention and which are just random read only files I have in the repo?

**Comment by fry69** [comment]
Aider doesn't care. The LLM does also not really care. It is just a convention.

**Comment by moltar** [comment]
So do read only files get auto added as context then?

**Comment by fry69** [comment]
Yes. that is the purpose of `/read` and `--read` and `read:`

**Comment by fry69** [comment]
For further discussion I recommend to join the Discord and carefully read the documentation.
