### ISSUE TITLE
Ability to use any valid YAML

### ISSUE THREAD

**Issue by moltar** [paul-gauthier/aider#1822]
### Issue

To my surprise, I've noticed this little note:

```
A note on lists

The syntax for specifying a list of values is not standard yaml. Instead, use this format:

read: [CONVENTIONS.md, anotherfile.txt, thirdfile.py]
```

Is there any chance any valid YAML can be supported?

I'm using a tool to produce this config, and unfortunately, I cannot force it to produce this exact YAML variant, and it renders the YAML in a typical dash-prefixed list.

### Version and model info

aider 0.57.1

**Comment by fry69** [comment]
Thank you for filing this issue.

aider uses ConfigArgParse (see here -> https://github.com/bw2/ConfigArgParse) which only supports a subset of YAML.

**Comment by moltar** [comment]
Understood. If you don't think there's a way to fix that, then the issue can be closed. Thanks!

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
