### ISSUE TITLE
Wrong language - French

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#1827]
Aider responded in French while I use English.

I just opened aider, and did a /web scrape of an English website (https://ollama.com/blog/tool-support), but then Aider immediately output text in French commenting on the web page.

Aider version: 0.57.1
Python version: 3.10.12
Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: Yes
OS: Linux 5.15.153.1-microsoft-standard-WSL2 (64bit)
Git version: git version 2.34.1

Aider v0.57.1
Main model: claude-3-5-sonnet-20240620 with diff edit format, prompt cache, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 0 files
Repo-map: using 1024 tokens, files refresh

**Comment by fry69** [comment]
Thank you for filing this issue.

LLMs can get confused and switch to a different language sometimes, aider has no influence over their behavior.

You can try to fix the language with `--chat-language` (see here -> https://aider.chat/docs/config/options.html#--chat-language-chat_language)

Or try creating a `CONVENTIONS.md` file which tells the LLM to respond in a specific language, see here -> https://aider.chat/docs/usage/conventions.html
