### ISSUE TITLE
"Timeout while loading" message when scraping

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#1828]
I get a "timeout while loading" message when scraping a site. This consistently and repeatedly happens on this site, while some other sites work ok. I have playwright installed.
The site still appears to have been scraped, as aider comments about the contents of the site.

> /web https://ollama.com/blog/tool-support

Scraping https://ollama.com/blog/tool-support...
Timeout while loading https://ollama.com/blog/tool-support

Aider version: 0.57.1
Python version: 3.10.12
Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: Yes
OS: Linux 5.15.153.1-microsoft-standard-WSL2 (64bit)
Git version: git version 2.34.1

Aider v0.57.1
Main model: claude-3-5-sonnet-20240620 with diff edit format, prompt cache, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 1 files
Repo-map: using 1024 tokens, files refresh

**Comment by fry69** [comment]
Thank you for filing this issue.

This seems to come from the playwright process, not aider. As it seems harmless, I recommend to just ignore these messages. This might just be a JS library or some other part of the website which failed to load but was unimportant for the content.
