### ISSUE TITLE
How to use Gemini with proxy url?

### ISSUE THREAD

**Issue by Flamme13** [paul-gauthier/aider#1849]
### Issue

Hello.
How to use proxy URL to use Gemini?
I tried `https://aider.chat/docs/llms/openai-compat.html` this example but it didn't help me.
I use it like this `aider --openai-api-base [proxy-url]` and in my `.aider.conf.yml` I set model `model: gemini/gemini-1.5-pro-002`. But --openai-api-base is simply ignored.
Can you explain me how to do it with example if it is possible?
Thanks.

### Version and model info

Aider version: 0.58.0
Python version: 3.10.12
Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 6.8.0-45-generic (64bit)
Git version: git version 2.34.1

**Comment by fry69** [comment]
> I use it like this `aider --openai-api-base [proxy-url]` and in my `.aider.conf.yml` I set model `model: gemini/gemini-1.5-pro-002`. But --openai-api-base is simply ignored.

Read the [instructions](https://aider.chat/docs/llms/openai-compat.html) you cited carefully again. You need to set the model name to
```yaml
model: openai/gemini-1.5-pro-002
```
to trigger using your OpenAI API compatible proxy. If you leave the `openai/` out, you'll use the Gemini endpoint.

This might still not work if your proxy does not correct the model to what the actual LLM endpoint expects.

**Comment by Flamme13** [comment]
I'm so sorry. Maybe I'm just stupid, but I don't understand how to use a proxy for Gemini for Aider.

I have a proxy URL. I can make a POST request to that URL with a Gemini API compliant body and get a Gemini API stream response.

For example, I can use the Gemin API like this:

```
curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"Explain how AI works"}]}]}' \
  -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-002:streamGenerateContent?alt=sse&key=$YOUR_API_KEY'
```

I can also use my proxy URL for the same result:

```
curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"Explain how AI works"}]}]}' \
  -X POST 'https://mytestproxy.domain/gemini'
```

Please explain how do I run Aider with my proxy URL for Gemini? What do I need to change in Aider config or in my proxy URL? Because I don't think OpenAI API is compatible with Gemini API. Maybe I need to convert request data and response data from OpenAI compatible API to Gemini compatible API and back?

Thanks.

**Comment by fry69** [comment]
The proxy URL/endpoint/schema must be supported by LiteLLM -> https://github.com/BerriAI/litellm

aider cannot support specific endpoints manually.

**Comment by Flamme13** [comment]
Is there anything that could be added to the Aider API to make this process easier?

**Comment by fry69** [comment]
> Is there anything that could be added to the Aider API to make this process easier?

I doubt it, every request has to go through LiteLLM in the end, that is how aider works.

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
