### ISSUE TITLE
v0.58.0 sends to many tokens

### ISSUE THREAD

**Issue by MarvinTheLabs** [paul-gauthier/aider#1854]
### Issue

Yesterday I encountered something which seems to be a bug in v0.58.0:
When using the aider chat every now and than I would get a 'rate_limit_error' out of nowhere. 

I was creating some readmes and only had the needed files with like 14k tokens in the chat. 
For some requests everything was working as intended, but sometimes I got the 'rate_limit_error' without adding more files to the chat.

Here is an excerpt from my .aider.chat.history.md:

`# aider chat started at 2024-09-30 13:17:22

...

#### /ask components and other corresponding elements should be imported from the ...

...

> Tokens: 14k sent, 1.1k received.
> Cost: $0.06 message, $0.21 session. Use --no-stream for accurate caching costs.

#### please apply the changes now

...

> litellm.RateLimitError: AnthropicException - b'{"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}'  
> Retrying in 0.2 seconds...  
> litellm.RateLimitError: AnthropicException - b'{"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}'  
> Retrying in 0.5 seconds...  
> litellm.RateLimitError: AnthropicException - b'{"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}'  
> Retrying in 1.0 seconds...
>
> ^C again to exit  
> Tokens: 777k sent, 7.3k received.
> Cost: $2.44 message, $2.65 session. Use --no-stream for accurate caching costs.
>
> ^C KeyboardInterrupt
`

When looking at the logs in the anthropic console about that time the same request seemed to be done multiple times at once: 

![Bildschirm­foto 2024-10-01 um 08 21 01](https://github.com/user-attachments/assets/b8d5704f-99a7-4ce3-bdcf-6f6a1c67f0cf)

For the rest of the day I used 0.57.0 and 0.56.0 without encountering the same issue.

### Version and model info

Aider  v0.58.0
Model: claude-3-5-sonnet-20240620

**Comment by fry69** [comment]
Thank you for filing this issue.

The fix is in the latest version (`0.58.1`), please update aider with
```
aider --upgrade
```
Please do not forget to exit and restart aider after it updated itself.

Duplicate #1841
