### ISSUE TITLE
/read-only does not autocomplete the full file path

### ISSUE THREAD

**Issue by distributev** [paul-gauthier/aider#1857]
### Issue

The same as /add does

This makes it very impractable to add files in read-only since the full path need to be knows by heart.

### Version and model info

Aider latest version with sonnet.

**Comment by fry69** [comment]
Thank you for filing this issue.

`/add` gets is files from the git repository and can use this information for autocomplete.
`/read` should support filesystem wide autocomplete in `0.58.1`, please check your version.

**Comment by distributev** [comment]
I have latest aider and /read-only does not suggest anything when I type.

Even for /read-only it can suggest from git repository since, most likely, people add to /read-only to benefit from the prompt caching and reduce costs when doing many subsequent /ask questions to aider on the same set of files. I use /ask a lot more often then I use /code

**Comment by fry69** [comment]
Works for me ->

<img width="793" alt="autocomplete" src="https://github.com/user-attachments/assets/c5ac63a4-ea87-42d3-b14f-e8d8471186e2">

**Comment by distributev** [comment]
I tried both /read and /read-only

Indeed something works with both but it is different behavior vs /add so it was confusing because I was doing what I was used from /add meaning to start to type part of the filename (could be in the middle) and aider will find files which match and suggest to autocomplete with full path => easy and nice

trying the same thing with /read and /read-only does not work - after I have read what you said I tried a bit more and noticed I can indeed start to type the beginning of folder name from my filesystem and it will offer me to complete the full folder name and then I can do the same for following folder name until I reach my file. good enough but being different behavior vs. /add it was confusing and (seemed) not to work - now that I found add it is a bit better but still... why not the same as /add ?

**Comment by fry69** [comment]
> why not the same as /add?

Because, as I mentioned above, `/add` works on the git repository files, those can be gathered in one go. The complete filesystem cannot.

I think this issue has been resolved, so I am closing it now. If you think I missed something, feel free to comment and I re-open it, if necessary.

**Comment by distributev** [comment]
Re: 

_"Because, as I mentioned above, /add works on the git repository files, those can be gathered in one go. The complete filesystem cannot."_

This I understood but why can't /read /read-only be made to work on git repository files the same like /add also? It can work on git repo files and be read only also do not exclude each other.

Or make both /add and /read work on filesystem but be consistent between commands.

Actually now I get used with aider's strong dependency on git but initially I was not comfortable with that. I mean, aider can modify files/folders in any folder structure being git folder report or not. And then, the git features, like git commit and other git features could come as "added extra nice bonus" but without hardcoding aider's basic capabilities with git without a strong reason to do so (git is not required to edit some files inside a folder structure)

**Comment by distributev** [comment]
aider is a great tool, if I did not make it obvious until now.
I am comfortable with both git and aider, this was not the point.

**Comment by mrclrchtr** [comment]
I got into the same situation today, thinking that `/read-only` autocompetion doesn't work. Intuitively I assumed that it works exactly like `/add`. Would it perhaps be possible to implement two commandos, one that works like `/add` and one that works at `fs` level?

**Comment by mrclrchtr** [comment]
It's contained in https://github.com/Aider-AI/aider/releases/tag/v0.59.0 🎉 Thank you very much!
