### ISSUE TITLE
Aider never hangs and did not recover after this issue 

### ISSUE THREAD

**Issue by Yona544** [paul-gauthier/aider#1869]
### Issue

PosExportFormUnit.pas frmFieldMapping.dfm frmFieldMapping.pas uFieldMappingLogic.pas uJSON_basket.pas uMasterDetail.pas
architect> litellm.InternalServerError: AnthropicException - {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}. Handle with `litellm.InternalServerError`.
Retry in 0.6 seconds.
litellm.InternalServerError: AnthropicException - {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}. Handle with `litellm.InternalServerError`.
Retry in 1.2 seconds.
litellm.InternalServerError: AnthropicException - {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}. Handle with `litellm.InternalServerError`.
Retry in 2.4 seconds.

### Version and model info

Aider v0.58.1
Main model: claude-3-5-sonnet-20240620 with architect edit format, infinite output
Editor model: claude-3-5-sonnet-20240620 with editor-diff edit format
Weak model: claude-3-haiku-20240307
Repo-map: using 1024 tokens, auto refresh

**Comment by fry69** [comment]
Thank you for filing this issue.

The Anthropic API is overloaded, there is nothing aider can do about this ->
> {"type":"overloaded_error","message":"Overloaded"}}
