### ISSUE TITLE
Architect mode: BadRequestError: litellm.BadRequestError: GetLLMProvider Exception - list index out of range

### ISSUE THREAD

**Issue by tarasglek** [paul-gauthier/aider#1881]
### Issue

`aider --deepseek --chat-mode architect --editor-model deepseek` it provides the answer, but when i confirm it throws this error.
Dropping ` --editor-model deepseek` works

### Version and model info

aider 0.58.1

**Comment by fry69** [comment]
Thank you for filing this issue.

The correct name for DeepSeek as a model is `deepseek/deepseek-code` 
(do not confuse this with the shorthand command line flag `--deepseek`, which sets the above model name for the main model)

Use this command line ->
```shell
aider --deepseek --chat-mode architect --editor-model deepseek/deepseek-code
```

**Comment by Yona544** [comment]
Maybe Aider can do a small ping to the model when loading to check if ALL the models used are responsive

**Comment by paul-gauthier** [comment]
Aider normally "sanity checks" each model on launch, but was not checking the `--editor-model`. That's been fixed.

The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by erik-balfe** [comment]
Still get this error after long and pricey answer by o1 that in the end fails with deepseek request error. 
Is there a way to check that current settings are ok without making expensive test requests?

I just made 5 requests where aider was not able to change anything when editing model failed to implement the changes.
It would be great if the program let me know that all API keys are ok and all model names are ok.
