### ISSUE TITLE
Uncaught ValueError in history.py line 120

### ISSUE THREAD

**Issue by rthidden** [paul-gauthier/aider#1889]
Aider version: 0.58.1
Python version: 3.12.6
Platform: Windows-11-10.0.22635-SP0
Python implementation: CPython
Virtual environment: Yes
OS: Windows 11 (64bit)
Git version: git version 2.46.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 727, in main
    coder.run()
  File "base_coder.py", line 730, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 773, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1201, in send_message
    self.reply_completed()
  File "architect_coder.py", line 32, in reply_completed
    editor_coder = Coder.create(**new_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 132, in create
    done_messages = from_coder.summarizer.summarize_all(done_messages)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "history.py", line 120, in summarize_all
    raise ValueError("summarizer unexpectedly failed for all models")
ValueError: summarizer unexpectedly failed for all models

```

**Comment by fry69** [comment]
Thank you for filing this issue.

It looks like the weak model failed to summarize the chat for some reason. aider cannot do anything about this in this case, but I think this exception should be handled more gracefully, so I label it a bug for now.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
