### ISSUE TITLE
Rate limit reached for 10KTPM-200RPM

### ISSUE THREAD

**Issue by kit678** [paul-gauthier/aider#189]
Just got GPT 4 API Access. I set the api key using 'export OPENAI_API_KEY="sk-xx..." '
Then I ran aider on a ~270 line ~2000 word html doc. I am using the 8K gpt model as shown below. Whats'up with these rate limits, I don't think I should be crossing those limits, my prompt was pretty short too. What am I missing?

$ aider resume.html --model gpt-4-0613
Aider v0.11.1
VSCode terminal detected, pretty output has been disabled.

Model: gpt-4-0613
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
Added resume.html to the chat.
Use /help to see in-chat commands, run with --help to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────resume.html                                                                                                                                                                                          
> what is this html about                                                                                                                                                                            

Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.
Retry in 0.2 seconds.
Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.
Retry in 0.2 seconds.
Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.
Retry in 0.2 seconds.
Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.
Retry in 2.8 seconds.
Rate limit reached for 10KTPM-200RPM in organization org-xxx  on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.
Retry in 9.5 seconds.

^C again to exit

**Comment by froggomad** [comment]
Same, I didn't notice this before upgrading to the most recent version or using ctags. Unfortunately I did both at the same time so not sure which could be the cause

**Comment by paul-gauthier** [comment]
@froggomad which version are you seeing this with?

**Comment by paul-gauthier** [comment]
@kit678 can you try running that example again with `--verbose` ? This will show you all the traffic back and forth to openai.

Does your openai organization use the api for other things? My understanding is that rate limits are applied across all api access coming from you org, not just from a single session or single api key.

**Comment by AlexSheiko** [comment]
The problem happens if attempting to work on a very large file (4000+ lines of code in my case)

**Comment by paul-gauthier** [comment]
I was able to reproduce this issue after some additional discussion with folks on discord. I've opened an issue that explains what it going on and which proposes a workaround for this unusual openai behavior.

https://github.com/paul-gauthier/aider/issues/205
