### ISSUE TITLE
Uncaught TypeError in pathlib.py line 373

### ISSUE THREAD

**Issue by existentialstudios** [paul-gauthier/aider#1890]
Aider version: 0.58.1
Python version: 3.12.5
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.45.1.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 477, in main
    right_repo_root = guessed_wrong_repo(io, git_root, fnames, git_dname)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 42, in guessed_wrong_repo
    check_repo = Path(GitRepo(io, fnames, git_dname).root).resolve()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo.py", line 94, in __init__
    self.root = utils.safe_abs_path(self.repo.working_tree_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils.py", line 99, in safe_abs_path
    res = Path(res).resolve()
          ^^^^^^^^^
  File "pathlib.py", line 1162, in __init__
    super().__init__(*args)
  File "pathlib.py", line 373, in __init__
    raise TypeError(
TypeError: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'NoneType'

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Can you please describe what happened when this exception occurred? Or give steps how to reproduce it?

(sorry for the late reply, this issue seemed to fallen through the net)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
