### ISSUE TITLE
Feature Idea: Locked files

### ISSUE THREAD

**Issue by vessenes** [paul-gauthier/aider#1891]
### Issue

I'm deep into a large codebase with Aider, crossing three different languages. I love it. It's incredibly helpful. However, I've found that steering Claude, especially when I'm working on cross-code / cross-module integrations can be tough; it can eagerly go ahead and change an interface or datastructure that I don't want to change -- instead I want the new code to consume the old datastructure. 

Instructions to this effect, e.g. "DO NOT EDIT THIS FILE. IT WORKS. ONLY EDIT <OTHER FILE>" are ... sometimes helpful. But of course, the context window is pretty long in these cases, because we have a lot of different files to look at. 

I wonder if a simple way might be a /lock command, which just treats certain files as read-only, and refuses patches for them. Happy to hear thoughts on this, but I think it would ease a common pain point for me.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can add files to the context with `/read-only` if you don't want aider to edit them.

**Comment by vessenes** [comment]
Nice!
