### ISSUE TITLE
Openai-api-base / problems getting it to work

### ISSUE THREAD

**Issue by lightningRalf** [paul-gauthier/aider#19]
Hello Paul,

I noticed that in the argument `--help` the openai api base is not included:

    parser.add_argument(
        "--openai-api-base",
        metavar="OPENAI_API_BASE",
        default="https://api.openai.com/v1",
        help="Specify the OpenAI API base endpoint (default: https://api.openai.com/v1)",
    )
    
is the --help info not automatically generated?

Greetings

**Comment by paul-gauthier** [comment]
Are you installing from pypi or GitHub? You need to install the latest from github to pick up the --openai-api-base feature. I haven't cut a new release to pypi that includes it.

```
$ pip install git+https://github.com/paul-gauthier/aider.git
$ aider --help | grep -i base
             [--openai-api-base OPENAI_API_BASE] [--dry-run] [--show-diffs]
  --openai-api-base OPENAI_API_BASE
                        Specify the OpenAI API base endpoint (default:
                        AIDER_OPENAI_API_BASE]
```

**Comment by lightningRalf** [comment]
Okey, so I tried it.
But it seems that I cannot get it to run.

I tried storing these in the config:
openai-api-key: "MYKEYHERE"
openai-api-base: "http://localhost:9090/v1/chat/completions"

(The readme of the other app tells me I have to it in this way) - hope there is a way to get it to this

**Comment by paul-gauthier** [comment]
Don't include `/chat/completions` in the API base. So your config file should have this entry:

```
openai-api-base: "http://localhost:9090/v1"
```

**Comment by paul-gauthier** [comment]
Closing this for now. Please feel free to re-open if the above didn't help with your issue.
