### ISSUE TITLE
Feature Request /runai

### ISSUE THREAD

**Issue by arashilmg** [paul-gauthier/aider#190]
The `/run` command is useful in the chatbox, but it just run exactly what I type a shell script.
It would be super useful(highly expected) to just translate what is in front of /run into a shell script then run it.

**Hence asking for a new `/runai` option**

i.e
```sh
> /run ls -at
```
vs
```sh
> /runai list all files sorted
```

**Comment by transcendr** [comment]
I don't think this should be aider's responsibility when there are already dedicated tools out there for this:

For example shell_gpt. Install it, alias it's command `sgpt` to `ai` if you want and do `/run ai` if you prefer. Here is an example output using it inside of aider:

![image](https://github.com/paul-gauthier/aider/assets/37011672/4dbb5c0d-ebd1-4aec-b748-48199ac8bcec)

**Comment by transcendr** [comment]
@paul-gauthier  I just wanted to note that the above does not work with github copilot CLI; it throws, doesn't recognize the command `??`. I didn't try aliasing it.

![image](https://github.com/paul-gauthier/aider/assets/37011672/c7684235-8eb8-41bb-9d8b-e2fcdaddba1f)

**Comment by paul-gauthier** [comment]
It appears that there is no executable named `??` available on your PATH.

**Comment by transcendr** [comment]
@paul-gauthier  pretty sure it has something to do with how it's injected into the shell:

See "Setup alias convenience commands" here:

https://www.npmjs.com/package/@githubnext/github-copilot-cli#:~:text=Setup%20alias%20convenience,the%20current%20session.

**Comment by arashilmg** [comment]
Pretty disappointed by your reply @transcendr; let me explain...

>I don't think this should be aider's responsibility when there are already dedicated tools out there for this

This was not a complaint for Aider not doing its responsibility; this is just a new **Feature Request** 
Of course, there are plenty of tools doing the same kind of task. But this theory is usually true with all features of all apps. For every feature of an app, there is a separate external tool that does the job. The points(use-case) of this feature are:

1. Not using other tooling and other integrations for executing ai generated shell command
2. Generated shell command to be in context with what is loaded in aider (e.x. when I say /runai "make the files executable", it would know the files that are loaded I mean)

_Anyway, I understand if you guys think the value of this feature request doesn't justify the effort_

**Comment by transcendr** [comment]
@arashilmg  I don’t think I ever said or implied that it was a complaint per se that Aider was not fulfilling its responsibility (although using the term “highly expected” as you did, does convey a bit of complainty-ness, though I never meant to convey that myself). I meant "responsibility" in the sense of common usage in development where we talk about the responsibility of a module, a class, a service, etc. And to be fair, in your original post, your example of “list all the files” is not exactly the same as your second example which now indicates that you would like in-context operations on files loaded into Aider.

**Comment by paul-gauthier** [comment]
I actually have been planning some feature work which should naturally solve this. When GPT replies with a `bash` code block, aider will ask if you'd like to run it. So you would have a chat session like this:

````
> How can I make the the file world readable?

You can use chmod, like this:

```bash
chmod a+r app.js
```

Run shell command `bash a+r app.js` (y/n)? y
````

Not sure when I will have the time to implement this, but it's on the roadmap.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
