### ISSUE TITLE
Uncaught NotFoundError in utils.py line 6432

### ISSUE THREAD

**Issue by htorres00** [paul-gauthier/aider#1903]
Aider version: 0.58.2.dev7+g9789668c
Python version: 3.12.5
Platform: macOS-10.16-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.44.0

An uncaught exception occurred:

```
openai.PermissionDeniedError: Error code: 403 - {'error': {'message': 'Project `proj_9KoeXdtHe0YQJbsF2FQAKmzl` does not have access to model `gpt-4o-mini`', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
```

**Comment by fry69** [comment]
Thank you for filing this issue.

Looks like you did not activate in this model in Vertex AI Model Garden -> 

> Project `proj_9KoeXdtHe0YQJbsF2FQAKmzl` does not have access to model `gpt-4o-mini`
