### ISSUE TITLE
openrouter/deepseek/deepseek-coder not recognised as a main model

### ISSUE THREAD

**Issue by kuatroka** [paul-gauthier/aider#1909]
### Issue

openrouter/deepseek/deepseek-coder not recognised as a main model, but it is alright as the weak. I set it up in my .env file. The weak is picked up but not the main. I'm using the same name for both.

thanks

![image](https://github.com/user-attachments/assets/0dc6cce2-2f74-49f3-8ad5-27ccf18f8901)

### Version and model info

See the screenshot

**Comment by fry69** [comment]
Thank you for filing this issue.

Please start aider with `--verbose` to see what it picks up from where. it may be that there is another model set somewhere, or a shorthand `--sonnet`.

**Comment by kuatroka** [comment]
```
Loaded /Users/yo_macbook/.env
Loaded /Users/yo_macbook/Documents/dev/aider-tut-python/.env
Too soon to check version: 0.8 hours
Command Line Args:   --verbose

Environment Variables:
  OPENAI_API_KEY:    ...jSse
  ANTHROPIC_API_KEY: ...egAA
  AIDER_MODEL:       openrouter/deepseek/deepseek-coder
  AIDER_SONNET:      true
  AIDER_WEAK_MODEL:  openrouter/deepseek/deepseek-coder
  AIDER_CACHE_PROMPTS:true
  AIDER_CODE_THEME:  monokai

```

I see 'sonnet' is set to true, but this is in my very top level `.env`. 
I also got an `.env` file right in my repo and I thought that it would be the one where the data is coming from and if there is no such .env , then it'd go to the top level one

**Comment by fry69** [comment]
This is your problem, remove where ever this get set ->
```
AIDER_SONNET:      true
```

**Comment by kuatroka** [comment]
Thanks, yes, I've done that already. Is there a hierarchy of which .env will it be looking first, second and so on?

> It is a shorthand to set Sonnet-3.5 as your main model which takes precedence over all.
even if I have multiple .env?

**Comment by fry69** [comment]
> Thanks, yes, I've done that already. Is there a hierarchy of which .env will it be looking first, second and so on?

Yes, see here -> https://aider.chat/docs/config/dotenv.html

> > It is a shorthand to set Sonnet-3.5 as your main model which takes precedence over all.
> 
> even if I have multiple .env?

I think so, yes.

**Comment by kuatroka** [comment]
> Your home directory.
The root of your git repo.
The current directory.
As specified with the --env-file <filename> parameter.
If the files above exist, they will be loaded in that order. Files loaded last will take priority.

According to this guide, the .env in the current directory should overwrite the one in the home dir, but I guess it's not happening. I imagine it's as you said if it's set in at least one, it can't be unset in another. A bit confusing, tbh, I'd assume, it should just choose one .env and stick to it and not pick one value from one .env and others form another

**Comment by kuatroka** [comment]
Thanks a lot. I'll close it
