### ISSUE TITLE
Vertex AI - anthropic-claude-3-5-sonnet not working "Quota exceeded"

### ISSUE THREAD

**Issue by drwbns** [paul-gauthier/aider#1912]
### Issue

Hey all! Been trying like hell to get Claude sonnet 3.5 working through Vertex AI but no luck. I am assuming its a google issue but figured I'd check here to be sure. I went through all the Vertex AI and gcloud setup, tried everything I could and no luck. I have plenty of credits in my google api account as well. Here's my log:

Aider v0.58.1
Main model: vertex_ai/claude-3-5-sonnet@20240620 with architect edit format, infinite output
Editor model: vertex_ai/claude-3-5-sonnet@20240620 with editor-diff edit format
Weak model: vertex_ai/claude-3-haiku@20240307
Git repo: .git with 38 files
Repo-map: using 1024 tokens, auto refresh
VSCode terminal detected, pretty output has been disabled.
Use /help <question> for help, run "aider --help" to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────architect> hello                                                                                                                                                             

litellm.RateLimitError: litellm.RateLimitError: VertexAIException - b'[{\n  "error": {\n    "code": 429,\n    "message": "Quota exceeded for 
aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: anthropic-claude-3-5-sonnet. Please submit a quota increase request. 
https://cloud.google.com/vertex-ai/docs/generative-ai/quotas-genai.",\n    "status": "RESOURCE_EXHAUSTED"\n  }\n}\n]'

**Comment by fry69** [comment]
Thank you for filing this issue.

This is an issue with your API account, there is nothing aider can do about this.

**Comment by sivaezhumalai** [comment]
Same issue for me also..is there any other solution for this?
