### ISSUE TITLE
CONTRIBUTING.md DEVELOPMENT.md missing

### ISSUE THREAD

**Issue by jowenjowen** [paul-gauthier/aider#192]
I want to contribute to this project. I've started by adding CONTRIBUTING.md
DEVELOPMENT.md files, but I'm willing to help with anything else. You can email me at jowenjowen@gmail.com

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

I'm not sure what you mean that you have "started by adding CONTRIBUTING.md
DEVELOPMENT.md files"?

**Comment by jowenjowen** [comment]
I can make a fork and then issue a PR and you can see if you want to accept
them (or modify them, or give me recommendations). I'm also interested in
helping with whatever you might need. I noticed your unit test coverage is
weak in some areas (but I'm not sure how helpful it would be to have better
coverage, because you might end up having to re-write tests when you
refactor).

I have a second motivation that I should mention, which is to figure out a
poor man's Domain Driven Development system that could be adopted by your
average programmer, and I want to use Aider to transform existing open
source projects to DDD to see if it actually improves the code. At some
point, I'm hoping to come up with a compelling method that's palatable.Ai

Anyway, if I can help with Aider in any way, let me know.

Thanks
James Owen

**Comment by linvest21** [comment]
Hi Paul, may have missed something simple: How do we recursively include
all source files in a given directory? Right now, I use "find" to list all
files of desired and use "/add". Thanks David

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
