### ISSUE TITLE
Voice language

### ISSUE THREAD

**Issue by buger** [paul-gauthier/aider#194]
Hi! I'm having issues with /voice command. When it works, it works great, but sometimes it not just transcribe, but also translate. For example I talk in english all the time, it properly transcribe it, but then also translate either to Russian or Ukranian 😅 In the logs it looks like:

> USER В английско, искам, че да добавите поддержка за екстензията на пайтен файла на листата на дефолтната екстензия, която ще бъде процесирана.
>
> To add support for Python files, we need to modify the cmd/code_compressor.py file. Specifically, we need to add '.py' to the list of default file types to process.

The last phase is accurate, but why it translated it...

**Comment by paul-gauthier** [comment]
Yes I have noticed this too. It would probably help to add a config option to set the language.

**Comment by paul-gauthier** [comment]
I added 2 things which should really help this:

1. The recent conversation is sent to Whisper as a "prompt". This will both give it a sense of the language you are using, but also show it some of the specific keywords and identifiers that you've been taking about.
2. I added `--voice-language` that lets you specify the language you want to use with an [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) code.

This is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
