### ISSUE TITLE
Parallel requests to multiple instances of GPT?

### ISSUE THREAD

**Issue by ProfitWaveTradingCo** [paul-gauthier/aider#206]
If possible Use an assembly of GPT models Giving them all the same role as aider, Allowing the user to input multiple API keys for each.  This would significantly increase aider capability by using multiple api keys to have a bigger input and output Would allow it to handle bigger tasks by breaking up the The user's query into multiple task lets say between 5 where each gpt model equals a number to complete that specific tasks . Open to feedback I'm new to all of this

**Comment by paul-gauthier** [comment]
Thanks for trying aider and asking this question.

I'm not exactly sure how that could work, but it's an interesting concept to think about.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by tianshuo** [comment]
A round-robin code would work for this:
1. shuffle keys in a  random way
2. pick first key  for  first query
3. Pick next  key for next query
4. If reach end,  restart from first key.
