### ISSUE TITLE
Frozen runpy line198

### ISSUE THREAD

**Issue by mcbgun** [paul-gauthier/aider#209]
Hi all,

Aider was working fine yesterday but suddenly, it's just stopped today? Any ideas? I am new to all this AI programming but have managed to create a good framework for a game and it's going well but this has thrown me when trying to load aider in the VSC terminal.

`traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\marc_\OneDrive\Desktop\python\Scripts\aider.exe\__main__.py", line 4, in <module>
  File "C:\Users\marc_\OneDrive\Desktop\python\Lib\site-packages\aider\main.py", line 9, in <module>
    from aider import __version__, models
ImportError: cannot import name '__version__' from 'aider' (C:\Users\marc_\OneDrive\Desktop\python\Lib\site-packages\aider\__init__.py)`

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue. It looks like something may be wrong with your local python environment, your python path or your install of aider. It seems as though python is not able to find the `aider` module.

You might want to try re-installing aider according to the install instructions:

https://aider.chat/docs/install.html

**Comment by mcbgun** [comment]
Thanks for the reply. The problem is... from shutting down the laptop one night and everything working... to opening it the next day and getting an error message.... I've not installed anything or changed anything. The usual lines appear...loading aider chat, GPT 4....ctags 1024 thing... and then bang. So I'm not getting to the prompt basically. Strange!

**Comment by mcbgun** [comment]
I've just tried uninstalling an reinstalling and the same output appear:

`Aider v0.12.0
VSCode terminal detected, pretty output has been disabled.
Model: gpt-4
Git repo: ..\.git
Repo-map: universal-ctags using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\marc_\OneDrive\Desktop\python\Scripts\aider.exe\__main__.py", line 7, in <module>
  File "C:\Users\marc_\OneDrive\Desktop\python\Lib\site-packages\aider\main.py", line 518, in main
    coder.dirty_commit()
  File "C:\Users\marc_\OneDrive\Desktop\python\Lib\site-packages\aider\coders\base_coder.py", line 875, in dirty_commit
    if not self.repo.is_dirty():
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marc_\OneDrive\Desktop\python\Lib\site-packages\aider\repo.py", line 191, in is_dirty
    return self.repo.is_dirty()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marc_\OneDrive\Desktop\python\Lib\site-packages\git\repo\base.py", line 819, in is_dirty
    if osp.isfile(self.index.path) and len(self.git.diff("--cached", *default_args)):
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marc_\OneDrive\Desktop\python\Lib\site-packages\git\cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marc_\OneDrive\Desktop\python\Lib\site-packages\git\cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marc_\OneDrive\Desktop\python\Lib\site-packages\git\cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
  cmdline: git diff --cached --abbrev=40 --full-index --raw
  stderr: 'error: unknown option `cached'
usage: git diff --no-index [<options>] <path> <path>

Diff output format options
    -p, --patch           generate patch
    -s, --no-patch        suppress diff output
    -u                    generate patch
    -U, --unified[=<n>]   generate diffs with <n> lines context
    -W, --function-context
                          generate diffs with <n> lines context
    --raw                 generate the diff in raw format
    --patch-with-raw      synonym for '-p --raw'
    --patch-with-stat     synonym for '-p --stat'
    --numstat             machine friendly --stat
    --shortstat           output only the last line of --stat
    -X, --dirstat[=<param1,param2>...]
                          output the distribution of relative amount of changes for each sub-directory
    --cumulative          synonym for --dirstat=cumulative
    --dirstat-by-file[=<param1,param2>...]
                          synonym for --dirstat=files,param1,param2...
    --check               warn if changes introduce conflict markers or whitespace errors
    --summary             condensed summary such as creations, renames and mode changes
    --name-only           show only names of changed files
    --name-status         show only names and status of changed files
    --stat[=<width>[,<name-width>[,<count>]]]
                          generate diffstat
    --stat-width <width>  generate diffstat with a given width
    --stat-name-width <width>
                          generate diffstat with a given name width
    --stat-graph-width <width>
                          generate diffstat with a given graph width
    --stat-count <count>  generate diffstat with limited lines
    --compact-summary     generate compact summary in diffstat
    --binary              output a binary diff that can be applied
    --full-index          show full pre- and post-image object names on the "index" lines
    --color[=<when>]      show colored diff
    --ws-error-highlight <kind>
                          highlight whitespace errors in the 'context', 'old' or 'new' lines in the diff
    -z                    do not munge pathnames and use NULs as output field terminators in --raw or --numstat
    --abbrev[=<n>]        use <n> digits to display object names
    --src-prefix <prefix>
                          show the given source prefix instead of "a/"
    --dst-prefix <prefix>
                          show the given destination prefix instead of "b/"
    --line-prefix <prefix>
                          prepend an additional prefix to every line of output
    --no-prefix           do not show any source or destination prefix
    --default-prefix      use default prefixes a/ and b/
    --inter-hunk-context <n>
                          show context between diff hunks up to the specified number of lines
    --output-indicator-new <char>
                          specify the character to indicate a new line instead of '+'
    --output-indicator-old <char>
                          specify the character to indicate an old line instead of '-'
    --output-indicator-context <char>
                          specify the character to indicate a context instead of ' '

Diff rename options
    -B, --break-rewrites[=<n>[/<m>]]
                          break complete rewrite changes into pairs of delete and create
    -M, --find-renames[=<n>]
                          detect renames
    -D, --irreversible-delete
                          omit the preimage for deletes
    -C, --find-copies[=<n>]
                          detect copies
    --find-copies-harder  use unmodified files as source to find copies
    --no-renames          disable rename detection
    --rename-empty        use empty blobs as rename source
    --follow              continue listing the history of a file beyond renames
    -l <n>                prevent rename/copy detection if the number of rename/copy targets exceeds given limit

Diff algorithm options
    --minimal             produce the smallest possible diff
    -w, --ignore-all-space
                          ignore whitespace when comparing lines
    -b, --ignore-space-change
                          ignore changes in amount of whitespace
    --ignore-space-at-eol
                          ignore changes in whitespace at EOL
    --ignore-cr-at-eol    ignore carrier-return at the end of line
    --ignore-blank-lines  ignore changes whose lines are all blank
    -I, --ignore-matching-lines <regex>
                          ignore changes whose all lines match <regex>
    --indent-heuristic    heuristic to shift diff hunk boundaries for easy reading
    --patience            generate diff using the "patience diff" algorithm
    --histogram           generate diff using the "histogram diff" algorithm
    --diff-algorithm <algorithm>
                          choose a diff algorithm
    --anchored <text>     generate diff using the "anchored diff" algorithm
    --word-diff[=<mode>]  show word diff, using <mode> to delimit changed words
    --word-diff-regex <regex>
                          use <regex> to decide what a word is
    --color-words[=<regex>]
                          equivalent to --word-diff=color --word-diff-regex=<regex>
    --color-moved[=<mode>]
                          moved lines of code are colored differently
    --color-moved-ws <mode>
                          how white spaces are ignored in --color-moved

Other diff options
    --relative[=<prefix>]
                          when run from subdir, exclude changes outside and show relative paths
    -a, --text            treat all files as text
    -R                    swap two inputs, reverse the diff
    --exit-code           exit with 1 if there were differences, 0 otherwise
    --quiet               disable all output of the program
    --ext-diff            allow an external diff helper to be executed
    --textconv            run external text conversion filters when comparing binary files
    --ignore-submodules[=<when>]
                          ignore changes to submodules in the diff generation
    --submodule[=<format>]
                          specify how differences in submodules are shown
    --ita-invisible-in-index
                          hide 'git add -N' entries from the index
    --ita-visible-in-index
                          treat 'git add -N' entries as real in the index
    -S <string>           look for differences that change the number of occurrences of the specified string
    -G <regex>            look for differences that change the number of occurrences of the specified regex
    --pickaxe-all         show all changes in the changeset with -S or -G
    --pickaxe-regex       treat <string> in -S as extended POSIX regular expression
    -O <file>             control the order in which files appear in the output
    --rotate-to <path>    show the change in the specified path first
    --skip-to <path>      skip the output to the specified path
    --find-object <object-id>
                          look for differences that change the number of occurrences of the specified object
    --diff-filter [(A|C|D|M|R|T|U|X|B)...[*]]
                          select files by diff type
    --output <file>       output to a specific file`

**Comment by mcbgun** [comment]
I've used webChat gpt to try and solve this.... don't know why I didn't think of this before! 

The traceback you provided indicates that there's an issue with running a Python script that uses the GitPython library to interact with Git repositories. It seems that the error originates from the line if not self.repo.is_dirty(): in the base_coder.py file of the aider package. The specific error message you're encountering is 'error: unknown option cached'.The issue seems to be related to the use of the --cached option with the git diff command, which is being used within the GitPython library. The --cached option might not be recognized or supported in the context you're using it.You might want to check the versions of both GitPython and Git on your system to ensure compatibility and update them if necessary. Additionally, verify the usage of the --cached option in the specific context where it's being used within the library.If you need further assistance, feel free to provide more context about the code you're working with or the specific task you're trying to achieve.

I'll have a play around and see what I can do.

**Comment by paul-gauthier** [comment]
One thing you could try is to upgrade to the latest code on the main branch. It has some significant changes to the way aider uses git. There's a good chance that will resolve your problem.

You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by mcbgun** [comment]
Hi

So it fixed the getting to the prompt bit. But when I make changes to the code I get an error relating to git when trying to commit  changes so think I may need to reinstall that.

**Comment by paul-gauthier** [comment]
Can you share a screenshot or copy&paste the error output?

**Comment by berkeleymalagon** [comment]
> One thing you could try is to upgrade to the latest code on the main branch. It has some significant changes to the way aider uses git. There's a good chance that will resolve your problem.
> 
> You can get it by installing the latest version from github:
> 
> ```
> python -m pip install git+https://github.com/paul-gauthier/aider.git
> ```
> 
> If you have a chance to try it, let me know if it works better for you.

I had the same issue and confirming that this fixed it for me. Thanks ✊🏼

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
