### ISSUE TITLE
ctags failure on macOS

### ISSUE THREAD

**Issue by tmm1** [paul-gauthier/aider#21]
```
Using git repo: .git
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

If you would like aider to use ctags, you need to install universal-ctags. On a mac you can usually do that with `brew install universal-ctags`. Or see https://github.com/universal-ctags/ctags

You can also just ignore that error message and use aider without ctags. It's just checking for universal-ctags and finding the old ctags that is installed by default on OSX. I've pushed an update that hides that confusing error output. If you install the latest aider from GitHub it won't show that useless error message.

**Comment by tmm1** [comment]
ah right this is sounding vaguely [familiar now](https://github.com/tmm1/ctags.rb)

**Comment by tmm1** [comment]
fyi `symbex` is an interesting python-specific alternative to ctags: https://twitter.com/simonw/status/1679514977714208768?s=20

i've also been experimenting with [tree-sitter](https://dcreager.net/2021/06/getting-started-with-tree-sitter/) which can pull tags as well as precise source code locations across a number of languages
