### ISSUE TITLE
Ctags on windows?

### ISSUE THREAD

**Issue by Dougie777** [paul-gauthier/aider#213]
The only binary I could find is Exuberant Ctags.  Is this a linux only thing?

When I installed Exuberant Ctags it says:  

Repo-map: basic using 1024 tokens (ctags --version does not claim to be universal ctags)

Any help appreciated.

**Comment by MightEnlightenYou** [comment]
https://github.com/universal-ctags/ctags

**Comment by paul-gauthier** [comment]
Thanks for trying aider! Have you reviewed the installation instructions

https://aider.chat/docs/install.html#install-universal-ctags-optional
