### ISSUE TITLE
Unable to Use Voice Functionality for Aider installed with Brew

### ISSUE THREAD

**Issue by jbgrunewald** [paul-gauthier/aider#2132]
Greetings, 

First off, I'm really grateful for the effort and this tool! I'm happy to pitch in with any PRs related to this issue too.

I'm running Aider on MacOS, and installed via the brew package manager. I wanted to try out the new voice feature, which is available on the version I have installed. I followed the install instructions to install PortAudio via brew, but I'm still getting the below error.

```
Unable to import `sounddevice` and/or `soundfile`, is portaudio installed?
```

I'm wondering if this is because there's no dependency on the portaudio package in the brew cask, but I'm not really sure why it doesn't seem to reference the package correctly. 

Interestingly...oddly even, if I install aider with `python3 -m pip install -U --upgrade-strategy only-if-needed aider-chat` and run it with `python3 -m aider`, the voice functionality works. No additional installs required for portaudio, it simply references the package previously installed with brew correctly (python3 is also installed with brew in this case).

Anyway, I'm clearly not blocked on this issue, but it was surprising that the brew only install wouldn't work as expected.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html
