### ISSUE TITLE
Ctags and context

### ISSUE THREAD

**Issue by WeOneGuy** [paul-gauthier/aider#214]
Hello, i've tried to ask aider with large file. I downloaded ctags and with start i'm getting Repo-map: universal-ctags using 1024 tokens. But with this large file it just doesn't send anything

**Comment by WeOneGuy** [comment]
Of course 
![изображение](https://github.com/paul-gauthier/aider/assets/91134099/5fb70e49-11dc-4ae9-a4c2-fd27863f4b62)

**Comment by WeOneGuy** [comment]
I've installed ctags through choco
![изображение](https://github.com/paul-gauthier/aider/assets/91134099/6ce85d24-0397-4129-9d83-1ec3a6088b41)

**Comment by paul-gauthier** [comment]
It looks like you ran aider with `--map-tokes 4024` ? Because that is probably too many tokens for the repo map.

**Comment by WeOneGuy** [comment]
With map tokens 1024 it also not working

**Comment by paul-gauthier** [comment]
What version of aider are you using?

**Comment by WeOneGuy** [comment]
0.13.0

**Comment by WeOneGuy** [comment]
I think i also must to say, when i was installing aider i got vew error about incompatibilities of urllib3 versions

**Comment by WeOneGuy** [comment]
I've just deleted all libs from my pc and installed aider, without any errors, so maybe it will work now

**Comment by WeOneGuy** [comment]
It's not working 😞
