### ISSUE TITLE
Rate Limit Issue with Large Configuration Files

### ISSUE THREAD

**Issue by Murtazokh** [paul-gauthier/aider#215]
Hello,
 
 I've been utilising Aider and it's been working very well for the most part. However, I've recently encountered an issue when trying to integrate the system with large configuration files( .py file containing Json format ). Specifically, we seem to be hitting a rate limit of 40,000 tokens per minute, as indicated by the following error:
 
 `Rate limit reached for default-gpt-4 in organization [] on tokens per min. Limit: 40000 / min. Please try again in 1ms.`
 
 This persistently occurs when working with larger configuration files directly. The system advises a retry after a few seconds, but the issue keeps reoccurring due to the size of our data.
 
 A potential solution could be splitting our large configuration files into smaller chunks. However, I wanted to bring this to your attention as it might be an issue other users are experiencing or could experience in the future.
 
 Any guidance on how we might be able to resolve this issue or any proposed alternatives would be greatly appreciated. 
 
 Thank you.

**Comment by nkeilar** [comment]
Yes, I had the similar thing when I tried to load a rather large source code file. How does this currently handle a situation where a source code file is too large to be included in the context... is there a mechanism to handle this or is it something that would require a work around.

I would refactor the code, but its non trivial

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue. See issue #205 for more info. I'm going to close this as a dup.

Basically, you are adding too many files or too large files to the chat. They are bigger than the GPT context window.

Unfortunately if your single source file is bigger than the context window, it won't currently work with aider unless you can refactor it first. Stay tuned though, as the goal is for aider to be able to handle files like this eventually.
