### ISSUE TITLE
JSON copy message stop the program.

### ISSUE THREAD

**Issue by lvalics** [paul-gauthier/aider#217]
If I copy an message like a JSON structure, add a . and stop. I need to Ctrl+C to cancel and add without brackets.

**Comment by paul-gauthier** [comment]
Thanks for trying aider! Try checking out the tip section of the readme:

https://github.com/paul-gauthier/aider#tips

Specifically:

* Use Meta-ENTER (Esc+ENTER in some environments) to enter multiline chat messages. Or enter `{` alone on the first line to start a multiline message and `}` alone on the last line to end it.

**Comment by lvalics** [comment]
Thank you, I will try that out.
