### ISSUE TITLE
How to set up multiple projects?

### ISSUE THREAD

**Issue by JamesSKR** [paul-gauthier/aider#218]
I'd like to run aider for different projects, but it seems to want to remember the first project that I created. I can't figure out how to have it look at only files within a specific project directory and not at the directory it's installed at.

Is this possible?

If it's not, any workarounds?

If I'm a total newb, I apologize 🙏❤

**Comment by paul-gauthier** [comment]
Thanks for trying aider! Just make sure each project has it's own git repo. Don't put them all in the same repo.

**Comment by JamesSKR** [comment]
Ahh, got it, thank you.

**Comment by JamesSKR** [comment]
> Thanks for trying aider! Just make sure each project has it's own git repo. Don't put them all in the same repo.

Still not sure exactly how to do this.

I've initialized a new repo with current projects files, but when I use the /ls command - it's still showing the files from the first project.

**Comment by JamesSKR** [comment]
Figured it out.

/git init

then have to restart VScode and run aider again in the same directory. All good!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
