### ISSUE TITLE
add .env file

### ISSUE THREAD

**Issue by r1di** [paul-gauthier/aider#219]
Hi,

i would like to recommend adding a .env file where we can change the things like the api key and pretty please the base url to openai, with that change we could route the traffic to local llm for testing.

As an example AutoGPT, AgentGPT and many more do this.

here is an example of the file: https://github.com/reworkd/AgentGPT/blob/main/.env.example

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

Aider supports a yaml config file to specify all its settings. You can see all the settings and info about the yaml file by running `aider --help`. Here's the note at the end about the yaml file:

```
Args that start with '--' can also be set in a config file
(/.../.aider.conf.yml or
/.../.aider.conf.yml or specified via -c). The config file uses YAML
syntax and must represent a YAML 'mapping' (for details, see
http://learn.getgrav.org/advanced/yaml). In general, command-line values override
environment variables which override config file values which override defaults.
````
