### ISSUE TITLE
gpt35 diff parser gets confused when working with markdown files that use code fences

### ISSUE THREAD

**Issue by tmm1** [paul-gauthier/aider#22]
for example:

    README.md
    ```markdown
    # LongMem
    ...
    ```
    embedded code block in original readme
    ```
    ```

will end up with `new_lines = []` and replace my `README.md` with nothing.

**Comment by paul-gauthier** [comment]
Thanks for reporting this. This is an expected corner case. I have a solution in mind. Will update the issue when I've had a chance to test it out.

**Comment by paul-gauthier** [comment]
I just pushed a fix that should let aider edit files that contain triple-backtick fences. Let me know if you're able to give it a try and if it solves your issue. You'll need to install the latest from GitHub to pick up this change.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now. Feel free to re-open it if you're still having problems.
