### ISSUE TITLE
Cloudflare 502 Bad Gateway causes complete crash.  Cannot ctrl-c just frozen 

### ISSUE THREAD

**Issue by Dougie777** [paul-gauthier/aider#222]
Not sure how often this will occur but a failed cloudflare response completely crashed aider.  Here is the response that I got back.  It does not retry as it says it will in 0.9 seconds...  just frozen.

        if 'updated_at' in response.json:
            self.assertNotEqual(response.json['updated_at'], old_updated_at)
>>>>>>> updated
```

This change will use the `get` method to access the `updated_at` key in the `response.json` dictionary, which will return `None` if the key is not present. Then, it will only perform the assertion to check if `updated_at` has changed if the key is present in the response.
Applied edit to test_topic.py
HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
)
Retry in 0.9 seconds.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

Given that you were getting 502 gateway errors, it's likely that cloudflare and/or openai is having server errors. Probably aider made a request that just hung inside their servers. If you waited longer you probably would have seen a timeout error and then aider would have made another retry.

You can see that aider is properly handling and retrying the 502 when it says `Retry in 0.9 seconds`.

**Comment by Dougie777** [comment]
Have not got this problem again so closing....
