### ISSUE TITLE
Support for Code LLama  with up to 100,000 tokens of context. ?

### ISSUE THREAD

**Issue by marvin-hansen** [paul-gauthier/aider#224]
"The Code Llama models provide stable generations with up to 100,000 tokens of context. 
All models are trained on sequences of 16,000 tokens and show improvements on inputs with up to 100,000 tokens."

https://ai.meta.com/blog/code-llama-large-language-model-coding/

https://www.geeky-gadgets.com/how-to-install-code-llama-locally/

Given the high importance of larger context, I wonder if you open to support the new 
code LLama model?

**Comment by ryanpeach** [comment]
All models are supported using an openai compatible API server. Try running it with llama.cpp in server mode.

**Comment by paul-gauthier** [comment]
Please see issue #172 for discussion about other/local LLMs.
