### ISSUE TITLE
replacing peace of code

### ISSUE THREAD

**Issue by sawa25** [paul-gauthier/aider#225]
hello.  i am playing python 3.9.17.i am trying to solve a task based on the existing code by adopt it.
so i building code in file A.py, using classes and methods from file B.py.
what i am doing wrong?: 
when aider solving task by analyzing file B.py in repo - it making some changes and replacing very big peace of code with just string "# ... rest of the code ..." and save this file, so it is became unusable without this peace of code.
also it change file A.py the same way...

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

Are you able to share some specific details about what you are trying to do? Maybe paste some output from aider?

**Comment by sawa25** [comment]
thank you for this very interesting project!
as for the issue: i am trying to grab some class and methods from public python package with help of aider - so i fork a package, organize empty file ".py" and modifying it with aider. i notify, that enough often aider can kill all the code by changing a couple of string and writing "# ... rest of the code ...". it is possible to get backup from git, but it is not the optimal behaviour, because you need to compare to versions and to discover, what to change. more obviously is to keep the rest of code as is, if i am working under this only file ".py". may be i am asking aider wrong if i get this behaviour... will look

**Comment by paul-gauthier** [comment]
Are you using gpt-3.5 or 4?

**Comment by sawa25** [comment]
gpt-3.5

  
>Пятница, 8 сентября 2023, 19:30 +03:00 от paul-gauthier ***@***.***>:
> 
> 
>Are you using gpt-3.5 or 4?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <paul-gauthier/aider/issues/225/1711936424 @ github . com> 
 
 
Волков В.В.

**Comment by paul-gauthier** [comment]
Unfortunately, 3.5 is quite limited in its capabilities. I recommend trying it with GPT-4.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
