### ISSUE TITLE
aider immediately exits with message: "Analytics have been permanently disabled."

### ISSUE THREAD

**Issue by makeProjectGreatAgain** [paul-gauthier/aider#2253]
### Issue

Setting `analytics-disable: false` in `.aider.conf.yml` works as expected.
However, when `analytics-disable: true` is set, aider exits immediately with the message: "Analytics have been permanently disabled."

CLI input:
```
aider .
```
CLI output:
```
Analytics have been permanently disabled.
```

### Version and model info

aider 0.61.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You don't need to add that to your config. If you've run it once, then analytics are disabled forever.

**Comment by jendrusha** [comment]
I’m having the same issue, can’t get Adier to run. It exits immediately with the same message. This problem occurs with the last two versions, but version 0.60.0 works fine.

**Comment by paul-gauthier** [comment]
Again, don't add it to your config. Run `aider --analytics-disable` once and you're done. They are disabled forever.

**Comment by jendrusha** [comment]
The latest dev version solved the issue. I was able to upgrade with `python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git`, `aider` command failed with the same error message. BTW, I didn't have any analytics related settings in my config file.

**Comment by ariel-frischer** [comment]
Had the same issue also confirming: 
`python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git` 
fixed the issue for me I had previously set `export AIDER_ANALYTICS_DISABLE=1` in my shell environment and even after removing it, then reloading shell, `python -m aider` command would exit immediately.
