### ISSUE TITLE
Upcontributing RepoMap to Llama_index

### ISSUE THREAD

**Issue by ryanpeach** [paul-gauthier/aider#226]
I'm curious if the author would be willing to allow me to copy and modify the RepoMap code for contribution to llama_index. I feel like it's very useful in a lot of applications and people will expect to find it there. With attribution of course.

**Comment by paul-gauthier** [comment]
It's an interesting idea. The repomap concept is under heavy development right now, and about to undergo significant changes. So now is probably not the best time to try packaging it up for use elsewhere.

**Comment by ryanpeach** [comment]
I think my own PR to llama_index may be able to create a repo map. Closing.
