### ISSUE TITLE
Change color of the assistant output

### ISSUE THREAD

**Issue by shihabdider** [paul-gauthier/aider#23]
Maybe I'm missing something obvious, but how do you change the color of the assistant output? Currently it is a dark blue that is very difficult to see on my terminal:

![Screen Shot 2023-06-17 at 10 27 23 PM](https://github.com/paul-gauthier/aider/assets/12467607/f506852f-69a7-4f36-9a12-0518d8aea17c)

I can change the user input and the tool output but I don't see an option to change the assistant output.

**Comment by paul-gauthier** [comment]
Thanks for filing this issue. It has been on my todo list to add an option to change the assistant output color.

I added an arg for `--assistant-output-color`. If you install from github, you can pick up this change.

**Comment by paul-gauthier** [comment]
Closing this for now. Please let me know if the above doesn't help with your issue.
