### ISSUE TITLE
New CodeT/Reflexion commands: /test-command /test-first

### ISSUE THREAD

**Issue by mikeslattery** [paul-gauthier/aider#230]
Example usage:
```
/test-command npm run test
/test-run
/test-fix
/test-first on
```

It's been found that [CodeT and Reflexion dramatically improve](https://twitter.com/johnjnay/status/1639362071807549446)  GPT-4's coding ability.  The idea would be to automatically run tests after every codegen and to retry codegen on an error.  GPT Engineer uses a similar strategy, I think.   Example workflow:

1. Before doing a batch of work, user calls /test-command <cmd> and /test-first on.
2. User Enters a prompt
3. Aider checks if a test method exists for the change, and if not generates it.
4. Aider attempts to make the code change for the prompt
5. Aider runs test command.
6. If an error occurred, create a prompt from the error output to attempt to fix the code.  Test again.
7. If an error occurred again, loop back to step 4 up to 10 times.   Reset the change.  Increase temperature.
8. After final failure, AI evaluates all error messages to find the least bad solution and apply its code change with an error notification. 

/test-command <command> also runs the test to make sure there weren't any preexisting failing tests.

Full Reflexion requires a vector database for long term memory, so perhaps that's too much for this ticket.

**Comment by linvest21** [comment]
>
> Paul and Folks, what is the best course of action here?
>

ASSISTANT The total number of lines of code provided in the files you've
shared is approximately 500. This includes both actual code and comments.
Please note that this is an approximate count and the actual number may
vary slightly.
USER what is the program try to achieve
Rate limit reached for 10KTPM-200RPM in organization
org-KCQGI7foClX645hFtffKoGaK on tokens per min. Limit: 10000 / min. Please
try again in 6ms. Contact us through our help center at help.openai.com if
you continue to have issues.
Retry in 1.0 seconds.
Rate limit reached for 10KTPM-200RPM in organization
org-KCQGI7foClX645hFtffKoGaK on tokens per min. Limit: 10000 / min. Please
try again in 6ms. Contact us through our help center at help.openai.com if
you continue to have issues.
Retry in 1.5 seconds.

Thanks ahead. -DL

**Comment by paul-gauthier** [comment]
@linvest21 see #205.

**Comment by paul-gauthier** [comment]
@mikeslattery Thanks for trying aider and making this suggestion.

Have you tried working with the `/run` command? You could probably use it to do what you're suggesting.

**Comment by mikeslattery** [comment]
I'm sorry, I don't think I described the functionality well.  The idea is not to run a test once, but to run the test after every change, and to re-submit any prompt that causes a test to fail.  Example scenario:

1. `/test-command npm run test`
2. `/test-first on`  - The changes the system prompt to instruct GPT-4 to work in a TDD manner, by generating tests first, when possible.
3. Prompt: "create a library function in util/lib.ts to do a quicksort"   This results in the generation of a unit test and the implementation code, as instructed in the system prompt.
4. Test runs and fails.
5. Implementation is re-generated.
6. Test runs and fails.
7. Implementation is re-generated.
8. Test runs and fails.
9. Implementation is re-generated.
10. Test runs and succeeds.

I know this may seem out of scope of your simple project, but it would greatly increase success rate.

**Comment by paul-gauthier** [comment]
I'm not sure it's suitable for aider to build support for this specific style of coding, as it is a general "pair programming" tool. I think you can get pretty close using the `/run` command and the up-arrow to just quickly re-run the tests frequently.
