### ISSUE TITLE
Proposal: HIL (Human in the Loop) Planning

### ISSUE THREAD

**Issue by achristianson** [paul-gauthier/aider#233]
# The Problem

`aider` can do an impressively good job on its own, but like all current LLM-based agent systems, it often falls short. Many times, just like with human software developers, the problem can be caught and fixed early --in the planning stage.

# Proposed Solution

To solve this problem, we can apply a HIL (Human in the Loop) strategy to the planning phase of the `aider` agent. Here's what I believe the agent should do:

1. Accept user query
2. Have a brief conversation with the user to nail down requirements
3. Generate a plan
4. Have at least one automatic review pass of the plan (https://arxiv.org/abs/2303.11366)
5. Propose plan to user
6. Iterate on the plan based on user feedback
7. Now it's time to continue with the regular `aider` agent coding process.

# Caveats

## Don't Annoy Users

For some users, or some specific tasks, we'll want `aider` to jump in and get right to coding. Therefore, we should have a CLI flag to `aider` to enable/disable this feature, and possibly even have an input for how much we want `aider` to get feedback from the user.

# Conclusion

There are some tasks where I certainly would not mind `aider` interviewing me, and getting my feedback on the plan before continuing. Just like with most human endeavors, if we put a little more thought and energy into the planning part of the process, we can get drastically better results and avoid major pitfalls before they have a chance to occur.

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

Aider's prompt already directs GPT to ask questions to make sure it understand the goal if there's any ambiguity. I'm not sure a full structured sequence like you are proposing is in line with the design goals of aider which are to work collaboratively in a pair-programming style workflow.

**Comment by samuelmukoti** [comment]
Hi,

I'm say I did notice some improvements and aired is asking me more and more to clarify some seemingly ambiguous tasks.  

@paul-gauthier  don't know if you've had a look at MetaGPT and ChatDev  projects.  They seem to be addressing the issues mentioned above by employing multiple agents, MetaGPT has a product manager, architect, software engineer, tester etc.. and each agent take part in the development process and tend to produce much higher quality code.  Those projects lack the unique features that aider offers especially the way you can iteratively revise the code.  Am curious to hear your thoughts about it Paul?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by kripper** [comment]
Maybe Aider could be the coder agent of MetaGPT, or both projects could share a library for working with existing code (to detect file references, add/remove files from the session context, parse files from the output, check syntax errors, etc).

The MetaGPT team is just implementing incremental development.
I would love to see both projects sharing common code.
