### ISSUE TITLE
GPT Adding Comments Cause Errors When Updating Files

### ISSUE THREAD

**Issue by generallynonsensical** [paul-gauthier/aider#235]
Usage: aider via terminal in vscode, debian

Error: 

`The error `Malformed response #2, retrying...
InvalidEditBlock: edit failed!

<myfile> does not contain the *exact sequence* of HEAD lines you specified.
Try again.
DO NOT skip blank lines, comments, docstrings, etc!
The HEAD block needs to be EXACTLY the same as the lines in assets/js/output.js with nothing missing!

<myfile> does not contain these 2 exact lines in a row:

  // Step 1: <Comment on what needs changing>`
  
Issue: The error causes a loop where aider keeps trying to fix the issue with updating the file. This burns through tokens fast and is incredibly expensive as it keep generating the same old code, then the new code updates, etc. If it does not catch the issue on the second go around, it will keep trying.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

Unfortunately even GPT-4 gets confused sometimes. You can always safely halt it by hitting CONTROL-C and then tell it to stop doing whatever it's doing wrong.

Another thing to try is to add fewer files to the chat, so GPT can focus more on the specific files you want it to change.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
