### ISSUE TITLE
Rate limit reached for 10KTPM-200RPM in organization org-xlxSEXU9Luxu23sByyOjFXb2

### ISSUE THREAD

**Issue by Dougie777** [paul-gauthier/aider#236]
I have not even been using aider for a few hours.  Loaded it up to make some code changes and got this first prompt.  Usually it goes away but it is continuing.  I check my account and I am nowhere near my account limit.  Wondering if this is per organization which is hard coded in the app?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue. See issue #205 for more details.
