### ISSUE TITLE
Can't use OpenRouter

### ISSUE THREAD

**Issue by azazar** [paul-gauthier/aider#237]
I've tried using OpenRouter as describled in  https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc , but exits with an error.

    $ aider --openai-api-base=https://openrouter.ai/api/v1 --openai-api-key=sk-or-v1-code-removed --model=anthropic/claude-2
    Aider v0.13.0
    VSCode terminal detected, pretty output has been disabled.
    Traceback (most recent call last):
      File "/home/ftpaccess/miniconda3/bin/aider", line 8, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/home/ftpaccess/miniconda3/lib/python3.11/site-packages/aider/main.py", line 452, in main
        main_model = models.Model(args.model)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ftpaccess/miniconda3/lib/python3.11/site-packages/aider/models.py", line 31, in __init__
        raise ValueError(f"Unknown context window size for model: {name}")
    ValueError: Unknown context window size for model: anthropic/claude-2

**Comment by azazar** [comment]
Same error for `openai/gpt-4-32k`

**Comment by kit678** [comment]
I don't think the openrouter feature has been released yet. Probably should see in the next release if all is well. I saw in the FAQ's that lama 2 was acting funny, anthropic was still working fine according to @paul-gauthier

**Comment by akmalulkhairin** [comment]
@azazar OpenRouter should be available in the main branch.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by joshuavial** [comment]
@azazar I looked on to this today and the history summariser was working fine for me when using open router - can you confirm this is still broken for you and provide more details in #231 if it still is?

**Comment by jeffrey-l-turner** [comment]
FYI. I noticed that if I did an anaconda setup with Aider, I had this issue. On the other hand if I `pip install aider-chat` it worked fine.
