### ISSUE TITLE
Document the configuration better

### ISSUE THREAD

**Issue by skorokithakis** [paul-gauthier/aider#240]
I see that #121 is related, but it was closed with a different resolution than perhaps initially intended. My main issue right now is that I can't find any documentation on the config file. A short paragraph about its location and format would do.

My specific issue is that my config file is this:

```
openai-api-key: <my key>
no-git: true
```

Yet, even though the OpenAI API works, I can't get Aider to never use git. I've looked through the docs but I haven't found anything that can point me in the right direction about how to configure Aider, a short section would help.

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

I think you probably need to use:

```
openai-api-key: <my key>
git: false
```

**Comment by skorokithakis** [comment]
Thanks, that worked! Could it be documented somewhere perhaps?

**Comment by paul-gauthier** [comment]
The `aider --help` command includes some docs:

```
Args that start with '--' can also be set in a config file
(/Users/gauthier/Projects/grep-ast/.aider.conf.yml or
/Users/gauthier/.aider.conf.yml or specified via -c). The config file uses
YAML syntax and must represent a YAML 'mapping' (for details, see
http://learn.getgrav.org/advanced/yaml). In general, command-line values
override environment variables which override config file values which
override defaults.
```

**Comment by skorokithakis** [comment]
I did see that, but, strictly speaking, `--no-git` starts with `--` and didn't work when set in the config file.
