### ISSUE TITLE
ImportError: cannot import name '__version__' from 'aider'

### ISSUE THREAD

**Issue by azazar** [paul-gauthier/aider#242]
It just fails to start.

# Error
```
$ aider
Traceback (most recent call last):
  File "/home/if/anaconda3/bin/aider", line 5, in <module>
    from aider.main import main
  File "/home/if/anaconda3/lib/python3.11/site-packages/aider/main.py", line 10, in <module>
    from aider import __version__, models
ImportError: cannot import name '__version__' from 'aider' (/home/if/anaconda3/lib/python3.11/site-packages/aider/__init__.py)
```

# Environment
---- Operating System ----
Linux 42823.example.com 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
---- Python Version ----
Python 3.11.3
---- Anaconda Version ----
conda 23.7.2
---- Installed Python Packages ----
aider==0.2.4
aider-chat==0.13.0
---- End of Environment Information ----

**Comment by azazar** [comment]
I've reinstalled it and the problem is gone

**Comment by eriknomitch** [comment]
I was also getting this error. The solution was to uninstall the `aider` package (I probably installed that by mistake) then reinstall `aider-chat`.
