### ISSUE TITLE
Feature request: --todo add gpt comment to a todo list file

### ISSUE THREAD

**Issue by ebudmada** [paul-gauthier/aider#243]
Very great program Paul ! Thank you for the well done work! I see you have a lot of request, and your program is becoming more popular!

Anyway, as a satisfied user, it would be nice if i could add an option to the first command line, or option in command line to ask to save 'todo' in a file. Most of the time, when I ask gpt to produce code, it ends by saying: "Don't forget to do that". So sometimes I ask him to save it in a todo file, or I ask him to do it.

Thank for Aider it is really helping producing something out of gpt.

Have a nice day

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

I'm not sure I fully understand what you are requesting. But from the sounds of it, it is probably specific to the way you are working with aider/GPT and perhaps not appropriate as a general feature for aider.

**Comment by ebudmada** [comment]
Yeah, I see. What I'm talking about is more commonly happening when asking aider to produce big complete program. So Aider is providing incomplete code, commenting lines that should be field with more code. Then when aider made git-hub commit, just before that, he is stating not to forget to change this and that (commented lines in code), but sometimes aider is also saying not to forget to do things which are not in commented lines. Anyway is think creating complete app is out of the scope of aider for now. So may not be that helpful to add that feature, thank you!

**Comment by joshuavial** [comment]
Interesting - this makes me think more about a custom instructions feature. If you added something like "please prefix any comments about future work with TODO" to every prompt then maybe it would behave closer to what you want?
