### ISSUE TITLE
Is it possible to document benchmark

### ISSUE THREAD

**Issue by ystoll** [paul-gauthier/aider#245]
Hi @paul-gauthier, thank you for such wonderful job with aider! I am currently trying to run the benchmark tests but the problem is that there is no documentation on how to do it. Specifically, there is no doc on the arguments of benchmark.py and on how environment variables should be set. Documentation on the tree structure of python exercises would also be nice.  Would it be possible to add some ?

**Comment by paul-gauthier** [comment]
Here you go!

https://github.com/paul-gauthier/aider/tree/main/benchmark

**Comment by ystoll** [comment]
Thanks @paul-gauthier !
