### ISSUE TITLE
idea: allow gpt to execute code before commit and self-correct code (like open-interpreter)

### ISSUE THREAD

**Issue by ebudmada** [paul-gauthier/aider#246]
There is a new tool, open-interpreter, which enable gpt to access terminal and execute command and script. I believe Aider would be the even more robust using this technology. Aider could execute the code before commit, and if not working, correct the code. Does not look simple to do but this would add a lot of success to benchmark, i guess.

Thank you for your great work all

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

The `/run` command may do what you're asking about. Maybe give that a try and let me know if it helps.

https://aider.chat/docs/commands.html

**Comment by ebudmada** [comment]
When i use the /run command, i get no result. But in another terminal I get error:

new_file.py                                                                                                                                                                                                     
> /run python \new_file.py                                                                                                                                                                                      


(nothing happend i waited a long time)
^C again to exit

(base) PS C:\Users\ebudm\Documents\script> python .\new_file.py
Currently scraping: _type result of refer a friend terms and conditions -template
An error occurred while processing _type: Invalid URL '_type': No scheme supplied. Perhaps you meant https://_type?
Do you want to continue? (y/n): n

**Comment by ebudmada** [comment]
looks like there is something different, if i use the same command (running on the other terminal) i get: 
> /run python .\new_file.py                                                                                                                                                                                     

python: can't open file 'C:\\Users\\ebudm\\Documents\\script\\.new_file.py': [Errno 2] No such file or directory #.new_file.py does not exist for sure, the file is new_file.py

> /run python new_file.py : nothing happend also

**Comment by ebudmada** [comment]
ok yeah great the /run command did the trick. Very nice. I don't know what happened, looks like there was dependencies not satisfied in my conda env, but without error message. But i did run the script in an another terminal with that conda env... Anyway now it is working.

Great feature Paul sorry i did'nt find it myself
