### ISSUE TITLE
Better diffs

### ISSUE THREAD

**Issue by samhaaf** [paul-gauthier/aider#248]
Hey!

First off, great work on aider. It's inspiring and very useful! I was actually working on a fork of it for voice-to-code and then you released exactly that!

The one issue I'm having is just how slow the updates can be, primarily because aider writes out the whole file in the left side of the diff. 

I've noticed that if we're only updating one function, aider usually writes a diff on just that function. However, if you are writing anything in the highest scope of the file, like defining a new function or class, then the whole file gets updated in the diff. 

I think that if aider knows where it's going to put a new function in a file, that it should just write a few lines before where the edit is being inserted. This could be accomplished by explicitly saying which lines are being replaced in the diff, or you could determine a relative offset by matching line hashes. 

Happy to PR a solution on this if you wouldn't mind thinking it over and telling me how you'd like to approach it.

**Comment by joshuavial** [comment]
Are you talking about behaviour using gpt-3.5 or gpt-4 as they use quite different formats for their output

I've been frustrated with large diffs from gpt-4 a lot - mostly from the extra time it takes before getting to code I can review. My work around has been to add a "please create a minimal diff" which makes it smaller, but also more fragile. I recall seeing a comment in discord or a previous issue along the lines of "the more code in the wrapping diff, the higher the quality of the new code written" but I haven't dug into it much.

I've also found that writing small files, small functions and giving aider small changes (practices I like anyway) becomes more important when working with aider - as well as having good test coverage etc.

I have wondered about a "custom instructions" sort of feature where a user could include some instructions in the config (so could be applied on a per project, or global level) which might be a more general way to have impact on this issue.

**Comment by samhaaf** [comment]
Yep, I was talking about gpt-4.

One solution I was imagining was to take advantage of the c-tags. Maybe aider could output the location that he wants to replace, instead of writing out the head of the diff. It could output a custom format like:

```python#diff[20,25]
...content...
```

which would replace lines 20 through 25 with the new content. This could be rendered in the terminal as an actual diff all at once, instead of one token at a time.

**Comment by samhaaf** [comment]
"the more code in the wrapping diff, the higher the quality of the new code written"

To that end, aider could split the output generation into two completions. 

First completion: would do logical reasoning and select the location of the diff

Locally: #diff[l,k] gets replaced with the content from the file.

Second completion: is given the updated response of the first completion and asked to complete the output. 

Downsides:
- Twice as many requests with the same full context, so more API costs (doesn't bother me)
- ctags don't store the end of a function definition, only the beginning. It might require custom code to read the files and find the end of the function definition. But maybe somebody else put out a repo for this. 
- Might be difficult to constrain gpt-4 to write an incomplete response. I have a tough time constraining it to do much simpler things. It tends to ignore instructions in the presence of complex problems.

**Comment by mikehearn** [comment]
It's worth noting that how hard you get hit by this depends on the language. In something like Kotlin it's very easy to pull code out into separate files or functions using the IDE, and that doesn't require updating imports when it's in the same package, so keeping files small and top level definitions minimal is quite easy. In Python it's not quite so easy, but I wonder if the better path isn't to slightly alter how scripting languages load code, rather than try to beat GPT into being more concise.

**Comment by tino** [comment]
However, the diff aider outputs to the console doesn't need to be the same as the content that is received from GPT. Why not run `git diff current_file tmp_file_from_gpt` and display that?

**Comment by paul-gauthier** [comment]
> However, the diff aider outputs to the console doesn't need to be the same as the content that is received from GPT. Why not run `git diff current_file tmp_file_from_gpt` and display that? 

You can see actual diffs with `--show-diffs` switch.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by Slach** [comment]
could we use side-by-side approach to view diffs?

i mean integrate something like
https://github.com/dandavison/delta ?

**Comment by materemias** [comment]
@paul-gauthier I just came to this topic, and didn't know if necrobumping or opening a new issue would be the right way to ask this question, but I really like the idea that @Slach proposed. side-by-side diffs would make changes easier to review, especially with larger chunks of delta.  Do you have something like that on your roadmap?
