### ISSUE TITLE
Request: Automatically create unit test from command line

### ISSUE THREAD

**Issue by leonj1** [paul-gauthier/aider#2490]
### Issue

```
find . -type f -name “*.go” | while read -r x; do echo "Create unit test for file. Then run 'make test' and fix any errors." | aider --sonnet --dark-mode --no-cache-prompts --no-auto-commit --no-suggest-shell-commands --yes --file "$x"; done
```
I would love to be able to execute a command like this in a repo to recursively create unit tests for the entire repo. Running make test would give aider a chance to capture the output and iterate X number of times until the unit test is working. Is this within scope for aider?

### Version and model info

latest

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/scripting.html

Just use `--message "do the thing"` not stdin for the message.

**Comment by leonj1** [comment]
Wow! thanks for the prompt response! Happy Thanksgiving!
