### ISSUE TITLE
Feature request: Separate API keys for GPT/Whisper

### ISSUE THREAD

**Issue by asifjahmed** [paul-gauthier/aider#255]
Hey @paul-gauthier! Really wonderful tool you've whipped up here! The concept of using git repos as the basis and making edits using diffs is truly out-of-the-box thinking, and I applaud you for this enormous contribution!

I have a small request, based on my use case currently where I am using a custom Azure instance of `gpt-4-32k` (Yes it is available if you set up an Azure account and request the access!!) yet the API keys do not necessarily work with other models. If `gpt-3.5-turbo-16k` were needed, for example, a different set of Azure parameters (namely '`deployment-id`') would need to change. But in addition to that, Azure APIs do not include `whisper` - so the lovely voice features of aider do not work when using Azure API keys.

It would be lovely if the `.aider.conf.yaml` config file could support different configurable params per model, so that I can continue to use my own Azure setup for `gpt-4-32k` but otherwise use my OpenAI account for `gpt-3.5-turbo-16k` or `whisper`.

Best Regards,
-asifjahmed

**Comment by olafgeibig** [comment]
I second this.

**Comment by olivMertens** [comment]
yeah Azure api include whisper in preview

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue!

One approach might be to make a different config.yml file for each model, and then specify which config file to use via `--config`.

Not sure that will help with voice/whisper, if you need a different deployment id to connect to gpt versus whisper in azure. But it should make it easy to do `aider --config gpt-4.yml` and `aider --config gpt-4-32k.yml`, etc.

**Comment by paul-gauthier** [comment]
I think you can do this now since we've switched to litellm for connecting to models. 

https://aider.chat/docs/llms.html


I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by loflet** [comment]
@paul-gauthier I am finding it difficult to configure aider with Azure OpenAI for voice. I have added the API key for Azure OpenAI and AzureAI in the env variable but still when I run /voice command, it records it but as soon as I press ENTER it throws error. Pasted the error's last line below

`openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}`

What am I missing here?
