### ISSUE TITLE
gpt-3.5-turbo-instruct

### ISSUE THREAD

**Issue by luberion** [paul-gauthier/aider#256]
Hello, can we use this model for aider? I got this error when I pass in parameter "--model gpt-3.5-turbo-instruct":

`openai.error.InvalidRequestError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?
`

I am using the latest version of aider:  v0.14.0

**Comment by paul-gauthier** [comment]
Supporting this instruct model would require new prompting and a entirely new non-chat based use of the openai api.

Is there a reason you wish to use it versus the normal chatgpt-3.5-turbo model?

**Comment by NerdGGuy** [comment]
https://twitter.com/GrantSlatton/status/1703913578036904431

This tweet shows evidence that chess performs better with the instruct model makes me wonder if gpt-3.5-turbo-instruct would perform better with diffs then gpt-3.5-turbo. I can report my rough attempts at making chatgpt-3.5-turbo with shell prompting were unsuccessful but I do wonder if shell prompting would work for the instruct model 🤔.

roughly speaking....

User input: "Fix a bug in the calculate function"
```
> ctags blah
blah blah blah
> cat app/calculator.py
blah blah blah
> git show
commit 2a79ef7b1c4a88362dbb8e08e2de8a55339a7b1c (HEAD -> main)
Author: John Doe <john.doe@example.com>
Date: Thu Sep 28 14:20:15 2023 +0000

    Fix a bug in the calculate function

diff --git a/app/calculator.py b/app/calculator.py
index 78a1d59..53b6f8b 100644
```

Completion:
```
--- a/app/calculator.py
+++ b/app/calculator.py
@@ -21,7 +21,7 @@ def calculate(a, b, operator):
     elif operator == '-':
         return a - b
     elif operator == '*':
-        return a * b
+        return a * b if b is not None else 0  # Fixed a bug where b could be None
     elif operator == '/':
         if b == 0:
             raise ValueError('Cannot divide by zero!')
```

**Comment by NerdGGuy** [comment]
@paul-gauthier I've tried this in playground using gpt-3.5-turbo-instruct.

prompt:
```
> ctags -x app/calculator.py
calculate     function    1 app/calculator.py def calculate(a, b, operator):

> cat app/calculator.py
def calculate(a, b, operator):
    if operator == '+':
        return a + b
    elif operator == '-':
        return a - b
    elif operator == '*':
        return a * b
    elif operator == '/':
        if b == 0:
            raise ValueError('Cannot divide by zero!')
        return a / b

> git show
commit 2a79ef7b1c4a88362dbb8e08e2de8a55339a7b1c (HEAD -> main)
Author: John Doe <john.doe@example.com>
Date: Thu Sep 28 14:20:15 2023 +0000

    Fix a bug in the calculate function

diff --git
```

completion:
```
 a/app/calculator.py b/app/calculator.py
index 63e8b2f..53c882d 100644
--- a/app/calculator.py
+++ b/app/calculator.py
@@ -6,7 +6,7 @@ def calculate(a, b, operator):
         return a - b
     elif operator == '*':
         return a * b
-    elif operator == '/':
+    elif operator == '/' and b != 0:
         return a / b
     else:
-        print('Invalid operator')
+        raise ValueError('Invalid operator')

print(calculate(5, 0, '/'))
- Invalid operator

print(calculate(5, 2, '/'))
- 2.5
```

**Comment by paul-gauthier** [comment]
I spent some time experimenting with prompts for `gpt-3.5-turbo-instruct` and benchmarking the results. Unfortunately, I wasn't able to get results that were any better than the normal chat based `gpt-3.5-turbo` models. In fact, the overall results were worse.

Given that, it doesn't seem worth the effort to build official support for the 3.5 instruct model.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
