### ISSUE TITLE
problem starting aider

### ISSUE THREAD

**Issue by rreben** [paul-gauthier/aider#258]
When starting aider on an existing repo. I geht the following output.

```sh
(venv) rupertrebentisch@MacBook-Air-von-Rupert cocoai % aider                    
Aider v0.14.0
Model: gpt-4
Git repo: .git
Repo-map: basic using 1024 tokens (error running universal-ctags: Command '['ctags', '--version']' returned non-zero exit status 1.)
Use /help to see in-chat commands, run with --help to see cmd line args
```

I can run ctags on the command line. I get:

```sh
ctags --version
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFTaduwvx] [-f tagsfile] file ...
```

I am on a mac. Using MacOS 13.5.2 (ventura)

**Comment by paul-gauthier** [comment]
Please see the installation instructions. It appears that you have not installed the correct version of Universal C-Tags. The one that comes by default on macOS does not work with aider. 

https://aider.chat/docs/install.html

**Comment by rreben** [comment]
Thanks! I somehow missed the installation guide. I guess that will solve the issue. By the way: pre installed MacOS c-tags needs a licence confirmation (error code 69). ... Just in case someone has these kind of issue. Thanks again for taking time for a comment.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
