### ISSUE TITLE
A way to ask the LLM to not edit import lines

### ISSUE THREAD

**Issue by mikehearn** [paul-gauthier/aider#259]
In languages like Java or Kotlin the list of imports at the top can get quite long. When GPT decides to edit those, it wastes a lot of tokens and often doesn't get it quite right. Fortunately it doesn't matter because IntelliJ can auto-fix missing imports in most cases, so this isn't usually necessary. It'd be nice if I could tell an aider session not to do that, but every time automatically.

**Comment by paul-gauthier** [comment]
I'm not sure aider could support this sort of functionality natively. I am reluctant to give it instructions to not bother doing the best possible job at coding.

This is something you could maybe do with custom instructions, if they get added (see #249).
