### ISSUE TITLE
Malformed ORIGINAL/UPDATE blocks, retrying...

### ISSUE THREAD

**Issue by raine** [paul-gauthier/aider#26]
I seem to be getting a ton of this and it just keeps repeating. To the point that this tool is not that useful.

Is this normal?

**Comment by paul-gauthier** [comment]
Thanks for trying aider, sorry to hear you're having troubles.

Which model are you using? 3.5 or 4? 3.5 has a lot of trouble following system prompt directions. If you have access to gpt-4, it is much more reliable.

If you're able to paste some output here, I'm happy to help try and debug more.

**Comment by raine** [comment]
Ah sorry, I'm on 3.5-turbo, should've included that. No access to GPT4 yet unfortunately.

**Comment by paul-gauthier** [comment]
I just release v0.7.0 which should reduce the chances of 3.5 getting stuck in a loop of improperly formatted responses. If you have a chance to try it, let me know if it helps with your issues.

**Comment by raine** [comment]
Thank you. I just tried it out.

Are you able to explain this behavior? The previous version at least rendered a progress bar and you could see something happening but now it seems to get stuck like that.

Video: https://share.cleanshot.com/lpvxGlnT (File too big for GitHub)

**Comment by paul-gauthier** [comment]
Thanks for reporting that. I believe the problem is because there is a triple-backtick block in the file you are editing. This was also reported by someone else in issue #22. Aider uses triple backtick fences to communicate with GPT, so there's an "escaping" issue here.

I am working on the solution for this now. I'll update both tickets when the fix is merged.

**Comment by paul-gauthier** [comment]
I just pushed a fix that should let aider edit files that contain triple-backtick fences. Let me know if you're able to give it a try and if it solves your issue. You'll need to install the latest from GitHub to pick up this change.

**Comment by raine** [comment]
I tried this same test case now with the latest master and it works perfectly.

```diff
commit 27597e71730ed4bb7065f62d0b0aa079acf924bf
Author: Raine Virta <raine.virta@gmail.com>
Date:   Mon Jun 26 19:40:33 2023 +0300

    aider: Added license section to the bottom of the `README.md`.
    
    # Context:
    USER: add license section at the bottom of the `README.md`
    ASSISTANT: No changes are needed.

diff --git a/README.md b/README.md
index 988101e..c4cfb9e 100644
--- a/README.md
+++ b/README.md
@@ -47,3 +47,7 @@ nmap <leader>tr <Plug>(testonly-reset)
 
 Feel free to open an issue if you encounter any problems or have improvements to
 suggest.
+
+## License
+
+This project is licensed under the [MIT License](LICENSE).
```

I'll close this for now. Thank you.
