### ISSUE TITLE
Default to /voice if the user presses enter on an empty prompt

### ISSUE THREAD

**Issue by mikehearn** [paul-gauthier/aider#260]
It's incredible how lazy aider makes me. Typing `/vo` suddenly seems like an unreasonable effort when AI is doing so much heavy lifting already. Right now pressing enter by itself does nothing useful, just repeats the prompt. If it recorded audio instead, that'd save me an extra three keystrokes each time! :)

**Comment by NerdGGuy** [comment]
On this topic it'd be amazing if somehow a vscode shortcut could trigger voice. @mikehearn you use vscode? Maybe Aider could write an extension for this for us 😂  (e.g. types /vo into the aider prompt 🤷?)?

**Comment by mikehearn** [comment]
No, I use IntelliJ. An IntelliJ plugin for aider would be cool, but not really necessary right now for me.

**Comment by mikehearn** [comment]
That said, I do actually have my IntelliJ hooked up with the Whisper API so I can dictate straight into an editing buffer. It's not really a plugin though, more like a custom hack, and I don't use it all that much.

**Comment by NerdGGuy** [comment]
OMG, 6 cents per 10mins? I'd always on that sucker waiting for a keyword 😂!!!

**Comment by jacksenechal** [comment]
Yeah I like the listening option, perhaps with a timeout after N minutes of inactivity to save $. Or you could wire up a small local voice model that listens for the keyword, and then triggers the `/voice` command.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
