### ISSUE TITLE
Azure Open AI GPT-4 not recognized since 9.22

### ISSUE THREAD

**Issue by olafgeibig** [paul-gauthier/aider#261]
Today I noticed that aider has problems with Azure's GPT-4. On startup aider says:
```
Aider v0.14.0
Setting openai.api_base=https://xxx.openai.azure.com
Setting openai.api_type=azure
Setting openai.api_version=2023-05-15
Setting openai.api_deployment_id=gpt-4
API key does not support gpt-4, falling back to gpt-3.5-turbo-16k
Model: gpt-3.5-turbo-16k
Git repo: .git
Repo-map: disabled
```

I'm sure it was working some days ago. I think even yesterday (September 21), because yesterday I couldn't add a file because my 8k GPT-4 context was exceeded. My Azure OpenAI service still works well with other locally installed software.

aider 0.14.0
MacOS 13.2
Python 3.10.10
 ~/.aider.conf.yml:
```
openai-api-type: azure
openai-api-key: xxx
openai-api-base: https://xxx.openai.azure.com
openai-api-version: 2023-05-15
openai-api-deployment-id: gpt-4
model: gpt-4
no-auto-commits: true
```
Edit: more aider output

**Comment by paul-gauthier** [comment]
@salilcbi  @tjroamer Are either of you still using aider with azure? Are you having problems since 9/22?

**Comment by olafgeibig** [comment]
I found some time to debug the problem. I think Microsoft renamed the model-ids that are returned by ```openai.Model.list()``. Now the response looks like this:
```
['ada', 'babbage', 'babbage-002', 'curie', 'davinci', 'davinci-002', 'gpt-35-turbo-0301', 'gpt-35-turbo-0613', 'gpt-35-turbo-instruct-0914', 'gpt-35-turbo-16k-0613', 'gpt-35-turbo-gso', 'gpt-4-0314', 'gpt-4-0613', 'gpt-4-32k-0314', 'gpt-4-32k-0613', 'text-davinci-003', 'code-cushman-001', 'text-similarity-ada-001', 'text-similarity-babbage-001', 'text-similarity-curie-001', 'text-similarity-davinci-001', 'text-search-ada-doc-001', 'text-search-ada-query-001', 'text-search-babbage-doc-001', 'text-search-babbage-query-001', 'text-search-curie-doc-001', 'text-search-curie-query-001', 'text-search-davinci-doc-001', 'text-search-davinci-query-001', 'code-search-ada-code-001', 'code-search-ada-text-001', 'code-search-babbage-code-001', 'code-search-babbage-text-001', 'text-embedding-ada-002', 'text-embedding-ada-002-2']
```
I don't know how the model list before but maybe they added the release date at the end? I'm on an Azure OpenAI instance in Sweden Central, maybe it's a different response somewhere else.

**Comment by paul-gauthier** [comment]
Have you tried running aider with `--model gpt-4-32k-0613`?

**Comment by paul-gauthier** [comment]
If you run aider with a model that isn't supported by your api/key, it will now list the supported models an error message. This should make it faster/easier to work around model naming weirdness like you're describing.

https://github.com/paul-gauthier/aider/commit/545f10551edf3ddfbf8b91575b4c283b10df5087

**Comment by olafgeibig** [comment]
Good solution 👍
