### ISSUE TITLE
During initial ctags scan, binary files yield errors

### ISSUE THREAD

**Issue by mikehearn** [paul-gauthier/aider#262]
The progress bar gets messed up as it scans in my main repository because there are binary files that are parsed as UTF-8, and then when that yields an error it's printed to the console.

Example:

```
/Users/mike/Hydraulic/product/open/guidebook/docs/configs/digicert-one-certificate-alias.png: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by paul-gauthier** [comment]
The progress bar only appears during the first initial scan of the repo. Seems like a small corner case that invalid files disturb it.

Probably the best way to address this would be at add an explicit allow/deny list of file extensions to avoid even attempting to scan things like images.

**Comment by mikehearn** [comment]
Why not just suppress errors so they don't print, or print them only to a logfile?

**Comment by paul-gauthier** [comment]
The errors are important for users to see, to they know if some of their source code files are using a different encoding than aider is using.

**Comment by paul-gauthier** [comment]
The main branch of the repo now has support for an `.aiderignore` file. If you are working with repos that contain images and other non-text files, you could add `*.png` etc to the `.aiderignore` file.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by mikehearn** [comment]
Nice, thanks! I'll try it out soon. 

I wonder if it could include .gitignore, as that tends to already identify irrelevant non-source files.

**Comment by paul-gauthier** [comment]
The purpose of the `.gitignore` file is to make sure git doesn't consider *new* files that match when doing `git status` and refuses to add them with `git add`.

Files that match which are *already* in the repo are still part of the repo. So it would be odd for aider to use `.gitignore` to additionally mean "but ignore them for aider purposes". That's what `.aiderignore` is for.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
