### ISSUE TITLE
Crashing when old code=new code

### ISSUE THREAD

**Issue by azazar** [paul-gauthier/aider#264]
Aider is crashing when diff doesn't include any actual modifications (old code is the same as new code)

    <source>php
    some_file.php
    <<<<<<< HEAD
    some content
    =======
    some content
    >>>>>>> updated
    </source>
    
    Please confirm this change.
     --no-verify -- /home/some/path.php
      stdout: 'On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working directory clean'
    
Version:

    $ aider --version
    aider 0.14.0

**Comment by azazar** [comment]
BTW. It happens quite often.

**Comment by paul-gauthier** [comment]
Thanks for reporting this issue. I'll work on resolving it.

**Comment by paul-gauthier** [comment]
Are you seeing this problem with gpt-4? I can't recall ever seeing it create a no-op change. I have also failed to trick it into making such an edit response.

**Comment by paul-gauthier** [comment]
The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by azazar** [comment]
Yes, I'm using GPT-4. Thanks.
