### ISSUE TITLE
Update exception #1

### ISSUE THREAD

**Issue by mel11691** [paul-gauthier/aider#265]
I had a problem where Aider wouldn't update my code until I put in a trivial change which allowed it to commit that change before it made it's own edits. This is probably because I committed some changes manually or something. I tried to fix this problem by deleting all my aider files in my workspace and deleting my manual ctags file in the workspace as well. Rerunning Aider didn't fix it, only my workaround by adding a letter to a comment fixed it.

I'm just curious why this happened, I'm a complete noobie and I'm using Chat GPT to help teach me how to code.

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

Sorry, but I'm not sure I understand your question. Can you share a screenshot or some chat logs from `.aider.chat.history.md` that more clearly show the problem you are trying to describe?

**Comment by mel11691** [comment]
![Screenshot 2023-09-28 143842](https://github.com/paul-gauthier/aider/assets/141965913/ea7c5d3b-4aa7-45df-ad45-ab53573bc047)

I would guess I committed a change manually and Aider thought it had to commit that previous change before makings it's edits. To fix it I made some trivial change and left it uncommitted, which Aider then committed, and then proceeded to make it's actual edits.

**Comment by paul-gauthier** [comment]
Are you using `aider` directly or via some other tool? The output in your screenshot contains things that aider doesn't output and is missing other things that aider does output (like the actual Update Exception).

**Comment by mel11691** [comment]
I'm using the console in VSC

**Comment by paul-gauthier** [comment]
I'm finding it hard to understand what is going on here. When I run aider inside a VS Code terminal window, it looks nothing like your screenshot. It is the standard aider colors, without line numbering on the left column and without special highlighting and notations on the `>>> HEAD` and `<<< updated` lines. Etc.

Whatever environment you are using is somehow not outputting the actual "update exception" details, which aider emits using a standard `print()` call.

Are you running aider from the command line inside a VS Code terminal window? Can you should me the invocation along with the aider version and other information it prints at launch?

**Comment by mel11691** [comment]
I took a screenshot of the .aider.chat.history.md file in VSC. I'm not sure of how to get the chat history in the terminal. I have used /clear a bunch of times since then, if that matters.

**Comment by paul-gauthier** [comment]
Can you show me the status lines that aider prints when you initially launch it? They should look something like this:

```
$ aider
Aider v0.14.1-dev
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
```

**Comment by mel11691** [comment]
![Screenshot 2023-09-30 131446](https://github.com/paul-gauthier/aider/assets/141965913/9d3755e7-cbc4-49ac-ae43-bd8e620b575f)

I just got the update notification so I'll update to the latest, but I did have the problem on 0.14.0.

**Comment by mel11691** [comment]
I think it has something to do with the working branch of the code, which is something I don't really understand. Like i said I'm very green. When I opened VSC I had a working branch of my file open for some reason I'm not sure of and just my file as is open. I xed out of my working branch and made some changes to my files including the file aider needed to make changes to. I again got an update exception #1. I think Aider wants to commit some change from the working branch, but can't. I'm not really sure.

**Comment by paul-gauthier** [comment]
Thanks for the additional information. I see why your output looked different than what I was expecting. You were sharing a screenshot of the `.aider.chat.history.md` file opened up in a VS Code editor window.

Unfortunately, the actual "update exception" information isn't logged to that file. Next time you see it happen live in your VS Code terminal, see if you can grab a screenshot of that.

That said, GPT-4 sometimes messes up no matter how strongly aider prompts it. If you get repeated updated exceptions, it can help to `/clear` old conversation history and to only `/add` the files that are needed for the specific change you are working on (and not a bunch of unrelated files). This helps GPT focus on your task.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
