### ISSUE TITLE
I built an API into the $20/mo UI - Need help integrating.

### ISSUE THREAD

**Issue by Dougie777** [paul-gauthier/aider#268]
I am paying $20 a month and using very little of those requests.  I built an API that will post a query and get a response and exposes an API compatible with openai's chat completions endpoint (/v1/chat/completions).  I have a few questions:
1) Where in aider's code can the url be modified (to hit localhost instead)
2) Does /clear start a new chat?  I need to understand /add and /drop if there is anything special I need to do.
3) Anything else you think I might need to know.

Thanks so much!!
Doug

**Comment by hchaudhary1** [comment]
Interesting... well, thats definitely shady stuff, you could get banned from OpenAI access. But if you still want to, you can just do this:

If your localhost can emulate the openrouter API (which should be easy), then just do this:
https://aider.chat/docs/faq.html#accessing-other-llms-with-openrouter
and change the base URL to localhost.

btw, what library allows you to re-use the WebUI session?

**Comment by Dougie777** [comment]
There's a lot of different options.  I'm using puppeteer.  It works well.  I'm not planning to abuse it but just use it to utilize some of the queries on paying $20 a month for.

**Comment by hchaudhary1** [comment]
I see, here is a better explanation:
https://github.com/danny-avila/LibreChat/blob/main/docs/install/apis_and_tokens.md#chatgpt-free-access-token

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
