### ISSUE TITLE
getting aider + ctags installed on OSX

### ISSUE THREAD

**Issue by mberman84** [paul-gauthier/aider#27]
Hi i'm trying to figure out how to use ctags with aider but it's not clear from the instructions. 

I cloned aider, installed it, and then cloned ctags and put it in the aider directory. i also installed that. it seems to be available because the command "aider" works but it doesn't see the universal ctags. am I doing something wrong? 

i navigate to my project directory and type "aider" and it loads up, and I get this:

```
(aider) ➜  pricer git:(main) ✗ aider .
Model: gpt-4
Git repo: .git
Repo-map: basic using 1024 tokens (universal-ctags not found)
Use /help to see in-chat commands.
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider. Sorry to hear you're having trouble getting ctags to work with it.

You need to install ctags, not just clone the universal-ctags repo. On OSX, you can usually install it with `brew uninstall universal-ctags`.

Here is some more info from the universal-ctags repo:

https://github.com/universal-ctags/homebrew-universal-ctags

Basically, you're in business if you can run `ctags --version` from your shell and get output like this:

```
$ ctags --version
Universal Ctags 6.0.0, Copyright (C) 2015-2022 Universal Ctags Team
...
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now. Feel free to re-open it if you're still having problems.
