### ISSUE TITLE
Adding a file that is already added triggers commit even if commits are disabled.

### ISSUE THREAD

**Issue by petebytes** [paul-gauthier/aider#275]
I am starting aider with --no-dirty-commits --no-auto-commits --model gpt-4

When adding /add a file that was already added triggers a commit.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

I can't reproduce the problem you are describing. What version of aider are you using? Can you share a screenshot or paste the output of aider where you are seeing unexpected behavior?

If you *really* don't want aider to do anything with git, you can use `--no-git`.
