### ISSUE TITLE
Keep getting error: Your branch is ahead of 'origin/new' by 6 commits.   (use "git push" to publish your local commits)  nothing to commit, working tree clean' Update exception #1, retrying...

### ISSUE THREAD

**Issue by cranyy** [paul-gauthier/aider#277]
I havent checked out this project for a while, so i might be a bit behind and be doing something wrong, but now anytime i try to do anything i keep getting Your branch is ahead of 'origin/new' by 6 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean'

Despite the fact that it makes many, multiple changes beforehand. If i try /undo it says no changes have been made with aider, even though they absolutely have (these 6 commits are all aider). I tried dirty-commit, auto-commit, no-auto-commit basically every one of the prerun commands and i keep getting the same error over and over, unless i actually git push, which i dont want to do as my repo is connected remotely. Even when i set it up locally to push there it still gives me the same error. 

So my question is how do i force it to just commit locally and have it stop bugging me that its ahead of the origin/new, like it was before.
Forgive me if this has been answered or is a stupid/newbie question, I just need some clarity.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

Can you show me a screenshot or paste the actual output of aider that results in this error? Also, what version of aider are you using?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
