### ISSUE TITLE
Git submodules are not included in the repo-map

### ISSUE THREAD

**Issue by zapaz** [paul-gauthier/aider#281]
Got an error with `repomap` when using  a git submodule library,   on that line :

https://github.com/paul-gauthier/aider/blob/22eb344192f665ea43ebffc51993ba8e2beb6486/aider/repomap.py#L309

`aider`suggests this fix 

```

> Repo-map can't include  .../src/lib/zzzzzz
To handle the case where the file is a symbolic link to a file in a git submodule, we can use the os.path.realpath() function. This function follows the symbolic link and returns the actual file path.

Here's how we can modify the code:

 for fname in fnames:
     real_path = os.path.realpath(fname)
     if not Path(real_path).is_file():
         self.io.tool_error(f"Repo-map can't include {fname}")
         continue

This code will follow the symbolic link and check if the actual file exists. If the file doesn't exist, it will print an error message and continue with the next file.
```

not a python expert, so don't know if it's ok ?

**Comment by NickEdinburgh** [comment]
I came here with two bugs, this being the first. The fix worked for me. So thanks for sharing.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and reporting this issue.

Can you share a screenshot or more of the aider output when this happens?

Is it just printing a warning and otherwise proceeding? If so, then I wouldn't worry about this. It's just going to leave the flagged file(s) out of the repository map.

If it's crashing aider, please let me know.

**Comment by paul-gauthier** [comment]
Looks like aider simply refuses to index the content in the submodule for the repo map. It prints a warning, but otherwise proceeds fine.

I actually think this is probably reasonable behavior. It's not clear that you want aider to pull in the (potentially very large amount of) code from submodules. But I'm open to input on this if you have a specific need.

```
$ git init
Initialized empty Git repository in .../tmp/submodule/.git/

$ touch hello.txt
$ ga hello.txt
$ gc -m init
[main (root-commit) a9db670] init
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 hello.txt

$ git submodule add https://github.com/paul-gauthier/grep-ast
Cloning into '.../tmp/submodule/grep-ast'...
remote: Enumerating objects: 315, done.
remote: Counting objects: 100% (315/315), done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 315 (delta 199), reused 245 (delta 129), pack-reused 0
Receiving objects: 100% (315/315), 84.68 KiB | 788.00 KiB/s, done.
Resolving deltas: 100% (199/199), done.

$ gc -a -m 'added submodule'
[main 3e36b47] added submodule
 2 files changed, 4 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 grep-ast

$ aider
Aider v0.14.2-dev
Add .aider* to .gitignore (recommended)? y
Added .aider* to .gitignore
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
─────────────────────────────────────────────────────────
> hi

 33%|███████████████████▋                                       | 1/3 [00:00<00:00,  2.95it/s]
Repo-map can't include .../tmp/submodule/grep-ast
100%|███████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  8.24it/s]

Hello! How can I assist you today?

─────────────────────────────────────────────────────────
>
```

**Comment by paul-gauthier** [comment]
I added logic so it will only warn you once about files that can't be included in the repo map. 
The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by zapaz** [comment]
Works like a charm!

 Merci beaucoup d' aider ;-)

**Comment by twilwa** [comment]
I'd be interested to, if I have the file open in my editor (nvim, vscode, etc) for context management, be able to add a single file from a submodule to the context window -- it would help a lot for web3 projects using Foundry especially (imported contracts are all managed by submodules or npm, but might need to be referenced by another contract that's not behind a .gitignore'd folder.

**Comment by paul-gauthier** [comment]
You can /read a file into the context from anywhere in the file system.

**Comment by twilwa** [comment]
musta missed that in the docs, thx!

**Comment by CAFxX** [comment]
> I actually think this is probably reasonable behavior. It's not clear that you want aider to pull in the (potentially very large amount of) code from submodules. But I'm open to input on this if you have a specific need.

Having the submodules indexed in the repomap would actually be really helpful when dealing with dependencies that are either not public or not widely used, so the LLM may not be very well aware of which specific APIs exist, what their signatures are, and how they are supposed to be used.

This is probably also true of any dependency (regardless of it being a submodule, or just a reference in a requirements.txt, go.mod, pom.xml, or anything else).
