### ISSUE TITLE
Add .aiderignore to tell aider to ignore portions of a git repo

### ISSUE THREAD

**Issue by NickEdinburgh** [paul-gauthier/aider#282]
I've only recently got aider set up, and it was working wonderfully. But suddenly I'm getting this bug in response to every request. I understand it's not uncommon in Python, with lots of potential fixes. But wondering if there's a known problem with a good way to fix it in Aider?

Thanks for the brilliant project!

/code/autogen/autogen_env/lib/python3.10/site-packages/matplotlib/backends/qt_editor/__pycache__/figureoptions.cpython-310.pyc: 'utf-8' codec can't 
decode byte 0xe9 in position 9: invalid continuation byte
Use --encoding to set the unicode encoding.

**Comment by heresandyboy** [comment]
I am getting the same error, though this is for a react application that uses yarn 3 as the package manager. It seems to be trying to read every single package from my yarn cache, the errors below are truncated, but it repeats for many packages, all zip files.

Anyone know how to stop it from reading my yarn cache?

``` bash
packages\chat-client\src\App.tsx packages\chat-client\src\index.tsx                                                                                                                                            
> /add packages\chat-client\src\apm.ts                                                                                                                                                                         

Added C:\code\devops\ai-consumer-chatbot\packages\chat-client\src\apm.ts to the chat
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────packages\chat-client\src\App.tsx packages\chat-client\src\apm.ts packages\chat-client\src\index.tsx                                                                                                            
> /add packages\chat-client\src\Page.tsx                                                                                                                                                                       

Added C:\code\devops\ai-consumer-chatbot\packages\chat-client\src\Page.tsx to the chat
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
packages\chat-client\src\App.tsx packages\chat-client\src\Page.tsx packages\chat-client\src\apm.ts packages\chat-client\src\index.tsx                                                                          
> I am trying to instrument @elastic/apm-rum into my application, I want to be able to trace the user interaction through my application, I have apm setup in my index.ts I ideally want to start a transactio 
n and have all other transactions and spans appear nested under the main one so I can see the path the user took through my application, how can I do this?                                                    

C:\code\devops\ai-consumer-chatbot\.yarn\cache\@discoveryjs-json-ext-npm-0.5.7-fe04af1f31-2176d301cc.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
Use --encoding to set the unicode encoding.
C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-apm-rum-core-npm-5.20.0-987b963c2b-6268bfacfc.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
Use --encoding to set the unicode encoding.
C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-apm-rum-npm-5.15.0-14b33c8cd8-5c94e9e5f9.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
Use --encoding to set the unicode encoding.
C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-apm-rum-react-npm-2.0.1-f354dc3ae9-15b50bb72d.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
Use --encoding to set the unicode encoding.
C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-ecs-helpers-npm-1.1.0-1f2d977a44-8f64e86fe3.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
Use --encoding to set the unicode encoding.
C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-ecs-pino-format-npm-1.3.0-e28c038f16-1543b80b84.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
Use --encoding to set the unicode encoding.
```

**Comment by NickEdinburgh** [comment]
> I am getting the same error, though this is for a react application that uses yarn 3 as the package manager. It seems to be trying to read every single package from my yarn cache, the errors below are truncated, but it repeats for many packages, all zip files.
> 
> Anyone know how to stop it from reading my yarn cache?
> 
> ```shell
> packages\chat-client\src\App.tsx packages\chat-client\src\index.tsx                                                                                                                                            
> > /add packages\chat-client\src\apm.ts                                                                                                                                                                         
> 
> Added C:\code\devops\ai-consumer-chatbot\packages\chat-client\src\apm.ts to the chat
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────packages\chat-client\src\App.tsx packages\chat-client\src\apm.ts packages\chat-client\src\index.tsx                                                                                                            
> > /add packages\chat-client\src\Page.tsx                                                                                                                                                                       
> 
> Added C:\code\devops\ai-consumer-chatbot\packages\chat-client\src\Page.tsx to the chat
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> packages\chat-client\src\App.tsx packages\chat-client\src\Page.tsx packages\chat-client\src\apm.ts packages\chat-client\src\index.tsx                                                                          
> > I am trying to instrument @elastic/apm-rum into my application, I want to be able to trace the user interaction through my application, I have apm setup in my index.ts I ideally want to start a transactio 
> n and have all other transactions and spans appear nested under the main one so I can see the path the user took through my application, how can I do this?                                                    
> 
> C:\code\devops\ai-consumer-chatbot\.yarn\cache\@discoveryjs-json-ext-npm-0.5.7-fe04af1f31-2176d301cc.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
> Use --encoding to set the unicode encoding.
> C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-apm-rum-core-npm-5.20.0-987b963c2b-6268bfacfc.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
> Use --encoding to set the unicode encoding.
> C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-apm-rum-npm-5.15.0-14b33c8cd8-5c94e9e5f9.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
> Use --encoding to set the unicode encoding.
> C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-apm-rum-react-npm-2.0.1-f354dc3ae9-15b50bb72d.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
> Use --encoding to set the unicode encoding.
> C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-ecs-helpers-npm-1.1.0-1f2d977a44-8f64e86fe3.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
> Use --encoding to set the unicode encoding.
> C:\code\devops\ai-consumer-chatbot\.yarn\cache\@elastic-ecs-pino-format-npm-1.3.0-e28c038f16-1543b80b84.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
> Use --encoding to set the unicode encoding.
> ```

I tracked it down to using 'git add .' so my workaround was to add only the functional directories I want to work with. Are you on MacOS? It might be specific to that. It would be better to resolve this at a code level, but right now I'm too busy to get sidetracked.

**Comment by heresandyboy** [comment]
> 
> I tracked it down to using 'git add .' so my workaround was to add only the functional directories I want to work with. Are you on MacOS? It might be specific to that. It would be better to resolve this at a code level, but right now I'm too busy to get sidetracked.

I'm on Windows, both 10 and 11 on two separate PCs. Can you elaborate on where you 'add only the functional directories'? I am using aider's `/add` to only add 3 files. My project is a mono reo with yarn workspace with a react client, api and other bits.

If I need to do something with git, can you explain what you mean?

**Comment by paul-gauthier** [comment]
Generally speaking, it's a bad idea to do `git add .` as it will literally add every file in every subdirectory to your git repository. That's usually not what you want, as there are often config, cache, virtual environments, installed packages, etc that will get put into git that way.

That said, it appears that yarn actually encourages people to commit parts of the the `.yarn` subdir to git. Which is an unexpected stance to take.

If you didn't mean/want to have `.yarn` in git, you could do something like the below commands. But it's your repo, so you should understand the commands below and their potential dangers and implications before running them.

```
git rm -r --cached .yarn
echo .yarn >> .gitignore
```

Also, the errors like these are harmless. Aider is just warning you that it can't read the file as text. These warning messages are annoying, but nothing bad is happening.

```
C:\code\devops\ai-consumer-chatbot\.yarn\cache\@discoveryjs-json-ext-npm-0.5.7-fe04af1f31-2176d301cc.zip: 'utf-8' codec can't decode byte 0xae in position 11: invalid start byte
Use --encoding to set the unicode encoding.
```

**Comment by paul-gauthier** [comment]
A possible enhancement would be to add support for an `.aiderignore` file, to tell aider to ignore parts of the git repo.

**Comment by NickEdinburgh** [comment]
Your .gitignore suggestion makes good sense. It would be ideal if it could default to excluding cruft each of the main OSs create from the off. The workaround of avoiding 'git add .' is okay now I've worked that out. And accepted it's harmless. But until I found the workaround it made aider useless as it would take 3-4 minutes per query to print out a wall of red warnings like this: 
![image](https://github.com/paul-gauthier/aider/assets/99728162/40305930-201a-4fab-8cd3-7e1309f46a36)

**Comment by heresandyboy** [comment]
Yes .aiderignore would be ideal. With regards to yarn caches being checked in, we are trying it out for a few months, idea is to speed up buillds, limit the amount of yarn installs and take advantage of decoupling our pipelines from npm registry without having to mirror.

**Comment by paul-gauthier** [comment]
Ok, I added an `.aiderignore` file. Put it in the root of the git repo, along side `.gitignore`. It should take all the normal git type wildcards, etc. It uses [pathspec](https://python-path-specification.readthedocs.io/en/latest/readme.html#tutorial) to parse the ignore file and test for matches.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by NickEdinburgh** [comment]
I installed the new version and tried a 'git add .' again to see what happened. So it's MUCH better. Now fewer than 400 lines of this stuff... which only took 2-3 seconds to run through rather than 2-3 minutes previously. I'll probably revert to adding specified dirs for neatness. But this absolutely makes it functional now for me even the other way.

Thanks!

/Users/...path.../.DS_Store: 'utf-8' codec can't decode byte 0xff in position 1068: invalid start byte
Use --encoding to set the unicode encoding.
/Users/...path.../.git copy/index: 'utf-8' codec can't decode byte 0xae in position 15: invalid start byte
Use --encoding to set the unicode encoding.
/Users/...path.../.git copy/objects/01/433bca2ac76590c48fabfee8d69d7b223f48bb: 'utf-8' codec can't decode byte 0xca in position 3: invalid 
continuation byte
Use --encoding to set the unicode encoding.
/Users/...path.../.git copy/objects/02/0474aa923091bc7ad0462838bf85f7983f9593: 'utf-8' codec can't decode byte 0xed in position 2: invalid 
continuation byte
Use --encoding to set the unicode encoding.
/Users/...path.../.git copy/objects/02/2afc5482154baf91364b10be3d4fae0e2e3df3: 'utf-8' codec can't decode byte 0xc9 in position 20: invalid 
continuation byte
Use --encoding to set the unicode encoding.
/Users/...path.../.git copy/objects/03/6180500278e4fd98b6bc41477988c29be11149: 'utf-8' codec can't decode bytes in position 2-3: invalid 
continuation byte
Use --encoding to set the unicode encoding.
