### ISSUE TITLE
Feature request: commit from cli without opening chat

### ISSUE THREAD

**Issue by samhaaf-pondurance** [paul-gauthier/aider#283]
The utility of writing a commit summary and making a commit is useful outside of the context of a chat. 

Something like `aider commit`, `aider /commit` or `aider --commit`.

**Comment by paul-gauthier** [comment]
This is a great idea, I'll keep it in mind. Thanks.

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by samhaaf-pondurance** [comment]
This is great! I woke up this morning to people talking about it on X :)
