### ISSUE TITLE
Visual Studio 2022 Integration.

### ISSUE THREAD

**Issue by tonymacx86PRO** [paul-gauthier/aider#29]
When i tried on my C# project, aider with gpt-4 and the repo map, I encountered many problems:
1. I don't understand how the confirmation system works because i write "y" or "yes" and it replies more times to confirm the confirmation but i don't understand how
2. When i come across to edit anything it can't edit existing files in my C# project from anaconda powershell WITH admin perms.
3. It have created some files but the Visual Studio recognizes as external files and doesn't add it to the project and I need to do it manually.
4. When it created classes, it have been created without using's, why?
5. Finally, the formating of the files where wrong, I needed to make in every file the using's import and shift tab every class created by aider.
Why this happening?

**Comment by tonymacx86PRO** [comment]
When i start to use the app I manage to deal with every problem but not with the external file problem. Maybe if is possible make a implementation.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and for letting me know about the issues you are having.

I'm glad to hear you solved most of your issues already!

Can you help me understand the remaining problem about external files? It sounds like you are having trouble getting Visual Studio to add "external files" to VS project? Is that right?

Did aider create the external files?

**Comment by tonymacx86PRO** [comment]
Hi! Yes, I have trouble with external files, so when a app that is not visual studio creates a file, for the visual studio I need to add to the project source manually, I am myself idk how to do it, but maybe there is a way to create an file from external source and import it automatically! You understand, what I mean?

**Comment by tonymacx86PRO** [comment]
Maybe this is known as including to project, I give some example about it that maked GPT-4 so you understand maybe what I want (It's for C# project like mine)
```python
import os
import glob
import xml.etree.ElementTree as ET

# Replace with the path to your Visual Studio project file
project_file = 'path/to/your/project.csproj'

# Replace with the path to the folder with external files
external_files_folder = 'path/to/external/files/folder'

# Read the source project file
tree = ET.parse(project_file)
root = tree.getroot()

# Find the section with Compile elements
compile_group = None

for item_group in root.findall("./{*}ItemGroup"):
    if item_group.find("./{*}Compile") is not None:
        compile_group = item_group
        break

if compile_group is None:
    compile_group = ET.SubElement(root, 'ItemGroup')

# Add external files with the .cs extension to the Compile group
for ext in ('*.cs',):
    for file in glob.glob(os.path.join(external_files_folder, ext)):
        file_relative_path = os.path.relpath(file, os.path.dirname(project_file))
        file_element = ET.SubElement(compile_group, 'Compile', {'Include': file_relative_path})

# Save changes to the project file
tree.write(project_file)
```

**Comment by paul-gauthier** [comment]
You could try asking aider to do this for you. Add the csproj file to the chat, and then ask it to add the new files to your project. You should probably make sure you have a backup of the csproj file before you attempt this though.

**Comment by tonymacx86PRO** [comment]
Ah ok! Thanks! I appreciate for your help 👍

**Comment by tonymacx86PRO** [comment]
I will mark it as closed
