### ISSUE TITLE
Dry Run

### ISSUE THREAD

**Issue by mel11691** [paul-gauthier/aider#290]
How do you apply an edit if you run Aider in dry run mode?

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

The purpose of the `--dry-run` switch is to make sure aider does NOT modify your files. If you want it to edit your files, do not use that switch.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
