### ISSUE TITLE
Add /rollback command

### ISSUE THREAD

**Issue by mweichert** [paul-gauthier/aider#291]
Sometimes when aider makes some changes, it messes up. It would be great if we could just add /rollback or /revert command and the codebase is reverted using a hard reset.

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

I think the `/undo` command solve your problem?

https://aider.chat/docs/commands.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
