### ISSUE TITLE
Feature Request: Trello card data Ingestion

### ISSUE THREAD

**Issue by cagatayozgur** [paul-gauthier/aider#294]
Feature Request: Trello card data Ingestion
Example implementation:

The user could say:
/trello [ticketID or URL]

contents of the Trello card is added to the context to provide more color to the issue at hand.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I'm not sure aider would add support for adding trello tickets specifically. But I expect aider will want to support pasting in a url to some external website, like a ticketing system or API docs, etc.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
