### ISSUE TITLE
Trying to install aider in a virtual environment with Anaconda seems like it causes a bunch of dependency issues

### ISSUE THREAD

**Issue by basilbowman** [paul-gauthier/aider#299]
_As you can tell by the title, I'm very much a novice - I would very easily believe that this is my fault/misunderstanding (and if anyone wanted to educate me with a couple of terms to google, I'd appreciate the heck out of it!)_

All that being said -  trying to install aider inside of an Anaconda venv causes what looks like a bunch of dependency issues.

Here's the example errors I'm seeing - I think most of these are caused by simpleaichat?

In a bone stock basic Anaconda venv with Python 3.11, running the command: python -m pip install aider-chat

Gives me these errors:

simpleaichat 0.2.2 requires httpx>=0.24.1, but you have httpx 0.23.0 which is incompatible.
simpleaichat 0.2.2 requires orjson>=3.9.0, but you have orjson 3.8.8 which is incompatible.
simpleaichat 0.2.2 requires pydantic>=2.0, but you have pydantic 1.10.12 which is incompatible.
simpleaichat 0.2.2 requires python-dotenv>=1.0.0, but you have python-dotenv 0.21.0 which is incompatible.
simpleaichat 0.2.2 requires rich>=13.4.1, but you have rich 13.3.5 which is incompatible.

I was able to solve this by manually updating (except with rich, which I was required to then roll back to 13.3.5 instead of the most current 13.6).

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I don't think I understand why `python -m pip install aider-chat` is printing error messages about `simpleaichat`. Aider and it's dependencies do not require `simpleaichat`. 

A vanilla anaconda docker image lets me install aider just fine:

```
$ docker pull continuumio/anaconda3
Using default tag: latest
latest: Pulling from continuumio/anaconda3
7dbc1adf280e: Pull complete
ad2a2c08a78a: Pull complete
Digest: sha256:b60631636309ed40a3bc01edc326128aeadfa50622da76052abc9ef2e1d3c8cc
Status: Downloaded newer image for continuumio/anaconda3:latest
docker.io/continuumio/anaconda3:latest

$ docker run -i -t continuumio/anaconda3 /bin/bash

(base) root@05f2055216a8:/# apt-get update
...

(base) root@05f2055216a8:/# apt-get install -y build-essential
...

(base) root@37abbd9becd1:/# conda create -n myenv python=3.11

(base) root@37abbd9becd1:/# conda activate myenv

(myenv) root@37abbd9becd1:/# python -m pip install aider-chat
...
Successfully installed CFFI-1.16.0 GitPython-3.1.31 PyYAML-6.0.1 Pygments-2.15.1 aider-chat-0.16.0 aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 attrs-23.1.0 backoff-2.2.1 certifi-2023.5.7 charset-normalizer-3.1.0 configargparse-1.7 diskcache-5.6.1 frozenlist-1.3.3 gitdb-4.0.10 grep-ast-0.2.0 idna-3.4 iniconfig-2.0.0 jsonschema-4.17.3 markdown-it-py-2.2.0 mdurl-0.1.2 multidict-6.0.4 networkx-3.1 numpy-1.24.3 openai-0.27.6 packaging-23.2 pathspec-0.11.2 pluggy-1.3.0 prompt-toolkit-3.0.38 pycparser-2.21 pyrsistent-0.20.0 pytest-7.3.1 regex-2023.10.3 requests-2.30.0 rich-13.3.5 scipy-1.10.1 smmap-5.0.0 sounddevice-0.4.6 soundfile-0.12.1 tiktoken-0.4.0 tqdm-4.65.0 tree-sitter-0.20.1 tree-sitter-languages-1.8.0 urllib3-2.0.2 wcwidth-0.2.6 yarl-1.9.2

(myenv) root@37abbd9becd1:/# aider --version
aider 0.16.0
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open if you can provide a way to reproduce the issue.
