### ISSUE TITLE
Color for diff output

### ISSUE THREAD

**Issue by kwmiebach** [paul-gauthier/aider#30]
I understand I can set colors for various texts like so:

`aider --user-input-color blue --tool-output-color blue --tool-error-color blue -assistant-output-color blue`

I tried various combinations and it changes the chat colors. I also found some code in the io.py, for example `InputOutput.__init__`

But I would very much like to be able to change the color of the diff output. I could apply this in my own fork or locally.

As you can see in the image, in my terminal the diff appears in a light color, maybe inverted:

![image](https://github.com/paul-gauthier/aider/assets/6737928/5f5057fb-e3be-4506-accd-48d5a9e92972)

Could you pleace point me to the code, where the inversion or the light color happens. Or if this is done by some library, where does the oputput happen?

Thank you very much!

**Comment by paul-gauthier** [comment]
Thanks for trying aider. Sorry to hear you're having trouble with the colors in the diff highlighting. 

You're correct. There isn't currently a way to change the colors inside the diffs. I've been meaning to add a switch that could control light mode and dark mode. I'll update this issue once I've had a chance to implement that.

**Comment by kwmiebach** [comment]
I am preparing a pull request

![image](https://github.com/paul-gauthier/aider/assets/6737928/ee6a3610-0a3c-44cc-8677-3eeb171a3b0b)

**Comment by paul-gauthier** [comment]
Okay, that sounds great. Thank you. 

That commit above was actually for another issue, not this one. I put the wrong issue number in the commit message.

**Comment by kwmiebach** [comment]
I've opened PR #49 and welcome any feedback. I admit my understanding of the codebase is limited, so please suggest any necessary adjustments or improvements.

Thanks

**Comment by kwmiebach** [comment]
This was implemented via merge. Closing.
