### ISSUE TITLE
ERROR: Failed building wheel for tree-sitter

### ISSUE THREAD

**Issue by jslomkowski** [paul-gauthier/aider#301]
When trying to install Aider 0.16.0 using pip on Windows or wsl or docker miniconda3 image, I get:

`ERROR: Failed building wheel for tree-sitter`

I am using conda environment and python==3.11.5
On macOS it works perfectly
I don't get this with Aider 0.15.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I just made some changes to the main branch which streamline the installation of aider. They make the tree-sitter install set simpler.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by jslomkowski** [comment]
It works. Thanks
