### ISSUE TITLE
C# support on MacOS

### ISSUE THREAD

**Issue by mikeplavsky** [paul-gauthier/aider#303]
When working with a C# repo, I am encountering this issue on MacOS with Aider v0.16 and Aider v0.16.2-dev.

`/tokens` crashes with: 
...
AttributeError: dlsym(0x81045c40, tree_sitter_c-sharp): symbol not found

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This is a bug in the C# tree-sitter language module, which is hard-crashing the entire process. I've been worried these might crop up. I will look into isolating all the tree-sitter code outside the main aider process.

**Comment by nevercast** [comment]
Amusing to see this reported 37 minutes ago, as I encountered this at almost exactly the same time. I'm on Windows 10, rather than MacOS. So, it's not specific to the operating system. Python 3.11.5. Aider v0.16.1.

**Comment by mikeplavsky** [comment]
@nevercast, It could be the same issue. Here is the stack trace; it appears that Aider is attempting to get the language from tree-sitter: 

  File "/opt/homebrew/lib/python3.11/site-packages/aider/repomap.py", line 134, in get_tags_raw
    language = get_language(lang)
               ^^^^^^^^^^^^^^^^^^
  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
  File "/opt/homebrew/lib/python3.11/site-packages/tree_sitter/__init__.py", line 83, in __init__
    language_function = getattr(self.lib, "tree_sitter_%s" % name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: dlsym(0x808ac5a0, tree_sitter_c-sharp): symbol not found

**Comment by nevercast** [comment]
Ah, looks like it is the same after all. Unless @paul-gauthier would rather keep the issues separate (OS?) I'd be happy to dedupe mine (#304) into this story also.

**Comment by paul-gauthier** [comment]
This does appear to be a dup of #304. The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by mikeplavsky** [comment]
Confirmed, fixed. Thank you! Awesome tool 👍
