### ISSUE TITLE
Consider more robust UTF encoding support.

### ISSUE THREAD

**Issue by nevercast** [paul-gauthier/aider#305]
Hi,

Python 3.11.5
Aider v0.16.2

Sometimes files in my working directory might have an encoding that is not UTF-8, more often than not, this is a file generated by an external tool/build step. While I prefer to only ever use UTF-8 files, I can't always control the output of other tools. 

Unfortunately, Aider does not always gracefully handle non UTF-8 files, instead it crashes. Here is a log of running `/tokens`:

```
> /tokens                                                                   
DEBUG: Loaded native library in 0.0010411739349365234 seconds
DEBUG: Got function tree_sitter_javascript successfully
DEBUG: A file with a BOM for UTF-16 was detected and is about to be read by Aider.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "Python311\Scripts\aider.exe\__main__.py", line 7, in <module>
  File "Python311\Lib\site-packages\aider\main.py", line 564, in main
    coder.run()
  File "Python311\Lib\site-packages\aider\coders\base_coder.py", line 319, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\coders\base_coder.py", line 398, in run_loop
    return self.commands.run(inp)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\commands.py", line 73, in run
    return self.do_run(matching_commands[0][1:], rest_inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\commands.py", line 51, in do_run
    return cmd_method(args)
           ^^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\commands.py", line 126, in cmd_tokens
    repo_content = self.coder.repo_map.get_repo_map(self.coder.abs_fnames, other_files)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    files_listing = self.get_ranked_tags_map(chat_files, other_files)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\repomap.py", line 349, in get_ranked_tags_map
    ranked_tags = self.get_ranked_tags(chat_fnames, other_fnames)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\repomap.py", line 260, in get_ranked_tags
    tags = list(self.get_tags(fname, rel_fname))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\repomap.py", line 124, in get_tags
    data = list(self.get_tags_raw(fname, rel_fname))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\repomap.py", line 168, in get_tags_raw
    code = f.read().decode(self.io.encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
```

The file was a `references.js` file, and it's encoding is UTF-16-LE. I was able to modify RepoMap to detect this and warn me with a debug. I can also change the encoding that I read the file with based on this detection, and that seems to work fine (very lightly tested).

Detect UTF-16:
```py
first_two_bytes = Path(fname).read_bytes()[:2]
  if first_two_bytes == b'\xff\xfe' or first_two_bytes == b'\xfe\xff':
    code_file_encoding = 'utf-16'
```

Optionally override the encoding when reading as text:
```py
code_file_encoding = self.io.encoding
first_two_bytes = Path(fname).read_bytes()[:2]
if first_two_bytes == b'\xff\xfe' or first_two_bytes == b'\xfe\xff':
    code_file_encoding = 'utf-16'
code = Path(fname).read_text(encoding=code_file_encoding)
tree = parser.parse(bytes(code, "utf-8"))
```

I'm not suggesting these as robust fixes, just as examples of the issue I'm facing. 

If Aider didn't crash, it would be less of a problem. However, I also think it would be trivial to handle UTF-16 (and possibly other encodings) and make Aider more useful rather than just resilient to crashing.

**Comment by nevercast** [comment]
There are obviously questions about allowing Aider to modify the encoding of a file, for example, if you were to ask Aider to edit a file that was UTF-16 (or other non-UTF-8 encoding), it would load the file and parse it as UTF-8. After the SEARCH/REPLACE block, how do we handle encoding then? The file could be written back out as UTF-16, or alternatively, we could allow Aider to modify the file encoding. Another, perhaps safer option, is that non UTF-8 files are always read-only/repo-map and never modifiable. This puts the responsibility of changing the encoding on the developer.

**Comment by paul-gauthier** [comment]
Thanks for calling this out. Aider goes to some effort to be robust against these sorts of unicode problems. This should be a straightforward fix. In most cases, aider simply ignores files which don't conform to the `--encoding` which is in effect.

**Comment by nevercast** [comment]
Ignoring files, or reporting it if the file is manually `/add`ed is certainly a defensive and reasonable approach. If Aider didn't crash then that's 90% of the pain gone. I understand if supporting multiple filetypes (without specifying `--encoding`) is aspirational or out of scope.

**Comment by paul-gauthier** [comment]
The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by nevercast** [comment]
`/tokens` now works as expected, and does not show any error which is clean.
`/add utf16.file` gives a nice red error message as I would expect.

There is one edge case I did encounter when testing, if I add an empty file, and then save it with utf16, Aider v0.16.4-dev crashes.
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "Python311\Scripts\aider.exe\__main__.py", line 7, in <module>
  File "Python311\Lib\site-packages\aider\main.py", line 564, in main
    coder.run()
  File "Python311\Lib\site-packages\aider\coders\base_coder.py", line 329, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\coders\base_coder.py", line 397, in run_loop
    inp = self.io.get_input(
          ^^^^^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\io.py", line 187, in get_input
    completer_instance = AutoCompleter(
                         ^^^^^^^^^^^^^^
  File "Python311\Lib\site-packages\aider\io.py", line 46, in __init__
    content = f.read()
    ```

**Comment by paul-gauthier** [comment]
Added test coverage and a fix. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
