### ISSUE TITLE
Enhancement: .aiderignore to ignore file patterns 

### ISSUE THREAD

**Issue by nevercast** [paul-gauthier/aider#307]
I tried to `/commit` just now and it unfortunately failed because `package-lock.json` didn't fit in the GPT-3.5 context. But I really don't care about package-lock and actually wanted a commit message for `package.json`. 

I don't see a way to ignore `package-lock.json` in Aider and I think that would be a great enhancement. For commit messages, but also for repomap. I'd expect it to have the same glob behaviour as a .gitignore.

A developer could ignore all sorts of paths that aren't helpful to the Assistant and minimise some token cost in the process.

**Comment by paul-gauthier** [comment]
Aider already honors `.aiderignore` as you describe.

**Comment by nevercast** [comment]
Incredible. I should have just tried it. You're excellent!
