### ISSUE TITLE
Aider in Ubuntu 22.04 Desktop (Gnome) shows white screen - I am unable to read the code

### ISSUE THREAD

**Issue by man0l** [paul-gauthier/aider#308]
![image](https://github.com/paul-gauthier/aider/assets/1413216/45147540-eddb-468f-9f85-d82a72be95b5)

This happens in the default terminal in Ubuntu and Gnome. I am not sure if it is a setting, but it seems like a bug. I use custom conda environment for running aider.

**Comment by man0l** [comment]
thank you, I managed to make it work by using the --dark-mode argument. Thanks!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
