### ISSUE TITLE
Suggestion: DryRun owerwrite

### ISSUE THREAD

**Issue by lvalics** [paul-gauthier/aider#309]
I usually run AIDER in dry mode, to avoid to write over my code and the solution maybe is not OK.
I would like to have a command like /dryover maybe if I get a response from AIDER and is ok, then run /dryover and get the last solution and write it bypassing dry-mode.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The entire purpose of `--dry-run` is to be certain that your files will not be modified. As such, it would not be appropriate to add a `/dryover` command that overruled that setting.

The expected way to use aider is to run it without `--dry-run` and keep your source code files in a git repo. Aider is very careful to make sure any changes made to the files are committed to git in distinct commits. Aider provides the `/undo` command to undo a change that you didn't like. Or you can use all of the normal git commands to revert any aider changes you'd like (either using `/git` inside the chat or just using `git` or any other standard git tools).

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by lexiforest** [comment]
I also think a command like `/apply` would be great for anyone who prefers `--dry-run` as default.

**Comment by amarjeetanandsingh** [comment]
@paul-gauthier I also prefer to run in dry run mode and then expect a /apply command to flush the changes to actually apply the changes in files.
Any possibility to reconsider this feature request?
