### ISSUE TITLE
Ctags not recognized

### ISSUE THREAD

**Issue by kwmiebach** [paul-gauthier/aider#31]
I installed universal ctags but it is not the latest version.

When I run aider, it doesn't seem to recognize it, although I can use ctags on the commandline:

```
aider
Model: gpt-4
Git repo: none
Repo-map: disabled
Use /help to see in-chat commands.
```

The `Repo-map: disabled` part indicates that ctags was not recognized, right?

Could the insalled universal-ctags be to old?

```
which ctags
/usr/bin/ctags

ctags --version

Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Apr 23 2021, 18:29:07
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc
```

**UPDATE:**

The solution given by @KnotEnvy worked, I created a git repo in the working directory first:

```
$ git init
Initialized empty Git repository in /workdir/.git/
$ aider app.py
Model: gpt-4
Creating empty file app.py
Files not tracked in .git:
 - app.py
Add them? y
Added app.py to the git repo
Commit b972fab Added new files to the git repo: app.py
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
```

So my ctag version seems to be ok.

**Comment by KnotEnvy** [comment]
you must be connected to a repo to use ctags. When connected these lines update, if ctags is installed it will be mentioned in the repo-map line. 
Git repo: none
Repo-map: disabled

**Comment by GaryMcD** [comment]
Not sure if this is the right thread, but I cannot get aider to pickup ctags.

'''zsh

➜  neat git:(master) ✗ aider
Model: gpt-4
Git repo: .git
Repo-map: basic using 1024 tokens (universal-ctags not found)
Use /help to see in-chat commands.
───────────────────────────────────────────────────────────────────────
> /exit                                                                

➜  neat git:(master) ✗ which ctags
/usr/local/bin/ctags
➜  neat git:(master) ✗ ctags --version
Universal Ctags 6.0.0(p6.0.20230702.0), Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul  2 2023, 18:32:54
  URL: https://ctags.io/
  Output version: 0.0
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc, +optscript
'''

**Comment by kwmiebach** [comment]
@GaryMcD 
> [...] I cannot get aider to pickup ctags.

Some ideas to make this work:

1. Use a fresh directory outside of any other git repository (previously I had it inside the aider repo tree when I had problems)
2. Maybe it helps not to have any special characters in the path? Is there a space in your working directory name? I am not sure what `neat git` stands for.
3. Start fresh: `mkdir $HOME/demo1 && cd $HOME/demo1 && git init`
4. Give a filename: `aider app.py`

Maybe one of it helps. Good luck

**Comment by kwmiebach** [comment]
@GaryMcD 

I believe you need the +json feature, which does not appear in your list.

> Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc, +optscript

Aider depends on the json feature.

I used the ctags version from my distribution where json is included.

**Comment by paul-gauthier** [comment]
@kwmiebach good point about the `+json` support.

I just pushed an update so that aider shows more clear explanations when it disables the repo map. You can pick it up by installing the latest from github, or it will go out soon in the next pypi release.

**Comment by GaryMcD** [comment]
Thanks for the details about `+json`. I tried re-installing ctags and still didn't get json, couldn't find anything in the configure help text. Eventually found this [GNU/Linux](https://github.com/universal-ctags/ctags/blob/master/docs/autotools.rst#gnulinux-distributions) and ran the commands it mentions to run BEFORE installing ctags. Did that, and now I have Json. Thanks all!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now. Please feel free to reopen or create a new issue if you have any further problems.
