### ISSUE TITLE
Consider adding `--subtree-only` to exclude repo content outside the cwd + subtree

### ISSUE THREAD

**Issue by paul-gauthier** [paul-gauthier/aider#312]
> NeverCast: It would be nice if Aider can handle virtual paths so that the agent is essentially sandboxed to a subpath in a Git repo. 

> Examples of this is where server and client implementations might be in the same repo, or there may be many libraries that are part of the project and can't be separated into individual git repos for many sensible reasons, but I'd still like to constrain the agent to focus on one particular area.

> Obviously the Git paths are still going to be relative to root and that's where Aider could handle that.

> paulg: I'm not sure Carter's issue is the result of an intentionally constructed monorepo. But agreed, sometimes it might be sensible to focus aider on a subtree of the repo. Could possibly add a --subtree-only which limits it to only consider paths in/below the cwd.

See discord discussion:

https://discord.com/channels/1131200896827654144/1133060505792159755/1169389326044508220

@nevercast

**Comment by iWhacko** [comment]
i would like to second this feature. I understand the fix made here: https://github.com/paul-gauthier/aider/issues/95

but when working on multiple subprojects, or even a java project where files are in src/main/java/org/acme/package it is a pain to keep typing the full path everytime. 
I suggest a /CWD command to set the Current Working dir for every command after that. so that you can switch during your session.

I'm not a python guru, but a java engineer for 17 years so I'm willing to give this enhancement a try if you could point me in a direction where I might need to do some edits, and I'll try it out.

**Comment by iWhacko** [comment]
OK, so I made some modifications, and got it working to set a cwd. if you then add a file relative to the cwd, it works. But now I'm a bit lost trying to find where the git root is used elsewhere, for instance when it's asking to create a file, because that still uses the root folder.

**Comment by tastyblob** [comment]
> OK, so I made some modifications, and got it working to set a cwd. if you then add a file relative to the cwd, it works. But now I'm a bit lost trying to find where the git root is used elsewhere, for instance when it's asking to create a file, because that still uses the root folder.

Can you share a snippet of where you're stuck?

**Comment by paul-gauthier** [comment]
Aider has `--subtree-only` now. 

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by gregid** [comment]
@paul-gauthier If possible I would like to reopen the issue. `--subtree-only` works fine for controlling the context but it does nothing for creation of new files. When working with monorepo the fact that aider always creates files starting in git root is troublesome. 

At first I started to disable auto-commit and manually copied each created file to the right folder and only then manually commit. As you can imagine this is against the idea of ai coding assistant when you have to constantly assist aider in the right placement of files.
At the moment I am using a convoluted `CONVENTIONS.md` to make it work for 50-80% of files which is far from ideal.

I thought maybe an option like `--cwd-for-new-files` where it would then switch from `git root` to `cwd` for new files.  But the proposal with `/CWD` command is even better as it would allow to dynamically switch the cwd.
