### ISSUE TITLE
Aider creates a commit when I add a file that was already in Git.

### ISSUE THREAD

**Issue by nevercast** [paul-gauthier/aider#314]
Hi,

Aider v.0.16.3
Python 3.11.5

When I /add a file, Aider detects that my workspace is dirty (because I have made some other changes), and commits those changes with a "aider: Added {filename}" commit message.

However, the file I just added to the chat was already in Git and had not changed, and Aider has wrongly committed unrelated changes with a bad commit message.

I would expect Aider to just add the file to the context of the chat, and not make any commits. I can then choose to use /commit, or Aider will do the correct thing with auto-correct later when it detects the dirty workspace.

**Comment by nevercast** [comment]
If it's relevant, the out-of-band changes were file deletions.

**Comment by paul-gauthier** [comment]
Thanks for filing this issue. I've fixed the bug and added test coverage.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by nevercast** [comment]
Excellent! Commit looks good. 
Just tested it and Aider v0.16.4-dev now works as expected.
