### ISSUE TITLE
Deprecated (or close) dependencies with chromadb

### ISSUE THREAD

**Issue by nikolaidk** [paul-gauthier/aider#319]
I have a conda env with chromadb and struggle with this error. Would prefer help with a fix instead of using a loop hole:

Found existing installation: aider-chat 0.16.0
---
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aider-chat 0.16.0 requires scipy==1.10.1, but you have scipy 1.11.3 which is incompatible.
aider-chat 0.16.0 requires urllib3==2.0.2, but you have urllib3 1.26.18 which is incompatible.
---

Seems like some packages needs update :)

**Comment by paul-gauthier** [comment]
I updated all the dependencies. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
