### ISSUE TITLE
[QUERY] universal ctags (or tree-sitter?) not being used?

### ISSUE THREAD

**Issue by trilloc** [paul-gauthier/aider#324]
Hi

I have a repo on git and I used aider as follows, but it doesnt seem to be using ctags (or tree-sitter). Pls help to fix.

Also it doesnt seem to know which files need to be modified .. it asks me to manually add the files.. could this be related?

"Please provide the specific files that need to be modified, and I can give you more detailed instructions with the exact code changes."

$ aider --model gpt-4-1106-preview --map-tokens 4096
Aider v0.16.3
Model: gpt-4-1106-preview
Git repo: .git
Repo-map: using 4096 tokens
Use /help to see in-chat commands, run with --help to see cmd line args

Cheers
Rajesh

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The aider output you've included indicates that the repo map is enabled (`Repo-map: using 4096 tokens`).

Can you be more clear about the problem you are having? Perhaps pasting some output or a screenshot that shows the issue?

**Comment by trilloc** [comment]
Hi @paul-gauthier 

Here is the screenshot..

![image](https://github.com/paul-gauthier/aider/assets/63382707/49853ed6-11c1-4890-91e0-57bcca13a2e0)

I am going through this codebase and tyring to figure out how to add a few enhancements. Aider/GPT4 is unable to figure out which files need to be changed...

Cheers
Rajesh

**Comment by paul-gauthier** [comment]
Did you try asking it which file it thinks needs to be modified?

**Comment by trilloc** [comment]
> Did you try asking it which file it thinks needs to be modified?

![image](https://github.com/paul-gauthier/aider/assets/63382707/53f956c8-acf8-4ce4-b74b-577726b8fcad)

yes, but it is not able to answer properly.

**Comment by paul-gauthier** [comment]
It says it thinks you need to modify `AdminDashboard.js` ? Is that not correct?

Are you just trying to test GPT? Or do you really need help figuring out which file to edit? Because if you know which file needs to be edited, the expedient thing is to just `/add` it yourself.

**Comment by trilloc** [comment]
> It says it thinks you need to modify `AdminDashboard.js` ? Is that not correct?
> 
> Are you just trying to test GPT? Or do you really need help figuring out which file to edit? Because if you know which file needs to be edited, the expedient thing is to just `/add` it yourself. 

Hi @paul-gauthier 
There is no file called AdminDashboard.jsx .. it is a third party repo and I am trying to understand their code.

Cheers

**Comment by paul-gauthier** [comment]
Sounds like GPT 4 Turbo is unable to figure out your repo.

Have you tried with plain old GPT-4?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
