### ISSUE TITLE
Kind request for Vim9 support!

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#325]
> Other editors
> If you are interested in creating an aider plugin for your favorite editor, please let me know by opening a [GitHub issue](https://github.com/paul-gauthier/aider/issues).

Hello!

Yes, I know Neovim... but maybe it's not that hard to make it work with Vim9 as well?

(probably gpt can help to translate from Lua used in Neovim's into Vim Script)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
