### ISSUE TITLE
`gpt-4-1106-preview` as new default?

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#326]
Suggestion:

What about considering   `gpt-4-1106-preview` (128k context window! https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo and cheaper) as new default? (and have fallback strategy that later falls back to gpt-4 and later to gpt-3.5-turbo)?
 
 I know one can add model `gpt-4-1106-preview` to `$AIDER_MODEL` environment variable:

```
$ tail -n 1 ~/.bashrc
export AIDER_MODEL='gpt-4-1106-preview'
$ echo $AIDER_MODEL 
gpt-4-1106-preview
$ aider llm.py
Aider v0.17.0
Model: gpt-4-1106-preview
```

* https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
* https://openai.com/pricing

**Comment by ChristianSch** [comment]
Why have a default model that is not freely available and needs at least one paid invoice for new users to attain?

**Comment by gwpl** [comment]
I thought that `gpt-4` was default model already (which satisfies your description), with fallback to gpt-3.5-turbo...

If I misunderstood intent, then let's keep gpt-3.5-turbo. I set model via environment variable.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I think it's too early to adopt the preview model as the "default" GPT-4 model for aider. The rate limits are very low right now. It's fully supported in aider v0.17 for anyone that wants to start using it. I'll definitely be looking to make it the default as soon as it seems reasonable.

**Comment by ChristianSch** [comment]
> I thought that `gpt-4` was default model already (which satisfies your description), with fallback to gpt-3.5-turbo...
> 
> If I misunderstood intent, then let's keep gpt-3.5-turbo. I set model via environment variable.

Maybe I'm wrong here. If so, you're right. But what @paul-gauthier said is still a good point.

**Comment by paul-gauthier** [comment]
Aider checks to see if GPT-4 is available on your API key. If it is, it uses that. If not, it falls back to GPT-3.5. 

Once the new GPT-4 preview model goes into production, that will probably be the model that aider checks for initially.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
