### ISSUE TITLE
Summarizer picking stronger models if needed [feature idea] 

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#327]
"Summarizer suddenly failed for gpt-3.5-turbo"

*  I am using `gpt-4-preview` model (and this time was loaded with a lot of context... and it can take up to 128k)

What I was thinking, was:

* maybe summarizer can be intelligent and :
    * if context is bigger use `gpt-3.5-turbo-16k`
    * otherwise if it's still too big, use `gpt-4-preview` (which is "gpt-4 turbo")
    
?

Sorry for not being more helpful, but I pressed "enter" and message disappeared so I tried to reconstruct from memory.

**Comment by paul-gauthier** [comment]
The summarizer now uses the 3.5 model with 16k.
