### ISSUE TITLE
Aider is very slow

### ISSUE THREAD

**Issue by azazar** [paul-gauthier/aider#330]
I'm trying it with `gpt-4-1106-preview`, and it takes about a minute to send query. It generates 100% CPU load during preparation of request.

**Comment by man0l** [comment]
I have just tested it and works as normal speed as I expect. I am not sure how fast would gpt4-turbo work anyway.

offtopic:
The good thing is it shows 120k tokens for input, which could cover a whole codebase, which is awesome!

![image](https://github.com/paul-gauthier/aider/assets/1413216/f9ca844f-3bad-4822-81ba-6c30930163eb)

**Comment by azazar** [comment]
I've just tried the same repo with `gpt-4` and small context window, and it's still very slow. Probably the cause is that the repo itself is too large. It took several minutes to generate the last line: 
![image](https://github.com/paul-gauthier/aider/assets/2816075/f988d8c5-4ee6-4f5b-9a81-dcb2c01149ea)

And couple more minutes to get the rest: 
![image](https://github.com/paul-gauthier/aider/assets/2816075/82693fe0-9b28-4036-824d-95c4236e0388)

**Comment by paul-gauthier** [comment]
You can use `.aiderignore` to tell aider to ignore parts of your repo if there's a lot of useless/irrelevant stuff in there. That will speed it up and save token costs for the repo map, etc.

**Comment by jackmac92** [comment]
> You can use `.aiderignore` to tell aider to ignore parts of your repo if there's a lot of useless/irrelevant stuff in there. That will speed it up and save token costs for the repo map, etc.

is it just `.aiderignore` or does it respect `.ignore` / some other file non specific to aider?
