### ISSUE TITLE
Is repository mapping supporting symlinks (Aider high CPU spike)

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#331]
BLUF: How repository mapping is supporting symlinks?

I have repository where AIDER gets stuck for few seconds with 100% cpu, and then continues.

IIRC output seemed repeated, but maybe I hallucinate.

The main reason I am writing this ticket is, because I just realised that in this directory I have "a lot" of symlinks to source files (one sourcefile can be symlinked with many many symlinks), and I wondered if it's possible that it's confusing https://aider.chat/docs/repomap.html repository mapping.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

If you have a lot of irrelevant content in your repo, you can use `.aiderignore` to tell aider which parts of the repo to ignore. This will speed things up and save on token costs, etc.

**Comment by gwpl** [comment]
I should have do more "RTFM" 🤦🏻 . Thank you! `.aiderignore` sounds like great advice!

**Comment by gwpl** [comment]
For completness and making issue helpful for other readers:

```
find . -type l >> .aiderignore
```
