### ISSUE TITLE
gpt-4-1106-preview

### ISSUE THREAD

**Issue by AutoJenny** [paul-gauthier/aider#332]
I've tried updating to gpt-4-1106-preview in model.py and I see it's already there in openai.py but I'm not getting it to fire up. Any suggestions? Thanks!

**Comment by Squallpka1** [comment]
im using with cmd. just type.
aider --model gpt-4-1106-preview
and its good to go. At least for me.

**Comment by AutoJenny** [comment]
Thanks.  :-). Exciting times.

**Comment by man0l** [comment]
it works great for me as well. I have tried /tokens command and it really shows 120k+ tokens :)

$ 0.23   23,404 tokens total
        107,668 tokens remaining in context window
        131,072 tokens max context window size

**Comment by mikeslattery** [comment]
> it works great for me as well. I have tried /tokens command and it really shows 120k+ tokens :)

Unfortunately, the actual limit is much less depending on [your usage tier](https://platform.openai.com/docs/guides/rate-limits/usage-tiers) (unless they changed it in last 24 hours)

**Comment by cranyy** [comment]
Anyone else think that gpt-4-1106 is much much worse? I swear every 4 or 5 messages it tells me to add the file to chat which it was just editing. it also duplicates functions, deletes function code en masse and replaces it with TODOs much more often than gpt-4?

**Comment by mikeslattery** [comment]
(out of scope comment about new engine features)

This ticket appears to only be about model selection, which is perfectly fine.  However, it would be great if Aider code could leverage new features of the model and API, such as uploading project files, RAG, and code-interpreter.   Aider code would drastically shrink in size, yet increase in ability (by knowing more about your project).  The `/add` command might even be able to be made optional; the AI could figure out which files are in scope.

That's a big change tho.  Likely some new leaner project should be written that does it.

**Comment by paul-gauthier** [comment]
> Anyone else think that gpt-4-1106 is much much worse? I swear every 4 or 5 messages it tells me to add the file to chat which it was just editing. it also duplicates functions, deletes function code en masse and replaces it with TODOs much more often than gpt-4?

See #343 for more discussion.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by sfdrada** [comment]
just in case any other people have problems with using the new model, updating the openai key by creating a new one allowed me to use it in aider
