### ISSUE TITLE
Add `!` as alias for `/run`

### ISSUE THREAD

**Issue by ryanfreckleton** [paul-gauthier/aider#334]
It would be a nice affordance to be able to type !<shell command> like I'm able to in python and various debuggers. The functionality can be identical to `/run` but is just shorter and consistent with other shell-like tools.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I like this idea.

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
