### ISSUE TITLE
Proposal: Fancy `/voice` | `/v` semantic with placeholders! (same for `/run` )

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#341]
Wouldn't it be great to have prompts like:

* `/v[opening_marker...closing_marker]`
* `/v[parameter=zoo, param2=foo...]
*  combination `/v[opening...ending, param1=... , param2=... ]

simmilar mechanism could be also applied to `run` , e.g. :

* `/run[edit]` # so result can be edited before send
* `/run[{#...#}] Make poem about contents of my root directory : [{#ls /#}] , and make it very poetic!`
    * (problem with this draft: I don't see how to inject command and parameters at same time... probably other syntax would be better)

Allowing e.g.:

* Insert into prompt with STT / ASR: `/v[{@...@},edit] Please be critique that is provoking to critical thinking... of following argumentation:  {@prompt="Argument:"@}, following this rules: {@Rules:@}. Be sophisticated, information dense.`
    * Which would ask with prompt `Argument:` and then STT / ASR prompt in next lline as usual, and later `Rules:` and STT / ASR prompt as usual.
    * "edit" parameter, will instead of sending produced text directly to STT / ARE, first allow edit. As it's specified on highest level `/v` it will allow edit in prompt of whole thing, like it would be typed, with inserted STT / ASR output into markers. If it would be in enclosed voice commands (here using `{@...@}` markers as defined), it would allow edit of STT / ASR output of those before being inserted.
    
As one can see proposed syntax aims to :

* be future proof => ability to add more parameters
* versatile context proof from grammar perspective : like in `s#...#...#` we can define marker, or bash `<<<UNIQUE_END_LINE` we should hav e a way for user to be able to define custom markers in case there is collision in input. Of course we can have some default like `/v[...]`|`/v`|`/voice` in case of lack of defined markers.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I'm not sure I fully understand your proposal or the benefits it would provide to the typical aider user?

**Comment by gwpl** [comment]
Sure! Let me try to be more casual/less formal in my explanation.

So basically main problem I arrived was:

* I was not always happy  with transcription.  => sometimes I prefer to send straight away, sometimes I would love to review and edit.

That brought me to idea:

* maybe `/v[edit]` when I want edit/review! and `/v` when I go straigth aways.

Then I realised... OpenAI STT/ASR has ability to provide prompt that may allow to give hints ...

* `/voice[prompt=...]`

Then I realised... but actually I often do in a sequence, many times in a row iterations, where most part is the same and I want to replace only fragments... what if instead of repeating myself I can do

* `part that repeats ... \v .... rest that repeats`

(all of this ofc combines with great `{...}` multi line {bracket} notation that you have (and other tools miss...)

Then my computer science nerd kick in, imagining scenarios when I need to put multiple markers inside 
 tmessage `xxxxx \v yyyyy \v zzzz` and after filling all `speak[enter]speak[enter]....`  to review whole thing before sending, and that's who I ended up with `\v[edit]{ xxxx \v yyyy \v zzzz}`. 
 
 Then I realised that Putting `\v` inside is insufficient, as I may want to speck about \v.... so we either need to provide marker like in linkux `sed` or extra escaping if we want to send `\v` to LLM, so `\v[marker=@v]...` or `xxx \\v yyy` .... and finally I arrived with grammar described above, that allows expressing everything, still probably not all features are needed at once. Still to me as developer having vision where things may need to go if needed is helpful.
 
 To me it would be especially helpful if in history after typng:
 
*  `Please make recipie for guest \v, who is vegan that don't like spicy food that match haloween season, from following ingredients: \v . And for sure include \v. But please for that person avoid \v. Please create new unique markdown file with recipie with unique "## title" and matching filename `  

To have in aider history not only version with all gaps filled, but also with `\v` markers. That way I could use `[up]`+`[up]`to get back to version with \v   hit `[enter]` and generate another recipie. 
After running few times I would have catalog with few recipies that consider preferences of different guests I have in mind.

**Comment by paul-gauthier** [comment]
It sounds more like you are trying to "script" aider with templates? You might want to look at this FAQ entry, which explains how to script aider from the command line or from python:

https://aider.chat/docs/faq.html#can-i-script-aider
