### ISSUE TITLE
User-defined aliases

### ISSUE THREAD

**Issue by DarrenTsung** [paul-gauthier/aider#342]
Hi, thanks for the great project! I was thinking it would be useful to have some sort of configuration for user-defined aliases at different scopes. 

For example, a user might define global aliases on their machine like: 
- `!` to be an alias for `/run` (https://github.com/paul-gauthier/aider/issues/334)

And then for projects we could commit in common aliases for development: 
- Adding files related to a section of the codebase, e.g. `/add_${feature}` as an alias for `/add $feature_source_file $other_file $another_related_file`
- Common run commands, e.g. `/clippy` as an alias for `/run cargo clippy -- -D warnings`

Aliases could be put under the same prefix as commands currently (like `/!` or `/clippy`) or under a different prefix to reduce confusion / collisions when new commands are released (maybe `!` and `!clippy`?).

Wdyt? I could put together a PR if you're interested.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Have you tried using the history search that's build into aider? You can do control-r to search back and re-use commands you've previously entered into the aider chat. That may make it easy to re-use commands that you need frequently?

**Comment by DarrenTsung** [comment]
Thanks for the reply! I haven't used control-r as much, but that's a good point and it does help with repeated commands. I still think aliases could be a good way for advocates within companies (like myself) to minimize the friction for team members who want to try aider out on a non-trivial example. 

For example, I could set up aliases for working with specific files within the repo, common run commands we use for linters like clippy, etc. Then run a workshop with my teammates to spin up aider and work through an example feature request.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
