### ISSUE TITLE
Enhance Git Integration for Global .gitignore and Optional Suggestions [Feature Request]

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#344]
**Description:**
Users of "aider," often encounter situations where it suggests adding `.aider*` entries to my project's `.gitignore` files. While this is helpful, it can sometimes lead to redundancy and clutter in multiple repositories. To improve user experience and offer better control over Git integration, I propose the following enhancements:

**How to utlize gitignore global configs**

Example:
```
echo '.aider*' >> ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global
```

Quote with other possible paths:

> $XDG_CONFIG_HOME/git/ignore, $GIT_DIR/info/exclude, .gitignore

from https://git-scm.com/docs/gitignore

> git config --get core.excludesfile

from https://stackoverflow.com/a/22885996/544721

1. **Global .gitignore Configuration:**
   - Allow users to specify a global `.gitignore` file that "aider" will utilize to determine which files should be globally ignored across all projects. This will help maintain cleaner and more consistent `.gitignore` files.
   - How it works with Git:
     - Users set a global `.gitignore` file path, e.g., `~/.gitignore_global`, using a command like:
       ```
       git config --global core.excludesfile ~/.gitignore_global
       ```
     - Git will automatically apply the rules from the global `.gitignore` file to all repositories, ensuring that files matching these patterns are ignored without needing to edit project-specific `.gitignore` files.

2. **Optional Flag: `--gitignore-aider-globally`:**
   - Introduce a new command-line flag (`--gitignore-aider-globally`) in "aider" to allow users to specify whether they want `.aider*` entries added to the project's `.gitignore` or rely on the global configuration.

**Expected Git Behavior:**
- Users can configure a global `.gitignore` file to centrally manage which files are ignored by Git across all repositories.
- Git will apply rules from the global `.gitignore` file to all repositories, ensuring consistent ignoring of specified files.
- Users have the option to control whether "aider" should suggest adding `.aider*` entries to the project's `.gitignore` file or utilize the global configuration with the `--gitignore-aider-globally` flag.

**Benefits:**
- Streamlined and consistent management of ignored files across multiple repositories.
- Improved user control and flexibility in handling `.aider*` entries in project-specific `.gitignore` files.
- Minimized repetition and clutter in `.gitignore` files.

**Additional Information:**
- These enhancements will provide a more seamless integration between "aider" and Git, making it easier for users to manage ignored files globally and per-project while maintaining a clean and organized Git repository structure.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider checks to see if `.aider` is ignored already in your environment. If it's ignored in the global gitignore or in the local repo. Either way. If it is not ignored somehow, aider will offer to add it to the`.gitignore` that is local the repo it's using.

So if you don't want to be bothered by aider's offer to add `.aider*` to your local `.gitignore` you can do what you've suggested and add it to a global gitignore. Aider should notice and stop asking.

**Comment by gwpl** [comment]
Great!

I double checked now, and indeed! I installed global ignore and Aider do not trigger!

However still, maybe `--add-aider-ignore-globally`could be something interesting, either as flag, or manual (probably there is already in manual, then I apologise).

Otherwise, as aider already recognizes global flag issue is ready to be closed if my suggestions here do not apply. Thank you again!

**Comment by paul-gauthier** [comment]
Glad that's working for you.

I don't think it's appropriate for aider to try and modify a user's global git configuration. 

On the other hand, when a user runs aider inside a repo they are expecting aider to make modifications to the files in that repo. So it's not too surprising that it might ask to modify the local `.gitignore` file.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
