### ISSUE TITLE
from aider.coders import Coder - ModuleNotFoundError: No module named 'aider.coders'; 'aider' is not a package

### ISSUE THREAD

**Issue by jontstaz** [paul-gauthier/aider#345]
Hi,

I'm trying to test out the new in-code Aider usage by using the example code but I'm getting an error: `ModuleNotFoundError: No module named 'aider.coders'; 'aider' is not a package`.

I just copy-pasted the code from the documentation and made sure I'm on the latest aider-chat version (0.17.0)
```python
from aider.coders import Coder

# This is a list of files to add to the chat
fnames = ["foo.py"]

# Create a coder object
coder = Coder.create(fnames=fnames)

# This will execute one instruction on those files and then return
coder.run("make a script that prints hello world")

# Send another instruction
coder.run("make it say goodbye")
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

Are you sure you have installed aider in the active python environment? That error makes it look like an issue with your local python env.

**Comment by jontstaz** [comment]
Yes I have. It only works when I actually have the aider folder itself in the same directory as the python file i'm executing. Regardless if aider is installed in the current python env, it still requires the aider folder for the aider.coders in-code execution to work.

**Comment by paul-gauthier** [comment]
This seems to be some problem with your local Python environment and the way that you've installed aider. It sounds like you've figured out how to make it work in your environment. Glad to hear that.

**Comment by jazoom** [comment]
I get this exact error using the latest Aider via the `paulgauthier/aider-full` Docker image. 0.70 worked fine. 0.71 gives this error and fails to start.

**Comment by jazoom** [comment]
By the way, @paul-gauthier, thank you for tagging the images with versions. That makes it very easy to just use the previous image.
