### ISSUE TITLE
Request to migrate from openai 0.28.1 to 1.3.0

### ISSUE THREAD

**Issue by roryfahy** [paul-gauthier/aider#351]
Hi,

Firstly, aider is so amazing, huge fan.

I would like to be able to use aider with the new openai api but because it depends on 0.28.1 my conda env needs to be running that version of openai package as well (unless I am mistaken)

I am happy to put up a pr for the migration if that would be desired/ useful.

For context here is the openai package [migration guide.](https://github.com/openai/openai-python/discussions/742).  They've outlined the necessary changes and also have a migration tool that seems to handle most of the heavy lifting.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Aider will certainly upgrade.

This new 1.x API is about 10 days old and has already had 11 updates in that time!

https://pypi.org/project/openai/#history

I may wait until the dust settles a bit before migrating aider onto it.

**Comment by deniercounter** [comment]
@paul-gauthier big thank you for the travail :) you open sourced. 

Unfortunately at the moment this migration is a show stopper, but I am sure that with the help of the community this can become an even bigger success story than it is right now.

**Comment by paul-gauthier** [comment]
Support for the new openai python client 1.3 is now merged into main. I would appreciate feedback if anyone sees problems, especially with Azure or OpenRouter.

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

**Comment by aarons** [comment]
Thank you so much! This is an update I've been looking forward to :)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
