### ISSUE TITLE
Feature Request: Mode where changes are just staged, not auto-committed

### ISSUE THREAD

**Issue by roryfahy** [paul-gauthier/aider#353]
I was looking through the documentation and issues here but didn't seem to finding anything about this. I would find it useful to have the code staged and then have the ability to inspect it/ redirect it/ test it before throwing in a commit.  Its easy enough right now to just run the `/undo` command but it would be nice to have a way to mold it slightly and then commit.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The `--no-auto-commits` flag might do what you need?
