### ISSUE TITLE
Restart after fail

### ISSUE THREAD

**Issue by aidanbha79** [paul-gauthier/aider#36]
After Aider crashed I restarted Aider in the same terminal but when I tried to carry on it failed to realise that I was working in C# and it tried to work in python. 

is it possible to either scan the current directory and see what the code format is for the project or have it so that it can pick up from where it picked up?

**Comment by paul-gauthier** [comment]
When you restarted, did you add some of your C# files to the chat? 

It might help me debug your issue if you could share some of the chat logs from `.aider.chat.history.md`. Particularly the logs before and after the restart and when it started coding in python.

**Comment by aidanbha79** [comment]
@paul-gauthier where would I find the logs? I have tried to look in the aider application under site-packages. I am on a Windows 11 pc.

**Comment by aidanbha79** [comment]
[aider.chat.history.md](https://github.com/paul-gauthier/aider/files/11940724/aider.chat.history.md)
As requested @paul-gauthier. 

When I restarted I didn't say it was a C# or give it any files. I thought it would pick up where it left off. When I did say it was C# it corrected it. it's at lines 605 to 660 it did the Python code. 

Brilliant program by the way. would be useful if it could read in a BRD from PDF or Word and away it goes and does its work. Others just don't seem to be able to write in the correct structure for C#.

**Comment by paul-gauthier** [comment]
Thank you for sharing the chat logs, they are very helpful.

I see that aider reports `Git repo: none` when it starts. Sounds you aren't using a git repo to manage your files? I really recommend it as a way to keep your changes safe, undo mistakes, etc.

When you launch aider inside a git repo, GPT knows about all of your files and can usually infer what programming language you are using etc.

But if you are not using git, you need to either:

1. Tell aider which files to edit by running it with `aider myfile.cs myotherfile.cs` or by doing `/add myfile.cs` from within the chat.
2. Or, tell it what language to use when making new files. Say things like "write me a c# program to do ..."

**Comment by aidanbha79** [comment]
Thank you for getting back on this @paul-gauthier I was having a play around with it and just making a dummy project up so not something I was planning to save. 

I will remember to do that next time. Might be useful to do a pre scan for the logs in the directory you are running in and if it finds them then pick up from there.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now. Please feel free to reopen or file another issue if you're having more problems.
