### ISSUE TITLE
Question - using other diff formats

### ISSUE THREAD

**Issue by omri123** [paul-gauthier/aider#361]
Hi Paul
Did you try using git diff format in place of search-replace bocks?
I am writing a feature that allow the user to add old commits to the context, and I need to choose how to represent it.
Thanks
Omri

**Comment by paul-gauthier** [comment]
I've done fairly extensive evaluations of many different editing formats. See the article below for a discussion of some of the most promising formats.

https://aider.chat/docs/benchmarks.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
