### ISSUE TITLE
Recursion error

### ISSUE THREAD

**Issue by SShadowS** [paul-gauthier/aider#362]
Ubuntu WSL
Aider 0.18.0

I ran into a recursion error almost right at the start. Is it the repo-map that fails?
Easy to reproduce, it is an open repo.
![image](https://github.com/paul-gauthier/aider/assets/3491765/d8a8e332-40eb-4b0d-a102-f354cc861f6e)

**Comment by SShadowS** [comment]
Just added commands as text so they are Copy/paste'able.
git clone https://github.com/SShadowS/wine64-bc4ubuntu.git winebc

Prompt:
Add the function HttpSendHttpResponse into Wine. It should use the functions available in Wine to do what the HttpSendHttpResponse do in Windows, but from Wine instead. The original function is described here https://tearn.microsoft.con/en-us/windows/win32/api/http/nf-http-httpsendhttpresponse

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue with such clear instructions to reproduce the problem.

The repo you're using has >10K files in it, which is more than aider can currently handle. If you're mainly planning to use aider on a portion of the repo, you can make a `.aiderignore` file to ignore large, irrelevant parts of the repo. 

 I've updated aider to be more graceful about this situation. It will warn you on launch that you're using a very large repo and to catch the `RecursionError` and disable the repo map if it occurs.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by SShadowS** [comment]
Ran the update, cant verify version as you can see in the end.
Same result, but no progress bar now.

![image](https://github.com/paul-gauthier/aider/assets/3491765/a06ce646-6ccc-4d28-b259-ff295f76a743)

**Comment by SShadowS** [comment]
It now shows the number of files in repo, but gives no warning and it still hits the recursion error.

![image](https://github.com/paul-gauthier/aider/assets/3491765/ff1bdc03-f44e-43f7-985f-70fbec3ec01e)

**Comment by paul-gauthier** [comment]
I'm sorry, the changes were still in my local. I just pushed them to github! If you upgrade again you should see them.

**Comment by SShadowS** [comment]
I can confirm it works now.
It shows a warning and disables the repo map.
