### ISSUE TITLE
(windows) error: No OpenAI API key provided. Use --openai-api-key or env OPENAI_API_KEY. (SOLVED)

### ISSUE THREAD

**Issue by chalsfxx** [paul-gauthier/aider#37]
I'm having this error in windows 11, and I've inserted the api key in the config file like said in the readme.md, also i've set the api key from command like using the command " set ", is this because I've not bought chatgpt premium? 

if that's the case, how can I use gpt 3.5 turbo, and change it? I'm a bit lost here

**Comment by tonymacx86PRO** [comment]
Hi @chalsfxx,

I'm sorry to hear you're having trouble setting the OpenAI API key. To address your issue, let's set the environment variable for the API key without using the `set` command. Follow these steps:

1. Press `Win + R` to open the Run dialog.
2. Type `SystemPropertiesAdvanced` and hit `Enter`. This opens the "System Properties" window with the "Advanced" tab selected.
3. At the bottom of the "Advanced" tab, click the "Environment Variables..." button to open the "Environment Variables" window.
4. In the "Environment Variables" window, under the "User variables" section, click the "New..." button.
5. For "Variable name", enter `OPENAI_API_KEY`. For "Variable value", enter your OpenAI API key, then click "OK".
6. Click "OK" to close the "Environment Variables" window, then click "OK" again to close the "System Properties" window.

Now, you should be able to use the OpenAI API with your applications. Keep in mind that you might need to restart any running applications or open new Command Prompt windows for the changes to take effect.

As for your question about GPT-3.5 Turbo and Chatbot API, the API is completely separated out of ChatGPT plus, You need to add billing to your **API** account, you don't need to waste money on ChatGPT. ChatGPT is a product with easy to use UI. But what aider uses is OpenAI API.

Best,
tonymacx86PRO

**Comment by paul-gauthier** [comment]
Here are some instructions on where to find your api key:

https://help.openai.com/en/articles/4936850-where-do-i-find-my-secret-api-key

They normally start with `sk-...`
