### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by user753** [paul-gauthier/aider#370]
Hello. 
I have access to openai api only through proxy, so it would be great if I could config proxy in `.aider.conf.yml` file
```
host: foo
port: 60000
username: foo
password: foo
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You might want to run a local service that makes the proxy transparent. It looks like ProxyChains might do this, but I am not familiar with it.

**Comment by user753** [comment]
Thanks. The simplest solution was to add
```
openai.proxy = {"https":"proxy_url"}
```
in `main.py`

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by kele527** [comment]
how to set  google gemini proxy?

**Comment by nmz787-intel** [comment]
> Thanks. The simplest solution was to add
> 
> ```
> openai.proxy = {"https":"proxy_url"}
> ```
> 
> in `main.py`

I don't see any openai imports in `main.py`... not sure where to look to patch this. There's still nothing in the docs about proxies for local-ish endpoints

**Comment by user753** [comment]
You can use 
set HTTPS_PROXY=http://login:password@ip:port

**Comment by nmz787-intel** [comment]
> You can use set HTTPS_PROXY=http://login:password@ip:port

It did not work for me, no matter what

**Comment by user753** [comment]
What operation system do you use?

**Comment by Mythli** [comment]
Would be nice if Aider could support a proxy :)

It should be a small change I believe, one message to aider and AI should do the job.
