### ISSUE TITLE
Adding tree sitter implementations

### ISSUE THREAD

**Issue by seanf** [paul-gauthier/aider#373]
Hi Paul, can you suggest what sort of work is needed to add another language in the [appropriate format](https://aider.chat/docs/repomap.html#credits)? 

Kotlin has a tree sitter implementation (MIT): https://github.com/fwcd/tree-sitter-kotlin. It seems to be supported by https://github.com/grantjenks/py-tree-sitter-languages

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You're right that py-tree-sitter-languages does support the kotlin language. The only other thing aider needs is a `tags.scm` query file for kotlin. It looks like that has not been provided in the tree-sitter-kotlin repo:

https://github.com/fwcd/tree-sitter-kotlin/tree/main/queries

**Comment by gwpl** [comment]
I am not yet familiar with tree-sitter, could you clarify if lack of `tags.scm` would be also blocker for adding `.ttl` RDF Turtle syntax ( https://github.com/BonaBeavis/tree-sitter-turtle/tree/main/bindings ) and `.sw` Sway programming language ( https://github.com/FuelLabs/tree-sitter-sway/tree/master/queries ) or do those repositories look fine?

**Comment by paul-gauthier** [comment]
@gwpl yes, aider needs a `tags.scm` file in order to be able to include a language in the detailed repository map.

**Comment by seanf** [comment]
> Thanks for trying aider and filing this issue.
> 
> You're right that py-tree-sitter-languages does support the kotlin language. The only other thing aider needs is a `tags.scm` query file for kotlin. It looks like that has not been provided in the tree-sitter-kotlin repo:
> 
> [fwcd/tree-sitter-kotlin@`main`/queries](https://github.com/fwcd/tree-sitter-kotlin/tree/main/queries?rgh-link-date=2023-11-27T22%3A58%3A40Z)

Thanks Paul.

Related issue: https://github.com/fwcd/tree-sitter-kotlin/issues/91

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by gminorcoles** [comment]
hi I am doing a bunch of kotlin work now and I have an interest in this. I am ignorant though, despite googling a lot about tags.scm. Woudl it be feasible for me to generate a tags.scm for the kotlin language? I see the tags.scm meantion on the treesitter docs site but have not yet found a detailed specification of what should go in that file. aider looks really cool, I wrote my own repo map, to help my LLM with coding,  in a lisp format, but then found aider by googling and it looks extremely promising.
