### ISSUE TITLE
[Question] Exploring tree of conversations by tracking .aider* in repository?

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#375]
Question: 

* Is `aider` currently designed to work correclty with tracking `.aider.chat.history.md` and `.aider.input.history` ?
* [Bug?] If reponsitory tracks those files, aider does not seem to commit them automatically. Can it be considered for aider to automatically include them in commit if they are already tracked by git ? (or should user after invocation fix manually with `git add...` + `git commit --amend --no-edit` ?)

Background / goal:

* I would love to explore tree of possible conversations with aider ( ala FLUX https://github.com/paradigmxyz/flux , but in terminal or maybe even steered by some automation for exploration of different paths of solving the problem)

Means:

* In git we naturally have DAG, can have branches and all facilities to go beyond linear "next step" vs "`/undo`"

Appendix:

Some explorations / experiment log:

* https://gist.github.com/gwpl/65251097795a2ab8ba6d6936f08791bd

Bug(?) found during the process:

* https://github.com/paul-gauthier/aider/issues/374

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Most users really do not want the `.aider` files in their git repos. Users were accidentally adding them to git and it was causing tremendous confusion. So aider offers to add `.aider*` to `.gitignore` if it's not already there.

**Comment by gwpl** [comment]
Sure, I just thought that for people using aider for exploration of LLM capabilities in research manner it would be interesting ticket to have in the repository, to highlight other aider applications.
I actually find it fantastic for prototyping some ideas, before actually later replacing with tailored API wrappers (if needed at all).

Let me close this issue for now then, everyone can find it and continue conversation regardless it being closed :).

(in mean time we have actual bug discovered in the process: https://github.com/paul-gauthier/aider/issues/374 )
