### ISSUE TITLE
When I was prompted to give the Endpoints.cs file for GPT-4 to analyze, aider crashed.

### ISSUE THREAD

**Issue by tonymacx86PRO** [paul-gauthier/aider#38]
Maybe when @paul-gauthier fixed #33 , created another bug when the user prompted to give to AI the context of specific file. I am using the latest git+ pip install. 
Here's goes nothing:
```
GigaBrain.API/OpenAI/Endpoints/Endpoints.cs
Add these files to the chat? y
Traceback (most recent call last):
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\Scripts\aider.exe\__main__.py", line 7, in <module>
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\main.py", line 293, in main
    coder.run()
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\coders\base_coder.py", line 328, in run
    new_user_message = self.run_loop()
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\coders\base_coder.py", line 394, in run_loop
    self.check_for_file_mentions(inp)
  File "C:\Users\Coder\AppData\Local\Programs\Python\Python310\lib\site-packages\aider\coders\base_coder.py", line 538, in check_for_file_mentions
    self.abs_fnames.add(os.path.abspath(os.path.join(self.root, rel_fname)))
AttributeError: 'list' object has no attribute 'add'
```

**Comment by paul-gauthier** [comment]
I just pushed a possible fix for this. But I think it would only have been relevant if you were running with the `--no-git` switch, which seems unlikely?

It also appears that the `base_coder.py` line numbers in your stack trace are different than the main branch. The main branch has that `self.abs_fnames.add(...)` on line 572.

https://github.com/paul-gauthier/aider/blob/main/aider/coders/base_coder.py#L572

The line numbers in your stack trace seem to agree with v0.7.2, which is what you get with a normal `pip install aider-chat` right now. That tagged release has the `self.abs_fnames.add(...)` on line 538 like in your stack track.

https://github.com/paul-gauthier/aider/blob/v0.7.2/aider/coders/base_coder.py#L538

Are you sure you have installed from the latest github by doing the command below?

```
pip install git+https://github.com/paul-gauthier/aider.git
```

**Comment by tonymacx86PRO** [comment]
Yes, I installed it now, if I need I can uninstall it and install it if you prefer. I executed 1 minute ago this:
`pip install git+https://github.com/paul-gauthier/aider.git`

**Comment by tonymacx86PRO** [comment]
I reinstalled aider-chat. I get that error installing the main one.

**Comment by tonymacx86PRO** [comment]
> I just pushed a possible fix for this. But I think it would only have been relevant if you were running with the `--no-git` switch, which seems unlikely?
> 
> It also appears that the `base_coder.py` line numbers in your stack trace are different than the main branch. The main branch has that `self.abs_fnames.add(...)` on line 572.
> 
> https://github.com/paul-gauthier/aider/blob/main/aider/coders/base_coder.py#L572
> 
> The line numbers in your stack trace seem to agree with v0.7.2, which is what you get with a normal `pip install aider-chat` right now. That tagged release has the `self.abs_fnames.add(...)` on line 538 like in your stack track.
> 
> https://github.com/paul-gauthier/aider/blob/v0.7.2/aider/coders/base_coder.py#L538
> 
> Are you sure you have installed from the latest github by doing the command below?
> 
> ```
> pip install git+https://github.com/paul-gauthier/aider.git
> ```

I appreciate that you so fast in editing the code! And the aider is useful likely, yes not so integrated into VS 2022 C# NET. workflow but is still more convenient than copy pasting! Thanks for this great tool!

**Comment by tonymacx86PRO** [comment]
I will check soon another commit cmd if the fix works.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now. From the stack trace, it really looks to me like you are running the 0.7.2 version of aider without the fix. Perhaps there's an issue in your local environment where you are installing from GitHub but somehow still invoking the older version due to a shell path issue or some such.

Please feel free to re-open the issue if you're still having trouble. I'm happy to try and help more.
