### ISSUE TITLE
--message-file | -mf : Ability to script aider providing message as file

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#381]
Could you please consider possibility to script aider by providing message prompt via file instead of argument?

Here is example PR: https://github.com/paul-gauthier/aider/pull/380

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by gwpl** [comment]
As changed https://github.com/paul-gauthier/aider/pull/380/files got merged , I should have closed issue myself, as PR 380 implements requested feature. Thank you!
