### ISSUE TITLE
OPENAI_API_KEY, --openai-api-key, and ~/.aider.conf.yml not getting used

### ISSUE THREAD

**Issue by karma0** [paul-gauthier/aider#385]
When I follow the instructions on the main `README.md`, they don't appear to work:

```bash
$ pip install aider-chat
$ export OPENAI_API_KEY=your-key-goes-here
$ aider hello.js
Aider v0.18.0
Model: gpt-4
Git repo: .git
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────
> Do anything

You exceeded your current quota, please check your plan and billing details.
Retry in 0.4 seconds.
You exceeded your current quota, please check your plan and billing details.
Retry in 0.1 seconds.
You exceeded your current quota, please check your plan and billing details.
Retry in 2.2 seconds.
^C

^C again to exit
```

The variable is properly set in my environment, but it's not getting used.  Additionally, I tried configuring it on the CLI with `--openai-api-key`, and in the configuration file `~/.aider.conf.yml` without any success.

When I check the API key page on OpenAI, it says that the key has never been used.

**Comment by karma0** [comment]
This issue happens on Mac and Linux (Ubuntu).

**Comment by paul-gauthier** [comment]
Thanks for trying aider. The error message you're seeing is an error from OpenAI. That message usually occurs when you've spent too much money already this month compared to the limits you've set in their dashboard. You should probably go and check to see if you've already spent your full limit. The month will be over within a day or two, so your quota will reset at that time also.

**Comment by karma0** [comment]
I just installed `shell-gpt` and it seems to work with the API key.

**Comment by karma0** [comment]
Okay, it's working now.  I added $10 to my OpenAI account, which seemed to fix it.  I wonder if it's an issue on their end - I showed $28 in unused credit for the month already.
