### ISSUE TITLE
Feature Idea: Custom repo-map methods

### ISSUE THREAD

**Issue by nkeilar** [paul-gauthier/aider#386]
I actually experimented before I knew about aider with my own approach, I had an index command that would run gpt over the whole code base and produce a summary of each file. This was then used in my repo map. I didn't' want to send the whole code base to openai at the stage, so I actually implemented the summary to happen locally using my 3090 and some 34 billion parameter quantized model. I think it would be nice to implement something like this as the repo map I find is not very useful and kind of a waste of tokens for large projects. It seems to just get randomly cut off. I'm working on a project with almost 20k commits, and the repo map just doesn't cut it. Maybe a default approach and some example classes of how you can override to make your own repo map could be insightful for the community, and we could use these recipes out of the box or as a base to customize.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You just need to implement a `RepoMap` class in `aider/repomap.py`. I believe the only 2 public methods are the `__init__()` and `get_tags()` methods.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue any time.
