### ISSUE TITLE
aider does not see files to available or writable [Bug]

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#395]
Main issue:

```
$ aider FOO
(...)
 If it's available and public, please add the `FOO` to the chat so I can provide the necessary changes.
 ```

I had already in past some messages of aider asking to provide file in read-write mode , which I added when lanuching for interactive mode ,e.g. `$aider foo bar` and later I had to `/drop foo` and `/add foo` to make aider to be able to use them.

I can not apply same trick in iteractive mode , as I can not give list of multiple messages... (e.g. -f 1st.md -f 2nd.md -f 3rd.md ....) however still it's topic for another issue...

Issue is that `aider -f msg.md foo bar`  complains that can not edit `foo `and asks   to add it to repository:

Fragment from `.aider.chat.history` :

```
# aider chat started at 2023-12-07 23:52:49

> Aider v0.18.1-dev  
> /home/gw-t490/.local/bin/aider --model gpt-4-1106-preview --message-file /tmp/tmp.Fu03ztRji6 docker/Dockerfile README.md (...)
> Model: gpt-4-1106-preview  
> Git repo: .git  
> Repo-map: using 1024 tokens  
> Added README.md to the chat.  
> Added docker/Dockerfile to the chat.  
(...)
> Use /help to see in-chat commands, run with --help to see cmd line args  
(...)
 If it's available and public, please add the `docker/Dockerfile` to the chat so I can provide the necessary changes.
 ```
 
Again, in past I had also asking files for read-write....

Or maybe it's not a bug but my misunderstanding how to provide files into aider "writable files" context?

**Comment by gwpl** [comment]
However it is hard to reproduce from scratch on small fresh repository, so probably happens when I am adding a lot of files into context.

For small examples works:

```
git init
touch FOO BAR ZOO
git add .
git commit -m 'init'
for f in `seq 1 10` ; do aider --model gpt-4-1106-preview --message 'add short joke to any of available files!' FOO BAR ZOO ; done
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Have you tried upgrading to the latest v0.19.x version of aider to see if this problem is better? There have been a number of relevant changes that should help.

**Comment by gwpl** [comment]
Thank you for following up on Aider! Sometimes it's so helpful!

So, even I am using version from HEAD of git repository, I still can observe sometimes chat asking "It will require changing FOO in following way <THEN DIFF FOLLOWS>  (...) please provide file to be writable."...

My current work around is that I simply respond insisting "Please, implement proposed changes in file FOO" or things like that, and then it suddenly understands that file is writable and implements earlier proposed change, so in that sense I see improvement , as IIRC me insisting month ago was not helpful.

**Comment by paul-gauthier** [comment]
Closing as a dup of #355 .
