### ISSUE TITLE
Configurable Prompts: Starting with Commit Message

### ISSUE THREAD

**Issue by aniruddha-adhikary** [paul-gauthier/aider#398]
If we want commit messages to follow a certain format, there is no way to configure it. We could add configuration / arguments to `aider` for customising the prompt for generating commit messages.

For example, a team may choose to commit with a short word descriptor (fix/feature/refactor/chore).

`refactor: add type definitions to orphan functions`

Currently this requires editing the source. A `yaml` configuration could be very helpful!

I'd like to help out to contribute this, but not sure if is appropriate as command-line argument?

**Comment by tastyblob** [comment]
Here's a basic PR to possibly work off of: https://github.com/paul-gauthier/aider/pull/494

**Comment by paul-gauthier** [comment]
This is possible with the `--commit-prompt` switch now.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
