### ISSUE TITLE
Error running aider..

### ISSUE THREAD

**Issue by PublicTrades** [paul-gauthier/aider#40]
Hello, after setup and attempt to run aider, I got this error:

```
admin@AFVFHGQBRQ6L7 aiderEngineer % aider justtest.py
zsh: command not found: aider
admin@AFVFHGQBRQ6L7 aiderEngineer % zsh --version

zsh 5.9 (arm-apple-darwin21.3.0)

via Codespace (testing)
👋 Welcome to Codespaces! You are on our default image. 
   - It includes runtimes and tools for Python, Node.js, Docker, and more. See the full list here: https://aka.ms/ghcs-default-image
   - Want to use a custom image instead? Learn more here: https://aka.ms/configure-codespace

🔍 To explore VS Code to its fullest, search using the Command Palette (Cmd/Ctrl + Shift + P or F1).

📝 Edit away, run your app as usual, and we'll automatically make it available for you to access.

@PublicTrades ➜ /workspaces/aiderEngineer (main) $ aider test.py
bash: aider: command not found
@PublicTrades ➜ /workspaces/aiderEngineer (main) $ 
```

How can I resolve?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and letting me know about the issues you are having.

Those error messages make it look like either aider hasn't been installed or it's been installed somewhere that isn't on your shell path. Did you run `pip3 install aider-chat` to install aider? If so then there might be a problem in your local shell or python configuration.

You could try invoking aider with `python3 -m aider.main` instead.

If that doesn't work, it may be hard for me to help debug the issues with your local environment.

**Comment by PublicTrades** [comment]
Hello, 
No worries, I was looking for something like aider so I'm happy to try it out. Unfortunately I didn't get to actually use because of the `zsh` path issue. I think aider under the hood aider uses `gpt-engineer` (i may be wrong), and what happened after installation was somehow my `zsh path` was modified. Took all day to fix the issue - even after several `zsh / yarn` install I still got the error message `zsh: command not found: aider` or `any of my other package that i previously installed including yarn`. Again, I love the concept, I would like to install it again if I can run it without such error, but I don't wanna deal with the headache of having to setting up and configuring my sys if it breaks anything.
