### ISSUE TITLE
command to scrape a webage and add it's content to the chat context

### ISSUE THREAD

**Issue by omri123** [paul-gauthier/aider#400]
Hi, I added a /web command to scrape a webpage and add it to chat context.
I would like to upstream it. Would you like to have it in your repo?
I am asking before creating a pull request, because it depends on other local changes of mine.
Thanks
Omri

**Comment by omri123** [comment]
https://github.com/omri123/aider/commit/ab26cc0ebd628f11bfef1afe69a788164ffd848c

**Comment by leewsimpson** [comment]
would love this feature !

**Comment by paul-gauthier** [comment]
I just pushed a new `/web <url>` command to the main branch. This will scrape the url and turn it into fairly clean markdown and then add it to the chat. 

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works for you.

**Comment by omri123** [comment]
Wonderful! I will try. I am closing the issue
