### ISSUE TITLE
Not able to build the Docker Image

### ISSUE THREAD

**Issue by krishnashed** [paul-gauthier/aider#407]
Hi! 

The docker image build is failing, when I tried using the command:

docker build -t aiderimage . 

![image](https://github.com/paul-gauthier/aider/assets/60742358/819f8e77-2cd3-4807-994f-696fda38ac2f)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Looks like the docker image is building fine in CI?

https://github.com/paul-gauthier/aider/actions/workflows/docker-build-test.yml

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
