### ISSUE TITLE
benhcmark.py arguments

### ISSUE THREAD

**Issue by apcameron** [paul-gauthier/aider#408]
Please add support for  this argument--openai-api-base=...  to benchmark.py 
In the past I was able to run it using something like this
OPENAI_API_BASE=http://192.168.0.118:5001/v1 OPENAI_KEY=dummy python3  benchmark/benchmark.py "magicoder-s-ds-6.7b._8bit"  --model gpt-3.5-turbo-16k --new --tries 2 --threads 1 --edit-format whole --verbose

The current version does not seem to work using this format.

**Comment by joshuavial** [comment]
you need to edit the benchmark.py file directly and set the base_url on the open ai client instantiation - https://github.com/paul-gauthier/aider/pull/379/commits/d4e663f7bc60135749da0381a245420d4d49c991 is what I did to make it work with openrouter.

**Comment by apcameron** [comment]
@joshuavial @paul-gauthier Yes It is possible to make it work by changing the code but I should not have to.
It used to work fine until somebody removed that functionality.
It should be added back to the code so it can be used out of the box like in the past.

**Comment by paul-gauthier** [comment]
I think the changes from @joshuavial PR #379 have added support for `OPENAI_API_BASE` to the benchmark script.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by apcameron** [comment]
@paul-gauthier I tried it today but still get the same error
OPENAI_API_BASE=http://192.168.0.118:5001/v1 OPENAI_KEY=dummy python3  benchmark/benchmark.py "NewHope"  --model gpt-3.5-turbo-16k --new --tries 2 --threads 1 --edit-format whole --verbose
...
SYSTEM Create a new file you MUST return a *file listing* which includes an appropriate filename, including any appropriate path.
Connection error.
Retry in 0.8 seconds.
Connection error.
Retry in 0.9 seconds.

**Comment by paul-gauthier** [comment]
What version of aider are you using? When reporting issues, it's helpful if you can include the full set of "announcement" lines that aider prints on launch.

**Comment by joshuavial** [comment]
The first thing I'd try is to put a print in the benchmark.py and see if the env var made it through so you can rule out having connection / port issues vs a problem in aider.

I recall having issues connecting from docker to a local llm, the solution in that case was to switch out to host.docker.internal - I don't think that's what is happening here though as you're referencing your local address explicitly, but it's the same category of problem that would be nice to rule out.

**Comment by apcameron** [comment]
Here is the version I am running
 Running setup.py develop for aider-chat
**Successfully installed aider-chat-0.20.1.dev0**
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@30529aba8e18:/aider# OPENAI_API_BASE=http://192.168.0.118:5001/v1 OPENAI_KEY=dummy python3  benchmark/benchmark.py "NewHope"  --model gpt-3.5-turbo-16k --new --tries 2 --threads 1 --edit-format whole --verbose
Copying /benchmarks/exercism-python -> /benchmarks/2024-01-08-23-16-15--NewHope ...
...done
main_model: gpt-3.5-turbo-16k
edit_format: whole
fnames: /benchmarks/2024-01-08-23-16-15--NewHope/beer-song/beer_song.py
Model: gpt-3.5-turbo-16k using whole edit format
Git repo: none
Repo-map: using 1024 tokens
Added beer_song.py to the chat.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by apcameron** [comment]
I can confirm that is is resolved
