### ISSUE TITLE
Using logs to building a custom dataset for fine tuning other LLM

### ISSUE THREAD

**Issue by nkeilar** [paul-gauthier/aider#410]
We have a big project with 20k commits. I'm looking for a way to generate training data sets. I like the idea of crawl, walk run, when it comes to adopting AI. I have some of my team using aider to code, which is resulting in discussion / data being generated. Some of it good, some of it not good. I'm wondering if anyone has explored creating data set for fine-tuning other models down the track? We can start with aider off the shelf now, then later use the data to train our own fine tuned model and use that for improved responses. 

I guess the dataset could be fine tuned to produce the new structured diff format... thoughts? 

Feel free to delete or close, as I'm not sure if this is within the scope of this project, but I felt the community may be struggling with the same thing.

**Comment by paul-gauthier** [comment]
There have been discussions in discord about using aider chat logs to fine tune models. I'm not aware of anyone actually making concrete progress on it yet though.

**Comment by R-Rudolf** [comment]
Here is a somewhat relevant paper about agentic fine-tuning:

https://fireact-agent.github.io/

**Comment by R-Rudolf** [comment]
And am exact match for an enthusiastic blogpost:

https://blog.continue.dev/its-time-to-collect-data-on-how-you-build-software/

The whole continue.dev may became a competitor/alternative to this project.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
