### ISSUE TITLE
AIDER + TLDRAW (MakeReal) ⚡

### ISSUE THREAD

**Issue by fire17** [paul-gauthier/aider#414]
Hi there!
I'm working on integrating aider and tldraw 🍀 
Hope yall are familar with [MakeReal](https://makereal.tldraw.com)
![image](https://github.com/paul-gauthier/aider/assets/9356048/f47e315e-1b7e-4f11-967e-d5fa506fa1de)

I've already seen @joshuavial adding images to the context in PR #379 (should probably check it out)
so assuming this is already solved **the only other thing i need from aider is:**

**1. Access aider through API, not only CLI**
  *  should enable us to use aider asynchronously and control it externaly, by using the makereal interface

This is how i envision it, more or less
![image](https://github.com/paul-gauthier/aider/assets/9356048/62efd7fb-62aa-472f-93bc-1d25521b5846)

I'm working concurrently the changes needed on aider, and on tldraw's makereal side,
If anyone wants to give me a hand and make this possible please write so in the comments ❤️ 

Thanks a lot and all the best!

**Comment by paul-gauthier** [comment]
This faq entry might be helpful:

https://aider.chat/docs/faq.html#can-i-script-aider

**Comment by fire17** [comment]
Thanks! I'm pretty sure this is exactly what i was looking for @paul-gauthier 
### Python
#### You can also script aider from python:
```
import openai
from aider.coders import Coder

# Make an openai client
client = openai.OpenAI(api_key=os.environ["OPENAI_API_KEY"])

# This is a list of files to add to the chat
fnames = ["foo.py"]

# Create a coder object
coder = Coder.create(client=client, fnames=fnames)

# This will execute one instruction on those files and then return
coder.run("make a script that prints hello world")

# Send another instruction
coder.run("make it say goodbye")
```

couple of questions please.. (i'll also dig and checkout for myself, but for might be good for others aswell)

When using `create(` can i also pass other args like the cli accepts?
I presume using `run` multiple times, retains the memory,
can we also send commands like `coder.run("/clear")` and other `/commands` ? like getting back `/tokens` etc.
And in general is using aider from python completely feature equivielent to using aider in the cli, or there are some caveats, and flows that work only from the cli?

Thanks a lot for the answer :) 
Please let me know what you think of the Aider+MakeReal idea, with that this issue can be closed :)

**Comment by paul-gauthier** [comment]
You can send multiple messages, but you can't call `run()` with `/commands`.

And yes `create()` will accept many arguments. Please look at the `aider/coders/base_coder.py` file and the other `XXXCoder` classes.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
