### ISSUE TITLE
Tweaks needed for isolated use

### ISSUE THREAD

**Issue by brayrobert201** [paul-gauthier/aider#418]
Hi,

Just a couple of tweaks needed for use in isolated environments.

1. Disable version check. That just sits there forever. I'd commented out
```check_version(io.tool_error)```
in main.py
But a flag would probably be better.

2. If there's no external connectivity and the file is missing, refer to instructions on downloading and referring to tiktoken (possibly add a variable saying where it's stored)
This worked well for that.
https://stackoverflow.com/questions/76106366/how-to-use-tiktoken-in-offline-mode-computer

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider's main use case is to work with OpenAI's apis. So support for running aider in "isolated environments" is not currently a high priority.

**Comment by brayrobert201** [comment]
Reasonable. In this case, an OpenAI compatible proxy is used to connect to the openai API.

Basically to allow for monitoring/control of how the API gets used and to allow bulk switching to other compatible services in the future.

Happy new year, BTW. Thanks for what you've done with this.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by paul-gauthier** [comment]
There's a `--skip-check-update` switch now, which might be helpful.  The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by brayrobert201** [comment]
Sorry about the delay in testing. It's lovely. Thank you
