### ISSUE TITLE
[Info] How to install Aider on Windows

### ISSUE THREAD

**Issue by Michal-Mikolas** [paul-gauthier/aider#42]
Since I had troubles installing Aider on Windows, I finaly managed it with these steps: 

1. `> pip install aider-chat --user`
2. `> $env:OPENAI_API_KEY='sk-...`
3. This created `aider.exe` in `c:\users\%username%\appdata\roaming\python\python311\scripts\` folder. But this folder was not added to PATH by default. So you need to add the folder to yout PATH manually. Be avare the folder will be different for different versions of Python.

**Comment by paul-gauthier** [comment]
Thanks for the helpful info.

I updated the README with a bit more windows specific install information.
