### ISSUE TITLE
Unable to import `sounddevice` and/or `soundfile`, is portaudio installed?

### ISSUE THREAD

**Issue by BenGWeeks** [paul-gauthier/aider#423]
Is voice supported from VS Code?

````
> /voice                                                                                                                         
Initializing sound device...
Unable to import `sounddevice` and/or `soundfile`, is portaudio installed?
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Is portaudio installed? See the install instructions: https://aider.chat/docs/install.html#install-portaudio-optional

Can you use `/voice` if you run aider in a terminal not inside VSCode?

**Comment by BenGWeeks** [comment]
Ah no. I'm actually doing this in a codespace (in a Windows browser) so possibly not possible?

**Comment by paul-gauthier** [comment]
Ya, probably can't use voice in that environment.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
