### ISSUE TITLE
About model updates, issues in code replace

### ISSUE THREAD

**Issue by ramses3** [paul-gauthier/aider#425]
I like the project, we tried it weeks ago, but still a lot of inconsistency on how openai models works on aider, im thinking in fine tuning deep seek coder to be very consistent with aider, i can do it myself and do it closed for my group, but maybe we can start something much better if more people get involved, can create a group in discord/telegram or slack to model the ai to our requirements instead of changing aider everytime gpt4 is updated or lobotomized

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

We have a channel on discord that discusses using aider with non-OpenAI models. Deep seek coder seems like the best of the open models based on benchmarking done by users.

https://discord.com/channels/1131200896827654144/1133060780649087048

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
