### ISSUE TITLE
[scripting][`--message-file`] Aider asks in interactive way. Feature request:  `--non-interactive` or `AIDER_NON_INTERACTIVE=true` support for scripting AIDER from Command Line

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#426]
When playing with `aider` from command line ( https://aider.chat/docs/faq.html#can-i-script-aider ):

```
aider --message-file PROMPT.FILE  #AKA aider -f PROMPT.FILE
```

I've encountered situation that it asked me if to "add files FOO BAR ?" 

and this stopped my automation obviously ;).

Any ideas how we could tackle this?

// Btw. here is small template for those that want to experiment with trees of generations: https://github.com/CLIAI/hello_world_three_of_generations_aider_CLI    ; when I was playing with it I encountered at some point above situation in one of generations.

**Comment by paul-gauthier** [comment]
You can use `--yes` to always answer yes to questions.

Or you can script aider from python for some more control.

https://aider.chat/docs/faq.html#can-i-script-aider

**Comment by gwpl** [comment]
If `--yes` is way to go,

Can we have equivalent `--no` (or `--yes=false?` :P) flag ?

( I do not see (`aider --help|grep no`) equivalent `--no` flag. )

Also maybe worth adding line to FAQ to command line section: https://github.com/paul-gauthier/aider/pull/433

**Comment by paul-gauthier** [comment]
Why do you want to run aider with `--no` ?

**Comment by gwpl** [comment]
As we know LLM can be confused if given too much in it's context window.

I've found that with some queries `aider` is asking to add files to context that are not relevant.

When `aider` asks to add weird irrelevant files I would like to respond `--no` by default when scripting aider. 

That way, when I script `aider` to run it programatically, I could make it stick to set of files I provided via command line.

**Comment by paul-gauthier** [comment]
If you are trying to do any sort of non-trivial scripting of aider you probably should script it using python. That will give you a lot more control.

**Comment by samreid** [comment]
I faced the same question today. I want to automate aider to visit several files non-interactively, so I followed the directions for command line scripting (using --message-file) at https://aider.chat/docs/scripting.html, but aider prompted me twice:

```
Add js/common/model/ControlPoint.ts to the chat? (Y)es/(N)o/(D)on't ask again [Yes]: N                                                                                                                 

https://github.com/phetsims/energy-skate-park/issues/387
Add URL to the chat? (Y)es/(N)o/(D)on't ask again [Yes]: N         
```

So I was looking for a `--non-interactive` or equivalent mode. I read in this issue and in https://github.com/Aider-AI/aider/issues/1375#issuecomment-2339363654 that scripting is a way to get more control, but scripting is described as non-stable, and is also significantly more complex than using the command line. So anyways, I thought I would post a +1 here before I investigate python scripting.

**Comment by gmile** [comment]
Using aider since yesterday. Stumbled upon this issue too today. In my case, I am providing examples based on specific file names, and would like to say "no" when aider asks me if I want to include the files. Here's my sample scripting attempt:

```fish
#!/usr/bin/env fish

set paths \
  'path/to/file1.ex' \
  'path/to/file2.ex'

for file in $paths
  set message '
  analyze included file like this...
  your task is to: ...

  rules/examples:
  - if you\'re analyzing fileX.ex file, the JSON object you must update is called ObjectX
  - if you\'re analyzing fileY.ex file, the JSON object you must update is called ObjectY
  '

  GEMINI_API_KEY=... aider --model gemini/gemini-2.0-flash --message $message --file $file --file schema.json
end
```

Seems like in my case I am able to work around aider always asking me by providing names of non-existing files in the prompt. Alternatively, at the expense of adding a handful of extra tokens on each cycle, I could provide `--yes` flag.
