### ISSUE TITLE
[scripting][`--message-file`] Can we specify `aider --message-file` return value?

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#427]
Can we specify `aider --message-file` return value?

e.g. that `aider --message-file` returns `0` (success) if managed to make (and commit) changes, otherwise non zero ?

**Comment by gwpl** [comment]
Back story, how I arrived here:

I've encountered this when playing with scripting (here is toy example template to build on: https://github.com/CLIAI/hello_world_three_of_generations_aider_CLI ).

Bascially, in my usecase, if aider generated commit, I would like to `git add .aider.chat.history` and depending if aider made commit then I would like to ammend it to add history with `git commit --amend --no-edit` otherwise I want to add fresh commit (as only history changed) e.g. with `git commit -m 'No changes. Only history update' `.

**Comment by paul-gauthier** [comment]
You should probably be scripting aider using python if you want to do these sorts of things?
