### ISSUE TITLE
Small Feature Request: Please add --check-update to make aider check for update and return status

### ISSUE THREAD

**Issue by zackees** [paul-gauthier/aider#432]
Hi there, I'm willing to do a PR for this if it would get in.

This feature would help in tooling. I'd like to be able to just run `aider --check-update` and see if there is an update or not, without then entering into prompting mode.

The reason this is useful is for integrations, where aider is a tool backend. For example, my command set `zcmds` has a commandlet called `aicode` that is just a wrapper around aider that provides a more streamlined experience, both for the developer experience but also to isolate the install of aider through pipx so that it's complex pinned dependency tree doesn't screw up the rest of my system.

I'd like for my tool to be able to run `aider --check-update` in a background process and then on the next run inform the user that there is a pending upgrade and whether they want to do it.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I asked aider to make this change: bd1c8b625d2ae15d833aa024a9325cecebf289f3.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works for you.

**Comment by zackees** [comment]
I'm crunching right now with a couple of projects. But after the next release, I will test the feature from pip, and the release after that I will report whether it works or not.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by zackees** [comment]
Hi, saw your new update and decided to check the functionality.

Good: Check update works as expected.

Bad: It's now obvious I need a flag `--skip-version-check`, because now my tool reports the correct upgrade path and also the original one:

![image](https://github.com/paul-gauthier/aider/assets/6856673/342745d1-4d3b-4364-a6da-bd33fdb3d3f7)
