### ISSUE TITLE
Question: Dynamic token count based on content length

### ISSUE THREAD

**Issue by tastyblob** [paul-gauthier/aider#434]
I'm currently calling aider with a bash function that uses https://github.com/felvin-search/token-count to calculate the total token count of the passed files and passes the result as argument for `--map-tokens`. Ever since 0.20.0 there's a warning that map tokens > 2048 can confuse GPT. Does this apply in all cases? Is there any point in dynamic calculation of map tokens as I'm currently using it?

**Comment by paul-gauthier** [comment]
I haven't done extensive benchmarking to measure the impact of extra large repo map context. But there tends to be diminishing returns if you send too much context that's not relevant to the task at hand. GPT can get confused or distracted.

There's certainly no problem with experimenting with larger repo maps. I added a warning just so folks know that bigger isn't always better.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
