### ISSUE TITLE
Is it possible to load the prompt from a file ?

### ISSUE THREAD

**Issue by b4git** [paul-gauthier/aider#436]
Instead of typing out the whole query in terminal, is it possible to write the query in a text file and have the aider read from it?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Yes, you can use `--message-file <filename>` to do this. Also try running `aider --help` for a list of all the options.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
