### ISSUE TITLE
how to optimize costs ?

### ISSUE THREAD

**Issue by younes-io** [paul-gauthier/aider#437]
I use aider in a codebase, and every time I run, it calls the OpenAI API with the codebase map I suppose and all the context, and since I use gpt4, it's quite expensive to spend a few dollars just in the "init" process..
I was wondering if there's another way to avoid this... would it be possible to locally store aider's map / context of the code ?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider doesn't send messages to GPT until you type something into the chat. There's no startup API activity that would incur costs.

What makes you think it's costing "a few dollars just in the init process"?

**Comment by younes-io** [comment]
I have this impression that after the first chat with aider (what I call the "init process") the cost is high... usually I would stop right away.. maybe because the context is big ? That's what I want to understand..

**Comment by paul-gauthier** [comment]
How are you determining that "the cost is high"?

Aider can tell you how many tokens it is using per message and how much they cost if you use the `/tokens` command in the chat.

I might be able to help more if you show me a screenshot of what aider prints on startup and what it prints from the `/tokens` command.

**Comment by Agupta00** [comment]
Would it be possible to have the gpt output tokens be in "quick english" to reduce the amount of tokens and thus pricing ?
Perhaps this could be a flag in aider.

For example ; 

```
I apologize for the oversight. Let's correct the diffs based on the actual content of the
files.

For frontend/src/actions/cardActions.js, we will modify the fetchCards function to make an
API call to the backend to fetch the cards:
``` 

Vs

```
Correct diffs, use file contents. 
frontend/src/actions/cardActions.js -modify- fetchCards function
``` 

or Altogether removing the commentary and just showing the diffs is another idea

**Comment by paul-gauthier** [comment]
If you are concerned about optimizing costs, you could use `aider -3` to run with gpt 3.5 turbo.

**Comment by gwpl** [comment]
Also maybe installing proxies will help in analysis of traffic/cost patterns.

Here is one of possibilities I came across:
https://docs.litellm.ai/docs/proxy/virtual_keys#tracking-spend

Is anyone using some openai API calls proxy for measurements/cost/performance/logging/archival/other_purposes ?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by Roald87** [comment]
Love the tool! But I quickly reached my $5 limit that I set. I was quite surprised that I reached it so quickly, because it was just a small project.

If I check the costs I get: `$ 0.09    9,155 tokens total`. But when I look at my openai there were 18 calls with 770,000 context tokens (!) and 5,000 generated tokens. Where do these context tokens come from? 

Is it maybe the git tree? I don't think it is that big right?:

```
➜ git count-objects
196 objects, 545 kilobytes
```

**Comment by paul-gauthier** [comment]
The /tokens command tells you the approximate cost to send each message. It can't estimate the cost of the reply tokens. 

So at about 10 cents per sent message it would take less than 50 messages to use up $5. 

If you run aider with --no-stream it can report actual cumulative costs. 

Also, what model are you using? Running with --4turbo will use the very cost effective gpt4 turbo.

**Comment by Roald87** [comment]
Thanks ill try it with the --no-stream option to see the cumulative costs. 

I'm launching aider without extra arguments, in that case it uses gpt4-turbo right?
