### ISSUE TITLE
Option to let Aider stage the changes without committing them ?

### ISSUE THREAD

**Issue by Hexodus** [paul-gauthier/aider#438]
I know that there is an option to show the diff in the terminal but IDE's are naturally better suited to show the changes visually. So I wonder if Aider has an **option to stage all changes without committing them unless asked to do so**? That would allow me to check the changes in VSCode to see exactly where and what was changed.

I've already checked the option list with /help but am not sure if e.g. `--no-auto-commits` would have the desired effect.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Try `--no-auto-commits`, which will leave the commits dirty in the repo. Your IDE should be able to show you the diff.

**Comment by Hexodus** [comment]
Thanks a lot! This works fine 👍
