### ISSUE TITLE
Question: What is the best approach to handle read-only vs read-write SECTIONS of files?

### ISSUE THREAD

**Issue by gwpl** [paul-gauthier/aider#443]
I hope it's ok I ask question here (as we lack "discussions" section, hopefully re-purposing issue is ok).

I came into following wonderings.
There are cases when one wants Aider to not modify some sections of file, and is fine with others.
It can be either due to organisational reasons (this part of code I wrote, other part wrote someone else...),
or due to files structure. Regarding second case , my strong use case is having Unit Tests in same file , e.g. in Rust it's common to have unit tests section at the end of file. And let's assume in TDD style we have tests that define expectations about behaviour, and code failing. We don't want Aider to change tests section, only rest of the file.

What would be best way to approach it?

Yes, I understand that probably it's use case to use aider via programming library, still, few options coming to my mind...

**Comment by gwpl** [comment]
Natural, naive approach that comes to my mind:

* say in prompt "Keep unit tests as they are!" and check if "read-only" section was modified , if yes, reject changes (i.e. /undo) and try again...

Here I can imagine Aider sometimes ending up in loops... to reduce probability that LLM wants to modify not allowed section, maybe:

* additionally one should inject comment around read-only section ```// READ ONLY SECTION STARTS HERE DO NOT MODIFY``` + ```// READ ONLY SECTION FINISHES HERE. READ-WRITE STARTS AGAIN```...

Wondering if my idea is correct or you knowing low level workings of aider and how ti's forced to make changes on code, maybe there is better way to do it (or add such programmatic functions to aider)

**Comment by harleypig** [comment]
I include comments to the file that begin with `// AIDER: simple instructions` and end with `// AIDER: END`.

Then I include in my prompt an instruction follow any comments beginning with '// AIDER: ...'.

It doesn't always work, but I find it convenient for the most part.

**Comment by paul-gauthier** [comment]
Ya, I usually just tell it not to change xyz in the chat.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
