### ISSUE TITLE
It doesn't know simple things like run a diff???

### ISSUE THREAD

**Issue by bayeslearner** [paul-gauthier/aider#445]
```
run a diff of the last git version and working copy and explain the difference.

I'm sorry for any misunderstanding, but as an AI, I don't have the capability to access your file system or version control systems like Git to run commands or check the differences between files. My functionality is limited to processing the text provided to me in this conversation.

To assist you with understanding the differences between two versions of a file, you would need to provide both versions of the file or the diff output. Once you provide that information, I can help explain the differences. If you have a diff output from the changes you made to the Vagrantfile, please share it here, and I will explain the changes to you.
```

**Comment by gwpl** [comment]
Glad to see more people trying Aider!

Aider is more "low level" tool. It is not running commands for you. It is transforming text.

Therefore if you want it to take output of command into consideration you need either:

## use brackets
```
{
I've run command below, could you take output in consideration when implementing X ?
$ command bla bla
output...
...
}
```

OR just use `/run` and you can use bash commenting `$ command # comment`  to inject prompt:

e.g. 
```
/run git diff HEAD^ # Could you please explain the difference and impact of following changes in information dense language for technical expert? Use bullet points and formatting to structure output in more readable and information dense way.
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by bayeslearner** [comment]
I think it’s confused about whether to run LLM or perform tool use? Are you saying adding /run will help it somehow?

**Comment by transcendr** [comment]
@bayeslearner you told it "run a diff of the last git version and working copy and explain the difference." ... it is correct, an AI language model can't do anything of the sort (unless it's set up to use function calling which aider is not). If you want Aider to analyze something,  you to provide it that something.  You can do that by either copying and pasting manually the output of `git diff xyz` or you can use the the `/run`  command which will run the command you give as an argument, and then provide the output of that command to Aider.  To inject additional prompt after the output, @gwpl  suggested appending `# your additional prompt here` to the run command.  Also, Aider is extremely well documented, and so you can use `--help` or `/help` (in chat), or go to aider.chat to understand the /run command. Or maybe just... try it?
