### ISSUE TITLE
Rate limit immediate error

### ISSUE THREAD

**Issue by iliakan** [paul-gauthier/aider#447]
```
Aider v0.21.2-dev
Model: gpt-4-1106-preview using udiff edit format
Git repo: .git with 3,382 files
Repo-map: using 1024 tokens
```

I added a bunch of files with `/add **/*.js` and asked "Where is login implemented?"

After the question it immediately died with error 429:

Request too large for gpt-4-1106-preview in organization org-XXXXXX on tokens per min(TPM): Limit 600000, Requested 936788. The input or output tokens must be reduced in order to run successfully.Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'

I believe, it sends ALL my js to ChatGPT.

I've read about "repository map", but I can't see if it's being sent. How can I see it?

I tried asking questions when files are added in aider and not added.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You should not add tons of files to the chat. Just add the files that you want aider to edit for the task at hand.

By adding all the files, you're sending them all to openai on every chat request and completely exceeding their rate limit for how many tokens you can send them per minute.

See #205 for more info on the rate limit error response.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
