### ISSUE TITLE
/undo immediately re-executes the prior command

### ISSUE THREAD

**Issue by mikehearn** [paul-gauthier/aider#450]
On latest Aider `/undo` doesn't seem to work. It undoes the commit and then re-executes the last request, meaning the AI just goes around in a circle and does the change all over again.

**Comment by paul-gauthier** [comment]
I made some changes to tell GPT to not just make the same changes again. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by mikehearn** [comment]
Thanks. Apologies I didn't have time to try this out. I only get to play with Aider occasionally at the moment.
