### ISSUE TITLE
add `--skip-version-check`

### ISSUE THREAD

**Issue by zackees** [paul-gauthier/aider#452]
Please add `--skip-version-check` to support better tooling.

This is what my wrapper looks like now, printing both the correct version upgrade mechanism and the previous one.

![image](https://github.com/paul-gauthier/aider/assets/6856673/b142f908-caf4-4f40-ac65-c059984924f3)

I'd like to do `--skip-version-check` when I call into the `Aider` backend with my custom configuration stack.

Thanks again for this amazing tool! it's like stepping into the future.

**Comment by paul-gauthier** [comment]
Thanks for the PR, merged.
