### ISSUE TITLE
+ sign to not show, but only colour

### ISSUE THREAD

**Issue by lvalics** [paul-gauthier/aider#455]
Hi, Is there a way/settings to not have this + or - sign on diffs, just the color decide if is was added or deleted from the code? I use dry-run and I always need to replace the + signs.
<img width="105" alt="image" src="https://github.com/paul-gauthier/aider/assets/27447535/e4c1c1af-bdfb-45a9-b7b8-76f593dfcb3e">

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Why not just stop using `--dry-run` and let aider make the edits for you?

**Comment by lvalics** [comment]
By allow to edit  AI the code in most of the case is ok, but sometimes is not. Also if I copy the code by myself is easier to learn the code, to understand it better. I prefer to control what I add to the code. Of course I know I can use undo, never tried.
It would help me to not be the plus sign there, is this possible? Thank you.

**Comment by paul-gauthier** [comment]
There's no way to suppress the +/- signs. They are a critical part of the unified diff editing format.

I really suggest dropping `--dry-run`. You can always do `/diff` to see the exact changes that were made and `/undo` to revert them.

**Comment by lvalics** [comment]
Already have done that, Thank you!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
