### ISSUE TITLE
[BUG] aider outputs numerous copies of messages 

### ISSUE THREAD

**Issue by vincanger** [paul-gauthier/aider#457]
```
Aider v0.22.0
Model: gpt-4-0613 using diff edit format
Git repo: .git with 22 files
Repo-map: using 1024 tokens
```

I can't follow aider's logs as it outputs numerous copies of the same message. In the end, the changes/commit execute correctly but my terminal is entirely cluttered. 
<img width="929" alt="image" src="https://github.com/paul-gauthier/aider/assets/70215737/6eae66ec-93d1-4ca8-a90c-650ae561a8c0">
<img width="816" alt="image" src="https://github.com/paul-gauthier/aider/assets/70215737/6e7cef98-4d4b-43aa-a7ca-09766924b458">

**Comment by davidmoshal** [comment]
+1 , it seems that trying to scroll back is one trigger, after which the console output overwrites itself numerous times

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
