### ISSUE TITLE
New turbo model and /tokens pricing calculations and context only 8K

### ISSUE THREAD

**Issue by transcendr** [paul-gauthier/aider#458]
- Aider version: 0.22.0
- Model being used: `gpt-4-turbo-preview`
- Other switches or config settings that are active: `--dark-mode`

When running the `/tokens` command the calculated prices appear to be for the base `gpt-4` model (approx 2-3X).  I think this is a simple calculation bug, but I wanted to confirm. The model at the top of the aider conversation is correctly stated as the one I've passed in as `--model`. 

For reference, here is the token output. Typically this kind of request would be closer to .05 rather than .12. And I tested pushing the context past the stated 8K limit and did not receive an error, even though /tokens says that the context window is exhausted.

```
Approximate context window usage, in tokens:

$ 0.05    1,538 system messages                                            
$ 0.03    1,065 repository map                                             use --map-tokens to resize
$ 0.02      699 internal/analytics/infrastructure/segment_provider.go      use /drop to drop from chat
$ 0.01      306 .ai/system/_task-plan.md                                   use /drop to drop from chat
$ 0.01      283 internal/analytics/infrastructure/segment_provider_test.go use /drop to drop from chat
$ 0.01      255 .ai/system/response-rules.md                               use /drop to drop from chat
================
$ 0.12    4,146 tokens total
          4,046 tokens remaining in context window
          8,192 tokens max context window size
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I've updated and corrected the pricing and other attributes of all the openai models.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
