### ISSUE TITLE
Tagging is broken

### ISSUE THREAD

**Issue by stefanmohl** [paul-gauthier/aider#460]
Since the latest v0.22.0 was released, there was no tag added to the git repo, so it is a bit of a guess as to what exact version was released. Maybe tagging broke in the latest release scripts?

**Comment by paul-gauthier** [comment]
What problem are you seeing? Tags look ok to me?

![image](https://github.com/paul-gauthier/aider/assets/69695708/98ea0a1d-712d-4021-b22f-ee2f4b4e1458)

**Comment by stefanmohl** [comment]
So do I, now. I am sorry (and a bit confused). It might be that I was looking at the wrong repo while being implicitly certain I was looking at the this repo. Sorry.
