### ISSUE TITLE
[Feature Request] Add a --follow-deps to optionally auto include local imports in given files

### ISSUE THREAD

**Issue by vesper8** [paul-gauthier/aider#461]
I'm wondering if this makes sense to you? In order to work more efficiently with aider and with GPT in general, I'm in the process of tagging all the features that exist in my large project and mapping all the files that are relevant to each feature. This got me thinking, when you pass a file to aider, to get the best answer it's sometimes best to also include all the other files that the one file interacts with, often those are imported inside the one file. So instead of passing a file and all of its imports manually, it would be nice to be able to instruct aider to pull in all the imported files with a simple flag. this would only pull in local imports (so not vendor imports) and it would only do this one level deep, or perhaps this depth could also be configured.

Would that be a cool feature? I think I'd use that.

Thanks for considering!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider already does quite a bit of work to send GPT relevant code context from elsewhere in your git repo. See this article about the [repo map](https://aider.chat/docs/repomap.html).

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
