### ISSUE TITLE
Feature Request: Add codellama model

### ISSUE THREAD

**Issue by Niqnil** [paul-gauthier/aider#463]
It was recently released and can be used through OpenRouter. 
**codellama/codellama-70b-instruct** and **meta-llama/codellama-34b-instruct** from https://openrouter.ai/docs#models

**Comment by olafgeibig** [comment]
I second this. Open source coding models are coming closer to GPT-4. I would propose to add a --4-alt CLI parameter that would use a prompting strategy that assumes GPT-4 capabilities without being specific for the actual GPT-4 variants. Moreover we would need to be able to set the context length when using a GPT-4 alternative. 

Just my 2ct regarding CodeLama. I would also like to experiment with it and I do believe its coding capabilities could be on par with GPT-4 but honestly the small context size actually is a show-stopper for productively using it with aider. Anyway, this may change as I expect coding models with larger context windows soon.

**Comment by paul-gauthier** [comment]
https://aider.chat/docs/faq.html#can-i-use-aider-with-other-llms-local-llms-etc
