### ISSUE TITLE
REQ: Break re-factoring down into new additions and then removals.

### ISSUE THREAD

**Issue by 5ocworkshop** [paul-gauthier/aider#464]
.22 is really great, but gpt4 still struggles with breaking larger functions down in to smaller pieces as it tries to make very large diffs and fails.  I have had good luck asking it to do one function at a time, and to do all the new adds as one diff, then once the functions are present and complete, go back and remove the duplicate code from the original function.  Not sure how this approach could be incorporated but wanted to mention that GPT4 is struggling with this particular task and this seems to be a way around it.

**Comment by heijligers** [comment]
bump
