### ISSUE TITLE
Problems copying a bug report

### ISSUE THREAD

**Issue by pietrosperoni** [paul-gauthier/aider#465]
Great project! I started using Aider. But the code it produced did not run. 
I had the code open in visual studio code and as soon as I tried to run it, it gave me some errors.
How am I supposed to progress from there? 
Because on ChatGPT I normally would have copied the errors report and I would receive informations on what to do. But when I tried to do this, since the report has a number of newlines inside, it would read each newline as the end of my feedback and start working from there. And then send the next line, respond to that, and so on. Is there a way to copy a block of text without this happening?

If not I could look into the bugs myself, but honestly I would rather have an aider that corrects my bug, and not me correcting the bugs of an aider :-).

Cheers

**Comment by pietrosperoni** [comment]
I discovered, if I copy immediately the error report, then it works. What instead does not work is to say a few words ("I just tested it and I got this error when i click this button. And here is the report: <CTRL-V>", and then copy the report. Then it copies the report, but it only reads it one line at a time.

**Comment by transcendr** [comment]
Just fyi, it's very hard to understand what you mean. In the age of AI, you can use it for a lot more than just coding -- for example, fixing your English and for general clarification if you're not very good at writing in a clear manner. There's really no excuse to write, especially a bug report, in broken English anymore. Then you may actually get a helpful response.

**Comment by paul-gauthier** [comment]
https://aider.chat/#tips

Use Meta-ENTER (Esc+ENTER in some environments) to enter multiline chat messages. Or enter { alone on the first line to start a multiline message and } alone on the last line to end it.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by pietrosperoni** [comment]
Thanks @paul-gauthier. I did not answer because I did not have the time so far to test what you said. But I appreciate you answering me. 
@transcendr I apologise if my request was not clear enough. It probably would be clearer if I added a video. But I am grateful Paul could understand it.
