### ISSUE TITLE
enhancement: would you be able to add indicative api costs you your examples?

### ISSUE THREAD

**Issue by rickoneeleven** [paul-gauthier/aider#466]
would be great to see in the examples how much the api cost was for each one. i'm guessing around a dollar?

**Comment by rickoneeleven** [comment]
understood. I was just thinking, as you worked through the examples, that at the end, there was the cost for whatever model you used in the example. For instance, when I was browsing the repository, my first question was, "What are we talking about here for API costs (for whatever model, maybe use GPT-4 Turbo for demonstration)? Is it costing $2 or $20 to run this demo using Turbo?"

If it's $20, and I know Turbo is a lot cheaper than GPT-4 base, then I know I'm not baller enough to play with this repo.

I don't know; I was more just talking you through my thought process as I browsed the repo and the first kind of thoughts that came to mind.

Thanks for all your work.

**Comment by paul-gauthier** [comment]
The costs you run up really depend on how you use aider and which models you are working with. The gpt 3.5 models are very cheap, but less capable. The new gpt-4 turbo models are a good compromise between cost and capability. The older gpt-4 models are the most capable, but also the most expensive.

**Comment by rickoneeleven** [comment]
understood. i guess I was just meaning for each example you show in your code examples, you'd have the api costs depending on whatever model you chose to use for each example. just a nice little quick sense for anyone new browsing the repo.

i understand what you mean, i think we may just view differently how useful the above would be, and that's cool.
