### ISSUE TITLE
Option to describe packages to use

### ISSUE THREAD

**Issue by user753** [paul-gauthier/aider#476]
I use tailwindcss in my project but If I just run aider and ask to create component it would use plain css.
I think it would be useful to have something like system prompt where I could describe all the packages I use in my project.
Something like `use tailwind, typescript, react, redux`

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. There's a FAQ entry that might contain helpful information:

- https://aider.chat/docs/faq.html#can-i-specify-guidelines-or-conventions
- https://aider.chat/docs/conventions.html
