### ISSUE TITLE
When scripting, can we have a boolean which answers 'y' to add newly created files when true

### ISSUE THREAD

**Issue by jamesdnexa** [paul-gauthier/aider#478]
Aider v0.24.1
No git repo found, create one to track GPT's changes (recommended)? y
Added .aider* to .gitignore
Git repository created in the current working directory.
Model: gpt-4-0613 using diff edit format
Git repo: .git with 0 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args

I am working with scripting.  I run `coder.run('Using the example of ...')`, and it decides the filenames based on the example.  But by default we see:

`Allow creation of new file models.py? no`

I understand when we create the coder, the example we're given reads:

```# This is a list of files to add to the chat
fnames = ["foo.py"]

# Create a coder object
coder = Coder.create(client=client, fnames=fnames)
```

Suggesting by adding files to the coder we're giving permission to make changes.  But I don't want to foretell what the newly created files will be in my example as it's better if it makes up it's own names based on the use case and the examples

Could we have 

`coder.run('Using the example of ...', True)`

as a way around this, so we can control the answer to the question of whether allowed to add?

Many thanks

**Comment by harleypig** [comment]
`aider -h` shows `--yes` ... have you tried that?

**Comment by jamesdnexa** [comment]
I have a workaround in place already actually, just thought it would be a good functionality for scripters.

If you have a local checkout in ./aider-env, you can go to:

`./aider-env/lib/python3.10/site-packages/aider/coders/base_coder.py`

And remove this code:

```
           if not self.io.confirm_ask(f"Allow creation of new file {path}?"):
                self.io.tool_error(f"Skipping edits to {path}")
                return
```

Now it won't ask.  Not the most elegant, but ok for my local auto / scripting version of aider for now - may well cause gremlins I haven't come across yet this way.

**Comment by paul-gauthier** [comment]
There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#can-i-script-aider

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
