### ISSUE TITLE
Respond to PRs

### ISSUE THREAD

**Issue by rjohnson318** [paul-gauthier/aider#48]
Can aider respond to PRs? Almost like a repo watcher, different developers can submit their code and aider tests it and if it passes a human can merge. If not it can add comments and code snippets to fix the errors.

**Comment by paul-gauthier** [comment]
Not currently, but it is certainly something that could be added to aider or built with it.

**Comment by paul-gauthier** [comment]
I'm going to close this issue since aider is not likely to support this use case directly any time soon. Feel free to reopen if you'd like to discuss further.
