### ISSUE TITLE
add folder instead of only add file

### ISSUE THREAD

**Issue by arist0v** [paul-gauthier/aider#480]
It could be usefull to be able to add a folder (CWD) so every file in that folder and sub-folder are automaticaly added to the context. Instead of having to add it one by one

**Comment by KennyDizi** [comment]
It would be a great feature.

**Comment by harleypig** [comment]
If you are using bash (there are similar ways to do this in other shells, but I don't use them so I don't know what they are) you can use `find`.
```
aider $(find dirname -type f)
```
But be careful ... `find` will find **all** files ... dotfiles, files aider and/or git is ignoring, etc.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It's usually a bad idea to dump a bunch of files into the chat. You just want to add files that *need to be edited* for the current task. [Aider will show GPT relevant context from the rest of the repo](https://aider.chat/2023/10/22/repomap.html), so you don't need to dump in "all the files".

That said, you can use wildcards with the `/add somedir/*.py` command. Or you can use wildcards on the command line `aider somedir/*.py`.

But really, you probably don't want to do this. Adding a ton of extra source code tends to distract/confuse GPT.

**Comment by arist0v** [comment]
The idea is to work on a project not just on some file, so having the rest
of the file help for context

Le sam. 24 févr. 2024, 10 h 23, paul-gauthier ***@***.***> a
écrit :

**Comment by paul-gauthier** [comment]
Aider sends context about the rest of the repo already. See the link I pasted in my last message:

https://aider.chat/2023/10/22/repomap.html

**Comment by paul-gauthier** [comment]
There's also a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#how-can-i-add-all-the-files-to-the-chat

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
