### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by arist0v** [paul-gauthier/aider#481]
I would like to be able to have a Web UI instead of only CLI option

Following feature is what i have in mind:

- Web ui access so i can set Aider on a server in my house and have it always ready
- Be able to have multiple "chat session" in the web ui

Thank you and good tools!

**Comment by paul-gauthier** [comment]
An experimental web UI is available in the main branch. You can get it by installing the latest version from github and running aider with the `--browser` switch.

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
