### ISSUE TITLE
Question/Feature Request: Execution Loops until Output Matches

### ISSUE THREAD

**Issue by fire17** [paul-gauthier/aider#484]
Hi there! hope you are well
Really exited about aider and have a question,
maybe you already have this implemented...

How can i run an execution loop until the output of the program matches exactly to my results
as i am aware, currently in aider, i can ask it for what i want to be done, Then run my code, and tell aider the results
for which it will continue to try to solve it iterively

honestly i feel silly, rerunning, waiting, copy and pasting outputs across terminals back to aider
so basically what i want is to set an execution cmd i.e `cd myproject && python3.11 myprogram.py -q {q} -s google.com`
along side with the output i want the program to end up returning, i.e `results code 200, with some data about {q}`

it should keep trying to do the mission until the output matches exactly=True or sematically=True
it should pause between iterations, so i have time to read the changes and new exec output
and pressing enter should make it go another loop or entering a number ie 3, enter, will make it run up-to 3 times without prompting me (stops sooner if matching)

if i would have it my way, it would even recognize input("enter something: ") and will input it by itself 🤯 
its like ai integration testing! and even loop it with mock values and or tell it to find qa edge cases
taking this to the extreme, where it pre defines desired output of functions it itself has yet to write, would make for a
Readme2Repo feature, where it would actually produce an entire working, tested project from a mission/vision file - that would be epic

oh and p.s. - do you have a flag  --branch {branch_id} that i can use to trigger auto creation of a branch, so the saved changes go there?
id love to start using aider as an api, to let my jarvis be able to call aider

Thanks alot and all the best!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Are you aware of the `/test` command? It will run a shell command, and if the exit status is non-zero it will automatically paste the output into the chat.

So you can do `/test pytest tests/the_faililing_test.py` and just keep pressing up-arrow+enter to do it again until GPT solves the bug.

Beyond that, you could script aider:
https://aider.chat/docs/faq.html#can-i-script-aider

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by fire17** [comment]
Thanks a lot, didn't know about /test, and still haven't played with scripting Aider

It would be nice if Aider could itself tell me about these abilities and also actively use them.

I'll open a new issue on the matter

Thanks a lot and all the best!
