### ISSUE TITLE
Custom prompt

### ISSUE THREAD

**Issue by boosh** [paul-gauthier/aider#486]
- Aider version: 0.24.1

Thanks for creating this, it's really awesome. I keep finding myself providing the same initial prompt to tell GPT to just reply with the code and no commentary. It'd be great if there was a feature to provide a custom initial canned prompt to apply to all the chats in a repo, even if the history is deleted.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.  There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#can-i-specify-guidelines-or-conventions
