### ISSUE TITLE
Support for OpenAI Organization ID

### ISSUE THREAD

**Issue by openclosure** [paul-gauthier/aider#487]
It would be helpful to be able to export some kind of `OPENAI_ORG_ID` variable to specify what organization the API key should be hitting (for those of us with dual work/personal OpenAI accounts).

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I had aider make this change and add a `--openai-organization-id` parameter.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by heijligers** [comment]
> It would be helpful to be able to export some kind of `OPENAI_ORG_ID` variable to specify what organization the API key should be hitting (for those of us with dual work/personal OpenAI accounts).

@openclosure Could u explain a bit more about the use case? Isn't a openai key organization specific?
Thanks!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
