### ISSUE TITLE
Refactor legacy codebase

### ISSUE THREAD

**Issue by FredericoPerimLopes** [paul-gauthier/aider#491]
Hi,
I have a legacy app I want to refactor using aider. Since the files are quite large, I keep hitting rate limits. What's a good approach to make the context a bit shorter with large files >= 1K loc.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Can you be more specific about what you mean by "hitting rate limits"? Maybe paste the error output or a screenshot of the error?

There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#how-can-i-add-all-the-files-to-the-chat

**Comment by FredericoPerimLopes** [comment]
@paul-gauthier thanks for the feedback. What happened was gpt-4 token limit reached. I was to got it to work by switching to gpt-3.5-turbo.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
