### ISSUE TITLE
Wrong project name for pipx in FAQ

### ISSUE THREAD

**Issue by gulliver-madrid** [paul-gauthier/aider#496]
Hi,
This is from the [FAQ](https://aider.chat/docs/faq.html#how-to-use-pipx-to-avoid-python-package-conflicts):
> Install [pipx](https://pipx.pypa.io/stable/) then just do:
> 
> pipx install aider

But this command generates this error message: 

> No apps associated with package aider or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using
> pip or a similar tool instead.

It seems that it should be `pipx install aider-chat` instead.

**Comment by paul-gauthier** [comment]
Thanks, fixed!
