### ISSUE TITLE
Command line paramater to specify test command

### ISSUE THREAD

**Issue by fdietze** [paul-gauthier/aider#499]
Thanks for creating aider!

Using it for the first time, I was missing a way to specify a test command. A test command would run automatically after every change and trigger a feedback loop until the exit code becomes 0.

I would use that for all kinds of testing and type checking.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. You can use the in-chat `/test` command to launch a test loop like you describe.

So you might do:

```
/test pytest some_tests.py
```
It will run them and feed the errors back to the LLM until the tests all pass and return exit code 0.

You can use control-R or the up-arrow to quickly pull up that same `/test` command again later in the chat.

**Comment by fdietze** [comment]
Thanks. I'm aware of `/test` already. But since it's always the same tests which need to run for a project (especially type checks), I thought this could be set up to run automatically by specifying a command once.

**Comment by paul-gauthier** [comment]
Would it help if you could configure a test command, and then doing `/test` without any args would run that configured command?

**Comment by fdietze** [comment]
That would run the tests *after* the changes have already been commited, right? I thought it would be nicer to only have commits for changes, which have passed the test command.

**Comment by paul-gauthier** [comment]
In general, I'm not prioritizing making a "tidy" or "perfect" git commit history. The priority is using git to make sure it's easy to undo/revert/inspect the history of changes made by the AI. If a clean commit history is important to you, you can always use `git rebase` to tidy things up.

**Comment by fdietze** [comment]
Ok, I see, that makes sense. Then I like your suggestion of configuring a test command which you can invoke using `/test`.

**Comment by paul-gauthier** [comment]
You can now use `--test-cmd` to specify the test command. 

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by fdietze** [comment]
Using it now, thank you so much!
