### ISSUE TITLE
Large uncommitted modifications make it impossible to use `aider` on a small file tracked in git

### ISSUE THREAD

**Issue by mobyvb** [paul-gauthier/aider#5]
Reproduction steps:
* Pick any git repo and run `aider smallfile`, where `smallfile` is already committed and there are no uncommitted changes - you should successfully end up at the prompt `smallfile>`
* Shut down aider
* Modify some file other than `smallfile` and add or remove a bunch of lines (enough changes that there will be too many tokens in the prompt)
* Run `aider smallfile` again - this time, you should see an error that looks like the following:
```
<large diff>
<big error message>
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 9132 tokens. Please reduce the length of the messages.
```

Current workaround:
```
cp smallfile untrackedsmallfile
aider untrackedsmallfile
```
^and since it is not tracked, the diff is irrelevant. I think it would be nice if this was still possible if the file was tracked
e.g. if the diff is too large, forget about committing files that were not explicitly mentioned in the `aider` invocation

Feel free to close this issue if you do not feel like this is a priority. The current workaround is fine for me at the moment. And it is simple enough to just make sure not to have uncommitted changes before running `aider`

**Comment by mobyvb** [comment]
also, I would be happy to implement a fix for this issue myself if you decide that it is in line with your vision for this project @paul-gauthier

**Comment by paul-gauthier** [comment]
aider notices if your repo is dirty, and asks if you want to auto commit the changes. You can suppress this behavior with the `--no-auto-commit` cmd line arg. But this will also stop auto committing the changes that aider itself makes.

The problem you are encountering is that `Coder.get_commit_message()` uses gpt-3.5-turbo to summarize the diffs into a sensible commit message. If the diff is large, it exceeds the 4K context window.

A simple fix would be:

1. Check if the diff is close to or larger than 4 kbytes (4k tokens * 4 bytes/token) and don't even bother sending the messages to gpt. Just return.
2. Catch the `openai.error.InvalidRequestError` and just return.

Maybe print a nice tool_error() message for each of these.

Actually, after typing the above I pasted it into aider and it fixed itself:
https://github.com/paul-gauthier/aider/commit/32e40a3e1c1d9545c8f92198848a1c91afe67496

**Comment by paul-gauthier** [comment]
Let me know if the latest version solves the problem for you.

**Comment by mobyvb** [comment]
> Let me know if the latest version solves the problem for you.

I will check and confirm later today. Thanks

**Comment by mobyvb** [comment]
@paul-gauthier hmm it doesn't seem like the latest version solves the issue for me, with or without the `--no-auto-commit` flag. 

I actually just noticed that reproducing this issue does not even require unstaged git changes.
I was able to cause it with a few simple steps:

1. check out very large repo (I used https://github.com/storj/storj)
2. without making any modifications from `HEAD`, open aider on a small file, (I used `aider private/apigen/common.go` and `aider private/apigen/common.go --no-auto-commit`)
3. make a request, e.g. "remove all comments"
My output:
```
Traceback (most recent call last):
  File "/home/moby/.local/bin/aider", line 33, in <module>
    sys.exit(load_entry_point('aider', 'console_scripts', 'aider')())
  File "/home/moby/dev/storj/aider/aider/main.py", line 138, in main
    coder.run()
  File "/home/moby/dev/storj/aider/aider/coder.py", line 217, in run
    new_user_message = self.run_loop()
  File "/home/moby/dev/storj/aider/aider/coder.py", line 270, in run_loop
    return self.send_new_user_message(inp)
  File "/home/moby/dev/storj/aider/aider/coder.py", line 287, in send_new_user_message
    content, interrupted = self.send(messages)
  File "/home/moby/dev/storj/aider/aider/coder.py", line 376, in send
    completion = openai.ChatCompletion.create(
  File "/home/moby/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/moby/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/moby/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/moby/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/home/moby/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 8192 tokens. However, your messages resulted in 32700 tokens. Please reduce the length of the messages.
```

It is worth noting that the repo I'm using is large enough that a list of filenames alone is sufficient to exceed the token limit. I'll look deeper into the internals of aider in case I can figure out a potential workaround.

**Comment by paul-gauthier** [comment]
I think this is a new issue you're seeing, likely caused by the giant file list as you say.

I just added a check, and aider will only send the file list to gpt if it is less than 100 files. In that case, gpt will only know about the specific files you add to the chat. It won't even know about the existence of other files in the repo, so it won't be able to ask to see any that are relevant.

But ya, if you add the files it needs to the chat then this should work better on large repos.

I am also working on a much more ambitious attempt to manage the limited context window size. But so far it's just some early experiments.

**Comment by mobyvb** [comment]
awesome, this works perfectly! I'll close this issue. Thanks!
Looking forward to seeing your experiments to manage the context window size. I've had some ideas about that for my own project but haven't spent any time on it yet.
