### ISSUE TITLE
Enhance error message for missing API Key

### ISSUE THREAD

**Issue by gulliver-madrid** [paul-gauthier/aider#505]
#### Current Behavior
Currently, if the OPENAI_API_KEY is not provided, the system currently throws a slightly confusing error message:
```
... (several traceback lines)
return text.replace(args.openai_api_key, "***")
TypeError: replace() argument 1 must be str, not None
```

This error message does not clearly indicate that the root cause is a missing API key, which can be confusing for users trying to troubleshoot their setup.

#### Proposed Change
It would be beneficial for usability if the error message could explicitly state that the OPENAI_API_KEY environment variable is missing, rather than indicating a type error with the `replace` method. A more descriptive error message could look something like this:
```
Error: Missing OPENAI_API_KEY environment variable. Please ensure you have set a valid OPENAI_API_KEY before running aider.
```

I don't have much experience making pull requests, but I could implement raising a ValueError with an informative message if args.openai_api_key is None. 
Thank you for this tool!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I just pushed a fix. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by gulliver-madrid** [comment]
Hello, thank you for the response. Indeed, the behavior is the same, if I do not define the OPENAI_API_KEY and try to start aider, I get an error `TypeError: replace() argument 1 must be str, not None` instead of an informative message about API key missing.
