### ISSUE TITLE
Aider very slow ( on large repos )

### ISSUE THREAD

**Issue by flaming-potato** [paul-gauthier/aider#506]
- Aider version: 26
- Model: any of the 128k+ ones
- openrouter / openai

Hi,

First of all, thanks for this fabulous tool, and your insights.

Now then,

Generally very happy with aider, but I am hitting a snag with a particular repo. It's quite big, 11k files. with aiderignore, we're talking about ~3k files.

Aider at times takes a full 1 or 2 minutes to give me an answer.

I think i saw people having issues with symbolic links in the past. Are there things I should be aware of that slow aider down ?
Do other people have issues with large repos ? :)

Thanks

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Right now aider is not expected to work well with very large repos. You can use an `.aiderignore` file to ignore the portions of the repo which you aren't actually intending to work on.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
