### ISSUE TITLE
Aider Researcher

### ISSUE THREAD

**Issue by fire17** [paul-gauthier/aider#507]
Hi there, hope you are well :)
I'm sure you've seen the recent buzz around Devin.

Add while it is impressive, technologically they basically do things that Aider and others already do.

The one thing I would love Aider to do is to be able to draw uppon more research.
For example in the Devin demo, they give it a url for a blog post, and ask it to implement what they do there. So obviously just scraping the page and adding it to context, it should be easy as pie for Aider but I don't think I have seen this being used (correct me if I am wrong)

Also to take it one step further, let's say I want to do the same thing, but am not aware of that blog/guide, if it's out there I would expect aider to enter a Research Phase, scrape a few promising guides and api docs from the web, choose the most likely one, or mix the best in all of them, and continue with the mission.
Even better to look at GitHub to find similar or partially relevant repos, and use them without writing everything from scratch, like us programmer already do

Another thing to note, I was impressed by gpt pilot's Refinement Stage, though I think aider does it too to some extent.

Also also, please check out Astro's Houston (install astro to see) I think something like that for Aider would be very pleasing

Please let me know if this (Researcher) is something in the works, there's a reason it's called R&D and not just D haha 
Thanks a lot! And all the best! ❤️ Aider

**Comment by paul-gauthier** [comment]
You can use the `/web` command to add any url to the chat.

**Comment by rawwerks** [comment]
@fire17 - 

1) see my comment in https://github.com/paul-gauthier/aider/issues/508 regarding a community that is excited by these same ideas. 

2) one thing to keep in mind is that with LLMs in general, and even with very sophisticated RAG pipelines (which I believe @paul-gauthier is working on adding ) --- _more information does not reliably lead to better outputs_. this is specifically true in code-generation models, where adding a bunch of human-written (or at least "natural language") documentation actually takes the LLM away from writing code well. in other words - my sense is that adding a "perplexity"-style search in front of aider will make aider dumber. (unless there is a really smart agent that is taking the search and then re-writing instructions to aider, but again that's an agent, not aider.) see this discussion for additional thoughts on this: https://forum.cursor.sh/t/has-cursor-gotten-dumb/2884/14?u=raw.works

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now as I think this is more of a conceptual discussion than a feature request. But feel free to add a comment here and I will re-open or file a new issue any time.
