### ISSUE TITLE
Bug when starting aider

### ISSUE THREAD

**Issue by jan-koch** [paul-gauthier/aider#512]
```
Aider v0.26.1
Model: gpt-4-0613 using diff edit format
Git repo: .git with 270+ files
Repo-map: using 1024 tokens
```

When trying to launch aider, I get this error:

```
jan@ThinkCentre-M900:/var/www/kobra/kobra_laravel_development$ aider
Traceback (most recent call last):
  File "/home/jan/.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/jan/.local/lib/python3.10/site-packages/aider/main.py", line 523, in main
    right_repo_root = guessed_wrong_repo(io, git_root, fnames, git_dname)
  File "/home/jan/.local/lib/python3.10/site-packages/aider/main.py", line 33, in guessed_wrong_repo
    check_repo = Path(GitRepo(io, fnames, git_dname).root).resolve()
  File "/home/jan/.local/lib/python3.10/site-packages/aider/repo.py", line 57, in __init__
    self.root = utils.safe_abs_path(self.repo.working_tree_dir)
  File "/home/jan/.local/lib/python3.10/site-packages/aider/utils.py", line 83, in safe_abs_path
    res = Path(res).resolve()
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I am not sure how to start fixing this, appreciate any insights :)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Can you share the full command line you used to invoke aider? Or even better, also share the output when you add `--verbose` to the command line.

**Comment by jan-koch** [comment]
This is the simple „aider“ command.Funny enough, „aider --help“ works and lists all commands.Everything else produces this error.Am 19.03.2024 um 19:52 schrieb paul-gauthier ***@***.***>:﻿
Thanks for trying aider and filing this issue.
Can you share the full command line you used to invoke aider? Or even better, also share the output when you add --verbose to the command line.

**Comment by jan-koch** [comment]
I think this error is related to the Github repository. Upon further inspection, it works in one branch of the repository but not in another branch. 

![image](https://github.com/paul-gauthier/aider/assets/10744168/b16f546f-dce6-487f-859f-96080eeabdc0)

**Comment by jan-koch** [comment]
Here's a screenshot of running ```aider --verbose``` and ```aider --help``` commands in the broken branch of the repository.

![image](https://github.com/paul-gauthier/aider/assets/10744168/bf48ba09-5d65-418f-a2a9-0d56a7698456)

**Comment by jan-koch** [comment]
No. I am just using one branch for production (that's broken with aider) and one for development (thankfully aider is working there lol)

**Comment by paul-gauthier** [comment]
The bug you show in your screenshots `TypeError: replace() argument 1 must be str, not None` is fixed in the latest version in the main branch. It's because you are running aider without providing an OpenAI API key. The fixed version will print a proper explanation of what's wrong. 

But you do need to provide an OpenAI API key. Perhaps you have an `aider.conf.yml` file in one directory/repo but not the other?

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by jan-koch** [comment]
The missing .aider.conf.yaml was the culprit!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
