### ISSUE TITLE
Missing tags.scm abort execution of repo map

### ISSUE THREAD

**Issue by magaton** [paul-gauthier/aider#514]
Hello, a great project, thanks!
Lots of things to learn.

I am trying to generate a repo map from a java project that contains some yaml, HTML files etc, that I would like to list in repo-map, but in case a matching `tree-sitter-{lang}-tags.scm` does not exist, `pkg_resources.resource_filename` throws `KeyError` which stops the execution.
The reason is that not all languages from `grep-ast` have their `tags.scm`,

I added a try/catch block and it works ok for me.
Not sure if that makes sense, or maybe a fallback `tags.scm` would be better.
WDYT?

```
       try:
            scm_fname = pkg_resources.resource_filename(
                __name__, os.path.join("queries", f"tree-sitter-{lang}-tags.scm")
            )
            # Continue with your code that uses scm_fname
        except KeyError:
            self.io.tool_output(f"The scm file for language '{lang}' does not exist.")
            return
```
            

- Aider version latest - build from source
- Model being used (only repo map)
- Other switches or config settings that are active

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I just pushed a fix for this corner case.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.
