### ISSUE TITLE
Feature req: Please integrate apipie.ai

### ISSUE THREAD

**Issue by EncryptShawn** [paul-gauthier/aider#518]
in addition to or in place of integrating with any aggregators - Please integrate APIpie so devs can access them all from one place/subscription and plus it also provides:

-The most affordable, reliable and fastest AI available
-One API to access ~500 Models and growing
-Language, embedding, voice, image, vision and more
-Global AI load balancing, route queries based on price or latency
-Redundancy for major models providing the greatest up time possible
-Global reporting of AI availability, pricing and performance

Its the same API format as openai, just change the domain name and your API key and enjoy a plethora of models without changing any of your code other than how you handle the models list.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Aider can connect to OpenAI compatible APIs. Here are some relevant docs:

https://aider.chat/docs/llms.html#openai-compatible-apis

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
