### ISSUE TITLE
Getting stuck

### ISSUE THREAD

**Issue by jpwinsw** [paul-gauthier/aider#52]
When running Aider I just get stuck here in the terminal. I have installed everything according to the instructions. Am I doing something wrong perhaps?

(venv) jw project % aider
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens

**Comment by paul-gauthier** [comment]
I'm going to close this issue, but feel free to re-open if you're able to provide additional information for me to help debug.
