### ISSUE TITLE
Streamlit output support

### ISSUE THREAD

**Issue by karthikcs** [paul-gauthier/aider#521]
Is there a way to route the Aider output to streamlit or any other frontend? 

```
Aider v0.26.1
Model: gpt-4-1106-preview using udiff edit format
Git repo: repo_root\.Net\.git with 132 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Can you help me understand what you want a frontend to do?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
