### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by amacsmith** [paul-gauthier/aider#523]
@paul-gauthier, just trying to help organize so I thought I would add a couple items of documentation and places for you to fill in if you want.

**Comment by paul-gauthier** [comment]
Thanks for the nudge. I've been meaning to add a CONTRIBUTING.md file. I probably can't use the PRs you created, as they form a very particular opinion. But I'll try and make some progress on this.

**Comment by paul-gauthier** [comment]
I added a contributing file. I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by amacsmith** [comment]
Thanks it looks good to me!
