### ISSUE TITLE
Feature Request: Implement Automatic File Addition 

### ISSUE THREAD

**Issue by hgncom** [paul-gauthier/aider#529]
### Problem Description
Manually adding *.py files to Aider sessions is cumbersome and prone to errors, particularly with large projects having files spread across various subdirectories. Errors occur frequently when there's a typo in the file path, immediately exiting Aider and displaying:

`
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\johan\\HGN2\\src\\front_end\\x\\user\\*.py'`

### Proposed Solution
Automatic File Addition: Implement a feature within Aider that automatically detects and adds all *.py files within a specified directory and its subdirectories. This would streamline the workflow significantly, making Aider more efficient for Python projects.

### Possible Implementation
A new command, such as /addall <directory>, could recursively add all *.py files from the specified directory and its subdirectories to the session. Alternatively, an option in Aider's settings to specify directories for auto-inclusion at session start could be provided.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#how-can-i-add-all-the-files-to-the-chat

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
