### ISSUE TITLE
Standalone Global Binary?

### ISSUE THREAD

**Issue by rambalachandran** [paul-gauthier/aider#535]
I have been using aider for past few weeks. I love it. However, I'm facing challenges using it for python development
1. Its dependencies conflicts with dependencies of the codebase which means i need to run it in a separate environment.
2. However if I run it in separate environment i'm unable to run Python commands that depend on codebase environment to pipe its output to aider.
3. In some cases I don't want aider and its dependencies become part of my python dependencies especially in prod environment.

It will be very helpful if aider can provide a global binary, something along the lines offered by yt-dlp which can be used across any python environment.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.  There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#how-to-use-pipx-to-avoid-python-package-conflicts

**Comment by rambalachandran** [comment]
Yes pipx seems to be the best solution.It will be very helpful if this can be described prominently in `README.md` . Closing the ticket

**Comment by paul-gauthier** [comment]
My only concern about strongly promoting installing via pipx is that it's an extra install step and dependency for new users. Most people can get going without it, and switch to pipx later if they ever encounter dependency problems.

**Comment by dwaltrip** [comment]
I'm pretty new to using pipx, just used it today for the first time. Can any python based tool installed via pip also be used via pipx? Installing via pipx does seem like a preferred approach.

The readme could simply mention it as an alternative to plain pip.
