### ISSUE TITLE
Default model when invoking aider via script using GPT-4 instead of GPT-4-turbo

### ISSUE THREAD

**Issue by thehqlife** [paul-gauthier/aider#537]
When asking questions or reporting issues, it is very helpful if you can include:

- Aider version: 0.27
- Model being used: gpt-4 instead of gpt-4-turbo-preview
- Other switches or config settings that are active

When I invoke Aider via a python script, the default model (in aider/models/__init__.py) is GPT4 = Model.create("gpt-4"). This is causing gpt-4 to be used via the script instead of the turbo (incurring higher costs)

Happy to push a PR for these changes if you'd like, let me know if you want to update the default model or create a separate GPT4Turbo model that can be passed into Coder.create

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. A change fixing this is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
