### ISSUE TITLE
Anthropic without OpenRouter middle man

### ISSUE THREAD

**Issue by aleclarson** [paul-gauthier/aider#538]
OpenRouter is a nice solution, but since Claude is so popular, it'd be nice to have direct support within Aider so extra costs can be avoided.

I found https://github.com/jtsang4/claude-to-chatgpt which acts as a client-side adapter for Claude models to be used as if they have an OpenAI-compatible API. There's no Claude 3 support quite yet, but perhaps Aider could be used to add support, or maybe we just use `claude-to-chatgpt` as inspiration for an adapter that lives in Aider's repository.

**Comment by aleclarson** [comment]
As a workaround, it appears LiteLLM can be set up locally, as [this comment](https://github.com/paul-gauthier/aider/issues/172#issuecomment-1936340229) describes.

**Comment by paul-gauthier** [comment]
Happy to keep this open, as direct Claude support is high priority for me at the moment.

**Comment by paul-gauthier** [comment]
Aider now supports directly connecting to Anthropic and many other LLM providers.

https://aider.chat/docs/llms.html#anthropic

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
