### ISSUE TITLE
Add support for "custom" models

### ISSUE THREAD

**Issue by tonymacx86PRO** [paul-gauthier/aider#54]
Can you add please support for custom models with generic prompts? Its will be great combination with a openai proxy.

**Comment by paul-gauthier** [comment]
Sorry, I'm not sure I understand what you are requesting. Can you provide more details?

**Comment by sriharshaguthikonda** [comment]
thank you for creating Aider. It’s been a great help to me and I’m sure to many others as well.

I was wondering if it’s possible to use other open-source LLMs instead of GPT models or along side GPT models. I think this feature would be useful for other users as well.

**Comment by alifanov** [comment]
like StarCoder with langhcain to replace OpenAI function calling

**Comment by uripeled2** [comment]
I recently published a package [llm-client](https://github.com/uripeled2/llm-client-sdk) that can be very helpful in enabling the support to run other LLM models, including OpenAI, Google, AI21, HuggingfaceHub, Aleph Alpha, Anthropic, Local models with transformers.

**Comment by paul-gauthier** [comment]
This FAQ entry provides some information about using aider with other LLMs:

https://github.com/paul-gauthier/aider/blob/main/docs/faq.md#can-i-use-aider-with-other-llms-local-llms-etc

**Comment by paul-gauthier** [comment]
I'm going to close this issue, but feel free to re-open if there's more you'd like to discuss about this.
