### ISSUE TITLE
Allow separate and explicit configuration of strong and weak models (gpt-3.5-turbo is hardcoded for weak) 

### ISSUE THREAD

**Issue by coffeecodechem** [paul-gauthier/aider#541]
```
Aider v0.27.0
Model: openrouter/anthropic/claude-3-haiku:beta
Git repo: .git with <10 files
OS: Windows 11, aider installed with pipx
```
From time to time, Aider seems to use GPT-3.5-Turbo, not strictly to the model picked in conf file. Judging from the token length, maybe it is not from the conversation, but some backend communication with the API.

Screenshot of OpenRouter token activity attached 
![image](https://github.com/paul-gauthier/aider/assets/80149823/dd475013-9e69-4ef9-8dd5-e7924a807cc2)

aider.conf.yml:
```
openai-api-base: https://openrouter.ai/api/v1
openai-api-key: sk-or-v1-xxxxx
model: anthropic/claude-3-haiku:beta
```

**Comment by coffeecodechem** [comment]
Sorry I don't have the capability to thoroughly test the source code yet, but this could be a starting point? https://github.com/paul-gauthier/aider/blob/3ab49f1df351d947d76d5e333326f9fd416e5f20/aider/coders/base_coder.py#L225
The `ChatSummary` there uses `models.Model.weak_model()` which is a static method returning "gpt-3.5-turbo-0125"

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Yes, aider uses 2 models: a strong model for coding and a weak model for making commit messages and summarizing the conversation history. Currently the weak model is always gpt 3.5 turbo.

Is there a specific reason you don't want it to use 3.5 for those functions?

**Comment by coffeecodechem** [comment]
For now, it is not really a problem to use gpt-3.5-turbo since it has similar pricing with Claude 3 Haiku, my chosen main model. But in case user is using OpenRouter, the user may prefer another weak model, like the free models provided by the platform. Personally, I want to use Claude 3 Haiku via OpenRouter for both the strong and weak model. So, maybe let the user to set the weak model via config file, but default it to GPT-3.5-Turbo if not assigned?

**Comment by paul-gauthier** [comment]
Aider now has both `--model` and `--weak-model` switches. And by default, aider uses a weak model from the same provider as the strong model whenever possible.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by coffeecodechem** [comment]
Thank you very much! I can confirm that the issue is now closed. Though per version 0.30.1 I want to give some notes on how I finally can run it:
`~/.aider.conf.yml`
```
openai-api-base: https://openrouter.ai/api/v1
openai-api-key: sk-something
model: openrouter/anthropic/claude-3-haiku:beta
weak-model: openrouter/anthropic/claude-3-haiku:beta
```
Then in the project folder I use `.env` to store the `OPENROUTER_API_KEY` (this is doable also by using export/global env variable).

Before, the models can be just `anthropic/claude-3-haiku:beta`. Now, it's important to add `openrouter/` in front of it.

**Comment by paul-gauthier** [comment]
See the docs for updated instructions on using openrouter:

https://aider.chat/docs/llms.html#openrouter
