### ISSUE TITLE
[feature request] Allow running commands in the environment: compilation, running test cases, and so on

### ISSUE THREAD

**Issue by samuela** [paul-gauthier/aider#543]
AFAICT (eg from https://aider.chat/examples/complex-change.html), aider does not currently support running commands automatically to let the agent test whether its changes have the desired effect, eg passing a test case. [SWE-Agent](https://swe-agent.com/) has demonstrated that such a technique is feasible. Could similar functionality be incorporated into aider?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. We have been discussing a `/test` command in issue #499. Sounds like that might be related?

**Comment by paul-gauthier** [comment]
I'm going to close this as a dup of #528 and/or #499.
