### ISSUE TITLE
[request] Add to nixpkgs

### ISSUE THREAD

**Issue by t56k** [paul-gauthier/aider#544]
Any interest in this being added to nixpkgs for Nix and NixOS?

**Comment by clementpoiret** [comment]
Would be awesome :)

**Comment by paul-gauthier** [comment]
Having aider available in nixpkgs sounds nice, but it's probably not something I would have time to work on in the near term.

**Comment by t56k** [comment]
I've made a Nix flake which gets aider up and running in a local devshell--happy to post it if there's interest (or fork the branch or whatever). I don't use Python enough to have an established methodology for repackaging from Pypi (i.e., everything I tried would fail) so this will have to do for now.

**Comment by rehno-lindeque** [comment]
> I've made a Nix flake which gets aider up and running in a local devshell--happy to post it if there's interest

@t56k Can't hurt, would you mind?

Not really sure if it's something I'll tackle, but aider has piqued my interest and trying out with a flake might motivate me to package.

**Comment by giodamelio** [comment]
I got aider packaged using [dream2nix](https://github.com/nix-community/dream2nix) to try it out today. It's not pretty, and definitely not anywhere close to being ready to go into nixpkgs, but it is usable.

Package source in my dotfiles: https://github.com/giodamelio/nixos-configs/blob/main/src/packages/aider.nix

You can also try it quickly via my flake:
```
$ nix run github:giodamelio/nixos-configs#aider
```

**Comment by unchainedio** [comment]
please add aider to nixpackages

**Comment by c-p-b** [comment]
> I got aider packaged using [dream2nix](https://github.com/nix-community/dream2nix) to try it out today. It's not pretty, and definitely not anywhere close to being ready to go into nixpkgs, but it is usable.
> 
> Package source in my dotfiles: https://github.com/giodamelio/nixos-configs/blob/main/src/packages/aider.nix
> 
> You can also try it quickly via my flake:
> 
> ```
> $ nix run github:giodamelio/nixos-configs#aider
> ```

I got a slightly modified version of this working. What I had to do:

- Move the pkgs.FetchFromGithub into a `let` block to reference the src later for requirements.txt (so that it used the requirements.txt packaged into the tarball). The code as-is I believe expected that to either be local or was referencing it in some other way, but it threw an error for me that it couldn't find this file. 
- Regenerate the lockfile by removing it and following the prompts to build for my architecture. If I used the existing lockfile it would use packages compiled for aarch64-darwin, and I'm building on x86-64-darwin

**Comment by rehno-lindeque** [comment]
> I'm open to a PR that would automate publishing aider releases to nix. I just don't use nix and would have to figure it all out from scratch.

I don't think you need to do anything like that @paul-gauthier. (Honestly, not your responsibility)

I believe the options for people who want this are:

1. Someone who is willing to be a nix package maintainer can attempt to get all the packages in #608 updated and merged into [nixpkgs](https://github.com/NixOS/nixpkgs) via pull requests.
    * Side-note: afaik I don't think any dream2nix packages are in nixpkgs right now, so I think my PR above is the closest thing.
    * Help can be attained on the [nix discourse](https://discourse.nixos.org/), etc
2. Go upvote https://github.com/NixOS/nixpkgs/issues/330726 and hope some good soul decides to volunteer
3. Use someone else's package definition

**Comment by arilotter** [comment]
It got merged 17 hours ago! :saluting_face: https://github.com/NixOS/nixpkgs/pull/323927

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by mjrusso** [comment]
Can confirm that the [aider-chat package](https://search.nixos.org/packages?channel=unstable&show=aider-chat&from=0&size=50&sort=relevance&type=packages&query=aider-chat) works. (Great timing; I've been meaning to try this out for awhile now :) Thanks to everyone involved!

**Comment by Corallus-Caninus** [comment]
nix-shell -p aider-chat  install v0.57.0 which is very out of date. Is there a way to install latest?

**Comment by paul-gauthier** [comment]
It is not recommended to install aider using OS package managers. They often install aider with the wrong dependencies. Nix has a history of this I believe. 

See the recommended install methods:

https://aider.chat/docs/install.html

**Comment by akaihola** [comment]
> `nix-shell -p aider-chat` installs v0.57.0 which is very out of date. Is there a way to install latest?

@Corallus-Caninus it seems that by running NixOS `unstable` you'll get `aider-chat 0.70.0` currently (see [package search](https://search.nixos.org/packages?channel=unstable&show=aider-chat)).

NixOS 24.11 seems to have `aider-chat 0.62.0` (see [package search](https://search.nixos.org/packages?channel=24.11&show=aider-chat)).

If you follow some of the links in the discussion above, you'll find various [Nix flake](https://nixos.wiki/wiki/Flakes) recipes – I have in my Aider fork [one](https://github.com/akaihola/aider/tree/nix-flake) too which allows me to keep up with Aider `main` but it's customized and under-documented enough that it doesn't make sense to recommend it.
