### ISSUE TITLE
universal-ctags not enabled?

### ISSUE THREAD

**Issue by 9M6** [paul-gauthier/aider#546]
```
Aider v0.28.0
Model: gpt-4-1106-preview using udiff edit format
Git repo: .git with 628 files
Repo-map: using 1024 tokens
```
Following the examples in some of the video-tutorials it was mentioned the use of universal-ctags, but it seems its not enabled. I'm using a mac-os and installed universal-ctags through homebrew.

Any idea how to enable it?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Aider no longer relies on ctags, it now uses tree-sitter which is installed automatically as part of the aider package.

The fact that you see `Repo-map: using 1024 tokens` means that the repo map is working properly.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
