### ISSUE TITLE
Files not created / saved

### ISSUE THREAD

**Issue by tddschn** [paul-gauthier/aider#547]
When asking questions or reporting issues, it is very helpful if you can include:

- Aider version `aider 0.28.0`
- Model being used (`gpt-4-xxx`, etc) `gpt-3.5-turbo` & `gpt-4-1106-preview`
- Other switches or config settings that are active

```
Aider v0.28.0
Model: gpt-3.5-turbo using whole edit format
Git repo: ../.git with 255 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
```

Prompt: `create python hello world file save to h.py`

Aider showed me the content and let me choose if I want to save the file, I pressed enter to choose default answer (y), then I run `/exit` and check if `h.py` was there - it wasn't. 

I don't know why this happened, could you help me please?

**Comment by paul-gauthier** [comment]
It looks like you ran aider from a subdir within your git repo. Notice how aider prints `Git repo: ../.git`. All filenames in aider are relative to the repo root. You should have seen a warning to this effect right below the lines you pasted into the issue: `Note: in-chat filenames are always relative to the git working dir, not the current working dir.`

So my guess is that you'll find `h.py` in the root directory of your git repo. Try `cd ..; ls -l h.py`.

**Comment by tddschn** [comment]
I just realised that the file was saved to the root of the repo, just like what you said. I only ran `git status` to check if there were new files and didn't do `ls ..`. Thank you for your help!
