### ISSUE TITLE
keywords run or test will attempt to add run and test, if they are scripts.

### ISSUE THREAD

**Issue by zackees** [paul-gauthier/aider#552]
![image](https://github.com/paul-gauthier/aider/assets/6856673/d9633b88-557b-4dd5-84f3-eba80ea46894)

**Comment by zackees** [comment]
Another example:

![image](https://github.com/paul-gauthier/aider/assets/6856673/b11af5de-110c-4e02-81dd-37588bbdc0e0)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You could add such filenames to `.aiderignore` so that aider won't pay any attention to them.

**Comment by zackees** [comment]
Thanks for the quick response. I'll update my front end to compensate.
