### ISSUE TITLE
Add vision support for openrouter models

### ISSUE THREAD

**Issue by few** [paul-gauthier/aider#556]
Aider v0.28.1-dev (9b2e6975843d253430c68ad011bcab27fb3e23cf)
Model: openai/gpt-4-turbo using udiff edit format
Git repo: none
Repo-map: using 1024 tokens

openai/gpt-4-turbo (among other models) support vision, but aider says: "Cannot add image file <path> as the model does not support image files"

Not sure how aider checks for vision support, in case it looks at https://openrouter.ai/api/v1/models, then checking $.architecture.modality=="multimodal" should be good enough.

**Comment by PierrunoYT** [comment]
We really need it for OpenRouter and non OpenRouter

**Comment by Zorlin** [comment]
This is absolutely critical for me at the moment.

Claude 3.5 Sonnet is far and away the best model for my `aider` use case from extensive testing, but because aider doesn't think it supports images I can't show it the results of what it's produced.

**Comment by paul-gauthier** [comment]
Vision should now work for sonnet 3.5 and gpt-4o both directly and via openrouter.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by PierrunoYT** [comment]
> python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git

![grafik](https://github.com/paul-gauthier/aider/assets/95778421/472f33e6-0d3c-4ac8-801b-fc576d7acbe3)

**Comment by mtin79** [comment]
will this also allow aider to look at ui images or figma screenshots to create the code for it (react, html, css …) ?

**Comment by paul-gauthier** [comment]
It should, yes.

**Comment by mtin79** [comment]
> It should, yes.

fantastic!!! ⚡️ so i would just tell aider in the prompt to look at specific files or folders for reference. or are there any specific command line options i have to know?

**Comment by Zorlin** [comment]
> > It should, yes.
> 
> fantastic!!! ⚡️ so i would just tell aider in the prompt to look at specific files or folders for reference. or are there any specific command line options i have to know?

just /add it like any other file

**Comment by paul-gauthier** [comment]
I recently added some docs...

https://aider.chat/docs/images-urls.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by garvanwalshe** [comment]
The same error occurs for glm 5.3 through oupenrouter. Aider claims it does not support images even though GLM claims it does. How do I configure it to ignore the check and attempt to supply the images to the model anyway? The docs file earlier int he thread has also disappeared (provides a 404).
