### ISSUE TITLE
Refresh files content

### ISSUE THREAD

**Issue by asystat** [paul-gauthier/aider#557]
When using aider, I always modify my project files myself through the IDE, using aider as some kind of "helper" to improve parts of the code and such.
But, when I modify the files myself on the IDE and save them, aider seems to not be aware of the changes made, so from then on, any aider git directives fail. 
I solve this by restarting aider or removing and and adding the files again, but it would be nice if aider was aware of the changes made automatically.

Thanks for the great work

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

As long as you save the edits in your IDE, aider should see them and always be working off the latest copy of the files.

What makes you think aider is not seeing the changes after you edit files in your IDE?

**Comment by asystat** [comment]
Maybe I didn't diagnose the behavior right. I assumed this was the case because when I make changes myself on the code, usually aider starts making mistakes on the git directives, resulting in aider falling a loop trying to fix its own commits.
But you are right, apparently it does know the content of the file, even after modified.

Anyways, when this happens, I ctrl+c aider and fix the code by hand myself. are there any additional tips or ways of using it so that it doesn't incur in git errors and me having to constantly fix the changes?

**Comment by paul-gauthier** [comment]
There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#aider-isnt-editing-my-files

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
