### ISSUE TITLE
nothing response in chat with "TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by zhjygit** [paul-gauthier/aider#561]
➜  ~ git:(master) ✗ aider a.html -vvv
Aider v0.28.0
Command Line Args:   a.html -vvv
Environment Variables:
  OPENAI_API_KEY:    ***
  OPENAI_API_BASE:   https://api.nextapi.fun/v1
Defaults:
  --model:           gpt-4-1106-preview
  --skip-model-availability-check:False
  --voice-language:  en
  --map-tokens:      1024
  --input-history-file:/home/zhjy/.aider.input.history
  --chat-history-file:/home/zhjy/.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     /home/zhjy/.aiderignore
  --encoding:        utf-8

Option settings:
  - aiderignore: /home/zhjy/.aiderignore
  - apply: None
  - assistant_output_color: #0088ff
  - auto_commits: True
  - chat_history_file: /home/zhjy/.aider.chat.history.md
  - check_update: False
  - code_theme: default
  - commit: False
  - config: None
  - dark_mode: False
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - encoding: utf-8
  - files: ['a.html']
  - git: True
  - gitignore: True
  - input_history_file: /home/zhjy/.aider.input.history
  - light_mode: False
  - map_tokens: 1024
  - message: None
  - message_file: None
  - model: gpt-4-1106-preview
  - openai_api_base: https://api.nextapi.fun/v1
  - openai_api_deployment_id: None
  - openai_api_key: ***
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - show_diffs: False
  - show_repo_map: False
  - skip_check_update: False
  - skip_model_availability_check: False
  - stream: True
  - tool_error_color: #FF2222
  - tool_output_color: None
  - user_input_color: #00cc00
  - verbose: True
  - voice_language: en
  - yes: None
API key supports: gpt-3.5-turbo, gpt-3.5-turbo-0301, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k, 
gpt-3.5-turbo-16k-0613, gpt-4, gpt-4-0314, gpt-4-0613
API key does not support gpt-4-1106-preview, falling back to gpt-3.5-turbo-0125
Model: gpt-3.5-turbo-0125 using whole edit format
Git repo: .git with 0 files
Repo-map: using 1024 tokens
Added a.html to the chat.
Use /help to see in-chat commands, run with --help to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
a.html> print a circle                                                                                           

SYSTEM Act as an expert software developer.
SYSTEM Take requests for changes to the supplied code.
SYSTEM If the request is ambiguous, ask questions.
SYSTEM 
SYSTEM Once you understand the request you MUST:
SYSTEM 1. Determine if any code changes are needed.
SYSTEM 2. Explain any needed changes.
SYSTEM 3. If changes are needed, output a copy of each file that needs changes.
SYSTEM 
SYSTEM To suggest changes to a file you MUST return the entire content of the updated file.
SYSTEM You MUST use this *file listing* format:
SYSTEM 
SYSTEM path/to/filename.js
SYSTEM ```
SYSTEM // entire file content ...
SYSTEM // ... goes in between
SYSTEM ```
SYSTEM 
SYSTEM Every *file listing* MUST use this format:
SYSTEM - First line: the filename with any originally provided path
SYSTEM - Second line: opening ```
SYSTEM - ... entire content of the file ...
SYSTEM - Final line: closing ```
SYSTEM 
SYSTEM To suggest changes to a file you MUST return a *file listing* that contains the entire content of the file.
SYSTEM *NEVER* skip, omit or elide content from a *file listing* using "..." or by adding comments like "... rest of code..."!
SYSTEM Create a new file you MUST return a *file listing* which includes an appropriate filename, including any appropriate path.
USER Here is the current content of the files:
USER 
USER a.html
USER ```
USER ```
ASSISTANT Ok.
USER print a circle
SYSTEM To suggest changes to a file you MUST return the entire content of the updated file.
SYSTEM You MUST use this *file listing* format:
SYSTEM 
SYSTEM path/to/filename.js
SYSTEM ```
SYSTEM // entire file content ...
SYSTEM // ... goes in between
SYSTEM ```
SYSTEM 
SYSTEM Every *file listing* MUST use this format:
SYSTEM - First line: the filename with any originally provided path
SYSTEM - Second line: opening ```
SYSTEM - ... entire content of the file ...
SYSTEM - Final line: closing ```
SYSTEM 
SYSTEM To suggest changes to a file you MUST return a *file listing* that contains the entire content of the file.
SYSTEM *NEVER* skip, omit or elide content from a *file listing* using "..." or by adding comments like "... rest of code..."!
SYSTEM Create a new file you MUST return a *file listing* which includes an appropriate filename, including any appropriate path.

**Comment by zhjygit** [comment]
My ai api is not support for gpt4, so it is in chat with default gpt-3.5-turbo.
however,in the -vvv content, the "model " remains gpt-4-1106-preview

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Are you actually using OpenAI's apis? It looks like you are trying to point to some other API endpoint:

```
openai_api_base: https://api.nextapi.fun/v1
```

**Comment by zhjygit** [comment]
> Thanks for trying aider and filing this issue.
> 
> Are you actually using OpenAI's apis? It looks like you are trying to point to some other API endpoint:
> 
> ```
> openai_api_base: https://api.nextapi.fun/v1
> ```

yes, as you see,my api base is https://api.nextapi.fun/v1, and i cannot get a openai's apis with some reasons like firewall.
If it is about api's soure, can you improte the code to run with third party apis?

**Comment by paul-gauthier** [comment]
It appears that the API you are using is returning responses which aren't fully compliant with the OpenAI API. I'm not sure I will be able to help you debug a non-standard API/proxy configuration.

**Comment by zhjygit** [comment]
> It appears that the API you are using is returning responses which aren't fully compliant with the OpenAI API. I'm not sure I will be able to help you debug a non-standard API/proxy configuration.

Thanks sir.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
