### ISSUE TITLE
Files added to the .aiderignore cannot be added to the repo chat

### ISSUE THREAD

**Issue by zackees** [paul-gauthier/aider#562]
Previously I submitted a bug report that when files like "install" or "run" or "test" were used, aider would catch onto these keywords and repeatedly ask to include "run" "test". It was suggested that there wouldn't be a fix so I patched it in my front end tool `aicode`.

However, now I want to work on my `./install` and aider refuses because it's in the .aiderignore list.

Can we please allow an exception to this aiderignore when the file is explicitly added to the chat?

**Comment by zackees** [comment]
or have a force option to foce it in the chat. This actually could be simpler

**Comment by paul-gauthier** [comment]
Sorry, I'm not sure I have a great solution other than avoid making files named after very common words if you both want to edit them with aider and do not want aider to offer to add them to chats. Often such little shell scripts are named `run.sh` or `install.sh`, for example.

**Comment by zackees** [comment]
Yeah. I'm adding them without the extension hence the problem.

I added them to aiderignore, but now when i try to modify an install file aider refuses because it's in the aiderignore.

Just adding exceptions for install/run/test would go a long way. zits these three keywords that are missing up my programming flow. Or else allow /add on a specific hole to break through the aider ignore directive.

**Comment by paul-gauthier** [comment]
I just pushed a change to the main branch that should help here. Aider will not offer to add bare filenames like `make` or `run` which may just be words.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by zackees** [comment]
Wanted to update and comment that i cannot test it this weekend because i am traveling to give important concession testimony. this is on my todo list though for next week

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
