### ISSUE TITLE
IndexError in aider/coders/base_coder.py when running 'aider' command

### ISSUE THREAD

**Issue by CSi-CJ** [paul-gauthier/aider#563]
When asking questions or reporting issues, it is very helpful if you can include:
Install with ```pip3 install git+https://github.com/paul-gauthier/aider.git@azure```
- Aider version 0.8.2 
- Model being used gpt-4
- Other switches or config settings that are active

The easiest way to do this is just just copy & paste the announcement lines that aider prints when you launch it, like these:

```
aider 0.8.2
Model: gpt-4
Git repo: .git with 134 files
Repo-map: basic using 1024 tokens (ctags executable not found)
Use /help to see in-chat commands, run with --help to see cmd line args
```

# Error: IndexError in aider/coders/base_coder.py

## Description
When running the `aider` command, I encountered the following error:
```
Traceback (most recent call last):
File "/usr/local/bin/aider", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.8/dist-packages/aider/main.py", line 398, in main
coder.run()
File "/usr/local/lib/python3.8/dist-packages/aider/coders/base_coder.py", line 383, in run
new_user_message = self.run_loop()
File "/usr/local/lib/python3.8/dist-packages/aider/coders/base_coder.py", line 456, in run_loop
return self.send_new_user_message(inp)
File "/usr/local/lib/python3.8/dist-packages/aider/coders/base_coder.py", line 488, in send_new_user_message
interrupted = self.send(messages, functions=self.functions)
File "/usr/local/lib/python3.8/dist-packages/aider/coders/base_coder.py", line 652, in send
self.show_send_output_stream(completion, silent)
File "/usr/local/lib/python3.8/dist-packages/aider/coders/base_coder.py", line 728, in show_send_output_stream
if chunk.choices[0].finish_reason == "length":
IndexError: list index out of range
```

This error occurs when trying to access the `finish_reason` property of the first element in the `chunk.choices` list, but the list is empty or does not have a first element.

## Steps to Reproduce
1. Install the `aider` package using pip: `pip install aider`
2. Run the `aider` command with java file
3. chat with java file "help me xxxxxx"
4. Observe the IndexError

## Expected Behavior
The `aider` command should run without any errors and provide the expected functionality.

## Additional Information
I tried to let aider check the log specification of my java code, but I always reported this error.

Any assistance in debugging and fixing this issue would be greatly appreciated.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Is there a reason you installed aider with that very specific `pip install` command? You installed a very old branch of aider directly from github.

Normally you should just do `git install aider-chat` per the install instructions:

https://aider.chat/docs/install.html

**Comment by CSi-CJ** [comment]
@paul-gauthier  Thanks for your help, it works for me and looks as well
