### ISSUE TITLE
Added Cohere_api_key Not working

### ISSUE THREAD

**Issue by mdabir1203** [paul-gauthier/aider#567]
When asking questions or reporting issues, it is very helpful if you can include:

- Aider version : 0.29.0
- Model being used : gpt-4
- Other switches or config settings that are active

The easiest way to do this is just just copy & paste the announcement lines that aider prints when you launch it, like these:

After using the export COHERE_API_KEY getting the below error message

![image](https://github.com/paul-gauthier/aider/assets/66947064/a4ba7202-4e8b-438b-b299-19b950d1b364)

```
Aider v0.21.2-dev
Model: gpt-4-0613 using diff edit format
Git repo: .git with 134 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Sorry to hear you're having trouble.

Can you show all the "announcement lines" that aider prints when you run it, not just the error? Also, what OS are you using?

**Comment by mdabir1203** [comment]
I am using linux and that is the only line it is showing. I tried to use the Cohere Command-r model. With GPT-4 it works

**Comment by paul-gauthier** [comment]
You might want to try installing the latest build from the main branch. 

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

It really does look like something is wrong with how you are setting the `COHERE_API_KEY` environment variabale though.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
