### ISSUE TITLE
Many openrouter models not working anymore in 0.29

### ISSUE THREAD

**Issue by space0bonzo** [paul-gauthier/aider#569]
- Aider version: 0.29
- Model being used: openrouter/meta-llama/llama-3-70b-instruct or ANY OTHER MODEL which is not mentioned in https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

OUTPUT: 
"""
vscode ➜ /workspaces/python (master) $ aider --model openrouter/meta-llama/llama-3-70b-instruct
Aider v0.29.0
VSCode terminal detected, pretty output has been disabled.
Unknown model openrouter/meta-llama/llama-3-70b-instruct, did you mean one of these?
- openrouter/meta-llama/codellama-34b-instruct
- openrouter/meta-llama/llama-2-70b-chat
- openrouter/meta-llama/llama-2-13b-chat
"""

Possiple explanation:
aider uses "litellm.model_cost.keys()" to search for the given model name. But model_cost just looks [1] into https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json to verify models.
This means any new model could not be used with aider anymore.

[1]https://litellm.vercel.app/docs/completion/token_usage#7-model_cost

**Comment by space0bonzo** [comment]
I just checked with 0.28:
"""
vscode ➜ /workspaces/python (master) $ aider --model microsoft/wizardlm-2-8x22b
Aider v0.28.0
Newer version v0.29.0 is available. To upgrade, run:
/usr/local/bin/python -m pip install --upgrade aider-chat
VSCode terminal detected, pretty output has been disabled.
Model: microsoft/wizardlm-2-8x22b using whole edit format
Git repo: .git with 4 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
"""

vs. 0.29
"""
vscode ➜ /workspaces/python (master) $ aider --model microsoft/wizardlm-2-8x22b 
Aider v0.29.0
VSCode terminal detected, pretty output has been disabled.
Unable to check environment variables for model microsoft/wizardlm-2-8x22b
Unknown model microsoft/wizardlm-2-8x22b
"""

**Comment by paul-gauthier** [comment]
Sorry, to be clear you should be able to do this:

```
export OPENROUTER_API_KEY=<your-key-goes-here>
aider --model openrouter/meta-llama/llama-3-70b-instruct
```

You might want to update to the latest aider from github as there are some fixes and improvements there:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

I added some docs for OpenRouter as well:

https://aider.chat/docs/llms.html#openrouter

**Comment by space0bonzo** [comment]
Works perfectly!

Thank you Paul, I think this is a great way to pass on the necessary information to the user, e.g. me. :)

"""
vscode ➜ /workspaces/python (master) $ aider --model openrouter/microsoft/wizardlm-2-8x22b
Aider v0.29.2
VSCode terminal detected, pretty output has been disabled.
Model openrouter/microsoft/wizardlm-2-8x22b: Unknown model, context window size and token costs unavailable.
For more info see https://aider.chat/docs/llms.html#model-warnings
Model: openrouter/microsoft/wizardlm-2-8x22b with whole edit format
Git repo: .git with 4 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
