### ISSUE TITLE
instead of hardcodung the model in aider/sendchat.py perhaps its better if we get it via the env? 

### ISSUE THREAD

**Issue by KUKARAF** [paul-gauthier/aider#570]
If you need any help let me know. I'd love to work on this as well

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, I don't understand. There's no model hard coded in sendchat? In fact you can select from a large number of different models.

https://aider.chat/docs/llms.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
