### ISSUE TITLE
Make aider aware of command that itself supports

### ISSUE THREAD

**Issue by jianghoy** [paul-gauthier/aider#574]
# The problem
When I ask Aider to commit my code changes (made outside using nvim), it response a typical git workflow.
```
> ok, could you commit current code (which contains my code change)?

As an AI language model, I don't have the capability to directly commit code to a git repository. However, I can help you prepare the code for a commit. If you have made changes to the set-diff.rkt file and you want to commit those
changes, you would typically follow these steps in your local development environment:

 1 Stage the changes for commit:

    git add set-diff.rkt

 2 Commit the changes with a message:

    git commit -m "Implement set difference functionality in set-diff.rkt"

 3 Push the commit to the remote repository (if necessary):

    git push


Please execute these commands in your terminal or use your preferred Git GUI to commit the changes. If you need further assistance with the commit message or any other part of the process, feel free to ask!
```
I then run them manually with `/git` command. 
# The proposal
Instead of just saying the normal stuff that users likely know how to do, e.g. how to commit code etc etc, when aider has a `/cmd` command supporting such operation, it should be aware of its capability and prompt user to act accordingly, so in this case aider can try to say something like:
```
you can try to commit code directly in aider by running: /git add set-diff.rkt 
```
etc, etc. The change will likely include a way to incorporate existing helper message into system prompt one way or another.

## Metadata

```shell
Models: gpt-4-1106-preview with udiff edit format, weak model gpt-3.5-turbo
Creating empty file /Users/jianghongying/code/racket/set-diff.rkt
Git repo: .git with 2 files
Repo-map: using 1024 tokens
Added set-diff.rkt to the chat.
Use /help to see in-chat commands, run with --help to see cmd line args
```

**Comment by Emasoft** [comment]
I strongly agree with this proposal. I'm just starting to use aider, and the biggest issue is the learning curve. Allowing aider to access always updated documentation (maybe in the system prompt?) would be a great step in the right direction. Even better, it would allow many settings to be directly operated by aider. For example: "change my linter for JavaScript from eslint to jshint" or "extend the Python max line length to 120 characters in the riff configuration" or "migrate from Antigen to Antidote" or "install yarn-audit-fix and add it to my git hooks" or "add @parcel/diagnostic to the tests to run on this project" or "automatically add and commit to git all source files that pass the pytests," etc.
If Aider could learn to configure itself and the environment via some function calls it would be really a great step forward for the platform.

**Comment by paul-gauthier** [comment]
I think this is solved by the new `/help` functionality?

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
