### ISSUE TITLE
Adding keys in config files for other LLM providers.

### ISSUE THREAD

**Issue by PrashamTrivedi** [paul-gauthier/aider#578]
### Issue

First of all, Thanks a lot for aider. And specially for the latest version which enables us to talk with multiple models.

Based on updated description and checking `main.py`. I have found out that the tool only supports OpenAI and Anthropic keys to be set in `~/.aider.conf.yml`. I was checking if we can add keys for other providers, mainly Gemini and Command+R in Config file and check it from there.

I am planning to create a PR, but before I do that, I want to know is there any specific reason why it shouldn't be done? 
Thanks again...

### Version and model info

```
Aider v0.30.1
Models: gpt-4-1106-preview with udiff edit format, weak model gpt-3.5-turbo
Git repo: .git with 156 files
Repo-map: using 1024 tokens
```

**Comment by paul-gauthier** [comment]
Here are some brief docs about the `.env` file:

https://aider.chat/docs/llms.html#using-a-env-file

**Comment by PrashamTrivedi** [comment]
That satisfies all the requirements. Hence Closing the comment. Thanks
