### ISSUE TITLE
Gemini can't create or edit files

### ISSUE THREAD

**Issue by paul-gauthier** [paul-gauthier/aider#579]
Copied @ssillah10 question from #168.

> Hi Paul, I am having the same issue but with Gemini. It can't create or edit files. Any suggestions?

**Comment by paul-gauthier** [comment]
Can you tell me the aider version, exact model name and any other settings/switches you are using? Easiest thing would be to copy & paste the "announcement" lines that aider prints on startup:

```
Aider v0.XX.Y
Model: gpt-N-... using ???? edit format
Git repo: .git with ### files
Repo-map: using #### tokens
```

**Comment by ssillah10** [comment]
Aider v0.30.1
Model: gemini/gemini-1.5-pro-latest with whole edit format
Git repo: .git with 0 files
Repo-map: using 1024 tokens

**Comment by SharadK9** [comment]
Hi,
Can you tell me how I can change from gpt-4 to Gemini or Groq models?
Thanks

Aider v0.30.2-dev
Models: gpt-4-1106-preview with udiff edit format, weak model gpt-3.5-turbo
Git repo: none
Repo-map: disabled

**Comment by paul-gauthier** [comment]
> Can you tell me how I can change from gpt-4 to Gemini or Groq models?

Here are the docs in connecting to other LLMs:

https://aider.chat/docs/llms.html

**Comment by ssillah10** [comment]
Aider v0.30.1
Model: gemini/gemini-1.5-pro-latest with whole edit format
Git repo: .git with 0 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
@SharadK9 can you show me the problem you are having with aider and gemini? Either take a screenshot, copy & paste the text from your terminal or pull the lines from `.aider.chat.history.md`.

**Comment by SharadK9** [comment]
> @SharadK9 can you show me the problem you are having with aider and gemini? Either take a screenshot, copy & paste the text from your terminal or pull the lines from `.aider.chat.history.md`.

Thanks Paul. Its working now. Uninstalled aider and then reinstalled again and set groq api key.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by ssillah10** [comment]
this is the error i get 

Malformed response #3, aborting.
https://aider.chat/docs/faq.html#aider-isnt-editing-my-files
No filename provided before ``` in file listing

**Comment by ssillah10** [comment]
i updated aider but gemini still isn't writing or updating to files, is there a fix?

**Comment by paul-gauthier** [comment]
Can you show me more of the output? Ideally I would like to see what gemini is sending back as far as the code and the wrapping around it.

Also, you can try using `--edit-format diff` with gemini. I am about to switch gemini to use that as the default edit format.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
