### ISSUE TITLE
Feature request: support a model fine-tuned on diffs?

### ISSUE THREAD

**Issue by kasbah** [paul-gauthier/aider#582]
Briefly trying out aider with GPT-4 I was impressed but did notice that GPT-4 doesn't seem to be particularly good at generating valid diffs. I came across these the [diff-codegen](https://carper.ai/diff-models-a-new-way-to-edit-code/) fine tuned models and am interested in trying them out. 

If I understand their results correctly though it's only a 0.3% improvement over the baseline in their benchmark so may not be worth it. Also, I couldn't see how to easily plug it in since this, or the Salesforce codegen models it's based on, don't seem to be mentioned anywhere in litellm or ollama. 

They did also make [diff dataset](https://huggingface.co/datasets/CarperAI/github-diffs-deduped) so that may help someone more capable than me fine-tune a better model.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. In case you haven't seen it, there's a long writeup about aider's current support for unified diffs:

https://aider.chat/docs/unified-diffs.html

**Comment by kasbah** [comment]
Thanks, maybe I should just give it another go then. When did aider switch to this unified diff format?

**Comment by paul-gauthier** [comment]
Aider implemented support for the unified diff edit format back in December. It currently uses this edit format for the GPT-4 Turbo models. Aider uses different edit formats for different models, choosing the one which performs best for the specific model. There's some more detail on this here: 

https://aider.chat/docs/llms.html#editing-format

**Comment by kasbah** [comment]
Ok thanks, I believe I was using GPT-4 (non-turbo) last time so will try turbo.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
