### ISSUE TITLE
more issues with Aider and Azure

### ISSUE THREAD

**Issue by philliplyle** [paul-gauthier/aider#583]
### Issue

Hi there,

I reviewed the previous ticket thread from last week on Aider and Azure where it was returning the "Resource Not Found" error. 

Unfortunately, the latest builds didn't fix our issue immediately, and we've noticed the following behavioral differences.   We are unable to get an Azure deployment working with only the YML file; we have to set the environmental variables.

Here is what's working.    Can you suggest how to get this working with only a YML file?

What used to work with nothing else:

openai-api-type: azure
openai-api-key: xxxxxx
openai-api-base: https://xxxx.openai.azure.com
openai-api-version: 2024-02-01
openai-api-deployment-id: test-model

What's required now:

Deployment Name matches underlying model exactly, AND:

YML:

openai-api-type: azure
openai-api-key: xxxxxx
openai-api-base: https://xxxx.openai.azure.com
openai-api-version: 2024-02-01
openai-api-deployment-id: test-model
model:  azure/test-model

AND

Environmental variables:

AZURE_API_BASE
AZURE_API_VERSION
AZURE_API_KEY

### Version and model info

Aider v0.30.1

**Comment by paul-gauthier** [comment]
There are some docs which might be helpful:

https://aider.chat/docs/llms.html#azure

https://aider.chat/docs/llms.html#model-warnings

https://aider.chat/docs/llms.html#using-a-env-file

**Comment by philliplyle** [comment]
Thanks Paul.  Yes, I've reviewed those items, and did manage to get the alternative deployment name working in conjunction with the environmental variables.  It does display a warning but proceeds regardless.

However, it doesnt address why we were previously able to execute against Azure without the environmental variables.   If OPENAI_API_TYPE is set to "azure" then why do we still have to set those variables separately?

Just pointing out that it was working without them before.

**Comment by paul-gauthier** [comment]
Aider recently added support for directly connecting to many LLM providers via the litellm package. This change required a shift to environment variables. I would recommend following the new docs about how to connect with Azure, but you're welcome to try and make it work a different way if you prefer.

**Comment by philliplyle** [comment]
Thanks for confirming the change.

The .ENV method doesn't appear to work for multiple users; does the file require a specific name?   I've tried simply ".env" myself as well as other file names, and another person reported the same.

**Comment by paul-gauthier** [comment]
You should create a `.env` file in the directory where you run aider. I've tested this on my local and it works fine. 

I just pushed a change to add a `--env-file` param to aider, so you can explicitly tell it which file to load. By default it will look in the root of your git repo, in the same dir where you find the `.git` directory. But you can override and have it load a specific file with `--env-file <filename>`.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by philliplyle** [comment]
I appreciate the feedback.  I can only test on a Windows computer at the moment, but it's definitely not picking up my .env.  See below.  I'll test on the updated version when I can.


05/02/2024  12:56 PM    <DIR>          .
05/01/2024  10:12 AM    <DIR>          ..
05/02/2024  08:52 AM            34,417 .aider.chat.history.md
05/02/2024  08:49 AM                24 .aider.conf.yml
05/01/2024  01:30 PM               275 .aider.input.history
**05/02/2024  08:49 AM               141 .env
05/01/2024  10:13 AM           108,459 aider.exe**

> **more .env**
AZURE_API_KEY=xxxx
AZURE_API_VERSION=2024-02-01
AZURE_API_BASE=xxx.openai.azure.com


>**aider**
Aider v0.30.1
Newer version v0.31.1 is available. To upgrade, run:
C:\Users\plyle\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip
install --upgrade aider-chat
Add .aider* to .gitignore (recommended)? n
**Model azure/test-model: Missing these environment variables:
- AZURE_API_BASE
- AZURE_API_VERSION
- AZURE_API_KEY**

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
