### ISSUE TITLE
Update docs for Windows users

### ISSUE THREAD

**Issue by savareyhano** [paul-gauthier/aider#584]
### Issue

When reading [docs llms](https://github.com/paul-gauthier/aider/blob/main/docs/llms.md) i came across `export` command, which according to this [stackoverflow answer](https://stackoverflow.com/questions/26368306/export-is-not-recognized-as-an-internal-or-external-command) is valid only for unix shells. In Windows it should use `set` instead of `export`, i think mentioning about this would help Windows users who use aider like myself not to get confused.

Is permission granted for me to open pull request about this?

### Version and model info

Aider v0.30.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

Good point, I have added `setx` versions of all the commands.

**Comment by savareyhano** [comment]
All good now, thanks.
