### ISSUE TITLE
Aider crashes after some time of use

### ISSUE THREAD

**Issue by ptkasper** [paul-gauthier/aider#586]
### Issue

I have a couple of time crashed aider after some time of use. Can't recall what the previous error was but I suspect it was the same as this time. Here are the last three lines from the console:

site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

### Version and model info

Aider 0.31.1
Models: gpt-4-1106-preview with udiff edit format, weak model gpt-3.5-turbo

Running Aider in VSCode terminal on WSL2/Ubuntu 22.04.4 LTS.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I've added `httpx.RemoteProtocolError` to the list of errors that aider automatically tries to recover from by retrying.  The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
