### ISSUE TITLE
[Question] Ollama local model support

### ISSUE THREAD

**Issue by Christoph** [paul-gauthier/aider#596]
# Issue
Connection to local ollama models (tested codeqwen:v1.5-chat and llama3) does not work.

## Steps
1. Install ollama
2. Download the model
`ollama list`
NAME              	ID          	SIZE  	MODIFIED     
codeqwen:v1.5-chat	a6f7662764bd	4.2 GB	13 hours ago	
3. serve
`OLLAMA_HOST=127.0.0.1:11435 ollama serve`
4. set oolama url
`export OLLAMA_API_BASE=http://127.0.0.1:11435`
5. start aider
`aider --model ollama/codeqwen:v1.5-chat`
6. use aider
```
Model ollama/codeqwen:v1.5-chat: Unknown model, context window size and token costs unavailable.
For more info see https://aider.chat/docs/llms.html#model-warnings
Aider v0.32.0
Model: ollama/codeqwen:v1.5-chat with whole edit format
Git repo: none
Repo-map: disabled
Use /help to see in-chat commands, run with --help to see cmd line args
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> teste                                                                                                              

Traceback (most recent call last):
  File "/home/chris/.virtualenvs/aider/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/chris/.virtualenvs/aider/lib/python3.12/site-packages/aider/main.py", line 402, in main
    coder.run()
  File "/home/chris/.virtualenvs/aider/lib/python3.12/site-packages/aider/coders/base_coder.py", line 480, in run
    list(self.send_new_user_message(new_user_message))
  File "/home/chris/.virtualenvs/aider/lib/python3.12/site-packages/aider/coders/base_coder.py", line 661, in 
send_new_user_message
    yield from self.send(messages, functions=self.functions)
  File "/home/chris/.virtualenvs/aider/lib/python3.12/site-packages/aider/coders/base_coder.py", line 790, in send
    yield from self.show_send_output_stream(completion)
  File "/home/chris/.virtualenvs/aider/lib/python3.12/site-packages/aider/coders/base_coder.py", line 874, in 
show_send_output_stream
    for chunk in completion:
  File "/home/chris/.virtualenvs/aider/lib/python3.12/site-packages/litellm/llms/ollama.py", line 261, in 
ollama_completion_stream
    raise e
  File "/home/chris/.virtualenvs/aider/lib/python3.12/site-packages/litellm/llms/ollama.py", line 249, in 
ollama_completion_stream
    status_code=response.status_code, message=response.text
                                              ^^^^^^^^^^^^^
  File "/home/chris/.virtualenvs/aider/lib/python3.12/site-packages/httpx/_models.py", line 576, in text
    content = self.content
              ^^^^^^^^^^^^
  File "/home/chris/.virtualenvs/aider/lib/python3.12/site-packages/httpx/_models.py", line 570, in content
    raise ResponseNotRead()
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

```
answer inside ollama console
```
[GIN] 2024/05/08 - 08:43:30 | 404 |      257.33µs |       127.0.0.1 | POST     "/api/generate"
```
May anyone help me or point me in the correct direction?

### Version and model info

Aider: v0.32.0
Model: ollama/codeqwen:v1.5-chat
OS: arch

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider generally works great with ollama. The error message you're getting mentions a problem streaming. Perhaps the model you are using does not support streaming? You could try running aider with the `--no-stream` option to see if that helps?

**Comment by Christoph** [comment]
Thank you for your quick answer!

I think the issue was that the exported port (11435) didnt work with aider.
After starting with the regular port 11434 did it work as expected.

And thank you for writing aider, its exactly the ai tooling i imagined to be really useful.
Your work is amazing!

kind regards,
chris

**Comment by rominf** [comment]
I got the same issue when using ollama, installed on another machine (not on localhost). Workaround is to install ollama on localhost (model downloading is not necessary).

**Comment by davidbuzz** [comment]
tip:
export OLLAMA_API_BASE=http://192.168.x.x:11434  
works for accessing over a LAN.. but this does NOT:
export OLLAMA_API_BASE=http://192.168.x.x:11434/

[ note the / on the end of the one that doesn't work. ]
