### ISSUE TITLE
Ensure that Aider's output is consistent with the language of the user's input.

### ISSUE THREAD

**Issue by zx9597446** [paul-gauthier/aider#597]
### Issue

Ensure that Aider's output is consistent with the language of the user's input.

### Version and model info

model: deepseek-chat

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Can you tell me more about what is not working the way you expect? Or can you share a screenshot or copy & paste some aider output that shows the problem?

**Comment by zx9597446** [comment]
First of all, thank you for providing such a great tool!
![屏幕截图 2024-05-09 095654](https://github.com/paul-gauthier/aider/assets/1539405/01f3e709-f71b-429d-aa06-388331e83649)

When explicitly asked to respond in Chinese, the AI assistant can do so. But when there is no explicit request, it often responds in English, and sometimes switches between languages in the middle.

**Comment by zx9597446** [comment]
![image](https://github.com/paul-gauthier/aider/assets/1539405/90c6c726-851d-44c4-abbf-9fd0e6afa4ea)
![image](https://github.com/paul-gauthier/aider/assets/1539405/0e30d58c-095b-44bf-8022-6172f6ba9189)

**Comment by paul-gauthier** [comment]
I added this to the system prompt: `Always reply to the user in the same language they are using.`

It helps GPT 3.5 stick with the user's language. Unfortunately, deepseek-chat still replies in English sometimes.

**Comment by zx9597446** [comment]
understood
