### ISSUE TITLE
[idea] - Use CSV formatted output for repo map

### ISSUE THREAD

**Issue by camAtGitHub** [paul-gauthier/aider#60]
Hi Paul, 

Love the work you have done to date!
Without digging through your actual code - you mention ctags needing / using? json output - json obviously repeats its header names with every object. Given that GPT4 understands CSV formatted data, is it worth trying to use CSV data in the repomap in an attempt to save tokens? 

Eg. 
```
echo 'name,line,filename,pattern,kind_long,type,scope'; ctags -x --fields=+Ks   --_xformat="%N,%n,%F,%P,%K,%t,%s"   filename-here.py

name,line,filename,pattern,kind_long,type,scope
double_uri_encode,142,harbour_api.py,/^    def double_uri_encode(self, input_string: str) -> str:$/,member,typename:str,harbourAPI
logger,11,harbour_api.py,/^logger = config.configure_logging()$/,variable,-,
```
Using CSV output in a crude example reduced character output by 42%.
Additional tokens could be saved by dropping `%F` and telling GPT the filename before the table....?

Anyway just an idea. Feel free to close.

Thanks, Cam

FYI `ctags --list-fields` provides the letters for xformat.

**Comment by paul-gauthier** [comment]
Thanks for trying, Aider!

Aider reads JSON from Universal Ctags but does not send JSON to GPT. It sends an efficient hierarchical tree format. 

You can find more details in this write-up about the repo map:

https://aider.chat/docs/ctags.html
