### ISSUE TITLE
Question: I spent around $35-$40 using aider-chat, how can we minimize the cost? 

### ISSUE THREAD

**Issue by al3rez** [paul-gauthier/aider#605]
### Issue

I love aider-chat, I've been using it for a while (I stopped using Cursor.sh because it didn't work as expected in Windows and Linux) so I had to find an alternative which I ended up with aider-chat, but after working with it for a while my OpenAI usage got up pretty quickly compared to $20/month from Cursor.sh, I pretty much I spent $40 for a few days which isn't a sustainable model, what can I do to improve the token usage? Also how can I ask questions for the whole code base without adding each file manually?

**Comment by Roald87** [comment]
See https://github.com/paul-gauthier/aider/issues/437

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

What model are you using? The new gpt-4o is significantly cheaper.

Also, be sure to only add files to the chat which need to be edited for the task at hand. Aider will share snippets of related content automatically. Don't "add the whole repo" to the chat.
