### ISSUE TITLE
Repo not mapping (large project)

### ISSUE THREAD

**Issue by novacoole** [paul-gauthier/aider#61]
I understand that with context limitations, only certain sized repos will work with this but just wanted to flag that this is silently erroring:

Tested with the example JS game 2048:
```
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
Use /help to see in-chat commands.
────────────────────────────────────────────────────────
> what is the repo?

Based on the file structure and content you've provided, it appears that the repository is for a version of the game 2048. The game logic is primarily
handled in JavaScript files, with HTML and CSS for the user interface. The game seems to be a web-based application.
```

Inside my extremely bloated Rails application:
```
Model: gpt-4
Git repo: .git
Repo-map: universal-ctags using 1024 tokens
Use /help to see in-chat commands.
────────────────────────────────────────────────────────
> what is the repo?

As an AI, I don't have access to specific repositories. However, I can help you with code changes, improvements, and suggestions based on the
information you provide. Please provide the details of the changes you want to make or the issues you're facing, and I'll do my best to assist you.
```

I'm guessing the universal-ctags mapping is just failing and so no ctags are being included in the request?

**Comment by jaobrown** [comment]
@novacoole perhaps try with https://github.com/universal-ctags/ctags to reduce needed context?

**Comment by paul-gauthier** [comment]
> I initialised a repo with `npx create-react-app` which ended up around ~300mb in size, and aider successfully mapped the repo, however when I git cloned reworkd/AgentGPT, which ended up ~60mb, aider failed to map even with 4096 tokens.

What do you mean "aider failed to map"? Can you be more precise about what output you either got or didn't get that makes you think aider failed to map a repo?

**Comment by paul-gauthier** [comment]
> Also, I saved the API key into the said file in my home directory, and it still asked for a key.

@darit thank you for reporting this! There was an error in the README, which showed the wrong filename for the conf file. The correct filename for the yaml configuration file is `.aider.conf.yml`. Hopefully this solves your problem.

**Comment by paul-gauthier** [comment]
> I initialised a repo with `npx create-react-app` which ended up around ~300mb in size, and aider successfully mapped the repo, however when I git cloned reworkd/AgentGPT, which ended up ~60mb, aider failed to map even with 4096 tokens.

@novacoole just following up again to see if you explain what you mean by "aider failed to map"? Can you be more precise about what output you either get or don't get that makes you think aider failed to map a repo?

**Comment by novacoole** [comment]
@paul-gauthier Sorry, I just mean that I got the generic response back when asking about the repo:

```
As an AI, I don't have access to specific repositories. However, I can help you with code changes, improvements, and suggestions based on the information you provide. Please provide the details of the changes you want to make or the issues you're facing, and I'll do my best to assist you.
```

"failed to map" was probably the wrong language, it's more that the map was not included in the request (i'm guessing). It just seems unusual that the deciding factor on whether or not a repo is recognised is not the size of the repo.

Just to be clear, i'm not having any issues with the environment variable and everything else is working as expected, ChatGPT just has no awareness of certain repos.

**Comment by paul-gauthier** [comment]
Try asking it about the "code base" instead of "repo". None of the system prompts discuss a git repository, so it may just be a terminology problem. 

You can also run aider with `--verbose` to see a debug level dump of the data being sent to gpt. You should be able to see the repo map data in there.

**Comment by novacoole** [comment]
@paul-gauthier Thanks Paul, I think it did come down to the terminology in the end, and using `--verbose` I was able to see my largest application's repo map was just too large.
