### ISSUE TITLE
AUR package named aider-chat seems to install wrong dependencies

### ISSUE THREAD

**Issue by szymor** [paul-gauthier/aider#610]
### Issue

aider crashes after typing literally anything, example:
```
Aider v0.35.0
Model: gemini/gemini-1.5-pro-latest with diff-fenced edit format
Git repo: .git with 6 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args
────────────────────────────────────────────────────────────────────────────────
> how to set up a default model for aider?                                      

Traceback (most recent call last):
  File "/usr/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/aider/main.py", line 408, in main
    coder.run()
  File "/usr/lib/python3.12/site-packages/aider/coders/base_coder.py", line 500, in run
    list(self.send_new_user_message(new_user_message))
  File "/usr/lib/python3.12/site-packages/aider/coders/base_coder.py", line 673, in send_new_user_message
    messages = self.format_messages()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aider/coders/base_coder.py", line 629, in format_messages
    messages += self.get_files_messages()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aider/coders/base_coder.py", line 435, in get_files_messages
    repo_content = self.get_repo_map()
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aider/coders/base_coder.py", line 424, in get_repo_map
    repo_content = self.repo_map.get_repo_map(self.abs_fnames, other_files)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aider/repomap.py", line 65, in get_repo_map
    files_listing = self.get_ranked_tags_map(chat_files, other_files)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aider/repomap.py", line 334, in get_ranked_tags_map
    ranked_tags = self.get_ranked_tags(chat_fnames, other_fnames)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aider/repomap.py", line 247, in get_ranked_tags
    tags = list(self.get_tags(fname, rel_fname))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aider/repomap.py", line 126, in get_tags
    data = list(self.get_tags_raw(fname, rel_fname))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aider/repomap.py", line 138, in get_tags_raw
    language = get_language(lang)
               ^^^^^^^^^^^^^^^^^^
  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)
```

It was the same even before configuring the model used.

### Version and model info

Aider v0.35.0
Model: gemini/gemini-1.5-pro-latest with diff-fenced edit format
Git repo: .git with 6 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Did you install aider with `pip install aider-chat`? I ask because it looks like you might be using a new, incompatible version of the `tree-sitter` package. A normal pip install of aider would bring in the correct version, or print a warning if there was a conflict.

You might consider installing aider with pipx to avoid package version conflicts.

https://aider.chat/docs/faq.html#how-to-use-pipx-to-avoid-python-package-conflicts

**Comment by szymor** [comment]
Nope, I used an AUR package named `aider-chat` ( https://aur.archlinux.org/packages/aider-chat ). `python-tree-sitter-languages` subdependency was not installed automatically, so I installed manually `python-tree-sitter-languages-bin 1.10.2-2` which seemed to solve the dependency.

Thank you for your fast answer, I will then just play around with dependencies on my PC.

**Comment by szymor** [comment]
Downgrading package python-tree-sitter (0.22.3-1 => 0.21.3-1) solved the issue. Thank you in advance :)

**Comment by paul-gauthier** [comment]
Normally when you install aider the pip requirements ensure the correct version of tree-sitter is installed. Do you know how you ended up with the wrong version? Is this a problem with the AUR package or something you did to your local environment?

**Comment by szymor** [comment]
One of dependencies of python-grep-ast, python-tree-sitter-languages, was not installed automatically when installing aider-chat from AUR, so I installed python-tree-sitter-languages-bin which solved that dependency in a graceful way. That package, on the other hand, depended on python-tree-sitter, so the latter was installed in the latest version.

I believe it is not an issue specific to my machine, but rather to the fact that downgrading AUR packages can be only done manually.

BTW, the AUR package aider-chat has some missing dependencies (two of them were listed by me recently on AUR), but it is a different story. I think I have not mentioned google-generativeai optional dependency there.

**Comment by paul-gauthier** [comment]
Any idea why the AUR package didn't use the `requirements.txt` that ships with aider? It names every dependency with a specific version.

**Comment by szymor** [comment]
1) AFAIK requirements.txt is used only by pip.
2) pikaur (AUR client) installs the newest version of a package by default.
3) I believe you cannot specify the version of dependencies on AUR.

**Comment by paul-gauthier** [comment]
That seems like a big limitation. It's pretty common for python projects to depend on specific versions. Aider has 2 dependencies which are pinned to specific older versions because newer versions cause problems.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by f0-x** [comment]
Hi @szymor, could you please tell me how did you specifically downgrade the version of `python-tree-sitter` package only ?

**Comment by szymor** [comment]
It was a few months ago, but as far as I remember I manually downloaded an older PKGBUILD and built the older package.
You could ask how to download previous releases of PKGBUILD. Change history is stored as git repositories on AUR, so you can clone the relevant repository and switch to a commit of choice. Then you make your package and install it.

**Comment by kittenvr** [comment]
> Thanks for trying aider and filing this issue.
> 
> Did you install aider with `pip install aider-chat`? I ask because it looks like you might be using a new, incompatible version of the `tree-sitter` package. A normal pip install of aider would bring in the correct version, or print a warning if there was a conflict.
> 
> You might consider installing aider with pipx to avoid package version conflicts.
> 
> https://aider.chat/docs/faq.html#how-to-use-pipx-to-avoid-python-package-conflicts

it seems like your faq link has expired, can you send a new one?

**Comment by szymor** [comment]
In the long run it is better to use a pip package as it resolves dependency issues smoothly.

**Comment by kittenvr** [comment]
> In the long run it is better to use a pip package as it resolves dependency issues smoothly.

this pip?
![image](https://github.com/user-attachments/assets/1be67fd0-05ef-4e21-a28b-9a14cd46b07e)

**Comment by szymor** [comment]
Yes, you can use pipx for your convenience.

**Comment by kittenvr** [comment]
> Yes, you can use pipx for your convenience.

like i said before the link to the faq page telling me how to use the pipx is expired

**Comment by szymor** [comment]
pipx install aider-chat

**Comment by paul-gauthier** [comment]
This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html
