### ISSUE TITLE
Can we use Microsoft's openai-service?

### ISSUE THREAD

**Issue by bbwl521** [paul-gauthier/aider#617]
https://azure.microsoft.com/zh-cn/products/ai-services/openai-service/
Can we use Microsoft's openai-service?

![image](https://github.com/paul-gauthier/aider/assets/44896926/e635aaa1-2db2-441e-b7da-21b01ba3abe2)

There are too many fed files and no reply. What's the problem?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Aider works with OpenAI models on Azure, yes:

https://aider.chat/docs/llms.html#azure

Can you share the "announce" lines that aider prints when it runs so I can see the aider version and the size of your repo?

Also, it looks like you may be adding too many files to the chat. There's a FAQ entry that might contain helpful information:

https://aider.chat/docs/faq.html#how-can-i-add-all-the-files-to-the-chat

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
