### ISSUE TITLE
Question : Retrieval of Repo Map Context 

### ISSUE THREAD

**Issue by Mage1507** [paul-gauthier/aider#618]
### Issue

**How can I extract the repo map context using Aider if repo path is provided? Below is the code I used, but it returns "None"**

`from aider.models import Model
from aider.repomap import RepoMap
from aider.io import InputOutput

chat_fnames = [""]

model = Model("gpt-4o", weak_model="gpt-3.5-turbo")

io = InputOutput()

rm = RepoMap(
    map_tokens=1024,
    root=None,
    main_model=model,
    io=io,
    max_context_window=model.info.get("max_input_tokens"),
)

repo_map = rm.get_ranked_tags_map(chat_fnames)

print(repo_map)`

**Expected Output :**

.gitignore
 
admin_tools.py
 
app.py:
⋮...
│def create_app(test_config=None):
⋮...
 
frontend/src/App.js
 
frontend/src/Dashboard.js:
⋮...
│const Dashboard = () => {
│  const [players, setPlayers] = useState([]);
│  const [loading, setLoading] = useState(true);
│  const [error, setError] = useState('');
│
│  useEffect(() => {
│    const fetchPlayers = async () => {
│      try {
│        const response = await axios.get(`${process.env.REACT_APP_BACKEND_URL || 'http://localhost:5000'}/players`);
│        setPlayers(response.data);
│      } catch (error) {
│        const errorMessage = error.response && error.response.data.message ? error.response.data.message : 'Failed to fetch players. Please try again
later.';
│        console.error("Failed to fetch players:", error);
│        setError(errorMessage);
│      } finally {
│        setLoading(false);
⋮...
 
frontend/src/LiveDraftBoard.js

**Actual Output :**

None

### Version and model info

Aider v0.36.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. FYI, the API to use the `RepoMap` class is not officially supported and may change at any time.

A quick glance at your code makes me wonder why you are passing in `chat_files=[""]` not `chat_files=[]` or `chat_files=None`? Also, you probably should be calling `get_repo_map()` and you'll need to pass in all the files in the repo split between `chat_files` and `other_files`.

**Comment by Mage1507** [comment]
Hi @paul-gauthier  thanks for your response. I am passing the directory path or file path like this **chat_files=["../api/routes.py"]** to get the repo map context of the file or entire directory. 

Even I am calling the get_repo_map() with the filepath I am getting the same "None" error .

Could you provide me with the specific code or advice on how to obtain the repository map context when given the path of a directory or file?

**Comment by shail-git** [comment]
hey @Mage1507 you manually need to get the list of source files in the repo , you can use the find_src_files function in repomap module.
i am using version 0.36.0 , imported with the following:
from aider.repomap import RepoMap, find_src_files

that will return a list of src files from the directory. pass that into the get repomap function as other_files and it should work

**Comment by OwenWo0** [comment]
Hi @Mage1507 , actually if you only want the RepoMap structure of your codebase, the easiest way is to instantiate `Coder`, which you can find a prototype in the main. Then just call `coder.get_repo_map()`. 
That works for me.

**Comment by Mage1507** [comment]
Hi @shail-git  and @OwenWo0  thanks for your answers. It's now working as expected.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
