### ISSUE TITLE
Text selection

### ISSUE THREAD

**Issue by DerKorb** [paul-gauthier/aider#62]
Hi, 
awesome tool! I have been coding in similiar directions for quite some while and have also tried all kinds of autogpt etc. but nothing provided nearly the same utility yet!
Have you put some thought into selecting existing code in a more token efficient way? Right now it often generates huge chunks of code, only to replace a single line within.
I was thinking about having some mechanism similar to how CRISPR uses guide RNA. So take a few tokens before and after where you want to place a cursor. A selector would look like this:
 path = [Cursor]os.path.join(
This way you could select arbitrary segments of code using only a few tokens.

**Comment by 2812427914** [comment]
i think we have some views in common, i tried autogpt, gpt-engineer, aider. each of them are very interesting to explore. but not flexible. not flexible for human Human intervention, not flexible on model  output. in my newly designed tool, context selecting and output constrain is crucial. very glad to see the same idea and look forward to your new progress.

**Comment by paul-gauthier** [comment]
Sorry, I'm not sure I understand the suggestion you are making. If you'd like to provide more info, I'd be happy to consider it.

**Comment by DerKorb** [comment]
I am still tuning a few ideas.
1.  What I tried to describe above: Have GPT4 place cursors in the code to make edits. The idea here would be chatGPT regurgitating a few tokens one by one and placing a Pipe as cursor in it while doing so. I could then find the matching tokens in the code and place a "cursor" accordingly. It is quite similiar to your approach, only responding more token efficient for the part to be replaced. I also hope this would lead it to make smaller edits.
> Place two cursors before at the beginning and end of the snippet. Use '|' to represent a cursor. For both cursors, return sections that include the cursor and the 10 characters immediately before and after it, to give context for positioning.

2. if there is a bash way to do edits, explaining the concept would be easy. I asked chatgpt and it suggested `sed`. It does howevery not support multiline edits so I tried this:
> To make an edit answer with:
> - a regex selecting a part of code that will be removed, keep it short
> - [optional] new code to insert at the position

Both approaches gave decent results on a few experiments in the playground, but I  guess they would still be prone to errors.

**Comment by DerKorb** [comment]
Maybe I was missing the context before: This is about making aiders code edits more token efficient by minimizing the response lenght of what code to replace.

**Comment by paul-gauthier** [comment]
Ah, I see. Thanks for clarifying.

I have done quite a bit of experimenting with asking GPT to use more compact "edit formats". I've tried many formats including `sed` , `diff -c`, `diff -u`, etc.

My experience is that GPT generally *codes worse* and *messes up the the edit syntax* when you push it in this direction. 

I recently did some systematic benchmarking which agree with this intuition. I wrote up some notes which you might find useful if you're experimenting with prompts for code editing:

https://aider.chat/docs/benchmarks.html

**Comment by DerKorb** [comment]
awesome, that is definitely an interesting read for me!
My other approach is using the AST (doing typescript) and providing function_calls like removeMethod, addMethod, etc provided by the language server. But of course that is not language agnostic. My tool is able to /add code itself and I'm also experimenting with ignoring filenames alltogether and only working with identifiers and code.

**Comment by DerKorb** [comment]
Well, I guess that readme more or less completely answers my questions. Very intersting, nice idea with the benchmark.
