### ISSUE TITLE
Is there any tutorial or docs for evaluating SWEBench lite using aider?

### ISSUE THREAD

**Issue by K-tang-mkv** [paul-gauthier/aider#620]
### Issue

I found you guys doing an awesome work on evaluating SWEBench lite using aider in this post https://aider.chat/2024/05/22/swe-bench-lite.html, can you provide any implementation details?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The benchmark harness that I've been using probably isn't tidy enough for other folks to use. I hope to publish it soon though.

**Comment by K-tang-mkv** [comment]
Really appreciate what you did! Looking forward your great work publishing out.

**Comment by paul-gauthier** [comment]
I just pushed the SWE Bench harness to a new repo:

https://github.com/paul-gauthier/aider-swe-bench

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
