### ISSUE TITLE
Question : Requesting for logic change in repomap.py and scm for html , sql 

### ISSUE THREAD

**Issue by Mage1507** [paul-gauthier/aider#621]
### Issue

I am trying to obtain the repository map context for a folder that contains HTML and SQL files. However, the logic in the **repomap.py** file for retrieving tags only targets keywords containing "ref" and "def." This approach is not suitable for HTML and SQL files since they do not include tags like name.definition(def) or name.reference(ref)

Could you please provide the correct SCM query file for HTML and SQL that adapts to our current repomap logic, or provide guidance on how to modify the repomap logic to suit HTML and SQL files?

Reference : 

https://github.com/paul-gauthier/aider/blob/main/aider/repomap.py#L186
https://github.com/paul-gauthier/aider/blob/main/aider/repomap.py#L279

**SCM used for HTML :** 

(tag_name) @tag
(erroneous_end_tag_name) @tag.error
(doctype) @constant
(attribute_name) @attribute
(attribute_value) @string
(comment) @comment
 
[
  "<"
  ">"
  "</"
  "/>"
] @punctuation.bracket
 
((script_element
  (raw_text) @injection.content)
(#set! injection.language "javascript"))
 
((style_element
  (raw_text) @injection.content)
(#set! injection.language "CSS"))

**SCM used for SQL :**

(string) @string
(number) @number
(comment) @comment

(function_call
    function: (identifier) @function)

[
  (NULL)
  (TRUE)
  (FALSE)
] @constant.builtin

([
  (type_cast
   (type (identifier) @type.builtin))
  (create_function_statement
   (type (identifier) @type.builtin))
  (create_function_statement
   (create_function_parameters
     (create_function_parameter (type (identifier) @type.builtin))))
  (create_type_statement
    (type_spec_composite (type (identifier) @type.builtin)))
  (create_table_statement
   (table_parameters
     (table_column (type (identifier) @type.builtin))))
 ]
 (#match?
   @type.builtin
    "^(bigint|BIGINT|int8|INT8|bigserial|BIGSERIAL|serial8|SERIAL8|bit|BIT|varbit|VARBIT|boolean|BOOLEAN|bool|BOOL|box|BOX|bytea|BYTEA|character|CHARACTER|char|CHAR|varchar|VARCHAR|cidr|CIDR|circle|CIRCLE|date|DATE|float8|FLOAT8|inet|INET|integer|INTEGER|int|INT|int4|INT4|interval|INTERVAL|json|JSON|jsonb|JSONB|line|LINE|lseg|LSEG|macaddr|MACADDR|money|MONEY|numeric|NUMERIC|decimal|DECIMAL|path|PATH|pg_lsn|PG_LSN|point|POINT|polygon|POLYGON|real|REAL|float4|FLOAT4|smallint|SMALLINT|int2|INT2|smallserial|SMALLSERIAL|serial2|SERIAL2|serial|SERIAL|serial4|SERIAL4|text|TEXT|time|TIME|time|TIME|timestamp|TIMESTAMP|tsquery|TSQUERY|tsvector|TSVECTOR|txid_snapshot|TXID_SNAPSHOT|enum|ENUM|range|RANGE)$"))

(identifier) @variable

[
  "::"
  "<"
  "<="
  "<>"
  "="
  ">"
  ">="
] @operator

[
  "("
  ")"
  "["
  "]"
] @punctuation.bracket

[
  ";"
  "."
] @punctuation.delimiter

[
  (type)
  (array_type)
] @type

[
 (primary_key_constraint)
 (unique_constraint)
 (null_constraint)
] @keyword

[
  "AND"
  "AS"
  "AUTO_INCREMENT"
  "CREATE"
  "CREATE_DOMAIN"
  "CREATE_OR_REPLACE_FUNCTION"
  "CREATE_SCHEMA"
  "TABLE"
  "TEMPORARY"
  "CREATE_TYPE"
  "DATABASE"
  "FROM"
  "GRANT"
  "GROUP_BY"
  "IF_NOT_EXISTS"
  "INDEX"
  "INNER"
  "INSERT"
  "INTO"
  "IN"
  "JOIN"
  "LANGUAGE"
  "LEFT"
  "LOCAL"
  "NOT"
  "ON"
  "OR"
  "ORDER_BY"
  "OUTER"
  "PRIMARY_KEY"
  "PUBLIC"
  "RETURNS"
  "SCHEMA"
  "SELECT"
  "SESSION"
  "SET"
  "TABLE"
  "TIME_ZONE"
  "TO"
  "UNIQUE"
  "UPDATE"
  "USAGE"
  "VALUES"
  "WHERE"
  "WITH"
  "WITHOUT"
] @keyword

**Comment by Mage1507** [comment]
Hi @paul-gauthier  thanks for your response. Below is the thing I am trying to do ,

- I am using Aider to analyze and implement changes in my existing codebase, which contains HTML and SQL files. However, the repo map for these files did not provide the necessary context. 
- Then I discovered that there was no SCM file for the HTML and SQL languages, so I created one with reference to the Tree-Sitter repo. Despite using these files, Aider still did not generate the context.

**Comment by paul-gauthier** [comment]
I guess I'm wondering why you concluded that "the repo map isn't providing the necessary context"? Is there some specific change you tried to make that didn't work? And if so, how did you conclude the repo map was a cause?

**Comment by Mage1507** [comment]
Hi @paul-gauthier If I'm not mistaken, the repo map context helps Aider determine which file needs modification. The context is generated based on the scm files provided. If there are no scm files for the relevant languages, the context won't be generated, and Aider won't be able to accurately guess the correct file.

**Comment by paul-gauthier** [comment]
I am asking if you asked aider for some specific code change that it wasn't able to provide?

Your concerns are reasonable in the abstract. But you shouldn't worry prematurely. Just try using aider to accomplish your task. It will probably work.

**Comment by Mage1507** [comment]
ok @paul-gauthier sure . Thanks for your support.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
