### ISSUE TITLE
Broken link in blogpost: 2024/05/22/swe-bench-lite.html

### ISSUE THREAD

**Issue by 0xdevalias** [paul-gauthier/aider#624]
### Issue

FYI, noticed that this blog: https://aider.chat/2024/05/22/swe-bench-lite.html

Has a broken link in the Acknowledgements: https://aider.chat/2024/05/22/SWE-bench-docker

### Version and model info

N/A

**Comment by paul-gauthier** [comment]
Thanks!

**Comment by 0xdevalias** [comment]
Np :)
