### ISSUE TITLE
Windows Defender deleting aider.exe

### ISSUE THREAD

**Issue by KhaledElbasiouni** [paul-gauthier/aider#628]
### Issue

Windows Defender (WD) is detecting `Trojan:Win32/Cinjo.O!cl` and thinks the culprit is `Python312/Scripts/aider.exe`.

After restarting my device, WD seems to have performed a scan of the device and keeps deleting `aider.exe`.

Adding the `Python312/Scripts` folder to the list of folders excluded from being scanned by Defender Antivirus prevents `aider.exe` from being deleted.

### Version and model info

Aider v0.36.0

Windows Edition: Windows 11 Enterprise
Version: 23H2

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

My best guess is there's something wrong with your local environment. Perhaps you have malware on your machine and it's infecting random executables.

The aider releases are built by [GitHub's Actions platform](https://github.com/paul-gauthier/aider/blob/main/.github/workflows/release.yml). It would be very surprising if it was compromised and generating code that contained malware.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
