### ISSUE TITLE
bug:  some environment vars are not read from .env or --env-file

### ISSUE THREAD

**Issue by jpshack-at-palomar** [paul-gauthier/aider#630]
### Issue

Only environment vars actually set in the environment and not those set in .env are reflected in `--verbose` output for me. There are three sections:  `environment variables`, `defaults`, and `options`. The  I have tried setting for  `AIDER_DARK_MODE=True` or `DARK_MODE=True` as well as other options such as `AIDER_LINT_CMD` and `AIDER_TEST_CMD` but see nothing reflected in any of those three sections.  

paulg confirmed in discord:  You are correct. The .env file is not wired up to set AIDER_xxx variables. 

### Version and model info

Aider v0.36.0.

**Comment by paul-gauthier** [comment]
You can now set all `AIDER_xxx` env vars in a .env file.

https://aider.chat/docs/dotenv.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
