### ISSUE TITLE
outputs to commit message instead of file

### ISSUE THREAD

**Issue by kb-** [paul-gauthier/aider#634]
### Issue

Output code ends up in the commit message and file remains unedited when I try this:

[dash_qt_demo.py.txt](https://github.com/user-attachments/files/15519702/dash_qt_demo.py.txt)

> (env312) PS C:\Users\xx\Documents\python\calc> aider --edit-format udiff --model ollama/llama3
> Aider v0.36.0
> Model: ollama/llama3 with udiff edit format
> Git repo: .git with 3 files
> Repo-map: disabled
> Use /help to see in-chat commands, run with --help to see cmd line args
> ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> > Modify the dash_qt_demo.py file to change the plot lines to be dashed instead of solid.
> 
> ai\dash_qt_demo.py
> Add these files to the chat? y
> I'll modify the dash_qt_demo.py file to change the plot lines to be dashed instead of solid. Here's the modified code:
> 
> 
>  --- dash_qt_demo.py
>  +++ dash_qt_demo.py
>  @@ -34,7 +34,7 @@
>           "data": [
>               {
>  -                "type": "scatter",
>  +                "type": "scatter",
>                   "mode": "lines+dots",  # Changed from "lines" to "lines+dots"
>                   "name": "sin(x)",
>                   "meta": ["some meta info"],
>               },
> 
> 
> In this modified code, I changed the mode parameter in the first plot line from "lines" to "lines+dots", which will make the lines dashed.
> 
> 
> Allow creation of new file dash_qt_demo.py? y
> Applied edit to dash_qt_demo.py
> Commit 816bc89 aider: Changed plot lines to be dashed instead of solid.
> ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> ai\dash_qt_demo.py dash_qt_demo.py

```
PS C:\Users\olivi\Documents\python\calc> git log
commit 816bc891653feb368e7aa4dfd405b5c630241cf2 (HEAD -> master)
Author: kb- <xx.com>
Date:   Sat Jun 1 02:17:14 2024 +0200

    aider: Changed plot lines to be dashed instead of solid.

    # Aider chat conversation:

    USER: Modify the dash_qt_demo.py file to change the plot lines to be dashed instead of solid.

    ASSISTANT: I'll modify the dash_qt_demo.py file to change the plot lines to be dashed instead of solid. Here's the modified code:

    ```diff
    --- dash_qt_demo.py
    +++ dash_qt_demo.py
    @@ -34,7 +34,7 @@
             "data": [
                 {
    -                "type": "scatter",
    +                "type": "scatter",
                     "mode": "lines+dots",  # Changed from "lines" to "lines+dots"
                     "name": "sin(x)",
                     "meta": ["some meta info"],
                 },
    ```

    In this modified code, I changed the `mode` parameter in the first plot line from `"lines"` to `"lines+dots"`, which will make the lines dashed.

```

### Version and model info

Aider v0.36.0
Model: ollama/llama3 with udiff edit format
Git repo: .git with 3 files
Repo-map: disabled

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
