### ISSUE TITLE
Benchmark aider on AutoCoder model?

### ISSUE THREAD

**Issue by 0xdevalias** [paul-gauthier/aider#636]
### Issue

AutoCoder was released recently, and makes some GPT-4-level claims. It would be interesting to see how aider performs with it, and how that stacks up against other benchmarks:

- https://github.com/bin123apple/AutoCoder
  - > We introduced a new model designed for the Code generation task. Its test accuracy on the HumanEval base dataset surpasses that of GPT-4 Turbo (April 2024). (90.9% vs 90.2%).
    > 
    > Additionally, compared to previous open-source models, AutoCoder offers a new feature: it can automatically install the required packages and attempt to run the code until it deems there are no issues, whenever the user wishes to execute the code.

### Version and model info

N/A

**Comment by paul-gauthier** [comment]
Is anyone hosting it as a cloud api endpoint?

**Comment by 0xdevalias** [comment]
> Is anyone hosting it as a cloud api endpoint?

@paul-gauthier Off the top of my head/from a quick Google I didn't immediately come across any. 

Curious, what are your needs for 'cloud hosted API'? Would it work to spin it up on a 'cloud GPU' service like Runpod/etc:

- https://www.runpod.io/gpu-instance/pricing
- https://vast.ai/pricing
- https://akash.network/gpus/

Through one of the standard open source 'LLM hosting interfaces':

- https://github.com/vllm-project/vllm
  - > A high-throughput and memory-efficient inference and serving engine for LLMs
  - https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html
    - > OpenAI Compatible Server
      > vLLM provides an HTTP server that implements OpenAI’s Completions and Chat API.
    - https://docs.vllm.ai/en/stable/models/supported_models.html
      - > Supported Models
        > vLLM supports a variety of generative Transformer models in [HuggingFace Transformers](https://huggingface.co/models). The following is the list of model architectures that are currently supported by vLLM. Alongside each architecture, we include some popular models that use it.
        - https://huggingface.co/models?sort=trending&search=autocoder
          - Seems to be listed here, so I assume it should be usable?
    - https://docs.vllm.ai/en/stable/models/adding_model.html
      - > Adding a New Model
        > This document provides a high-level guide on integrating a [HuggingFace Transformers](https://github.com/huggingface/transformers) model into vLLM.
  - https://github.com/runpod-workers/worker-vllm
    - > OpenAI-Compatible vLLM Serverless Endpoint Worker
- etc

The AutoCoder models are available here:

- https://github.com/bin123apple/AutoCoder#model
  - > The Model is avaliable on Huggingface: [AutoCoder (33B)](https://huggingface.co/Bin12345/AutoCoder) [AutoCoder-S (6.7B)](https://huggingface.co/Bin12345/AutoCoder_S_6.7B)
    > 
    > The base model is `deepseeker-coder`.
    - https://huggingface.co/Bin12345/AutoCoder
    - https://huggingface.co/Bin12345/AutoCoder_S_6.7B
    - https://deepseekcoder.github.io/
      - https://github.com/deepseek-ai/DeepSeek-Coder

**Comment by paul-gauthier** [comment]
Sure, we could spin it up anywhere. It's just much easier to hit a cloud api, given the large number of models folks would like to see benchmarked.

**Comment by 0xdevalias** [comment]
> It's just much easier to hit a cloud api, given the large number of models folks would like to see benchmarked.

@paul-gauthier _nods_, for sure. Even with that caveat, I feel like RunPod might be a good fit for it. In addition to the links above, also just found this docs page:

- https://docs.runpod.io/category/vllm-endpoint
  - > Deploy blazingly fast OpenAI-compatible serverless endpoints for any LLM.
  - https://docs.runpod.io/serverless/workers/vllm/overview
    - > Use the `runpod/worker-vllm:stable-cuda11.8.0` or `runpod/worker-vllm:stable-cuda12.1.0 `image to deploy a vLLM Worker. The vLLM Worker can use most Hugging Face LLMs and is compatible with OpenAI's API, by specifying the `MODEL_NAME` parameter.
  - https://docs.runpod.io/serverless/workers/vllm/get-started
    - https://docs.runpod.io/serverless/workers/vllm/get-started#send-a-request
      - > Send a request
        > This section walks you through sending a request to your Serverless Endpoint. The vLLM Worker can use any Hugging Face model and is compatible with OpenAI's API. If you have the OpenAI library installed, you can continue using it with the vLLM Worker.
- https://docs.runpod.io/cli/overview
  - > RunPod CLI (`runpodctl`) is a command-line interface tool designed to automate and manage GPU pods on RunPod.
    >
    > This tool facilitates efficient interaction with RunPod's cloud computing platform, enabling you to execute code, transfer data, and manage computing resources seamlessly.

It seems like it should be fairly straightforward (as much as any tech task ever is at least) to spin up a vLLM worker (potentially even scripted via the RunPod CLI) with whichever model that's desired to benchmark against; and then can connect to it using an OpenAI compatible API; so should only be like 1 small step extra beyond finding a 'native cloud API' for the models.

**Comment by paul-gauthier** [comment]
Sure, but unfortunately I'm not able to make the time to spin up a server for every new model that comes out.

**Comment by 0xdevalias** [comment]
> unfortunately I'm not able to make the time to spin up a server for every new model that comes out.

@paul-gauthier I'm starting to sense that there may be some miscommunication / misinterpretation. When you say "not able to make the time to spin up a server for every new model, is it actually the issue of "spinning up a server"/etc (vs using an existing cloud API); or is the core of the issue more that "I can't benchmark against every model"?

So far, I have been operating on the assumption that you meant the former, and was looking to provide solutions in that space. But if you've actually been intending to convey they latter, then that's a very different story, and completely understandable.

**Comment by 0xdevalias** [comment]
Just noticed this pricing mentioned on another repo:

- https://github.com/aorwall/moatless-tools
  - > I use the SWE-bench benchmark as a way to verify these ideas. Currently, Moatless Tools has a solution rate of 24%, **with each benchmark instance costing an average of $0.13 to solve with GPT-4o. Running the SWE Bench Lite dataset with 300 instances costs approx 40 dollars.**

It would be interesting to see the costs of evaluation alongside the results. That might also give people a more tangible feel for how much it costs when they ask for an arbitrary model to be benchmarked (or alternatively, if there is an 'easy formula' for them to follow to do the testing, may motivate them to be like "oh, it's only $X, maybe I will run it myself!".

**Comment by paul-gauthier** [comment]
I try and benchmark as many noteworthy models as I can. But time spent benchmarking is time not spent improving aider. So I have to balance priorities. It's typically most efficient to benchmark models available on a cloud api and significantly more complex to spin up a local or cloud instance to benchmark a model. So most of the benchmarking I do is against cloud apis.

Folks are always welcome to submit benchmark results as a PR.
https://aider.chat/docs/leaderboards/#contributing-benchmark-results

The costs are in the raw yml benchmark data, but are not always reliable. I am often benchmarking models within hours of their release, and the cost database metadata isn't always up-to-date or available yet. Costs often change over time. For these reasons I am reluctant to publish the costs data in the table and commit to the effort required to make and keep it accurate.

**Comment by 0xdevalias** [comment]
> But time spent benchmarking is time not spent improving aider. So I have to balance priorities.

Totally understandable.

> It's typically most efficient to benchmark models available on a cloud api and significantly more complex to spin up a local or cloud instance to benchmark a model.

While I hear you on this point, I feel like the info provided earlier RE: Runpod and basically a single command to spin up the equivalent of a cloud API probably doesn't fit into 'significantly more complex', at least by my definition of it.

> Folks are always welcome to submit benchmark results as a PR.
> [aider.chat/docs/leaderboards/#contributing-benchmark-results](https://aider.chat/docs/leaderboards/#contributing-benchmark-results)

Oh interesting. Somehow I totally missed that section before. That's good to know!

> The costs are in the raw yml benchmark data, but are not always reliable.

True true, that's also good to know.

> I am often benchmarking models within hours of their release, and the cost database metadata isn't always up-to-date or available yet. Costs often change over time. For these reasons I am reluctant to publish the costs data in the table and commit to the effort required to make and keep it accurate.

_nods_ understandable.

---

Aspirationally I would like to say that I will follow my own instructions above for running an API on Runpod, and then the benchmark instructions to run/submit a benchmark for AutoCoder; but if I'm being honest with myself, it'll probably slip pretty far down my TODO list (based on the things that have already been sitting there forever that I'm only just getting to)

Based on that, I'm happy for you to close this issue if it's not something you feel like you will have bandwidth/interest in doing; or to leave it open if you'd prefer it stay 'more visible' in the hopes someone else might like to run the benchmarks.

Either way, I'll put this on my TODO list, and if/when I get to it, can comment here again to re-open, or just submit the results on a new PR or similar.

**Comment by paul-gauthier** [comment]
I'm probably not going to keep open issues for benchmarking requests.

So I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
