### ISSUE TITLE
feat:  Add a command-line issue that writes out a yaml or .env file w/ defaults and instructions

### ISSUE THREAD

**Issue by jpshack-at-palomar** [paul-gauthier/aider#637]
### Issue

To promote an easy getting started experience add a command-line option that would write-out config files with comments, defaults and examples so as to reduce errors and config questions.

`aider --write-conf-template-yml $HOME` or `aider --write-conf-template-env $HOME` writes an .aider.conf.yml or .env file to your home dir. (If the argument is omitted the template is written to stdout.)

Pull request forthcoming.

### Version and model info

N/A

**Comment by scruffynerf** [comment]
new user, and wanted to test this out.  Discovered it defaulted to auto git commit, to my shock.  Realized I wanted to make a config file, and couldn't find one in docs or repo, so looked in issues, and was pleased to see this will happen.

(Yes, it's easy to make a trivial config... but a sample one would go a long way.

**Comment by paul-gauthier** [comment]
There's now a reference and sample yaml file in the docs.

https://aider.chat/docs/aider_conf.html
