### ISSUE TITLE
[Idea] Using embeddings and Search Indexing

### ISSUE THREAD

**Issue by PriNova** [paul-gauthier/aider#64]
The following idea would be to convert the repository(s) as vector embeddings and combine them with ctags. I.e. the prompt would be compared as embedding with a VectorDB and from this the 5-10 highest ranking results would be taken. Then the context scope would be determined. This can then be passed to the LLM and conclusions can be drawn from it.

What do you think about it?

**Comment by paul-gauthier** [comment]
Yup, something along those lines is likely to be helpful.

See also issue #1 for some previous discussion.
