### ISSUE TITLE
Question: Generate new project using Aider?

### ISSUE THREAD

**Issue by Michal-Mikolas** [paul-gauthier/aider#640]
### Issue

Hello,  
how can I start new project from scratch using Aider? For example, how can I tell Aider to _"Generate boilerplate for Chrome extension which will have popup window with one button."_ ? 

Such task requires creation of multiple files. And I want Aider to think of the proper file names, it's content etc. 

Thank you.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Have try tried running aider in an empty directory and literally typing "Generate boilerplate for Chrome extension which will have popup window with one button"  into the chat? I just did, and aider made some logical looking files...

```
> Generate boilerplate for Chrome extension which will have popup window with one button.

Here is the boilerplate code for a Chrome extension with a popup window containing one button:

...

This setup includes:

 1 manifest.json to define the extension.
 2 popup.html for the popup window with a button.
 3 popup.js to handle the button click event.
 4 Placeholder paths for icon images.
```

**Comment by Michal-Mikolas** [comment]
Wow that works, thank you :-)
