### ISSUE TITLE
Is there the posibility to add another models or get cheap? 

### ISSUE THREAD

**Issue by AxolotDevelopment** [paul-gauthier/aider#641]
### Issue

First I want to say that this tool is the best tool I have ever tried, what happens is that it is becoming very expensive in terms of openai tokens and more so as my project grows... Is there any way I can run a model locally or an alternative that can be compared to gpt-4o? Currently with the 128K of context it can do an update with a single prompt and hit the nail on the head with all the files it needs, so I don't know if that level of quality could be achieved in a more economical way...

Anyway, your tool is incredible, I hope you continue to progress with it

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. See the [LLM leaderboards](https://aider.chat/docs/leaderboards/) for rankings of how capable the various models are. See the [docs on connecting to LLMs](https://aider.chat/docs/llms.html) for recommended models, including some free ones.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
