### ISSUE TITLE
aider browser

### ISSUE THREAD

**Issue by nas-maker** [paul-gauthier/aider#643]
### Issue

Hi, I'm trying to use the Aider browser, but the default model is GPT-4. How can I switch to a different model?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The browser version of aider is currently experimental and has less functionality than the CLI version. To switch models, you will need to restart aider and run it specifying the new model:

Here's how to run it with Opus:
```
aider --browser --opus
```

Or see the docs for examples of how to use other models. Just add `--browser` to also start up the browser version.

https://aider.chat/docs/llms.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
