### ISSUE TITLE
azure/gpt-4-turbo-vision-preview only returns a few tokens before returning 'The chat session is larger than the context window!'

### ISSUE THREAD

**Issue by rhabraken** [paul-gauthier/aider#645]
### Issue

The model has a context window of 128.000 tokens so something funny is going on. 

https://community.openai.com/t/documented-max-token-default-is-incorrect-for-gpt-4-vision-preview/507329

Looks like the max_tokens is incredibly low for this model and should be set manually for every request. I couldn't find a way to set the max_tokens param, is there a way?

**Comment by NeuralAIM** [comment]
Same with `deepseek/deepseek-chat`:
![image](https://github.com/paul-gauthier/aider/assets/75082388/e49dcd46-6036-4bd0-ae77-6f4a741b80f1)

I try using:
1. `aider --model deepseek/deepseek-chat --max-chat-history-tokens 32000`
2. `setx AIDER_MAX_CHAT_HISTORY_TOKENS 32000`

**Comment by paul-gauthier** [comment]
Thanks for trying aider!

Why are you trying to set `--max-chat-history-tokens`? You shouldn't need to do that, and it should probably not be set to such a high value.

Have you tried running aider simply with `aider --model deepseek/deepseek-chat`?

**Comment by rhabraken** [comment]
Hello Paul, 

I didn't set the --max-chat-history-tokens, but still got the same message. 
I tried aider --model azure/gpt-4-turbo-vision-preview and I got the error above.
I don't get the error with other models like for example aider --model azure/gpt-4.

![image](https://github.com/paul-gauthier/aider/assets/36812420/a1d100cb-b6db-48c3-a065-a370c6fd2ef9)

**Comment by NeuralAIM** [comment]
> Have you tried running aider simply with `aider --model deepseek/deepseek-chat`?

Yes, I tried. But it did not help.

**Comment by djh00t** [comment]
I get it when running with `gpt-4o` too.

**Comment by rodion-m** [comment]
The same problem with gpt-4o. @paul-gauthier Could you please assist us?

**Comment by Batyan45** [comment]
Same problem

**Comment by paul-gauthier** [comment]
Can you show me all the announce lines that aider prints on startup? And all switches/config that you have set?

Aider should only print that error when the server returns a response that indicates it stopped because of token window limits. 

Are you connecting directly to the API provider? Or is there some firewall or proxy in between which could be failing to speak the correct openai API protocol?

Is the model outputting a lot of text before this error? Every model has a limit of how many output tokens it can emit. Often as low as 4k.

**Comment by djh00t** [comment]
I use the following in .bashrc aliases:

```
alias aider1='command -v aider >/dev/null 2>&1 || { echo >&2 "aider not found, installing..."; pip install aider-chat; }; aider --model gpt-4-turbo --no-auto-commits'
alias aider2='command -v aider >/dev/null 2>&1 || { echo >&2 "aider not found, installing..."; pip install aider-chat; }; aider --model gpt-4o --no-auto-commits'
alias aider3='command -v aider >/dev/null 2>&1 || { echo >&2 "aider not found, installing..."; pip install aider-chat; }; aider --no-auto-commits'
```

Here is the startup screen:

```
Aider v0.37.0
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 66 files
Repo-map: using 1024 tokens
Added push/push4 to the chat.
VSCode terminal detected, pretty output has been disabled.
Use /help to see in-chat commands, run with --help to see cmd line args
───────────────────────────────────────────────────────────────────────────────────────
push/push4> 
```


Here is the console output:

```
The chat session is larger than the context window!

Approximate context window usage, in tokens:

$ 0.0054    1,086 system messages                      
$ 0.0067    1,330 chat history                         use /clear to clear
$ 0.0107    2,141 push/code_audit.md                   use /drop to drop from chat
$ 0.0034      683 klingon_tools/code_audit_template.j2 use /drop to drop from chat
$ 0.0207    4,137 push/push4                           use /drop to drop from chat
==================
$ 0.0469    9,377 tokens total
          118,623 tokens remaining in context window
          128,000 tokens max context window size

To reduce token usage:
 - Use /drop to remove unneeded files from the chat session.
 - Use /clear to clear chat history.
 ```

**Comment by randoentity** [comment]
Try adding max_tokens=128000 to send_with_retries, kwargs dict in aider/sendchat.py.
If this is it, then passing the remaining tokens would be my next step.

**Comment by paul-gauthier** [comment]
@djh00t how much output is coming back from the LLM before it throws the context window exception? Every model has a limit of how many output tokens it can emit. Often as low as 4k tokens.

**Comment by paul-gauthier** [comment]
I have added more docs about LLM token limits:

https://aider.chat/docs/troubleshooting/token-limits.html

I've also updated aider to print more specific and helpful error messages. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, please share the error output here if you continue to see token limit errors.

**Comment by rodion-m** [comment]
Thanks a lot for the update! Is there a chance that you will update a package too?

Btw, I hope the aider doesn't limit LLM's output to 4k, because of the Gemini Pro output limit of 8k.

**Comment by paul-gauthier** [comment]
Aider doesn't enforce a limit. The LLMs enforce their own limits.

These changes will go out in the next aider release, which should be soon.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by rodion-m** [comment]
@paul-gauthier the bug still persists. This is a screenshot from my friend: 
![image](https://github.com/paul-gauthier/aider/assets/36400912/ff6ab510-f380-4bbe-abbc-a55c993068ff)
He uses aider from main branch.

**Comment by iamwavecut** [comment]
^ Yep, that's me

Also, I have no screenshot but I've got nearly the same error while using anthropic's claude 3/5 sonnet with 200k context window, will update if encounter again
