### ISSUE TITLE
Aider support for hosted LLM (LLM gateway endpoint)

### ISSUE THREAD

**Issue by pratikmishra12008** [paul-gauthier/aider#646]
### Question

Does aider has support for self hosted LLM? 

I have my llama3 model hosted on web service to which I connect through an endpoint and api key.
If no, do we have it planned in future?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Yes, see the docs:

https://aider.chat/docs/llms.html

**Comment by amrrs** [comment]
Thanks for sharing the page @paul-gauthier is there any plan to support Mistral's new Codestral API?

**Comment by rocholojavinar** [comment]
![](https://img.youtube.com/vi/CyD8hAjj8L8/maxresdefault.jpg)

**Comment by paul-gauthier** [comment]
@amrrs if you have access to codestral, you can try it with aider. I believe it's available via ollama.

https://aider.chat/docs/llms/ollama.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
