### ISSUE TITLE
aider: error: unrecognized arguments

### ISSUE THREAD

**Issue by olafgeibig** [paul-gauthier/aider#652]
### Issue

I installed aider v0.37.0 into a fresh venv with python 3.11.7 on MacOS. I can't even simply run "aider". I checked that aider isn't installed in the global pyenv that I'm using. I even downgraded to 0.36.0 and 0.35.0 but it's the same issue.

```aider: error: unrecognized arguments: --skip-model-availability-check=True```

### Version and model info
aider v0.37.0
OpenAI API key is set

**Comment by olafgeibig** [comment]
Okay, found the problem. It was an old ~/.aider.conf.yml on this machine that set this argument

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
