### ISSUE TITLE
.NET: Add a support of auto-installing new NuGet package into the project or solution

### ISSUE THREAD

**Issue by rodion-m** [paul-gauthier/aider#655]
First, thanks a lot for a great tool! It really looks very good comparing with other copilots (I've tried a lot of).

Auto [installing for packages](https://learn.microsoft.com/en-us/nuget/install-nuget-client-tools?tabs=macos) can be easily made by editing .csproj (or Directory.Build.props) file, or by cli.

Perhaps, later I'll try to make a PR. @paul-gauthier what do you think about this feature?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Have you tried adding `.csproj` to the chat and asking aider to add the packages? It would probably edit the file and add them for you.

**Comment by rodion-m** [comment]
Thanks for the answer! Yes, in common case it can work well. But in a deeper dive, it's not so easy to add an appropriate version of the package, because it may depend on the framework version, and also, LLM may not be aware of the latest versions of the package. Also, it's nice to have it as an automatic feature, but with user approval (like part of the job).

**Comment by paul-gauthier** [comment]
I don't think we want to implement per-framework functionality in aider. I expect to let aider run shell commands soon. And it will probably know how to invoke the right commands for a .NET project.

See #528 for more info.

**Comment by rodion-m** [comment]
Wow, it's very nice! Anyways, let's leave this issue open to track this important feature.
