### ISSUE TITLE
Question / contributing test cases.

### ISSUE THREAD

**Issue by arthurwolf** [paul-gauthier/aider#658]
### Issue

Amazing project.

I'm under the impression that if I were to contribute additional test cases for the benchmark, that might help with getting those tasks to work in the long run, is that correct? 

If so, is there some way to contribute (typescript) tasks/test cases for the benchmark?

Or is there some even better path to getting aider to become capable of new things?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. The main aider benchmark is based on Exercism python problems. It probably wouldn't be hard for someone to adapt the benchmark harness to run Exercism problems for other languages.

But I'm not sure that's directly a way to get "aider to become capable of new things". Aider should work fine with typescript code bases.

Is there something you're trying to do that isn't working the way you'd expect?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
