### ISSUE TITLE
Feature request: giving aider an example PR or commit

### ISSUE THREAD

**Issue by aantn** [paul-gauthier/aider#659]
### Issue

I'm using aider to generate integrations (e.g. jira connector) for an open source project. Every integration has a standard format and requires editing the same files in a standard manner. (E.g. update config parsing, add example to Readme.)

It would be great if I could give aider an example github PR and instruct it to do the same exact thing for another integration. 

I'm comfortable scripting aider and will attempt to put something together myself, but if you have tips please let me know

**Comment by TheSnowGuru** [comment]
you can use /web command to scrape any data and add it to the discussion with aider, tell us how it went :)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. You may want to look over the docs on specifying coding conventions:

https://aider.chat/docs/conventions.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by aantn** [comment]
Awesome, was not familiar with /web
Thanks and no problem.
