### ISSUE TITLE
Request: add `__main__.py` file so that aider can be run like `python3 -m aider` (for those without configured paths)

### ISSUE THREAD

**Issue by DeflateAwning** [paul-gauthier/aider#674]
### Issue

Request: add a `__main__.py` file to the package, so that aider can be run like `python3 -m aider` (for those without configured paths)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You should be able to do:

```
python -m aider.main
```

**Comment by DeflateAwning** [comment]
Can you make is so that I only need to do `python -m aider`? This is a very common implementation for CLI-focused modules/python projects.

**Comment by paul-gauthier** [comment]
I had aider implement this. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by DeflateAwning** [comment]
`python -m aider -h` works now. Looks fixed to me. Thanks!
