### ISSUE TITLE
Feature Request: allow prompt to be passed in to launch of aider (arg on cli)

### ISSUE THREAD

**Issue by paul-hammant** [paul-gauthier/aider#675]
### Issue

Add a `--prompt` option. Example of use below:

```
aider --no-auto-commits --prompt "fix up any spelling mistakes you can see; then exit" path/to/mybook.md
```
With that, allow an `exit()` capability too.

### Version and model info

$> aider --version           
aider 0.37.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This may be helpful:

https://aider.chat/docs/scripting.html
