### ISSUE TITLE
Support cursor shape configuration for VI mode from prompt-toolkit

### ISSUE THREAD

**Issue by joerideg** [paul-gauthier/aider#676]
### Issue

First of all thank you for this amazing project! 

Loving the new `--vim` flag as I'm a nvim user. One thing I am missing is the context whether I'm in 'normal' or 'insert' mode, normally I would see a 'beam' cursor when in insert mode and 'block' cursor when not in insert mode. 

This is especially nice and consistent when using it in nvim itself using https://github.com/joshuavial/aider.nvim 

### Version and model info

`aider --version` states aider 0.37.1-dev but I did build it from git

**Comment by unphased** [comment]
I would like to ask for this as well. Have aider possibly check for terminal escape code support for this feature, and then use the line cursor for insert mode and block cursor for normal mode.

**Comment by fuzetsu** [comment]
Looked into this, and it's a pretty easy change so I opened a PR #1589

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by unphased** [comment]
This works, but there is a weird 2 second delay going from insert mode to normal mode. I hit esc and it takes a while before the cursor switches. 

there is no delay entering insert mode, and, also, the cursor changes to block if we hit <esc>l (move cursor right one char) for example.

**Comment by fuzetsu** [comment]
[There is a binding for the `esc` key in aider](https://github.com/fuzetsu/aider/blob/e9353f6d09b53f008a47a74861b1aa8b6371dfdc/aider/io.py#L345), but removing it doesn't really help much with the delay.

The delay is likely an upstream issue, some discussion about the delay here: 
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/192
