### ISSUE TITLE
Analysis of a source file without changing it?

### ISSUE THREAD

**Issue by c19witness** [paul-gauthier/aider#679]
### Issue

Say I wanted to analyze a source file and not have the Aider make a change to it, but just give me the insights from the analysis. 

    "tell me about OWASPs you might see"
    "let me know if this recipe has metric and imperial weights and measures"
    "does this book chapter flow - give me some feedback"
 
Does it, (a) have a mechanism equivalent to `--write-insights-to path/to/someTextFile.txt`
Or should I (b) get it to leave insightful comments in the source - perhaps as comments with # or // in the leftmost position ensuring source still functions the same. Comments I can find later with find-in-files or silversearcher-ag
Or (c) ask it to do a HTTP-POST to some other endpoint to collect the feedback.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You could just say something like "Don't modify my source files, but write me a doc owasp.md that tells me about OWASPs you might see"?

**Comment by paul-gauthier** [comment]
You could also run aider with `--dry-run` to prevent it from actually editing any files.

**Comment by paul-hammant** [comment]
With a tiny bit of creativity, that'll do, yes, sir:

```
#!/bin/bash
base_dir="."
ag --markdown -l "cheesecake" | while read -r file; do
        aider --no-auto-commits --dry-run --message "If a line has imperial and metric measures in it, change the entire line to 'AIDER-INSIGHT: \$FILENAME:\$LINENUM: mixed measures encountered' where FILENAME is the name of this file and LINENUM is the current line number" "$file"
done
```

Then pipe that through grep matching on AIDER-INSIGHT

I now have an AI boosted but waaaay slower version of silversearcher-ag

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by paul-gauthier** [comment]
You may want to look at the scripting docs as well. 

https://aider.chat/docs/scripting.html

**Comment by c19witness** [comment]
Good solution. Thx
