### ISSUE TITLE
Feature: configure the amount of retries and allow continueing retrying

### ISSUE THREAD

**Issue by Nucs** [paul-gauthier/aider#681]
### Issue

I am heavily relying on test-cmd to safely request new changes at it will retry for a few times to successfully add changes to code.
It would be very helpful to be able to change the retrying number from 3 from within the configuration.
Maybe in addition - have a way to continue retry another time after it has stopped/stopping after 3 retries.

It is true that 80% of the cases are fixed within 1-2 retries.

### Version and model info

Latest aider,
GPT-4o

**Comment by paul-gauthier** [comment]
You can just run `/test` again. Or press up-arrow to re-send the last command.
