### ISSUE TITLE
Improve the guidance in the `aider -h` for using an Azure API key with Aider

### ISSUE THREAD

**Issue by DeflateAwning** [paul-gauthier/aider#683]
### Issue

My work has given me an Azure OpenAI API key (only hex characters). How can I use this with Aider? 

For example, what are the valid `OPENAI_API_TYPE` values? Perhaps they could be specified as enum-like choices.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This might be helpful:

https://aider.chat/docs/llms/azure.html

**Comment by DeflateAwning** [comment]
Thanks! That's the docs I was looking for. 

I maintain that it would have been helpful if the `--help` string listed what the valid values for the `OPENAI_API_TYPE` are; it would have given me an indication that Azure is indeed supported.

**Comment by paul-gauthier** [comment]
Glad to hear you got aider working with azure. I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
