### ISSUE TITLE
Autocomplete is sometimes slow on moderately sized (300 files) git repos

### ISSUE THREAD

**Issue by paul-gauthier** [paul-gauthier/aider#684]
### Issue

[From NeverCast in discord](https://discord.com/channels/1131200896827654144/1133060264825208942/1251008387773104268):

> NeverCast: I'm seeing a performance regression when typing /add, only 300 files, sometimes I'll get the file list hints come up, but most the time the terminal just halts

![image](https://github.com/paul-gauthier/aider/assets/69695708/e5d6b2bd-7548-493e-968a-727cf05a2c09)

![image](https://github.com/paul-gauthier/aider/assets/69695708/3e2f06f6-0645-4c07-91fb-fd629c2eca75)

> NeverCast: Add lrucache(1) to get tracked files, and lrucache(1,000) to normalize path seemed to help a lot, I haven't unit tested or end end tested that change, but it's usable now

> NeverCast: Entirely possible though that this breaks the file list entirely, not checked that either

> paulg: I think it's probably dangerous to simply cache these, because aider needs to react when the git repo changes. 
> Purging the caches whever the user types their first character into a new chat input would probably get most benefits. And it's an easy cache eviction policy.

**Comment by paul-gauthier** [comment]
https://discord.com/channels/1131200896827654144/1133060264825208942/1253171725315866668

> Most of my aiderignores start with `*` and then I include the paths I want. Which is probably why ignores is such a hot path for me during tab completion

**Comment by myurko** [comment]
I have some pretty major performance issues with add on larger repos that I work with (10s of k of files). When I've profiled it, the get_tracked_files function seems to be called every character I type, can can take 10s of seconds (most of the time in normalize_path). Can we instead cache the tracked files? Adding files to the aiderignore doesn't help as that is post-normalization.

**Comment by bearjaws** [comment]
I have a legacy codebase with ~22k files in it, even paring it down to ~300 files it still is slow to search files using /add on a M2 MBP. 

It definitely improves using an .aiderignore, as searching the full 22k files just freezes for 20+ seconds.

This is my .aiderignore for anyone else trying to work in a specific directory, this essentially ignores everything and then adds a few specific items back.

```
*

!.gitignore
!README.md
!/src/
!/src/**
```

**Comment by paul-gauthier** [comment]
The main branch handles this much more efficiently now. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by bearjaws** [comment]
Hey @paul-gauthier I tested it out on my large repo with 312 files.

First /add goes to 99% CPU usage on one core for a few seconds. Then searching is instant and works great!

Decided to remove my .aiderignore entirely:

```
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model
claude-3-haiku-20240307
Git repo: .git with 31,687 files
```

Performance still seems good, first /add takes a few seconds (seems the same as 312 files interestingly) but subsequent searches are snappy.

Thank you so much for working on this!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
