### ISSUE TITLE
A comment adder

### ISSUE THREAD

**Issue by Ulladay-Hub** [paul-gauthier/aider#686]
Just to add comments

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I'm not sure I understand your comment. Can you explain more?

**Comment by Ulladay-Hub** [comment]
A function where it can only add comments, no code. Just for if you want to upload it to GitHub, it can be more readable.

**Comment by paul-gauthier** [comment]
Have you tried just asking aider to add comments?

**Comment by Ulladay-Hub** [comment]
Oh....
