### ISSUE TITLE
Bug in `whole` edit format (files created in directory that starts with ###)

### ISSUE THREAD

**Issue by rodion-m** [paul-gauthier/aider#687]
### Issue

1. Ask aider to add a feature using 4 files as a context with edit format `whole`.
2. Got a message from aider (it's exact existing files from the that):
```
Allow creation of new file ### src/Nostradamus.Console/Models/SolutionMap.cs? y
Allow creation of new file ### src/Nostradamus.Console/Models/WorkspaceMap.cs? y
Allow creation of new file ### src/Nostradamus.Console/Indexing/SolutionMapGenerator.cs? y
Allow creation of new file ### src/Nostradamus.Console/Indexing/WorkspaceMapGenerator.cs? y
Applied edit to ### src/Nostradamus.Console/Models/SolutionMap.cs
Applied edit to ### src/Nostradamus.Console/Indexing/WorkspaceMapGenerator.cs
Applied edit to ### src/Nostradamus.Console/Models/WorkspaceMap.cs
Applied edit to ### src/Nostradamus.Console/Indexing/SolutionMapGenerator.cs
```

So, aider used "### src" directory instead of "src/"

### Version and model info

Aider v0.37.0
Models: gpt-4o with diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 96 files
Repo-map: using 10000 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This was with gpt-4o?

Why did you configure 10k tokens worth of repo map? 

How large were the 4 source files?

Did you have other non-default settings enabled?

**Comment by rodion-m** [comment]
Hello! You're right that 10k is too much, especially for GPT-4o. I'll fix it. 

But this error is relevant for Opus too.

**Comment by paul-gauthier** [comment]
You can use an `.aiderignore` file to tell aider to ignore the other parts of your repo.

https://aider.chat/docs/options.html#--aiderignore-aiderignore

You might also find this doc helpful about the odd `###` filenames:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
