### ISSUE TITLE
Feature: explicit no-retries policy

### ISSUE THREAD

**Issue by paul-hammant** [paul-gauthier/aider#688]
### Issue

I'm getting:

```
OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 1.0 seconds.
OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 0.3 seconds.
OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 3.1 seconds.
OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Retry in 5.1 seconds.
...
```
I am not sure, but I think I have to ctrl-c to stop it. I'd prefer a --no-retries option (or something more sophisticated at your discretion) to get my script to stop recursing and allow me to remedy in another way ... like wait for July 1st and run again, he he.

### Version and model info

# aider --version 
aider 0.37.0

gpt4o is the model

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It's always safe to use control-c to interrupt aider if it's doing something undesirable. It will just drop you back to the chat prompt.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by paul-hammant** [comment]
In a for-loop where I'm going through hundreds of files, I should not rely on a non-zero return code, I should parse stdout? to look for such things?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
