### ISSUE TITLE
OpenRouter models are not recognised

### ISSUE THREAD

**Issue by Michal-Mikolas** [paul-gauthier/aider#693]
### Issue

Hello,  
I like to use OpenRouter because of variability and freedom which this platform offers to me.  

However Aider always tells me it doesn't know the models like "Llama 3" or "DeepSeek": 

```
PS C:\Users\mikolas\Projects\aider> aider --model openrouter/deepseek/deepseek-chat --edit-format diff --weak-model openrouter/meta-llama/llama-3-8b-instruct
Model openrouter/deepseek/deepseek-chat: Unknown model, context window size and token costs unavailable.
Did you mean one of these?
- deepseek/deepseek-chat
https://aider.chat/docs/llms/warnings.html
Model openrouter/meta-llama/llama-3-8b-instruct: Unknown model, context window size and token costs unavailable.
Did you mean one of these?
- openrouter/meta-llama/llama-3-8b-instruct:free
- openrouter/meta-llama/llama-3-8b-instruct:extended
https://aider.chat/docs/llms/warnings.html
Aider v0.38.1-dev
Models: openrouter/deepseek/deepseek-chat with diff edit format, weak model openrouter/meta-llama/llama-3-8b-instruct
Git repo: .git with 262 files
Repo-map: disabled
Use /help to see in-chat commands, run with --help to see cmd line args
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>
``` 

![WindowsTerminal_sE7Gknd60i](https://github.com/paul-gauthier/aider/assets/900316/11b3cc25-724e-4cb8-a7ea-275504f6f3bb)

### Version and model info

Aider v0.38.1-dev
Models: openrouter/deepseek/deepseek-chat with diff edit format, weak model openrouter/meta-llama/llama-3-8b-instruct
Git repo: .git with 262 files
Repo-map: disabled

Python 3.12.3
Windows 11 23H2

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The URL provided in the warning has more info:

https://aider.chat/docs/llms/warnings.html

Especially this section:

https://aider.chat/docs/llms/warnings.html#specifying-context-window-size-and-token-costs

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
