### ISSUE TITLE
deepseek via openrouter and repo-map

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#695]
### Issue

Hi,
first of all, thank you very much for your work because what you have done is very helpful in my daily work.

When I run aider: aider --model openrouter/deepseek/deepseek-coder
I receive following information:

Model openrouter/deepseek/deepseek-coder: Unknown model, context window size and token costs unavailable.
and also Repo-map is disabled.

Considering that you rank deepseek coder very highly, I would ask for support for this model via openrouter and enabling repomaps for it.

Without this repomaps, I get javascript code on the default questions even though the project is in spring boot.

### Version and model info

aider version 0.38.0
model: openrouter/deepseek/deepseek-coder

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I just submitted a PR to litellm to add context & cost info to their database for the openrouter version of deepseek coder v2.

https://github.com/BerriAI/litellm/pull/4308

I have not had a chance to test the repomap with coder v2 yet. I will enable it when I'm able to confirm that it's capable of working with a repomap.

**Comment by paul-gauthier** [comment]
I've enabled the repo map for deepseek coder v2 now as well.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by ErykCh** [comment]
Thank you.

That's why I really appreciate the community around all tools using AI on github, the speed of response and openness to adding new functionalities is amazing.
