### ISSUE TITLE
Add RSS feed for blog

### ISSUE THREAD

**Issue by CGamesPlay** [paul-gauthier/aider#699]
### Issue

I'd love to follow updates on the Aider blog, but it doesn't presently generate any RSS feed. If possible, it would be great to have one so I can stay up to date.

**Comment by paul-gauthier** [comment]
Thanks for your interest in the blog. I pasted your issue into aider, and it updated the website to have an rss feed (b03d739).

**Comment by CGamesPlay** [comment]
Great! I tested in my feed reader and it works!
