### ISSUE TITLE
vertex_ai/claude_* models aren't in MODEL_SETTINGS

### ISSUE THREAD

**Issue by spdustin** [paul-gauthier/aider#700]
### Issue

When using e.g. `vertex_ai/claude-3-5-sonnet@20240620`, `aider` falls back to whole-file editing with no repo map.

It seems that the `MODEL_SETTINGS` const in [aider/models.py](https://github.com/paul-gauthier/aider/blob/main/aider/models.py#L35) will never match Vertex AI's Claude because the provider/**model** match expects `claude-3-5-sonnet-2024062` (hyphen before build identifier) rather than `claude-3-5-sonnet@2024062` (at-sign before build identifier)

### Version and model info

> Aider v0.39.0  
> Model: vertex_ai/claude-3-5-sonnet@20240620 with whole edit format  
> Git repo: .git with 23 files  
> Repo-map: disabled

**Comment by spdustin** [comment]
Adding the models directly to the const *mostly* works, but throws errors because `litellm` doesn't have token costs for the weak model `vertex_ai/claude-3-haiku@20240307`

oddly, litellm also says that system messages aren't supported in the same error, which isn't correct.

It's far too late for me to be writing a pair of coordinating PRs now, but I'll try and do that tomorrow. 😄

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I'd be happy to see a PR that adds the vertex versions to MODEL_SETTINGS.

**Comment by krrishdholakia** [comment]
> litellm also says that system messages aren't supported in the same error

hey @spdustin can you share a call for repro?
