### ISSUE TITLE
循环Fix any errors below, if possible.

### ISSUE THREAD

**Issue by 18657769868** [paul-gauthier/aider#707]
### Issue

选择一个文件，输入“分析功能，画出plantuml”
能正确输出plantuml，但会出现："Fix any errors below, if possible."
然后一直循环重复
![image](https://github.com/paul-gauthier/aider/assets/22534813/05df4cbc-2f71-4f81-a031-f6494951ebcb)

### Version and model info

Aider v0.39.0
Model: deepseek/deepseek-coder with whole edit format
Git repo: .git with 101 files
Repo-map: disabled

**Comment by paul-gauthier** [comment]
Sorry, I'm not sure I understand the issue you are reporting?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
