### ISSUE TITLE
Enabling Repomap for AWS Bedrock Claude Sonnet anthropic.claude-3-5-sonnet-20240620-v1:0 

### ISSUE THREAD

**Issue by cmann50** [paul-gauthier/aider#711]
### Issue

Is it possible to enable the repo_map for: model: anthropic.claude-3-5-sonnet-20240620-v1:0 ?

This is the new Anthropic Claude Sonnet 3.5 running on Amazon AWS Bedrock, so I believe aider is using litellm to access it.

### Version and model info

Aider v0.39.0
Model: anthropic.claude-3-5-sonnet-20240620-v1:0 with whole edit format
Git repo: .git with 80 files
Repo-map: disabled
Use /help to see in-chat commands, run with --help to see cmd line args

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This doc may be helpful:

https://aider.chat/docs/llms/warnings.html#adding-settings-for-missing-models

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
