### ISSUE TITLE
Selecting the wrong file to update

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#715]
### Issue

Hi,

I would like to report strange behavior.

I asked Aider to add a connection pool.

He did it correctly, but at the end he still wanted to add the appropriate properties. But it didn't detect the file:
src/main/resources/application.properties
it just deleted the entire contents of the file where the connection pool code was and overwrote them with default values.

I don't know if this can be corrected on Aider's side or if it's a problem with the model. But I think there's something missing in Repo-map. Would it be possible to add an option to write Repo-map to the screen? Because I don't know if I should expand the number of tokens or if he indexed the files incorrectly.

![aider sonnet 3 5 add connection pool 1](https://github.com/paul-gauthier/aider/assets/95491982/ebd876fa-5959-421f-98d3-a946049169d2)
![aider sonnet 3 5 add connection pool 2](https://github.com/paul-gauthier/aider/assets/95491982/33ef12cc-93fe-4119-b759-064957d1a7cd)

Aider v0.39.0
Model: Claude 3.5 Sonnet
Git repo: .gt with 26 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It's always best just to `/add` the files aider needs to edit if you know what they are. Aider will do its best to figure that out, but if you just want to get some work done -- tell it.

**Comment by ErykCh** [comment]
But I didn't expect to correct application.properties. I event didn't know I have to.

Maybe differently, I started using Aider a week ago when I was given a spring boot application to write.

And in my opinion, this is one of the use cases where AI is really useful. I don't know the spring boot libraries, I haven't read any documentation, but I'm writing a complicated application and it works fine.

And now I don't even want to go into how to write correctly in spring boot because Sonnet 3.5 obviously knows it better.

What's missing is a few things that need to be refined (for example, it skips imports) and I think it will be a really good coworker.

**Comment by paul-gauthier** [comment]
This doc may also be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by ErykCh** [comment]
None of this is likely to help.

Somehow I didn't notice that this problem would happen again, and from what I see you made some changes to support Sonnet 3.5. So maybe the problem is solved.
