### ISSUE TITLE
More tokens in repo map when changing the model

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#717]
### Issue

I noticed several times that when changing between different models, the number of tokens in the map rempo increases.

After change from sonnet model:
![image](https://github.com/paul-gauthier/aider/assets/95491982/c3849f0d-d434-4181-b31d-1837f723a20b)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The "using 1024 tokens" is a guideline and not a hard limit. Aider sometimes uses more or less, depending on the situation.

**Comment by ErykCh** [comment]
yes, but the next time I run the application there will be 1024 tokens. The problem is when I change the model. 

Maybe everything is ok. But to be sure, I think it's worth checking what is happening and why this behavior occurs.

**Comment by paul-gauthier** [comment]
Sure thing, happy to answer questions.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
