### ISSUE TITLE
What is the graph ranking algorithm?

### ISSUE THREAD

**Issue by ramsey-coding** [paul-gauthier/aider#719]
### Issue

In the following article it is mention that aider uses a graph ranking algorithm.

https://aider.chat/2023/10/22/repomap.html

How that ranking algorithm works? Can you provide some insight?

**Comment by paul-gauthier** [comment]
I haven't had a chance to write it up. You can look in `repomap.py` to study the code.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
