### ISSUE TITLE
gpt4 is not generally available to new users

### ISSUE THREAD

**Issue by alexanderkjeldaas** [paul-gauthier/aider#72]
gpt4 is only available to "all existing API developers with a history of successful payments".  i.e. before the first billing cycle, new users will not be able to use gpt4.

I see that commit cdf8f9a4b2b4a65993227ac5af1eaf3f1b85c9d8 works well with gpt3.5-turbo-16k, but later commits stop working.

**Comment by paul-gauthier** [comment]
Thanks for filing this issue. The latest release v0.8.2 and main branch of github should be working correctly again. There was a period where aider assumed everyone had access to gpt-4, but that was resolved this morning.

See #71 for more details.

Let me know if you're still having any problems after upgrading. Or you can work around the bug with by running aider with `--model gpt-3.5-turbo-16k` to explicitly select a 3.5 model.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but please feel free to re-open if you have further problems.

**Comment by alexanderkjeldaas** [comment]
latest main does not wokr, no.  `--model gpt-3.5-turbo-16k` selects the gpt-3.5 turbo model, but the diff detection is broken.

**Comment by alexanderkjeldaas** [comment]
latest main does not work, no. --model gpt-3.5-turbo-16k selects the gpt-3.5 turbo model, but the diff detection is broken.

**Comment by alexanderkjeldaas** [comment]
latest, not working

https://asciinema.org/a/WhosqpVZAZtk9PFFQbW92fw3v

commit https://github.com/paul-gauthier/aider/commit/cdf8f9a4b2b4a65993227ac5af1eaf3f1b85c9d8 works

https://asciinema.org/a/lRM3pT49q99Od6Ft1ZpMunZQ0
