### ISSUE TITLE
Overzealous SQL linting

### ISSUE THREAD

**Issue by liffiton** [paul-gauthier/aider#720]
### Issue

The linter is consistently marking various lines in SQL edits as incorrect when they are not.  I've seen it mark lots of primary key column defs, some `PRAGMA` statements, and at least one non-primary-key column def.  The spurious issues aren't the end of the world, but they add friction.

Just to see, I let Sonnet-3.5 try to fix one such issue, and it agreed there's no issue:

```
# Fix any errors below, if possible.


## See relevant line below marked with █.

src/gened/migrations/20240608--add_experiment_tables.sql:
...⋮...
  6│
  7│-- Create experiments table
  8│CREATE TABLE experiments (
  9█    id          INTEGER PRIMARY KEY AUTOINCREMENT,
 10│    name        TEXT NOT NULL UNIQUE,
 11│    description TEXT
 12│);
 13│
...⋮...


Attempt to fix lint errors? y
I apologize for the confusion. The migration script you've shown is actually correct
and doesn't contain any errors. The line marked with █ is perfectly valid SQL for
creating a table with an auto-incrementing primary key. There's no need to make any
changes to this file.

If you'd like me to make any specific modifications or if you have any other concerns
about the migration script, please let me know, and I'll be happy to assist you further.
```

This is a script for SQLite in particular, if it matters.  Possibly it's an issue of SQL dialects.

### Version and model info

Aider v0.40.0
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model claude-3-haiku-20240307

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I can look into this and try and determine why the sql linter is triggering these spurious issues.

If the sql linting is problematic for you, you could to `--lint-cmd sql:echo` to disable it.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
