### ISSUE TITLE
Enhancement: add current date to the prompt

### ISSUE THREAD

**Issue by liffiton** [paul-gauthier/aider#722]
This is tiny, but it *may* be worth a few tokens in the prompt:  When creating a new file that the LLM probably could infer should be named using today's date, it chose June 06, 2024 (possibly because that is one day after the date in the most recent filename it can see).  I'm guessing it would be correct if the current date were placed in the prompt somewhere.

I imagine this could also be useful for edits like date/time-stamped comments, file creation dates in comments, etc.

**Comment by paul-gauthier** [comment]
This was implemented a few weeks ago.

```
Keep this info about the user's system in mind:
- The user's system: macOS-14.5-x86_64-i386-64bit
- The user's shell: SHELL=/usr/local/Cellar/bash/5.2.26/bin/bash
- The current date/time: 2024-08-02T15:51:55.574841
```

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
