### ISSUE TITLE
Why do we importing litellm from `aider.litellm`

### ISSUE THREAD

**Issue by ramsey-coding** [paul-gauthier/aider#725]
### Issue

I see `https://github.com/paul-gauthier/aider/blob/965c35870cb85c56898c341e6dd46c39e77dcfbe/aider/models.py`

and the `self.info = litellm.get_model_info(model)`

Is it correct?

should not we use the import from `litellm`?

**Comment by paul-gauthier** [comment]
The aider.litellm ensures that litellmm is loaded with the proper configuation.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
