### ISSUE TITLE
how to evaluate aider on swe_bench lite dataset?

### ISSUE THREAD

**Issue by ramsey-coding** [paul-gauthier/aider#726]
### Issue

how can I evaluate aider on swe_bench lite dataset?

Are there documents for replication step?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://github.com/paul-gauthier/aider-swe-bench

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
