### ISSUE TITLE
Adding information about versions of main libraries to repomaps

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#727]
### Issue

Hi,

the code may be different depending on the libraries we use. Is Java version 1.8 or 21. Is SpringBoot 2.x or 3.x. Is Python 3.6 or 3.12.

In my opinion, information from pom.xml about the versions of the most important libraries should be added to the repo map.

If this can't be done automatically, it should be possible to add a user section with this information.

For example, the .aider.system_message file in the project directory, where the user will be able to provide additional informations about the project. Because I wouldn't like to state in every query that I'm using SpringBoot version 3.3. Because I also clean the chat history very often so that it does not contain dozens of items.

![image](https://github.com/paul-gauthier/aider/assets/95491982/16e828ee-7a18-4ab4-b695-5450733fa5e3)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/conventions.html

**Comment by ErykCh** [comment]
Thanks,
