### ISSUE TITLE
Shouldn't ask to add not existing files to the chat

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#728]
### Issue

Hi,

if it knows that new files must be created than it shouldn't ask to add them to the chat:

![image](https://github.com/paul-gauthier/aider/assets/95491982/78a1e49c-e8b5-4397-9e70-d32633a0f942)

### Version and model info

Aider: 0.40.0
Model: Claude Sonnet 3.5

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by ErykCh** [comment]
I would expect Aider to ask to include these files:

 Add these files to the chat?

and if I have the --yes option enabled, it will even do it automatically.

**Comment by paul-gauthier** [comment]
Are those files part of your git repo? If you do `git ls-files` do they show up?

**Comment by ErykCh** [comment]
No.

another example from a moment ago

![image](https://github.com/paul-gauthier/aider/assets/95491982/782d3e86-88ab-490f-a9fb-9857ef606aa3)

I thought that /add creates a file if it doesn't exist.

But for me something is missing here.

There is a text: I'll wait for your approval to proceed
But there is no any place to put y

but I must admit that he made the format method very nicely because extracted all the data from the Document class, which is not part of the code because it is from the Spring AI package

But this is a completely different story, how to make sure that if something changes in the public library, he will know about it. For example, a new field will be added to the Document class, how will it know about its existence? Do you expect it will be possible to add code from outside the project repository to the repomap?


Aider v0.40.7-dev
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/anthropic/claude-3-haiku
Git repo: .git with 35 files
Repo-map: using 2028 tokens

**Comment by paul-gauthier** [comment]
Aider only works with the code in your repo. It can't see code outside the repo.

**Comment by ErykCh** [comment]
Ok, I understand this.

but what about the problem that the user must accept adding a file but the question about adding a file does not appear?

**Comment by paul-gauthier** [comment]
That was just the LLM talking to you, not aider itself. I think the LLM was a bit confused about the exact way aider works.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
