### ISSUE TITLE
stop messing with commit author

### ISSUE THREAD

**Issue by bitdeep** [paul-gauthier/aider#730]
### Issue

![image](https://github.com/paul-gauthier/aider/assets/19378023/cd0f8a74-6ae8-4438-815e-fac63facfdbb)
Please, don't, just add a flag for anyone to use this.
Why you guys keep forcing this into us?

### Version and model info

Aider v0.40.0
Models: openrouter/anthropic/claude-3.5-sonnet with whole edit format, weak model openrouter/anthropic/claude-3-haiku-20240307
Git repo: .git with 2 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This doc may be helpful:

https://aider.chat/docs/git.html#commit-attribution

**Comment by ethomas2** [comment]
@bitdeep would this suggestion be preferable? https://github.com/paul-gauthier/aider/issues/737

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
