### ISSUE TITLE
Error to set model to openrouter/meta-llama/llama-3-8b-instruct:free 

### ISSUE THREAD

**Issue by yxd0018** [paul-gauthier/aider#731]
### Issue

$ aider --model openrouter/meta-llama/llama-3-8b-instruct:free
Traceback (most recent call last):
  File "/home/abc/.local/bin/aider", line 8, in <module>
    sys.exit(main())
  File "/home/abc/.local/lib/python3.10/site-packages/aider/main.py", line 406, in main
    main_model = models.Model(args.model, weak_model=args.weak_model)
  File "/home/abc/.local/lib/python3.10/site-packages/aider/models.py", line 331, in __init__
    if self.info.get("max_input_tokens", 0) < 32 * 1024:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

It's fine to connect similar model without the word "free" in the model

### Version and model info

v0.40.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can ignore the warning. See the link in the output which explains this.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
