### ISSUE TITLE
Build instructions are unclear

### ISSUE THREAD

**Issue by cognivore** [paul-gauthier/aider#732]
### Issue

`pip install` installs a version that complaints about it being old; `pip upgrade` doesn't upgrade the version as suggested. Furthermore, in a little bit, the version installed with `pip` breaks.

Best case scenario for everyone would be to package `aider-chat` as a `python3Package` in NixOS; second best case scenario would be to provide a clear instruction about how to build the program locally and link the resulting artefact into `.local/bin`.

If there is a will to package it for Nix, I am ready to work on it (it will require packaging grep-ast into python3Packages too). Otherwise, it would be cute to get the community to come up with documentation about local installs.

**Comment by cognivore** [comment]
https://github.com/gebeer/flake-aider-chat

In the meantime, this ad-hoc solution seems to work for me.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Can you share the output that makes you think pip install is installing an old version? Please include all the announce lines that print when aider starts.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
