### ISSUE TITLE
Relation between Def and ref in repo map, may be wrong because mapping by function or method name 

### ISSUE THREAD

**Issue by zbflcy** [paul-gauthier/aider#735]
for example, i have some method with the same name in different files, there are not only one definers?

```python 
 for ident in idents:
            definers = defines[ident]
            if ident in mentioned_idents:
                mul = 10
            else:
                mul = 1
            for referencer, num_refs in Counter(references[ident]).items():
                for definer in definers:
                    # if referencer == definer:
                    #    continue
                    G.add_edge(referencer, definer, weight=mul * num_refs, ident=ident)
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider uses heuristics to match defs and refs, and it's ok if they are not perfect. It will consider all the possible definers as defs.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
