### ISSUE TITLE
Add config option to prefix commit messages with Aider

### ISSUE THREAD

**Issue by ethomas2** [paul-gauthier/aider#737]
### Issue

First of all fantastic tool! I've been using it for 2 days and i'm already in love!

By default right now aider writes `<Your Name> (aider)` as the commit author for any commits it makes. Instead of (or in addition to) this i'd prefer if it wrote `Aider:` into the commit message. E.g.

```git
commit 4eb896bcf75ec7ea8c23c4c28553f5f888d37174
Author: Evan Thomas <evanrthom@gmail.com>
Date:   Wed Jun 26 18:35:09 2024 -0700

    Aider: <some commit message>
```

I prefer this because my workflow with aider involves a lot of git diffing and commit squashing. 
1. I ask aider to do something 
2. Review the changes by doing a `git difftool` of all recent commits 
3. Optionally make some small changes myself and go back to step 2
4. Either "accept the changes" by squashing them all and marking the author as me, or "reject" by resetting hard to the last non-aider commit

In order to do this it's useful to be able to see at a glance which commits are Aider's and which commits are mine. I find it much easier to distinguish between Aider's commits and mine if `Aider: ` is in the commit message than if it's in the author field.

Furthermore, when I squash it's convenient for me to change the commit message body in the process of doing an interactive rebase.  It's much less convenient for me to change the author, as that involves executing another git command after the squash. By carelessness I end up with a lot of commits with  `Author: Evan Thomas (aider)` even after step 4, and then it's hard to tell which commit's i've "Accepted" vs "Rejected". This mistake would be much harder to make if `Aider: ` was in the body

If you agree with the philosophy of this change i'm happy to try my hand at putting up a pr. Thanks again for the fantastic tool!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I've added a `--attribute-commit-message` switch that will do this. See the docs for more info:

https://aider.chat/docs/git.html#commit-attribution

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by wbazant** [comment]
I tried it and liked it a lot, thanks for implementing the feature! I think aider should also attribute itself in commit messages as a committer.

I'm not sure if I'm pointing out something obvious, so, here's my commit log from the last few hours - I occasionally commit with the name x, then aider sometimes commits my code, and sometimes aider authors and commits.

```
Sun Jun 30 00:03:54 2024 +0100 x
Sat Jun 29 23:56:30 2024 +0100 aider: Refactored the ConnectLocation component to use the isEditing prop and the useRouteMatch hook to determine the editing state.
Sat Jun 29 23:56:29 2024 +0100 Removed the `reviewRouteMatch` logic and updated the `useEffect` hook accordingly.
Sat Jun 29 23:30:53 2024 +0100 aider: Implemented location editing functionality and added isEditing state to the Redux store.
Sat Jun 29 23:28:26 2024 +0100 Improved the handling of location editing by using the current position instead of the previous location being edited.
Sat Jun 29 22:54:42 2024 +0100 x
Sat Jun 29 22:25:40 2024 +0100 aider: Implemented loading indicator and position field display in the LocationForm component.
Sat Jun 29 22:17:38 2024 +0100 Starting to integrate draggable marker and edit-location
Sat Jun 29 21:52:29 2024 +0100 WIP edit location - original attempt

```
I wrote the bottom two commits yesterday, and want this to eventually look like:
```
{ squash the whole section above once I'm done }
Sat Jun 29 22:17:38 2024 +0100 Starting to integrate draggable marker and edit-location
Sat Jun 29 21:52:29 2024 +0100 WIP edit location - original attempt
```


The aider-made commit messages that don't start with aider confused me for a second when I saw the log - I think they should be attributed to aider too, maybe in a `aider (committed): <ai summary>` format.

**Comment by ethomas2** [comment]
This worked for me. Thanks!
