### ISSUE TITLE
Is it possible to call aider within Python code as a library? 

### ISSUE THREAD

**Issue by hhn12138** [paul-gauthier/aider#738]
### Issue

This is a really impressive project, and if it could be directly called within Python code, its range of applications would be greatly expanded.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/scripting.html

**Comment by hhn12138** [comment]
> Thanks for trying aider and filing this issue. This doc may be helpful:
> 
> https://aider.chat/docs/scripting.html
Thank you very much！

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
