### ISSUE TITLE
Test Command does not support arguments on Windows.

### ISSUE THREAD

**Issue by nevercast** [paul-gauthier/aider#741]
Using PowerShell inside VSCode on Windows 11 with Python 3.10 and Aider 0.40.5.

`aider --test-cmd "npm run check" --test` gives 

```
Aider v0.40.5
...
'"npm run check"' is not recognized as an internal or external command, operable program or batch file 
```

Presumably you're calling out to shell (cmd, Windows) to execute the command, seems the quoting isn't working as I would expect. 

I get the same output if I single or double quote, so it's not PowerShell that I'm calling aider from at fault, but instead how the execution is being constructed I suspect

Expected output would be that aider properly handles invoking a command with arguments on Windows.

I would expect this to work for lint-cmd too, I have not tested it.

I also have not tested using the config file, only command line invocation.

I have not checked the source code, but may do so in the coming days.

**Comment by user753** [comment]
Quick fix is to change args to args[0] in 
https://github.com/paul-gauthier/aider/blob/7a3b0d6ddb86f9321ea59d9d57de82163e027e61/aider/commands.py#L544

**Comment by paul-gauthier** [comment]
I think I've fix this. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by nevercast** [comment]
For completeness, I have tested this and it is fixed. Thank you!
