### ISSUE TITLE
Suggestion: Use gh to access issues on private repos

### ISSUE THREAD

**Issue by raymondclowe** [paul-gauthier/aider#742]
### Issue

aider works great to fix my issues, but currently it can't see the issues in my private repos without cutting and pasting the content.  Could it use `gh issue list` and `view` to look at issues?  Or can it already to this and I'm not understanding?

### Version and model info

aider 0.40.6

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You should be able to do `/run gh issue view XXX` to share issues from private repos in the chat.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
