### ISSUE TITLE
Feature: allow user prompt in commit message instead of commit summary

### ISSUE THREAD

**Issue by wbazant** [paul-gauthier/aider#748]
I'm experimenting with programming just by telling the AI what to change. When I use aider iteratively in this way and it doesn't quite work, I might end up making lots of commits. To see where I got to so far, I typically prepare a command like `git diff <last good commit> HEAD` and ask for changes based on what bit of code to move where, or describing what the result misses, etc., and then I squash them all.

Here's a sample of what that might look like:
```
Removed unnecessary code for calculating drag offset and simplified the drag event handling.
Improved the map marker dragging functionality by using the Google Maps API's projection methods to accurately calculate the new marker position during drag events.
Implemented drag and drop functionality for the map marker, updating its position based on the user's drag actions.
Added support for dragging the new location map pin.
Added draggable functionality to the new location map pin component.
Implemented draggable map pin functionality with updated position state and event handlers.
Removed unnecessary `onChange` event handler from `DraggableNewLocationMapPin` component and updated the `Map` component to use the `onDragEnd` event instead.
Added drag offset functionality to the DraggableNewLocationMapPin component.
Reordered the imports and exported components in the Pins.js file.
Implemented draggable new location map pin with geocoding and map dragging control.
Implemented geolocation functionality and updated map position in the Redux store.
Implemented draggable new location map pin and updated position in Redux state.
```
These are mostly not related of what I was trying to do, it looks like the model just looks at the diff and guesses what the change was about. For successful changes it's great - `Reordered the imports and exported components in the Pins.js file.` is really what I remember asking - and for the other ones, I'm pretty sure I told it to make adjustments and technical changes, nothing like adding support for that whole feature.

I would find the tool more useful for this workflow if my own prompts were there instead. It would also be a tiny monetary saving.

An idea off the back of this feature request is to include the request made by the user in the summarization prompt - I'm guessing it's currently not there.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You're right the summary prompt should have been including the chat messages, but was not. It was a bug. Fixed.

Aider used to include the chat messages in the body of the commit message, but many users did not want that. 

I think you want something different though? For the commit message to be solely made up of the chat messages without a one-line summary at the start?

**Comment by wbazant** [comment]
I remember the commit messages had replies from the chatbot in a diff format, making them very long and hard to read. I don't mean that, I mean my prompt to aider - the message I typed after adding files and before getting the code change back.

It's not as good as an AI summary for presenting to others, but it is a short description of what aider has set out to do that the user will understand, since they wrote it.

When I change code with software tools - something like a rename across the project - I will often include the command that makes a change, for example `find src -type f | xargs perl -i -pe 's/oldName/newName/` . By analogy, a more elaborate version would be to produce a command which reproduces the change - prompt, model version, files included, etc. but I don't know how useful that is. Meanwhile, switching off the AI summary requires something to be put in the commit message, and user's own prompt is perfect for that.

**Comment by wbazant** [comment]
I might be misunderstanding what the model gets when I ask for a few different things in order within a chat session. I used it as if the context of my requests was just the files I added, but I just asked it to 'review previous commit and do more of the same' and it understood me, so presumably it gets all the previous messages - I should probably be killing the aider session and restarting it a lot more, to save up on tokens!

**Comment by wbazant** [comment]
Actually, I'm not sure if the feature is of a general interest, it's more for me to figure out how I like programming with LLMs. Thanks for replying, and I'm glad you found something to fix off the back off this! I'm gonna close this and I've made myself a wrapper:

```
#!/usr/bin/env python
import sys
import subprocess

def main():
    # Capture the -m argument and the message
    args = sys.argv[1:]
    if '-m' not in args:
        print("Error: -m argument is required.")
        sys.exit(1)

    m_index = args.index('-m')
    if m_index + 1 >= len(args):
        print("Error: No message provided for the -m argument.")
        sys.exit(1)

    commit_message = args[m_index + 1]

    # Call the aider command with the original arguments
    aider_command = ['aider', '--sonnet', '--no-gitignore', '--no-attribute-author', '--no-attribute-committer', '--attribute-commit-message'] + args
    subprocess.run(aider_command)

    # Amend the commit message with the provided message
    subprocess.run(['git', 'commit', '--amend', '-m', "Aider prompt: " + commit_message])

if __name__ == "__main__":
    main()
```
