### ISSUE TITLE
Setting API Key not working

### ISSUE THREAD

**Issue by PierrunoYT** [paul-gauthier/aider#750]
### Issue

In the docs there is written you need to use setx to set the OpenRouter API Key but actually you should use set without the x. Also not sure if you need to use export or set.

### Version and model info

-

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Sorry, I do not understand what you are asking?

**Comment by PierrunoYT** [comment]
> Thanks for trying aider and filing this issue. Sorry, I do not understand what you are asking?

I mean in the docs there it says you need to use setx to set the API Key on Windows but instead you should use set not setx. The command export is also written somewhere but not sure what's the difference betweeen set and export on Windows

**Comment by paul-gauthier** [comment]
It all depends on which OS and shell you are using. Unfortunately the docs can't cover every possible way to set environment variables.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
