### ISSUE TITLE
Sonnet support for images

### ISSUE THREAD

**Issue by david-strejc** [paul-gauthier/aider#751]
### Issue

Will sonnet support images? Also it would be great to be able through some mechanism to quickly add images. My idea is my Flameshot automatically ads screen to /add image command. Is there any interface how to do that in python?

**Comment by PierrunoYT** [comment]
Also make sure it works with OpenRouter too

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This looks like a duplicate of #556, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.

**Comment by yamitzky** [comment]
#556  is related, but I think it's a separate issue.

openrouter/openai/gpt-4 is not listed in models.py, so comprehensive configurations need to be written or a special process for openrouter should be added.

I created Sonnet support itself as a Pull Request, so please check it!

**Comment by paul-gauthier** [comment]
I merged it. Thanks!
