### ISSUE TITLE
--attibute-commit-message should also attribute aider where aider only committed the change

### ISSUE THREAD

**Issue by wbazant** [paul-gauthier/aider#753]
see: https://github.com/paul-gauthier/aider/issues/737#issuecomment-2198370954 . Making a new issue since the other one got closed.

**Comment by paul-gauthier** [comment]
It should be doing that in the committer name.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
