### ISSUE TITLE
What shell is best to work with Aider?

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#755]
### Issue

The /add method works very slowly for me, listing and filtering work very slowly.

I work on a computer with a fast processor and I have 64 gigs of RAM and an SSD drive. So I guess the problem is in the shell?

### Version and model info

Aider v0.40.7-dev
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/anthropic/claude-3-haiku
Git repo: .git with 36 files
Repo-map: using 2028 tokens

**Comment by paul-gauthier** [comment]
Aider should work quickly in a repo with only 36 files. It is known to be a bit slow on large repos with hundreds of files or more.

**Comment by ErykCh** [comment]
I started running it from zsh shell and it seems to be a bit faster

simple test

/add and just type spacebar and how many seconds does it take for the cursor to move, for me it takes 3

/add and a random string of characters on the keyboard, it takes about 3 seconds to print something

co powoduje, że jak wpiszę niewłaściwą nazwę klasy to czekam 3 sekundy aż mogę wybrać backspace

**Comment by paul-gauthier** [comment]
I just made a change which improved this significantly. 


The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by ErykCh** [comment]
Yes, it works much better.
Now there is about a 3 second delay but only the first time you use /add. So what could be improved is to load all the information asynchronously after startup to make the first use of /add faster.

But not to be too beautiful :-( I again encountered the same problem described below.

Previously I thought it might have something to do with my environment. But apparently it's on Aider's side. It can loop endlessly.

I don't have a deterministic description of how to trigger this. I just write the correct version of the class and then after typing when it stops finding matching ones, than I click backspace and want to write the next characters again and then Aider gets stuck. It gets into an infinite loop. Ctrl+C breaks this loop and you can continue typing.

Here it crashed on Cha and after selecting Ctrl+C it added the Cha file to the main directory.

![image](https://github.com/paul-gauthier/aider/assets/95491982/2c560503-1848-4fb3-8f57-a296742c72ae)

This stuck also happened to me several times on earlier versions. Now I have the version: v0.42.1-dev

**Comment by paul-gauthier** [comment]
Please let me know if you are able to describe how to reproduce the problem you're describing.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
