### ISSUE TITLE
/drop dumps files that were added when Aider was launched

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#756]
### Issue

According to https://aider.chat/docs/conventions.html

I add the .aider.memory.md file with a description of what libraries are to be used and in which versions

however, this file is removed by the /drop command

it should be possible to add files rigidly, so that /drop doesn't throw them away

### Version and model info

Aider v0.40.7-dev
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/anthropic/claude-3-haiku
Git repo: .git with 36 files
Repo-map: using 2028 tokens
Added .aider.memory.md to the chat.

**Comment by ErykCh** [comment]
Since Aider codes itself, I think this requirement is quite simple to implement.

For example, setting -permanent before the filename.

So the following call:

aider -permanent .aider.memory.md

Causes /drop <without filenames> to not drop this file.

Aider, can you make a quick fix with this functionality?

**Comment by paul-gauthier** [comment]
The `/drop` command is currently working as intended. That said, sounds like you want the feature being tracked in #660.
