### ISSUE TITLE
Feature: Configure RPM for specific models

### ISSUE THREAD

**Issue by usmanovbf** [paul-gauthier/aider#764]
### Issue

Hi! First of all, thank you for such unique tool.
I wonder, is it possible to set request per minute amount? For example, if I use free version of Gemini, it allows 2 RPM https://ai.google.dev/pricing . So, I am getting the error now.
```
Unexpected error: litellm.RateLimitError: litellm.RateLimitError: VertexAIException - b'[{\n  "error": {\n    "code": 429,\n    "message": "Resource
has been exhausted (e.g. check quota).",\n    "status": "RESOURCE_EXHAUSTED"\n  }\n}\n]'
```

Since aider uses litellm, it will be greate to pass litellm settings from some YAML file and use rpm attribute, for example, like this https://litellm.vercel.app/docs/proxy/reliability#step-1---set-deployments-on-config

Please, make an attention to this, since it will help to bring more delicate fine tuning.

Thank you!.

### Version and model info

Aider v0.40.6
Model: gemini/gemini-1.5-pro-latest with diff-fenced edit format
Git repo: .git with 6 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider should have retried that error a bunch of times before finally giving up?

Aider doesn't use the litellm proxy, just the python library. And I don't know what the proxy would do if the client exceeds the rate limit? Probably just return a rate limit error just like google is?

**Comment by usmanovbf** [comment]
> Aider should have retried that error a bunch of times before finally giving up?

Unfortunately, it stucks with the error
```
Unexpected error: litellm.RateLimitError: litellm.RateLimitError: VertexAIException - b'{\n  "error": {\n    "code": 429,\n    "message": "Resource has been exhausted (e.g. check quota).",\n    "status":
"RESOURCE_EXHAUSTED"\n  }\n}\n'

```

and I need to press Ctrl+C two times and re-run aider.


Perhaps, moving to litellm or just adding retry mechanism after certain point of time would help it.

> And I don't know what the proxy would do if the client exceeds the rate limit?

It should just wait for some time to make the request again based on the RPM from the specific model quota and just using exponential backoff.

> Probably just return a rate limit error just like google is?

It obligates to re-run aider manually again and again and it's not suitable. Better to have auto-retry based on the allowed RPM for the model or just based on the exponential backoff.

**Comment by paul-gauthier** [comment]
Aider does retry litellm.RateLimitError. If all the retries fail, only then does it report the error to the user.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
