### ISSUE TITLE
/web url appears to work and adds nothing to the context

### ISSUE THREAD

**Issue by fferreres** [paul-gauthier/aider#765]
### Issue

I have yet do add files, and aider loads normally, adds itself to .gitignore, detects the .git folder, .env. I followed the suggestion to install chomium headless exactly as indicated, and it seems to work. i had to add certificates (Mac specific step). 
Upon calling web with a url, the LLM returns a message about what to SEARCH/REPLACE. I asked to share the prompt, and I think the LLM is not getting any content from the /web command, neither is anything displayed in the command line screen. I tried a few urls.

### Version and model info

Latest

**Comment by fferreres** [comment]
I fixed itself used aider itself. I put the issue, and it decided to add other features (which not sure are the intended thing or not) but it decided to better parse things, focus on the main content, remove javascript, convert it to markdown for better understanding by the LLM, then paste the head (first few lines) in the command window and and ask if one would like to add that to the context, as opposed to just doing it without asking.

![image](https://github.com/paul-gauthier/aider/assets/20901550/a4c55566-6422-43e7-a4cb-b79e5c70d5a3)

I this real or will this dream drift to some kind of nightmare singularity event?

**Comment by paul-gauthier** [comment]
Very nice. Aider has written 7% of itself.

https://aider.chat/2024/05/24/self-assembly.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
