### ISSUE TITLE
Aider just does random changes and commits them

### ISSUE THREAD

**Issue by znat** [paul-gauthier/aider#768]
### Issue

Just installed. Added a file. Aider does random refactors (factorial and commits them)

### Version and model info

Aider latest, model: gpt-4o

**Comment by dannylank** [comment]
It depends a lot on the model you use, I particularly like Claude2 more, it is more coherent when following instructions, for development it considers that he has better control of the changes, although it still makes mistakes, with openai I always say when starting not to make changes, only those that I tell you and try not to change the code if it is not necessary
