### ISSUE TITLE
'NoneType' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by ackoi** [paul-gauthier/aider#769]
### Issue

Aider was working fine until the last update.

I'm now getting this in a loop when doing a simple index.html and styles.css edit.

It even saved the file as binary instead of the code it outputs for some reason.

Anyone else getting similar issues?

**Comment by paul-gauthier** [comment]
When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```
