### ISSUE TITLE
Highlighting breaks for unclear reasons

### ISSUE THREAD

**Issue by mikehearn** [paul-gauthier/aider#773]
### Issue

It was working and then, suddenly, it wasn't. But aider can still extract patches and do the work - it's just not highlight output properly, on neither the web nor console versions. Maybe it's related to the files I added to the chat? Restarting doesn't help.

<img width="1953" alt="image" src="https://github.com/paul-gauthier/aider/assets/971089/e9fffbc4-44b4-4706-b8d6-b7e7354303cb">

<img width="889" alt="image" src="https://github.com/paul-gauthier/aider/assets/971089/0409d3c4-3a0e-46c4-9610-af16c2b46c9d">

### Version and model info

Aider v0.41.0
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 2,041 files

**Comment by paul-gauthier** [comment]
Ya, this can happen if the file you are editing contains triple-backticks. Aider has to switch to another fencing mechanism, which won't render pretty in the chat.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
