### ISSUE TITLE
Feature: Proxy Support for aider

### ISSUE THREAD

**Issue by usmanovbf** [paul-gauthier/aider#774]
### Issue

**Summary:**

This feature request proposes adding support for using proxies with Aider, the AI pair programming tool.

**Motivation:**

Currently, Aider directly connects to LLM APIs, which can be problematic in certain scenarios:

* **Network Restrictions:** Users behind firewalls or in environments with restricted internet access may be unable to directly connect to LLM APIs.
* **Privacy Concerns:** Some users may prefer routing their requests through a proxy for added privacy.

**Proposed Solution:**

Implement a configuration option within Aider to specify a proxy server address and port. Aider would then route all API requests through this proxy.

**Implementation Details:**

* **Configuration:**

Add a new section to the Aider configuration file  for proxy settings. This section could include fields for:

    * `proxy_host`: The hostname or IP address of the proxy server.
    * `proxy_port`: The port number of the proxy server.
    * `proxy_type`: (Optional) The type of proxy (e.g., HTTP, SOCKS5).
    *  `credentials`: dict to store creds

**Benefits:**

* **Increased Accessibility:** Enables Aider to be used in environments with network restrictions.
* **Enhanced Privacy:** Provides an additional layer of privacy for users concerned about data exposure.
* **Improved Reliability:** Proxies can help mitigate issues caused by network instability or rate limiting.

**Additional Considerations:**

* **Proxy Authentication:** Consider supporting proxy authentication mechanisms (e.g., username/password, API keys) for enhanced security.
* **Proxy Selection:** Allow users to choose from a list of pre-configured proxies or specify custom proxy settings and apply round robin algorithm

By implementing proxy support, Aider can become more versatile and accessible to a wider range of users.

### Version and model info

Aider v0.41.0
Model: gemini/gemini-1.5-pro-latest with diff-fenced edit format
Git repo: .git with 16 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider uses litellm to connect to LLM APIs, and it supports setting a base url for most providers. 

Which provider do you want to proxy to?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by Tuinslak** [comment]
This actually seems to work when using `ALL_PROXY`. In my case, it's a socks5 proxy. 

Without proxy:

```
litellm.APIError: APIError: OpenrouterException - [Errno 8] nodename nor servname provided, or not known
Retrying in 0.2 seconds...
  litellm.APIError: APIError: OpenrouterException - [Errno 8] nodename nor servname provided, or not known
Retrying in 0.5 seconds...
 litellm.APIError: APIError: OpenrouterException - [Errno 8] nodename nor servname provided, or not known
Retrying in 1.0 seconds...
 ░litellm.APIError: APIError: OpenrouterException - [Errno 8] nodename nor servname provided, or not known
Retrying in 2.0 seconds...
```

With proxy:

```
$ export ALL_PROXY="socks5h://127.0.0.1:9999"
$ aider 
[...]
► THINKING

Modifying HTML and CSS...
[...]
```
