### ISSUE TITLE
Feature: Add web-scraping instead of using LLMs API only

### ISSUE THREAD

**Issue by usmanovbf** [paul-gauthier/aider#776]
### Issue

Because web-based LLMs provide more quotas then via APIs, like Chatgpt, Gemini, etc. And they are cheaper in this way.

### Version and model info

Aider v0.40.6
Model: gemini/gemini-1.5-pro-latest with diff-fenced edit format
Git repo: .git with 6 files
Repo-map: using 1024 tokens

**Comment by maledorak** [comment]
This idea stands against the [Terms of Use of OpenAI](https://openai.com/policies/terms-of-use/)

```
What you cannot do. You may not use our Services for any illegal, harmful, or abusive activity. For example, you are prohibited from:

...

Automatically or programmatically extracting data or Output (defined below).
```

And for sure, every web-based LLM has similar Policies.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, this is out of scope for aider as it typically violates terms of use.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
