### ISSUE TITLE
Citation for the Unified Diff Page

### ISSUE THREAD

**Issue by LukvonStrom** [paul-gauthier/aider#778]
### Issue

As a researcher, I would like to be able to cite at least the following page, if not others: website/docs/unified-diffs.md

Maybe it would even be a good idea to submit a paper with the content of this page to arxiv?

### Version and model info

Applies to the entire website in the repo.

**Comment by paul-gauthier** [comment]
Thanks for your interest in aider. I don't think I'll have the time to turn that article into an actual paper. It might be best to just cite it as a URL?

**Comment by LukvonStrom** [comment]
Unfortunately its missing a proper author and date attribution for that though :(On 3. Jul 2024, at 21:00, paul-gauthier ***@***.***> wrote:﻿
Thanks for your interest in aider. I don't think I'll have the time to turn that article into an actual paper. It might be best to just cite it as a URL?

**Comment by paul-gauthier** [comment]
The version that appears on the blog is dated. I'm the author. Happy to add my actual name to it if that helps you?

https://aider.chat/2023/12/21/unified-diffs.html

**Comment by LukvonStrom** [comment]
Yes that would make the citation perfect, thank you very much!On 4. Jul 2024, at 01:03, paul-gauthier ***@***.***> wrote:﻿
The version that appears on the blog is dated. I'm the author. Happy to add my actual name to it if that helps you?
https://aider.chat/2023/12/21/unified-diffs.html

**Comment by paul-gauthier** [comment]
Ok, it now says "December 21, 2023, by Paul Gauthier".

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by LukvonStrom** [comment]
May I also ask for attribution to be added to this page please? https://aider.chat/docs/leaderboards/

**Comment by paul-gauthier** [comment]
That page is updated regularly, as new models are benchmarked, etc. So at best it would have a "last updated date", not a "date of publication". Not sure if that's useful for you?

**Comment by LukvonStrom** [comment]
that would work, a citation after all just should reference the when - I might add a link to archive.org for my research though :)

**Comment by paul-gauthier** [comment]
The leaderboard page now has an author & date:

> By Paul Gauthier, last updated July 29, 2024.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
