### ISSUE TITLE
[Q] Do you know any good opensource voice clients for AI chat?

### ISSUE THREAD

**Issue by NightMachinery** [paul-gauthier/aider#779]
Do you know any good opensource voice clients for AI chat?

I tried `/voice`, and it worked quite well, even though both my accent and the internet connection here are less than ideal. I am now wondering if there any good FOSS voice-centric clients that allow one to chat with GPT4O or Sonnet 3.5.

PS: The voice mode in aider is somewhat cumbersome to use? I think when one enters `/voice`, aider should go in a voice mode, and the next time it needs input, a simple enter should allow it to start listening. Typing `/voice` is inconvenient.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can just do `/v` and you can also use the up arrow to use previously entered commands.

Sorry, I don't have any recommendations for other voice clients.

**Comment by NightMachinery** [comment]
Thanks.
