### ISSUE TITLE
Please provide a way to add which model to use

### ISSUE THREAD

**Issue by sarkaramitabh300** [paul-gauthier/aider#78]
As chat GPT 4 is quite expensive, it would be fantastic if you could offer the ability to integrate GPT models for use via command line.

**Comment by imhsouna** [comment]
+1

**Comment by imhsouna** [comment]
API key does not support gpt-4-32k, falling back to gpt-3.5-turbo-16k

**Comment by paul-gauthier** [comment]
You'll get that error if the OpenAI API key you are using is not authorized to use gpt-4-32k. OpenAI has not released that model to many users. It doesn't appear that they key you are using has been granted access?

**Comment by imhsouna** [comment]
yes i still have not access to gpt-4-32k, i have to wait :)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue if you have any further problems.
