### ISSUE TITLE
[Bug]: Repo-map: disabled for ollama models

### ISSUE THREAD

**Issue by danividalg** [paul-gauthier/aider#781]
### Issue

Repo-map seems to be disabled for all ollama models.
I tried with the following commands and all shows the same result:
- aider --model ollama/qwen2:72b-instruct-q8_0
- aider --model ollama/deepseek-coder-v2
- aider --model ollama/llama3

The output is:

Model ollama/deepseek-coder-v2: Unknown context window size and costs, using sane defaults.
For more info, see: https://aider.chat/docs/llms/warnings.html

Aider v0.41.0
Model: ollama/deepseek-coder-v2 with whole edit format
Git repo: .git with 29 files
Repo-map: disabled
Use /help to see in-chat commands, run with --help to see cmd line args

Or

Aider v0.41.0
Model: ollama/llama3 with whole edit format
Git repo: .git with 29 files
Repo-map: disabled
Added src\main\java\com\danividalg\skillpillweb\service\DemoService.java to the chat.
Use /help to see in-chat commands, run with --help to see cmd line args

The problem seems to not be present with other models with api key like GPT, Claude or Deepseek, with commands like:
- aider --model deepseek/deepseek-coder
- aider --model openrouter/anthropic/claude-3.5-sonnet
- aider

The output is:
Aider v0.41.0
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/anthropic/claude-3-haiku-20240307
Git repo: .git with 29 files
Repo-map: using 1024 tokens
Use /help to see in-chat commands, run with --help to see cmd line args

Where we can see that the repo-map is enabled and set to 1024 tokens

In addition seems to exists another error related with litellm (message "Model ollama/deepseek-coder-v2: Unknown context window size and costs, using sane defaults.") that I already reported here https://github.com/BerriAI/litellm/issues/4521

Hope this problem with the repo-map can be solved because I want to use aider with ollama/deepseek-coder-v2 (16b) so it can be completelly free and local.

Thanks a lot in advance for your help :)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Thanks for trying aider and filing this issue. These docs may be helpful:

https://aider.chat/docs/troubleshooting/warnings.html

https://aider.chat/docs/config/adv-model-settings.html

**Comment by danividalg** [comment]
Thanks for your quick reply! :)
It works!, I didn't see the advanced model settings info
I have been able to fix both problems.
Thank you very much :)
