### ISSUE TITLE
Run Docker Image freeze

### ISSUE THREAD

**Issue by dannylank** [paul-gauthier/aider#789]
### Issue

I start docker with  docker run -it -p 8501:8501 --volume $(pwd):/app aider-chat  --no-auto-commits --35-t
urbo --no-verify-ssl --openai-api-key sk-proj-... --browser. first I have to add this to a docker file:
1. RUN git config --global --add safe.directory /app. Because always show that and stops the container
2. I need to add a port to run -p 8501:8501 with a docker container, the other way don´t work
3. Is running welll but when open the url shows = Running get_coder(). with spinner but it doesn't move forward it stays there
4. when make a ctrl+c shows:
Exception ignored in: <module 'threading' from '/usr/local/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
  File "/usr/local/lib/python3.10/site-packages/streamlit/web/bootstrap.py", line 44, in signal_handler
    server.stop()
  File "/usr/local/lib/python3.10/site-packages/streamlit/web/server/server.py", line 405, in stop
    self._runtime.stop()
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/runtime.py", line 324, in stop
    async_objs.eventloop.call_soon_threadsafe(stop_on_eventloop)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 798, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

### Version and model info

Aider v0.41.0
35-turbo

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, I am not sure I understand what issue you are reporting?

**Comment by dannylank** [comment]
using docker over wsl --browser doesn't work. Stay showing: Running get_coder().

**Comment by paul-gauthier** [comment]
I was able to use the browser just fine like this:

```
$ docker run -it -p 8501:8501 --volume $(pwd):/app paulgauthier/aider --browser <..rest of args...>
```

And then connect my browser to `http://0.0.0.0:8501/`

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by rasodu** [comment]
I use Aider webui on a remote server. When I start the container, it provides several options to access the UI, but none of these IP addresses match my host's IP address. Is there a way to set the hostname or configure Aider to bind to 0.0.0.0?

```
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.18.0.5:8501
  External URL: http://<external-modem-ip>:8501
```
