### ISSUE TITLE
update deepseek-coder to 128k

### ISSUE THREAD

**Issue by zx9597446** [paul-gauthier/aider#792]
deepseek changes context from 32k to 128k

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I've submitted a PR to litellm to update deekseek coder's context window.

https://github.com/BerriAI/litellm/pull/4541

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
