### ISSUE TITLE
I guess you could call it a success

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#793]
### Issue

![image](https://github.com/paul-gauthier/aider/assets/95491982/4bbba4d2-95c5-48b2-b074-c2330a16ceb4)

Assuming 3 thousand tokens per commit. That's almost 20,000 commits this week, only on open router via this model.

And number one to use DeepSeek-Coder-V2

![image](https://github.com/paul-gauthier/aider/assets/95491982/a6198bf2-651e-4965-8e4a-869cf0a68a8b)

**Comment by paul-gauthier** [comment]
Thanks for sharing this!

**Comment by agawrylak** [comment]
Where is this from?

**Comment by paul-gauthier** [comment]
Open router leaderboards. 


I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by ErykCh** [comment]
And aider keeps going up.

The screenshot at the beginning was from Thursday and this one is from Wednesday.

![image](https://github.com/paul-gauthier/aider/assets/95491982/904293d1-f128-42d1-9375-1f077a9360a2)

**Comment by ErykCh** [comment]
continued climbing ...

![image](https://github.com/user-attachments/assets/cd42d6fd-e7d1-40a9-be56-c4e25589292f)

**Comment by ErykCh** [comment]
still progress

![Screenshot_2024-07-25-23-04-56-20_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/94691d08-cc8c-443a-ac1a-1430b69bd95c)
