### ISSUE TITLE
Add Nvidia NIM Support

### ISSUE THREAD

**Issue by parththakor** [paul-gauthier/aider#794]
### Issue

Hi Aider Team, 

It would be great to have support for Nvidia NIM I tried using the openAI base url but litellm keeps throwing errors for some reason, 

Thanks!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by huvers** [comment]
@parththakor -- NVIDIA NIMs work for me. Here's my code snippet:

    if args.model == "NIM-llama3.1-405b":
        print(f"Using NVIDIA NIM API with {args.model}.")
        os.environ["OPENAI_API_BASE"] = "https://integrate.api.nvidia.com/v1"
        os.environ["OPENAI_API_KEY"] = os.environ.get("NVIDIA_API_KEY")
        client_model = "openai/meta/llama-3.1-405b-instruct"
        client = openai.OpenAI(
            base_url=os.environ["OPENAI_API_BASE"],
            api_key=os.environ["OPENAI_API_KEY"]
        )
