### ISSUE TITLE
Backtrack in Anthropic API

### ISSUE THREAD

**Issue by tiagoefreitas** [paul-gauthier/aider#798]
### Issue

If I use whole file mode with the Anthropic API I get rate limited. Would be great to support backtracking.
The OpenAI client libs have it built-in, but not anthropic, so you could see how openai does it and just copy the code :)
Will do it when I have time if no one else picks it up.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, what do you mean by backtracking?

Why not use diff mode? Or, you can use the anthropic models via openrouter which doesn't rate limit them.

**Comment by tiagoefreitas** [comment]
backtracking means when you hit a rate limit you wait and try again and if
you hit it again you wait longer there is a standard way/formula.

btw is there bedrock support? have credits and higher limits there

thanks!

**Comment by paul-gauthier** [comment]
Ah, you're referring to backoff and retries. Aider does this already. You should see lines like `Retry in XX seconds` when it does this. After 60 seconds worth of retries it will fail with the underlying error.

Aider supports most APIs, via litellm.

For general info on using aider with APIs see:

https://aider.chat/docs/llms.html

See the litellm docs on bedrock specifically:

https://litellm.vercel.app/docs/providers/bedrock

**Comment by tiagoefreitas** [comment]
sorry got the term mixed up…ok I may have missed those lines

thanks, aider has been very helpful lately. you should monetize it it’s too
good to be free

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
