### ISSUE TITLE
Stop it from refactoring on empty prompt when adding files

### ISSUE THREAD

**Issue by tiagoefreitas** [paul-gauthier/aider#799]
### Issue

Sometimes when I or the VS Code extension adds files, Aider decides to refactor the code without a prompt.
Not sure if I click enter by accident with a blank prompt, but would like to disable that.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
