### ISSUE TITLE
Customize commit message

### ISSUE THREAD

**Issue by Thanatermesis** [paul-gauthier/aider#803]
### Issue

Since the commit message is generated by AI (I assume), could be good to have an instruction parameter to add to its generation, for example:

```text
--instruction-commit   Give a special instruction for the commit message generation
```
_this instruction will be appended to its main instruction, similar to: "create a message for the commit. + but make it short"_

For example, I would like to give the instruction to make the messages more human-understandable, it actually only says exactly what has modified but not why, when the commit is about fixing a bug this is important to explain like "before a possible race condition could happen when X Z, by checking the variable Y before to use it will avoid it"

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.


This looks like a duplicate of #398, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.
