### ISSUE TITLE
BadRequestError

### ISSUE THREAD

**Issue by Reza-kh80** [paul-gauthier/aider#804]
### Issue

Hi everyone, after that I entered aider in the console and wrote my prompt, I got this error:
ERROR:
BadRequestError: litellm.BadRequestError: AnthropicException -
{"type":"error","error":{"type":"invalid_request_error","message":"Your credit balance is too low to access the Claude
API. Please go to Plans & Billing to upgrade or purchase credits."}}

I connected to Claude Sonnet and got API key from this site: https://console.anthropic.com/settings/keys
and set by this command:
set ANTHROPIC_API_KEY=sk-***

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The error message says you need to purchase Anthropic credits. 

> Your credit balance is too low to access the Claude API. Please go to Plans & Billing to upgrade or purchase credits

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by vigneshnani1234** [comment]
hello everyone.....
iam also facing this same issue of badrequest while i want work on my project and used an agent to help and on running few commands i am facing this issue.
BadRequestError: litellm.BadRequestError: AnthropicException -
{"type":"error","error":{"type":"invalid_request_error","message":"Your credit balance is too low to access the Claude
API. Please go to Plans & Billing to upgrade or purchase credits."}}

please help me to work on my project and to fix this issue
