### ISSUE TITLE
[enhancement] Enable stop streaming in streamlit (--browser)

### ISSUE THREAD

**Issue by avimar** [paul-gauthier/aider#807]
### Issue

Similar to #595 not all options are available in the browser interface - such as interrupting. In the CLI we can do ctrl-C to interrupt the current process.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

There should be a STOP button at the top right of the browser window?

<img width="986" alt="2024-07-07_07-42-30" src="https://github.com/paul-gauthier/aider/assets/69695708/1313eb73-465e-4ce9-96c3-e67b9cae7665">

**Comment by avimar** [comment]
Oh, yes I see it there, sorry! It indeed seems to work.

I was expecting it by the submit button like chatgpt and librechat does.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
