### ISSUE TITLE
do not depend on numpy 2

### ISSUE THREAD

**Issue by NightMachinery** [paul-gauthier/aider#808]
```
aider-chat 0.41.0 requires numpy==2.0.0, but you have numpy 1.26.4 which is incompatible.
```
I get this warning in `pip`. Since lots of libraries are still not compatible with numpy 2, it'd be good to support both?

Is there a way to easily install `aider` in an isolated env? I think `pipx` does NOT do this? What do you use yourself?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Yes, pipx should install aider in its own isolated environment.

https://aider.chat/docs/install/pipx.html

**Comment by paul-gauthier** [comment]
You should consider installing the latest aider v0.43.0, which no longer asks for numpy 2.0.0. It uses `numpy==1.26.4`.

**Comment by NightMachinery** [comment]
Thanks, yes, pipx seems to work.
