### ISSUE TITLE
Groq models stopped to work ? 

### ISSUE THREAD

**Issue by Thanatermesis** [paul-gauthier/aider#811]
### Issue

Today it doesn't seems to work with the Groq models, im trying multiple ones and seems like some changes happen but not the ones that im requesting, also is not showing up any diff...

I'm trying each model one to one and at least this one seems outdated from the list:

```
Unexpected error: litellm.NotFoundError: GroqException - Error code: 404 - {'error': {'message':
'The model `llama2-70b-4096` does not exist or you do not have access to it.', 'type':
'invalid_request_error', 'code': 'model_not_found'}}
```

**Comment by Thanatermesis** [comment]
Mixtral seems to be the only to "do something", but it keeps 10 seconds waiting and finally throws:

```

litellm.RateLimitError: RateLimitError: GroqException - Error code: 429 - {'error': {'message': 'Rate limit reached for model `mixtral-8x7b-32768` in organization `org_01j1xwgekre1d9g95kazm8e068` on tokens per minute (TPM): Limit 5000, Used 0, Requested 6053. Please try again in 12.636s. Visit
https://console.groq.com/docs/rate-limits for more information.', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Retry in 0.1 seconds.
```

I'm trying it with a very small html git with only 18 files so I don't think that the contents are so high

**Comment by Thanatermesis** [comment]
This seems to be an issue with the amount of tokens or with models limitation so maybe should be closed,

I will left it open for the "llama2" deprecated listed entry

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/llms/groq.html


When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```

**Comment by Thanatermesis** [comment]
Hi @paul-gauthier,

Seems like the issue happens "sometimes", so sounds more like a server (groq) problem where they don't reply, I think this issue should be fixed, on the other hand as mentioned in the first message **llama2-70b-4096** looks to be a deprecated / unexisting entry, it is removed from the list? (I cannot check so i downgraded to 0.42 due to the big recent changes, but I will upgrade soon or wait for 0.44

**Comment by paul-gauthier** [comment]
FYI, I released v 0.43.4 recently which is much smaller. 


I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by Ehsan-msmmed** [comment]
Run a VPN on your system then try again

**Comment by be42day** [comment]
Run a VPN on your system then try again
