### ISSUE TITLE
Deepseek models wrongly defined

### ISSUE THREAD

**Issue by Thanatermesis** [paul-gauthier/aider#812]
### Issue

I'm trying the deepseek models, as shown in documentation and the interactive interface the model name is **deepseek-coder**, but it fails, seems like the correct model name is **deepseek/deepseek-coder** instead

**Comment by Thanatermesis** [comment]
Seems like im facing a similar issue to i found at #811 , is processing really slow (3-5 minutes in that progress bar) and it says that im exceeding my tokens ? but I only provided a single .html file of 196 lines to the chat, nothing more

```
 + 109 / 196 lines [████████████████░░░░░░░░░░░░░░]  56%

Model deepseek/deepseek-coder has hit a token limit!
Token counts below are approximate.

Input tokens: ~10,441 of 128,000
Output tokens: ~2,785 of 4,096
Total tokens: ~13,226 of 128,000

For more info: https://aider.chat/docs/troubleshooting/token-limits.html
````

In a second attempt it seems to have work better, maybe because the model has been provided on the terminal? (on the first attempt, when started it said "Repo-map: disabled" )

```text
❯ aider --yes --show-diffs --auto-commits --model deepseek/deepseek-coder  components/Hero.tsx                                                                                                                                                                                  untracked
Aider v0.43.0
Model: deepseek/deepseek-coder with diff edit format
Git repo: .git with 18 files
Repo-map: using 1024 tokens
Added components/Hero.tsx to the chat.
Use /help <question> to ask for help, run with --help to see cmd line args
```

now, the final result was a bit strange, but I assume for now that it was a limitation of the model imperfections

**Comment by Thanatermesis** [comment]
In the statistics I can see it used **167k** input tokens, 5k output

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, which documentation page are you referring to? This one looks correct?

https://aider.chat/docs/llms/deepseek.html

**Comment by Thanatermesis** [comment]
Not the documentation but the tool itself, when you use /model or /models it shows deepseek-code without the prepended deepseek/

**Comment by paul-gauthier** [comment]
I made some changes to improve this. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
