### ISSUE TITLE
aider should register the commits it does

### ISSUE THREAD

**Issue by Thanatermesis** [paul-gauthier/aider#814]
### Issue

if the --no-attribute-author/committer is used, seems like causes this issue:

```
> /undo
The last commit was not made by aider in this chat session.
```

To solve this, aider should keep a track of the commits (probably better using the commit ID) on a history file in order to know which ones has been made by aider

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This bug should be fixed in the latest release.
