### ISSUE TITLE
ability to add multiple codebase as library to repo map [feature requests]

### ISSUE THREAD

**Issue by linziwen** [paul-gauthier/aider#818]
As the context of the llm one step forward, maybe aider should have ability to add more than one codebase as library to the repo map. Thank you and I love aider very much

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Why do you want to add multiple code bases? What are you trying to do?

You can add doc web pages for libraries with /web. 

https://aider.chat/docs/usage/images-urls.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
