### ISSUE TITLE
Don't ask to add urls to the chat

### ISSUE THREAD

**Issue by SuchAFuriousDeath** [paul-gauthier/aider#820]
When making a prompt such 'Add a function that sends a request to https://some.url the user is asked whether he wants to add https://some.url to the chat, which is nonsense.

**Comment by 5ocworkshop** [comment]
I disagree, it can be quite helpful in various situations - for example various platforms like sqalchemey report a brief error and also return a URL that explains what is wrong in detail.  This allows you to quickly add that URL to the current chat which can help significantly in resolving an issue.

On the flip side, I also see where you are coming from.  I am working with a database that contains URLs as one of the fields and during debug, when there are a lot of URLs appearing on the console, I can get prompted a dozen times or more.  It would be nice to be able to turn it off if you don't want it for that session (and in fairness perhaps you can and I haven't looked?).

**Comment by SuchAFuriousDeath** [comment]
I agree. I didn't realize that you can actually have aider download files, I just though this was unambiguously a bug. My bad :)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
