### ISSUE TITLE
--extra-index-url 

### ISSUE THREAD

**Issue by fferreres** [paul-gauthier/aider#824]
pip install complains about --extra-index-url  in the requirements.txt file. I passed the cpu index via env variable and commented that out. not sure if it's just me, otherwise close.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I am working on this topic at the moment. It would be helpful if you could share the error output you were seeing?

**Comment by fferreres** [comment]
fixed with the later commits you did. thank you!
