### ISSUE TITLE
Feature Request: Configurable Command Prefix for LLM Interaction

### ISSUE THREAD

**Issue by Adoliin** [paul-gauthier/aider#825]
### Issue

I'm starting to use Aider and appreciate its integration into the development workflow. However, I've encountered an issue that could potentially improve the user experience and reduce token consumption errors.

### Issue Description

Currently, in Aider, commands for interacting with the LLM begin with a `/` prefix (e.g., `/add`, `/drop`). This system works well, but the default behavior allows any non-prefixed input to be sent directly to the LLM. This has led to several instances where I accidentally trigger the LLM because I forget to use the `/` prefix, leading to unnecessary token usage, especially in contexts with a large number of tokens.

### Suggested Feature

I propose adding a configuration option that changes the default interaction model with the LLM. Specifically, it would be beneficial to have a setting where:

- **Only commands prefixed with `/chat` are sent to the LLM**. This would prevent accidental activation of the LLM and help users manage token usage more efficiently.
- **Optionally, allow users to execute all commands without a prefix**, aligning more closely with typical terminal usage where commands are entered without a `/`.

This feature would help users like me, who spend significant time in the terminal, to adapt more seamlessly to Aider's command structure without frequent errors.

### Benefits

- **Reduces accidental LLM activations**: Limits unnecessary token loss and enhances user control.
- **Enhances user adaptation**: Aligns more closely with common terminal behaviors, easing the learning curve for new and transitioning users.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I think this is out of scope for aider, as it is intended primarily to chat with the LLM about coding.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
