### ISSUE TITLE
How to change top of git repo, accidentally started aider first time in homedir

### ISSUE THREAD

**Issue by 5ocworkshop** [paul-gauthier/aider#826]
### Issue

When I first tried aider months ago I must have launched it while in my home directory and of course it set that as the top of the git repo.  You can imagine this is sub-optimal for keeping projects separated.

Is there an elegant way for me to reset the git repo to a sub-directory so I can have different repos for different projects under my home directory?  Even if I lost my change history I'm ok with that to get this cleaned up.

Thanks in advance.  0.43 with GPT-4o and Sonnet 3.5

**Comment by 5ocworkshop** [comment]
But if the folder is a subdir of a parent where the top of the git tree is, won't it still be included or will that cause that subdir to be removed?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider should use the most specific git repo. 

You could also consider deleting the .git dir from your home directory. But you would lose all prior git history if you did that.
