### ISSUE TITLE
Please add deepseek in sample.env

### ISSUE THREAD

**Issue by yhmickey** [paul-gauthier/aider#832]
### Issue

Please add DEEPSEEK option in sample.env

**Comment by sprappcom** [comment]
deepseek v2 coder of the deepseek api website i think. currently there's no v2, only "v1"

**Comment by sprappcom** [comment]
i got it working. it is working deepseek/coder model option

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/llms/deepseek.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
