### ISSUE TITLE
Please Add support for integration plugins for the JetBrains series of IDEs

### ISSUE THREAD

**Issue by DeepakChen** [paul-gauthier/aider#838]
### Issue

I do not prefer using VS Code as my IDE; instead, I utilize JetBrains' PyCharm and other IDEs for my development work. I hope that the aider can add plugin support for JetBrains' series of code editors.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.


This looks like a duplicate of #650, so I'm going to close it so discussion can happen there. Please let me know if you think it's actually a distinct issue.
