### ISSUE TITLE
NeoVim plugin

### ISSUE THREAD

**Issue by joshuavial** [paul-gauthier/aider#84]
Amazing project, definitely the best AI coding assistant I've used. Here is a nvim plugin I knocked together with it that might be useful for folks - https://github.com/joshuavial/aider.nvim

**Comment by paul-gauthier** [comment]
This is great. Thanks for putting it together and sharing it with me. Let me find a good way to link to your repo from the documentation, probably somewhere in the installation instructions. I'll update this issue when I have a chance to do that.

**Comment by paul-gauthier** [comment]
I added a link to your plugin in the new installation instructions doc.

https://aider.chat/docs/install.html

Thanks again!
