### ISSUE TITLE
ubuntu 24.04 based docker support

### ISSUE THREAD

**Issue by sprappcom** [paul-gauthier/aider#841]
ubuntu is easier to add more features. pls do support docker ubuntu version in future if possible.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You should be able to copy the `docker/Dockerfile` and switch the FROM line to your preferred base distribution.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
