### ISSUE TITLE
/add twice in a command crashes program

### ISSUE THREAD

**Issue by transcendr** [paul-gauthier/aider#844]
### Issue

Minor bug that I just encountered. Mid-conversation I meant to add a couple files but accidentally used `/add` twice and it crashed.

![image](https://github.com/user-attachments/assets/7dec9bd2-c617-4f44-b607-18aee03e38cd)

### Version and model info

![image](https://github.com/user-attachments/assets/d06590e9-e7de-4919-8979-718ae5a1fb6b)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

If you want to add multiple files at the same time, you don't need to type `/add` more than once. Just type all the files after the `/add`, like this:

```
/add file1.go file2.go another-file.go
```

That said, aider shouldn't crash if you type `/add` more than once. I've fixed that bug.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by transcendr** [comment]
@paul-gauthier thanks, long time user, aware that /add is only required once, was just reporting the crash. You're doing god's work with aider.
