### ISSUE TITLE
Huggingface

### ISSUE THREAD

**Issue by RFARREY** [paul-gauthier/aider#846]
### Issue

How dare you make a list of endpoints and forget to include Hugginface? The mother of all AI model repos? You my dear friend need an exorcist immediately and a baptism to align you with the cause. Repent from your ways and seek the kingdom. Bow before the throne that is hugginface and don't be disrespectful. Go and sin no more!

### Version and model info

ALL versions my friend. wake up now!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Aider supports HF via LiteLLM.

https://litellm.vercel.app/docs/providers/huggingface

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
