### ISSUE TITLE
Upgrade Not Working

### ISSUE THREAD

**Issue by websmyths** [paul-gauthier/aider#847]
### Issue

When I run aider it says the following:

> Newer version v0.43.4 is available. To upgrade, run:
> /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -m pip install --upgrade aider-chat
> Aider v0.41.0

I have run the upgrade several times and after the first time it says:

> Installing collected packages: aider-chat
> Successfully installed aider-chat-0.43.4
> 

But when I run aider again, I get the same upgrade message above. When I do:

> aider --version
> aider 0.41.0
> 

I even uninstalled and reinstalled it. It says 0.43.4 is installed, but when I run it or ask for the version it says 0.41.0 is running. 

Aider v0.41.0
Model: Sonnet

**Comment by chrisspen** [comment]
Yeah, it's completely broken for me too. Using the GPT backend, and now it doesn't respond to anything. It just hangs.

**Comment by websmyths** [comment]
> Yeah, it's completely broken for me too. Using the GPT backend, and now it doesn't respond to anything. It just hangs.

It's not broken. It just won't upgrade. Otherwise working fine.

**Comment by websmyths** [comment]
It works now. I tried closing my terminal session and opening a new one and got the new version of Aider. Closing issue.
