### ISSUE TITLE
Exclamation Marks Output Issue

### ISSUE THREAD

**Issue by ceabarr** [paul-gauthier/aider#852]
### Issue

Hello,

I am using Aider with Deepseek-coder-v2 on the IDX platform without any issues, but when I try to use it locally with Ollama with VSCode, all my responses return "!!!!!!!!!!!" answer. 

First, I installed ollama and then use "ollama run deepseek-coder-v2" and started the server, talked with the LLM without any issues. After that, I ran "aider --model ollama/deepseek-coder-v2" and started the chat, but the response was always bunch of exclamation marks. Here is the screenshot:
![aider error](https://github.com/user-attachments/assets/223c535e-8864-4e35-b2e8-38df164d7659)

I tested with or without a metadata file just to check if it made any difference, but it didn't.

After triggering this error, ollama is also starting to act up and when I go back and try to talk with ollama, it does the following:
![ollama error](https://github.com/user-attachments/assets/5795710a-876e-49f4-8762-c049832b8a75)

I only managed to run aider with deepseek only one time (I was trying everything, uninstalling, reinstalling, etc) but that was it, its not working again. I don't know what else to do.

Please help me.

Thanks in advance.

### Version and model info

Aider v0.43.4
Model: ollama/deepseek-coder-v2 with whole edit format
Git repo: .git with 7 files
Repo-map: disabled
VSCode terminal detected, pretty output has been disabled.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This is probably a sign that your quantized LLM is not capable of following aider's system prompt. You should use a stronger model.

https://aider.chat/docs/llms.html#use-a-capable-model

**Comment by ceabarr** [comment]
Hello,

As you can see, I am using deepseek-coder-v2, which is capable of following Aider's system prompt according to the Aider's LLM Leaderboard. However, I solved my issue by not using Ollama's Windows server client and instead running the "Ollama serve" directly from the terminal.

**Comment by paul-gauthier** [comment]
Glad to hear it's working for you now. 

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
