### ISSUE TITLE
Setting the maximum number of recent questions in the chat history.

### ISSUE THREAD

**Issue by ErykCh** [paul-gauthier/aider#858]
### Issue

I would like to be able to set how many last questions should be remembered in the chat history. When working longer, I don't want the last 50 questions to be in the chat history. I think that the last 7 questions are a reasonable maximum.

### Version and model info

Aider v0.43.5-dev
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model openrouter/anthropic/claude-3-haiku
Git repo: .git with 96 files
Repo-map: using 2028 tokens
Added .aider.memory.md to the chat.

**Comment by paul-gauthier** [comment]
Aider already summarizes the past chat history to keep it from growing unbounded.
