### ISSUE TITLE
Rate limit exceeded with Anthropic - lacks appropriate backoff

### ISSUE THREAD

**Issue by trs-80** [paul-gauthier/aider#861]
### Issue

Aider v0.43.4
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 20 files
Repo-map: using 1024 tokens

Made a request to resolve and issue with the code and received these messages:

```
litellm.RateLimitError: AnthropicException - {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit
(https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also
contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}
Retry in 0.7 seconds.
litellm.RateLimitError: AnthropicException - {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit
(https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also
contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}
Retry in 0.5 seconds.
litellm.RateLimitError: AnthropicException - {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit
(https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also
contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}
Retry in 3.6 seconds.
litellm.RateLimitError: AnthropicException - {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit
(https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also
contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}
Retry in 6.1 seconds.
```

**Notice the retry wait keeps increasing**

Have been using aider without issue with Anthropic for the last 3 days on the repo up until I run out of daily tokens, but first time I have run into this issue. Nothing that I am aware of is special about the change/issue that I am attempting to resolve.

### Version and model info

Aider v0.43.4
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 20 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This is a standard exponential backoff strategy.

FYI, you can use Sonnet through OpenRouter to avoid rate limits.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by psigmasoft** [comment]
https://unify.ai/ looks to be an interesting alternative to OpenRouter - is there any likelihood that services other than OpenRouter might be supported for dealing with reducing LLM token costs?
