### ISSUE TITLE
files outside of a repo can be added when invoking aider, edits can be made

### ISSUE THREAD

**Issue by sudomain** [paul-gauthier/aider#865]
I'm not sure if this is a feature or bug:

It seems we're allowed to add files outside of the repo when invoking aider:

`aider ~/testfile.conventions.md`

But the same files cannot be when using the `/add` command. 

I personally, I like this because I want to be able to include different conventions.md files for different languages, frameworks, etc. For example, in `~/.config/aider/conventions/` having `python.conventions.md` or `bash.conventions.md`

_Originally posted by @sudomain in https://github.com/paul-gauthier/aider/issues/660#issuecomment-2228882254_

**Comment by paul-gauthier** [comment]
Thanks, this is probably a bug.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
