### ISSUE TITLE
Aider .env precedence is wrong, does not behave as documented.

### ISSUE THREAD

**Issue by nevercast** [paul-gauthier/aider#868]
### Issue

Aider does not load the correct `OPENAI_API_KEY`. I have it defined in both my home directory and my .git root (which also happens to be my current directory). 

### Expectation

Aider uses the `OPENAI_API_KEY` from my git root / current directory, not the one in my home directory.

### Behaviour

Aider is using the key that's specified in my home directory, this behaviour can also be seen if I set the key as a User or System environment variable, that defined env var will take precedence over .env files, which feels incorrect and also does not align with the documented behaviour.

### Documentation

https://aider.chat/docs/config.html#configuration
> Aider has many options which can be set with command line switches. Most options can also be set in an .aider.conf.yml file which can be placed in your home directory or at the root of your git repo. Or by setting environment variables like AIDER_xxx either in your shell or a .env file.

https://aider.chat/docs/config/dotenv.html#config-with-env
> Aider will look for a .env file in these locations:
> Your **home** directory.
> The **root** of your git repo.
> The **current** directory.
> As specified with the --env-file <filename> parameter.
> If the files above exist, they will be loaded in that order. **Files loaded last will take priority**.

### Hypothesis & Workarounds

I have not found a workaround to get hierarchical environment variables working. I tried using --env-file on the command line, and still the home dir env takes precedence. 

1. Initially I suspected that perhaps the OPENAI_API_KEY was already loaded into my shell, and Aider was letting the shell's environment take precedence over .env (behaviour I would still find confusing). However, I have verified that this is not the case. OPENAI_API_KEY is not defined in the shell before launching Aider.
2. I can confirm that if I define OPENAI_API_KEY on the CLI before launching Aider, that value takes precedence. 
3. I can confirm that if I use --openai-api-key on the CLI, that has the highest precedence. 

Thus, the behaviour seems to match ConfigArgParse of command line > environment variables > config file values > defaults, where environment variables are trampling .env files. 

What I do not expect, is that `~/.env` is being loaded between the launch of Aider and the ConfigArgParse, populating the environment and causing the config file values to not work as expected. 

I have tried using AIDER_OPENAI_API_KEY to see if that auto loads in ConfigArgParse and tramples the environment, that does not work either.

I see python-dotenv is a transient dependency of lite-llm, but that should have behaviour that works in my favour, not against it. 

```
python-dotenv==1.0.1
    # via litellm
```

### Screenshot

I echo the API key via /run to demonstrate that the environment is not populated correctly, when Aider tries to make a commit in this configuration (because its using GPT-3.5 as weak model) it will fail as it will use 'homedir' as the API key instead of the correct key defined in my project.

![image](https://github.com/user-attachments/assets/c12cc39b-b634-46fe-ac80-b1a195fb6121)

### Version and model info

Aider v0.43.4
Model: claude-3.5-sonnet / gpt-3.5-turbo
Git repo: 497 files
Repo-map 1024

**Comment by paul-gauthier** [comment]
Thanks for reporting this. I can reproduce the problem.

**Comment by paul-gauthier** [comment]
The fix is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by nevercast** [comment]
LGTM! Thanks! 🚀
