### ISSUE TITLE
Repo-map:disabled when use aider by azure openAI. how to fix it

### ISSUE THREAD

**Issue by Randylcy** [paul-gauthier/aider#869]
### Issue

![image](https://github.com/user-attachments/assets/d8725f7c-9434-4b68-b701-325738019482)
As u can see, Repo-map is disabled, when use aider by azure openAI. But I have watched the blog of Aider, nothing else should user do to use the Repo-map. How to fix the problem? anyone konw it

### Version and model info
Aider v0.43.4
Model: azure/aider1 with whole edit format. (GPT-4o)
Git repo: .git with 348 files
Repo-map: disabled

_No response_

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/config/adv-model-settings.html

**Comment by Randylcy** [comment]
您的邮件我已收到。我尽快查看并回复

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by Randylcy** [comment]
> I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

thx so much. it worked by your tips

**Comment by Randylcy** [comment]
> Thanks for trying aider and filing this issue. This doc may be helpful:
> 
> https://aider.chat/docs/config/adv-model-settings.html

thx so much. it worked by your tips

**Comment by Astlaan** [comment]
@paul-gauthier 

I'm trying to use grok:

```
    "xai/grok-beta": {
        "max_tokens": 131072,
        "max_input_tokens": 131072,
        "max_output_tokens": 131072,
        "input_cost_per_token": 0.000005,
        "output_cost_per_token": 0.000015,
        "litellm_provider": "xai",
        "mode": "chat",
        "use_repo_map": true
    }
```

I tried both `xai/grok-beta` (as above) and `grok-beta` as model id, however, when I initialize aider, the repo map always comes disabled:

```
Aider v0.63.1
Model: xai/grok-beta with architect edit format
Editor model: xai/grok-beta with editor-diff edit format
Git repo: .git with 60 files
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args
```

I had to manually include `--map-tokens 1024` in the aider command for the repo map to start working.

**Comment by Randylcy** [comment]
您的邮件我已收到。我尽快查看并回复
