### ISSUE TITLE
How to modify Aider with Aider?

### ISSUE THREAD

**Issue by SerialIterator** [paul-gauthier/aider#870]
### Issue

I'm adding a feature to Aider using Aider. I cloned the main branch and started working on it locally. Once I thought it was ready to test I created a separate conda environment and installed a development version there so I could modify it quickly. When I use the "real" aider to edit my local files, pip updates all my envs to point to the local file. The Aider blog says Aider wrote a large portion of it's own files. What do you do to isolate a "functional" Aider program from the dev version so you can work on it?

### Version and model info

Aider v0.43.5dev
Windows 11 using separate conda environments to isolate versions of Aider

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/install/pipx.html

https://aider.chat/docs/install/optional.html#install-the-development-version-of-aider

**Comment by SerialIterator** [comment]
I'm familiar with editing and installing local packages in development mode but I'm having odd behavior from pip.

1. I cloned the repo locally, lets say in `/Documents/aider`
2. create two conda environments `aider_original` and `aider_dev`.
3. install Aider in `aider_original` with `pip install aider-chat`
4. switch to `aider_dev` with `conda activate aider_dev`.
5. I change version number in `aider/__init__.py` file to ensure I which package is which. 
6. navigate to `/Documents/aider` and install a local development version with `pip install -e .`
7. I check aider with `aider --version` and it outputs my dev version
8. switch to `aider_original` env
9. check aider version and it is the original version
10. navigate to `/Documents/aider`
11. check aider version with `aider --version` and it shows my dev version
12. navigate back to `/Documents` and check version with `aider --version` and its the original

I can use `pip list` and if I'm in the development directory, pip displays the dev version as if it is installed even though I have installed it in the `aider_dev` env. I've checked the envs `Lib/site-packages` and `aider_original` shows the package as installed but `aider_dev` shows the `aider-chat.egg-link` as it is a symlink to use the development package. Which is how to should be.

When I try to use aider in my dev directory, pip somehow thinks it needs to use my dev version and switches over but ONLY while I'm in the aider directory.

I resorted to using `aider_original` inside of an ubuntu WSL instance to isolate it completely but it is slower as it has to access the mounted files from windows to work on my dev version. 

I didn't expect this behavior and I'm wondering if anyone who has worked on Aider with Aider just uses separate environments and its fine. It's as if pip sees the local directory and thinks that it should use that but that's not how pip is supposed to work

**Comment by paul-gauthier** [comment]
Sorry, it would be very hard for me to help debug your local python development environment.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
