### ISSUE TITLE
Add --openrouter-api-key configuration option

### ISSUE THREAD

**Issue by r7l** [paul-gauthier/aider#873]
It would be helpful to have a configuration option for Openrouter API key, like we have it for OpenAI and Anthropic. Currently it is only possible to use an ENV variable which is not always working well.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/config/dotenv.html

**Comment by r7l** [comment]
I've tested this with the most recent version and got this error: `aider: error: unrecognized arguments: --openrouter-api-key=sk...`.

I don't see any option for it mentioned in the docs in either .env or YAML config. I only see it mentioned here as an environment variable: https://aider.chat/docs/llms/openrouter.html

**Comment by nevercast** [comment]
You should create a `.env` file next to where you launch aider, or at the Git root. 

This file should have the following line.

```ini

OPENROUTER_API_KEY=sk-...

```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by paul-gauthier** [comment]
FYI, newer versions support `--api-key` like this:

```
aider --api-key openrouter=<key>
```

**Comment by jrouquie** [comment]
And it also works in the config file ~/.aider.conf.yml :

`api-key: openrouter=sk...`

This solves my problem, thanks!

**Comment by rpgdev** [comment]
> I have it set in YAML config. and tested this with the most recent version and got this error: `aider: error: unrecognized arguments: --openrouter-api-key=sk...`.
> 
> I don't see any option for it mentioned in the docs in either .env or YAML config. I only see it mentioned here as an environment variable: https://aider.chat/docs/llms/openrouter.html

This is still the case, openrouter variables aren't present in the reference .env file.

**Comment by mrienstra** [comment]
Docs are still a bit confusing on this front. For someone setting up Aider for the first time, who wishes to store their API keys in a sensible fashion, it is easy to miss https://aider.chat/docs/config/api-keys.html#other-api-providers which shows:

```yml
api-key:
- gemini=foo      # Sets env var GEMINI_API_KEY=foo
- openrouter=bar  # Sets env var OPENROUTER_API_KEY=bar
- deepseek=baz    # Sets env var DEEPSEEK_API_KEY=baz
```

... https://github.com/Aider-AI/aider/pull/3241 partially addresses this.

Hmm, kinda seems like "Settings keys for other providers works a bit differently, see below." can be dropped, and the two sections ("OpenAI and Anthropic" and "Other API providers") can just be merged, as there is no longer any noteworthy difference. Appears they are all treated the same, aside from OpenAI and Anthropic having "special entries" in the yaml config file. Which is a state of affairs which should perhaps be migrated away from, doesn't seem like it provides any value. Already (just tested locally to confirm) OpenAI and Anthropic API keys can be set from within the `api-key` array, and personally I would prefer to have the docs just show that approach. In the future the "special entries" for OpenAI and Anthropic could be deprecated to simplify both codebase & docs.

```yml
api-key:
- anthropic=foo  # env var ANTHROPIC_API_KEY
- deepseek=bar   # env var DEEPSEEK_API_KEY
- gemini=spam    # env var GEMINI_API_KEY
- openai=zork    # env var OPENAI_API_KEY
- openrouter=fum # env var OPENROUTER_API_KEY
```

https://github.com/Aider-AI/aider/blob/8ba29ee/aider/website/assets/sample.aider.conf.yml#L7-L9 says:

```yml
# Note: You can only put OpenAI and Anthropic API keys in the yaml
# config file. Keys for all APIs can be stored in a .env file
# https://aider.chat/docs/config/dotenv.html
```

... which is no longer accurate.

One possible flow for a new user onboarding (I believe this is more or less the route I took twice, on two different computers):

1. https://aider.chat/#getting-started
2. https://aider.chat/docs/install.html
3. https://aider.chat/docs/install/optional.html
4. https://aider.chat/docs/config/api-keys.html
5. https://aider.chat/docs/config/aider_conf.html
6. https://github.com/Aider-AI/aider/blob/main/aider/website/assets/sample.aider.conf.yml
