### ISSUE TITLE
how can i change the smmary model？

### ISSUE THREAD

**Issue by hhn12138** [paul-gauthier/aider#875]
### Issue

when i use aider 
get a error：ummarizer unexpectedly failed for gpt-3.5-turbo
what is the problem
how can i change the smmary model

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use `--weak-model`.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
