### ISSUE TITLE
Adding a file immediately prompts for changes?

### ISSUE THREAD

**Issue by Gabriel-p** [paul-gauthier/aider#877]
### Issue

I'm testing the free `openrouter/meta-llama/llama-3-8b-instruct:free` model. Upon adding a file, `aider` attemps to update it immediately? What does this mean?

```
> aider `arXiv_NN.py`

Here is the updated arXiv_NN.py file:

arXiv_NN.py

 @@ -2,5 +2,6 @@
  from bs4 import BeautifulSoup as BS
      url = "http://arxiv.org/list/" + categ + "/new"
      html = requests.get(url)
      soup = BS(html.content, features="xml")
...
```

### Version and model info

Aider v0.44.0
Model: openrouter/meta-llama/llama-3-8b-instruct:free with whole edit format
Git repo: .git with 4 files
Repo-map: disabled

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

That model is not strong enough to follow aider's system prompt. This doc may be helpful:

https://aider.chat/docs/llms.html#use-a-capable-model

**Comment by Gabriel-p** [comment]
Thank you again!

**Comment by Gabriel-p** [comment]
@paul-gauthier sorry to bother you again, but I'm reading https://aider.chat/docs/leaderboards/ trying to decide on a model to use and I can't understand the benchmark *Percent using correct edit format* for which almost all models are rated with 100%. It is described below as:

> Measures the percent of coding tasks where the LLM complied with the edit format specified in the system prompt. If the LLM makes edit mistakes, aider will give it feedback and ask for a fixed copy of the edit. The best models can reliably conform to the edit format, without making errors.

but I don't really understand what type of test this is. Are there examples anywhere?

**Comment by paul-gauthier** [comment]
It just measures whether the model is able to consistently follow aider's system prompt about how to edit files. Numbers close to 100% are good.

**Comment by rodgermoore** [comment]
Is there another way of preventing (or stopping) the LLM to immediately take action after a file is added to the chat? As soon as there is some chat history, Claude 3.5 Sonnet seems to be quite aggressive on making unwanted changes.

**Comment by Gabriel-p** [comment]
Had the same thing happen yesterday using Gemini 1.5: added a file and midway through it failed complaining about some changes I never requested
