### ISSUE TITLE
Feature request: Allow the LLM to add files in response to prompting

### ISSUE THREAD

**Issue by owenwp** [paul-gauthier/aider#880]
### Issue

It would be great if Aider could take my prompt and use the repo map (and any docs I choose to add as context) to decide which files it needs to add in order to execute my instructions, only for that specific commit. This would also be great for asking questions about an existing codebase, or fixing bugs without prior knowledge of which code paths are active. These auto-added files could be removed for followup prompts, since the diffs are still in the chat history and should help the LLM re-add those files if they are truly relevant, to prevent continuous growth of added files.

**Comment by jluyckx** [comment]
This all already works ! There's a flag to "auto-answer" yes, and if you use the web UI all of this is the default (as in, it loads file automatically). Maybe try to it out a bit more, you'll see all of this is fine.

**Comment by owenwp** [comment]
Oh, that's great. It wasn't too clear from the docs, especially with all the examples showing it operate on just one or two manually added files at a time.
