### ISSUE TITLE
LiteLLM:ERROR

### ISSUE THREAD

**Issue by Asheart** [paul-gauthier/aider#883]
### Issue

I alwais have this error :

LiteLLM:ERROR: litellm_logging.py:1274 - Model=deepseek-coder-v2 not found in completion cost map. Setting 'response_cost' to None

anyone know how to fix it?

### Version and model info

aider --model ollama/deepseek-coder-v2
Model ollama/deepseek-coder-v2: Unknown context window size and costs, using sane defaults.
For more info, see: https://aider.chat/docs/llms/warnings.html

Aider v0.44.0
Model: ollama/deepseek-coder-v2 with whole edit format
Git repo: .git with 9 files
Repo-map: disabled
VSCode terminal detected, pretty output has been disabled.
Use /help <question> for help, run "aider --help" to see cmd line args

I use the 16b, 8.9 model version of deepseek-coder-v2

**Comment by nevercast** [comment]
Related to #874

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This error message is a warning, and can be safely ignored.

I've opened an issue with litellm to see if aider can suppress it.

https://github.com/BerriAI/litellm/issues/4818

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by oatmealm** [comment]
I'm seeing it as well. But I'm asking ollma directly not via litellm, unless that's aider in fact works? Does it use litell to abstract endpoints?

**Comment by nevercast** [comment]
> I'm seeing it as well. But I'm asking ollma directly not via litellm, unless that's aider in fact works? Does it use litell to abstract endpoints?

Hi there,

Yes aider uses litellm as a common interface for connecting to LLMs 

This issue should be resolved, please update Aider and see if you're still affected.
