### ISSUE TITLE
Custom provider

### ISSUE THREAD

**Issue by Batyan45** [paul-gauthier/aider#890]
### Issue

I have an ISP that provides access to Claude via openai interfaces. Here are the contents of my .aider.models.json file:

```
{
    "claude-3-5-sonnet-20240620": {
        "max_tokens": 4096,
        "max_input_tokens": 200000,
        "max_output_tokens": 4096,
        "input_cost_per_token": 0.000003,
        "output_cost_per_token": 0.000015,
        "litellm_provider": "openai",
        "mode": "chat",
        "supports_function_calling": true,
        "supports_vision": true,
        "tool_use_system_prompt_tokens": 159
    }
}
```

But when I try to connect with the command
`aider --model openai/claude-3-5-sonnet-20240620` I got:

```
Model openai/claude-3-5-sonnet-20240620: Unknown context window size and costs, using sane defaults.
Did you mean one of these?
- openai/claude-3-5-sonnet-20240620
- openai/claude-3-5-sonnet-20240620
- openai/claude-3-5-sonnet-20240620
```

Am I doing something wrong?

### Version and model info

Aider v0.45.1
Model: openai/claude-3-5-sonnet-20240620 with diff edit format
Git repo: .git with 0 files
Repo-map: using 2048 tokens

**Comment by r7l** [comment]
It seems like the filename is wrong. I had a similar issue once. You may have to check this page in the docs:

https://aider.chat/docs/config/adv-model-settings.html

You can either set the file in config or use the expected name `.aider.model.metadata.json`.

**Comment by Batyan45** [comment]
> It seems like the filename is wrong. I had a similar issue once. You may have to check this page in the docs:
> 
> https://aider.chat/docs/config/adv-model-settings.html
> 
> You can either set the file in config or use the expected name `.aider.model.metadata.json`.

Thanks, this works :)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
