### ISSUE TITLE
Add cuda support for /help function

### ISSUE THREAD

**Issue by rodgermoore** [paul-gauthier/aider#891]
### Issue

# Add cuda support for /help function
Hi, great fan of Aider, its amaizing 😉 My home computer is kind of old, at least the cpu is. I have a 3060TI which is fine for smaller cuda jobs like creating embeddings on-the-fly. The Aider /help function only has cpu suppot right? Would be great if cuda is supported!

### Version and model info

# aider 0.45.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Installing cuda support uses a lot of disk space in some environments, so it's disable by default. You can install aider with `pip install aider-chat[help]` to include cuda. You will need to do the install in a clean environment, or the non-cuda install will just remain in place.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
