### ISSUE TITLE
token limits issue

### ISSUE THREAD

**Issue by YukoOshima** [paul-gauthier/aider#892]
### Issue

I use the azure gpt module and it always report the token limit issue. but I think there's still much room for the token.

```
Model azure/gpt-4o-2024-05-13 has hit a token limit!
Token counts below are approximate.

Input tokens: ~7,453 of 128,000
Output tokens: ~987 of 4,096
Total tokens: ~8,440 of 128,000

For more info: https://aider.chat/docs/troubleshooting/token-limits.html
```

**Comment by randoentity** [comment]
I run into this too with local models. To get around this I've removed the exhausted flag condition block here: https://github.com/paul-gauthier/aider/blob/b7eaa0fe7c6f904a1d8e70c5e714410043a312e6/aider/coders/base_coder.py#L874

A better approach would be to set the can_prefill for the specific model you're using in models.py and submit a PR for it. 

FWIW, I don't know what pre-filling is. Ideally we would query the model or provider if the model can indeed prefill, but as Paul hasn't done that I assume it isn't straight forward or possible.

**Comment by mr-september** [comment]
I'm seeing a related, possibly the same issue running Llama 3.1 from novita.ai which theoretically has 128k tokens.

```
Model openai/meta-llama/llama-3.1-70b-instruct has hit a token limit!
Token counts below are approximate.

Input tokens: ~9,707 of 0 -- possibly exhausted context window!
Output tokens: ~0 of 0 -- possibly exceeded output limit!
Total tokens: ~9,707 of 0 -- possibly exhausted context window!

To reduce output tokens:
- Ask for smaller changes in each request.
- Break your code into smaller source files.

To reduce input tokens:
- Use /tokens to see token usage.
- Use /drop to remove unneeded files from the chat session.
- Use /clear to clear the chat history.
- Break your code into smaller source files.

For more info: https://aider.chat/docs/troubleshooting/token-limits.html
```

**Comment by paul-gauthier** [comment]
Aider relies on the [litellm metadata file](https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json) for token limits and costs. You can submit a PR there if you find a model that needs updated info.

Or you can locally override:

https://aider.chat/docs/config/adv-model-settings.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
