### ISSUE TITLE
is there any request for system messages token ?

### ISSUE THREAD

**Issue by tuanlv14** [paul-gauthier/aider#893]
### Issue

I saw system messages token  always required each time I started aider. Is this required or not ? It will be counted into input token or output token ? 

![image](https://github.com/user-attachments/assets/670177f5-3acd-45cc-b481-21365cdc87a9)

### Version and model info

Aider v.0.44.0

**Comment by jginstitute** [comment]
Everything returned by the `/tokens` command counts as input tokens. Aider can't predict the number of tokens that will be returned in advance. Whatever is returned is added to the chat history, affecting the input token count for your next prompt (unless you `/clear` your chat history).

System messages are crucial as they provide the language model with general instructions on how to handle the chat history, added files, repository map, and your current prompt. These messages also specify the response format that Aider expects (e.g., diff, whole, etc.). So, to answer your question: yes, system messages are absolutely required.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Yes, the system messages are critical and required. They are how aider works with the LLM to edit code.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
