### ISSUE TITLE
Custom System Prompts

### ISSUE THREAD

**Issue by yahia-wk** [paul-gauthier/aider#895]
### Issue

Is there a way to to pass custom system prompts for a Coder object in the aider library, this will be useful for defining multiple agents with different personalities/style

**Comment by zenturacp** [comment]
Is this what you mean?

https://aider.chat/docs/faq.html#can-i-change-the-system-prompts-that-aider-uses

It is possible to change the system prompts there  - for now that's what to do i think

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
