### ISSUE TITLE
fireworks/models/deepseek-coder-v2-lite-instruct configuration

### ISSUE THREAD

**Issue by tuanlv14** [paul-gauthier/aider#897]
### Issue

I used:
FIREWORKS_AI_API_KEY = "mykey"     // in .env file
And I config .aider.model.metadata.json as bellow:
```
"fireworks_ai/deepseek-coder-v2-instruct": {
        "max_tokens": 65536,
        "max_input_tokens": 65536,
        "max_output_tokens": 8192,
        "input_cost_per_token": 0.0000012, 
        "output_cost_per_token": 0.0000012,
        "litellm_provider": "fireworks_ai", 
        "mode": "chat",
        "supports_function_calling": true,
        "source": "https://fireworks.ai/pricing"
    }
```
Then I try to call aider with:
```
aider --model fireworks_ai/accounts/fireworks/models/deepseek-coder-v2-instruct
aider --model fireworks_ai/deepseek-coder-v2-instruct
aider --model fireworks_ai/fireworks_ai/deepseek-coder-v2-instruct
aider --model openai/fireworks_ai/deepseek-coder-v2-instruct
```
But no option had worked for me. It gave me the llm proxy error. Is there anyone can help me to fix?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, what is the error message or specific problem you are having?

When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
