### ISSUE TITLE
Can no longer /add files not part of the original repo

### ISSUE THREAD

**Issue by cranyy** [paul-gauthier/aider#90]
Hello,

Firstly let me start by saying what you've made here is really truly magical. It has some issues here and there, but wow - this is really head and shoulders above other openai based coding assistants, and I cant wait to see how far it can go in the future. 

My issue after pulling the latest version today is as follows: {please note i am very much a beginner at coding)
Last week i could /add all files that were inside of the repo folder, which was great as i had created my test/ folder and filled it with different projects, all of which could be selected from the /add function. 

As of now, I can no longer do that, using /ls lists only the aider repo files, and i have to manually add and commit my files to add them to the chat. 

I dont know if this was intended or if I am doing something wrong.

**Comment by paul-gauthier** [comment]
Thanks for very nice comments about aider and for reporting this issue.

The latest release (v0.8.3) assumes that you want all the files you work on with aider to be part of git. This is mainly to ensure the safety of your files' contents. GPT can sometimes make (huge) mistakes when you ask it to edit a file, to the point of deleting most of a file's content, etc. This isn't super common, but it happens. Making sure the files are in git means it's always easy to undo a GPT mistake (big or small).

If you prefer to operate without using git, you can run aider with `--no-git`.

I am curious to get your thoughts about this change. I don't want aider to use git by default if that causes some problem for people that I didn't anticipate.

**Comment by paul-gauthier** [comment]
I recently added a FAQ entry about aider's use of git. This might be helpful:
https://aider.chat/docs/faq.html#how-does-aider-use-git

I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by cranyy** [comment]
Hello again, I just retested the new version and thank for fixing the issue with /add. From my laymans perspective the commit issues seems to be much better now when you have the option of no commit and now that it rarely if ever does the "your existing code" commit. 
My only concern (and i dont even know if this is the case) is that when it writes the "ORIGINAL" it wastes tokens, especially if its a particularly long function or class.

Perhaps, an alternative solution, which I am sure you've thought of already, but just in case, could be to just create copies of the files, if possible, then make as many commits there as you want, this way you can get the best of both worlds.

Concerning the new 0.10.1 version currently i am encountering the following problems, which might be similar to the current ticket, so I felt like it would be better to post them here, rather than open a new one. 

1. When trying to  /drop files it gives me this error, even though they have been added in the chat successfully. I have to do /drop without specifying the file and then readd it:
 ----
![aider](https://github.com/paul-gauthier/aider/assets/128929586/b41875f2-516b-4cf4-99e4-741a3417227d)

----
Is there something wrong I am doing here?


2. This is almost certainly a me issue here - but in windows cmd/powershell i can no longer copy/paste inside once I've run aider and have to manually rewrite errors if they occur.  


3. This is more of a newbie question than an issue - I've managed to get c-tags going by adding the path to env, but i dont really understand how to use it correctly, and all i see is it taking up 1024 tokens, and still not being able to figure out if lets say i add 2 files to the chat, and exclude a 3rd (main.py), it still doesnt exactly know what functions are carried out in the main.py. I am pretty certain this is just due to my lack of understanding of the process, so any guide/info here would be greatly appreciated, as my current project is waaaaay over the 8k limit so any option to manage that would be of huge value. 

Again, thank you for this product, I cannot express enough how freaking amazing it is, especially to a total beginner such as myself.

**Comment by LumenYoung** [comment]
Hi, sorry to comment on this closed issue. Yet I find it not good to 1) let arbitrary file been edited by aider that is not track 2) block all the file from being added to aider.

It is actually important cause sometimes you have a example data/config that you don't want to add to the repo yet you want to provide this information to aider as context. This is very common at least in my workflow that I need paste this into the chat which is really not ideal, **I would say adding external file is important even we are using git for tracking**.

Therefore I would like to ask if we can either add 1) read only file with command like `/read` to allow aider read yet not modify the file or 2) a seperate command to add external file `/add-external` that is no different from add except people wont accidentally add file to aider without noticing its not version controlled.

BTW, this is such a great piece of software that fulfill almost every need I want to work with AI in the terminal. Thanks @paul-gauthier !

**Comment by raine** [comment]
Even if you disable `git` option, `/add` should be able to autocomplete files in your directory.

I really don't need aider to be git aware. I stage and commit its changes myself.
