### ISSUE TITLE
Issue with creating files when using Ollama/Deepseekcoder V2 in Aider

### ISSUE THREAD

**Issue by saleham5** [paul-gauthier/aider#900]
## Issue with Ollama/Deepseekcoder V2 in Aider

I tried using Aider with Gemini, and it works fine with no issues at all. However, when I tried it with Ollama/Deepseekcoder V2, it didn't work well.

### Issues Encountered

1. **Incorrect File Path Creation**:
   - When I assign tasks to create something, after writing the code, it always asks to create the file under the wrong path. For example:
     ```plaintext
     Allow creation of new file path/to/create_video.py? (y) it adds the path/to/ for some reason.
     ```
   - We can ignore this, and it does create the file anyway, but it's still an inconvenience.

2. **Confusion with Code Content**:
   - The main issue that makes the whole thing unusable is when it tries to create files with incorrect commands. For example:
     ```plaintext
     Allow creation of new file create_video('path/to/audio_file.wav', 'output_video.mp4')? y
     ```
   - This is not even a file that should be created. It seems to get confused by elements within the code and tries to apply them incorrectly later.

### Steps to Reproduce

1. Use Aider with Ollama/Deepseekcoder V2.
2. Assign a task to create a new file.
3. Observe the incorrect file path prompts and attempts to create files with code commands.

### Expected Behavior

- The tool should correctly identify the paths and files to be created without getting confused by the content of the code.

### Environment

- Aider version: v0.45.0
- Operating System: Ubunut

### Environment

- Aider version: v0.45.0
- Operating System: Ubunut

**Comment by paul-gauthier** [comment]
The ollama page shows `quantization Q4_0`, so I think it's been quantized?

https://ollama.com/library/deepseek-coder-v2

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by josx** [comment]
I am using, the same model as above ollama/deepseek-coder-v2 and i got the following

```
The LLM did not conform to the edit format.
https://aider.chat/docs/troubleshooting/edit-errors.html

No filename provided before ``` in file listing
```

Why is this happening? can i help to solve it?

**Comment by josx** [comment]
As @paul-gauthier recommends I have downloaded deepseek not quantized. 
This one https://ollama.com/library/deepseek-coder-v2:16b-lite-base-fp16 

I am not having the above errors, but not so usefull yet (some weird dialogues like "Ok, any changes I propose will be to those files", "I switched the greeting text from "Hello" to "Hey")
