### ISSUE TITLE
[Feature Request] openai / claude charges per input ant output token. possible to "minify" input and output after sending and prompt it for "compressed form?" 

### ISSUE THREAD

**Issue by sprappcom** [paul-gauthier/aider#906]
### Issue

to further save costs, possible to provide a feature where compression / minification is done?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, that's not really possible.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
