### ISSUE TITLE
[Feature] Add apply-formatting command

### ISSUE THREAD

**Issue by rodion-m** [paul-gauthier/aider#907]
It would be great if aider could automatically apply formatting sources after edits. Now, to achieve this, you have to extend the test-cmd command `npx @biomejs/biome format --write ./src && npm run build` (which can slow down the processing).

Proposal format:
```yml
apply-formatting-cmd: "@biomejs/biome format --write " # after `--write ` aider should put updated files list
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

There are many possible tools/checks that you might want aider to do. Aider has hooks for 2 types:

1. Per-file checks to run after a file is edited with with `--lint-cmd`
2. Repo-wide checks to run after edits with the `--test-cmd`

It's up to each user to wrap their checks/tools/etc into one of these steps. A shell script is a good way to do that.

https://aider.chat/docs/usage/lint-test.html

**Comment by rodion-m** [comment]
Absolutely, Paul. I'm aware that we only have `--lint-cmd` and `--test-cmd`, but not all linters support code formatting. It might be a good idea to listen to Aider's users before we close this issue and make a decision about this feature's usefulness. What do you think?

**Comment by paul-gauthier** [comment]
I am suggesting that you overload the lint command with a shell script like:

```
#!/bin/sh

format-command $*
lint-command $*
any-other-per-file-command $*
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
