### ISSUE TITLE
ctags error

### ISSUE THREAD

**Issue by bsoung** [paul-gauthier/aider#91]
Running into a problem and not sure if anyone's encountered it before while experimenting with ctags. Installed ctags with brew.

`Repo-map: basic using 1024 tokens (error running universal-ctags: Command 
'['ctags', '--version']' returned non-zero exit status 1.)`

Getting `illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...`

When running `ctags --version`. Seems to break the repo map of course. Has anyone seen this?

**Comment by joshuavial** [comment]
I haven't seen it before - what do you see when you type `ctags --version` in the terminal?

**Comment by joshuavial** [comment]
sounds like your install of ctags is the issue, it may be there are two versions floating around. I had to delete the default version of ctags (exuberant) on ubuntu before the universal-ctags would kick in.

`type -a ctags` should show you all the places ctags is installed and `which ctags` should show you the one that is being called.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to re-open or file a new issue if you have any further problems.
