### ISSUE TITLE
Model openrouter/openai/gpt-4o-mini: Unknown [..]

### ISSUE THREAD

**Issue by powellnorma** [paul-gauthier/aider#917]
### Issue

```
$ aider --model openrouter/openai/gpt-4o-mini
Model openrouter/openai/gpt-4o-mini: Unknown context window size and costs, using sane defaults.
Did you mean one of these?
- openrouter/openai/gpt-4o-mini
- openrouter/openai/gpt-4o-mini
For more info, see: https://aider.chat/docs/llms/warnings.html
```

### Version and model info

aider 0.45.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/config/adv-model-settings.html

**Comment by powellnorma** [comment]
What I find confusing is this:
```
Did you mean one of these?
- openrouter/openai/gpt-4o-mini
- openrouter/openai/gpt-4o-mini
```

Because that's exactly the model I gave it. It sounds as if there already are pre-settings for this model, but its not using them for some reason.

Isn't it supposed to use the same pre-settings as for `openai/gpt-4o-mini` (without openrouter)?

**Comment by paul-gauthier** [comment]
Ah, yes! You are right, there was a bug which I have fixed. It was listing the input model for every entry in the did-you-mean list, rather than the actual models found in the database.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by powellnorma** [comment]
Ok, now it says:

```
Did you mean one of these?
- openrouter/openai/gpt-4
- openrouter/openai/gpt-4o
```

Would be great if we could add `openrouter/openai/gpt-4o-mini` as preset as well, thank you! :)

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
