### ISSUE TITLE
Feature Request: Ability to Exclude Specific Folders or Files from ctags/context map

### ISSUE THREAD

**Issue by MohHeader** [paul-gauthier/aider#92]
Hello,

I am super excited about what is been doing here, and yeah this is the first production-ready AI coder I can use with my projects.

Super THANKS ^_^

Although I think the roadmap is more towards an automated context mapping, but giving some manual control until then could be a great option.

(And of course the following is created by GPT)

An enhancement to the current mechanism by which aider uses ctags to create the context map.

Currently, it maps all the files in the repository, but there are certain instances where some directories or files may not be necessary or might contain low-priority vendor code or other frameworks. In such cases, it would be beneficial to manually  exclude these folders or files from the map.

## Feature Description:

Adding a feature that allows users to specify directories or files to be excluded from the mapping process. This could be implemented in the form of a configuration setting or command line argument where users can provide a list of directories or files to be ignored.

## Benefit:

This feature would enable users to better control the mapping process and manage the context that GPT-4 operates in. Ignoring less relevant folders or files would not only speed up the mapping process, but also provide more space for the more relevant and important context.

**Comment by joshuavial** [comment]
I gave this a bit of a look and found that aider won't listen to [exclusions in a ctags options file](https://docs.ctags.io/en/latest/option-file.html). I tried setting up options files in my project directory and home directory which worked fine when calling ctags over the command line but aider would still entries of them into the cache db. I noticed that aider was using absolute paths to the files so tried exclusion patterns for relative and absolute paths (and also *.py) but it still made an entry for each file.

I'm guessing that the repomap logic would need updating to honour the options files.

**Comment by alexanderkjeldaas** [comment]
Vaguely related, it seems like the file completion in aider is limited in the number of files it handles.  If exclusions are required to make it work better, it would be good.

Another option would be for aider to automatically exclude everything outside the current directory if started in a subdirectory of the repository.  This can be useful when working in larger repos, for example a monorepo.

**Comment by paul-gauthier** [comment]
Can you help me understand what you mean when you say that file completions are limited? It would be great if you could include a screenshot or a snippet of output that illustrates the problem you're trying to describe.

**Comment by paul-gauthier** [comment]
I am reluctant to build more "manual" controls for telling aider which parts of the repo to pay attention to. The goal of the repo map, ctags, etc is to let aider figure this out as much as possible. I'm working on a number of extensions to this approach as well. I'd rather focus on reducing the need for manual direction wrt the codebse, versus building (and debugging, supporting) more manual controls.

I'm going to close this issue for now, but feel free to re-open or file a new issue any time.

**Comment by quaternion7** [comment]
IMHO is very unlikely that a 100% automatic solution will work for every project/environment. 
I work on many monorepos that have tons of files that not always relevant, are minified or cache related.
Considering on how important is to keep the map/context concise (also to avoid higher input costs), being able to set a list of file patterns to include/exclude in the project .env would be perfect.
Also to make it not completely dependent on git (but rather use it as an extra filter for modifiable files), would help me a lot with legacy SVN based repos for example.

**Comment by rubin55** [comment]
I ran into this issue because Repo-Map seems to not like a specific path in our repository: 

    Repo-map can't include wallet_core/gba_hc_converter/resources
    Has it been deleted from the file system but not from git?

I wanted to figure out why, because this folder exists normally on my filesystem; Then I figured, maybe I can tell Repo-Map to ignore it, but reading this issue, I don't think that would work (or can I ignore it using `.aiderignore` - I've tried that but the above error message keeps showing up in chat, right before the model answers)

How can I figure out why Repo-Map gives me this error?
