### ISSUE TITLE
Consider not pinning requirements in for published package

### ISSUE THREAD

**Issue by philipp-eisen** [paul-gauthier/aider#920]
### Issue

Currently the requirements in setup.py are read from the pip compiled requirements.txt. See: https://github.com/paul-gauthier/aider/blob/main/setup.py#L15

This makes it hard to use the aider package in an environment where you also want to install other packages, because the hard restrictions of this package contradict the ones of other packages.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/install/pipx.html

**Comment by philipp-eisen** [comment]
Hm, I was trying to use aider not as a CLI, but rather as a package and use it programmatically. In that case the pipx solution wouldn't help unfortunately.

https://github.com/paul-gauthier/aider/pull/921

**Comment by paul-gauthier** [comment]
Sorry, as I mentioned in the PR it's not possible to publish aider without pinned requirements. They are needed to ensure proper installation and operation.

For your case, I would suggest that you don't install aider using the provided setup.py and requirements.txt. But rather you can customize the req.txt file to be compatible with your other deps.

**Comment by philipp-eisen** [comment]
I see -- I suppose I'm not trying to use aider in the main way it's meant to be used (as a CLI). Generally I would say though that for published packages a hard pin is not ideal. 

See for example: https://discuss.python.org/t/should-i-be-pinning-my-dependencies/13159. And the ranges of versions should be defined as you already do in the requirements.in. 

But I see that if your main intended use is as a CLI defining ranges instead of pinning may add some extra maintenance effort that you don't want to support.

**Comment by paul-gauthier** [comment]
Yes, that's correct. Aider is primarily packaged to be used as a CLI tool for end users. As such, it's very helpful to be sure that it's being installed with known package versions that have been tested and are used by all users.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by philipp-eisen** [comment]
All good 👍 . I definitely think though that integrating aider within applications is a super nice use case and for that it would be nice to have more friendly requirements.
