### ISSUE TITLE
when aider need to add code，it will replace the code whitch shoud not be replaced

### ISSUE THREAD

**Issue by hhn12138** [paul-gauthier/aider#923]
### Issue

When the model needs to add code to a file, there are times when it inadvertently overwrites existing code that does not require modification. How should this issue be addressed?

for example：
to add code2 

it should be：
search

code1

======

code1

code2

replace

but aider ：

search

code1

======

code2

replace

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
