### ISSUE TITLE
Feature Request: Novita AI

### ISSUE THREAD

**Issue by mr-september** [paul-gauthier/aider#924]
### Issue

https://novita.ai

Just another API provider like Together AI or OpenRouter, but with cheaper prices (for now?).

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/llms/openai-compat.html

Looks like you would want to set `OPENAI_API_BASE=https://api.novita.ai/v3/openai`

**Comment by mr-september** [comment]
Thanks, that works perfectly (although the outputs/interactions are a bit wonky, those are probably different issues). For future Googlers, this was what worked for me on Windows VS Code (mostly underscores to hyphens)
```
python -m aider.main --model openai/meta-llama/llama-3.1-70b-instruct --browser --openai-api-base "https://api.novita.ai/v3/openai" --openai-api-key "6f***56"
```
