### ISSUE TITLE
Deepseek API UPDATE (Added 128k context, 8k output, assistant prefix)

### ISSUE THREAD

**Issue by NeuralAIM** [paul-gauthier/aider#925]
### Issue

![image](https://github.com/user-attachments/assets/2c56feb1-3f5c-4ed1-af02-e8963105aa8a)
**deepseek API has 128k context, but displays only 32k**
![image](https://github.com/user-attachments/assets/05dd0eca-ee30-452e-ae71-1bd9c5874382)

### Version and model info

PS> aider --model openrouter/deepseek/deepseek-coder
Aider v0.45.2-dev
Model: openrouter/deepseek/deepseek-coder with diff edit format

**Comment by NeuralAIM** [comment]
![image](https://github.com/user-attachments/assets/af52513f-81fe-433a-830c-960bbed766d9)

https://github.com/paul-gauthier/aider/issues/705#issuecomment-2195777748, Why is there no auto-continue for other models?

**Comment by nevercast** [comment]
> Why is there no auto-continue for other models?

Because Anthropic provides prefill of assistant responses, so the output can be resumed. https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/prefill-claudes-response

**Comment by NeuralAIM** [comment]
> > Why is there no auto-continue for other models?
> 
> Because Anthropic provides prefill of assistant responses, so the output can be resumed. https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/prefill-claudes-response

This does not prevent from implementing such functionality with the help of a prompt.

**Comment by NeuralAIM** [comment]
> > Why is there no auto-continue for other models?
> 
> Because Anthropic provides prefill of assistant responses, so the output can be resumed. https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/prefill-claudes-response

Added: https://platform.deepseek.com/api-docs/news/news0725

**Comment by paul-gauthier** [comment]
Aider relies on the [litellm metadata file](https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json) for token limits and costs. You can submit a PR there if you find a model that needs updated info.

Or you can locally override:

https://aider.chat/docs/config/adv-model-settings.html

**Comment by paul-gauthier** [comment]
I have an open issue with litellm to support prefill/prefix for non-Anthropic models. This would be the preferred way for aider to support deepseek's new prefill.

https://github.com/BerriAI/litellm/issues/4881

**Comment by NeuralAIM** [comment]
**DeepSeek API introduces Context Caching on Disk**
![image](https://github.com/user-attachments/assets/a171dd56-0b75-4d22-a028-8f7d7c7539f6)
![image](https://github.com/user-attachments/assets/201a31a2-2a13-42cf-bc4c-b8b467cff9c7)


https://platform.deepseek.com/api-docs/news/news0802/

**Comment by NeuralAIM** [comment]
> The main branch has 3 new features which I think solve this issue:
> 
> * Infinite output for DeepSeek Coder, Mistral models in addition to Anthropic's models.
> * New `--deepseek` switch to use DeepSeek Coder.
> * DeepSeek Coder uses 8k token output.
> 
> The change is available in the main branch. You can get it by installing the latest version from github:
> 
> ```
> python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
> ```
> 
> If you have a chance to try it, let me know if it works well for you.

I'm using an open router and it doesn't have infinite output and 128k context:
![image](https://github.com/user-attachments/assets/5e17950e-41be-441c-a9ab-9dbb85b4fbf7)

**Comment by paul-gauthier** [comment]
Unfortunately, it doesn't look like openrouter supports prefill for the deepseek models.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
