### ISSUE TITLE
Are we getting llama 3.1 405b 

### ISSUE THREAD

**Issue by Yona544** [paul-gauthier/aider#927]
[https://ai.meta.com/blog/meta-llama-3-1/](https://ai.meta.com/blog/meta-llama-3-1/)
maybe instead of haiku for the planning stage cheaper modal

**Comment by PierrunoYT** [comment]
You can use it with OpenRouter

**Comment by apcameron** [comment]
Its available on GROQ but aider does not see it yet.
https://console.groq.com/docs/models

**Comment by Kreijstal** [comment]
https://www.youtube.com/watch?v=DJq51H6umgU
Did claude get also dumber on aider?

**Comment by oloho** [comment]
There a token limit of 32k using openrouer

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
