### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 106: character maps to <undefined>

### ISSUE THREAD

**Issue by PierrunoYT** [paul-gauthier/aider#928]
### Issue

![grafik](https://github.com/user-attachments/assets/7e5c3ba1-2cbc-4d05-ae06-7f4f820d8dcf)

### Version and model info

C:\Users\pierr\Picarta Bot\New Fix 23.06.2024 - Kopie>aider --model openrouter/anthropic/claude-3.5-sonnet
Loaded C:\Users\pierr\Picarta Bot\New Fix 23.06.2024 - Kopie\.env
No git repo found, create one to track GPT's changes (recommended)? y
Git repository created in the current working directory.
Added .aider* to .gitignore
Aider v0.45.1
Models: openrouter/anthropic/claude-3.5-sonnet with diff edit format, weak model
openrouter/anthropic/claude-3-haiku-20240307
Git repo: .git with 0 files
Repo-map: using 1024 tokens
Use /help <question> for help, run "aider --help" to see cmd line args

**Comment by paul-gauthier** [comment]
This should be fixed now. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by PierrunoYT** [comment]
Nice thx

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
