### ISSUE TITLE
Surprising and annoying first-use experience

### ISSUE THREAD

**Issue by jazoom** [paul-gauthier/aider#932]
### Issue

I just ran Aider via Docker. It's the first time I've run it. I was following the docs.

The first command I ran was `/add`. I chose a file.

I was asked `Add these files to the chat? y`

As soon as I hit `enter` Aider started doing a bunch of stuff I didn't ask it to do, then committed it to my git. Very surprising and annoying. It committed some things I had staged already, then committed some new changes. It was very annoying to unpick it all.

I suggest that autocommit of true is a horrible default.

Also, I assume it's a bug that it started to do this immediately after me adding a file. I didn't give it any commands:

```
src/lib/auth.ts
Add these files to the chat? y
To refactor the loginUser and createUser functions in src/lib/auth.ts to use math.factorial, we need to:                                  

 1 Import the math module.                                                                                                                
 2 Replace the existing factorial calculation with math.factorial.                                                                        

Here are the SEARCH/REPLACE blocks:  

... blocks redacted

Please confirm if userData has a property that should be used for the factorial calculation, or provide more details if needed.           


Committing src/lib/auth.ts before applying edits.
Commit 7d589b9 Added authentication functions for user login and creation in auth.ts.
Applied edit to src/lib/auth.ts
Commit c81f760 Added factorial calculation using `math.factorial` in the `createUser` function.
```

There was no interaction with me for any of that.

**Comment by jazoom** [comment]
Okay I think I found out why it might have started doing things. I thought I had to press `enter` after writing `/add`, then I put in the file name. It autocompleted the file name so I assumed it was all going as expected. I then hit `enter` with the file name there. I have no idea where 'factorial' came from since that word doesn't feature in any of the files.

So it wasn't clear how /add was supposed to work. Still a poor default to have it commit, IMHO.

**Comment by jazoom** [comment]
That aside, this seems like an awesome library. Thank you for providing it. I look forward to testing it out some more.

**Comment by Emasoft** [comment]
Many (including me) already asked to make Aider ask the user confirmations before applying changes. But no luck until now in convincing @paul-gauthier 🤷‍♂️

**Comment by batmanscode** [comment]
> Many (including me) already asked to make Aider ask the user confirmations before applying changes. But no luck until now in convincing @paul-gauthier 🤷‍♂️

I usually add a "ask before changing" every now and then and use with `--no-git` so I can just undo with ctrl/CMD+z

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/git.html

When reporting problems, it is very helpful if you can provide:

- Aider version
- LLM model you are using
- Any stack traces or error messages
- A description of what you were doing when the error happened. 

Including the “announcement” lines that aider prints at startup is an easy way to share some of this helpful info.

```
Aider v0.37.1-dev
Models: gpt-4o with diff edit format, weak model gpt-3.5-turbo
Git repo: .git with 243 files
Repo-map: using 1024 tokens
```

**Comment by jazoom** [comment]
@paul-gauthier 

Well I've read all the docs now. The point is that as I was new and following through the docs from top to bottom, doing exactly as the docs told me to do, my project got messed up. Requiring knowledge further down in the docs not to mess up your project is a horrible first-use experience, which was my point.

I am actually very surprised the default is to mess with git commits without any user input.

After reading all the docs and trying it a bit more I've decided Aider isn't for me, but I still think it has great potential for those who don't want to use an IDE dedicated to AI assistance.

**Comment by paul-gauthier** [comment]
Sorry to hear you aren't happy with your aider experience.

The git integration is important exactly because it protects your code from being "messed up" by aider. Git provides the ability to easily and completely undo any changes that aider makes. And aider makes this trivial with the `/undo` command in the chat.

All that said, I do have the ability to disable edits without approval in the roadmap. It's being tracked in issue #649. But I expect the default behavior to remain as it is.

**Comment by jazoom** [comment]
I know what git is of course, since Aider requires a git repository.

Maybe you should mention the undo command early in the docs, since I hadn't yet come across it when my repo was messed up. By the time I found it I'd already reversed it all manually.

**Comment by jazoom** [comment]
Probably also a good idea to warn that Aider can and will commit changes already made prior to Aider ever being run. If I knew this I wouldn't have tried it out until I'd committed my current changes that i was working on.

**Comment by NathanSmeltzer** [comment]
@jazoom I had the same issue when starting. 
Setting these environment variables helped:
AIDER_AUTO_COMMITS=False
AIDER_DRY_RUN=True

Then also start your first prompt with something like:
"Ask at least 1 clarifying question to improve with decision making before editing code for this reply and all future replies."

**Comment by paul-gauthier** [comment]
Aider's use of git and the `/undo` command is discussed on the main usage page in the docs:

https://aider.chat/docs/usage.html#making-changes

Which also links to the more detailed docs page about git:

https://aider.chat/docs/git.html

I also just added a hint about `/undo` that is shown in the chat after every commit:

```
...
Applied edit to app.py
Commit 71612b3 Add a Fibonacci endpoint.
You can use /undo to revert and discard the committed changes.
```

So I am trying to ensure this behavior is well documented and visible to users. But your experience makes it clear that I should continue to try and do better at this.

Thank you for taking the time to share you experience. I really appreciate the feedback.

**Comment by jazoom** [comment]
> Aider's use of git and the `/undo` command is discussed on the main usage page in the docs:

Ah. I must have missed that bit on my first reading of that page. My apologies. 

> I also just added a hint about `/undo` that is shown in the chat after every commit:

This likely would have saved me the (minor) headache. It'll certainly save someone in future. 

> Thank you for taking the time to share you experience. I really appreciate the feedback.

No worries. When you know everything about a piece of software it's difficult to view it through the eyes of a first-time user. That's why I made this issue. You may close it if you feel it has been adequately addressed.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
