### ISSUE TITLE
Is there a startup parameter that allows using only the specified env file?

### ISSUE THREAD

**Issue by purelind** [paul-gauthier/aider#936]
### Issue

I referred to the [documentation](https://aider.chat/docs/config/dotenv.html#config-with-env) to configure the env-file because I already had a .env file in the home directory for other purposes. 
<img width="880" alt="image" src="https://github.com/user-attachments/assets/3e6a227d-7263-481b-b637-a58c7487aa92">

So, I created a ~/.aider.env file to store aider's environment configuration, and then executed `aider --env-file ~/.aider.env `to start it.
At this point, I expect aider to only read the file I specified, rather than having to read the ~/.env file (this file is not for aider to use).

<img width="933" alt="image" src="https://github.com/user-attachments/assets/eacc0c40-2c9a-4104-a391-6c21c4deefc7">

### Version and model info

Aider:  v0.45.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider always searches all the listed env locations. If your more general env has settings you don't want in the more specific env, can you just override them?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by purelind** [comment]
Perhaps I didn't express myself clearly. In my local environment, the .env file under the HOME directory is an environment configuration file for other programs, not a general configuration file for aider. Currently, aider will parse all environment configuration files, so when loading $HOME/.env, it will display a warning because the configuration items in this file are for use with zsh and therefore do not conform to aider's configuration specifications.

**Comment by purelind** [comment]
What I hope is that when we specify a configuration file, only that specified file is loaded, rather than continuing to load all the configuration files in the traversal order. In my opinion, this would be a more reasonable configuration file loading behavior.
