### ISSUE TITLE
Plain text diffs without any color.

### ISSUE THREAD

**Issue by adriangalilea** [paul-gauthier/aider#937]
### Issue

Hello, just installed Aider and I can't see colored outputs on the diffs as everyone does:

<img width="246" alt="image" src="https://github.com/user-attachments/assets/978e3ed7-e079-42b0-8b7c-b2196fbaa29d">

However I can do `git diff --color` and get:

<img width="696" alt="image" src="https://github.com/user-attachments/assets/b69beaaa-1f31-425a-81a5-362a953091cb">

My .gitconfig just in case:
```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[user]
	name = adriangalilea
	email = adriangalilea@gmail.com
[core]
    pager = delta

[interactive]
    diffFilter = delta --color-only

[delta]
    navigate = true    # use n and N to move between diff sections

[merge]
    conflictstyle = diff3

[diff]
    colorMoved = default

```

### Version and model info

Aider v0.45.1
Mode:gpt-4o
Usage: Editing a random README.md
Terminal: Kitty, warp
Config diff tool: delta

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Based on the output you've shared, it looks like you are editing files that contain triple-backticks. So aider is using `<source>` to delimit code. In this case, you lose colorized output unfortunately.

**Comment by adriangalilea** [comment]
> Thanks for trying aider and filing this issue.
> 
> Based on the output you've shared, it looks like you are editing files that contain triple-backticks. So aider is using `<source>` to delimit code. In this case, you lose colorized output unfortunately.

Ahhh I see the classic LLM markdown parsing hell :)

Can you go into more details?

Perhaps there's a way to solve this, tho I understand, I faced same issues when parsing llm markdown output to Telegram flavoured Markdown, and these 3 projects implement some solutions:

https://github.com/sudoskys/telegramify-markdown
https://github.com/skoropadas/telegramify-markdown
https://github.com/yym68686/md2tgmd

Just in case you wanna take a look I'm sharing those, even tho they may not be relevant.

**Comment by paul-gauthier** [comment]
I think it's just going to be a corner case where we lose color.

**Comment by adriangalilea** [comment]
That's alright, perhaps include a note on the FAQ?
