### ISSUE TITLE
Request: allow attachment of external files for inclusion in requests

### ISSUE THREAD

**Issue by glinkot** [paul-gauthier/aider#939]
**The issue**

Just like the 'coding conventions' example in the docs, including extra structured context data (aside from the codemaps aider auto generates) is really useful.  That example is static though - there are lots of examples where the extra files must update each request:

- updated screenshots of the webpage, app or whatever.  
- In some tools important info is in binary or weird xml files and won't be in aider's codemap.  eg. I have a Unity script that creates a nice text file of object hierarchy and each object's properties.

Given it's static and must be in git, I'd have to do this each request:

1. Take the screenshot, into project folder (or run dump, whatever)
2. Do a git commit
3. /drop the old image/text file
4. /add the new image/text file. 
5. Make the request

**Proposal**
An '/attach' command ie. '/attach mypropertymap.txt' (or myimage.png)

- Attached files differ from files we /add.  They aren't 'in the project and editable by aider', they are read only, and solely get sent up to the model for context.  This means they don't have to be in git, it's a normal filepath anywhere on my file system.
- They are freshly loaded from the filesystem each time aider does a request.  This lets the user have their own workflow for autoscreenshotting their app, updating their dump files every 10 seconds, etc.

A /detach command would go alongside it, so these reference files can persist through your normal workflow as you separately add and drop 'aider managed' files.

This would be powerful I think!  The /web command may already have implemented much of what's needed - a read only addition to context which aider knows it doesn't edit.  I'm not sure if you can remove things added with /web so perhaps it would become /attachweb to make it clear you can /detach web files too.

Ideally the name of the attached file would go up so you can say in the aider request 'refer to the attached blah.txt file' and the model knows what file name/content that is.

Thanks for listening Paul!

**Comment by glinkot** [comment]
I was starting to try this on unity - in that case I had written a script to lay out the components and property values in the editor - a bit like the context map provided to the model by aider.  That got me thinking a good solution for this would be an '/attach' command ie. '/attach mypropertymap.txt' (or myimage.png)

- Attached files differ from files there due to /add.  They aren't 'in the project to edit', they are read only, and just get sent up to the model for context.  This means they don't have to be in git, it's a normal filepath.
- They are freshly loaded from the filesystem each time aider does a request.  This lets the user have their own methods for autoscreenshotting their app, interface or whatever.  Maybe I set one up to screenshot a region of my screen every 10 seconds for example.  Or for text files, refreshing a log or whatever.

Ideally the name of the attached file would go up so you can say in the aider request 'refer to the attached blah.txt file' and the model knows what file name/content that is.

This would be powerful.  I haven't done lots of tests, but it seems when I send an image of 'this table is formatted wrongly' with a screenshot of its actual appearance, aider/sonnet does a better job of responding.

**Comment by paul-gauthier** [comment]
This is now supported via `/read`.
