### ISSUE TITLE
When using Anthropic on Vertex AI the Haiku model continuously triggers summarization errors after code generation of Sonnet 3.5 

### ISSUE THREAD

**Issue by rodgermoore** [paul-gauthier/aider#940]
## Aider 0.45.1

After a block of code generation the weak Haiku model triggers summarization errors after code generation when using the Anthropic models on Google Vertex AI.

### Error message
```
summarizer unexpectedly failed for vertex_ai/claude-3-haiku@20240307
```

### Aider env settings for the Anthropic model on Vertex.
```
## Specify the model to use for the main chat
AIDER_MODEL=vertex_ai/claude-3-5-sonnet@20240620

## Use claude-3-opus-20240229 model for the main chat
#AIDER_OPUS=

## Use claude-3-5-sonnet-20240620 model for the main chat
# AIDER_SONNET=true
```

Please provide instructions how to follow up, need specific logging?

Thanks

## Addition
[A Google search tells me](https://www.googlecloudcommunity.com/gc/AI-ML/Encountered-429-error-quot-Quota-exceeded-for-online-prediction/m-p/741337) there are quite some people having quota limit problems with the Haiku model on Vertex. I made a rude bypass to set claude-3-5-sonnet-20240620 as a weak model too.

A better solution would be to have a fallback mechanism?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can manually specify whichever weak model you like with `--weak-model`.

**Comment by paul-gauthier** [comment]
The latest release falls back to the main model if the weak model can't make a commit message. So that should help quite a bit here.

**Comment by rodgermoore** [comment]
> Thanks for trying aider and filing this issue.
> 
> You can manually specify whichever weak model you like with `--weak-model`.

Thanks! I guess "RTFM" still applies 😉

**Comment by rodgermoore** [comment]
> The latest release falls back to the main model if the weak model can't make a commit message. So that should help quite a bit here.

```
Aider v0.46.1
Model: vertex_ai/claude-3-5-sonnet@20240620 with diff edit format
```
Still getting:
```
summarizer unexpectedly failed for vertex_ai/claude-3-haiku@20240307
```
Using --weak-model to set Claude 3.5. Thanks for the tip.

**Comment by paul-gauthier** [comment]
I had previously added the strong model fallback just to the commit message generator. I've added it to the chat history summarizer too now, which is the problem you are encountering.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
