### ISSUE TITLE
[Feature] Support adding file read-only.

### ISSUE THREAD

**Issue by MehrCurry** [paul-gauthier/aider#941]
### Issue

I am looking for a way to add files read-only to the context. Let's say I have a requirements document called `requirements.md`. When i have added that to the context I have seen Aider changing the requirements to match the implementation want is normaly not want is intended. Same with predefined testcases. At sometime I would like to mark testcases read-only to make sure Aider changes the code and not the tests ;)

### Version and model info

Aider v0.45.1
Model: openai/aws/claude-3.5-sonnet with diff edit format
Git repo: .git with 18 files
Repo-map: using 1024 tokens

**Comment by Emasoft** [comment]
I agree. Very often the AI only has needs to know the content of a file but it should not be modified. Instead the AI goes and changes everything. It is very annoying reverting the code every time, removing the source file, ask the AI to make the changes again, and then adding the file again to continue developing.

**Comment by MehrCurry** [comment]
Another Use Case: I generated an API Client with the OpenAPI Tools. These files must be part of the context but must not be changed.

**Comment by sholub89** [comment]
Agreed. It would be a very nice feature to differentiate what can be modified and what can't. Currently, all the files added to the context are treated the same and are modifiable.

**Comment by glinkot** [comment]
Agree.  See my detailed suggestion here of an approach that would cover these use cases.

https://github.com/paul-gauthier/aider/issues/939

**Comment by paul-gauthier** [comment]
Main branch now lets you `/read <file>` from anywhere, including outside the repo. The LLM can see it, but not edit it. Also has `--read <file>` on command line and `read: <file>` in the yaml.

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by Ga68** [comment]
this is a great feature! thanks

¿is it intentional that the read-only files are not listed in the "added" files list? I can see it's there if I run a `/tokens` command, but otherwise it's not there.

**Comment by paul-gauthier** [comment]
They are listed in /ls in the main branch. Where else would like like/expect to see them? In the list above the prompt?

**Comment by Ga68** [comment]
that was my intuition. I'm not positive that intuition is the right one, but my mind was at "if it's being sent to [LMM] when I hit enter, then it's in the list of files I'm looking at when I'm writing my instruction".

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by Ga68** [comment]
the lastest version works great! thanks so much.

now that it was there I noticed a behavior which may be worth addressing.

1. file is added in read only mode (either via config or `/read`)
2. I now want to change it to edit mode
3. I type `/add my-file.md`

the unexpected behavior is that it stays in read-only mode, as opposed to my expectation that anything I use `/add` for would be in edit mode.

**Comment by MehrCurry** [comment]
Thank you so much. Great addition.
A small glitch might be that aider keeps asking to add the file but it's still added read-only.

```
api/openapi.yaml
Add these files to the chat? n
```
