### ISSUE TITLE
[FeatReq] Add support for apps and libs that require two console to develop (like Textual)

### ISSUE THREAD

**Issue by Emasoft** [paul-gauthier/aider#944]
### Issue

Certain python apps and libraries require multiple terminal consoles open at the same time.
This is because the TUI interface is displayed in one console, while the debug messages are displayed in another console.
Textual is an example. [Textual](https://github.com/Textualize/textual) is the most popular TUI framework for Python, used to develop apps like [Elia](https://github.com/darrenburns/elia), [Memray](https://github.com/bloomberg/memray), [Parllama](https://github.com/paulrobello/parllama) and [Posting](https://github.com/darrenburns/posting).
The dev mode of Textual requires some special setup on two consoles. You can read about it here:

https://textual.textualize.io/guide/devtools/
https://github.com/Textualize/textual-dev

Currently Aider cannot monitor or display two consoles at the same time, and consequently developing Textual apps with it is impossible. Because the AI needs both the console outputs (the debug logs messages and the TUI snapshots) added to the chat to understand what is going on. This is also somewhat related to this issue: https://github.com/paul-gauthier/aider/issues/912 .
Please add support for displaying and adding to chat multiple consoles output. 

P.S.
Writing tests for Textual is also difficult for the same reason. But you can use a tool like `pytest-textual-snapshot` to handle those UI tests in Aider once you implement the dual console output. Please add support for it. You can read about it here:

https://textual.textualize.io/guide/testing/
https://github.com/Textualize/pytest-textual-snapshot

Thanks! 😊 🙏

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I don't think there is a natural way for aider to support this. Aider's `/run` command simply runs a program captures its stdout/stderr. That won't work with a TUI app at all that uses complex terminal control sequences. 

You need a CLI program you can run that will simply dump the textual console logs and then exit. It doesn't look like `textual console` supports that, as it runs forever printing logs. You may be able to write such a CLI program without too much trouble (maybe even using aider to write it).

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by Emasoft** [comment]
Can you implement a plug-in system for Aider? I would be happy to write a plugin for letting Aider receive the log output from Textual (all I need to do is to adapt the code from here:  https://github.com/Textualize/textual-dev/blob/main/src/textual_dev/client.py ).
