### ISSUE TITLE
[FeatReq] Please add a button to kill the running process without crashing or exiting the chat

### ISSUE THREAD

**Issue by Emasoft** [paul-gauthier/aider#945]
### Issue

Please ad a button to kill the running process without crashing or exiting the chat.
Very often while running a program inside Aider the process hangs or gets into an infinite loop or recursion, and there is no way to kill it without killing the Aider process or closing the terminal. 
Both a graphic button (like those from Textual) and a key shortcut should be provided to do this, because sometimes the keyboard becomes unresponsive when the process hangs.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/usage/commands.html#interrupting-with-control-c

It’s always safe to use Control-C to interrupt aider if it isn’t providing a useful response. The partial response remains in the conversation, so you can refer to it when you reply to the LLM with more information or direction.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by Emasoft** [comment]
Of course the cases I was referring to were those ones when Control-C won't work. As I said, the hang process made the keyboard unresponsive.
