### ISSUE TITLE
authentication_error

### ISSUE THREAD

**Issue by davidmoshal** [paul-gauthier/aider#950]
### Issue

 Trying to understand this error, it occurs even if the api key is set:
 - in .zshrc
 - in .env in the project
 - and with export ANTHROPIC_API_KEY=
 
It does work with OpenAI, ie: `aider --4-turbo` works
 
Macos Sonoma 14.5
aider 0.45.1
repo is private

-----
 
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 1436, in completion
    response = anthropic_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/llms/anthropic.py", line 683, in completion
    raise AnthropicError(
litellm.llms.anthropic.AnthropicError: {"type":"error","error":{"type":"authentication_error","message":"invalid
x-api-key"}}

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It looks like your API key is invalid. Maybe get a new one from the Anthropic website?

You can also run `aider --verbose` to confirm which key it is using, in case you've got multiple configured in various yaml/.env/environment locations.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
