### ISSUE TITLE
Using gemma-2 causes exception

### ISSUE THREAD

**Issue by kim0** [paul-gauthier/aider#954]
### Issue

Used `/model gemini/gemini-gemma-2-27b-it ` which worked

Trying to run anything afterwards caused

```
Unexpected error: litellm.NotFoundError: VertexAIException - b'{\n  "error": {\n    "code": 404,\n    "message": "models/gemini-gemma-2-27b-it is 
not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported 
methods.",\n    "status": "NOT_FOUND"\n  }\n}\n'
```

### Version and model info

Aider v0.45.1
Model: gemini/gemini-gemma-2-27b-it with whole edit format
Git repo: .git with 16 files
Repo-map: disabled

**Comment by kim0** [comment]
@paul-gauthier I believe it was in the `/models` output and auto-completed for me. If there's another way to use `gemma-2` please let me know

**Comment by paul-gauthier** [comment]
The `/models` command searches the litellm list of models, which is crowd sourced. It is not guaranteed to be accurate.

Groq seems to support gemma 2:

https://console.groq.com/docs/models#gemma-2-9b

https://aider.chat/docs/llms/groq.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
