### ISSUE TITLE
Feature Request - Turn chat history into Requirement and Design documents

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#955]
### Issue

I frequently ask aider not to write any code, but instead to suggest design changes and features.
I then lose some of the details as my chat history gets longer.
It would be useful to be able to create and add to design and requirement documents, and have them under version control. Aider could make additions and changes and they would always be available.

I realise I could already do this, but I think that there might be additions to aider that could make this easier
- tags for the chat history
- library of document templates

One workflow might be that after a discussion with aider, I tag the suggestions and right-click or somehow select them for addition to the design docs.

This is much fishing for workflow suggestions as it is a feature request.
Thanks to Paul for aider, it really extends the capabilities of LLMs for coding.

**Comment by avimar** [comment]
Sounds cool, first iterate to have it _write out_ the design docs - and perhaps the API specifications.

Then it can use that piece by piece to write the code.

**Comment by Emasoft** [comment]
I think that this would be too complicated. And any sufficiently accurate project description would easily consume all the context space of the chat. 
The best would be taking the example from Github: you can manage github project with just three things:  
- feature requests (todo)
- bug reports
- tasklist/milestones (those are just a list of the 2 things above: featreq and bugs)  

  
We can just let the user create those with two new aider commands like these:
“/feature <description>” : add a feature request description
“/bug <description>” : add a bug report

Also the AI should be able to create those entries by itself in the /ask mode if the user asks for new features, or if the user report a bug.

Those two kind of entries should also be imported from the github repo issues list, with a command like this:
“/github-sync <repo url>”  

You should also be able to specify if you want just to sync the bugs or the features:
“/github-sync <repo url> issues bugs”

When you need to have a overview of the project progress, you should be able to call a command like:
“/tasklist”

And getting a result like:

| Type    | Description                                            | Reference URL                                      | Status         |
|---------|--------------------------------------------------------|---------------------------------------------------|----------------|
| Feat | Add user authentication feature                        | https://github.com/myproject/issues/45             | 📝 planned     |
| Bug     | Fix crash on startup when configuration is missing     | https://github.com/myproject/issues/32             | ✅ solved      |
| Feat| Implement dark mode for the application                |                                                   | 📝 planned     |
| Bug     | Resolve memory leak in data processing module          | https://github.com/myproject/issues/19             | 🔄 in progress |
| Feat| Add support for exporting data in CSV format           | https://github.com/myproject/issues/52             | 📝 planned     |
| Bug     | Correct typo in user settings description              |                                                   | ✅ solved      |
| Feat | Create an admin dashboard for monitoring activities    |                                                   | 📝 planned     |
| Bug     | Address layout issues on mobile devices                | https://github.com/myproject/issues/27             |  ❌ wontfix |
| Feat | Integrate third-party API for weather updates          |                                                   | 📝 planned     |
| Bug     | Fix broken link in the help documentation              |                                                   | ❌ wontfix     |

**Project Status Summary:**
- 📝 Planned: 5
- ✅ Solved: 2
- ❌ Wontfix: 1
- 🔄 In Progress: 2

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Maybe have aider edit some markdown documents for you as you chat? requirements.md and design.md etc.

**Comment by lockmeister** [comment]
Thanks for the replies. 
I've recently learned about Claude Artifacts, I think this might be close to what I want. At the moment I have Claude open separately to aider. 

I still think it would be nice to incorporate it into aider.
