### ISSUE TITLE
[Question]: Back button?

### ISSUE THREAD

**Issue by BarfingLemurs** [paul-gauthier/aider#969]
### Question

Is there a way to go back to my previous dialog? A regeneration feature might not be useful since aider adopts a temp=0, but I often find myself wanting to backtrack and rephrase the prompt better, without restarting my session.

**Comment by PrashamTrivedi** [comment]
Hi,

Are you asking about getting the prompt you have previously entered in CLI? If yes, you can press up arrow in empty prompt and you can cycle through your prompt history..

**Comment by BarfingLemurs** [comment]
Hi, thanks, it's not that. This when you are 8k tokens in, having already done multiple back-and-forths.

Suppose I feel like the model comprehends things well at 8k. Then, I go off in a tangent chatting with the model until 16k, and now find that it's comprehension is much worse.
I would like to go back to the previous state, without sequencially prompting it back from scratch to 8k.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Not currently. You can use the up arrow and control-r to go back and re-send previous messages.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
