### ISSUE TITLE
Why is aider hitting the API when I'm only managing what files are included?

### ISSUE THREAD

**Issue by glinkot** [paul-gauthier/aider#971]
### Issue

Per the screenshot, I would have thought that listing files, adding/removing them etc would be local operations.  However as we see, it's chatting with the API at each action.  Is that expected behaviour?

![image](https://github.com/user-attachments/assets/06910f17-422a-4cae-b7a0-e76f1adab961)

**Comment by glinkot** [comment]
That wasn't the one I was referring to - it was the /add ones.  

I've redone this with a more constrained set of files and it doesn't exhibit the behaviour.

**Comment by paul-gauthier** [comment]
This has been fixed. The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by glinkot** [comment]
Yes, this is indeed fixed.  Thanks Paul!
