### ISSUE TITLE
Bug - aider edits code even when I ask it not to

### ISSUE THREAD

**Issue by lockmeister** [paul-gauthier/aider#972]
### Issue

When discussing code with aider, I say "do not edit this code" and then proceed with the question. But it frequently edits the code. I'm aware of the --dry-run flag, but I want to have discussions while in a session.

### Version and model info

aider 0.46.1
Claude Sonnet 3.5

**Comment by xeroc** [comment]
Same here.
I would love to be able to just ask questions about the code and have it explained to me by aider and i think with the repo map it has a huge advantage over others doing that (at high cost).

Please allow us to chat with our codebase, that would be awesome!

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider now as an `ask` mode. This doc may be helpful:

https://aider.chat/docs/usage/modes.html

**Comment by xeroc** [comment]
This is brilliant. Thank you so much!

**Comment by lockmeister** [comment]
that's great! Is that new?
