### ISSUE TITLE
[FeatReq] Implement a Plugins system in Aider

### ISSUE THREAD

**Issue by Emasoft** [paul-gauthier/aider#973]
### Issue

Please implement a plug-in system for Aider.
The PLUGINS should be able to simply provide an INPUT or an OUTPUT.
  
An **AIDER INPUT PLUGIN** would be content added to the chat. This would be extremely useful for allowing the AI to receive some custom output or debug data from some library, like HTTP responses, images or socket/connection logs, memory tracing, raw SQL, JSON messages, GUI/TUI screen snapshots, etc. to help the debug process. 
For example, I would be happy to write a plugin for letting Aider receive the log output from [Textual](https://textual.textualize.io/getting_started/). All I need to do is to adapt the code from here:  https://github.com/Textualize/textual-dev/blob/main/src/textual_dev/client.py  
  
An **AIDER OUTPUT PLUGIN** would be a way to execute some code and data in a sandbox to see it running. Something similar to the "Artifacts" generation in the Claude 3.5 chatbot.
  
This would allow people like me to contribute to the project.
Thanks.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The best ways to feed output from other programs into aider are:

1. Use `/run`.
2. Copy & paste the output into the chat.
3. Put the output into a file somehow, and add it to the chat.

I think `/run` is probably most useful for your needs. Simply make a cli program that will output the Textual logs. Then you a `/run` it to add the logs to the aider chat.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
