### ISSUE TITLE
commit message creation `/commit` creates messages with unwanted text

### ISSUE THREAD

**Issue by kenowessels** [paul-gauthier/aider#975]
### Issue

Since the change to the commit message prompt, it does not seem to work properly for me.

I get messages like these running `/commit`:
> feat(foo): add support for bar
>
> The commit message follows the Conventional Commits guidelines:
>
> feat(foo): add support for bar

This happened for multiple commit messages I tried to create.

### Version and model info

Aider v0.47.0
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 13,733 files
Repo-map: using 1024 tokens

AIDER_AUTO_COMMITS=false

**Comment by lightningRalf** [comment]
This just got introduced in 0.47.0.
you can see the prompts here: https://github.com/paul-gauthier/aider/blob/main/aider/prompts.py
Also there was a change in 0.47.1. Maybe try again and report back, or edit the prompt.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The latest 0.47.1 should be better for this.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
