### ISSUE TITLE
Using ![cmd] breaks screen formatting

### ISSUE THREAD

**Issue by lawong888** [paul-gauthier/aider#977]
### Issue

Aider works normally until I start to use ![cmd] and the screen formatting is not rendered correctly:

> /add README.md main.py requirements.txt prompt.txt compliance_cli2.csv
No files matched 'compliance_cli2.csv'. Do you want to create C:\Users\Lawless\AI\variance\calllog6\compliance_cli2.csv
? n
Added C:\Users\Lawless\AI\variance\calllog6\README.md to the chat
Added C:\Users\Lawless\AI\variance\calllog6\prompt.txt to the chat
Added C:\Users\Lawless\AI\variance\calllog6\main.py to the chat
Added C:\Users\Lawless\AI\variance\calllog6\requirements.txt to the chat
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
README.md main.py prompt.txt requirements.txt
> !ls *.csv

test.csv
test1.csv
test2.csv
test4.csv

Add the output to the chat? (y/n/instructions):  n
←[38;2;0;204;0m────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────←[0m
README.md main.py prompt.txt requirements.txt
> /add test2.csv

Added C:\Users\Lawless\AI\variance\calllog6\test2.csv to the chat
←[38;2;0;204;0m────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────←[0m
README.md test2.csv main.py prompt.txt requirements.txt
> /ask I want to generate an extra "qualitative" report in text format from the compliance SN 71 to 91

←[38;2;255;34;34m^C again to exit←[0m
←[38;2;0;204;0m────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────←[0m

### Version and model info

Aider v0.46.1
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 15 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

What OS, shell and terminal are you using? Is the `ls` command set to output special terminal control characters?

This seems to be a problem unique to your local environment.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
