### ISSUE TITLE
feature request: support conventional commit messages

### ISSUE THREAD

**Issue by alexanderkjeldaas** [paul-gauthier/aider#98]
Conventional commit messages are defined [here](https://www.conventionalcommits.org/en/v1.0.0/#summary)

Aider can be compatible with conventional commits while still keeping the information currently in the commit messages.

Using conventional commits means other tooling that checks for conventional commits and uses these to generate for example changelogs, detect changes for semantic versioning and other things, do not need to understand the "unconventional" commit structure.

Conventional commit does not *explicitly* forbid the aider commits, but the typical suggestion is to use types that pass for example commitlint:

 https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional

**Comment by paul-gauthier** [comment]
I agree with the spirit of what you are requesting here. My concern is that people expect commits that are made in the conventional commit format to have been created by humans who thought carefully about what label to apply. 

Aider relies on GPT-3.5 to generate commit messages, and it seems very likely that it will choose the wrong conventional commit labels for some commits. I worry that it's actually worse to provide wrong labels and pretend to be conforming to the spec.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to reopen it or file another issue if there's more you would like to discuss.

**Comment by alexanderkjeldaas** [comment]
Wouldn't it be possible for aider to ask gpt to only classify if it is relatively sure about it?

So instead of saying: classify accourding to conventional commits, ask it to classify if it is relatively certain, otherwise say it doesn't know, and then do not adhere to conventional commits in the commit message.

This should be a standard situation where you want to reduce the false positive rate (wrong classification), and that can be done by increasing the false negative rate (i.e. let gpt classify more commits as "unknown") by asking it to be very certain.

If this "trick" does not work, I understand that it shouldn't be done.
