### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by zenturacp** [paul-gauthier/aider#981]
### Issue

Why are you always version bumping on all major versions released?

Very confusing version scheming :-)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, I'm not sure I understand your question?

**Comment by zenturacp** [comment]
> Thanks for trying aider and filing this issue.
> 
> Sorry, I'm not sure I understand your question?

Never mind, it's just because your commit messages on the current like 0.47.1 just says version bump

![image](https://github.com/user-attachments/assets/ef9e0a78-8bbc-4f43-8ca5-b51306fe5b8a)

The tags for minor versions dont have a descriptive changelog, but the major releases have, so i was under the impression that all was changed was the version number and then a commit - now i see that there is more when i compare from 0.47.0 to 0.47.1, was just wondering. Just close not really important

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
