### ISSUE TITLE
Feature Request: Add support for OpenRouter.

### ISSUE THREAD

**Issue by jechaviz** [paul-gauthier/aider#983]
### Issue

OpenRouter.ai
is an unified interface, OpenAi compatible, for a lot of commercial and opensource models.

**Comment by fantomechess** [comment]
https://aider.chat/docs/llms/openrouter.html
Looks like they have it already.

**Comment by kanishkave** [comment]
<img width="584" alt="image" src="https://github.com/user-attachments/assets/990f0a30-d498-4de7-9c74-05ae07a90f77">
I am not able to find the 405b on openrouter?

**Comment by jechaviz** [comment]
Thank you for the comments.
