### ISSUE TITLE
how to fully setup aider with deepseek coder please help.

### ISSUE THREAD

**Issue by SlySlayer32** [paul-gauthier/aider#985]
### Issue

I have been sitting here for nearly 10 hours trying to setup aider with deepseek api, i can change models i just cant get it to see my deepseek api key

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/llms/deepseek.html

**Comment by lawong888** [comment]
BTW, if you use setx in Windows, the keys won't show up immediately until you close and reopen another terminal.  Check by typing echo %DEEPSEEK_API_KEY% to see if the key is refreshed.

or if you have choco installed, and don't want to close / reopen terminal window,  type:
RefreshEnv cmd

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by BAPO-X** [comment]
try watching this video for the installation:[https://www.youtube.com/watch?v=xcN3Lw0zbp4](url)
