### ISSUE TITLE
Show currently used model

### ISSUE THREAD

**Issue by torson** [paul-gauthier/aider#986]
It would be nice to always see currently used model. 
For example in front of the context files list: 
```
[gpt-4o] src/config.yaml src/server.py
>
```

Or in front of the tokens status after every LLM response : 
```
[gpt-4o] Tokens: 11,740 sent, 1,159 received. Cost: $0.08 request, $0.08 session.
```

I frequently change the model, use a big one on complex tasks and lighter cheaper one otherwise , but loose track of which one is being used so I need to look up the command history and sometimes just forgetting to do that.

**Comment by ophoria** [comment]
+1

**Comment by bluegithupu** [comment]
+1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The latest aider will show the model name when you do `/tokens`:

```
> /tokens

Approximate context window usage for claude-3-5-sonnet-20240620, in tokens:

$ 0.0034    1,131 system messages
$ 0.0271    9,022 repository map  use --map-tokens to resize
==================
$ 0.0305   10,153 tokens total
          189,847 tokens remaining in context window
          200,000 tokens max context window size
```

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I worry about putting it in front of the prompt, because it can be very long. Eg: `openrouter/openai/claude-3-5-sonnet`.

**Comment by torson** [comment]
Yes, having the active model name under /tokens is also one way. It's not always there in front of you, but better than scrolling up the history . Thanks!
