### ISSUE TITLE
Unable to use Azure based GPT-4o models

### ISSUE THREAD

**Issue by ferozkhan-zycus** [paul-gauthier/aider#988]
### Issue

As per the help documentation, we need to set --4o flag for GPT-4o models. But for Azure based GPT-4o models, when we set 4o flag in Aider command, it expects OpenAI details rather than considering Azure specific details. If we don't set 4o flag, it seems to put token limit of 32K when processing large files. do we have a reference implementation to use Azure based GPT-4o models? that would be very useful. Attaching the working .env file and also the error screenshot.
![env](https://github.com/user-attachments/assets/f9572a61-c824-428c-b5f3-6e38d708a058)
![aider-command-erro](https://github.com/user-attachments/assets/8968dc18-256d-4ab9-97ec-2c39ae76c855)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/llms/azure.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
