### ISSUE TITLE
Should ignore space(s) in front of /in-chat commands 

### ISSUE THREAD

**Issue by lawong888** [paul-gauthier/aider#989]
### Issue

/in-chat commands are great but if I accidentally added space(s) in front of the / commands, the application passes it to the LLM and waste some tokens giving some random answers.   It would be good if those leading spaces were ignored (stripped) when encountering a "/"as the first character in the command line?

### Version and model info

Aider v0.47.1
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model claude-3-haiku-20240307
Git repo: .git with 15 files
Repo-map: using 1024 tokens

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I think there's a pretty strong argument to keep things the way they are. This way you can start a chat message with slash, as long as you put some whitespace in front of it.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.
