### ISSUE TITLE
Tab filename completion causes aider to hang 

### ISSUE THREAD

**Issue by tom-doerr** [paul-gauthier/aider#995]
### Issue

If I tab the filename gets filled out, but the name is surrounded by `  characters. This causes aider to hang and I need to start a new session. 
![image](https://github.com/user-attachments/assets/bee8472e-9fc6-4ba2-beb3-4fa778807e8e)
![image](https://github.com/user-attachments/assets/c60148f4-0eeb-4eba-88a5-f43521dbb914)

### Version and model info

❯ pip freeze | grep aider
aider-chat==0.47.1
 ~/gi/aider_test_project  main ⇡13 !2           ✔  2   16:08:27 

**Comment by tom-doerr** [comment]
Have the issue in kitty terminal as well as in the gnome terminal

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It seems like perhaps you are using a terminal that doesn't support all the features aider needs for pretty output. You could try running aider `--no-pretty` and see if that helps?

**Comment by paul-gauthier** [comment]
The error "WARNING: your terminal doesn't support cursor position requests (CPR)" indicates there is a problem with your terminal not being capable.

But CPR is fairly widely supported, and should be provided by Gnome.

**Comment by tom-doerr** [comment]
Yes should also be supported by Kitty. Same issue with the `--no-pretty` flag:
![image](https://github.com/user-attachments/assets/d5697676-e23d-46b2-8ebf-a925ddfb2b41)

Though it's not urgent, I'll just type out the filenames to avoid the issue

**Comment by paul-gauthier** [comment]
Are you running aider from within a sub-terminal of some kind? Like running emacs in your terminal and launching an emacs terminal window inside that with aider?

**Comment by paul-gauthier** [comment]
Also, what does `/run echo $TERM` show you?

**Comment by tom-doerr** [comment]
I'm starting it from Zsh which might be started from bash (Not quite sure how I configured it). Not using emacs, tmux or screen.
![image](https://github.com/user-attachments/assets/c78fd661-a83d-49a9-9b67-69aed705c79d)

**Comment by tom-doerr** [comment]
Same result:
![image](https://github.com/user-attachments/assets/3759e4d4-7a73-413e-b41c-e577d3d306dc)

**Comment by paul-gauthier** [comment]
This is really puzzling.

What does `tput u6` output for you from the command line? What does `/run tput u6` output?

Does `tput cup 5 10 ; echo Hello` jump to row 5, column 10 and print "Hello" there?

As best I can tell, something is broken in your terminal environment somehow.

**Comment by tom-doerr** [comment]
![image](https://github.com/user-attachments/assets/08ef619e-05d6-418e-8af4-ea5b76788821)
![image](https://github.com/user-attachments/assets/329b82a6-636b-4d86-83b7-79dfca6e013a)
```
❯ 
❯ 
❯ tput u6
%d;%dR%                                                                        ❯ aider --sonnet --vim
Model claude-3-5-sonnet-20240620: Missing these environment variables:
- ANTHROPIC_API_KEY
For more info, see: https://aider.chat/docs/llms/warnings.html

Model claude-3-haiku-20240307: Missing these environment variables:
- ANTHROPIC_API_KEY
For more info, see: https://aider.chat/docs/llms/warnings.html

Aider v0.48.1
Models: claude-3-5-sonnet-20240620 with diff edit format, weak model 
claude-3-haiku-20240307
Git repo: .git with 12 files
Repo-map: using 1024 tokens
Use /help <question> for help, run "aider --help" to see cmd line args
───────────────────────────────────────────────────────────────────────────────
> /run tput u6                                                                 

%d;%dR
Add the output to the chat? (y/n/instructions):  y

```
![image](https://github.com/user-attachments/assets/56fe0d55-65ab-4fb7-bf32-bf2d7eec471a)

Something being broken on my end sounds plausible.

**Comment by paul-gauthier** [comment]
I just did a fresh install of kitty on my Mac, and I am not seeing any errors. Makes me think something has gotten broken in your terminfo/termcap/environment?

<img width="635" alt="2024-08-12_14-22-32" src="https://github.com/user-attachments/assets/9f280929-5759-4191-ad85-1158e2796763">

**Comment by tom-doerr** [comment]
Yeah that seems likely. Should we just close this? It's not a major issue anyway
